snode.c: express::RootRoute Class Reference
express::RootRoute Class Reference
#include <RootRoute.h>
Public Member Functions
RootRoute ()=default
Route & use (const RootRoute &rootRoute)
Route & use (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & all (const RootRoute &rootRoute)
Route & all (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & get (const RootRoute &rootRoute)
Route & get (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & put (const RootRoute &rootRoute)
Route & put (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & post (const RootRoute &rootRoute)
Route & post (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & del (const RootRoute &rootRoute)
Route & del (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & connect (const RootRoute &rootRoute)
Route & connect (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & options (const RootRoute &rootRoute)
Route & options (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & trace (const RootRoute &rootRoute)
Route & trace (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & patch (const RootRoute &rootRoute)
Route & patch (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & head (const RootRoute &rootRoute)
Route & head (const std::string &relativeMountPath, const RootRoute &rootRoute)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Public Member Functions inherited from express::Route
Route (const std::string &method, const std::string &relativeMountPath, const std::shared_ptr< Dispatcher > &dispatcher)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Protected Member Functions
void dispatch (Request &req, Response &res)
void dispatch (Controller &&state)
void dispatch (Controller &state)
std::shared_ptr< dispatcher::RouterDispatcher > getDispatcher () const
std::list< Route > & routes ()
Protected Member Functions inherited from express::Route
Route ()
bool dispatch (Controller &state)
bool dispatch (Controller &state, const std::string &parentMountPath)
bool dispatchNext (Controller &state, const std::string &parentMountPath)
Friends
class Route
class Controller
template<typename Server >
class WebAppT
Additional Inherited Members
Protected Attributes inherited from express::Route
MountPoint mountPoint
std::shared_ptr< Dispatcher > dispatcher
Detailed Description
Definition at line 59 of file RootRoute.h.
Constructor & Destructor Documentation
RootRoute()
express::RootRoute::RootRoute () default
Member Function Documentation
all() [1/6]
Route & express::RootRoute::all (const RootRoute & rootRoute)
Definition at line 81 of file RootRoute.cpp.
all() [2/6]
Route & express::RootRoute::all (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 81 of file RootRoute.cpp.
all() [3/6]
Route & express::RootRoute::all (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 81 of file RootRoute.cpp.
all() [4/6]
Route & express::RootRoute::all (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 81 of file RootRoute.cpp.
all() [5/6]
Route & express::RootRoute::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 81 of file RootRoute.cpp.
all() [6/6]
Route & express::RootRoute::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 81 of file RootRoute.cpp.
connect() [1/6]
Route & express::RootRoute::connect (const RootRoute & rootRoute)
Definition at line 86 of file RootRoute.cpp.
connect() [2/6]
Route & express::RootRoute::connect (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 86 of file RootRoute.cpp.
connect() [3/6]
Route & express::RootRoute::connect (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 86 of file RootRoute.cpp.
connect() [4/6]
Route & express::RootRoute::connect (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 86 of file RootRoute.cpp.
connect() [5/6]
Route & express::RootRoute::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 86 of file RootRoute.cpp.
connect() [6/6]
Route & express::RootRoute::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 86 of file RootRoute.cpp.
del() [1/6]
Route & express::RootRoute::del (const RootRoute & rootRoute)
Definition at line 85 of file RootRoute.cpp.
del() [2/6]
Route & express::RootRoute::del (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 85 of file RootRoute.cpp.
del() [3/6]
Route & express::RootRoute::del (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 85 of file RootRoute.cpp.
del() [4/6]
Route & express::RootRoute::del (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 85 of file RootRoute.cpp.
del() [5/6]
Route & express::RootRoute::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 85 of file RootRoute.cpp.
del() [6/6]
Route & express::RootRoute::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 85 of file RootRoute.cpp.
dispatch() [1/3]
void express::RootRoute::dispatch (Controller && state) protected
Definition at line 68 of file RootRoute.cpp.
{
         state.setRootRoute(this);
         dispatch(state);
     }
References dispatch().
dispatch() [2/3]
void express::RootRoute::dispatch (Controller & state) protected
Definition at line 74 of file RootRoute.cpp.
{
         if (!Route::dispatch(state, "")) {
             state.getResponse()->sendStatus(404);
         }
     }
References express::Route::dispatch(), express::Controller::getResponse(), and express::Response::sendStatus().
dispatch() [3/3]
void express::RootRoute::dispatch (Request & req, Response & res) protected
Definition at line 64 of file RootRoute.cpp.
{
         dispatch(Controller(req, res));
     }
References Controller.
Referenced by dispatch(), and express::Controller::next().
get() [1/6]
Route & express::RootRoute::get (const RootRoute & rootRoute)
Definition at line 82 of file RootRoute.cpp.
get() [2/6]
Route & express::RootRoute::get (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 82 of file RootRoute.cpp.
get() [3/6]
Route & express::RootRoute::get (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 82 of file RootRoute.cpp.
get() [4/6]
Route & express::RootRoute::get (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 82 of file RootRoute.cpp.
get() [5/6]
Route & express::RootRoute::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 82 of file RootRoute.cpp.
get() [6/6]
Route & express::RootRoute::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 82 of file RootRoute.cpp.
getDispatcher()
std::shared_ptr< dispatcher::RouterDispatcher > express::RootRoute::getDispatcher () const protected
Definition at line 56 of file RootRoute.cpp.
{
         return std::dynamic_pointer_cast<dispatcher::RouterDispatcher>(dispatcher);
     }
References express::Route::dispatcher.
head() [1/6]
Route & express::RootRoute::head (const RootRoute & rootRoute)
Definition at line 90 of file RootRoute.cpp.
head() [2/6]
Route & express::RootRoute::head (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 90 of file RootRoute.cpp.
head() [3/6]
Route & express::RootRoute::head (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 90 of file RootRoute.cpp.
head() [4/6]
Route & express::RootRoute::head (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 90 of file RootRoute.cpp.
head() [5/6]
Route & express::RootRoute::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 90 of file RootRoute.cpp.
head() [6/6]
Route & express::RootRoute::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 90 of file RootRoute.cpp.
options() [1/6]
Route & express::RootRoute::options (const RootRoute & rootRoute)
Definition at line 87 of file RootRoute.cpp.
options() [2/6]
Route & express::RootRoute::options (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 87 of file RootRoute.cpp.
options() [3/6]
Route & express::RootRoute::options (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 87 of file RootRoute.cpp.
options() [4/6]
Route & express::RootRoute::options (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 87 of file RootRoute.cpp.
options() [5/6]
Route & express::RootRoute::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 87 of file RootRoute.cpp.
options() [6/6]
Route & express::RootRoute::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 87 of file RootRoute.cpp.
patch() [1/6]
Route & express::RootRoute::patch (const RootRoute & rootRoute)
Definition at line 89 of file RootRoute.cpp.
patch() [2/6]
Route & express::RootRoute::patch (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 89 of file RootRoute.cpp.
patch() [3/6]
Route & express::RootRoute::patch (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 89 of file RootRoute.cpp.
patch() [4/6]
Route & express::RootRoute::patch (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 89 of file RootRoute.cpp.
patch() [5/6]
Route & express::RootRoute::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 89 of file RootRoute.cpp.
patch() [6/6]
Route & express::RootRoute::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 89 of file RootRoute.cpp.
post() [1/6]
Route & express::RootRoute::post (const RootRoute & rootRoute)
Definition at line 84 of file RootRoute.cpp.
post() [2/6]
Route & express::RootRoute::post (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 84 of file RootRoute.cpp.
post() [3/6]
Route & express::RootRoute::post (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 84 of file RootRoute.cpp.
post() [4/6]
Route & express::RootRoute::post (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 84 of file RootRoute.cpp.
post() [5/6]
Route & express::RootRoute::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 84 of file RootRoute.cpp.
post() [6/6]
Route & express::RootRoute::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 84 of file RootRoute.cpp.
put() [1/6]
Route & express::RootRoute::put (const RootRoute & rootRoute)
Definition at line 83 of file RootRoute.cpp.
put() [2/6]
Route & express::RootRoute::put (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 83 of file RootRoute.cpp.
put() [3/6]
Route & express::RootRoute::put (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 83 of file RootRoute.cpp.
put() [4/6]
Route & express::RootRoute::put (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 83 of file RootRoute.cpp.
put() [5/6]
Route & express::RootRoute::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 83 of file RootRoute.cpp.
put() [6/6]
Route & express::RootRoute::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 83 of file RootRoute.cpp.
routes()
std::list< Route > & express::RootRoute::routes () protected
Definition at line 60 of file RootRoute.cpp.
{
         return std::dynamic_pointer_cast<dispatcher::RouterDispatcher>(dispatcher)->getRoutes();
     }
References express::Route::dispatcher.
trace() [1/6]
Route & express::RootRoute::trace (const RootRoute & rootRoute)
Definition at line 88 of file RootRoute.cpp.
trace() [2/6]
Route & express::RootRoute::trace (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 88 of file RootRoute.cpp.
trace() [3/6]
Route & express::RootRoute::trace (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 88 of file RootRoute.cpp.
trace() [4/6]
Route & express::RootRoute::trace (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 88 of file RootRoute.cpp.
trace() [5/6]
Route & express::RootRoute::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 88 of file RootRoute.cpp.
trace() [6/6]
Route & express::RootRoute::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 88 of file RootRoute.cpp.
use() [1/6]
Route & express::RootRoute::use (const RootRoute & rootRoute)
Definition at line 80 of file RootRoute.cpp.
use() [2/6]
Route & express::RootRoute::use (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 80 of file RootRoute.cpp.
use() [3/6]
Route & express::RootRoute::use (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 80 of file RootRoute.cpp.
use() [4/6]
Route & express::RootRoute::use (const std::string & relativeMountPath, const RootRoute & rootRoute)
Definition at line 80 of file RootRoute.cpp.
use() [5/6]
Route & express::RootRoute::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 80 of file RootRoute.cpp.
use() [6/6]
Route & express::RootRoute::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 80 of file RootRoute.cpp.
Friends And Related Function Documentation
Controller
friend class Controller friend
Definition at line 86 of file RootRoute.h.
Referenced by dispatch().
Route
friend class Route friend
Definition at line 85 of file RootRoute.h.
WebAppT
template<typename Server > friend class WebAppT friend
Definition at line 89 of file RootRoute.h.
The documentation for this class was generated from the following files:
express/RootRoute.h
express/RootRoute.cpp