snode.c: net::ConfigRemote< SocketAddressT > Class Template Reference
net::ConfigRemote< SocketAddressT > Class Template Reference abstract
#include <ConfigRemote.h>
Public Member Functions
const SocketAddress & getRemoteAddress () const
void setRemoteAddress (const SocketAddress &remoteAddress) const
Protected Types
using SocketAddress = SocketAddressT
Protected Member Functions
ConfigRemote ()=default
virtual ~ConfigRemote ()=default
Private Member Functions
virtual SocketAddress getAddress () const =0
Private Attributes
SocketAddress remoteAddress
bool initialized = false
Detailed Description
template<typename SocketAddressT>
class net::ConfigRemote< SocketAddressT >
Definition at line 31 of file ConfigRemote.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::ConfigRemote< SocketAddressT >::SocketAddress = SocketAddressT protected
Definition at line 36 of file ConfigRemote.h.
Constructor & Destructor Documentation
ConfigRemote()
template<typename SocketAddressT > net::ConfigRemote< SocketAddressT >::ConfigRemote () protected default
~ConfigRemote()
template<typename SocketAddressT > virtual net::ConfigRemote< SocketAddressT >::~ConfigRemote () protected virtual default
Member Function Documentation
getAddress()
template<typename SocketAddressT > virtual SocketAddress net::ConfigRemote< SocketAddressT >::getAddress () const private pure virtual
Implemented in net::un::ConfigRemote, net::rf::ConfigRemote, net::l2::ConfigRemote, net::in6::ConfigRemote, and net::in::ConfigRemote.
Referenced by net::ConfigRemote< SocketAddressT >::getRemoteAddress().
getRemoteAddress()
template<typename SocketAddressT > const SocketAddress& net::ConfigRemote< SocketAddressT >::getRemoteAddress () const inline
Definition at line 39 of file ConfigRemote.h.
{
             if (!initialized) {
                 utils::Config::instance().parse(true); // Try command line parsing in case Address is not initialized using setLocalAddress
                 remoteAddress = getAddress();
                 initialized = true;
             }
             return remoteAddress;
         }
References net::ConfigRemote< SocketAddressT >::getAddress(), net::ConfigRemote< SocketAddressT >::initialized, utils::Config::instance(), utils::Config::parse(), and net::ConfigRemote< SocketAddressT >::remoteAddress.
setRemoteAddress()
template<typename SocketAddressT > void net::ConfigRemote< SocketAddressT >::setRemoteAddress (const SocketAddress & remoteAddress) const inline
Definition at line 50 of file ConfigRemote.h.
{
             this->remoteAddress = remoteAddress;
             this->initialized = true;
         }
References net::ConfigRemote< SocketAddressT >::initialized, and net::ConfigRemote< SocketAddressT >::remoteAddress.
Member Data Documentation
initialized
template<typename SocketAddressT > bool net::ConfigRemote< SocketAddressT >::initialized = false mutable private
Definition at line 59 of file ConfigRemote.h.
Referenced by net::ConfigRemote< SocketAddressT >::getRemoteAddress(), and net::ConfigRemote< SocketAddressT >::setRemoteAddress().
remoteAddress
template<typename SocketAddressT > SocketAddress net::ConfigRemote< SocketAddressT >::remoteAddress mutable private
Definition at line 58 of file ConfigRemote.h.
Referenced by net::ConfigRemote< SocketAddressT >::getRemoteAddress(), and net::ConfigRemote< SocketAddressT >::setRemoteAddress().
The documentation for this class was generated from the following file:
net/ConfigRemote.h