snode.c: express::middleware::BasicAuthentication Class Reference
express::middleware::BasicAuthentication Class Reference
#include <BasicAuthentication.h>
Protected Member Functions
BasicAuthentication (const std::string &userName, const std::string &password, const std::string &realm)
Static Protected Member Functions
static class BasicAuthentication & instance (const std::string &userName, const std::string &password, const std::string &realm)
Private Attributes
std::string userName
std::string password
std::string realm
std::string credentials
Friends
class BasicAuthentication & BasicAuthentication (const std::string &userName, const std::string &password, const std::string &realm)
Additional Inherited Members
Public Member Functions inherited from express::Router
Router ()
Route & use (const Router &router)
Route & use (const std::string &relativeMountPath, const Router &router)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & all (const Router &router)
Route & all (const std::string &relativeMountPath, const Router &router)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & get (const Router &router)
Route & get (const std::string &relativeMountPath, const Router &router)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & put (const Router &router)
Route & put (const std::string &relativeMountPath, const Router &router)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & post (const Router &router)
Route & post (const std::string &relativeMountPath, const Router &router)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & del (const Router &router)
Route & del (const std::string &relativeMountPath, const Router &router)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & connect (const Router &router)
Route & connect (const std::string &relativeMountPath, const Router &router)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & options (const Router &router)
Route & options (const std::string &relativeMountPath, const Router &router)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & trace (const Router &router)
Route & trace (const std::string &relativeMountPath, const Router &router)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & patch (const Router &router)
Route & patch (const std::string &relativeMountPath, const Router &router)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & head (const Router &router)
Route & head (const std::string &relativeMountPath, const Router &router)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Protected Attributes inherited from express::Router
std::shared_ptr< RootRoute > rootRoute = nullptr
Detailed Description
Definition at line 34 of file BasicAuthentication.h.
Constructor & Destructor Documentation
BasicAuthentication()
express::middleware::BasicAuthentication::BasicAuthentication (const std::string & userName, const std::string & password, const std::string & realm) protected
Definition at line 36 of file BasicAuthentication.cpp.
         : userName(userName)
         , password(password)
         , realm(realm) {
         std::string userNamePassword = userName + ":" + password;
         credentials = base64::base64_encode(reinterpret_cast<unsigned char*>(userNamePassword.data()), userNamePassword.length());
         use([realm, this] MIDDLEWARE(req, res, next) {
             std::string authCredentials = httputils::str_split(req.get("Authorization"), ' ').second;
             if (authCredentials == credentials) {
                 next();
             } else {
                 if (authCredentials.empty()) {
                     res.set("WWW-Authenticate", "Basic realm=\"" + realm + "\"");
                 }
                 res.sendStatus(401);
             }
         });
     }
References base64::base64_encode(), credentials, MIDDLEWARE, password, realm, httputils::str_split(), express::Router::use(), and userName.
Referenced by instance().
Member Function Documentation
instance()
class BasicAuthentication & express::middleware::BasicAuthentication::instance (const std::string & userName, const std::string & password, const std::string & realm) static protected
Definition at line 58 of file BasicAuthentication.cpp.
{
         // Keep the created authentication middleware alive
         static std::list<std::shared_ptr<class BasicAuthentication>> basicAuthentications;
         BasicAuthentication* basicAuthentication = new BasicAuthentication(userName, password, realm);
         basicAuthentications.push_back(std::shared_ptr<BasicAuthentication>(basicAuthentication));
         return *basicAuthentication;
     }
References BasicAuthentication(), password, realm, and userName.
Referenced by BasicAuthentication.
Friends And Related Function Documentation
BasicAuthentication
class BasicAuthentication& BasicAuthentication (const std::string & userName, const std::string & password, const std::string & realm) friend
Definition at line 68 of file BasicAuthentication.cpp.
{
         return BasicAuthentication::instance(userName, password, realm);
     }
References instance().
Member Data Documentation
credentials
std::string express::middleware::BasicAuthentication::credentials private
Definition at line 44 of file BasicAuthentication.h.
Referenced by BasicAuthentication().
password
std::string express::middleware::BasicAuthentication::password private
Definition at line 42 of file BasicAuthentication.h.
Referenced by BasicAuthentication(), and instance().
realm
std::string express::middleware::BasicAuthentication::realm private
Definition at line 43 of file BasicAuthentication.h.
Referenced by BasicAuthentication(), and instance().
userName
std::string express::middleware::BasicAuthentication::userName private
Definition at line 41 of file BasicAuthentication.h.
Referenced by BasicAuthentication(), and instance().
The documentation for this class was generated from the following files:
express/middleware/BasicAuthentication.h
express/middleware/BasicAuthentication.cpp