snode.c: web::websocket::server::GroupsManager Class Reference
web::websocket::server::GroupsManager Class Reference
#include <GroupsManager.h>
Public Member Functions
void subscribe (SubProtocol *subProtocol, std::string group="")
void unsubscribe (SubProtocol *subProtocol)
void sendBroadcast (const std::string &group, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcast (const std::string &group, const std::string &message, const SubProtocol *excludedClient)
void sendBroadcastStart (const std::string &group, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcastStart (const std::string &group, const std::string &message, const SubProtocol *excludedClient)
void sendBroadcastFrame (const std::string &group, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcastFrame (const std::string &group, const std::string &message, const SubProtocol *excludedClient)
void sendBroadcastEnd (const std::string &group, const char *message, std::size_t messageLength, const SubProtocol *excludedClient)
void sendBroadcastEnd (const std::string &group, const std::string &message, const SubProtocol *excludedClient)
void forEachClient (const std::string &group, const std::function< void(SubProtocol *)> &sendToClient, const SubProtocol *excludedClient)
Static Public Member Functions
static GroupsManager * instance ()
Public Attributes
std::map< std::string, std::set< SubProtocol * > > groups
Static Public Attributes
static GroupsManager * groupsManager = nullptr
Private Member Functions
GroupsManager ()=default
GroupsManager (const GroupsManager &)=delete
~GroupsManager ()
GroupsManager & operator= (const GroupsManager &)=delete
Detailed Description
Definition at line 38 of file GroupsManager.h.
Constructor & Destructor Documentation
GroupsManager() [1/2]
web::websocket::server::GroupsManager::GroupsManager () private default
Referenced by instance().
GroupsManager() [2/2]
web::websocket::server::GroupsManager::GroupsManager (const GroupsManager &) private delete
~GroupsManager()
web::websocket::server::GroupsManager::~GroupsManager () private
Definition at line 31 of file GroupsManager.cpp.
{
         GroupsManager::groupsManager = nullptr;
     }
References groupsManager.
Member Function Documentation
forEachClient()
void web::websocket::server::GroupsManager::forEachClient (const std::string & group, const std::function< void(SubProtocol *)> & sendToClient, const SubProtocol * excludedClient)
Definition at line 144 of file GroupsManager.cpp.
{
         if (groups.contains(channel)) {
             for (SubProtocol* client : groups[channel]) {
                 if (client != excludedClient) {
                     sendToClient(client);
                 }
             }
         }
     }
References groups.
Referenced by web::websocket::server::SubProtocol::forEachClient().
instance()
GroupsManager * web::websocket::server::GroupsManager::instance () static
Definition at line 35 of file GroupsManager.cpp.
{
         return GroupsManager::groupsManager == nullptr ? GroupsManager::groupsManager = new GroupsManager() : GroupsManager::groupsManager;
     }
References GroupsManager(), and groupsManager.
Referenced by web::websocket::server::SubProtocol::forEachClient(), web::websocket::server::SubProtocol::sendBroadcast(), web::websocket::server::SubProtocol::sendBroadcastEnd(), web::websocket::server::SubProtocol::sendBroadcastFrame(), web::websocket::server::SubProtocol::sendBroadcastStart(), web::websocket::server::SubProtocol::SubProtocol(), web::websocket::server::SubProtocol::subscribe(), and web::websocket::server::SubProtocol::~SubProtocol().
operator=()
GroupsManager& web::websocket::server::GroupsManager::operator= (const GroupsManager &) private delete
sendBroadcast() [1/2]
void web::websocket::server::GroupsManager::sendBroadcast (const std::string & group, const char * message, std::size_t messageLength, const SubProtocol * excludedClient)
Definition at line 70 of file GroupsManager.cpp.
{
         if (groups.contains(channel)) {
             for (SubProtocol* client : groups[channel]) {
                 if (client != excludedClient) {
                     client->sendMessage(message, messageLength);
                 }
             }
         }
     }
References groups.
Referenced by web::websocket::server::SubProtocol::sendBroadcast().
sendBroadcast() [2/2]
void web::websocket::server::GroupsManager::sendBroadcast (const std::string & group, const std::string & message, const SubProtocol * excludedClient)
Definition at line 83 of file GroupsManager.cpp.
{
         if (groups.contains(channel)) {
             for (SubProtocol* client : groups[channel]) {
                 if (client != excludedClient) {
                     client->sendMessage(message);
                 }
             }
         }
     }
References groups.
sendBroadcastEnd() [1/2]
void web::websocket::server::GroupsManager::sendBroadcastEnd (const std::string & group, const char * message, std::size_t messageLength, const SubProtocol * excludedClient)
Definition at line 127 of file GroupsManager.cpp.
{
         if (groups.contains(channel)) {
             for (SubProtocol* client : groups[channel]) {
                 if (client != excludedClient) {
                     client->sendMessageEnd(message, messageLength);
                 }
             }
         }
     }
References groups.
Referenced by web::websocket::server::SubProtocol::sendBroadcastEnd(), and sendBroadcastEnd().
sendBroadcastEnd() [2/2]
void web::websocket::server::GroupsManager::sendBroadcastEnd (const std::string & group, const std::string & message, const SubProtocol * excludedClient)
Definition at line 140 of file GroupsManager.cpp.
{
         sendBroadcastEnd(channel, message.data(), message.length(), excludedClient);
     }
References sendBroadcastEnd().
sendBroadcastFrame() [1/2]
void web::websocket::server::GroupsManager::sendBroadcastFrame (const std::string & group, const char * message, std::size_t messageLength, const SubProtocol * excludedClient)
Definition at line 110 of file GroupsManager.cpp.
{
         if (groups.contains(channel)) {
             for (SubProtocol* client : groups[channel]) {
                 if (client != excludedClient) {
                     client->sendMessageFrame(message, messageLength);
                 }
             }
         }
     }
References groups.
Referenced by web::websocket::server::SubProtocol::sendBroadcastFrame(), and sendBroadcastFrame().
sendBroadcastFrame() [2/2]
void web::websocket::server::GroupsManager::sendBroadcastFrame (const std::string & group, const std::string & message, const SubProtocol * excludedClient)
Definition at line 123 of file GroupsManager.cpp.
{
         sendBroadcastFrame(channel, message.data(), message.length(), excludedClient);
     }
References sendBroadcastFrame().
sendBroadcastStart() [1/2]
void web::websocket::server::GroupsManager::sendBroadcastStart (const std::string & group, const char * message, std::size_t messageLength, const SubProtocol * excludedClient)
Definition at line 93 of file GroupsManager.cpp.
{
         if (groups.contains(channel)) {
             for (SubProtocol* client : groups[channel]) {
                 if (client != excludedClient) {
                     client->sendMessageStart(message, messageLength);
                 }
             }
         }
     }
References groups.
Referenced by web::websocket::server::SubProtocol::sendBroadcastStart(), and sendBroadcastStart().
sendBroadcastStart() [2/2]
void web::websocket::server::GroupsManager::sendBroadcastStart (const std::string & group, const std::string & message, const SubProtocol * excludedClient)
Definition at line 106 of file GroupsManager.cpp.
{
         sendBroadcastStart(channel, message.data(), message.length(), excludedClient);
     }
References sendBroadcastStart().
subscribe()
void web::websocket::server::GroupsManager::subscribe (SubProtocol * subProtocol, std::string group = "")
Definition at line 39 of file GroupsManager.cpp.
{
         if (channel.empty()) {
             channel = subProtocol->getName();
         }
         if (subProtocol->group != channel) {
             std::string newChannel = subProtocol->getName() + "/" + channel;
             groups[newChannel].insert(subProtocol);
             if (!subProtocol->group.empty()) {
                 unsubscribe(subProtocol);
             }
             subProtocol->group = newChannel;
         }
     }
References web::websocket::SubProtocol< SocketContextUpgradeT >::getName(), web::websocket::server::SubProtocol::group, groups, and unsubscribe().
Referenced by web::websocket::server::SubProtocol::SubProtocol(), and web::websocket::server::SubProtocol::subscribe().
unsubscribe()
void web::websocket::server::GroupsManager::unsubscribe (SubProtocol * subProtocol)
Definition at line 57 of file GroupsManager.cpp.
{
         if (groups.contains(subProtocol->group)) {
             groups[subProtocol->group].erase(subProtocol);
             if (groups[subProtocol->group].size() == 0) {
                 groups.erase(subProtocol->group);
                 if (groups.size() == 0) {
                     delete this;
                 }
             }
         }
     }
References web::websocket::server::SubProtocol::group, and groups.
Referenced by subscribe(), and web::websocket::server::SubProtocol::~SubProtocol().
Member Data Documentation
groups
std::map<std::string, std::set<SubProtocol*> > web::websocket::server::GroupsManager::groups
Definition at line 72 of file GroupsManager.h.
Referenced by forEachClient(), sendBroadcast(), sendBroadcastEnd(), sendBroadcastFrame(), sendBroadcastStart(), subscribe(), and unsubscribe().
groupsManager
GroupsManager * web::websocket::server::GroupsManager::groupsManager = nullptr static
Definition at line 70 of file GroupsManager.h.
Referenced by instance(), and ~GroupsManager().
The documentation for this class was generated from the following files:
web/websocket/server/GroupsManager.h
web/websocket/server/GroupsManager.cpp