snode.c: database::mariadb::MariaDBCommand Class Reference
database::mariadb::MariaDBCommand Class Reference abstract
#include <MariaDBCommand.h>
Public Member Functions
MariaDBCommand (const std::string &name, const std::function< void(const std::string &, unsigned int)> &onError)
virtual ~MariaDBCommand ()=default
const std::string & commandName ()
int commandStart (MYSQL *mysql, const utils::Timeval &currentTime)
void setMariaDBConnection (MariaDBConnection *mariaDBConnection)
virtual int commandContinue (int status)=0
virtual bool commandCompleted ()=0
virtual void commandError (const std::string &errorString, unsigned int errorNumber)=0
virtual std::string commandInfo ()=0
Public Attributes
const std::function< void(const std::string &, unsigned int)> onError
Protected Attributes
std::string name
MariaDBConnection * mariaDBConnection = nullptr
MYSQL * mysql = nullptr
utils::Timeval startTime = 0
Private Member Functions
virtual int commandStart ()=0
Detailed Description
Definition at line 40 of file MariaDBCommand.h.
Constructor & Destructor Documentation
MariaDBCommand()
database::mariadb::MariaDBCommand::MariaDBCommand (const std::string & name, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 28 of file MariaDBCommand.cpp.
         : name(name)
         , onError(onError) {
     }
~MariaDBCommand()
virtual database::mariadb::MariaDBCommand::~MariaDBCommand () virtual default
Member Function Documentation
commandCompleted()
virtual bool database::mariadb::MariaDBCommand::commandCompleted () pure virtual
Implemented in database::mariadb::commands::sync::MariaDBUseResultCommand, database::mariadb::commands::sync::MariaDBFieldCountCommand, database::mariadb::commands::sync::MariaDBAffectedRowsCommand, database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBCommitCommand, and database::mariadb::commands::async::MariaDBAutoCommitCommand.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), and database::mariadb::MariaDBConnection::execute_sync().
commandContinue()
virtual int database::mariadb::MariaDBCommand::commandContinue (int status) pure virtual
Implemented in database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBCommitCommand, database::mariadb::commands::async::MariaDBAutoCommitCommand, and database::mariadb::MariaDBCommandSync.
Referenced by database::mariadb::MariaDBConnection::commandContinue().
commandError()
virtual void database::mariadb::MariaDBCommand::commandError (const std::string & errorString, unsigned int errorNumber) pure virtual
Implemented in database::mariadb::commands::sync::MariaDBUseResultCommand, database::mariadb::commands::sync::MariaDBFieldCountCommand, database::mariadb::commands::sync::MariaDBAffectedRowsCommand, database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBCommitCommand, and database::mariadb::commands::async::MariaDBAutoCommitCommand.
Referenced by database::mariadb::MariaDBConnection::checkStatus(), and database::mariadb::MariaDBConnection::execute_sync().
commandInfo()
virtual std::string database::mariadb::MariaDBCommand::commandInfo () pure virtual
Implemented in database::mariadb::commands::sync::MariaDBUseResultCommand, database::mariadb::commands::sync::MariaDBFieldCountCommand, database::mariadb::commands::sync::MariaDBAffectedRowsCommand, database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBCommitCommand, and database::mariadb::commands::async::MariaDBAutoCommitCommand.
Referenced by database::mariadb::MariaDBConnection::commandCompleted(), database::mariadb::MariaDBConnection::commandContinue(), and database::mariadb::MariaDBConnection::commandStart().
commandName()
const std::string & database::mariadb::MariaDBCommand::commandName ()
Definition at line 44 of file MariaDBCommand.cpp.
{
         return name;
     }
References name.
Referenced by database::mariadb::commands::async::MariaDBAutoCommitCommand::commandInfo(), database::mariadb::commands::async::MariaDBCommitCommand::commandInfo(), database::mariadb::commands::async::MariaDBConnectCommand::commandInfo(), database::mariadb::commands::async::MariaDBExecCommand::commandInfo(), database::mariadb::commands::async::MariaDBFetchRowCommand::commandInfo(), database::mariadb::commands::async::MariaDBFreeResultCommand::commandInfo(), database::mariadb::commands::async::MariaDBQueryCommand::commandInfo(), database::mariadb::commands::async::MariaDBRollbackCommand::commandInfo(), database::mariadb::commands::sync::MariaDBAffectedRowsCommand::commandInfo(), database::mariadb::commands::sync::MariaDBFieldCountCommand::commandInfo(), and database::mariadb::commands::sync::MariaDBUseResultCommand::commandInfo().
commandStart() [1/2]
virtual int database::mariadb::MariaDBCommand::commandStart () private pure virtual
Implemented in database::mariadb::commands::sync::MariaDBUseResultCommand, database::mariadb::commands::sync::MariaDBFieldCountCommand, database::mariadb::commands::sync::MariaDBAffectedRowsCommand, database::mariadb::commands::async::MariaDBRollbackCommand, database::mariadb::commands::async::MariaDBQueryCommand, database::mariadb::commands::async::MariaDBFreeResultCommand, database::mariadb::commands::async::MariaDBFetchRowCommand, database::mariadb::commands::async::MariaDBExecCommand, database::mariadb::commands::async::MariaDBConnectCommand, database::mariadb::commands::async::MariaDBCommitCommand, and database::mariadb::commands::async::MariaDBAutoCommitCommand.
Referenced by commandStart().
commandStart() [2/2]
int database::mariadb::MariaDBCommand::commandStart (MYSQL * mysql, const utils::Timeval & currentTime)
Definition at line 33 of file MariaDBCommand.cpp.
{
         this->mysql = mysql;
         startTime = currentTime;
         return commandStart();
     }
References commandStart(), mysql, and startTime.
Referenced by database::mariadb::MariaDBConnection::commandStart(), and database::mariadb::MariaDBConnection::execute_sync().
setMariaDBConnection()
void database::mariadb::MariaDBCommand::setMariaDBConnection (MariaDBConnection * mariaDBConnection)
Definition at line 40 of file MariaDBCommand.cpp.
{
         this->mariaDBConnection = mariaDBConnection;
     }
References mariaDBConnection.
Referenced by database::mariadb::MariaDBConnection::commandStart().
Member Data Documentation
mariaDBConnection
MariaDBConnection* database::mariadb::MariaDBCommand::mariaDBConnection = nullptr protected
Definition at line 63 of file MariaDBCommand.h.
Referenced by setMariaDBConnection().
mysql
MYSQL* database::mariadb::MariaDBCommand::mysql = nullptr protected
Definition at line 64 of file MariaDBCommand.h.
Referenced by database::mariadb::commands::async::MariaDBAutoCommitCommand::commandContinue(), database::mariadb::commands::async::MariaDBCommitCommand::commandContinue(), database::mariadb::commands::async::MariaDBConnectCommand::commandContinue(), database::mariadb::commands::async::MariaDBExecCommand::commandContinue(), database::mariadb::commands::async::MariaDBQueryCommand::commandContinue(), database::mariadb::commands::async::MariaDBRollbackCommand::commandContinue(), database::mariadb::commands::async::MariaDBAutoCommitCommand::commandStart(), database::mariadb::commands::async::MariaDBCommitCommand::commandStart(), database::mariadb::commands::async::MariaDBConnectCommand::commandStart(), database::mariadb::commands::async::MariaDBExecCommand::commandStart(), database::mariadb::commands::async::MariaDBQueryCommand::commandStart(), database::mariadb::commands::async::MariaDBRollbackCommand::commandStart(), database::mariadb::commands::sync::MariaDBAffectedRowsCommand::commandStart(), database::mariadb::commands::sync::MariaDBFieldCountCommand::commandStart(), database::mariadb::commands::sync::MariaDBUseResultCommand::commandStart(), and commandStart().
name
std::string database::mariadb::MariaDBCommand::name protected
Definition at line 61 of file MariaDBCommand.h.
Referenced by commandName().
onError
const std::function<void(const std::string&, unsigned int)> database::mariadb::MariaDBCommand::onError
Definition at line 69 of file MariaDBCommand.h.
Referenced by database::mariadb::commands::async::MariaDBAutoCommitCommand::commandError(), database::mariadb::commands::async::MariaDBCommitCommand::commandError(), database::mariadb::commands::async::MariaDBConnectCommand::commandError(), database::mariadb::commands::async::MariaDBExecCommand::commandError(), database::mariadb::commands::async::MariaDBFetchRowCommand::commandError(), database::mariadb::commands::async::MariaDBFreeResultCommand::commandError(), database::mariadb::commands::async::MariaDBQueryCommand::commandError(), database::mariadb::commands::async::MariaDBRollbackCommand::commandError(), database::mariadb::commands::sync::MariaDBAffectedRowsCommand::commandError(), database::mariadb::commands::sync::MariaDBFieldCountCommand::commandError(), and database::mariadb::commands::sync::MariaDBUseResultCommand::commandError().
startTime
utils::Timeval database::mariadb::MariaDBCommand::startTime = 0 protected
Definition at line 66 of file MariaDBCommand.h.
Referenced by commandStart().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBCommand.h
database/mariadb/MariaDBCommand.cpp