snode.c: CLI::Config Class Reference
CLI::Config Class Reference abstract
This class provides a converter for configuration files.
#include <CLI11.hpp>
Public Member Functions
virtual std::string to_config (const App *, bool, bool, std::string) const =0
Convert an app into a configuration.
virtual std::vector< ConfigItem > from_config (std::istream &) const =0
Convert a configuration into an app.
virtual std::string to_flag (const ConfigItem &item) const
Get a flag value.
std::vector< ConfigItem > from_file (const std::string &name)
Parse a config file, throw an error (ParseError:ConfigParseError or FileError) on failure.
virtual ~Config ()=default
Virtual destructor.
Protected Attributes
std::vector< ConfigItem > items {}
Detailed Description
This class provides a converter for configuration files.
Definition at line 2649 of file CLI11.hpp.
Constructor & Destructor Documentation
~Config()
virtual CLI::Config::~Config () virtual default
Virtual destructor.
Member Function Documentation
from_config()
virtual std::vector<ConfigItem> CLI::Config::from_config (std::istream &) const pure virtual
Convert a configuration into an app.
Implemented in CLI::ConfigBase.
from_file()
std::vector<ConfigItem> CLI::Config::from_file (const std::string & name) inline
Parse a config file, throw an error (ParseError:ConfigParseError or FileError) on failure.
Definition at line 2672 of file CLI11.hpp.
{
             std::ifstream input{name};
             if (!input.good())
                 throw FileError::Missing(name);
             return from_config(input);
         }
References CLI::FileError::Missing().
to_config()
virtual std::string CLI::Config::to_config (const App * , bool , bool , std::string) const pure virtual
Convert an app into a configuration.
Implemented in CLI::ConfigBase.
to_flag()
virtual std::string CLI::Config::to_flag (const ConfigItem & item) const inline virtual
Get a flag value.
Definition at line 2661 of file CLI11.hpp.
{
             if (item.inputs.size() == 1) {
                 return item.inputs.at(0);
             }
             if (item.inputs.empty()) {
                 return "{}";
             }
             throw ConversionError::TooManyInputsFlag(item.fullname());
         }
References CLI::ConfigItem::fullname(), CLI::ConfigItem::inputs, and CLI::ConversionError::TooManyInputsFlag().
Member Data Documentation
items
std::vector<ConfigItem> CLI::Config::items {} protected
Definition at line 2651 of file CLI11.hpp.
The documentation for this class was generated from the following file:
utils/CLI11.hpp