snode.c: core::EventLoop Class Reference
core::EventLoop Class Reference
#include <EventLoop.h>
Public Member Functions
EventDispatcher & getReadEventDispatcher ()
EventDispatcher & getWriteEventDispatcher ()
EventDispatcher & getExceptionalConditionEventDispatcher ()
TimerEventDispatcher & getTimerEventDispatcher ()
unsigned long getEventCounter ()
unsigned long getTickCounter ()
Static Public Member Functions
static EventLoop & instance ()
Static Protected Member Functions
static void init (int argc, char *argv[])
static int start (struct timeval timeOut)
static TickStatus tick (struct timeval timeOut)
static void stop ()
static void free ()
Private Member Functions
EventLoop (const EventLoop &eventLoop)=delete
EventLoop & operator= (const EventLoop &eventLoop)=delete
EventLoop ()=default
~EventLoop ()=default
TickStatus _tick (struct timeval timeOut)
void _free ()
Static Private Member Functions
static void stoponsig (int sig)
Private Attributes
EventDispatcher readEventDispatcher
EventDispatcher writeEventDispatcher
EventDispatcher exceptionalConditionEventDispatcher
TimerEventDispatcher timerEventDispatcher
struct timeval nextEventTimeout = {LONG_MAX, 0}
unsigned long tickCounter = 0
Static Private Attributes
static EventLoop eventLoop
static bool running = false
static bool stopped = true
static int stopsig = 0
static bool initialized = false
Friends
class SNodeC
Detailed Description
Definition at line 34 of file EventLoop.h.
Constructor & Destructor Documentation
EventLoop() [1/2]
core::EventLoop::EventLoop (const EventLoop & eventLoop) private delete
EventLoop() [2/2]
core::EventLoop::EventLoop () private default
~EventLoop()
core::EventLoop::~EventLoop () private default
Member Function Documentation
_free()
void core::EventLoop::_free () private
Definition at line 144 of file EventLoop.cpp.
{
         readEventDispatcher.observeEnabledEvents();
         writeEventDispatcher.observeEnabledEvents();
         exceptionalConditionEventDispatcher.observeEnabledEvents();
         readEventDispatcher.disableObservedEvents();
         writeEventDispatcher.disableObservedEvents();
         exceptionalConditionEventDispatcher.disableObservedEvents();
         readEventDispatcher.unobserveDisabledEvents();
         writeEventDispatcher.unobserveDisabledEvents();
         exceptionalConditionEventDispatcher.unobserveDisabledEvents();
         readEventDispatcher.releaseUnobservedEvents();
         writeEventDispatcher.releaseUnobservedEvents();
         exceptionalConditionEventDispatcher.releaseUnobservedEvents();
         timerEventDispatcher.cancelAll();
         DynamicLoader::execDlCloseAll();
     }
References core::TimerEventDispatcher::cancelAll(), core::EventDispatcher::disableObservedEvents(), exceptionalConditionEventDispatcher, core::DynamicLoader::execDlCloseAll(), core::EventDispatcher::observeEnabledEvents(), readEventDispatcher, core::EventDispatcher::releaseUnobservedEvents(), timerEventDispatcher, core::EventDispatcher::unobserveDisabledEvents(), and writeEventDispatcher.
Referenced by free(), and start().
_tick()
TickStatus core::EventLoop::_tick (struct timeval timeOut) private
Definition at line 79 of file EventLoop.cpp.
{
         TickStatus tickStatus = TickStatus::SUCCESS;
         struct timeval nextDispatcherTimeout = readEventDispatcher.observeEnabledEvents();
         nextEventTimeout = std::min(nextDispatcherTimeout, nextEventTimeout);
         nextDispatcherTimeout = writeEventDispatcher.observeEnabledEvents();
         nextEventTimeout = std::min(nextDispatcherTimeout, nextEventTimeout);
         nextDispatcherTimeout = exceptionalConditionEventDispatcher.observeEnabledEvents();
         nextEventTimeout = std::min(nextDispatcherTimeout, nextEventTimeout);
         nextDispatcherTimeout = timerEventDispatcher.getNextTimeout();
         nextEventTimeout = std::min(nextDispatcherTimeout, nextEventTimeout);
         int maxFd = readEventDispatcher.getMaxFd();
         maxFd = std::max(writeEventDispatcher.getMaxFd(), maxFd);
         maxFd = std::max(exceptionalConditionEventDispatcher.getMaxFd(), maxFd);
         if (maxFd >= 0 || !timerEventDispatcher.empty()) {
             nextEventTimeout = std::max(nextEventTimeout, {0, 0});
             nextEventTimeout = std::min(nextEventTimeout, timeOut);
             int counter = core::system::select(maxFd + 1,
                                                &readEventDispatcher.getFdSet(),
                                                &writeEventDispatcher.getFdSet(),
                                                &exceptionalConditionEventDispatcher.getFdSet(),
                                                &nextEventTimeout);
             if (counter >= 0) {
                 nextEventTimeout = {LONG_MAX, 0};
                 timerEventDispatcher.dispatch();
                 struct timeval currentTime = {core::system::time(nullptr), 0};
                 nextDispatcherTimeout = readEventDispatcher.dispatchActiveEvents(currentTime);
                 nextEventTimeout = std::min(nextDispatcherTimeout, nextEventTimeout);
                 nextDispatcherTimeout = writeEventDispatcher.dispatchActiveEvents(currentTime);
                 nextEventTimeout = std::min(nextDispatcherTimeout, nextEventTimeout);
                 nextDispatcherTimeout = exceptionalConditionEventDispatcher.dispatchActiveEvents(currentTime);
                 nextEventTimeout = std::min(nextDispatcherTimeout, nextEventTimeout);
                 readEventDispatcher.unobserveDisabledEvents();
                 writeEventDispatcher.unobserveDisabledEvents();
                 exceptionalConditionEventDispatcher.unobserveDisabledEvents();
                 readEventDispatcher.releaseUnobservedEvents();
                 writeEventDispatcher.releaseUnobservedEvents();
                 exceptionalConditionEventDispatcher.releaseUnobservedEvents();
                 DynamicLoader::execDlCloseDeleyed();
             } else if (errno != EINTR) {
                 PLOG(ERROR) << "select";
                 tickStatus = TickStatus::SELECT_ERROR;
             }
         } else {
             tickStatus = TickStatus::NO_OBSERVER;
         }
         return tickStatus;
     }
References core::TimerEventDispatcher::dispatch(), core::EventDispatcher::dispatchActiveEvents(), core::TimerEventDispatcher::empty(), exceptionalConditionEventDispatcher, core::DynamicLoader::execDlCloseDeleyed(), core::EventDispatcher::getFdSet(), core::EventDispatcher::getMaxFd(), core::TimerEventDispatcher::getNextTimeout(), nextEventTimeout, core::NO_OBSERVER, core::EventDispatcher::observeEnabledEvents(), readEventDispatcher, core::EventDispatcher::releaseUnobservedEvents(), core::system::select(), core::SELECT_ERROR, core::SUCCESS, core::system::time(), timerEventDispatcher, core::EventDispatcher::unobserveDisabledEvents(), and writeEventDispatcher.
Referenced by start(), and tick().
free()
void core::EventLoop::free () static protected
Definition at line 239 of file EventLoop.cpp.
{
         eventLoop._free();
     }
References _free(), and eventLoop.
Referenced by core::SNodeC::free().
getEventCounter()
unsigned long core::EventLoop::getEventCounter ()
Definition at line 248 of file EventLoop.cpp.
{
         return readEventDispatcher.getEventCounter() + writeEventDispatcher.getEventCounter() +
                exceptionalConditionEventDispatcher.getEventCounter();
     }
References exceptionalConditionEventDispatcher, core::EventDispatcher::getEventCounter(), readEventDispatcher, and writeEventDispatcher.
getExceptionalConditionEventDispatcher()
EventDispatcher & core::EventLoop::getExceptionalConditionEventDispatcher ()
Definition at line 71 of file EventLoop.cpp.
{
         return exceptionalConditionEventDispatcher;
     }
References exceptionalConditionEventDispatcher.
getReadEventDispatcher()
EventDispatcher & core::EventLoop::getReadEventDispatcher ()
Definition at line 63 of file EventLoop.cpp.
{
         return readEventDispatcher;
     }
References readEventDispatcher.
getTickCounter()
unsigned long core::EventLoop::getTickCounter ()
Definition at line 253 of file EventLoop.cpp.
{
         return tickCounter;
     }
References tickCounter.
getTimerEventDispatcher()
TimerEventDispatcher & core::EventLoop::getTimerEventDispatcher ()
Definition at line 75 of file EventLoop.cpp.
{
         return timerEventDispatcher;
     }
References timerEventDispatcher.
Referenced by core::timer::Timer::cancel(), core::timer::Timer::intervalTimer(), and core::timer::Timer::singleshotTimer().
getWriteEventDispatcher()
EventDispatcher & core::EventLoop::getWriteEventDispatcher ()
Definition at line 67 of file EventLoop.cpp.
{
         return writeEventDispatcher;
     }
References writeEventDispatcher.
init()
void core::EventLoop::init (int argc, char * argv[]) static protected
Definition at line 167 of file EventLoop.cpp.
{
         logger::Logger::init(argc, argv);
         logger::Logger::setCustomFormatSpec("%tick", core::getTickCounterAsString);
         EventLoop::initialized = true;
     }
References core::getTickCounterAsString(), logger::Logger::init(), initialized, and logger::Logger::setCustomFormatSpec().
Referenced by core::SNodeC::init().
instance()
EventLoop & core::EventLoop::instance () static
Definition at line 59 of file EventLoop.cpp.
{
         return eventLoop;
     }
References eventLoop.
Referenced by core::timer::Timer::cancel(), core::getTickCounterAsString(), core::timer::Timer::intervalTimer(), and core::timer::Timer::singleshotTimer().
operator=()
EventLoop& core::EventLoop::operator= (const EventLoop & eventLoop) private delete
start()
int core::EventLoop::start (struct timeval timeOut) static protected
Definition at line 175 of file EventLoop.cpp.
{
         if (!initialized) {
             PLOG(ERROR) << "snode.c not initialized. Use EventLoop::init(argc, argv) before EventLoop::start().";
             exit(1);
         }
         sighandler_t oldSigPipeHandler = core::system::signal(SIGPIPE, SIG_IGN);
         sighandler_t oldSigQuitHandler = core::system::signal(SIGQUIT, EventLoop::stoponsig);
         sighandler_t oldSigHubHandler = core::system::signal(SIGHUP, EventLoop::stoponsig);
         sighandler_t oldSigIntHandler = core::system::signal(SIGINT, EventLoop::stoponsig);
         sighandler_t oldSigTermHandler = core::system::signal(SIGTERM, EventLoop::stoponsig);
         sighandler_t oldSigAbrtHandler = core::system::signal(SIGABRT, EventLoop::stoponsig);
         if (!running) {
             running = true;
             stopped = false;
             do {
                 while (!stopped && eventLoop._tick(timeOut) == TickStatus::SUCCESS) {
                     eventLoop.tickCounter++;
                 };
                 eventLoop._free();
             } while (!stopped && false);
             running = false;
         }
         core::system::signal(SIGPIPE, oldSigPipeHandler);
         core::system::signal(SIGQUIT, oldSigQuitHandler);
         core::system::signal(SIGHUP, oldSigHubHandler);
         core::system::signal(SIGINT, oldSigIntHandler);
         core::system::signal(SIGTERM, oldSigTermHandler);
         core::system::signal(SIGABRT, oldSigAbrtHandler);
         int returnReason = 0;
         if (stopsig != 0) {
             returnReason = -1;
         }
         return returnReason;
     }
References _free(), _tick(), eventLoop, initialized, running, core::system::signal(), stoponsig(), stopped, stopsig, core::SUCCESS, and tickCounter.
Referenced by core::SNodeC::start().
stop()
void core::EventLoop::stop () static protected
Definition at line 235 of file EventLoop.cpp.
{
         stopped = true;
     }
References stopped.
Referenced by core::SNodeC::stop(), and stoponsig().
stoponsig()
void core::EventLoop::stoponsig (int sig) static private
Definition at line 243 of file EventLoop.cpp.
{
         stopsig = sig;
         stop();
     }
References stop(), and stopsig.
Referenced by start().
tick()
TickStatus core::EventLoop::tick (struct timeval timeOut) static protected
Definition at line 220 of file EventLoop.cpp.
{
         if (!initialized) {
             PLOG(ERROR) << "snode.c not initialized. Use EventLoop::init(argc, argv) before EventLoop::start().";
             exit(1);
         }
         sighandler_t oldSigPipeHandler = core::system::signal(SIGPIPE, SIG_IGN);
         TickStatus tickStatus = eventLoop._tick(timeOut);
         core::system::signal(SIGPIPE, oldSigPipeHandler);
         return tickStatus;
     }
References _tick(), eventLoop, initialized, and core::system::signal().
Referenced by core::SNodeC::tick().
Friends And Related Function Documentation
SNodeC
friend class SNodeC friend
Definition at line 85 of file EventLoop.h.
Member Data Documentation
eventLoop
EventLoop core::EventLoop::eventLoop static private
Definition at line 68 of file EventLoop.h.
Referenced by free(), instance(), start(), and tick().
exceptionalConditionEventDispatcher
EventDispatcher core::EventLoop::exceptionalConditionEventDispatcher private
Definition at line 72 of file EventLoop.h.
Referenced by _free(), _tick(), getEventCounter(), and getExceptionalConditionEventDispatcher().
initialized
bool core::EventLoop::initialized = false static private
Definition at line 81 of file EventLoop.h.
Referenced by init(), start(), and tick().
nextEventTimeout
struct timeval core::EventLoop::nextEventTimeout = {LONG_MAX, 0} private
Definition at line 74 of file EventLoop.h.
Referenced by _tick().
readEventDispatcher
EventDispatcher core::EventLoop::readEventDispatcher private
Definition at line 70 of file EventLoop.h.
Referenced by _free(), _tick(), getEventCounter(), and getReadEventDispatcher().
running
bool core::EventLoop::running = false static private
Definition at line 78 of file EventLoop.h.
Referenced by start().
stopped
bool core::EventLoop::stopped = true static private
Definition at line 79 of file EventLoop.h.
Referenced by start(), and stop().
stopsig
int core::EventLoop::stopsig = 0 static private
Definition at line 80 of file EventLoop.h.
Referenced by start(), and stoponsig().
tickCounter
unsigned long core::EventLoop::tickCounter = 0 private
Definition at line 83 of file EventLoop.h.
Referenced by getTickCounter(), and start().
timerEventDispatcher
TimerEventDispatcher core::EventLoop::timerEventDispatcher private
Definition at line 74 of file EventLoop.h.
Referenced by _free(), _tick(), and getTimerEventDispatcher().
writeEventDispatcher
EventDispatcher core::EventLoop::writeEventDispatcher private
Definition at line 71 of file EventLoop.h.
Referenced by _free(), _tick(), getEventCounter(), and getWriteEventDispatcher().
The documentation for this class was generated from the following files:
core/EventLoop.h
core/EventLoop.cpp