snode.c: database::mariadb::MariaDBConnection Class Reference
database::mariadb::MariaDBConnection Class Reference
#include <MariaDBConnection.h>
Public Member Functions
MariaDBConnection (MariaDBClient *mariaDBClient, const MariaDBConnectionDetails &connectionDetails)
MariaDBConnection (const MariaDBConnection &)=delete
~MariaDBConnection ()
MariaDBConnection & operator= (const MariaDBConnection &)=delete
MariaDBCommandSequence & execute_async (MariaDBCommandSequence &&commandSequence)
void execute_sync (MariaDBCommand *mariaDBCommand)
void commandStart (const utils::Timeval &currentTime)
void commandContinue (int status)
void commandCompleted ()
void unmanaged ()
Protected Member Functions
void checkStatus (int status)
void readEvent () override
void writeEvent () override
void outOfBandEvent () override
void readTimeout () override
void writeTimeout () override
void outOfBandTimeout () override
void unobservedEvent () override
Private Attributes
MariaDBClient * mariaDBClient
MYSQL * mysql
std::deque< MariaDBCommandSequence > commandSequenceQueue
MariaDBCommand * currentCommand = nullptr
bool connected = false
MariaDBCommandStartEvent commandStartEvent
Private Attributes inherited from core::EventReceiver
Event _event
Additional Inherited Members
Private Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout=60)
Private Member Functions inherited from core::DescriptorEventReceiver
int getRegisteredFd ()
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
bool isEnabled () const
bool isSuspended () const
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
void enable (int fd)
void disable ()
void suspend ()
void resume ()
void setTimeout (const utils::Timeval &timeout)
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
Private Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Private Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish ()
void unPublish ()
const std::string & getName ()
Private Member Functions inherited from core::eventreceiver::WriteEventReceiver
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout=60)
Private Member Functions inherited from core::eventreceiver::ExceptionalConditionEventReceiver
ExceptionalConditionEventReceiver (const std::string &name, const utils::Timeval &timeout=60)
Detailed Description
Definition at line 62 of file MariaDBConnection.h.
Constructor & Destructor Documentation
MariaDBConnection() [1/2]
database::mariadb::MariaDBConnection::MariaDBConnection (MariaDBClient * mariaDBClient, const MariaDBConnectionDetails & connectionDetails) explicit
Definition at line 37 of file MariaDBConnection.cpp.
         : ReadEventReceiver("MariaDBConnectionRead", core::DescriptorEventReceiver::TIMEOUT::DISABLE)
         , WriteEventReceiver("MariaDBConnectionWrite", core::DescriptorEventReceiver::TIMEOUT::DISABLE)
         , ExceptionalConditionEventReceiver("MariaDBConnectionExceptional", core::DescriptorEventReceiver::TIMEOUT::DISABLE)
         , mariaDBClient(mariaDBClient)
         , mysql(mysql_init(nullptr))
         , commandStartEvent("MariaDBCommandStartEvent", this) {
         mysql_options(mysql, MYSQL_OPT_NONBLOCK, 0);
         execute_async(std::move(MariaDBCommandSequence().execute_async(new database::mariadb::commands::async::MariaDBConnectCommand(
             connectionDetails,
             [this](void) -> void {
                 if (mysql_errno(mysql) == 0) {
                     int fd = mysql_get_socket(mysql);
                     VLOG(0) << "Got valid descriptor: " << fd;
                     ReadEventReceiver::enable(fd);
                     WriteEventReceiver::enable(fd);
                     ExceptionalConditionEventReceiver::enable(fd);
                     ReadEventReceiver::suspend();
                     WriteEventReceiver::suspend();
                     ExceptionalConditionEventReceiver::suspend();
                     connected = true;
                 } else {
                     VLOG(0) << "Got no valid descriptor: " << mysql_error(mysql) << ", " << mysql_errno(mysql);
                 }
             },
             [](void) -> void {
                 VLOG(0) << "Connected";
             },
             [](const std::string& errorString, unsigned int errorNumber) -> void {
                 VLOG(0) << "Connect error: " << errorString << " : " << errorNumber;
             }))));
     }
References connected, execute_async(), and mysql.
MariaDBConnection() [2/2]
database::mariadb::MariaDBConnection::MariaDBConnection (const MariaDBConnection &) delete
~MariaDBConnection()
database::mariadb::MariaDBConnection::~MariaDBConnection ()
Definition at line 75 of file MariaDBConnection.cpp.
{
         for (MariaDBCommandSequence& mariaDBCommandSequence : commandSequenceQueue) {
             for (MariaDBCommand* mariaDBCommand : mariaDBCommandSequence.sequence()) {
                 mariaDBCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
                 delete mariaDBCommand;
             }
         }
         if (mariaDBClient != nullptr) {
             mariaDBClient->connectionVanished();
         }
         mysql_close(mysql);
         mysql_library_end();
     }
References commandSequenceQueue, database::mariadb::MariaDBClient::connectionVanished(), mariaDBClient, and mysql.
Member Function Documentation
checkStatus()
void database::mariadb::MariaDBConnection::checkStatus (int status) protected
Definition at line 165 of file MariaDBConnection.cpp.
{
         if (connected) {
             if ((status & MYSQL_WAIT_READ) != 0) {
                 if (ReadEventReceiver::isSuspended()) {
                     ReadEventReceiver::resume();
                 }
             } else if (!ReadEventReceiver::isSuspended()) {
                 ReadEventReceiver::suspend();
             }
             if ((status & MYSQL_WAIT_WRITE) != 0) {
                 if (WriteEventReceiver::isSuspended()) {
                     WriteEventReceiver::resume();
                 }
             } else if (!WriteEventReceiver::isSuspended()) {
                 WriteEventReceiver::suspend();
             }
             if ((status & MYSQL_WAIT_EXCEPT) != 0) {
                 if (ExceptionalConditionEventReceiver::isSuspended()) {
                     ExceptionalConditionEventReceiver::resume();
                 }
             } else if (!ExceptionalConditionEventReceiver::isSuspended()) {
                 ExceptionalConditionEventReceiver::suspend();
             }
             if ((status & MYSQL_WAIT_TIMEOUT) != 0) {
                 ReadEventReceiver::setTimeout(mysql_get_timeout_value(mysql));
                 //                WriteEventReceiver::setTimeout(mysql_get_timeout_value(mysql));
                 //                ExceptionalConditionEventReceiver::setTimeout(mysql_get_timeout_value(mysql));
             } else {
                 ReadEventReceiver::setTimeout(core::DescriptorEventReceiver::TIMEOUT::DEFAULT);
                 //                WriteEventReceiver::setTimeout(core::DescriptorEventReceiver::TIMEOUT::DEFAULT);
                 //                ExceptionalConditionEventReceiver::setTimeout(core::DescriptorEventReceiver::TIMEOUT::DEFAULT);
             }
             if (status == 0) {
                 if (mysql_errno(mysql) == 0) {
                     if (currentCommand->commandCompleted()) {
                         commandCompleted();
                     }
                 } else {
                     currentCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
                     commandCompleted();
                 }
                 commandStartEvent.publish();
             }
         } else {
             currentCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
             commandCompleted();
             delete this;
         }
     }
References commandCompleted(), database::mariadb::MariaDBCommand::commandCompleted(), database::mariadb::MariaDBCommand::commandError(), commandStartEvent, connected, currentCommand, core::DescriptorEventReceiver::TIMEOUT::DEFAULT, mysql, and database::mariadb::MariaDBCommandStartEvent::publish().
Referenced by commandContinue(), and commandStart().
commandCompleted()
void database::mariadb::MariaDBConnection::commandCompleted ()
Definition at line 149 of file MariaDBConnection.cpp.
{
         VLOG(0) << "Completed: " << currentCommand->commandInfo();
         commandSequenceQueue.front().commandCompleted();
         if (commandSequenceQueue.front().empty()) {
             commandSequenceQueue.pop_front();
         }
         delete currentCommand;
         currentCommand = nullptr;
     }
References database::mariadb::MariaDBCommand::commandInfo(), commandSequenceQueue, and currentCommand.
Referenced by checkStatus().
commandContinue()
void database::mariadb::MariaDBConnection::commandContinue (int status)
Definition at line 135 of file MariaDBConnection.cpp.
{
         if (currentCommand != nullptr) {
             VLOG(0) << "Continue: " << currentCommand->commandInfo();
             int currentStatus = currentCommand->commandContinue(status);
             checkStatus(currentStatus);
         } else if ((status & MYSQL_WAIT_READ) != 0 && commandSequenceQueue.empty()) {
             VLOG(0) << "Read-Event but no command in queue: Disabling EventReceivers";
             ReadEventReceiver::disable();
             WriteEventReceiver::disable();
             ExceptionalConditionEventReceiver::disable();
         }
     }
References checkStatus(), database::mariadb::MariaDBCommand::commandContinue(), database::mariadb::MariaDBCommand::commandInfo(), commandSequenceQueue, and currentCommand.
Referenced by outOfBandEvent(), outOfBandTimeout(), readEvent(), readTimeout(), writeEvent(), and writeTimeout().
commandStart()
void database::mariadb::MariaDBConnection::commandStart (const utils::Timeval & currentTime)
Definition at line 115 of file MariaDBConnection.cpp.
{
         if (!commandSequenceQueue.empty()) {
             currentCommand = commandSequenceQueue.front().nextCommand();
             currentCommand->setMariaDBConnection(this);
             VLOG(0) << "Start: " << currentCommand->commandInfo();
             int status = currentCommand->commandStart(mysql, currentTime);
             checkStatus(status);
         } else if (mariaDBClient != nullptr) {
             if (ReadEventReceiver::isSuspended()) {
                 ReadEventReceiver::resume();
             }
         } else {
             ReadEventReceiver::disable();
             WriteEventReceiver::disable();
             ExceptionalConditionEventReceiver::disable();
         }
     }
References checkStatus(), database::mariadb::MariaDBCommand::commandInfo(), commandSequenceQueue, database::mariadb::MariaDBCommand::commandStart(), currentCommand, mariaDBClient, mysql, and database::mariadb::MariaDBCommand::setMariaDBConnection().
Referenced by database::mariadb::MariaDBCommandStartEvent::event().
execute_async()
MariaDBCommandSequence & database::mariadb::MariaDBConnection::execute_async (MariaDBCommandSequence && commandSequence)
Definition at line 92 of file MariaDBConnection.cpp.
{
         if (currentCommand == nullptr && commandSequenceQueue.empty()) {
             commandStartEvent.publish();
         }
         commandSequenceQueue.emplace_back(std::move(commandSequence));
         return commandSequenceQueue.back();
     }
References commandSequenceQueue, commandStartEvent, currentCommand, and database::mariadb::MariaDBCommandStartEvent::publish().
Referenced by database::mariadb::MariaDBClient::execute_async(), and MariaDBConnection().
execute_sync()
void database::mariadb::MariaDBConnection::execute_sync (MariaDBCommand * mariaDBCommand)
Definition at line 102 of file MariaDBConnection.cpp.
{
         mariaDBCommand->commandStart(mysql, utils::Timeval::currentTime());
         if (mysql_errno(mysql) == 0) {
             if (mariaDBCommand->commandCompleted()) {
             }
         } else {
             mariaDBCommand->commandError(mysql_error(mysql), mysql_errno(mysql));
         }
         delete mariaDBCommand;
     }
References database::mariadb::MariaDBCommand::commandCompleted(), database::mariadb::MariaDBCommand::commandError(), database::mariadb::MariaDBCommand::commandStart(), utils::Timeval::currentTime(), and mysql.
Referenced by database::mariadb::MariaDBClient::execute_sync().
operator=()
MariaDBConnection& database::mariadb::MariaDBConnection::operator= (const MariaDBConnection &) delete
outOfBandEvent()
void database::mariadb::MariaDBConnection::outOfBandEvent () override protected virtual
Implements core::eventreceiver::ExceptionalConditionEventReceiver.
Definition at line 227 of file MariaDBConnection.cpp.
{
         commandContinue(MYSQL_WAIT_EXCEPT);
     }
References commandContinue().
outOfBandTimeout()
void database::mariadb::MariaDBConnection::outOfBandTimeout () override protected virtual
Reimplemented from core::eventreceiver::ExceptionalConditionEventReceiver.
Definition at line 239 of file MariaDBConnection.cpp.
{
         commandContinue(MYSQL_WAIT_TIMEOUT);
     }
References commandContinue().
readEvent()
void database::mariadb::MariaDBConnection::readEvent () override protected virtual
Implements core::eventreceiver::ReadEventReceiver.
Definition at line 219 of file MariaDBConnection.cpp.
{
         commandContinue(MYSQL_WAIT_READ);
     }
References commandContinue().
readTimeout()
void database::mariadb::MariaDBConnection::readTimeout () override protected virtual
Reimplemented from core::eventreceiver::ReadEventReceiver.
Definition at line 231 of file MariaDBConnection.cpp.
{
         commandContinue(MYSQL_WAIT_TIMEOUT);
     }
References commandContinue().
unmanaged()
void database::mariadb::MariaDBConnection::unmanaged ()
Definition at line 161 of file MariaDBConnection.cpp.
{
         mariaDBClient = nullptr;
     }
References mariaDBClient.
Referenced by database::mariadb::MariaDBClient::~MariaDBClient().
unobservedEvent()
void database::mariadb::MariaDBConnection::unobservedEvent () override protected virtual
Implements core::Observer.
Definition at line 243 of file MariaDBConnection.cpp.
{
         delete this;
     }
writeEvent()
void database::mariadb::MariaDBConnection::writeEvent () override protected virtual
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 223 of file MariaDBConnection.cpp.
{
         commandContinue(MYSQL_WAIT_WRITE);
     }
References commandContinue().
writeTimeout()
void database::mariadb::MariaDBConnection::writeTimeout () override protected virtual
Reimplemented from core::eventreceiver::WriteEventReceiver.
Definition at line 235 of file MariaDBConnection.cpp.
{
         commandContinue(MYSQL_WAIT_TIMEOUT);
     }
References commandContinue().
Member Data Documentation
commandSequenceQueue
std::deque<MariaDBCommandSequence> database::mariadb::MariaDBConnection::commandSequenceQueue private
Definition at line 100 of file MariaDBConnection.h.
Referenced by commandCompleted(), commandContinue(), commandStart(), execute_async(), and ~MariaDBConnection().
commandStartEvent
MariaDBCommandStartEvent database::mariadb::MariaDBConnection::commandStartEvent private
Definition at line 105 of file MariaDBConnection.h.
Referenced by checkStatus(), and execute_async().
connected
bool database::mariadb::MariaDBConnection::connected = false private
Definition at line 103 of file MariaDBConnection.h.
Referenced by checkStatus(), and MariaDBConnection().
currentCommand
MariaDBCommand* database::mariadb::MariaDBConnection::currentCommand = nullptr private
Definition at line 102 of file MariaDBConnection.h.
Referenced by checkStatus(), commandCompleted(), commandContinue(), commandStart(), and execute_async().
mariaDBClient
MariaDBClient* database::mariadb::MariaDBConnection::mariaDBClient private
Definition at line 97 of file MariaDBConnection.h.
Referenced by commandStart(), unmanaged(), and ~MariaDBConnection().
mysql
MYSQL* database::mariadb::MariaDBConnection::mysql private
Definition at line 98 of file MariaDBConnection.h.
Referenced by checkStatus(), commandStart(), execute_sync(), MariaDBConnection(), and ~MariaDBConnection().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBConnection.h
database/mariadb/MariaDBConnection.cpp