snode.c: net::in::stream::ServerConfig Class Reference
net::in::stream::ServerConfig Class Reference
#include <ServerConfig.h>
Public Member Functions
ServerConfig (const std::string &name)
const std::string & getBindInterface () const
uint16_t getBindPort () const
int parse (bool required=false)
Public Member Functions inherited from net::ServerConfig
ServerConfig (const std::string &name)
int getBacklog () const
Public Member Functions inherited from net::Config
Config (const std::string &name)
const std::string & getName () const
int getReadTimeout () const
int getWriteTimeout () const
Private Attributes
CLI::App * serverBindSc = nullptr
CLI::Option * bindServerHostOpt = nullptr
CLI::Option * bindServerPortOpt = nullptr
std::string bindInterface
uint16_t bindPort
Additional Inherited Members
Public Attributes inherited from net::Config
CLI::App * serverSc = nullptr
Protected Member Functions inherited from net::Config
void finish ()
Detailed Description
Definition at line 38 of file ServerConfig.h.
Constructor & Destructor Documentation
ServerConfig()
net::in::stream::ServerConfig::ServerConfig (const std::string & name) explicit
Definition at line 30 of file ServerConfig.cpp.
         : net::ServerConfig(name) {
         serverBindSc = serverSc->add_subcommand("bind");
         serverBindSc->description("Server socket bind options");
         serverBindSc->configurable();
         bindServerHostOpt = serverBindSc->add_option("-a,--host", bindInterface, "Bind host name or IP address");
         bindServerHostOpt->type_name("[hostname|ip]");
         bindServerHostOpt->default_val("0.0.0.0");
         bindServerHostOpt->configurable();
         bindServerPortOpt = serverBindSc->add_option("-p,--port", bindPort, "Bind port number");
         bindServerPortOpt->type_name("[uint16_t]");
         bindServerPortOpt->default_val(0);
         bindServerPortOpt->configurable();
         finish();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindInterface, bindPort, bindServerHostOpt, bindServerPortOpt, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), net::Config::finish(), serverBindSc, net::Config::serverSc, and CLI::Option::type_name().
Member Function Documentation
getBindInterface()
const std::string & net::in::stream::ServerConfig::getBindInterface () const
Definition at line 49 of file ServerConfig.cpp.
{
         return bindInterface;
     }
References bindInterface.
Referenced by net::in::stream::ServerSocket::listen().
getBindPort()
uint16_t net::in::stream::ServerConfig::getBindPort () const
Definition at line 53 of file ServerConfig.cpp.
{
         return bindPort;
     }
References bindPort.
Referenced by net::in::stream::ServerSocket::listen().
parse()
int net::in::stream::ServerConfig::parse (bool required = false)
Definition at line 57 of file ServerConfig.cpp.
{
         utils::Config::instance().required(serverSc, required);
         utils::Config::instance().required(serverBindSc, required);
         utils::Config::instance().required(bindServerPortOpt, required);
         try {
             utils::Config::instance().parse();
         } catch (const CLI::ParseError& e) {
         }
         return 0;
     }
References bindServerPortOpt, utils::Config::instance(), utils::Config::parse(), utils::Config::required(), serverBindSc, and net::Config::serverSc.
Referenced by net::in::stream::ServerSocket::listen().
Member Data Documentation
bindInterface
std::string net::in::stream::ServerConfig::bindInterface private
Definition at line 68 of file ServerConfig.h.
Referenced by getBindInterface(), and ServerConfig().
bindPort
uint16_t net::in::stream::ServerConfig::bindPort private
Definition at line 69 of file ServerConfig.h.
Referenced by getBindPort(), and ServerConfig().
bindServerHostOpt
CLI::Option* net::in::stream::ServerConfig::bindServerHostOpt = nullptr private
Definition at line 60 of file ServerConfig.h.
Referenced by ServerConfig().
bindServerPortOpt
CLI::Option* net::in::stream::ServerConfig::bindServerPortOpt = nullptr private
Definition at line 61 of file ServerConfig.h.
Referenced by parse(), and ServerConfig().
serverBindSc
CLI::App* net::in::stream::ServerConfig::serverBindSc = nullptr private
Definition at line 59 of file ServerConfig.h.
Referenced by parse(), and ServerConfig().
The documentation for this class was generated from the following files:
net/in/stream/ServerConfig.h
net/in/stream/ServerConfig.cpp