snode.c: net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT > Class Template Reference
net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT > Class Template Reference
#include <SocketServer.h>
Public Types
using SocketAddress = typename net::socket::stream::legacy::SocketServer< l2cap::Socket, SocketContextFactoryT >::SocketAddress
Public Types inherited from net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >
using SocketContextFactory = SocketContextFactoryT
using SocketAcceptor = SocketAcceptorT
using SocketConnection = typename SocketAcceptor::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Member Functions
void listen (uint16_t psm, int backlog, const std::function< void(int)> &onError)
void listen (const std::string &address, int backlog, const std::function< void(int)> &onError)
void listen (const std::string &address, uint16_t psm, int backlog, const std::function< void(int)> &onError)
Public Member Functions inherited from net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >
SocketServer (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketServer ()=default
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(int)> &onError) const
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Detailed Description
template<typename SocketContextFactoryT>
class net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >
Definition at line 32 of file SocketServer.h.
Member Typedef Documentation
SocketAddress
template<typename SocketContextFactoryT > using net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >::SocketAddress = typename net::socket::stream::legacy::SocketServer<l2cap::Socket, SocketContextFactoryT>::SocketAddress
Definition at line 36 of file SocketServer.h.
Member Function Documentation
listen() [1/3]
template<typename SocketContextFactoryT > void net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >::listen (const std::string & address, int backlog, const std::function< void(int)> & onError) inline
Definition at line 44 of file SocketServer.h.
{
             listen(SocketAddress(address), backlog, onError);
         }
References net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >::listen().
listen() [2/3]
template<typename SocketContextFactoryT > void net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >::listen (const std::string & address, uint16_t psm, int backlog, const std::function< void(int)> & onError) inline
Definition at line 48 of file SocketServer.h.
{
             listen(SocketAddress(address, psm), backlog, onError);
         }
References net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >::listen().
listen() [3/3]
template<typename SocketContextFactoryT > void net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >::listen (uint16_t psm, int backlog, const std::function< void(int)> & onError) inline
Definition at line 40 of file SocketServer.h.
{
             listen(SocketAddress(psm), backlog, onError);
         }
Referenced by net::socket::bluetooth::l2cap::SocketServer< SocketContextFactoryT >::listen().
The documentation for this class was generated from the following file:
net/socket/bluetooth/l2cap/SocketServer.h