snode.c: net::l2::stream::ClientSocket Class Reference
net::l2::stream::ClientSocket Class Reference
#include <ClientSocket.h>
Public Member Functions
void connect (const std::string &address, uint16_t psm, const std::function< void(int)> &onError)
void connect (const std::string &address, uint16_t psm, const std::string &bindAddress, const std::function< void(int)> &onError)
void connect (const std::string &address, uint16_t psm, const std::string &bindAddress, uint16_t bindPsm, const std::function< void(int)> &onError)
Public Member Functions inherited from core::socket::ClientSocket< net::l2::stream::Socket >
virtual void connect (const std::function< void(int)> &onError) const=0
virtual void connect (const typename Socket::SocketAddress &remoteAddress, const typename Socket::SocketAddress &bindAddress, const std::function< void(int)> &onError) const=0
virtual void connect (const typename Socket::SocketAddress &remoteAddress, const std::function< void(int)> &onError) const=0
Additional Inherited Members
Public Types inherited from core::socket::ClientSocket< net::l2::stream::Socket >
using Socket = net::l2::stream::Socket
Protected Member Functions inherited from core::socket::ClientSocket< net::l2::stream::Socket >
ClientSocket ()=default
Detailed Description
Definition at line 35 of file ClientSocket.h.
Member Function Documentation
connect() [1/3]
void net::l2::stream::ClientSocket::connect (const std::string & address, uint16_t psm, const std::function< void(int)> & onError)
Definition at line 27 of file ClientSocket.cpp.
{
         connect(SocketAddress(address, psm), onError);
     }
Referenced by connect().
connect() [2/3]
void net::l2::stream::ClientSocket::connect (const std::string & address, uint16_t psm, const std::string & bindAddress, const std::function< void(int)> & onError)
Definition at line 31 of file ClientSocket.cpp.
{
         connect(SocketAddress(address, psm), SocketAddress(bindAddress), onError);
     }
References connect().
connect() [3/3]
void net::l2::stream::ClientSocket::connect (const std::string & address, uint16_t psm, const std::string & bindAddress, uint16_t bindPsm, const std::function< void(int)> & onError)
Definition at line 38 of file ClientSocket.cpp.
{
         connect(SocketAddress(address, psm), SocketAddress(bindAddress, bindPsm), onError);
     }
References connect().
Referenced by connect().
The documentation for this class was generated from the following files:
net/l2/stream/ClientSocket.h
net/l2/stream/ClientSocket.cpp