snode.c: core::EventMultiplexer Class Reference
core::EventMultiplexer Class Reference abstract
#include <EventMultiplexer.h>
Classes
class EventQueue
Public Types
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Public Member Functions
DescriptorEventPublisher & getDescriptorEventPublisher (core::EventMultiplexer::DISP_TYPE dispType)
TimerEventPublisher & getTimerEventPublisher ()
void publish (core::Event *event)
void unPublish (core::Event *event)
TickStatus tick (const utils::Timeval &tickTimeOut)
void stop ()
Protected Member Functions
EventMultiplexer (DescriptorEventPublisher *const readDescriptorEventPublisher, DescriptorEventPublisher *const writeDescriptorEventPublisher, DescriptorEventPublisher *const exceptionDescriptorEventPublisher)
virtual ~EventMultiplexer ()
int getObservedEventReceiverCount ()
int getMaxFd ()
Protected Attributes
std::array< DescriptorEventPublisher *, 3 > descriptorEventPublishers
core::TimerEventPublisher *const timerEventPublisher
Private Member Functions
EventMultiplexer (const EventMultiplexer &)=delete
EventMultiplexer & operator= (const EventMultiplexer &)=delete
void checkTimedOutEvents (const utils::Timeval &currentTime)
utils::Timeval getNextTimeout (const utils::Timeval &currentTime)
virtual int multiplex (utils::Timeval &tickTimeOut)=0
void publishActiveEvents (int count, const utils::Timeval &currentTime)
virtual void publishActiveEvents (int count)=0
void unobserveDisabledEvents (const utils::Timeval &currentTime)
Private Attributes
EventQueue eventQueue
Friends
class DescriptorEventPublisher
Detailed Description
Definition at line 43 of file EventMultiplexer.h.
Member Enumeration Documentation
DISP_TYPE
enum core::EventMultiplexer::DISP_TYPE
Enumerator
RD
WR
EX
Definition at line 72 of file EventMultiplexer.h.
 { RD = 0, WR = 1, EX = 2 };
Constructor & Destructor Documentation
EventMultiplexer() [1/2]
core::EventMultiplexer::EventMultiplexer (const EventMultiplexer &) private delete
EventMultiplexer() [2/2]
core::EventMultiplexer::EventMultiplexer (DescriptorEventPublisher *const readDescriptorEventPublisher, DescriptorEventPublisher *const writeDescriptorEventPublisher, DescriptorEventPublisher *const exceptionDescriptorEventPublisher) protected
Definition at line 38 of file EventMultiplexer.cpp.
         : descriptorEventPublishers{readDescriptorEventPublisher, writeDescriptorEventPublisher, exceptionDescriptorEventPublisher}
         , timerEventPublisher(new core::TimerEventPublisher()) {
     }
~EventMultiplexer()
core::EventMultiplexer::~EventMultiplexer () protected virtual
Reimplemented in core::select::EventMultiplexer, core::poll::EventMultiplexer, and core::epoll::EventMultiplexer.
Definition at line 45 of file EventMultiplexer.cpp.
{
         for (DescriptorEventPublisher* descriptorEventPublisher : descriptorEventPublishers) {
             delete descriptorEventPublisher;
         }
         delete timerEventPublisher;
     }
References descriptorEventPublishers, and timerEventPublisher.
Member Function Documentation
checkTimedOutEvents()
void core::EventMultiplexer::checkTimedOutEvents (const utils::Timeval & currentTime) private
Definition at line 140 of file EventMultiplexer.cpp.
{
         for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
             descriptorEventPublisher->checkTimedOutEvents(currentTime);
         }
     }
References descriptorEventPublishers.
Referenced by tick().
getDescriptorEventPublisher()
DescriptorEventPublisher & core::EventMultiplexer::getDescriptorEventPublisher (core::EventMultiplexer::DISP_TYPE dispType)
Definition at line 52 of file EventMultiplexer.cpp.
{
         return *descriptorEventPublishers[dispType];
     }
References descriptorEventPublishers.
getMaxFd()
int core::EventMultiplexer::getMaxFd () protected
Definition at line 77 of file EventMultiplexer.cpp.
{
         return std::accumulate(descriptorEventPublishers.begin(),
                                descriptorEventPublishers.end(),
                                -1,
                                [](int count, DescriptorEventPublisher* descriptorEventPublisher) -> int {
                                    return std::max(descriptorEventPublisher->getMaxFd(), count);
                                });
     }
References descriptorEventPublishers.
Referenced by core::select::EventMultiplexer::multiplex().
getNextTimeout()
utils::Timeval core::EventMultiplexer::getNextTimeout (const utils::Timeval & currentTime) private
Definition at line 124 of file EventMultiplexer.cpp.
{
         utils::Timeval nextTimeout = DescriptorEventReceiver::TIMEOUT::MAX;
         if (eventQueue.empty()) {
             for (DescriptorEventPublisher* const eventMultiplexer : descriptorEventPublishers) {
                 nextTimeout = std::min(eventMultiplexer->getNextTimeout(currentTime), nextTimeout);
             }
             nextTimeout = std::min(timerEventPublisher->getNextTimeout(currentTime), nextTimeout);
             nextTimeout = std::max(nextTimeout, utils::Timeval()); // In case nextTimeout is negative
         } else {
             nextTimeout = 0;
         }
         return nextTimeout;
     }
References descriptorEventPublishers, core::EventMultiplexer::EventQueue::empty(), eventQueue, core::TimerEventPublisher::getNextTimeout(), core::DescriptorEventReceiver::TIMEOUT::MAX, and timerEventPublisher.
Referenced by tick().
getObservedEventReceiverCount()
int core::EventMultiplexer::getObservedEventReceiverCount () protected
Definition at line 68 of file EventMultiplexer.cpp.
{
         return std::accumulate(descriptorEventPublishers.begin(),
                                descriptorEventPublishers.end(),
                                0,
                                [](int count, DescriptorEventPublisher* descriptorEventPublisher) -> int {
                                    return count + descriptorEventPublisher->getObservedEventReceiverCount();
                                });
     }
References descriptorEventPublishers.
Referenced by tick().
getTimerEventPublisher()
core::TimerEventPublisher & core::EventMultiplexer::getTimerEventPublisher ()
Definition at line 56 of file EventMultiplexer.cpp.
{
         return *timerEventPublisher;
     }
References timerEventPublisher.
multiplex()
virtual int core::EventMultiplexer::multiplex (utils::Timeval & tickTimeOut) private pure virtual
Implemented in core::select::EventMultiplexer, core::poll::EventMultiplexer, and core::epoll::EventMultiplexer.
Referenced by tick().
operator=()
EventMultiplexer& core::EventMultiplexer::operator= (const EventMultiplexer &) private delete
publish()
void core::EventMultiplexer::publish (core::Event * event)
Definition at line 60 of file EventMultiplexer.cpp.
{
         eventQueue.insert(event);
     }
References eventQueue, and core::EventMultiplexer::EventQueue::insert().
Referenced by core::Event::publish().
publishActiveEvents() [1/2]
virtual void core::EventMultiplexer::publishActiveEvents (int count) private pure virtual
Implemented in core::select::EventMultiplexer, core::poll::EventMultiplexer, and core::epoll::EventMultiplexer.
publishActiveEvents() [2/2]
void core::EventMultiplexer::publishActiveEvents (int count, const utils::Timeval & currentTime) private
Definition at line 146 of file EventMultiplexer.cpp.
{
         timerEventPublisher->publishActiveEvents(currentTime);
         publishActiveEvents(count);
     }
References core::TimerEventPublisher::publishActiveEvents(), and timerEventPublisher.
Referenced by tick().
stop()
void core::EventMultiplexer::stop ()
Definition at line 117 of file EventMultiplexer.cpp.
{
         for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
             descriptorEventPublisher->stop();
         }
         timerEventPublisher->stop();
     }
References descriptorEventPublishers, core::TimerEventPublisher::stop(), and timerEventPublisher.
Referenced by core::EventLoop::free().
tick()
TickStatus core::EventMultiplexer::tick (const utils::Timeval & tickTimeOut)
Definition at line 86 of file EventMultiplexer.cpp.
{
         TickStatus tickStatus = TickStatus::SUCCESS;
         utils::Timeval currentTime = utils::Timeval::currentTime();
         eventQueue.execute(currentTime);
         checkTimedOutEvents(currentTime);
         unobserveDisabledEvents(currentTime);
         DynamicLoader::execDlCloseDeleyed();
         if (getObservedEventReceiverCount() > 0 || !timerEventPublisher->empty() || !eventQueue.empty()) {
             utils::Timeval nextTimeout = std::min(getNextTimeout(currentTime), tickTimeOut);
             int ret = multiplex(nextTimeout);
             if (ret >= 0) {
                 publishActiveEvents(ret, utils::Timeval::currentTime());
             } else if (errno != EINTR) {
                 tickStatus = TickStatus::ERROR;
             } else {
                 // ignore EINTR - it is not an error
             }
         } else {
             tickStatus = TickStatus::NO_OBSERVER;
         }
         return tickStatus;
     }
References checkTimedOutEvents(), utils::Timeval::currentTime(), core::TimerEventPublisher::empty(), core::EventMultiplexer::EventQueue::empty(), core::ERROR, eventQueue, core::DynamicLoader::execDlCloseDeleyed(), core::EventMultiplexer::EventQueue::execute(), getNextTimeout(), getObservedEventReceiverCount(), multiplex(), core::NO_OBSERVER, publishActiveEvents(), core::SUCCESS, timerEventPublisher, and unobserveDisabledEvents().
Referenced by core::EventLoop::_tick().
unobserveDisabledEvents()
void core::EventMultiplexer::unobserveDisabledEvents (const utils::Timeval & currentTime) private
Definition at line 151 of file EventMultiplexer.cpp.
{
         for (DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
             descriptorEventPublisher->unobserveDisabledEvents(currentTime);
         }
         timerEventPublisher->unobserveDisableEvents();
     }
References descriptorEventPublishers, timerEventPublisher, and core::TimerEventPublisher::unobserveDisableEvents().
Referenced by tick().
unPublish()
void core::EventMultiplexer::unPublish (core::Event * event)
Definition at line 64 of file EventMultiplexer.cpp.
{
         eventQueue.remove(event);
     }
References eventQueue, and core::EventMultiplexer::EventQueue::remove().
Referenced by core::Event::unPublish().
Friends And Related Function Documentation
DescriptorEventPublisher
friend class DescriptorEventPublisher friend
Definition at line 104 of file EventMultiplexer.h.
Member Data Documentation
descriptorEventPublishers
std::array<DescriptorEventPublisher*, 3 > core::EventMultiplexer::descriptorEventPublishers protected
Definition at line 98 of file EventMultiplexer.h.
Referenced by checkTimedOutEvents(), core::epoll::EventMultiplexer::EventMultiplexer(), getDescriptorEventPublisher(), getMaxFd(), getNextTimeout(), getObservedEventReceiverCount(), core::poll::EventMultiplexer::publishActiveEvents(), core::select::EventMultiplexer::publishActiveEvents(), stop(), unobserveDisabledEvents(), and ~EventMultiplexer().
eventQueue
EventQueue core::EventMultiplexer::eventQueue private
Definition at line 102 of file EventMultiplexer.h.
Referenced by getNextTimeout(), publish(), tick(), and unPublish().
timerEventPublisher
core::TimerEventPublisher* const core::EventMultiplexer::timerEventPublisher protected
Definition at line 99 of file EventMultiplexer.h.
Referenced by getNextTimeout(), getTimerEventPublisher(), publishActiveEvents(), stop(), tick(), unobserveDisabledEvents(), and ~EventMultiplexer().
The documentation for this class was generated from the following files:
core/EventMultiplexer.h
core/EventMultiplexer.cpp