snode.c: web::http::tls::rf::Server< Request, Response > Class Template Reference
web::http::tls::rf::Server< Request, Response > Class Template Reference
#include <Server.h>
Public Types
using SocketAddress = typename Super::SocketAddress
using SocketConnection = typename Super::SocketConnection
Public Types inherited from web::http::server::Server< net::rf::stream::tls::SocketServer, web::http::server::Request, web::http::server::Response >
using Request = web::http::server::Request
using Response = web::http::server::Response
using SocketConnection = typename Super::SocketConnection
using SocketAddress = typename SocketConnection::SocketAddress
Public Types inherited from core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >
using SocketConnection = typename Super::SocketConnection
using SocketAddress = typename Super::SocketAddress
Public Types inherited from core::socket::stream::SocketServer< ServerSocketT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
using SocketConnection = typename SocketAcceptor::SocketConnection
using SocketAddress = typename Super::SocketAddress
Public Member Functions
void listen (uint8_t channel, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &address, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &address, uint8_t channel, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const SocketAddress &localAddress, int backlog, const std::function< void(const SocketAddress &, int)> &onError) const override
void listen (const std::function< void(const SocketAddress &, int)> &onError) const override
Public Member Functions inherited from web::http::server::Server< net::rf::stream::tls::SocketServer, web::http::server::Request, web::http::server::Response >
Server (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &, Response &)> &onRequestReady, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void listen (const SocketAddress &socketAddress, const std::function< void(int)> &onError)
Public Member Functions inherited from core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void addSniCert (const std::string &domain, const std::map< std::string, std::any > &sniCert)
void addSniCerts (const std::map< std::string, std::map< std::string, std::any >> &sniCerts)
void setForceSni ()
Public Member Functions inherited from core::socket::stream::SocketServer< ServerSocketT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
SocketServer (const SocketServer &)=default
~SocketServer () override=default
void listen (const SocketAddress &localAddress, int backlog, const std::function< void(const SocketAddress &, int)> &onError) const override
void listen (const std::function< void(const SocketAddress &, int)> &onError) const override
void onConnect (const std::function< void(SocketConnection *)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
ServerConfig & getServerConfig ()
Private Types
using Super = web::http::server::Server< net::rf::stream::tls::SocketServer, Request, Response >
Additional Inherited Members
Protected Attributes inherited from core::socket::stream::SocketServer< ServerSocketT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
std::shared_ptr< ServerConfig > serverConfig
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response>
class web::http::tls::rf::Server< Request, Response >
Definition at line 32 of file Server.h.
Member Typedef Documentation
SocketAddress
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> using web::http::tls::rf::Server< Request, Response >::SocketAddress = typename Super::SocketAddress
Definition at line 37 of file Server.h.
SocketConnection
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> using web::http::tls::rf::Server< Request, Response >::SocketConnection = typename Super::SocketConnection
Definition at line 38 of file Server.h.
Super
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> using web::http::tls::rf::Server< Request, Response >::Super = web::http::server::Server<net::rf::stream::tls::SocketServer, Request, Response> private
Definition at line 33 of file Server.h.
Member Function Documentation
listen() [1/5]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void core::socket::stream::SocketServer< ServerSocketT, SocketAcceptorT, SocketContextFactoryT >::listen inline override
Definition at line 71 of file SocketServer.h.
{
             serverConfig->setLocalAddress(localAddress);
             serverConfig->setBacklog(backlog);
             listen(onError);
         }
Referenced by web::http::tls::rf::Server< Request, Response >::listen().
listen() [2/5]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void core::socket::stream::SocketServer< ServerSocketT, SocketAcceptorT, SocketContextFactoryT >::listen inline override
Definition at line 80 of file SocketServer.h.
{
             SocketAcceptor* socketAcceptor = new SocketAcceptor(socketContextFactory, _onConnect, _onConnected, _onDisconnect, options);
             socketAcceptor->listen(serverConfig, onError);
         }
listen() [3/5]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::tls::rf::Server< Request, Response >::listen (const std::string & address, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 46 of file Server.h.
{
             listen(address, LISTEN_BACKLOG, onError);
         }
References web::http::tls::rf::Server< Request, Response >::listen(), and LISTEN_BACKLOG.
listen() [4/5]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::tls::rf::Server< Request, Response >::listen (const std::string & address, uint8_t channel, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 50 of file Server.h.
{
             listen(address, channel, LISTEN_BACKLOG, onError);
         }
References web::http::tls::rf::Server< Request, Response >::listen(), and LISTEN_BACKLOG.
listen() [5/5]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::tls::rf::Server< Request, Response >::listen (uint8_t channel, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 42 of file Server.h.
{
             listen(channel, LISTEN_BACKLOG, onError);
         }
References web::http::tls::rf::Server< Request, Response >::listen(), and LISTEN_BACKLOG.
The documentation for this class was generated from the following file:
web/http/tls/rf/Server.h