snode.c: net::config::ConfigTls Class Reference
net::config::ConfigTls Class Reference
#include <ConfigTls.h>
Public Member Functions
ConfigTls ()
utils::Timeval getInitTimeout () const
utils::Timeval getShutdownTimeout () const
void setInitTimeout (const utils::Timeval &newInitTimeoutSet)
void setShutdownTimeout (const utils::Timeval &newShutdownTimeoutSet)
Private Attributes
CLI::App * tlsSc = nullptr
CLI::Option * initTimeoutOpt = nullptr
CLI::Option * shutdownTimeoutOpt = nullptr
utils::Timeval initTimeout
utils::Timeval initTimeoutSet = -1
utils::Timeval shutdownTimeout
utils::Timeval shutdownTimeoutSet = -1
Additional Inherited Members
Protected Member Functions inherited from net::config::ConfigBase
CLI::App * add_subcommand (const std::string &name, const std::string &description="")
CLI::Option * add_option (const std::string &name, int &variable, const std::string &description)
void parse (bool forceError=false) const
ConfigBase ()=default
ConfigBase (const std::string &name)
ConfigBase (const ConfigBase &)=delete
ConfigBase & operator= (const ConfigBase &)=delete
virtual ~ConfigBase ()=default
const std::string & getName () const
Detailed Description
Definition at line 37 of file ConfigTls.h.
Constructor & Destructor Documentation
ConfigTls()
net::config::ConfigTls::ConfigTls () explicit
Definition at line 39 of file ConfigTls.cpp.
{
         if (!getName().empty()) {
             tlsSc = add_subcommand("tls", "Options for SSL/TLS behaviour");
             tlsSc->group("Option groups");
             initTimeoutOpt = tlsSc->add_option("--init-timeout", initTimeout, "SSL/TLS initialization timeout");
             initTimeoutOpt->type_name("[sec]");
             initTimeoutOpt->default_val(DEFAULT_INITTIMEOUT);
             shutdownTimeoutOpt = tlsSc->add_option("--shutdown-timeout", shutdownTimeout, "SSL/TLS shutdown timeout");
             shutdownTimeoutOpt->type_name("[sec]");
             shutdownTimeoutOpt->default_val(DEFAULT_SHUTDOWNTIMEOUT);
         } else {
             initTimeout = DEFAULT_INITTIMEOUT;
             shutdownTimeout = DEFAULT_SHUTDOWNTIMEOUT;
         }
     }
References CLI::App::add_option(), net::config::ConfigBase::add_subcommand(), DEFAULT_INITTIMEOUT, DEFAULT_SHUTDOWNTIMEOUT, CLI::Option::default_val(), net::config::ConfigBase::getName(), CLI::App::group(), initTimeout, initTimeoutOpt, shutdownTimeout, shutdownTimeoutOpt, tlsSc, and CLI::Option::type_name().
Member Function Documentation
getInitTimeout()
utils::Timeval net::config::ConfigTls::getInitTimeout () const
Definition at line 57 of file ConfigTls.cpp.
{
         utils::Timeval initTimeout = this->initTimeout;
         if (initTimeoutSet >= 0 && initTimeoutOpt != nullptr && initTimeoutOpt->count() == 0) {
             initTimeout = initTimeoutSet;
         }
         return initTimeout;
     }
References CLI::Option::count(), initTimeout, initTimeoutOpt, and initTimeoutSet.
getShutdownTimeout()
utils::Timeval net::config::ConfigTls::getShutdownTimeout () const
Definition at line 67 of file ConfigTls.cpp.
{
         utils::Timeval shutdownTimeout = this->shutdownTimeout;
         if (shutdownTimeoutSet >= 0 && shutdownTimeoutOpt != nullptr && shutdownTimeoutOpt->count() == 0) {
             shutdownTimeout = shutdownTimeoutSet;
         }
         return shutdownTimeout;
     }
References CLI::Option::count(), shutdownTimeout, shutdownTimeoutOpt, and shutdownTimeoutSet.
setInitTimeout()
void net::config::ConfigTls::setInitTimeout (const utils::Timeval & newInitTimeoutSet)
Definition at line 77 of file ConfigTls.cpp.
{
         initTimeoutSet = newInitTimeoutSet;
     }
References initTimeoutSet.
setShutdownTimeout()
void net::config::ConfigTls::setShutdownTimeout (const utils::Timeval & newShutdownTimeoutSet)
Definition at line 81 of file ConfigTls.cpp.
{
         shutdownTimeoutSet = newShutdownTimeoutSet;
     }
References shutdownTimeoutSet.
Member Data Documentation
initTimeout
utils::Timeval net::config::ConfigTls::initTimeout private
Definition at line 52 of file ConfigTls.h.
Referenced by ConfigTls(), and getInitTimeout().
initTimeoutOpt
CLI::Option* net::config::ConfigTls::initTimeoutOpt = nullptr private
Definition at line 49 of file ConfigTls.h.
Referenced by ConfigTls(), and getInitTimeout().
initTimeoutSet
utils::Timeval net::config::ConfigTls::initTimeoutSet = -1 private
Definition at line 53 of file ConfigTls.h.
Referenced by getInitTimeout(), and setInitTimeout().
shutdownTimeout
utils::Timeval net::config::ConfigTls::shutdownTimeout private
Definition at line 55 of file ConfigTls.h.
Referenced by ConfigTls(), and getShutdownTimeout().
shutdownTimeoutOpt
CLI::Option* net::config::ConfigTls::shutdownTimeoutOpt = nullptr private
Definition at line 50 of file ConfigTls.h.
Referenced by ConfigTls(), and getShutdownTimeout().
shutdownTimeoutSet
utils::Timeval net::config::ConfigTls::shutdownTimeoutSet = -1 private
Definition at line 56 of file ConfigTls.h.
Referenced by getShutdownTimeout(), and setShutdownTimeout().
tlsSc
CLI::App* net::config::ConfigTls::tlsSc = nullptr private
Definition at line 48 of file ConfigTls.h.
Referenced by ConfigTls().
The documentation for this class was generated from the following files:
net/config/ConfigTls.h
net/config/ConfigTls.cpp