snode.c: core::DescriptorEventDispatcher Class Reference
core::DescriptorEventDispatcher Class Reference abstract
#include <DescriptorEventDispatcher.h>
Classes
class EventReceiverList
Public Member Functions
virtual ~DescriptorEventDispatcher ()=default
void publish (Event *event)
void enable (DescriptorEventReceiver *eventReceiver)
void disable (DescriptorEventReceiver *eventReceiver)
void suspend (DescriptorEventReceiver *eventReceiver)
void resume (DescriptorEventReceiver *eventReceiver)
void observeEnabledEvents (const utils::Timeval &currentTime)
virtual void dispatchActiveEvents ()=0
void dispatchImmediateEvents ()
void checkTimedOutEvents (const utils::Timeval &currentTime)
void unobserveDisabledEvents (const utils::Timeval &currentTime)
virtual void finishTick ()
int getObservedEventReceiverCount () const
int getMaxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void stop ()
Protected Member Functions
DescriptorEventDispatcher ()=default
virtual void modAdd (DescriptorEventReceiver *eventReceiver)=0
virtual void modDel (DescriptorEventReceiver *eventReceiver)=0
virtual void modOn (DescriptorEventReceiver *eventReceiver)=0
virtual void modOff (DescriptorEventReceiver *eventReceiver)=0
Protected Attributes
std::map< int, EventReceiverList > enabledEventReceiver
std::map< int, EventReceiverList > observedEventReceiver
std::map< int, EventReceiverList > disabledEventReceiver
unsigned long eventCounter = 0
Private Member Functions
DescriptorEventDispatcher (const DescriptorEventDispatcher &)=delete
DescriptorEventDispatcher & operator= (const DescriptorEventDispatcher &)=delete
Detailed Description
Definition at line 40 of file DescriptorEventDispatcher.h.
Constructor & Destructor Documentation
DescriptorEventDispatcher() [1/2]
core::DescriptorEventDispatcher::DescriptorEventDispatcher (const DescriptorEventDispatcher &) private delete
DescriptorEventDispatcher() [2/2]
core::DescriptorEventDispatcher::DescriptorEventDispatcher () protected default
~DescriptorEventDispatcher()
virtual core::DescriptorEventDispatcher::~DescriptorEventDispatcher () virtual default
Member Function Documentation
checkTimedOutEvents()
void core::DescriptorEventDispatcher::checkTimedOutEvents (const utils::Timeval & currentTime)
Definition at line 125 of file DescriptorEventDispatcher.cpp.
{
         for ([[maybe_unused]] const auto& [fd, eventReceivers] : observedEventReceiver) { // cppcheck-suppress unusedVariable
             eventReceivers.front()->checkTimeout(currentTime);
         }
     }
References observedEventReceiver.
disable()
void core::DescriptorEventDispatcher::disable (core::DescriptorEventReceiver * eventReceiver)
Definition at line 55 of file DescriptorEventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         if (enabledEventReceiver.contains(fd) && enabledEventReceiver[fd].contains(eventReceiver)) {
             // same tick as enable
             eventReceiver->disabled();
             if (eventReceiver->getObservationCounter() > 0) {
                 enabledEventReceiver[fd].remove(eventReceiver);
             }
         } else if (eventReceiver->isEnabled() &&
                    (!disabledEventReceiver.contains(fd) || !disabledEventReceiver[fd].contains(eventReceiver))) {
             // next tick as enable
             disabledEventReceiver[fd].push_back(eventReceiver);
         } else {
             LOG(WARNING) << "EventReceiver double disable " << fd;
         }
     }
References core::DescriptorEventReceiver::disabled(), disabledEventReceiver, enabledEventReceiver, core::Observer::getObservationCounter(), core::DescriptorEventReceiver::getRegisteredFd(), and core::DescriptorEventReceiver::isEnabled().
Referenced by core::DescriptorEventReceiver::disable().
dispatchActiveEvents()
virtual void core::DescriptorEventDispatcher::dispatchActiveEvents () pure virtual
Implemented in core::select::DescriptorEventDispatcher, core::poll::DescriptorEventDispatcher, and core::epoll::DescriptorEventDispatcher.
dispatchImmediateEvents()
void core::DescriptorEventDispatcher::dispatchImmediateEvents ()
Definition at line 115 of file DescriptorEventDispatcher.cpp.
{
         for (const auto& [fd, eventReceivers] : observedEventReceiver) { // cppcheck-suppress unusedVariable
             core::DescriptorEventReceiver* eventReceiver = eventReceivers.front();
             if (eventReceiver->continueImmediately() && !eventReceiver->isSuspended()) {
                 eventCounter++;
                 eventReceiver->publish();
             }
         }
     }
References core::DescriptorEventReceiver::continueImmediately(), eventCounter, core::DescriptorEventReceiver::isSuspended(), observedEventReceiver, and core::EventReceiver::publish().
enable()
void core::DescriptorEventDispatcher::enable (core::DescriptorEventReceiver * eventReceiver)
Definition at line 40 of file DescriptorEventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         if (disabledEventReceiver.contains(fd) && disabledEventReceiver[fd].contains(eventReceiver)) {
             // same tick as disable
             disabledEventReceiver[fd].remove(eventReceiver);
         } else if (!eventReceiver->isEnabled() &&
                    (!enabledEventReceiver.contains(fd) || !enabledEventReceiver[fd].contains(eventReceiver))) {
             // next tick as disable
             enabledEventReceiver[fd].push_back(eventReceiver);
         } else {
             LOG(WARNING) << "EventReceiver double enable " << fd;
         }
     }
References disabledEventReceiver, enabledEventReceiver, core::DescriptorEventReceiver::getRegisteredFd(), and core::DescriptorEventReceiver::isEnabled().
Referenced by core::DescriptorEventReceiver::enable().
finishTick()
void core::DescriptorEventDispatcher::finishTick () virtual
Reimplemented in core::poll::DescriptorEventDispatcher, and core::epoll::DescriptorEventDispatcher.
Definition at line 169 of file DescriptorEventDispatcher.cpp.
{
     }
Referenced by unobserveDisabledEvents().
getMaxFd()
int core::DescriptorEventDispatcher::getMaxFd () const
Definition at line 176 of file DescriptorEventDispatcher.cpp.
{
         int maxFd = -1;
         if (!observedEventReceiver.empty()) {
             maxFd = observedEventReceiver.rbegin()->first;
         }
         return maxFd;
     }
References observedEventReceiver.
getNextTimeout()
utils::Timeval core::DescriptorEventDispatcher::getNextTimeout (const utils::Timeval & currentTime) const
Definition at line 186 of file DescriptorEventDispatcher.cpp.
{
         utils::Timeval nextTimeout = core::DescriptorEventReceiver::TIMEOUT::MAX;
         for (const auto& [fd, eventReceivers] : observedEventReceiver) { // cppcheck-suppress unusedVariable
             const core::DescriptorEventReceiver* eventReceiver = eventReceivers.front();
             if (eventReceiver->isEnabled()) {
                 if (!eventReceiver->isSuspended() && eventReceiver->continueImmediately()) {
                     nextTimeout = 0;
                 } else {
                     nextTimeout = std::min(eventReceiver->getTimeout(currentTime), nextTimeout);
                 }
             } else {
                 nextTimeout = 0;
             }
         }
         return nextTimeout;
     }
References core::DescriptorEventReceiver::continueImmediately(), core::DescriptorEventReceiver::getTimeout(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::TIMEOUT::MAX, and observedEventReceiver.
getObservedEventReceiverCount()
int core::DescriptorEventDispatcher::getObservedEventReceiverCount () const
Definition at line 172 of file DescriptorEventDispatcher.cpp.
{
         return static_cast<int>(observedEventReceiver.size());
     }
References observedEventReceiver.
modAdd()
virtual void core::DescriptorEventDispatcher::modAdd (DescriptorEventReceiver * eventReceiver) protected pure virtual
Implemented in core::select::DescriptorEventDispatcher, core::poll::DescriptorEventDispatcher, and core::epoll::DescriptorEventDispatcher.
Referenced by observeEnabledEvents().
modDel()
virtual void core::DescriptorEventDispatcher::modDel (DescriptorEventReceiver * eventReceiver) protected pure virtual
Implemented in core::select::DescriptorEventDispatcher, core::poll::DescriptorEventDispatcher, and core::epoll::DescriptorEventDispatcher.
Referenced by unobserveDisabledEvents().
modOff()
virtual void core::DescriptorEventDispatcher::modOff (DescriptorEventReceiver * eventReceiver) protected pure virtual
Implemented in core::select::DescriptorEventDispatcher, core::poll::DescriptorEventDispatcher, and core::epoll::DescriptorEventDispatcher.
Referenced by observeEnabledEvents(), suspend(), and unobserveDisabledEvents().
modOn()
virtual void core::DescriptorEventDispatcher::modOn (DescriptorEventReceiver * eventReceiver) protected pure virtual
Implemented in core::select::DescriptorEventDispatcher, core::poll::DescriptorEventDispatcher, and core::epoll::DescriptorEventDispatcher.
Referenced by resume(), and unobserveDisabledEvents().
observeEnabledEvents()
void core::DescriptorEventDispatcher::observeEnabledEvents (const utils::Timeval & currentTime)
Definition at line 97 of file DescriptorEventDispatcher.cpp.
{
         for (const auto& [fd, eventReceivers] : enabledEventReceiver) { // cppcheck-suppress unassignedVariable
             for (core::DescriptorEventReceiver* eventReceiver : eventReceivers) {
                 if (eventReceiver->isEnabled()) {
                     eventReceiver->triggered(currentTime);
                     observedEventReceiver[fd].push_front(eventReceiver);
                     modAdd(eventReceiver);
                     if (eventReceiver->isSuspended()) {
                         modOff(eventReceiver);
                     }
                 } else {
                     eventReceiver->unobservedEvent();
                 }
             }
         }
         enabledEventReceiver.clear();
     }
References enabledEventReceiver, modAdd(), modOff(), and observedEventReceiver.
operator=()
DescriptorEventDispatcher& core::DescriptorEventDispatcher::operator= (const DescriptorEventDispatcher &) private delete
publish()
void core::DescriptorEventDispatcher::publish (Event * event)
resume()
void core::DescriptorEventDispatcher::resume (core::DescriptorEventReceiver * eventReceiver)
Definition at line 85 of file DescriptorEventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         if (eventReceiver->isSuspended()) {
             if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                 modOn(eventReceiver);
             }
         } else {
             LOG(WARNING) << "EventReceiver double resume " << fd;
         }
     }
References core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::isSuspended(), modOn(), and observedEventReceiver.
Referenced by core::DescriptorEventReceiver::resume().
stop()
void core::DescriptorEventDispatcher::stop ()
Definition at line 206 of file DescriptorEventDispatcher.cpp.
{
         for (const auto& [fd, eventReceivers] : observedEventReceiver) { // cppcheck-suppress unusedVariable
             for (core::DescriptorEventReceiver* eventReceiver : eventReceivers) {
                 if (eventReceiver->isEnabled()) {
                     eventReceiver->terminate();
                 }
             }
         }
     }
References observedEventReceiver.
suspend()
void core::DescriptorEventDispatcher::suspend (core::DescriptorEventReceiver * eventReceiver)
Definition at line 73 of file DescriptorEventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         if (!eventReceiver->isSuspended()) {
             if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                 modOff(eventReceiver);
             }
         } else {
             LOG(WARNING) << "EventReceiver double suspend";
         }
     }
References core::DescriptorEventReceiver::getRegisteredFd(), core::DescriptorEventReceiver::isSuspended(), modOff(), and observedEventReceiver.
Referenced by core::DescriptorEventReceiver::suspend().
unobserveDisabledEvents()
void core::DescriptorEventDispatcher::unobserveDisabledEvents (const utils::Timeval & currentTime)
Definition at line 131 of file DescriptorEventDispatcher.cpp.
{
         std::map<int, EventReceiverList> unobservedEventReceiver;
         for (const auto& [fd, eventReceivers] : disabledEventReceiver) {
             for (core::DescriptorEventReceiver* eventReceiver : eventReceivers) {
                 observedEventReceiver[fd].remove(eventReceiver);
                 if (observedEventReceiver[fd].empty()) {
                     modDel(eventReceiver);
                     observedEventReceiver.erase(fd);
                 } else {
                     observedEventReceiver[fd].front()->triggered(currentTime);
                     if (!observedEventReceiver[fd].front()->isSuspended()) {
                         modOn(observedEventReceiver[fd].front());
                     } else {
                         modOff(observedEventReceiver[fd].front());
                     }
                 }
                 eventReceiver->disabled();
                 if (eventReceiver->getObservationCounter() == 0) {
                     unobservedEventReceiver[fd].push_back(eventReceiver);
                 }
             }
         }
         disabledEventReceiver.clear();
         if (!unobservedEventReceiver.empty()) {
             for (const auto& [fd, eventReceivers] : unobservedEventReceiver) { // cppcheck-suppress unusedVariable
                 for (DescriptorEventReceiver* eventReceiver : eventReceivers) {
                     eventReceiver->unobservedEvent();
                 }
             }
             unobservedEventReceiver.clear();
             finishTick();
         }
     }
References disabledEventReceiver, finishTick(), modDel(), modOff(), modOn(), and observedEventReceiver.
Member Data Documentation
disabledEventReceiver
std::map<int, EventReceiverList> core::DescriptorEventDispatcher::disabledEventReceiver protected
Definition at line 89 of file DescriptorEventDispatcher.h.
Referenced by disable(), enable(), and unobserveDisabledEvents().
enabledEventReceiver
std::map<int, EventReceiverList> core::DescriptorEventDispatcher::enabledEventReceiver protected
Definition at line 87 of file DescriptorEventDispatcher.h.
Referenced by disable(), enable(), and observeEnabledEvents().
eventCounter
unsigned long core::DescriptorEventDispatcher::eventCounter = 0 protected
Definition at line 91 of file DescriptorEventDispatcher.h.
Referenced by core::epoll::DescriptorEventDispatcher::dispatchActiveEvents(), core::poll::DescriptorEventDispatcher::dispatchActiveEvents(), core::select::DescriptorEventDispatcher::dispatchActiveEvents(), and dispatchImmediateEvents().
observedEventReceiver
std::map<int, EventReceiverList> core::DescriptorEventDispatcher::observedEventReceiver protected
Definition at line 88 of file DescriptorEventDispatcher.h.
Referenced by checkTimedOutEvents(), core::poll::DescriptorEventDispatcher::dispatchActiveEvents(), core::select::DescriptorEventDispatcher::dispatchActiveEvents(), dispatchImmediateEvents(), getMaxFd(), getNextTimeout(), getObservedEventReceiverCount(), observeEnabledEvents(), resume(), stop(), suspend(), and unobserveDisabledEvents().
The documentation for this class was generated from the following files:
core/DescriptorEventDispatcher.h
core/DescriptorEventDispatcher.cpp