snode.c: net::Config Class Reference
net::Config Class Reference
#include <Config.h>
Public Member Functions
Config (const std::string &name)
const std::string & getName () const
int getReadTimeout () const
int getWriteTimeout () const
Public Attributes
CLI::App * serverSc = nullptr
Protected Member Functions
void finish ()
Private Attributes
CLI::App * serverConnectionSc = nullptr
CLI::Option * serverConnectionReadTimeoutOpt = nullptr
CLI::Option * serverConnectionWriteTimeoutOpt = nullptr
std::string name
int readTimeout
int writeTimeout
Detailed Description
Definition at line 35 of file Config.h.
Constructor & Destructor Documentation
Config()
net::Config::Config (const std::string & name) explicit
Definition at line 30 of file Config.cpp.
         : name(name) {
         serverSc = utils::Config::instance().add_subcommand(name, "Server configuration");
         serverSc->configurable();
     }
References utils::Config::add_subcommand(), CLI::App::configurable(), utils::Config::instance(), name, and serverSc.
Member Function Documentation
finish()
void net::Config::finish () protected
Definition at line 36 of file Config.cpp.
{
         serverConnectionSc = serverSc->add_subcommand("connection");
         serverConnectionSc->description("Options for established client connections");
         serverConnectionSc->configurable();
         serverConnectionReadTimeoutOpt = serverConnectionSc->add_option("-r,--readtimeout", readTimeout, "Read timeout");
         serverConnectionReadTimeoutOpt->type_name("[sec]");
         serverConnectionReadTimeoutOpt->default_val(60);
         serverConnectionReadTimeoutOpt->configurable();
         serverConnectionWriteTimeoutOpt = serverConnectionSc->add_option("-w,--writetimeout", writeTimeout, "Write timeout");
         serverConnectionWriteTimeoutOpt->type_name("[sec]");
         serverConnectionWriteTimeoutOpt->default_val(60);
         serverConnectionWriteTimeoutOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), readTimeout, serverConnectionReadTimeoutOpt, serverConnectionSc, serverConnectionWriteTimeoutOpt, serverSc, CLI::Option::type_name(), and writeTimeout.
Referenced by net::in::stream::ServerConfig::ServerConfig(), net::in6::stream::ServerConfig::ServerConfig(), net::l2::stream::ServerConfig::ServerConfig(), net::rf::stream::ServerConfig::ServerConfig(), and net::un::stream::ServerConfig::ServerConfig().
getName()
const std::string & net::Config::getName () const
Definition at line 52 of file Config.cpp.
{
         return name;
     }
References name.
getReadTimeout()
int net::Config::getReadTimeout () const
Definition at line 56 of file Config.cpp.
{
         return readTimeout;
     }
References readTimeout.
getWriteTimeout()
int net::Config::getWriteTimeout () const
Definition at line 60 of file Config.cpp.
{
         return writeTimeout;
     }
References writeTimeout.
Member Data Documentation
name
std::string net::Config::name private
Definition at line 56 of file Config.h.
Referenced by Config(), getName(), and net::un::stream::ServerConfig::ServerConfig().
readTimeout
int net::Config::readTimeout private
Definition at line 57 of file Config.h.
Referenced by finish(), and getReadTimeout().
serverConnectionReadTimeoutOpt
CLI::Option* net::Config::serverConnectionReadTimeoutOpt = nullptr private
Definition at line 53 of file Config.h.
Referenced by finish().
serverConnectionSc
CLI::App* net::Config::serverConnectionSc = nullptr private
Definition at line 52 of file Config.h.
Referenced by finish().
serverConnectionWriteTimeoutOpt
CLI::Option* net::Config::serverConnectionWriteTimeoutOpt = nullptr private
Definition at line 54 of file Config.h.
Referenced by finish().
serverSc
CLI::App* net::Config::serverSc = nullptr
Definition at line 49 of file Config.h.
Referenced by Config(), finish(), net::in::stream::ServerConfig::parse(), net::in6::stream::ServerConfig::parse(), net::l2::stream::ServerConfig::parse(), net::rf::stream::ServerConfig::parse(), net::in::stream::ServerConfig::ServerConfig(), net::in6::stream::ServerConfig::ServerConfig(), net::l2::stream::ServerConfig::ServerConfig(), net::rf::stream::ServerConfig::ServerConfig(), net::ServerConfig::ServerConfig(), and net::un::stream::ServerConfig::ServerConfig().
writeTimeout
int net::Config::writeTimeout private
Definition at line 58 of file Config.h.
Referenced by finish(), and getWriteTimeout().
The documentation for this class was generated from the following files:
net/Config.h
net/Config.cpp