snode.c: CLI::IncorrectConstruction Class Reference
CLI::IncorrectConstruction Class Reference
Errors
Thrown when an option is set to conflicting values (non-vector and multi args, for example)
#include <CLI11.hpp>
Public Member Functions
IncorrectConstruction (std::string msg, ExitCodes exit_code)
IncorrectConstruction (std::string msg, int exit_code)
IncorrectConstruction (std::string msg)
Public Member Functions inherited from CLI::ConstructionError
ConstructionError (std::string msg, ExitCodes exit_code)
ConstructionError (std::string msg, int exit_code)
Public Member Functions inherited from CLI::Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static IncorrectConstruction PositionalFlag (std::string name)
static IncorrectConstruction Set0Opt (std::string name)
static IncorrectConstruction SetFlag (std::string name)
static IncorrectConstruction ChangeNotVector (std::string name)
static IncorrectConstruction AfterMultiOpt (std::string name)
static IncorrectConstruction MissingOption (std::string name)
static IncorrectConstruction MultiOptionPolicy (std::string name)
Protected Member Functions
IncorrectConstruction (std::string ename, std::string msg, int exit_code)
IncorrectConstruction (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from CLI::ConstructionError
ConstructionError (std::string ename, std::string msg, int exit_code)
ConstructionError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when an option is set to conflicting values (non-vector and multi args, for example)
Definition at line 659 of file CLI11.hpp.
Constructor & Destructor Documentation
IncorrectConstruction() [1/5]
CLI::IncorrectConstruction::IncorrectConstruction (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 660 of file CLI11.hpp.
Referenced by AfterMultiOpt(), ChangeNotVector(), MissingOption(), MultiOptionPolicy(), PositionalFlag(), Set0Opt(), and SetFlag().
IncorrectConstruction() [2/5]
CLI::IncorrectConstruction::IncorrectConstruction (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 660 of file CLI11.hpp.
IncorrectConstruction() [3/5]
CLI::IncorrectConstruction::IncorrectConstruction (std::string msg, ExitCodes exit_code) inline
Definition at line 660 of file CLI11.hpp.
IncorrectConstruction() [4/5]
CLI::IncorrectConstruction::IncorrectConstruction (std::string msg, int exit_code) inline
Definition at line 660 of file CLI11.hpp.
IncorrectConstruction() [5/5]
CLI::IncorrectConstruction::IncorrectConstruction (std::string msg) inline explicit
Definition at line 661 of file CLI11.hpp.
Member Function Documentation
AfterMultiOpt()
static IncorrectConstruction CLI::IncorrectConstruction::AfterMultiOpt (std::string name) inline static
Definition at line 674 of file CLI11.hpp.
{
             return IncorrectConstruction(name + ": You can't change expected arguments after you've changed the multi option policy!");
         }
References IncorrectConstruction().
ChangeNotVector()
static IncorrectConstruction CLI::IncorrectConstruction::ChangeNotVector (std::string name) inline static
Definition at line 671 of file CLI11.hpp.
{
             return IncorrectConstruction(name + ": You can only change the expected arguments for vectors");
         }
References IncorrectConstruction().
MissingOption()
static IncorrectConstruction CLI::IncorrectConstruction::MissingOption (std::string name) inline static
Definition at line 677 of file CLI11.hpp.
{
             return IncorrectConstruction("Option " + name + " is not defined");
         }
References IncorrectConstruction().
Referenced by CLI::Option::excludes(), and CLI::Option::needs().
MultiOptionPolicy()
static IncorrectConstruction CLI::IncorrectConstruction::MultiOptionPolicy (std::string name) inline static
Definition at line 680 of file CLI11.hpp.
{
             return IncorrectConstruction(name + ": multi_option_policy only works for flags and exact value options");
         }
References IncorrectConstruction().
PositionalFlag()
static IncorrectConstruction CLI::IncorrectConstruction::PositionalFlag (std::string name) inline static
Definition at line 662 of file CLI11.hpp.
{
             return IncorrectConstruction(name + ": Flags cannot be positional");
         }
References IncorrectConstruction().
Referenced by CLI::App::_add_flag_internal().
Set0Opt()
static IncorrectConstruction CLI::IncorrectConstruction::Set0Opt (std::string name) inline static
Definition at line 665 of file CLI11.hpp.
{
             return IncorrectConstruction(name + ": Cannot set 0 expected, use a flag instead");
         }
References IncorrectConstruction().
SetFlag()
static IncorrectConstruction CLI::IncorrectConstruction::SetFlag (std::string name) inline static
Definition at line 668 of file CLI11.hpp.
{
             return IncorrectConstruction(name + ": Cannot set an expected number for flags");
         }
References IncorrectConstruction().
The documentation for this class was generated from the following file:
utils/CLI11.hpp