snode.c: net::un::stream::ConfigBind Class Reference
net::un::stream::ConfigBind Class Reference
#include <ConfigBind.h>
Public Member Functions
ConfigBind (CLI::App *baseSc)
const std::string & getBindSunPath () const
net::un::SocketAddress getBindAddress () const
Protected Attributes
CLI::App * bindSc = nullptr
CLI::Option * bindSunPathOpt = nullptr
std::string bindSunPath = ""
Detailed Description
Definition at line 37 of file ConfigBind.h.
Constructor & Destructor Documentation
ConfigBind()
net::un::stream::ConfigBind::ConfigBind (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigBind.cpp.
{
         bindSc = baseSc->add_subcommand("bind");
         bindSc->group("Sub-Options (use -h,--help on them)");
         bindSc->description("Server socket bind options");
         bindSc->configurable();
         bindSunPathOpt = bindSc->add_option("-p,--path", bindSunPath, "Unix domain socket path");
         bindSunPathOpt->type_name("[filesystem path]");
         bindSunPathOpt->default_val("/tmp/sun.sock");
         bindSunPathOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindSc, bindSunPath, bindSunPathOpt, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), CLI::App::group(), and CLI::Option::type_name().
Member Function Documentation
getBindAddress()
SocketAddress net::un::stream::ConfigBind::getBindAddress () const
Definition at line 45 of file ConfigBind.cpp.
{
         return net::un::SocketAddress(bindSunPath);
     }
References bindSunPath.
getBindSunPath()
const std::string & net::un::stream::ConfigBind::getBindSunPath () const
Definition at line 41 of file ConfigBind.cpp.
{
         return bindSunPath;
     }
References bindSunPath.
Member Data Documentation
bindSc
CLI::App* net::un::stream::ConfigBind::bindSc = nullptr protected
Definition at line 46 of file ConfigBind.h.
Referenced by ConfigBind(), and net::un::stream::ServerConfig::required().
bindSunPath
std::string net::un::stream::ConfigBind::bindSunPath = "" protected
Definition at line 49 of file ConfigBind.h.
Referenced by ConfigBind(), getBindAddress(), and getBindSunPath().
bindSunPathOpt
CLI::Option* net::un::stream::ConfigBind::bindSunPathOpt = nullptr protected
Definition at line 47 of file ConfigBind.h.
Referenced by ConfigBind(), and net::un::stream::ServerConfig::required().
The documentation for this class was generated from the following files:
net/un/stream/ConfigBind.h
net/un/stream/ConfigBind.cpp