snode.c: net::rc::stream::ClientSocket< ConfigT > Class Template Reference
net::rc::stream::ClientSocket< ConfigT > Class Template Reference
#include <ClientSocket.h>
Public Member Functions
void connect (const std::string &address, uint8_t channel, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &localAddress, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &localAddress, uint8_t bindChannel, const std::function< void(const SocketAddress &, int)> &onError)
Public Member Functions inherited from net::ClientSocket< ConfigT, net::rc::stream::Socket >
virtual void connect (const std::function< void(const SocketAddress &, int)> &onError) const=0
void connect (const SocketAddress &remoteAddress, const SocketAddress &localAddress, const std::function< void(const SocketAddress &, int)> &onError) const
void connect (const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, int)> &onError) const
Config & getConfig ()
Protected Member Functions
ClientSocket (const std::string &name)
Protected Member Functions inherited from net::ClientSocket< ConfigT, net::rc::stream::Socket >
ClientSocket (const std::string &name)
ClientSocket (const ClientSocket &)=default
virtual ~ClientSocket ()=default
Private Types
using Super = net::ClientSocket< ConfigT, net::rc::stream::Socket >
Additional Inherited Members
Public Types inherited from net::ClientSocket< ConfigT, net::rc::stream::Socket >
using Config = ConfigT
using Socket = net::rc::stream::Socket
using SocketAddress = typename Socket::SocketAddress
Protected Attributes inherited from net::ClientSocket< ConfigT, net::rc::stream::Socket >
std::shared_ptr< Config > config
Detailed Description
template<typename ConfigT>
class net::rc::stream::ClientSocket< ConfigT >
Definition at line 36 of file ClientSocket.h.
Member Typedef Documentation
Super
template<typename ConfigT > using net::rc::stream::ClientSocket< ConfigT >::Super = net::ClientSocket<ConfigT, net::rc::stream::Socket> private
Definition at line 37 of file ClientSocket.h.
Constructor & Destructor Documentation
ClientSocket()
template<typename Config > net::rc::stream::ClientSocket< Config >::ClientSocket (const std::string & name) explicit protected
Definition at line 28 of file ClientSocket.hpp.
         : Super(name) {
     }
Member Function Documentation
connect() [1/3]
template<typename Config > void net::rc::stream::ClientSocket< Config >::connect (const std::string & address, uint8_t channel, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 33 of file ClientSocket.hpp.
{
         connect(SocketAddress(address, channel), onError);
     }
References core::system::connect().
connect() [2/3]
template<typename Config > void net::rc::stream::ClientSocket< Config >::connect (const std::string & address, uint8_t channel, const std::string & localAddress, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 40 of file ClientSocket.hpp.
{
         connect(SocketAddress(address, channel), SocketAddress(localAddress), onError);
     }
References core::system::connect().
connect() [3/3]
template<typename Config > void net::rc::stream::ClientSocket< Config >::connect (const std::string & address, uint8_t channel, const std::string & localAddress, uint8_t bindChannel, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 48 of file ClientSocket.hpp.
{
         connect(SocketAddress(address, channel), SocketAddress(localAddress, bindChannel), onError);
     }
References core::system::connect().
The documentation for this class was generated from the following files:
net/rc/stream/ClientSocket.h
net/rc/stream/ClientSocket.hpp