snode.c: utils::Config Class Reference
utils::Config Class Reference
#include <Config.h>
Static Public Member Functions
static int init (int argc, char *argv[])
static void prepare ()
static void terminate ()
static CLI::App * add_subcommand (const std::string &subcommand_name, const std::string &subcommand_description)
static std::string getApplicationName ()
static int parse (bool stopOnError=false)
Private Member Functions
Config ()=delete
Config (const Config &)=delete
~Config ()=delete
Config & operator= (const Config &)=delete
Static Private Attributes
static int argc = 0
static char ** argv = nullptr
static CLI::App app
static std::string name
static bool startDaemon = false
static bool stopDaemon = false
static std::string outputConfigFile
static bool dumpConfig = false
static bool forceLogFile = false
static bool showConfig = false
static std::string logFile
static std::string defaultConfDir
static std::string defaultLogDir
static std::string defaultPidDir
Detailed Description
Definition at line 34 of file Config.h.
Constructor & Destructor Documentation
Config() [1/2]
utils::Config::Config () private delete
Config() [2/2]
utils::Config::Config (const Config &) private delete
~Config()
utils::Config::~Config () private delete
Member Function Documentation
add_subcommand()
CLI::App * utils::Config::add_subcommand (const std::string & subcommand_name, const std::string & subcommand_description) static
Definition at line 205 of file Config.cpp.
{
         return app.add_subcommand(subcommand_name, subcommand_description);
     }
References CLI::App::add_subcommand(), and app.
Referenced by net::config::ConfigBase::ConfigBase().
getApplicationName()
std::string utils::Config::getApplicationName () static
Definition at line 209 of file Config.cpp.
{
         return name;
     }
References name.
init()
int utils::Config::init (int argc, char * argv[]) static
Definition at line 70 of file Config.cpp.
{
         Config::argc = argc;
         Config::argv = argv;
         name = std::filesystem::path(argv[0]).filename();
         const char* homedir;
         if ((homedir = getenv("XDG_CONFIG_HOME")) == nullptr) {
             if ((homedir = getenv("HOME")) == nullptr) {
                 homedir = getpwuid(getuid())->pw_dir;
             }
         }
         defaultConfDir = homedir + CONFFILEPATH;
         defaultLogDir = homedir + LOGFILEPATH;
         defaultPidDir = homedir + PIDFILEPATH;
         logger::Logger::init(argc, argv);
         std::filesystem::create_directories(defaultConfDir);
         std::filesystem::permissions(
             defaultConfDir,
             (std::filesystem::perms::owner_all | std::filesystem::perms::group_read | std::filesystem::perms::group_exec) &
                 ~std::filesystem::perms::others_all);
         std::filesystem::create_directories(defaultLogDir);
         std::filesystem::permissions(
             defaultLogDir, (std::filesystem::perms::owner_all | std::filesystem::perms::group_all) & ~std::filesystem::perms::others_all);
         std::filesystem::create_directories(defaultPidDir);
         std::filesystem::permissions(
             defaultPidDir, (std::filesystem::perms::owner_all | std::filesystem::perms::group_all) & ~std::filesystem::perms::others_all);
         app.option_defaults()->take_first();
         app.option_defaults()->configurable();
         app.configurable();
         app.description("Configuration for application " + name);
         app.allow_extras();
         app.allow_config_extras();
         app.get_formatter()->column_width(40);
         CLI::Option* allHelpOpt = app.set_help_all_flag("--help-all", "Expand all help");
         allHelpOpt->configurable(false);
         CLI::Option* showConfigFlag = app.add_flag("-s,--show-config", showConfig, "Show current configuration and exit");
         showConfigFlag->configurable(false);
         CLI::Option* dumpConfigFlg =
             app.add_flag("-w{" + defaultConfDir + "/" + name + ".conf" + "},--write-config{" + defaultConfDir + "/" + name + ".conf" + "}",
                          outputConfigFile,
                          "Write config file");
         dumpConfigFlg->configurable(false);
         CLI::Option* logFileOpt = app.add_option("-l,--log-file", logFile, "Log to file");
         logFileOpt->default_val(defaultLogDir + "/" + name + ".log");
         logFileOpt->type_name("[path]");
         logFileOpt->excludes(showConfigFlag);
         CLI::Option* forceLogFileFlag =
             app.add_flag("-g,!-n,--force-log-file,!--no-log-file", forceLogFile, "Force writing logs to file for foureground applications");
         forceLogFileFlag->excludes(showConfigFlag);
         CLI::Option* startDaemonOpt = app.add_flag("-d,!-f,--daemonize,!--foreground", startDaemon, "Start application as daemon");
         startDaemonOpt->excludes(showConfigFlag);
         CLI::Option* stopDaemonOpt = app.add_flag("-k,--kill", stopDaemon, "Kill running daemon");
         stopDaemonOpt->disable_flag_override();
         stopDaemonOpt->configurable(false);
         parse();
         if (stopDaemon) {
             utils::Daemon::stopDaemon(defaultPidDir + "/" + name + ".pid");
             VLOG(0) << "Daemon killed";
             exit(0);
         } else {
             if (app["--help"]->count() == 0 && app["--help-all"]->count() == 0) {
                 app.set_config("--config", defaultConfDir + "/" + name + ".conf", "Read an config file", false);
             }
             parse(); // for daemonize, logfile and forceLogFile
             if (!showConfig) {
                 if (startDaemon) {
                     VLOG(0) << "Running as daemon";
                     utils::Daemon::startDaemon(defaultPidDir + "/" + name + ".pid");
                     logger::Logger::quiet();
                 } else {
                     if (!forceLogFile) {
                         logFile = "";
                     }
                     VLOG(0) << "Running in foureground";
                 }
                 if (!logFile.empty()) {
                     logger::Logger::logToFile(logFile);
                 }
             }
         }
         return 0;
     }
References CLI::App::add_flag(), CLI::App::add_option(), CLI::App::allow_config_extras(), CLI::App::allow_extras(), app, argc, argv, CONFFILEPATH, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), defaultConfDir, defaultLogDir, defaultPidDir, CLI::App::description(), CLI::Option::disable_flag_override(), CLI::Option::excludes(), forceLogFile, CLI::App::get_formatter(), logger::Logger::init(), logFile, LOGFILEPATH, logger::Logger::logToFile(), name, CLI::App::option_defaults(), outputConfigFile, parse(), PIDFILEPATH, logger::Logger::quiet(), CLI::App::set_config(), CLI::App::set_help_all_flag(), showConfig, startDaemon, utils::Daemon::startDaemon(), stopDaemon, utils::Daemon::stopDaemon(), CLI::OptionBase< CRTP >::take_first(), and CLI::Option::type_name().
Referenced by core::EventLoop::init().
operator=()
Config& utils::Config::operator= (const Config &) private delete
parse()
int utils::Config::parse (bool stopOnError = false) static
Definition at line 213 of file Config.cpp.
{
         try {
             int errnotmp = errno;
             Config::app.parse(argc, argv);
             errno = errnotmp;
         } catch (const CLI::ParseError& e) {
             if (stopOnError && !showConfig) {
                 exit(Config::app.exit(e));
             }
         }
         return 0;
     }
References app, argc, argv, CLI::App::parse(), and showConfig.
Referenced by init(), net::config::ConfigBase::parse(), and prepare().
prepare()
void utils::Config::prepare () static
Definition at line 177 of file Config.cpp.
{
         parse(app["--help"]->count() > 0 || app["--help-all"]->count() > 0);
         if (app["--write-config"]->count() > 0) {
             VLOG(0) << "Write config file " << outputConfigFile;
             std::ofstream confFile(outputConfigFile);
             confFile << app.config_to_str(true, true);
         }
         if (showConfig) {
             VLOG(0) << "Show current configuration\n" << app.config_to_str(true, true);
             exit(0);
         }
     }
References app, CLI::App::config_to_str(), outputConfigFile, parse(), and showConfig.
Referenced by core::EventLoop::start().
terminate()
void utils::Config::terminate () static
Definition at line 193 of file Config.cpp.
{
         if (startDaemon) {
             Daemon::erasePidFile(defaultPidDir + "/" + name + ".pid");
         }
         if (fcntl(STDIN_FILENO, F_SETFL, O_NONBLOCK) >= 0) {
             char buf[1024];
             while (read(STDIN_FILENO, buf, 1024) > 0)
                 ;
         }
     }
References defaultPidDir, utils::Daemon::erasePidFile(), name, core::system::read(), and startDaemon.
Referenced by core::EventLoop::free().
Member Data Documentation
app
CLI::App utils::Config::app static private
Definition at line 56 of file Config.h.
Referenced by add_subcommand(), init(), parse(), and prepare().
argc
int utils::Config::argc = 0 static private
Definition at line 54 of file Config.h.
Referenced by init(), and parse().
argv
char ** utils::Config::argv = nullptr static private
Definition at line 55 of file Config.h.
Referenced by init(), and parse().
defaultConfDir
std::string utils::Config::defaultConfDir static private
Definition at line 65 of file Config.h.
Referenced by init().
defaultLogDir
std::string utils::Config::defaultLogDir static private
Definition at line 66 of file Config.h.
Referenced by init().
defaultPidDir
std::string utils::Config::defaultPidDir static private
Definition at line 67 of file Config.h.
Referenced by init(), and terminate().
dumpConfig
bool utils::Config::dumpConfig = false static private
Definition at line 61 of file Config.h.
forceLogFile
bool utils::Config::forceLogFile = false static private
Definition at line 62 of file Config.h.
Referenced by init().
logFile
std::string utils::Config::logFile static private
Definition at line 64 of file Config.h.
Referenced by init().
name
std::string utils::Config::name static private
Definition at line 57 of file Config.h.
Referenced by getApplicationName(), init(), and terminate().
outputConfigFile
std::string utils::Config::outputConfigFile static private
Definition at line 60 of file Config.h.
Referenced by init(), and prepare().
showConfig
bool utils::Config::showConfig = false static private
Definition at line 63 of file Config.h.
Referenced by init(), parse(), and prepare().
startDaemon
bool utils::Config::startDaemon = false static private
Definition at line 58 of file Config.h.
Referenced by init(), and terminate().
stopDaemon
bool utils::Config::stopDaemon = false static private
Definition at line 59 of file Config.h.
Referenced by init().
The documentation for this class was generated from the following files:
utils/Config.h
utils/Config.cpp