snode.c: database::mariadb::MariaDBClientASyncAPI Class Reference
database::mariadb::MariaDBClientASyncAPI Class Reference abstract
#include <MariaDBClientASyncAPI.h>
Public Member Functions
MariaDBCommandSequence & query (const std::string &sql, const std::function< void(const MYSQL_ROW)> &onQuery, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & exec (const std::string &sql, const std::function< void(void)> &onExec, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & startTransactions (const std::function< void(void)> &onAutoCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & endTransactions (const std::function< void(void)> &onAutoCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & commit (const std::function< void(void)> &onCommit, const std::function< void(const std::string &, unsigned int)> &onError)
MariaDBCommandSequence & rollback (const std::function< void(void)> &onRollback, const std::function< void(const std::string &, unsigned int)> &onError)
Protected Member Functions
MariaDBClientASyncAPI ()=default
MariaDBClientASyncAPI (const MariaDBClientASyncAPI &)=default
virtual ~MariaDBClientASyncAPI ()=default
virtual MariaDBCommandSequence & execute_async (MariaDBCommand *mariaDBCommand)=0
Protected Attributes
MYSQL_RES * lastResult = nullptr
Detailed Description
Definition at line 40 of file MariaDBClientASyncAPI.h.
Constructor & Destructor Documentation
MariaDBClientASyncAPI() [1/2]
database::mariadb::MariaDBClientASyncAPI::MariaDBClientASyncAPI () protected default
MariaDBClientASyncAPI() [2/2]
database::mariadb::MariaDBClientASyncAPI::MariaDBClientASyncAPI (const MariaDBClientASyncAPI &) protected default
~MariaDBClientASyncAPI()
virtual database::mariadb::MariaDBClientASyncAPI::~MariaDBClientASyncAPI () protected virtual default
Member Function Documentation
commit()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::commit (const std::function< void(void)> & onCommit, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 76 of file MariaDBClientASyncAPI.cpp.
{
         return execute_async(new database::mariadb::commands::async::MariaDBCommitCommand(onCommit, onError));
     }
References execute_async().
endTransactions()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::endTransactions (const std::function< void(void)> & onAutoCommit, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 71 of file MariaDBClientASyncAPI.cpp.
{
         return execute_async(new database::mariadb::commands::async::MariaDBAutoCommitCommand(true, onAutoCommit, onError));
     }
References execute_async().
exec()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::exec (const std::string & sql, const std::function< void(void)> & onExec, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 60 of file MariaDBClientASyncAPI.cpp.
{
         return execute_async(new database::mariadb::commands::async::MariaDBExecCommand(sql, onExec, onError));
     }
References execute_async().
execute_async()
virtual MariaDBCommandSequence& database::mariadb::MariaDBClientASyncAPI::execute_async (MariaDBCommand * mariaDBCommand) protected pure virtual
Implemented in database::mariadb::MariaDBCommandSequence, and database::mariadb::MariaDBClient.
Referenced by commit(), endTransactions(), exec(), query(), rollback(), and startTransactions().
query()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::query (const std::string & sql, const std::function< void(const MYSQL_ROW)> & onQuery, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 38 of file MariaDBClientASyncAPI.cpp.
{
         return execute_async(new database::mariadb::commands::async::MariaDBQueryCommand(
                                  sql,
                                  [](void) -> void {
                                  },
                                  onError))
             .execute_async(new database::mariadb::commands::sync::MariaDBUseResultCommand(
                 [&lastResult = this->lastResult](MYSQL_RES* result) -> void {
                     lastResult = result;
                 },
                 onError))
             .execute_async(new database::mariadb::commands::async::MariaDBFetchRowCommand(lastResult, onQuery, onError))
             .execute_async(new database::mariadb::commands::async::MariaDBFreeResultCommand(
                 lastResult,
                 [this](void) -> void {
                     lastResult = nullptr;
                 },
                 onError));
     }
References database::mariadb::MariaDBCommandSequence::execute_async(), execute_async(), and lastResult.
rollback()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::rollback (const std::function< void(void)> & onRollback, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 81 of file MariaDBClientASyncAPI.cpp.
{
         return execute_async(new database::mariadb::commands::async::MariaDBRollbackCommand(onRollback, onError));
     }
References execute_async().
startTransactions()
MariaDBCommandSequence & database::mariadb::MariaDBClientASyncAPI::startTransactions (const std::function< void(void)> & onAutoCommit, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 66 of file MariaDBClientASyncAPI.cpp.
{
         return execute_async(new database::mariadb::commands::async::MariaDBAutoCommitCommand(false, onAutoCommit, onError));
     }
References execute_async().
Member Data Documentation
lastResult
MYSQL_RES* database::mariadb::MariaDBClientASyncAPI::lastResult = nullptr protected
Definition at line 68 of file MariaDBClientASyncAPI.h.
Referenced by query().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBClientASyncAPI.h
database/mariadb/MariaDBClientASyncAPI.cpp