snode.c: web::http::tls::in6::Server< Request, Response > Class Template Reference
web::http::tls::in6::Server< Request, Response > Class Template Reference
#include <Server.h>
Public Types
using SocketAddress = typename Super::SocketAddress
using SocketConnection = typename Super::SocketConnection
Public Types inherited from web::http::server::Server< net::in6::stream::tls::SocketServer, web::http::server::Request, web::http::server::Response >
using Request = web::http::server::Request
using Response = web::http::server::Response
using SocketConnection = typename Super::SocketConnection
using SocketAddress = typename SocketConnection::SocketAddress
Public Types inherited from core::socket::stream::tls::SocketServer< SocketServerT, SocketContextFactoryT >
using SocketConnection = typename Super::SocketConnection
using SocketAddress = typename Super::SocketAddress
Public Types inherited from core::socket::stream::SocketServer< SocketServerT, core::socket::stream::tls::SocketAcceptor, SocketContextFactoryT >
using SocketConnection = typename SocketAcceptor::SocketConnection
using SocketAddress = typename Super::SocketAddress
Public Member Functions
void listen (uint16_t port, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &ipOrHostname, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, int)> &onError)
Public Member Functions inherited from web::http::server::Server< net::in6::stream::tls::SocketServer, web::http::server::Request, web::http::server::Response >
Server (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &, Response &)> &onRequestReady, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
Server (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &, Response &)> &onRequestReady, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void listen (const SocketAddress &socketAddress, const std::function< void(int)> &onError)
Public Member Functions inherited from core::socket::stream::tls::SocketServer< SocketServerT, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
SocketServer (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void addSniCert (const std::string &domain, const std::map< std::string, std::any > &sniCert)
void addSniCerts (const std::map< std::string, std::map< std::string, std::any >> &sniCerts)
void setForceSni ()
Public Member Functions inherited from core::socket::stream::SocketServer< SocketServerT, core::socket::stream::tls::SocketAcceptor, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
SocketServer (const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void listen (const std::function< void(const SocketAddress &, int)> &onError) const override
void onConnect (const std::function< void(SocketConnection *)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Private Types
using Super = web::http::server::Server< net::in6::stream::tls::SocketServer, Request, Response >
Additional Inherited Members
Protected Attributes inherited from core::socket::stream::SocketServer< SocketServerT, core::socket::stream::tls::SocketAcceptor, SocketContextFactoryT >
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response>
class web::http::tls::in6::Server< Request, Response >
Definition at line 32 of file Server.h.
Member Typedef Documentation
SocketAddress
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> using web::http::tls::in6::Server< Request, Response >::SocketAddress = typename Super::SocketAddress
Definition at line 37 of file Server.h.
SocketConnection
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> using web::http::tls::in6::Server< Request, Response >::SocketConnection = typename Super::SocketConnection
Definition at line 38 of file Server.h.
Super
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> using web::http::tls::in6::Server< Request, Response >::Super = web::http::server::Server<net::in6::stream::tls::SocketServer, Request, Response> private
Definition at line 33 of file Server.h.
Member Function Documentation
listen() [1/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::tls::in6::Server< Request, Response >::listen (const std::string & ipOrHostname, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 46 of file Server.h.
{
             listen(ipOrHostname, LISTEN_BACKLOG, onError);
         }
References web::http::tls::in6::Server< Request, Response >::listen(), and LISTEN_BACKLOG.
listen() [2/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::tls::in6::Server< Request, Response >::listen (const std::string & ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 50 of file Server.h.
{
             listen(ipOrHostname, port, LISTEN_BACKLOG, onError);
         }
References web::http::tls::in6::Server< Request, Response >::listen(), and LISTEN_BACKLOG.
listen() [3/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::tls::in6::Server< Request, Response >::listen (uint16_t port, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 42 of file Server.h.
{
             listen(port, LISTEN_BACKLOG, onError);
         }
References LISTEN_BACKLOG.
Referenced by web::http::tls::in6::Server< Request, Response >::listen().
The documentation for this class was generated from the following file:
web/http/tls/in6/Server.h