snode.c: net::stream::ServerSocket< SocketT > Class Template Reference
net::stream::ServerSocket< SocketT > Class Template Reference
#include <ServerSocket.h>
Public Member Functions
int listen (int backlog)
int accept (typename SocketT::SocketAddress &addr)
int accept4 (typename SocketT::SocketAddress &addr, int flags)
Private Types
using Super = SocketT
Detailed Description
template<typename SocketT>
class net::stream::ServerSocket< SocketT >
Definition at line 29 of file ServerSocket.h.
Member Typedef Documentation
Super
template<typename SocketT > using net::stream::ServerSocket< SocketT >::Super = SocketT private
Definition at line 31 of file ServerSocket.h.
Member Function Documentation
accept()
template<typename SocketT > int net::stream::ServerSocket< Socket >::accept (typename SocketT::SocketAddress & addr)
Definition at line 35 of file ServerSocket.hpp.
{
         addr.getAddrLen() = sizeof(typename Socket::SocketAddress::SockAddr);
         return core::system::accept(Socket::getFd(), addr, &addr.getAddrLen());
     }
accept4()
template<typename SocketT > int net::stream::ServerSocket< Socket >::accept4 (typename SocketT::SocketAddress & addr, int flags)
Definition at line 41 of file ServerSocket.hpp.
{
         addr.getAddrLen() = sizeof(typename Socket::SocketAddress::SockAddr);
         return core::system::accept4(Socket::getFd(), addr, &addr.getAddrLen(), flags);
     }
References core::system::accept4(), and core::Descriptor::getFd().
listen()
template<typename Socket > int net::stream::ServerSocket< Socket >::listen (int backlog)
Definition at line 30 of file ServerSocket.hpp.
{
         return core::system::listen(Socket::getFd(), backlog);
     }
References core::Descriptor::getFd(), and core::system::listen().
The documentation for this class was generated from the following files:
net/stream/ServerSocket.h
net/stream/ServerSocket.hpp