snode.c: core::socket::stream::SocketContext Class Reference
core::socket::stream::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
ssize_t readFromPeer (char *junk, std::size_t junklen)
void close ()
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
SocketContext * switchSocketContext (SocketContextFactory *socketContextFactory)
void setTimeout (int timeout)
virtual void onReceiveFromPeer ()=0
virtual void onWriteError (int errnum)=0
virtual void onReadError (int errnum)=0
virtual void onConnected ()
virtual void onDisconnected ()
Protected Member Functions
SocketContext (SocketConnection *socketConnection)
virtual ~SocketContext ()=default
Private Attributes
SocketConnection * socketConnection
Friends
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT >
class SocketConnectionT
Detailed Description
Definition at line 37 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
core::socket::stream::SocketContext::SocketContext (SocketConnection * socketConnection) explicit protected
Definition at line 30 of file SocketContext.cpp.
         : socketConnection(socketConnection) {
     }
~SocketContext()
virtual core::socket::stream::SocketContext::~SocketContext () protected virtual default
Reimplemented in web::http::client::SocketContext< RequestT, ResponseT >.
Member Function Documentation
close()
void core::socket::stream::SocketContext::close ()
Definition at line 58 of file SocketContext.cpp.
{
         socketConnection->close();
     }
References core::socket::stream::SocketConnection::close(), and socketConnection.
Referenced by web::http::client::Request::enqueue(), web::http::client::Request::error(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose(), express::Response::sendFile(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
getLocalAddressAsString()
std::string core::socket::stream::SocketContext::getLocalAddressAsString () const
Definition at line 50 of file SocketContext.cpp.
{
         return socketConnection->getLocalAddressAsString();
     }
References core::socket::stream::SocketConnection::getLocalAddressAsString(), and socketConnection.
getRemoteAddressAsString()
std::string core::socket::stream::SocketContext::getRemoteAddressAsString () const
Definition at line 54 of file SocketContext.cpp.
{
         return socketConnection->getRemoteAddressAsString();
     }
References core::socket::stream::SocketConnection::getRemoteAddressAsString(), and socketConnection.
onConnected()
void core::socket::stream::SocketContext::onConnected () virtual
Reimplemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Definition at line 70 of file SocketContext.cpp.
{
         VLOG(0) << "Protocol connected";
     }
onDisconnected()
void core::socket::stream::SocketContext::onDisconnected () virtual
Reimplemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, and web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >.
Definition at line 74 of file SocketContext.cpp.
{
         VLOG(0) << "Protocol disconnecteded";
     }
onReadError()
virtual void core::socket::stream::SocketContext::onReadError (int errnum) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, web::http::server::SocketContext< RequestT, ResponseT >, and web::http::client::SocketContext< RequestT, ResponseT >.
onReceiveFromPeer()
virtual void core::socket::stream::SocketContext::onReceiveFromPeer () pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, web::http::server::SocketContext< RequestT, ResponseT >, and web::http::client::SocketContext< RequestT, ResponseT >.
onWriteError()
virtual void core::socket::stream::SocketContext::onWriteError (int errnum) pure virtual
Implemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, web::http::server::SocketContext< RequestT, ResponseT >, and web::http::client::SocketContext< RequestT, ResponseT >.
readFromPeer()
ssize_t core::socket::stream::SocketContext::readFromPeer (char * junk, std::size_t junklen)
Definition at line 42 of file SocketContext.cpp.
{
         ssize_t ret = 0;
         ret = socketConnection->readFromPeer(junk, junklen);
         return ret;
     }
References core::socket::stream::SocketConnection::readFromPeer(), and socketConnection.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::readFrameData(), web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
sendToPeer() [1/2]
void core::socket::stream::SocketContext::sendToPeer (const char * junk, std::size_t junkLen)
Definition at line 34 of file SocketContext.cpp.
{
         socketConnection->sendToPeer(junk, junkLen);
     }
References core::socket::stream::SocketConnection::sendToPeer(), and socketConnection.
Referenced by web::http::client::Request::enqueue(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData(), and sendToPeer().
sendToPeer() [2/2]
void core::socket::stream::SocketContext::sendToPeer (const std::string & data)
Definition at line 38 of file SocketContext.cpp.
{
         sendToPeer(data.data(), data.length());
     }
References sendToPeer().
setTimeout()
void core::socket::stream::SocketContext::setTimeout (int timeout)
Definition at line 66 of file SocketContext.cpp.
{
         socketConnection->setTimeout(timeout);
     }
References core::socket::stream::SocketConnection::setTimeout(), and socketConnection.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose().
switchSocketContext()
SocketContext * core::socket::stream::SocketContext::switchSocketContext (SocketContextFactory * socketContextFactory)
Definition at line 62 of file SocketContext.cpp.
{
         return socketConnection->switchSocketContext(socketContextFactory);
     }
References socketConnection, and core::socket::stream::SocketConnection::switchSocketContext().
Referenced by web::http::client::Response::upgrade().
Friends And Related Function Documentation
SocketConnectionT
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > friend class SocketConnectionT friend
Definition at line 66 of file SocketContext.h.
Member Data Documentation
socketConnection
SocketConnection* core::socket::stream::SocketContext::socketConnection private
Definition at line 63 of file SocketContext.h.
Referenced by close(), web::websocket::client::SocketContextUpgrade::create(), web::websocket::server::SocketContextUpgrade::create(), getLocalAddressAsString(), getRemoteAddressAsString(), readFromPeer(), sendToPeer(), setTimeout(), and switchSocketContext().
The documentation for this class was generated from the following files:
core/socket/stream/SocketContext.h
core/socket/stream/SocketContext.cpp