snode.c: CLI::ConfigError Class Reference
CLI::ConfigError Class Reference
Errors
Thrown when extra values are found in an INI file.
#include <CLI11.hpp>
Public Member Functions
ConfigError (std::string msg, ExitCodes exit_code)
ConfigError (std::string msg, int exit_code)
ConfigError (std::string msg)
Public Member Functions inherited from CLI::ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from CLI::Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static ConfigError Extras (std::string item)
static ConfigError NotConfigurable (std::string item)
Protected Member Functions
ConfigError (std::string ename, std::string msg, int exit_code)
ConfigError (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from CLI::ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when extra values are found in an INI file.
Definition at line 900 of file CLI11.hpp.
Constructor & Destructor Documentation
ConfigError() [1/5]
CLI::ConfigError::ConfigError (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 901 of file CLI11.hpp.
Referenced by Extras(), and NotConfigurable().
ConfigError() [2/5]
CLI::ConfigError::ConfigError (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 901 of file CLI11.hpp.
ConfigError() [3/5]
CLI::ConfigError::ConfigError (std::string msg, ExitCodes exit_code) inline
Definition at line 901 of file CLI11.hpp.
ConfigError() [4/5]
CLI::ConfigError::ConfigError (std::string msg, int exit_code) inline
Definition at line 901 of file CLI11.hpp.
ConfigError() [5/5]
CLI::ConfigError::ConfigError (std::string msg) inline explicit
Definition at line 902 of file CLI11.hpp.
Member Function Documentation
Extras()
static ConfigError CLI::ConfigError::Extras (std::string item) inline static
Definition at line 903 of file CLI11.hpp.
{
             return ConfigError("INI was not able to parse " + item);
         }
References ConfigError().
Referenced by CLI::App::_parse_config().
NotConfigurable()
static ConfigError CLI::ConfigError::NotConfigurable (std::string item) inline static
Definition at line 906 of file CLI11.hpp.
{
             return ConfigError(item + ": This option is not allowed in a configuration file");
         }
References ConfigError().
Referenced by CLI::App::_parse_single_config().
The documentation for this class was generated from the following file:
utils/CLI11.hpp