snode.c: web::http::server::tls::ServerRfComm< Request, Response > Class Template Reference
web::http::server::tls::ServerRfComm< Request, Response > Class Template Reference
#include <Server.h>
Public Member Functions
void listen (uint8_t channel, const std::function< void(int)> &onError)
void listen (const std::string &address, const std::function< void(int)> &onError)
void listen (const std::string &address, uint8_t channel, const std::function< void(int)> &onError)
Public Member Functions inherited from web::http::server::Server< net::socket::bluetooth::rfcomm::tls::SocketServer, web::http::server::Request, web::http::server::Response >
Server (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &, Response &)> &onRequestReady, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void listen (const SocketAddress &socketAddress, const std::function< void(int)> &onError)
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
Additional Inherited Members
Public Types inherited from web::http::server::Server< net::socket::bluetooth::rfcomm::tls::SocketServer, web::http::server::Request, web::http::server::Response >
using Request = web::http::server::Request
using Response = web::http::server::Response
using SocketServer = net::socket::bluetooth::rfcomm::tls::SocketServer< web::http::server::SocketContextFactory< Request, Response > >
using SocketConnection = typename SocketServer::SocketConnection
using SocketAddress = typename SocketConnection::SocketAddress
Protected Attributes inherited from web::http::server::Server< net::socket::bluetooth::rfcomm::tls::SocketServer, web::http::server::Request, web::http::server::Response >
SocketServer socketServer
std::function< void(Request &, Response &)> onRequestReady
Detailed Description
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response>
class web::http::server::tls::ServerRfComm< Request, Response >
Definition at line 78 of file Server.h.
Member Function Documentation
listen() [1/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::server::tls::ServerRfComm< Request, Response >::listen (const std::string & address, const std::function< void(int)> & onError) inline
Definition at line 90 of file Server.h.
{
             socketServer.listen(address, 5, onError);
         }
References net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen(), and web::http::server::Server< net::socket::bluetooth::rfcomm::tls::SocketServer, web::http::server::Request, web::http::server::Response >::socketServer.
listen() [2/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::server::tls::ServerRfComm< Request, Response >::listen (const std::string & address, uint8_t channel, const std::function< void(int)> & onError) inline
Definition at line 94 of file Server.h.
{
             socketServer.listen(address, channel, 5, onError);
         }
References net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen(), and web::http::server::Server< net::socket::bluetooth::rfcomm::tls::SocketServer, web::http::server::Request, web::http::server::Response >::socketServer.
listen() [3/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::server::tls::ServerRfComm< Request, Response >::listen (uint8_t channel, const std::function< void(int)> & onError) inline
Definition at line 86 of file Server.h.
{
             socketServer.listen(channel, 5, onError);
         }
References net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen(), and web::http::server::Server< net::socket::bluetooth::rfcomm::tls::SocketServer, web::http::server::Request, web::http::server::Response >::socketServer.
Referenced by express::tls::WebAppRfComm::listen().
The documentation for this class was generated from the following file:
web/http/server/tls/Server.h