snode.c: core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT > Class Template Reference
core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT > Class Template Reference
#include <SocketServer.h>
Public Types
using Socket = typename Super::Socket
using SocketAddress = typename Super::SocketAddress
using SocketConnection = typename Super::SocketConnection
Public Types inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
using Socket = typename ServerSocket::Socket
using SocketAddress = typename Socket::SocketAddress
using SocketConnection = typename SocketAcceptor::SocketConnection
Public Member Functions
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void addSniCert (const std::string &domain, const std::map< std::string, std::any > &sniCert)
void addSniCerts (const std::map< std::string, std::map< std::string, std::any >> &sniCerts)
void setForceSni ()
Public Member Functions inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketServer ()=default
void listen (const std::function< void(const Socket &socket, int)> &onError) const override
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(const Socket &socket, int)> &onError) const override
void onConnect (const std::function< void(SocketConnection *)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
ServerConfig & getServerConfig ()
Private Types
using Super = core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, typename ServerSocketT::Socket >, SocketContextFactoryT >
Private Member Functions
void addSniCtx (const std::string &domain, SSL_CTX *sslCtx)
void freeSniCerts (std::map< std::string, SSL_CTX * > *sniSslCtxs)
Private Attributes
std::shared_ptr< std::map< std::string, SSL_CTX * > > sniSslCtxs
bool forceSni = false
Additional Inherited Members
Protected Types inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
using ServerSocket = ServerSocketT
using ServerConfig = ServerConfigT
using SocketAcceptor = core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >
using SocketContextFactory = SocketContextFactoryT
Protected Attributes inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::tls::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
ServerConfig serverConfig
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename ServerSocketT, typename ServerConfigT, typename SocketContextFactoryT>
class core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >
Definition at line 34 of file SocketServer.h.
Member Typedef Documentation
Socket
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > using core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::Socket = typename Super::Socket
Definition at line 49 of file SocketServer.h.
SocketAddress
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > using core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::SocketAddress = typename Super::SocketAddress
Definition at line 50 of file SocketServer.h.
SocketConnection
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > using core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::SocketConnection = typename Super::SocketConnection
Definition at line 51 of file SocketServer.h.
Super
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > using core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::Super = core::socket::stream::SocketServer<ServerSocketT, ServerConfigT, core::socket::stream::tls::SocketAcceptor<ServerConfigT, typename ServerSocketT::Socket>, SocketContextFactoryT> private
Definition at line 41 of file SocketServer.h.
Constructor & Destructor Documentation
SocketServer()
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::SocketServer (const std::string & name, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 53 of file SocketServer.h.
                                                                 {{}})
             : Super(name, onConnect, onConnected, onDisconnect, options)
             , sniSslCtxs(new std::map<std::string, SSL_CTX*>, [this](std::map<std::string, SSL_CTX*>* sniSslCtxs) {
                 freeSniCerts(sniSslCtxs);
             }) {
             this->options.insert({{"SNI_SSL_CTXS", sniSslCtxs}});
             this->options.insert({{"FORCE_SNI", &forceSni}});
         }
Member Function Documentation
addSniCert()
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > void core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCert (const std::string & domain, const std::map< std::string, std::any > & sniCert) inline
Definition at line 77 of file SocketServer.h.
{
             SSL_CTX* sslCtx = ssl_ctx_new(sniCert, true);
             addSniCtx(domain, sslCtx);
         }
References core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCtx(), and core::socket::stream::tls::ssl_ctx_new().
Referenced by core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCerts().
addSniCerts()
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > void core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCerts (const std::map< std::string, std::map< std::string, std::any >> & sniCerts) inline
Definition at line 82 of file SocketServer.h.
{
             for (const auto& [domain, cert] : sniCerts) {
                 addSniCert(domain, cert);
             }
         }
References core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCert().
addSniCtx()
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > void core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCtx (const std::string & domain, SSL_CTX * sslCtx) inline private
Definition at line 67 of file SocketServer.h.
{
             if (sslCtx != nullptr) {
                 sniSslCtxs->insert({{domain, sslCtx}});
                 VLOG(2) << "SSL_CTX for domain '" << domain << "' installed";
             } else {
                 VLOG(2) << "Can not create SSL_CTX for SNI '" << domain << "'";
             }
         }
References core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::sniSslCtxs.
Referenced by core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCert().
freeSniCerts()
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > void core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::freeSniCerts (std::map< std::string, SSL_CTX * > * sniSslCtxs) inline private
Definition at line 93 of file SocketServer.h.
{
             for (const auto& [domain, sniSslCtx] : *sniSslCtxs) { // cppcheck-suppress unusedVariable
                 ssl_ctx_free(sniSslCtx);
             }
             delete sniSslCtxs;
         }
References core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::sniSslCtxs, and core::socket::stream::tls::ssl_ctx_free().
setForceSni()
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > void core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::setForceSni () inline
Definition at line 88 of file SocketServer.h.
{
             forceSni = true;
         }
References core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::forceSni.
Member Data Documentation
forceSni
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > bool core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::forceSni = false private
Definition at line 101 of file SocketServer.h.
Referenced by core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::setForceSni().
sniSslCtxs
template<typename ServerSocketT , typename ServerConfigT , typename SocketContextFactoryT > std::shared_ptr<std::map<std::string, SSL_CTX*> > core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::sniSslCtxs private
Definition at line 100 of file SocketServer.h.
Referenced by core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::addSniCtx(), and core::socket::stream::tls::SocketServer< ServerSocketT, ServerConfigT, SocketContextFactoryT >::freeSniCerts().
The documentation for this class was generated from the following file:
core/socket/stream/tls/SocketServer.h