snode.c: net::l2::stream::ServerConfig Class Reference
net::l2::stream::ServerConfig Class Reference
#include <ServerConfig.h>
Public Member Functions
ServerConfig (const std::string &name)
const std::string & getBindInterface () const
uint16_t getPsm () const
int parse (bool required=false)
Public Member Functions inherited from net::ServerConfig
ServerConfig (const std::string &name)
int getBacklog () const
Public Member Functions inherited from net::Config
Config (const std::string &name)
const std::string & getName () const
int getReadTimeout () const
int getWriteTimeout () const
Private Attributes
CLI::App * serverBindSc = nullptr
CLI::Option * bindServerHostOpt = nullptr
CLI::Option * bindServerPsmOpt = nullptr
std::string bindInterface
uint16_t psm
Additional Inherited Members
Public Attributes inherited from net::Config
CLI::App * serverSc = nullptr
Protected Member Functions inherited from net::Config
void finish ()
Detailed Description
Definition at line 38 of file ServerConfig.h.
Constructor & Destructor Documentation
ServerConfig()
net::l2::stream::ServerConfig::ServerConfig (const std::string & name) explicit
Definition at line 30 of file ServerConfig.cpp.
         : net::ServerConfig(name) {
         serverBindSc = serverSc->add_subcommand("bind");
         serverBindSc->description("Server socket bind options");
         serverBindSc->configurable();
         bindServerHostOpt = serverBindSc->add_option("-a,--host", bindInterface, "Bind bluetooth address");
         bindServerHostOpt->type_name("[bluetooth address]");
         bindServerHostOpt->default_val(":::::");
         bindServerHostOpt->configurable();
         bindServerPsmOpt = serverBindSc->add_option("-p,--psm", psm, "Bind protocol service multiplexer");
         bindServerPsmOpt->type_name("[uint16_t]");
         bindServerPsmOpt->default_val(0);
         bindServerPsmOpt->configurable();
         finish();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindInterface, bindServerHostOpt, bindServerPsmOpt, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), net::Config::finish(), psm, serverBindSc, net::Config::serverSc, and CLI::Option::type_name().
Member Function Documentation
getBindInterface()
const std::string & net::l2::stream::ServerConfig::getBindInterface () const
Definition at line 49 of file ServerConfig.cpp.
{
         return bindInterface;
     }
References bindInterface.
getPsm()
uint16_t net::l2::stream::ServerConfig::getPsm () const
Definition at line 53 of file ServerConfig.cpp.
{
         return psm;
     }
References psm.
parse()
int net::l2::stream::ServerConfig::parse (bool required = false)
Definition at line 57 of file ServerConfig.cpp.
{
         utils::Config::instance().required(serverSc, required);
         utils::Config::instance().required(serverBindSc, required);
         utils::Config::instance().required(bindServerHostOpt, required);
         utils::Config::instance().required(bindServerPsmOpt, required);
         try {
             utils::Config::instance().parse();
         } catch (const CLI::ParseError& e) {
         }
         return 0;
     }
References bindServerHostOpt, bindServerPsmOpt, utils::Config::instance(), utils::Config::parse(), utils::Config::required(), serverBindSc, and net::Config::serverSc.
Member Data Documentation
bindInterface
std::string net::l2::stream::ServerConfig::bindInterface private
Definition at line 53 of file ServerConfig.h.
Referenced by getBindInterface(), and ServerConfig().
bindServerHostOpt
CLI::Option* net::l2::stream::ServerConfig::bindServerHostOpt = nullptr private
Definition at line 50 of file ServerConfig.h.
Referenced by parse(), and ServerConfig().
bindServerPsmOpt
CLI::Option* net::l2::stream::ServerConfig::bindServerPsmOpt = nullptr private
Definition at line 51 of file ServerConfig.h.
Referenced by parse(), and ServerConfig().
psm
uint16_t net::l2::stream::ServerConfig::psm private
Definition at line 54 of file ServerConfig.h.
Referenced by getPsm(), and ServerConfig().
serverBindSc
CLI::App* net::l2::stream::ServerConfig::serverBindSc = nullptr private
Definition at line 49 of file ServerConfig.h.
Referenced by parse(), and ServerConfig().
The documentation for this class was generated from the following files:
net/l2/stream/ServerConfig.h
net/l2/stream/ServerConfig.cpp