snode.c: net::in::ConfigLocal Class Reference
net::in::ConfigLocal Class Reference
#include <ConfigLocal.h>
Public Member Functions
ConfigLocal (CLI::App *baseSc)
Public Member Functions inherited from net::ConfigLocal< net::in::SocketAddress >
const SocketAddress & getLocalAddress () const
void setLocalAddress (const SocketAddress &localAddress) const
Protected Member Functions
void required () const
Protected Member Functions inherited from net::ConfigLocal< net::in::SocketAddress >
ConfigLocal ()=default
virtual ~ConfigLocal ()=default
Protected Attributes
CLI::App * bindSc = nullptr
CLI::Option * bindHostOpt = nullptr
CLI::Option * bindPortOpt = nullptr
Private Member Functions
SocketAddress getAddress () const override
Private Attributes
std::string bindHost = ""
uint16_t bindPort = 0
Additional Inherited Members
Protected Types inherited from net::ConfigLocal< net::in::SocketAddress >
using SocketAddress = net::in::SocketAddress
Detailed Description
Definition at line 39 of file ConfigLocal.h.
Constructor & Destructor Documentation
ConfigLocal()
net::in::ConfigLocal::ConfigLocal (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigLocal.cpp.
{
         bindSc = baseSc->add_subcommand("local");
         bindSc->description("Bind options");
         bindSc->configurable();
         bindHostOpt = bindSc->add_option("-a,--host", bindHost, "Host name or IP address");
         bindHostOpt->type_name("[hostname|ip]");
         bindHostOpt->default_val("0.0.0.0");
         bindHostOpt->take_first();
         bindHostOpt->configurable();
         bindPortOpt = bindSc->add_option("-p,--port", bindPort, "Port number");
         bindPortOpt->type_name("[uint16_t]");
         bindPortOpt->default_val(0);
         bindPortOpt->take_first();
         bindPortOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindHost, bindHostOpt, bindPort, bindPortOpt, bindSc, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), CLI::OptionBase< CRTP >::take_first(), and CLI::Option::type_name().
Member Function Documentation
getAddress()
SocketAddress net::in::ConfigLocal::getAddress () const override private virtual
Implements net::ConfigLocal< net::in::SocketAddress >.
Definition at line 47 of file ConfigLocal.cpp.
{
         return SocketAddress(bindHost, bindPort);
     }
References bindHost, and bindPort.
required()
void net::in::ConfigLocal::required () const protected
Definition at line 51 of file ConfigLocal.cpp.
{
         bindSc->required();
         bindPortOpt->required();
     }
References bindPortOpt, bindSc, CLI::App::required(), and CLI::OptionBase< CRTP >::required().
Referenced by net::in::stream::ServerConfig::ServerConfig().
Member Data Documentation
bindHost
std::string net::in::ConfigLocal::bindHost = "" private
Definition at line 53 of file ConfigLocal.h.
Referenced by ConfigLocal(), and getAddress().
bindHostOpt
CLI::Option* net::in::ConfigLocal::bindHostOpt = nullptr protected
Definition at line 47 of file ConfigLocal.h.
Referenced by ConfigLocal().
bindPort
uint16_t net::in::ConfigLocal::bindPort = 0 private
Definition at line 54 of file ConfigLocal.h.
Referenced by ConfigLocal(), and getAddress().
bindPortOpt
CLI::Option* net::in::ConfigLocal::bindPortOpt = nullptr protected
Definition at line 48 of file ConfigLocal.h.
Referenced by ConfigLocal(), and required().
bindSc
CLI::App* net::in::ConfigLocal::bindSc = nullptr protected
Definition at line 46 of file ConfigLocal.h.
Referenced by ConfigLocal(), and required().
The documentation for this class was generated from the following files:
net/in/ConfigLocal.h
net/in/ConfigLocal.cpp