snode.c: core::pipe::PipeSource Class Reference
core::pipe::PipeSource Class Reference
#include <PipeSource.h>
Public Member Functions
PipeSource (int fd)
void send (const char *junk, std::size_t junkLen)
void send (const std::string &data)
void eof ()
void setOnError (const std::function< void(int errnum)> &onError)
Public Member Functions inherited from core::DescriptorEventReceiver
int getRegisteredFd ()
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
bool isEnabled () const
bool isSuspended () const
Public Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish () const
const std::string & getName ()
Protected Member Functions
void writeEvent () override
void unobservedEvent () override
Protected Member Functions inherited from core::Descriptor
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
void attachFd (int fd)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Protected Member Functions inherited from core::eventreceiver::WriteEventReceiver
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
void enable (int fd)
void disable ()
void suspend ()
void resume ()
void setTimeout (const utils::Timeval &timeout)
void checkTimeout (const utils::Timeval &currentTime)
Protected Attributes
std::function< void(int errnum)> onError
std::vector< char > writeBuffer
Protected Attributes inherited from core::Descriptor
enum core::Descriptor::FLAGS none
Protected Attributes inherited from core::EventReceiver
Event event
Private Member Functions
PipeSource (const PipeSource &)=delete
PipeSource & operator= (const PipeSource &)=delete
void terminate () override
Additional Inherited Members
Protected Types inherited from core::Descriptor
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Detailed Description
Definition at line 36 of file PipeSource.h.
Constructor & Destructor Documentation
PipeSource() [1/2]
core::pipe::PipeSource::PipeSource (const PipeSource &) private delete
PipeSource() [2/2]
core::pipe::PipeSource::PipeSource (int fd) explicit
Definition at line 36 of file PipeSource.cpp.
         : Descriptor(fd)
         , core::eventreceiver::WriteEventReceiver("PipeSource fd = " + std::to_string(fd)) {
         WriteEventReceiver::enable(fd);
         WriteEventReceiver::suspend();
     }
References core::Descriptor::fd.
Member Function Documentation
eof()
void core::pipe::PipeSource::eof ()
Definition at line 59 of file PipeSource.cpp.
{
         WriteEventReceiver::disable();
     }
operator=()
PipeSource& core::pipe::PipeSource::operator= (const PipeSource &) private delete
send() [1/2]
void core::pipe::PipeSource::send (const char * junk, std::size_t junkLen)
Definition at line 47 of file PipeSource.cpp.
{
         writeBuffer.insert(writeBuffer.end(), junk, junk + junkLen);
         if (WriteEventReceiver::isSuspended()) {
             WriteEventReceiver::resume();
         }
     }
References writeBuffer.
Referenced by send().
send() [2/2]
void core::pipe::PipeSource::send (const std::string & data)
Definition at line 55 of file PipeSource.cpp.
{
         send(data.data(), data.size());
     }
References send().
setOnError()
void core::pipe::PipeSource::setOnError (const std::function< void(int errnum)> & onError)
Definition at line 43 of file PipeSource.cpp.
{
         this->onError = onError;
     }
References onError.
terminate()
void core::pipe::PipeSource::terminate () override private virtual
Reimplemented from core::DescriptorEventReceiver.
Definition at line 86 of file PipeSource.cpp.
{
         WriteEventReceiver::terminate();
     }
unobservedEvent()
void core::pipe::PipeSource::unobservedEvent () override protected virtual
Implements core::Observer.
Definition at line 82 of file PipeSource.cpp.
{
         delete this;
     }
writeEvent()
void core::pipe::PipeSource::writeEvent () override protected virtual
Implements core::eventreceiver::WriteEventReceiver.
Definition at line 63 of file PipeSource.cpp.
{
         ssize_t ret = core::system::write(
             getFd(), writeBuffer.data(), (writeBuffer.size() < MAX_SEND_JUNKSIZE) ? writeBuffer.size() : MAX_SEND_JUNKSIZE);
         if (ret > 0) {
             writeBuffer.erase(writeBuffer.begin(), writeBuffer.begin() + ret);
             if (writeBuffer.empty()) {
                 WriteEventReceiver::suspend();
             }
         } else if (errno != EAGAIN && errno != EWOULDBLOCK && errno != EINTR) {
             WriteEventReceiver::disable();
             if (onError) {
                 onError(errno);
             }
         }
     }
References core::Descriptor::getFd(), MAX_SEND_JUNKSIZE, onError, core::system::write(), and writeBuffer.
Member Data Documentation
onError
std::function<void(int errnum)> core::pipe::PipeSource::onError protected
Definition at line 59 of file PipeSource.h.
Referenced by setOnError(), and writeEvent().
writeBuffer
std::vector<char> core::pipe::PipeSource::writeBuffer protected
Definition at line 61 of file PipeSource.h.
Referenced by send(), and writeEvent().
The documentation for this class was generated from the following files:
core/pipe/PipeSource.h
core/pipe/PipeSource.cpp