snode.c: net::in6::SocketAddress Class Reference
net::in6::SocketAddress Class Reference
#include <SocketAddress.h>
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &ipOrHostname)
SocketAddress (const std::string &ipOrHostname, uint16_t port)
SocketAddress (uint16_t port)
void setHost (const std::string &ipOrHostname)
void setPort (uint16_t port)
uint16_t port () const
std::string host () const
std::string serv () const
std::string address () const override
std::string toString () const override
Public Member Functions inherited from net::SocketAddress< sockaddr_in6 >
SocketAddress (socklen_t addrLen=sizeof(SockAddr))
SocketAddress (const SocketAddress &socketAddress)
virtual ~SocketAddress ()=default
SocketAddress & operator= (const SocketAddress &socketAddress)
operator sockaddr * ()
operator const sockaddr * () const
sockaddr & getSockAddr ()
const sockaddr & getSockAddr () const
socklen_t & getAddrLen ()
const socklen_t & getAddrLen () const
Additional Inherited Members
Public Types inherited from net::SocketAddress< sockaddr_in6 >
using SockAddr = sockaddr_in6
Protected Attributes inherited from net::SocketAddress< sockaddr_in6 >
SockAddr sockAddr
socklen_t addrLen
Detailed Description
Definition at line 47 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/4]
net::in6::SocketAddress::SocketAddress ()
Definition at line 36 of file SocketAddress.cpp.
{
         std::memset(&sockAddr, 0, sizeof(sockAddr));
         sockAddr.sin6_family = AF_INET6;
         sockAddr.sin6_addr = in6addr_any;
         sockAddr.sin6_port = 0;
     }
References net::SocketAddress< sockaddr_in6 >::sockAddr.
SocketAddress() [2/4]
net::in6::SocketAddress::SocketAddress (const std::string & ipOrHostname) explicit
Definition at line 44 of file SocketAddress.cpp.
         : SocketAddress() {
         setHost(ipOrHostname);
     }
References setHost().
SocketAddress() [3/4]
net::in6::SocketAddress::SocketAddress (const std::string & ipOrHostname, uint16_t port)
Definition at line 49 of file SocketAddress.cpp.
         : SocketAddress() {
         setHost(ipOrHostname);
         setPort(port);
     }
References port(), setHost(), and setPort().
SocketAddress() [4/4]
net::in6::SocketAddress::SocketAddress (uint16_t port) explicit
Definition at line 55 of file SocketAddress.cpp.
         : SocketAddress() {
         setPort(port);
     }
References port(), and setPort().
Member Function Documentation
address()
std::string net::in6::SocketAddress::address () const override virtual
Implements net::SocketAddress< sockaddr_in6 >.
Definition at line 113 of file SocketAddress.cpp.
{
         int tmpErrno = errno;
         char ip[NI_MAXHOST];
         int ret =
             core::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), ip, 256, nullptr, 0, NI_NUMERICHOST);
         errno = tmpErrno;
         return ret >= 0 ? ip : gai_strerror(ret);
     }
References core::system::getnameinfo(), and net::SocketAddress< sockaddr_in6 >::sockAddr.
Referenced by host().
host()
std::string net::in6::SocketAddress::host () const
Definition at line 101 of file SocketAddress.cpp.
{
         int tmpErrno = errno;
         char host[NI_MAXHOST];
         int ret =
             core::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), host, 256, nullptr, 0, NI_NAMEREQD);
         errno = tmpErrno;
         return ret == EAI_NONAME ? address() : ret >= 0 ? host : gai_strerror(ret);
     }
References address(), core::system::getnameinfo(), and net::SocketAddress< sockaddr_in6 >::sockAddr.
Referenced by toString().
port()
uint16_t net::in6::SocketAddress::port () const
Definition at line 97 of file SocketAddress.cpp.
{
         return (ntohs(sockAddr.sin6_port));
     }
References net::SocketAddress< sockaddr_in6 >::sockAddr.
Referenced by setPort(), SocketAddress(), and toString().
serv()
std::string net::in6::SocketAddress::serv () const
Definition at line 125 of file SocketAddress.cpp.
{
         int tmpErrno = errno;
         char serv[NI_MAXSERV];
         int ret = core::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), nullptr, 0, serv, 256, 0);
         errno = tmpErrno;
         return ret >= 0 ? serv : gai_strerror(ret);
     }
References core::system::getnameinfo(), and net::SocketAddress< sockaddr_in6 >::sockAddr.
setHost()
void net::in6::SocketAddress::setHost (const std::string & ipOrHostname)
Definition at line 60 of file SocketAddress.cpp.
{
         struct addrinfo hints {};
         struct addrinfo* res;
         struct addrinfo* resalloc;
         std::memset(&hints, 0, sizeof(hints));
         /* We only care about IPV6 results */
         hints.ai_family = AF_INET6;
         hints.ai_socktype = 0;
         hints.ai_flags = AI_ADDRCONFIG | AI_V4MAPPED;
         int err = core::system::getaddrinfo(ipOrHostname.c_str(), nullptr, &hints, &res);
         if (err != 0) {
             throw bad_hostname(ipOrHostname + ": " + gai_strerror(err));
         }
         resalloc = res;
         while (res) {
             /* Check to make sure we have a valid AF_INET6 address */
             if (res->ai_family == AF_INET6) {
                 sockAddr.sin6_addr = reinterpret_cast<sockaddr_in6*>(res->ai_addr)->sin6_addr;
                 break;
             }
             res = res->ai_next;
         }
         core::system::freeaddrinfo(resalloc);
     }
References core::system::freeaddrinfo(), core::system::getaddrinfo(), and net::SocketAddress< sockaddr_in6 >::sockAddr.
Referenced by SocketAddress().
setPort()
void net::in6::SocketAddress::setPort (uint16_t port)
Definition at line 93 of file SocketAddress.cpp.
{
         sockAddr.sin6_port = htons(port);
     }
References port(), and net::SocketAddress< sockaddr_in6 >::sockAddr.
Referenced by SocketAddress().
toString()
std::string net::in6::SocketAddress::toString () const override virtual
Implements net::SocketAddress< sockaddr_in6 >.
Definition at line 136 of file SocketAddress.cpp.
{
         return host() + ":" + std::to_string(port());
     }
References host(), port(), and CLI::detail::to_string().
The documentation for this class was generated from the following files:
net/in6/SocketAddress.h
net/in6/SocketAddress.cpp