snode.c: core::ReadEventReceiver Class Reference
core::ReadEventReceiver Class Reference abstract
#include <ReadEventReceiver.h>
Protected Member Functions
ReadEventReceiver (const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
~DescriptorEventReceiver ()=default
Private Member Functions
virtual void readEvent ()=0
virtual void readTimeout ()
void dispatchEvent () final
void timeoutEvent () final
bool continueImmediately () const final
virtual bool continueReadImmediately () const
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
int getRegisteredFd ()
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime) override
void triggered (const utils::Timeval &currentTime)
void disabled ()
virtual void terminate ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Public Member Functions inherited from core::EventReceiver
EventReceiver ()
virtual ~EventReceiver ()=default
void publish ()
Public Attributes inherited from core::DescriptorEventReceiver
utils::Timeval publisedTime
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
Protected Attributes inherited from core::EventReceiver
Event event
Detailed Description
Definition at line 32 of file ReadEventReceiver.h.
Constructor & Destructor Documentation
ReadEventReceiver()
core::ReadEventReceiver::ReadEventReceiver (const utils::Timeval & timeout = 60) protected
Definition at line 30 of file ReadEventReceiver.cpp.
         : DescriptorEventReceiver(
               EventLoop::instance().getEventDispatcher().getDescriptorEventDispatcher(core::EventDispatcher::DISP_TYPE::RD), timeout) {
     }
Member Function Documentation
continueImmediately()
bool core::ReadEventReceiver::continueImmediately () const final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 51 of file ReadEventReceiver.cpp.
{
         return continueReadImmediately();
     }
References continueReadImmediately().
continueReadImmediately()
bool core::ReadEventReceiver::continueReadImmediately () const private virtual
Reimplemented in core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::SocketReader< SocketT >, core::socket::stream::legacy::SocketReader< SocketT >, and core::file::FileReader.
Definition at line 39 of file ReadEventReceiver.cpp.
{
         return false;
     }
Referenced by continueImmediately().
dispatchEvent()
void core::ReadEventReceiver::dispatchEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 43 of file ReadEventReceiver.cpp.
{
         readEvent();
     }
References readEvent().
readEvent()
virtual void core::ReadEventReceiver::readEvent () private pure virtual
Implemented in core::socket::stream::SocketReader< SocketT >, core::socket::stream::tls::TLSShutdown, core::socket::stream::tls::TLSHandshake, core::pipe::PipeSink, core::file::FileReader, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by dispatchEvent().
readTimeout()
void core::ReadEventReceiver::readTimeout () private virtual
Reimplemented in core::socket::stream::tls::TLSShutdown, and core::socket::stream::tls::TLSHandshake.
Definition at line 35 of file ReadEventReceiver.cpp.
{
         disable();
     }
References core::DescriptorEventReceiver::disable().
Referenced by timeoutEvent().
timeoutEvent()
void core::ReadEventReceiver::timeoutEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 47 of file ReadEventReceiver.cpp.
{
         readTimeout();
     }
References readTimeout().
The documentation for this class was generated from the following files:
core/ReadEventReceiver.h
core/ReadEventReceiver.cpp