snode.c: CLI::IsMember Class Reference
CLI::IsMember Class Reference
Verify items are in a set.
#include <CLI11.hpp>
Public Types
using filter_fn_t = std::function< std::string(std::string)>
Public Member Functions
template<typename T , typename... Args>
IsMember (std::initializer_list< T > values, Args &&... args)
This allows in-place construction using an initializer list.
template<typename T >
IsMember (T &&set)
This checks to see if an item is in a set (empty function)
template<typename T , typename F >
IsMember (T set, F filter_function)
template<typename T , typename... Args>
IsMember (T &&set, filter_fn_t filter_fn_1, filter_fn_t filter_fn_2, Args &&... other)
You can pass in as many filter functions as you like, they nest (string only currently)
Public Member Functions inherited from CLI::Validator
Validator ()=default
Validator (std::string validator_desc)
Construct a Validator with just the description string.
Validator (std::function< std::string(std::string &)> op, std::string validator_desc, std::string validator_name="")
Construct Validator from basic information.
Validator & operation (std::function< std::string(std::string &)> op)
Set the Validator operation function.
std::string operator() (std::string &str) const
std::string operator() (const std::string &str) const
Validator & description (std::string validator_desc)
Specify the type string.
Validator description (std::string validator_desc) const
Specify the type string.
std::string get_description () const
Generate type description information for the Validator.
Validator & name (std::string validator_name)
Specify the type string.
Validator name (std::string validator_name) const
Specify the type string.
const std::string & get_name () const
Get the name of the Validator.
Validator & active (bool active_val=true)
Specify whether the Validator is active or not.
Validator active (bool active_val=true) const
Specify whether the Validator is active or not.
Validator & non_modifying (bool no_modify=true)
Specify whether the Validator can be modifying or not.
Validator & application_index (int app_index)
Specify the application index of a validator.
Validator application_index (int app_index) const
Specify the application index of a validator.
int get_application_index () const
Get the current value of the application index.
bool get_active () const
Get a boolean if the validator is active.
bool get_modifying () const
Get a boolean if the validator is allowed to modify the input returns true if it can modify the input.
Validator operator& (const Validator &other) const
Validator operator| (const Validator &other) const
Validator operator! () const
Create a validator that fails when a given validator succeeds.
Additional Inherited Members
Protected Attributes inherited from CLI::Validator
std::function< std::string()> desc_function_
This is the description function, if empty the description_ will be used.
std::function< std::string(std::string &)> func_
std::string name_ {}
The name for search purposes of the Validator.
int application_index_ = -1
A Validator will only apply to an indexed value (-1 is all elements)
bool active_ {true}
Enable for Validator to allow it to be disabled if need be.
bool non_modifying_ {false}
specify that a validator should not modify the input
Detailed Description
Verify items are in a set.
Definition at line 3477 of file CLI11.hpp.
Member Typedef Documentation
filter_fn_t
using CLI::IsMember::filter_fn_t = std::function<std::string(std::string)>
Definition at line 3479 of file CLI11.hpp.
Constructor & Destructor Documentation
IsMember() [1/4]
template<typename T , typename... Args> CLI::IsMember::IsMember (std::initializer_list< T > values, Args &&... args) inline
This allows in-place construction using an initializer list.
Definition at line 3483 of file CLI11.hpp.
             : IsMember(std::vector<T>(values), std::forward<Args>(args)...) {
         }
IsMember() [2/4]
template<typename T > CLI::IsMember::IsMember (T && set) inline explicit
This checks to see if an item is in a set (empty function)
Definition at line 3489 of file CLI11.hpp.
             : IsMember(std::forward<T>(set), nullptr) {
         }
IsMember() [3/4]
template<typename T , typename F > CLI::IsMember::IsMember (T set, F filter_function) inline explicit
This checks to see if an item is in a set: pointer or copy version. You can pass in a function that will filter both sides of the comparison before computing the comparison.
Definition at line 3496 of file CLI11.hpp.
{
             // Get the type of the contained item - requires a container have ::value_type
             // if the type does not have first_type and second_type, these are both value_type
             using element_t = typename detail::element_type<T>::type;            // Removes (smart) pointers if needed
             using item_t = typename detail::pair_adaptor<element_t>::first_type; // Is value_type if not a map
             using local_item_t = typename IsMemberType<item_t>::type; // This will convert bad types to good ones
                                                                       // (const char * to std::string)
             // Make a local copy of the filter function, using a std::function if not one already
             std::function<local_item_t(local_item_t)> filter_fn = filter_function;
             // This is the type name for help, it will take the current version of the set contents
             desc_function_ = [set]() {
                 return detail::generate_set(detail::smart_deref(set));
             };
             // This is the function that validates
             // It stores a copy of the set pointer-like, so shared_ptr will stay alive
             func_ = [set, filter_fn](std::string& input) {
                 local_item_t b;
                 if (!detail::lexical_cast(input, b)) {
                     throw ValidationError(input); // name is added later
                 }
                 if (filter_fn) {
                     b = filter_fn(b);
                 }
                 auto res = detail::search(set, b, filter_fn);
                 if (res.first) {
                     // Make sure the version in the input string is identical to the one in the set
                     if (filter_fn) {
                         input = detail::value_string(detail::pair_adaptor<element_t>::first(*(res.second)));
                     }
                     // Return empty error string (success)
                     return std::string{};
                 }
                 // If you reach this point, the result was not found
                 return input + " not in " + detail::generate_set(detail::smart_deref(set));
             };
         }
References CLI::detail::generate_set(), CLI::detail::lexical_cast(), CLI::detail::search(), CLI::detail::smart_deref(), and CLI::detail::value_string().
IsMember() [4/4]
template<typename T , typename... Args> CLI::IsMember::IsMember (T && set, filter_fn_t filter_fn_1, filter_fn_t filter_fn_2, Args &&... other) inline
You can pass in as many filter functions as you like, they nest (string only currently)
Definition at line 3541 of file CLI11.hpp.
             : IsMember(
                   std::forward<T>(set),
                   [filter_fn_1, filter_fn_2](std::string a) {
                       return filter_fn_2(filter_fn_1(a));
                   },
                   other...) {
         }
The documentation for this class was generated from the following file:
utils/CLI11.hpp