snode.c: net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT > Class Template Reference
net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT > Class Template Reference
#include <SocketClient.h>
Public Types
using SocketAddress = typename ConcreteSocketClient< rfcomm::Socket, SocketContextFactoryT >::SocketAddress
Public Member Functions
void connect (const std::string &address, uint8_t channel, const std::function< void(int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &bindAddress, const std::function< void(int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &bindAddress, uint8_t bindChannel, const std::function< void(int)> &onError)
Detailed Description
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketClient, typename SocketContextFactoryT>
class net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >
Definition at line 35 of file SocketClient.h.
Member Typedef Documentation
SocketAddress
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketClient, typename SocketContextFactoryT > using net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::SocketAddress = typename ConcreteSocketClient<rfcomm::Socket, SocketContextFactoryT>::SocketAddress
Definition at line 39 of file SocketClient.h.
Member Function Documentation
connect() [1/3]
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketClient, typename SocketContextFactoryT > void net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect (const std::string & address, uint8_t channel, const std::function< void(int)> & onError) inline
Definition at line 43 of file SocketClient.h.
{
             connect(SocketAddress(address, channel), onError);
         }
Referenced by web::http::client::legacy::ClientRfComm< Request, Response >::connect(), web::http::client::tls::ClientRfComm< Request, Response >::connect(), and net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect().
connect() [2/3]
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketClient, typename SocketContextFactoryT > void net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect (const std::string & address, uint8_t channel, const std::string & bindAddress, const std::function< void(int)> & onError) inline
Definition at line 47 of file SocketClient.h.
{
             connect(SocketAddress(address, channel), SocketAddress(bindAddress), onError);
         }
References net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect().
connect() [3/3]
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketClient, typename SocketContextFactoryT > void net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect (const std::string & address, uint8_t channel, const std::string & bindAddress, uint8_t bindChannel, const std::function< void(int)> & onError) inline
Definition at line 51 of file SocketClient.h.
{
             connect(SocketAddress(address, channel), SocketAddress(bindAddress, bindChannel), onError);
         }
References net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect().
The documentation for this class was generated from the following file:
net/socket/bluetooth/rfcomm/SocketClient.h