snode.c: core::TimerEventReceiver Class Reference
core::TimerEventReceiver Class Reference abstract
#include <TimerEventReceiver.h>
Protected Member Functions
TimerEventReceiver (const std::string &name, const utils::Timeval &delay)
virtual ~TimerEventReceiver () override
utils::Timeval getTimeout () const
void enable ()
void update ()
void cancel ()
Private Member Functions
TimerEventReceiver (const TimerEventReceiver &)=delete
TimerEventReceiver & operator= (const TimerEventReceiver &)=delete
void event (const utils::Timeval &currentTime) final
virtual void dispatchEvent ()=0
virtual void unobservedEvent ()=0
void setTimer (Timer *timer)
void updateTimeout ()
Private Attributes
TimerEventPublisher & timerEventPublisher
Timer * timer = nullptr
utils::Timeval absoluteTimeout
utils::Timeval delay
Friends
class Timer
class TimerEventPublisher
Additional Inherited Members
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish ()
void unPublish ()
const std::string & getName ()
Protected Attributes inherited from core::EventReceiver
Event _event
Detailed Description
Definition at line 41 of file TimerEventReceiver.h.
Constructor & Destructor Documentation
TimerEventReceiver() [1/2]
core::TimerEventReceiver::TimerEventReceiver (const TimerEventReceiver &) private delete
TimerEventReceiver() [2/2]
core::TimerEventReceiver::TimerEventReceiver (const std::string & name, const utils::Timeval & delay) protected
Definition at line 34 of file TimerEventReceiver.cpp.
         : EventReceiver(name)
         , timerEventPublisher(EventLoop::instance().getEventMultiplexer().getTimerEventPublisher())
         , absoluteTimeout(utils::Timeval::currentTime() + delay)
         , delay(delay) {
     }
~TimerEventReceiver()
core::TimerEventReceiver::~TimerEventReceiver () override protected virtual
Definition at line 41 of file TimerEventReceiver.cpp.
{
         if (timer != nullptr) {
             timer->removeTimerEventReceiver();
         }
     }
References core::Timer::removeTimerEventReceiver(), and timer.
Member Function Documentation
cancel()
void core::TimerEventReceiver::cancel () protected
Definition at line 65 of file TimerEventReceiver.cpp.
{
         timerEventPublisher.remove(this);
     }
References core::TimerEventPublisher::remove(), and timerEventPublisher.
Referenced by core::Timer::cancel(), and core::timer::SingleshotTimer::dispatchEvent().
dispatchEvent()
virtual void core::TimerEventReceiver::dispatchEvent () private pure virtual
Implemented in core::timer::SingleshotTimer, core::timer::IntervalTimerStopable, and core::timer::IntervalTimer.
Referenced by event().
enable()
void core::TimerEventReceiver::enable () protected
Definition at line 55 of file TimerEventReceiver.cpp.
{
         timerEventPublisher.insert(this);
     }
References core::TimerEventPublisher::insert(), and timerEventPublisher.
Referenced by core::Timer::Timer().
event()
void core::TimerEventReceiver::event (const utils::Timeval & currentTime) final private virtual
Implements core::EventReceiver.
Definition at line 69 of file TimerEventReceiver.cpp.
{
         LOG(INFO) << "Timer: Dispatch delta = " << (currentTime - getTimeout()).msd() << " ms";
         dispatchEvent();
     }
References dispatchEvent(), and getTimeout().
getTimeout()
utils::Timeval core::TimerEventReceiver::getTimeout () const protected
Definition at line 47 of file TimerEventReceiver.cpp.
{
         return absoluteTimeout;
     }
References absoluteTimeout.
Referenced by event(), and core::TimerEventPublisher::timernode_lt::operator()().
operator=()
TimerEventReceiver& core::TimerEventReceiver::operator= (const TimerEventReceiver &) private delete
setTimer()
void core::TimerEventReceiver::setTimer (Timer * timer) private
Definition at line 75 of file TimerEventReceiver.cpp.
{
         this->timer = timer;
     }
References timer.
Referenced by core::Timer::operator=(), core::Timer::Timer(), and core::Timer::~Timer().
unobservedEvent()
virtual void core::TimerEventReceiver::unobservedEvent () private pure virtual
Implemented in core::timer::SingleshotTimer, core::timer::IntervalTimerStopable, and core::timer::IntervalTimer.
update()
void core::TimerEventReceiver::update () protected
Definition at line 59 of file TimerEventReceiver.cpp.
{
         timerEventPublisher.erase(this);
         absoluteTimeout += delay;
         timerEventPublisher.insert(this);
     }
References absoluteTimeout, delay, core::TimerEventPublisher::erase(), core::TimerEventPublisher::insert(), and timerEventPublisher.
Referenced by core::timer::IntervalTimer::dispatchEvent().
updateTimeout()
void core::TimerEventReceiver::updateTimeout () private
Definition at line 51 of file TimerEventReceiver.cpp.
{
         absoluteTimeout += delay;
     }
References absoluteTimeout, and delay.
Friends And Related Function Documentation
Timer
friend class Timer friend
Definition at line 72 of file TimerEventReceiver.h.
TimerEventPublisher
friend class TimerEventPublisher friend
Definition at line 73 of file TimerEventReceiver.h.
Member Data Documentation
absoluteTimeout
utils::Timeval core::TimerEventReceiver::absoluteTimeout private
Definition at line 69 of file TimerEventReceiver.h.
Referenced by getTimeout(), update(), and updateTimeout().
delay
utils::Timeval core::TimerEventReceiver::delay private
Definition at line 70 of file TimerEventReceiver.h.
Referenced by update(), and updateTimeout().
timer
Timer* core::TimerEventReceiver::timer = nullptr private
Definition at line 68 of file TimerEventReceiver.h.
Referenced by setTimer(), and ~TimerEventReceiver().
timerEventPublisher
TimerEventPublisher& core::TimerEventReceiver::timerEventPublisher private
Definition at line 66 of file TimerEventReceiver.h.
Referenced by cancel(), enable(), and update().
The documentation for this class was generated from the following files:
core/TimerEventReceiver.h
core/TimerEventReceiver.cpp