snode.c: core::socket::stream::tls::SocketWriter< SocketT > Class Template Reference
core::socket::stream::tls::SocketWriter< SocketT > Class Template Reference abstract
#include <SocketWriter.h>
Protected Member Functions
virtual void doSSLHandshake (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int)> &onError)=0
void setSSLError (int sslErr)
Protected Member Functions inherited from core::socket::stream::SocketWriter< SocketT >
SocketWriter (const std::function< void(int)> &onError)
virtual ~SocketWriter ()=default
void sendToPeer (const char *junk, std::size_t junkLen)
void shutdown ()
void doWrite ()
Protected Member Functions inherited from core::WriteEventReceiver
WriteEventReceiver (long timeout=60)
virtual bool continueWriteImmediately ()
Protected Member Functions inherited from core::EventReceiver
EventReceiver (EventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Attributes
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
Protected Attributes inherited from core::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Private Member Functions
void doShutdown () override
ssize_t write (const char *junk, std::size_t junkLen) override
int getError () override
Additional Inherited Members
Public Types inherited from core::socket::stream::SocketWriter< SocketT >
using Socket = SocketT
Public Member Functions inherited from core::EventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from core::ObservationCounter
bool isObserved ()
Detailed Description
template<typename SocketT>
class core::socket::stream::tls::SocketWriter< SocketT >
Definition at line 39 of file SocketWriter.h.
Member Function Documentation
doShutdown()
template<typename SocketT > void core::socket::stream::tls::SocketWriter< SocketT >::doShutdown () inline override private virtual
Reimplemented from core::socket::stream::SocketWriter< SocketT >.
Definition at line 43 of file SocketWriter.h.
{
             SSL_shutdown(ssl);
             doSSLHandshake(
                 [this](void) -> void { // onSuccess
                     LOG(INFO) << "SSL/TLS shutdown handshake success";
                     core::socket::stream::SocketWriter<SocketT>::doShutdown();
                 },
                 [this](void) -> void { // onTimeout
                     LOG(WARNING) << "SSL/TLS shutdown handshake timed out";
                     core::socket::stream::SocketWriter<SocketT>::doShutdown();
                 },
                 [this](int sslErr) -> void { // onError
                     ssl_log("SSL/TLS shutdown handshake failed", sslErr);
                     core::socket::stream::SocketWriter<SocketT>::doShutdown();
                 });
         }
References core::socket::stream::SocketWriter< SocketT >::doShutdown(), core::socket::stream::tls::SocketWriter< SocketT >::doSSLHandshake(), core::socket::stream::tls::SocketWriter< SocketT >::ssl, core::socket::stream::tls::ssl_log(), and core::socket::stream::tls::SocketWriter< SocketT >::sslErr.
doSSLHandshake()
template<typename SocketT > virtual void core::socket::stream::tls::SocketWriter< SocketT >::doSSLHandshake (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int)> & onError) protected pure virtual
Referenced by core::socket::stream::tls::SocketWriter< SocketT >::doShutdown(), and core::socket::stream::tls::SocketWriter< SocketT >::write().
getError()
template<typename SocketT > int core::socket::stream::tls::SocketWriter< SocketT >::getError () inline override private virtual
Implements core::socket::stream::SocketWriter< SocketT >.
Definition at line 106 of file SocketWriter.h.
{
             int ret = errno;
             switch (sslErr) {
                 case SSL_ERROR_NONE:
                     [[fallthrough]];
                 case SSL_ERROR_ZERO_RETURN:
                     ret = 0;
                     break;
                 case SSL_ERROR_SYSCALL:
                     break;
                 default:
                     ret = -sslErr;
                     break;
             };
             return ret;
         }
References core::socket::stream::tls::SocketWriter< SocketT >::sslErr.
setSSLError()
template<typename SocketT > void core::socket::stream::tls::SocketWriter< SocketT >::setSSLError (int sslErr) inline protected
Definition at line 130 of file SocketWriter.h.
{
             this->sslErr = sslErr;
         }
References core::socket::stream::tls::SocketWriter< SocketT >::sslErr.
Referenced by core::socket::stream::tls::SocketWriter< SocketT >::write().
write()
template<typename SocketT > ssize_t core::socket::stream::tls::SocketWriter< SocketT >::write (const char * junk, std::size_t junkLen) inline override private virtual
Implements core::socket::stream::SocketWriter< SocketT >.
Definition at line 60 of file SocketWriter.h.
{
             sslErr = 0;
             int ret = SSL_write(ssl, junk, static_cast<int>(junkLen));
             if (ret <= 0) {
                 sslErr = SSL_get_error(ssl, ret);
                 switch (sslErr) {
                     case SSL_ERROR_WANT_READ:
                         LOG(INFO) << "SSL/TLS start renegotiation on write";
                         doSSLHandshake(
                             [](void) -> void {
                                 LOG(INFO) << "SSL/TLS renegotiation on write success";
                             },
                             [](void) -> void {
                                 LOG(WARNING) << "SSL/TLS renegotiation on write timed out";
                             },
                             [this](int sslErr) -> void {
                                 ssl_log("SSL/TLS renegotiation", sslErr);
                                 setSSLError(sslErr);
                             });
                         errno = EAGAIN;
                         break;
                     case SSL_ERROR_WANT_WRITE:
                         ret = 0;
                         errno = EAGAIN;
                         break;
                     case SSL_ERROR_ZERO_RETURN:
                         ret = 0;
                         errno = 0;
                         break;
                     case SSL_ERROR_SYSCALL:
                         if (errno != 0) {
                             ssl_log("SSL/TLS write failed", sslErr);
                         }
                         break;
                     default:
                         ssl_log("SSL/TLS write failed", sslErr);
                         break;
                 }
             }
             return ret;
         }
References core::socket::stream::tls::SocketWriter< SocketT >::doSSLHandshake(), core::socket::stream::tls::SocketWriter< SocketT >::setSSLError(), core::socket::stream::tls::SocketWriter< SocketT >::ssl, core::socket::stream::tls::ssl_log(), core::ssl::SSL_write(), and core::socket::stream::tls::SocketWriter< SocketT >::sslErr.
Member Data Documentation
ssl
template<typename SocketT > SSL* core::socket::stream::tls::SocketWriter< SocketT >::ssl = nullptr protected
Definition at line 134 of file SocketWriter.h.
Referenced by core::socket::stream::tls::SocketWriter< SocketT >::doShutdown(), and core::socket::stream::tls::SocketWriter< SocketT >::write().
sslErr
template<typename SocketT > int core::socket::stream::tls::SocketWriter< SocketT >::sslErr = SSL_ERROR_NONE protected
Definition at line 136 of file SocketWriter.h.
Referenced by core::socket::stream::tls::SocketWriter< SocketT >::doShutdown(), core::socket::stream::tls::SocketWriter< SocketT >::getError(), core::socket::stream::tls::SocketWriter< SocketT >::setSSLError(), and core::socket::stream::tls::SocketWriter< SocketT >::write().
The documentation for this class was generated from the following file:
core/socket/stream/tls/SocketWriter.h