snode.c: net::in::SocketAddress Class Reference
net::in::SocketAddress Class Reference
#include <SocketAddress.h>
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &ipOrHostname)
SocketAddress (const std::string &ipOrHostname, uint16_t port)
SocketAddress (uint16_t port)
uint16_t port () const
std::string host () const
std::string serv () const
std::string address () const override
std::string toString () const override
Public Member Functions inherited from core::socket::SocketAddress< struct sockaddr_in >
SocketAddress ()
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr)
SocketAddress & operator= (const SocketAddress &socketAddress)
SocketAddress & operator= (const SockAddr &sockAddr)
const sockaddr & getSockAddr () const
socklen_t getSockAddrLen () const
Additional Inherited Members
Public Types inherited from core::socket::SocketAddress< struct sockaddr_in >
using SockAddr = struct sockaddr_in
Protected Attributes inherited from core::socket::SocketAddress< struct sockaddr_in >
SockAddr sockAddr
Detailed Description
Definition at line 34 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/4]
net::in::SocketAddress::SocketAddress ()
Definition at line 48 of file SocketAddress.cpp.
{
         sockAddr.sin_family = AF_INET;
         sockAddr.sin_addr.s_addr = htonl(INADDR_ANY);
         sockAddr.sin_port = 0;
     }
References core::socket::SocketAddress< struct sockaddr_in >::sockAddr.
SocketAddress() [2/4]
net::in::SocketAddress::SocketAddress (const std::string & ipOrHostname) explicit
Definition at line 54 of file SocketAddress.cpp.
         : SocketAddress(ipOrHostname, 0) {
     }
SocketAddress() [3/4]
net::in::SocketAddress::SocketAddress (const std::string & ipOrHostname, uint16_t port)
Definition at line 58 of file SocketAddress.cpp.
{
         struct addrinfo hints {};
         struct addrinfo* res;
         struct addrinfo* resalloc;
         memset(&hints, 0, sizeof(hints));
         memset(&sockAddr, 0, sizeof(sockAddr));
         /* We only care about IPV6 results */
         hints.ai_family = AF_INET;
         hints.ai_socktype = 0;
         hints.ai_flags = AI_ADDRCONFIG;
         int err = core::system::getaddrinfo(ipOrHostname.c_str(), nullptr, &hints, &res);
         if (err != 0) {
             throw bad_hostname(ipOrHostname);
         }
         resalloc = res;
         while (res) {
             /* Check to make sure we have a valid AF_INET6 address */
             if (res->ai_family == AF_INET) {
                 /* Use memcpy since we're going to free the res variable later */
                 memcpy(&sockAddr, res->ai_addr, res->ai_addrlen);
                 /* Here we convert the port to network byte order */
                 sockAddr.sin_port = htons(port);
                 sockAddr.sin_family = AF_INET;
                 break;
             }
             res = res->ai_next;
         }
         core::system::freeaddrinfo(resalloc);
     }
References core::system::freeaddrinfo(), core::system::getaddrinfo(), port(), and core::socket::SocketAddress< struct sockaddr_in >::sockAddr.
SocketAddress() [4/4]
net::in::SocketAddress::SocketAddress (uint16_t port) explicit
Definition at line 97 of file SocketAddress.cpp.
{
         sockAddr.sin_family = AF_INET;
         sockAddr.sin_port = htons(port);
         sockAddr.sin_addr.s_addr = htonl(INADDR_ANY);
     }
References port(), and core::socket::SocketAddress< struct sockaddr_in >::sockAddr.
Member Function Documentation
address()
std::string net::in::SocketAddress::address () const override virtual
Implements core::socket::SocketAddress< struct sockaddr_in >.
Definition at line 114 of file SocketAddress.cpp.
{
         char ip[NI_MAXHOST];
         core::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), ip, 256, nullptr, 0, NI_NUMERICHOST);
         return ip;
     }
References core::system::getnameinfo(), and core::socket::SocketAddress< struct sockaddr_in >::sockAddr.
host()
std::string net::in::SocketAddress::host () const
Definition at line 107 of file SocketAddress.cpp.
{
         char host[NI_MAXHOST];
         core::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), host, 256, nullptr, 0, 0);
         return host;
     }
References core::system::getnameinfo(), and core::socket::SocketAddress< struct sockaddr_in >::sockAddr.
Referenced by toString().
port()
uint16_t net::in::SocketAddress::port () const
Definition at line 103 of file SocketAddress.cpp.
{
         return (ntohs(sockAddr.sin_port));
     }
References core::socket::SocketAddress< struct sockaddr_in >::sockAddr.
Referenced by SocketAddress(), and toString().
serv()
std::string net::in::SocketAddress::serv () const
Definition at line 121 of file SocketAddress.cpp.
{
         char serv[NI_MAXSERV];
         core::system::getnameinfo(reinterpret_cast<const sockaddr*>(&sockAddr), sizeof(sockAddr), nullptr, 0, serv, 256, 0);
         return serv;
     }
References core::system::getnameinfo(), and core::socket::SocketAddress< struct sockaddr_in >::sockAddr.
toString()
std::string net::in::SocketAddress::toString () const override virtual
Implements core::socket::SocketAddress< struct sockaddr_in >.
Definition at line 128 of file SocketAddress.cpp.
{
         return host() + ":" + std::to_string(port());
     }
References host(), and port().
The documentation for this class was generated from the following files:
net/in/SocketAddress.h
net/in/SocketAddress.cpp