snode.c: net::rc::SocketAddress Class Reference
net::rc::SocketAddress Class Reference
#include <SocketAddress.h>
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &btAddress)
SocketAddress (const std::string &btAddress, uint8_t channel)
SocketAddress (uint8_t channel)
void setAddress (const std::string &btAddress)
void setChannel (uint8_t channel)
uint8_t channel () const
std::string address () const override
std::string toString () const override
Public Member Functions inherited from net::SocketAddress< struct sockaddr_rc >
SocketAddress ()
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr)
virtual ~SocketAddress ()=default
SocketAddress & operator= (const SocketAddress &socketAddress)
SocketAddress & operator= (const SockAddr &sockAddr)
const sockaddr & getSockAddr () const
socklen_t getSockAddrLen () const
Additional Inherited Members
Public Types inherited from net::SocketAddress< struct sockaddr_rc >
using SockAddr = struct sockaddr_rc
Protected Attributes inherited from net::SocketAddress< struct sockaddr_rc >
SockAddr sockAddr
Detailed Description
Definition at line 37 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/4]
net::rc::SocketAddress::SocketAddress ()
Definition at line 48 of file SocketAddress.cpp.
{
         std::memset(&sockAddr, 0, sizeof(sockAddr));
         sockAddr.rc_family = AF_BLUETOOTH;
         sockAddr.rc_bdaddr = {{0, 0, 0, 0, 0, 0}};
         sockAddr.rc_channel = static_cast<unsigned char>(0);
     }
References net::SocketAddress< struct sockaddr_rc >::sockAddr.
SocketAddress() [2/4]
net::rc::SocketAddress::SocketAddress (const std::string & btAddress) explicit
Definition at line 56 of file SocketAddress.cpp.
         : SocketAddress() {
         setAddress(btAddress);
     }
References setAddress().
SocketAddress() [3/4]
net::rc::SocketAddress::SocketAddress (const std::string & btAddress, uint8_t channel)
Definition at line 66 of file SocketAddress.cpp.
         : SocketAddress() {
         setAddress(btAddress);
         setChannel(channel);
     }
References channel(), setAddress(), and setChannel().
SocketAddress() [4/4]
net::rc::SocketAddress::SocketAddress (uint8_t channel) explicit
Definition at line 61 of file SocketAddress.cpp.
         : SocketAddress() {
         setChannel(channel);
     }
References channel(), and setChannel().
Member Function Documentation
address()
std::string net::rc::SocketAddress::address () const override virtual
Implements net::SocketAddress< struct sockaddr_rc >.
Definition at line 84 of file SocketAddress.cpp.
{
         char address[256];
         ba2str(&sockAddr.rc_bdaddr, address);
         return address;
     }
References net::SocketAddress< struct sockaddr_rc >::sockAddr.
Referenced by toString().
channel()
uint8_t net::rc::SocketAddress::channel () const
Definition at line 80 of file SocketAddress.cpp.
{
         return sockAddr.rc_channel;
     }
References net::SocketAddress< struct sockaddr_rc >::sockAddr.
Referenced by setChannel(), SocketAddress(), and toString().
setAddress()
void net::rc::SocketAddress::setAddress (const std::string & btAddress)
Definition at line 72 of file SocketAddress.cpp.
{
         str2ba(btAddress.c_str(), &sockAddr.rc_bdaddr);
     }
References net::SocketAddress< struct sockaddr_rc >::sockAddr.
Referenced by SocketAddress().
setChannel()
void net::rc::SocketAddress::setChannel (uint8_t channel)
Definition at line 76 of file SocketAddress.cpp.
{
         sockAddr.rc_channel = channel;
     }
References channel(), and net::SocketAddress< struct sockaddr_rc >::sockAddr.
Referenced by SocketAddress().
toString()
std::string net::rc::SocketAddress::toString () const override virtual
Implements net::SocketAddress< struct sockaddr_rc >.
Definition at line 91 of file SocketAddress.cpp.
{
         return address() + ":" + std::to_string(channel());
     }
References address(), channel(), and CLI::detail::to_string().
The documentation for this class was generated from the following files:
net/rc/SocketAddress.h
net/rc/SocketAddress.cpp