snode.c: core::socket::stream::tls::TLSHandshake Class Reference
core::socket::stream::tls::TLSHandshake Class Reference
#include <TLSHandshake.h>
Static Public Member Functions
static void doHandshake (SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int)> &onError, const utils::Timeval &timeout)
Private Member Functions
TLSHandshake (SSL *ssl, const std::function< void(void)> &onSuccess, const std::function< void(void)> &onTimeout, const std::function< void(int)> &onError, const utils::Timeval &timeout)
void readEvent () override
void writeEvent () override
void readTimeout () override
void writeTimeout () override
void unobservedEvent () override
Private Attributes
SSL * ssl = nullptr
std::function< void(void)> onSuccess
std::function< void(void)> onTimeout
std::function< void(int)> onError
bool timeoutTriggered
int fd = -1
Additional Inherited Members
Public Member Functions inherited from core::EventReceiver
int getRegisteredFd ()
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime)
void triggered (const utils::Timeval &currentTime)
void disabled ()
virtual void terminate ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Protected Member Functions inherited from core::ReadEventReceiver
ReadEventReceiver (const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::EventReceiver
EventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
Protected Member Functions inherited from core::WriteEventReceiver
WriteEventReceiver (const utils::Timeval &timeout=60)
Detailed Description
Definition at line 36 of file TLSHandshake.h.
Constructor & Destructor Documentation
TLSHandshake()
core::socket::stream::tls::TLSHandshake::TLSHandshake (SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int)> & onError, const utils::Timeval & timeout) private
Definition at line 39 of file TLSHandshake.cpp.
         : ReadEventReceiver(timeout)
         , WriteEventReceiver(timeout)
         , ssl(ssl)
         , onSuccess(onSuccess)
         , onTimeout(onTimeout)
         , onError(onError)
         , timeoutTriggered(false) {
         fd = SSL_get_fd(ssl);
         ReadEventReceiver::enable(fd);
         WriteEventReceiver::enable(fd);
         ReadEventReceiver::suspend();
         WriteEventReceiver::suspend();
         int ret = SSL_do_handshake(ssl);
         int sslErr = SSL_ERROR_NONE;
         if (ret < 1) {
             sslErr = SSL_get_error(ssl, ret);
         }
         switch (sslErr) {
             case SSL_ERROR_WANT_READ:
                 ReadEventReceiver::resume();
                 break;
             case SSL_ERROR_WANT_WRITE:
                 WriteEventReceiver::resume();
                 break;
             case SSL_ERROR_NONE:
                 ReadEventReceiver::disable();
                 WriteEventReceiver::disable();
                 onSuccess();
                 break;
             default:
                 ReadEventReceiver::disable();
                 WriteEventReceiver::disable();
                 onError(sslErr);
                 break;
         }
     }
References core::EventReceiver::disable(), core::EventReceiver::enable(), fd, onError, onSuccess, core::EventReceiver::resume(), ssl, and core::EventReceiver::suspend().
Referenced by doHandshake().
Member Function Documentation
doHandshake()
void core::socket::stream::tls::TLSHandshake::doHandshake (SSL * ssl, const std::function< void(void)> & onSuccess, const std::function< void(void)> & onTimeout, const std::function< void(int)> & onError, const utils::Timeval & timeout) static
Definition at line 31 of file TLSHandshake.cpp.
{
         new TLSHandshake(ssl, onSuccess, onTimeout, onError, timeout);
     }
References onError, onSuccess, onTimeout, ssl, and TLSHandshake().
Referenced by core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake().
readEvent()
void core::socket::stream::tls::TLSHandshake::readEvent () override private virtual
Implements core::ReadEventReceiver.
Definition at line 85 of file TLSHandshake.cpp.
{
         int ret = SSL_do_handshake(ssl);
         int sslErr = SSL_ERROR_NONE;
         if (ret < 1) {
             sslErr = SSL_get_error(ssl, ret);
         }
         switch (sslErr) {
             case SSL_ERROR_WANT_READ:
                 break;
             case SSL_ERROR_WANT_WRITE:
                 ReadEventReceiver::suspend();
                 WriteEventReceiver::resume();
                 break;
             case SSL_ERROR_NONE:
                 ReadEventReceiver::disable();
                 WriteEventReceiver::disable();
                 onSuccess();
                 break;
             default:
                 ReadEventReceiver::disable();
                 WriteEventReceiver::disable();
                 onError(sslErr);
                 break;
         }
     }
References core::EventReceiver::disable(), onError, onSuccess, core::EventReceiver::resume(), ssl, and core::EventReceiver::suspend().
readTimeout()
void core::socket::stream::tls::TLSHandshake::readTimeout () override private virtual
Reimplemented from core::ReadEventReceiver.
Definition at line 141 of file TLSHandshake.cpp.
{
         if (!timeoutTriggered) {
             timeoutTriggered = true;
             ReadEventReceiver::disable();
             WriteEventReceiver::disable();
             onTimeout();
         }
     }
References core::EventReceiver::disable(), onTimeout, and timeoutTriggered.
unobservedEvent()
void core::socket::stream::tls::TLSHandshake::unobservedEvent () override private virtual
Implements core::Observer.
Definition at line 159 of file TLSHandshake.cpp.
{
         delete this;
     }
writeEvent()
void core::socket::stream::tls::TLSHandshake::writeEvent () override private virtual
Implements core::WriteEventReceiver.
Definition at line 113 of file TLSHandshake.cpp.
{
         int ret = SSL_do_handshake(ssl);
         int sslErr = SSL_ERROR_NONE;
         if (ret < 1) {
             sslErr = SSL_get_error(ssl, ret);
         }
         switch (sslErr) {
             case SSL_ERROR_WANT_READ:
                 WriteEventReceiver::suspend();
                 ReadEventReceiver::resume();
                 break;
             case SSL_ERROR_WANT_WRITE:
                 break;
             case SSL_ERROR_NONE:
                 ReadEventReceiver::disable();
                 WriteEventReceiver::disable();
                 onSuccess();
                 break;
             default:
                 ReadEventReceiver::disable();
                 WriteEventReceiver::disable();
                 onError(sslErr);
                 break;
         }
     }
References core::EventReceiver::disable(), onError, onSuccess, core::EventReceiver::resume(), ssl, and core::EventReceiver::suspend().
writeTimeout()
void core::socket::stream::tls::TLSHandshake::writeTimeout () override private virtual
Reimplemented from core::WriteEventReceiver.
Definition at line 150 of file TLSHandshake.cpp.
{
         if (!timeoutTriggered) {
             timeoutTriggered = true;
             ReadEventReceiver::disable();
             WriteEventReceiver::disable();
             onTimeout();
         }
     }
References core::EventReceiver::disable(), onTimeout, and timeoutTriggered.
Member Data Documentation
fd
int core::socket::stream::tls::TLSHandshake::fd = -1 private
Definition at line 67 of file TLSHandshake.h.
Referenced by TLSHandshake().
onError
std::function<void(int)> core::socket::stream::tls::TLSHandshake::onError private
Definition at line 63 of file TLSHandshake.h.
Referenced by doHandshake(), readEvent(), TLSHandshake(), and writeEvent().
onSuccess
std::function<void(void)> core::socket::stream::tls::TLSHandshake::onSuccess private
Definition at line 61 of file TLSHandshake.h.
Referenced by doHandshake(), readEvent(), TLSHandshake(), and writeEvent().
onTimeout
std::function<void(void)> core::socket::stream::tls::TLSHandshake::onTimeout private
Definition at line 62 of file TLSHandshake.h.
Referenced by doHandshake(), readTimeout(), and writeTimeout().
ssl
SSL* core::socket::stream::tls::TLSHandshake::ssl = nullptr private
Definition at line 60 of file TLSHandshake.h.
Referenced by doHandshake(), readEvent(), TLSHandshake(), and writeEvent().
timeoutTriggered
bool core::socket::stream::tls::TLSHandshake::timeoutTriggered private
Definition at line 65 of file TLSHandshake.h.
Referenced by readTimeout(), and writeTimeout().
The documentation for this class was generated from the following files:
core/socket/stream/tls/TLSHandshake.h
core/socket/stream/tls/TLSHandshake.cpp