snode.c: net::ConfigTls Class Reference
net::ConfigTls Class Reference
#include <ConfigTls.h>
Public Member Functions
ConfigTls (CLI::App *baseSc)
const utils::Timeval & getInitTimeout () const
const utils::Timeval & getShutdownTimeout () const
Private Attributes
CLI::App * tlsSc = nullptr
CLI::Option * tlsInitTimeoutOpt = nullptr
CLI::Option * tlsShutdownTimeoutOpt = nullptr
utils::Timeval initTimeout
utils::Timeval shutdownTimeout
Detailed Description
Definition at line 35 of file ConfigTls.h.
Constructor & Destructor Documentation
ConfigTls()
net::ConfigTls::ConfigTls (CLI::App * baseSc) explicit
Definition at line 31 of file ConfigTls.cpp.
{
         tlsSc = baseSc->add_subcommand("tls");
         tlsSc->description("Options for SSL/TLS behaviour");
         tlsSc->configurable();
         tlsInitTimeoutOpt = tlsSc->add_option("-i,--init-timeout", initTimeout, "SSL/TLS initialization timeout");
         tlsInitTimeoutOpt->type_name("[sec]");
         tlsInitTimeoutOpt->default_val(10);
         tlsInitTimeoutOpt->take_first();
         tlsInitTimeoutOpt->configurable();
         tlsShutdownTimeoutOpt = tlsSc->add_option("-s,--shutdown-timeout", shutdownTimeout, "SSL/TLS shutdown timeout");
         tlsShutdownTimeoutOpt->type_name("[sec]");
         tlsShutdownTimeoutOpt->default_val(2);
         tlsShutdownTimeoutOpt->take_first();
         tlsShutdownTimeoutOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), initTimeout, shutdownTimeout, CLI::OptionBase< CRTP >::take_first(), tlsInitTimeoutOpt, tlsSc, tlsShutdownTimeoutOpt, and CLI::Option::type_name().
Member Function Documentation
getInitTimeout()
const utils::Timeval & net::ConfigTls::getInitTimeout () const
Definition at line 53 of file ConfigTls.cpp.
{
         return initTimeout;
     }
References initTimeout.
getShutdownTimeout()
const utils::Timeval & net::ConfigTls::getShutdownTimeout () const
Definition at line 49 of file ConfigTls.cpp.
{
         return shutdownTimeout;
     }
References shutdownTimeout.
Member Data Documentation
initTimeout
utils::Timeval net::ConfigTls::initTimeout private
Definition at line 48 of file ConfigTls.h.
Referenced by ConfigTls(), and getInitTimeout().
shutdownTimeout
utils::Timeval net::ConfigTls::shutdownTimeout private
Definition at line 49 of file ConfigTls.h.
Referenced by ConfigTls(), and getShutdownTimeout().
tlsInitTimeoutOpt
CLI::Option* net::ConfigTls::tlsInitTimeoutOpt = nullptr private
Definition at line 45 of file ConfigTls.h.
Referenced by ConfigTls().
tlsSc
CLI::App* net::ConfigTls::tlsSc = nullptr private
Definition at line 44 of file ConfigTls.h.
Referenced by ConfigTls().
tlsShutdownTimeoutOpt
CLI::Option* net::ConfigTls::tlsShutdownTimeoutOpt = nullptr private
Definition at line 46 of file ConfigTls.h.
Referenced by ConfigTls().
The documentation for this class was generated from the following files:
net/ConfigTls.h
net/ConfigTls.cpp