snode.c: core::Timer Class Reference
core::Timer Class Reference
#include <Timer.h>
Public Member Functions
void cancel ()
Protected Member Functions
Timer (core::TimerEventReceiver *timerEventReceiver)
Timer (Timer &&timer)
virtual ~Timer ()
Timer & operator= (Timer &&timer)
Private Member Functions
void removeTimerEventReceiver ()
Private Attributes
TimerEventReceiver * timerEventReceiver = nullptr
friend TimerEventReceiver
Detailed Description
Definition at line 32 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/2]
core::Timer::Timer (core::TimerEventReceiver * timerEventReceiver) explicit protected
Definition at line 31 of file Timer.cpp.
         : timerEventReceiver(timerEventReceiver) {
         timerEventReceiver->setTimer(this);
         timerEventReceiver->enable();
     }
References core::TimerEventReceiver::enable(), core::TimerEventReceiver::setTimer(), and timerEventReceiver.
Timer() [2/2]
core::Timer::Timer (Timer && timer) explicit protected
Definition at line 37 of file Timer.cpp.
{
         timerEventReceiver = std::move(timer.timerEventReceiver);
         timerEventReceiver->setTimer(this);
         timer.timerEventReceiver = nullptr;
     }
References core::TimerEventReceiver::setTimer(), and timerEventReceiver.
~Timer()
core::Timer::~Timer () protected virtual
Definition at line 51 of file Timer.cpp.
                   {
         if (timerEventReceiver != nullptr) {
             timerEventReceiver->setTimer(nullptr);
         }
     }
References core::TimerEventReceiver::setTimer(), and timerEventReceiver.
Member Function Documentation
cancel()
void core::Timer::cancel ()
Definition at line 57 of file Timer.cpp.
{
         if (timerEventReceiver != nullptr) {
             timerEventReceiver->cancel();
         }
     }
References core::TimerEventReceiver::cancel(), and timerEventReceiver.
operator=()
Timer & core::Timer::operator= (Timer && timer) protected
Definition at line 43 of file Timer.cpp.
{
         timerEventReceiver = std::move(timer.timerEventReceiver);
         timerEventReceiver->setTimer(this);
         timer.timerEventReceiver = nullptr;
         return *this;
     }
References core::TimerEventReceiver::setTimer(), and timerEventReceiver.
Referenced by core::timer::Timer::operator=().
removeTimerEventReceiver()
void core::Timer::removeTimerEventReceiver () private
Definition at line 63 of file Timer.cpp.
{
         timerEventReceiver = nullptr;
     }
References timerEventReceiver.
Referenced by core::TimerEventReceiver::~TimerEventReceiver().
Member Data Documentation
timerEventReceiver
TimerEventReceiver* core::Timer::timerEventReceiver = nullptr private
Definition at line 47 of file Timer.h.
Referenced by cancel(), operator=(), removeTimerEventReceiver(), Timer(), and ~Timer().
TimerEventReceiver
friend core::Timer::TimerEventReceiver private
Definition at line 49 of file Timer.h.
The documentation for this class was generated from the following files:
core/Timer.h
core/Timer.cpp