snode.c: net::in::stream::SocketClient< ConfigT > Class Template Reference
net::in::stream::SocketClient< ConfigT > Class Template Reference
#include <SocketClient.h>
Public Types
using Config = ConfigT
Public Types inherited from net::stream::SocketClient< ConfigT, net::in::stream::ClientSocket >
using Config = ConfigT
using Socket = net::in::stream::ClientSocket
using SocketAddress = typename Socket::SocketAddress
Public Types inherited from net::SocketConfig< ConfigT >
using Config = ConfigT
Public Member Functions
void connect (const std::string &ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindIpOrHostname, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindIpOrHostname, uint16_t bindPort, const std::function< void(const SocketAddress &, int)> &onError)
Public Member Functions inherited from net::stream::SocketClient< ConfigT, net::in::stream::ClientSocket >
SocketClient ()=default
SocketClient (const SocketClient &)=default
virtual ~SocketClient ()=default
virtual void connect (const std::function< void(const SocketAddress &, int)> &onError) const=0
void connect (const SocketAddress &remoteAddress, const SocketAddress &localAddress, const std::function< void(const SocketAddress &, int)> &onError) const
void connect (const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, int)> &onError) const
Public Member Functions inherited from net::SocketConfig< ConfigT >
SocketConfig (const std::string &name)
SocketConfig (const SocketConfig &)=default
const Config & getConfig ()
Protected Member Functions
SocketClient (const std::string &name)
Private Types
using Super = net::stream::SocketClient< ConfigT, net::in::stream::ClientSocket >
Additional Inherited Members
Protected Types inherited from net::stream::SocketClient< ConfigT, net::in::stream::ClientSocket >
using Super = net::SocketConfig< ConfigT >
Protected Attributes inherited from net::SocketConfig< ConfigT >
std::shared_ptr< Config > config
Detailed Description
template<typename ConfigT>
class net::in::stream::SocketClient< ConfigT >
Definition at line 36 of file SocketClient.h.
Member Typedef Documentation
Config
template<typename ConfigT > using net::in::stream::SocketClient< ConfigT >::Config = ConfigT
Definition at line 44 of file SocketClient.h.
Super
template<typename ConfigT > using net::in::stream::SocketClient< ConfigT >::Super = net::stream::SocketClient<ConfigT, net::in::stream::ClientSocket> private
Definition at line 38 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient()
template<typename Config > net::in::stream::SocketClient< Config >::SocketClient (const std::string & name) explicit protected
Definition at line 29 of file SocketClient.hpp.
         : Super(name) {
     }
Member Function Documentation
connect() [1/3]
template<typename Config > void net::in::stream::SocketClient< Config >::connect (const std::string & ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 34 of file SocketClient.hpp.
{
         connect(SocketAddress(ipOrHostname, port), onError);
     }
References core::system::connect().
connect() [2/3]
template<typename Config > void net::in::stream::SocketClient< Config >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindIpOrHostname, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 41 of file SocketClient.hpp.
{
         connect(SocketAddress(ipOrHostname, port), SocketAddress(bindIpOrHostname), onError);
     }
References core::system::connect().
connect() [3/3]
template<typename Config > void net::in::stream::SocketClient< Config >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindIpOrHostname, uint16_t bindPort, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 49 of file SocketClient.hpp.
{
         connect(SocketAddress(ipOrHostname, port), SocketAddress(bindIpOrHostname, bindPort), onError);
     }
References core::system::connect().
The documentation for this class was generated from the following files:
net/in/stream/SocketClient.h
net/in/stream/SocketClient.hpp