snode.c: express::Router Class Reference
express::Router Class Reference
#include <Router.h>
Public Member Functions
Router ()
Route & use (const Router &router)
Route & use (const std::string &relativeMountPath, const Router &router)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & all (const Router &router)
Route & all (const std::string &relativeMountPath, const Router &router)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & get (const Router &router)
Route & get (const std::string &relativeMountPath, const Router &router)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & put (const Router &router)
Route & put (const std::string &relativeMountPath, const Router &router)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & post (const Router &router)
Route & post (const std::string &relativeMountPath, const Router &router)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & del (const Router &router)
Route & del (const std::string &relativeMountPath, const Router &router)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & connect (const Router &router)
Route & connect (const std::string &relativeMountPath, const Router &router)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & options (const Router &router)
Route & options (const std::string &relativeMountPath, const Router &router)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & trace (const Router &router)
Route & trace (const std::string &relativeMountPath, const Router &router)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & patch (const Router &router)
Route & patch (const std::string &relativeMountPath, const Router &router)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Route & head (const Router &router)
Route & head (const std::string &relativeMountPath, const Router &router)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &state)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> &lambda, Lambdas... lambdas)
Protected Attributes
std::shared_ptr< RootRoute > rootRoute = nullptr
Friends
class Route
class RootRoute
Detailed Description
Definition at line 67 of file Router.h.
Constructor & Destructor Documentation
Router()
express::Router::Router ()
Definition at line 50 of file Router.cpp.
         : rootRoute(std::make_shared<RootRoute>()) {
     }
Member Function Documentation
all() [1/10]
Route & express::Router::all (const Router & router)
Definition at line 55 of file Router.cpp.
all() [2/10]
Route & express::Router::all (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 55 of file Router.cpp.
all() [3/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 63 of file Router.hpp.
all() [4/10]
Route & express::Router::all (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 55 of file Router.cpp.
all() [5/10]
template<typename... Lambdas> Route & express::Router::all (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 63 of file Router.hpp.
all() [6/10]
Route & express::Router::all (const std::string & relativeMountPath, const Router & router)
Definition at line 55 of file Router.cpp.
all() [7/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 55 of file Router.cpp.
all() [8/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 63 of file Router.hpp.
all() [9/10]
Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 55 of file Router.cpp.
all() [10/10]
template<typename... Lambdas> Route & express::Router::all (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 63 of file Router.hpp.
connect() [1/10]
Route & express::Router::connect (const Router & router)
Definition at line 60 of file Router.cpp.
connect() [2/10]
Route & express::Router::connect (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 60 of file Router.cpp.
connect() [3/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 68 of file Router.hpp.
connect() [4/10]
Route & express::Router::connect (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 60 of file Router.cpp.
connect() [5/10]
template<typename... Lambdas> Route & express::Router::connect (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 68 of file Router.hpp.
connect() [6/10]
Route & express::Router::connect (const std::string & relativeMountPath, const Router & router)
Definition at line 60 of file Router.cpp.
connect() [7/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 60 of file Router.cpp.
connect() [8/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 68 of file Router.hpp.
connect() [9/10]
Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 60 of file Router.cpp.
connect() [10/10]
template<typename... Lambdas> Route & express::Router::connect (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 68 of file Router.hpp.
del() [1/10]
Route & express::Router::del (const Router & router)
Definition at line 59 of file Router.cpp.
del() [2/10]
Route & express::Router::del (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 59 of file Router.cpp.
del() [3/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 67 of file Router.hpp.
del() [4/10]
Route & express::Router::del (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 59 of file Router.cpp.
del() [5/10]
template<typename... Lambdas> Route & express::Router::del (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 67 of file Router.hpp.
del() [6/10]
Route & express::Router::del (const std::string & relativeMountPath, const Router & router)
Definition at line 59 of file Router.cpp.
del() [7/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 59 of file Router.cpp.
del() [8/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 67 of file Router.hpp.
del() [9/10]
Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 59 of file Router.cpp.
del() [10/10]
template<typename... Lambdas> Route & express::Router::del (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 67 of file Router.hpp.
get() [1/10]
Route & express::Router::get (const Router & router)
Definition at line 56 of file Router.cpp.
get() [2/10]
Route & express::Router::get (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 56 of file Router.cpp.
get() [3/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 64 of file Router.hpp.
get() [4/10]
Route & express::Router::get (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 56 of file Router.cpp.
get() [5/10]
template<typename... Lambdas> Route & express::Router::get (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 64 of file Router.hpp.
get() [6/10]
Route & express::Router::get (const std::string & relativeMountPath, const Router & router)
Definition at line 56 of file Router.cpp.
get() [7/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 56 of file Router.cpp.
get() [8/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 64 of file Router.hpp.
get() [9/10]
Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 56 of file Router.cpp.
get() [10/10]
template<typename... Lambdas> Route & express::Router::get (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 64 of file Router.hpp.
head() [1/10]
Route & express::Router::head (const Router & router)
Definition at line 64 of file Router.cpp.
head() [2/10]
Route & express::Router::head (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 64 of file Router.cpp.
head() [3/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 72 of file Router.hpp.
head() [4/10]
Route & express::Router::head (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 64 of file Router.cpp.
head() [5/10]
template<typename... Lambdas> Route & express::Router::head (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 72 of file Router.hpp.
head() [6/10]
Route & express::Router::head (const std::string & relativeMountPath, const Router & router)
Definition at line 64 of file Router.cpp.
head() [7/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 64 of file Router.cpp.
head() [8/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 72 of file Router.hpp.
head() [9/10]
Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 64 of file Router.cpp.
head() [10/10]
template<typename... Lambdas> Route & express::Router::head (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 72 of file Router.hpp.
options() [1/10]
Route & express::Router::options (const Router & router)
Definition at line 61 of file Router.cpp.
Referenced by express::middleware::StaticMiddleware::StaticMiddleware().
options() [2/10]
Route & express::Router::options (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 61 of file Router.cpp.
options() [3/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 69 of file Router.hpp.
options() [4/10]
Route & express::Router::options (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 61 of file Router.cpp.
options() [5/10]
template<typename... Lambdas> Route & express::Router::options (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 69 of file Router.hpp.
options() [6/10]
Route & express::Router::options (const std::string & relativeMountPath, const Router & router)
Definition at line 61 of file Router.cpp.
options() [7/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 61 of file Router.cpp.
options() [8/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 69 of file Router.hpp.
options() [9/10]
Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 61 of file Router.cpp.
options() [10/10]
template<typename... Lambdas> Route & express::Router::options (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 69 of file Router.hpp.
patch() [1/10]
Route & express::Router::patch (const Router & router)
Definition at line 63 of file Router.cpp.
patch() [2/10]
Route & express::Router::patch (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 63 of file Router.cpp.
patch() [3/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 71 of file Router.hpp.
patch() [4/10]
Route & express::Router::patch (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 63 of file Router.cpp.
patch() [5/10]
template<typename... Lambdas> Route & express::Router::patch (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 71 of file Router.hpp.
patch() [6/10]
Route & express::Router::patch (const std::string & relativeMountPath, const Router & router)
Definition at line 63 of file Router.cpp.
patch() [7/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 63 of file Router.cpp.
patch() [8/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 71 of file Router.hpp.
patch() [9/10]
Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 63 of file Router.cpp.
patch() [10/10]
template<typename... Lambdas> Route & express::Router::patch (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 71 of file Router.hpp.
post() [1/10]
Route & express::Router::post (const Router & router)
Definition at line 58 of file Router.cpp.
post() [2/10]
Route & express::Router::post (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 58 of file Router.cpp.
post() [3/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 66 of file Router.hpp.
post() [4/10]
Route & express::Router::post (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 58 of file Router.cpp.
post() [5/10]
template<typename... Lambdas> Route & express::Router::post (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 66 of file Router.hpp.
post() [6/10]
Route & express::Router::post (const std::string & relativeMountPath, const Router & router)
Definition at line 58 of file Router.cpp.
post() [7/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 58 of file Router.cpp.
post() [8/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 66 of file Router.hpp.
post() [9/10]
Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 58 of file Router.cpp.
post() [10/10]
template<typename... Lambdas> Route & express::Router::post (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 66 of file Router.hpp.
put() [1/10]
Route & express::Router::put (const Router & router)
Definition at line 57 of file Router.cpp.
put() [2/10]
Route & express::Router::put (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 57 of file Router.cpp.
put() [3/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 65 of file Router.hpp.
put() [4/10]
Route & express::Router::put (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 57 of file Router.cpp.
put() [5/10]
template<typename... Lambdas> Route & express::Router::put (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 65 of file Router.hpp.
put() [6/10]
Route & express::Router::put (const std::string & relativeMountPath, const Router & router)
Definition at line 57 of file Router.cpp.
put() [7/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 57 of file Router.cpp.
put() [8/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 65 of file Router.hpp.
put() [9/10]
Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 57 of file Router.cpp.
put() [10/10]
template<typename... Lambdas> Route & express::Router::put (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 65 of file Router.hpp.
trace() [1/10]
Route & express::Router::trace (const Router & router)
Definition at line 62 of file Router.cpp.
trace() [2/10]
Route & express::Router::trace (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 62 of file Router.cpp.
trace() [3/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 70 of file Router.hpp.
trace() [4/10]
Route & express::Router::trace (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 62 of file Router.cpp.
trace() [5/10]
template<typename... Lambdas> Route & express::Router::trace (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 70 of file Router.hpp.
trace() [6/10]
Route & express::Router::trace (const std::string & relativeMountPath, const Router & router)
Definition at line 62 of file Router.cpp.
trace() [7/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 62 of file Router.cpp.
trace() [8/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 70 of file Router.hpp.
trace() [9/10]
Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 62 of file Router.cpp.
trace() [10/10]
template<typename... Lambdas> Route & express::Router::trace (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 70 of file Router.hpp.
use() [1/10]
Route & express::Router::use (const Router & router)
Definition at line 54 of file Router.cpp.
Referenced by express::middleware::BasicAuthentication::BasicAuthentication(), express::middleware::JsonMiddleware::JsonMiddleware(), express::middleware::StaticMiddleware::StaticMiddleware(), and express::middleware::VHost::VHost().
use() [2/10]
Route & express::Router::use (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 54 of file Router.cpp.
use() [3/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 62 of file Router.hpp.
use() [4/10]
Route & express::Router::use (const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 54 of file Router.cpp.
use() [5/10]
template<typename... Lambdas> Route & express::Router::use (const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 62 of file Router.hpp.
use() [6/10]
Route & express::Router::use (const std::string & relativeMountPath, const Router & router)
Definition at line 54 of file Router.cpp.
use() [7/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 54 of file Router.cpp.
use() [8/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 62 of file Router.hpp.
use() [9/10]
Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda)
Definition at line 54 of file Router.cpp.
use() [10/10]
template<typename... Lambdas> Route & express::Router::use (const std::string & relativeMountPath, const std::function< void(Request &req, Response &res, Next &state)> & lambda, Lambdas... lambdas)
Definition at line 62 of file Router.hpp.
Friends And Related Function Documentation
RootRoute
friend class RootRoute friend
Definition at line 87 of file Router.h.
Route
friend class Route friend
Definition at line 86 of file Router.h.
Member Data Documentation
rootRoute
std::shared_ptr<RootRoute> express::Router::rootRoute = nullptr protected
Definition at line 84 of file Router.h.
The documentation for this class was generated from the following files:
express/Router.h
express/Router.cpp
express/Router.hpp