snode.c: core::Observer Class Reference
core::Observer Class Reference abstract
#include <EventReceiver.h>
Public Member Functions
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Private Attributes
int observationCounter = 0
Detailed Description
Definition at line 34 of file EventReceiver.h.
Member Function Documentation
getObservationCounter()
int core::Observer::getObservationCounter () inline
Definition at line 48 of file EventReceiver.h.
{
             return observationCounter;
         }
References observationCounter.
Referenced by core::DescriptorEventDispatcher::disable().
isObserved()
bool core::Observer::isObserved () inline
Definition at line 36 of file EventReceiver.h.
{
             return observationCounter > 0;
         }
References observationCounter.
observed()
void core::Observer::observed () inline
Definition at line 40 of file EventReceiver.h.
{
             observationCounter++;
         }
References observationCounter.
Referenced by core::EventReceiver::enable().
unObserved()
void core::Observer::unObserved () inline
Definition at line 44 of file EventReceiver.h.
{
             observationCounter--;
         }
References observationCounter.
Referenced by core::EventReceiver::disabled().
unobservedEvent()
virtual void core::Observer::unobservedEvent () pure virtual
Implemented in core::socket::stream::tls::TLSShutdown, core::socket::stream::tls::TLSHandshake, core::socket::stream::SocketConnector< ClientConfigT, SocketConnectionT >, core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::legacy::SocketConnection< SocketT > >, core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >, core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >, core::socket::stream::SocketAcceptor< ServerConfigT, core::socket::stream::tls::SocketConnection< SocketT > >, core::socket::stream::SocketAcceptor< ServerConfigT, core::socket::stream::legacy::SocketConnection< SocketT > >, core::pipe::PipeSource, core::pipe::PipeSink, core::file::FileReader, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Member Data Documentation
observationCounter
int core::Observer::observationCounter = 0 private
Definition at line 55 of file EventReceiver.h.
Referenced by getObservationCounter(), isObserved(), observed(), and unObserved().
The documentation for this class was generated from the following file:
core/EventReceiver.h