snode.c: net::in6::stream::ConfigBind Class Reference
net::in6::stream::ConfigBind Class Reference
#include <ConfigBind.h>
Public Member Functions
ConfigBind (CLI::App *baseSc)
const std::string & getBindHost () const
uint16_t getBindPort () const
net::in6::SocketAddress getBindAddress () const
Protected Attributes
CLI::App * bindSc = nullptr
CLI::Option * bindHostOpt = nullptr
CLI::Option * bindPortOpt = nullptr
Private Attributes
std::string bindHost = ""
uint16_t bindPort = 0
Detailed Description
Definition at line 38 of file ConfigBind.h.
Constructor & Destructor Documentation
ConfigBind()
net::in6::stream::ConfigBind::ConfigBind (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigBind.cpp.
{
         bindSc = baseSc->add_subcommand("bind");
         bindSc->group("Sub-Options (use -h,--help on them)");
         bindSc->description("Server socket bind options");
         bindSc->configurable();
         bindHostOpt = bindSc->add_option("-a,--host", bindHost, "Bind host name or IP address");
         bindHostOpt->type_name("[hostname|ip]");
         bindHostOpt->default_val("::");
         bindHostOpt->configurable();
         bindPortOpt = bindSc->add_option("-p,--port", bindPort, "Bind port number");
         bindPortOpt->type_name("[uint16_t]");
         bindPortOpt->default_val(0);
         bindPortOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindHost, bindHostOpt, bindPort, bindPortOpt, bindSc, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), CLI::App::group(), and CLI::Option::type_name().
Member Function Documentation
getBindAddress()
SocketAddress net::in6::stream::ConfigBind::getBindAddress () const
Definition at line 54 of file ConfigBind.cpp.
{
         return net::in6::SocketAddress(bindHost, bindPort);
     }
References bindHost, and bindPort.
getBindHost()
const std::string & net::in6::stream::ConfigBind::getBindHost () const
Definition at line 46 of file ConfigBind.cpp.
{
         return bindHost;
     }
References bindHost.
getBindPort()
uint16_t net::in6::stream::ConfigBind::getBindPort () const
Definition at line 50 of file ConfigBind.cpp.
{
         return bindPort;
     }
References bindPort.
Member Data Documentation
bindHost
std::string net::in6::stream::ConfigBind::bindHost = "" private
Definition at line 54 of file ConfigBind.h.
Referenced by ConfigBind(), getBindAddress(), and getBindHost().
bindHostOpt
CLI::Option* net::in6::stream::ConfigBind::bindHostOpt = nullptr protected
Definition at line 50 of file ConfigBind.h.
Referenced by ConfigBind().
bindPort
uint16_t net::in6::stream::ConfigBind::bindPort = 0 private
Definition at line 55 of file ConfigBind.h.
Referenced by ConfigBind(), getBindAddress(), and getBindPort().
bindPortOpt
CLI::Option* net::in6::stream::ConfigBind::bindPortOpt = nullptr protected
Definition at line 51 of file ConfigBind.h.
Referenced by ConfigBind(), and net::in6::stream::ServerConfig::required().
bindSc
CLI::App* net::in6::stream::ConfigBind::bindSc = nullptr protected
Definition at line 49 of file ConfigBind.h.
Referenced by ConfigBind(), and net::in6::stream::ServerConfig::required().
The documentation for this class was generated from the following files:
net/in6/stream/ConfigBind.h
net/in6/stream/ConfigBind.cpp