snode.c: core::socket::stream::tls::SocketConnection< SocketT > Class Template Reference
core::socket::stream::tls::SocketConnection< SocketT > Class Template Reference
#include <SocketConnection.h>
Public Types
using SocketAddress = typename Super::SocketAddress
Public Member Functions
SocketConnection (int fd, const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const SocketAddress &localAddress, const SocketAddress &remoteAddress, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onDisconnect, const utils::Timeval &readTimeout, const utils::Timeval &writeTimeout, std::size_t readBlockSize, std::size_t writeBlockSize, const utils::Timeval &terminateTimeout)
SSL * getSSL () const
Public Member Functions inherited from core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >
void close () final
void shutdownRead () final
void shutdownWrite () final
void setTimeout (const utils::Timeval &timeout) final
const SocketAddress & getRemoteAddress () const
const SocketAddress & getLocalAddress () const
int getDescriptor () const override
core::socket::SocketContext * getSocketContext ()
Private Types
using Super = core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, typename SocketT::SocketAddress >
using Socket = SocketT
using SocketReader = core::socket::stream::tls::SocketReader< Socket >
using SocketWriter = core::socket::stream::tls::SocketWriter< Socket >
Private Member Functions
~SocketConnection () override=default
SSL * startSSL (SSL_CTX *ctx, const utils::Timeval &initTimeout, const utils::Timeval &shutdownTimeout)
void stopSSL ()
void doSSLHandshake (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int)> &onError) override
void doSSLShutdown (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int)> &onError, const utils::Timeval &shutdownTimeout)
void doReadShutdown () override
void doWriteShutdown () override
void setSSLError (int sslErr)
Private Attributes
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
utils::Timeval initTimeout
utils::Timeval shutdownTimeout
Friends
template<typename ServerConfig , typename Socket >
class SocketAcceptor
template<typename ServerConfig , typename SocketConnection >
class core::socket::stream::SocketAcceptor
template<typename ClientConfig , typename Socket >
class SocketConnector
template<typename ClientConfig , typename SocketConnection >
class core::socket::stream::SocketConnector
Additional Inherited Members
Protected Types inherited from core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >
using Super = core::socket::SocketConnection
using SocketReader = core::socket::stream::tls::SocketReader< SocketT >
using SocketWriter = core::socket::stream::tls::SocketWriter< SocketT >
using SocketAddress = SocketT::SocketAddress
Protected Types inherited from core::socket::stream::SocketReader< SocketT >
using Socket = SocketT
Protected Types inherited from core::socket::stream::SocketWriter< SocketT >
using Socket = SocketT
Protected Member Functions inherited from core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >
SocketConnection (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const SocketAddress &localAddress, const SocketAddress &remoteAddress, const std::function< void()> &onConnect, const std::function< void()> &onDisconnect, const utils::Timeval &readTimeout, const utils::Timeval &writeTimeout, std::size_t readBlockSize, std::size_t writeBlockSize, const utils::Timeval &terminateTimeout)
~SocketConnection () override
Protected Member Functions inherited from core::socket::SocketConnection
SocketConnection (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory)
void onConnected ()
void onDisconnected ()
void onReceiveFromPeer ()
void onWriteError (int errnum)
void onReadError (int errnum)
core::socket::SocketContext * getSocketContext ()
core::socket::SocketContext * switchSocketContext (core::socket::SocketContextFactory *socketContextFactory)
Protected Member Functions inherited from core::socket::stream::tls::SocketReader< SocketT >
bool hasBufferedData () const override
void terminate () override
Protected Member Functions inherited from core::socket::stream::SocketReader< SocketT >
SocketReader (const std::function< void(int)> &onError, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
~SocketReader () override=default
void setBlockSize (std::size_t readBlockSize)
ssize_t readFromPeer (char *junk, std::size_t junkLen)
void doRead ()
void shutdown ()
Protected Member Functions inherited from core::eventreceiver::ReadEventReceiver
ReadEventReceiver (const std::string &name, const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
void enable (int fd)
void disable ()
void suspend ()
void resume ()
void setTimeout (const utils::Timeval &timeout)
void checkTimeout (const utils::Timeval &currentTime)
int getRegisteredFd ()
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
bool isEnabled () const
bool isSuspended () const
Protected Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Protected Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish () const
const std::string & getName ()
Protected Member Functions inherited from core::socket::stream::tls::SocketWriter< SocketT >
void terminate () override
Protected Member Functions inherited from core::socket::stream::SocketWriter< SocketT >
SocketWriter (const std::function< void(int)> &onError, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
~SocketWriter () override=default
void setBlockSize (std::size_t writeBlockSize)
void sendToPeer (const char *junk, std::size_t junkLen)
void doWrite ()
void shutdown ()
Protected Member Functions inherited from core::eventreceiver::WriteEventReceiver
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout=60)
Protected Attributes inherited from core::socket::stream::tls::SocketReader< SocketT >
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
Protected Attributes inherited from core::EventReceiver
Event event
Protected Attributes inherited from core::socket::stream::tls::SocketWriter< SocketT >
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
Detailed Description
template<typename SocketT>
class core::socket::stream::tls::SocketConnection< SocketT >
Definition at line 47 of file SocketConnection.h.
Member Typedef Documentation
Socket
template<typename SocketT > using core::socket::stream::tls::SocketConnection< SocketT >::Socket = SocketT private
Definition at line 56 of file SocketConnection.h.
SocketAddress
template<typename SocketT > using core::socket::stream::tls::SocketConnection< SocketT >::SocketAddress = typename Super::SocketAddress
Definition at line 62 of file SocketConnection.h.
SocketReader
template<typename SocketT > using core::socket::stream::tls::SocketConnection< SocketT >::SocketReader = core::socket::stream::tls::SocketReader<Socket> private
Definition at line 58 of file SocketConnection.h.
SocketWriter
template<typename SocketT > using core::socket::stream::tls::SocketConnection< SocketT >::SocketWriter = core::socket::stream::tls::SocketWriter<Socket> private
Definition at line 59 of file SocketConnection.h.
Super
template<typename SocketT > using core::socket::stream::tls::SocketConnection< SocketT >::Super = core::socket::stream::SocketConnection<core::socket::stream::tls::SocketReader<SocketT>, core::socket::stream::tls::SocketWriter<SocketT>, typename SocketT::SocketAddress> private
Definition at line 52 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection()
template<typename SocketT > core::socket::stream::tls::SocketConnection< SocketT >::SocketConnection (int fd, const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory, const SocketAddress & localAddress, const SocketAddress & remoteAddress, const std::function< void(SocketConnection< SocketT > *)> & onConnect, const std::function< void(SocketConnection< SocketT > *)> & onDisconnect, const utils::Timeval & readTimeout, const utils::Timeval & writeTimeout, std::size_t readBlockSize, std::size_t writeBlockSize, const utils::Timeval & terminateTimeout) inline
Definition at line 64 of file SocketConnection.h.
             : Super::Descriptor(fd)
             , Super(
                   socketContextFactory,
                   localAddress,
                   remoteAddress,
                   [onConnect, this]() -> void {
                       onConnect(this);
                   },
                   [onDisconnect, this]() -> void {
                       onDisconnect(this);
                   },
                   readTimeout,
                   writeTimeout,
                   readBlockSize,
                   writeBlockSize,
                   terminateTimeout) {
         }
~SocketConnection()
template<typename SocketT > core::socket::stream::tls::SocketConnection< SocketT >::~SocketConnection () override private virtual default
Reimplemented from core::socket::SocketConnection.
Member Function Documentation
doReadShutdown()
template<typename SocketT > void core::socket::stream::tls::SocketConnection< SocketT >::doReadShutdown () inline override private virtual
Reimplemented from core::socket::stream::SocketReader< SocketT >.
Definition at line 229 of file SocketConnection.h.
{
             if (SSL_get_shutdown(ssl) == (SSL_SENT_SHUTDOWN | SSL_RECEIVED_SHUTDOWN)) {
                 VLOG(0) << "SSL_Shutdown COMPLETED: Close_notify sent and received";
                 SocketWriter::doWriteShutdown();
             } else {
                 VLOG(0) << "SSL_Shutdown WAITING: Close_notify received but not send";
             }
         }
References core::socket::stream::SocketWriter< SocketT >::doWriteShutdown().
doSSLHandshake()
template<typename SocketT > void core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int)> & onError) inline override private virtual
Implements core::socket::stream::tls::SocketReader< SocketT >.
Definition at line 130 of file SocketConnection.h.
{
             int resumeSocketReader = false;
             int resumeSocketWriter = false;
             if (!SocketReader::isSuspended()) {
                 SocketReader::suspend();
                 resumeSocketReader = true;
             }
             if (!SocketWriter::isSuspended()) {
                 SocketWriter::suspend();
                 resumeSocketWriter = true;
             }
             TLSHandshake::doHandshake(
                 ssl,
                 [onSuccess, this, resumeSocketReader, resumeSocketWriter](void) -> void { // onSuccess
                     if (resumeSocketReader) {
                         SocketReader::resume();
                     }
                     if (resumeSocketWriter) {
                         SocketWriter::resume();
                     }
                     onSuccess();
                 },
                 [onTimeout, this](void) -> void { // onTimeout
                     if (SocketReader::isEnabled()) {
                         SocketReader::disable();
                     }
                     if (SocketWriter::isEnabled()) {
                         SocketWriter::disable();
                     }
                     onTimeout();
                 },
                 [onError, this](int sslErr) -> void { // onError
                     setSSLError(sslErr);
                     if (SocketReader::isEnabled()) {
                         SocketReader::disable();
                     }
                     if (SocketWriter::isEnabled()) {
                         SocketWriter::disable();
                     }
                     onError(sslErr);
                 },
                 initTimeout);
         }
References core::DescriptorEventReceiver::disable(), core::socket::stream::tls::TLSHandshake::doHandshake(), core::DescriptorEventReceiver::isEnabled(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
doSSLShutdown()
template<typename SocketT > void core::socket::stream::tls::SocketConnection< SocketT >::doSSLShutdown (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int)> & onError, const utils::Timeval & shutdownTimeout) inline private
Definition at line 179 of file SocketConnection.h.
{
             int resumeSocketReader = false;
             int resumeSocketWriter = false;
             if (!SocketReader::isSuspended()) {
                 SocketReader::suspend();
                 resumeSocketReader = true;
             }
             if (!SocketWriter::isSuspended()) {
                 SocketWriter::suspend();
                 resumeSocketWriter = true;
             }
             TLSShutdown::doShutdown(
                 ssl,
                 [onSuccess, this, resumeSocketReader, resumeSocketWriter](void) -> void { // onSuccess
                     if (resumeSocketReader) {
                         SocketReader::resume();
                     }
                     if (resumeSocketWriter) {
                         SocketWriter::resume();
                     }
                     onSuccess();
                 },
                 [onTimeout, this, resumeSocketReader, resumeSocketWriter](void) -> void { // onTimeout
                     if (resumeSocketReader) {
                         SocketReader::resume();
                     }
                     if (resumeSocketWriter) {
                         SocketWriter::resume();
                     }
                     onTimeout();
                 },
                 [onError, this, resumeSocketReader, resumeSocketWriter](int sslErr) -> void { // onError
                     setSSLError(sslErr);
                     if (resumeSocketReader) {
                         SocketReader::resume();
                     }
                     if (resumeSocketWriter) {
                         SocketWriter::resume();
                     }
                     onError(sslErr);
                 },
                 shutdownTimeout);
         }
References core::socket::stream::tls::TLSShutdown::doShutdown(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventReceiver::resume(), and core::DescriptorEventReceiver::suspend().
doWriteShutdown()
template<typename SocketT > void core::socket::stream::tls::SocketConnection< SocketT >::doWriteShutdown () inline override private virtual
Reimplemented from core::socket::stream::SocketWriter< SocketT >.
Definition at line 238 of file SocketConnection.h.
{
             if ((SSL_get_shutdown(ssl) & SSL_SENT_SHUTDOWN) == 0) {
                 doSSLShutdown(
                     [this]() -> void { // thus send one
                         if (SSL_get_shutdown(ssl) == (SSL_SENT_SHUTDOWN | SSL_RECEIVED_SHUTDOWN)) {
                             VLOG(0) << "SSL_Shutdown COMPLETED: Close_notify sent and received";
                             SocketWriter::doWriteShutdown();
                         } else {
                             VLOG(0) << "SSL_Shutdown WAITING: Close_notify sent but not received";
                         }
                     },
                     [this]() -> void {
                         LOG(WARNING) << "SSL_shutdown: Handshake timed out";
                         SocketWriter::disable();
                     },
                     [this](int sslErr) -> void {
                         ssl_log("SSL_shutdown: Handshake failed", sslErr);
                         SocketWriter::disable();
                     },
                     shutdownTimeout);
             }
         }
References core::DescriptorEventReceiver::disable(), core::socket::stream::SocketWriter< SocketT >::doWriteShutdown(), and core::socket::stream::tls::ssl_log().
getSSL()
template<typename SocketT > SSL* core::socket::stream::tls::SocketConnection< SocketT >::getSSL () const inline
Definition at line 93 of file SocketConnection.h.
{
             return ssl;
         }
setSSLError()
template<typename SocketT > void core::socket::stream::tls::SocketConnection< SocketT >::setSSLError (int sslErr) inline private
Definition at line 261 of file SocketConnection.h.
{
             this->sslErr = sslErr;
         }
startSSL()
template<typename SocketT > SSL* core::socket::stream::tls::SocketConnection< SocketT >::startSSL (SSL_CTX * ctx, const utils::Timeval & initTimeout, const utils::Timeval & shutdownTimeout) inline private
Definition at line 100 of file SocketConnection.h.
{
             this->initTimeout = initTimeout;
             this->shutdownTimeout = shutdownTimeout;
             if (ctx != nullptr) {
                 ssl = SSL_new(ctx);
                 if (ssl != nullptr) {
                     if (SSL_set_fd(ssl, Socket::getFd()) == 1) {
                         SocketReader::ssl = ssl;
                         SocketWriter::ssl = ssl;
                     } else {
                         SSL_free(ssl);
                         ssl = nullptr;
                     }
                 }
             }
             return ssl;
         }
References core::Descriptor::getFd(), core::socket::stream::tls::SocketReader< SocketT >::ssl, and core::socket::stream::tls::SocketWriter< SocketT >::ssl.
stopSSL()
template<typename SocketT > void core::socket::stream::tls::SocketConnection< SocketT >::stopSSL () inline private
Definition at line 120 of file SocketConnection.h.
{
             if (ssl != nullptr) {
                 SSL_free(ssl);
                 ssl = nullptr;
                 SocketReader::ssl = nullptr;
                 SocketWriter::ssl = nullptr;
             }
         }
References core::socket::stream::tls::SocketReader< SocketT >::ssl, and core::socket::stream::tls::SocketWriter< SocketT >::ssl.
Friends And Related Function Documentation
core::socket::stream::SocketAcceptor
template<typename SocketT > template<typename ServerConfig , typename SocketConnection > friend class core::socket::stream::SocketAcceptor friend
Definition at line 276 of file SocketConnection.h.
core::socket::stream::SocketConnector
template<typename SocketT > template<typename ClientConfig , typename SocketConnection > friend class core::socket::stream::SocketConnector friend
Definition at line 282 of file SocketConnection.h.
SocketAcceptor
template<typename SocketT > template<typename ServerConfig , typename Socket > friend class SocketAcceptor friend
Definition at line 273 of file SocketConnection.h.
SocketConnector
template<typename SocketT > template<typename ClientConfig , typename Socket > friend class SocketConnector friend
Definition at line 279 of file SocketConnection.h.
Member Data Documentation
initTimeout
template<typename SocketT > utils::Timeval core::socket::stream::tls::SocketConnection< SocketT >::initTimeout private
Definition at line 269 of file SocketConnection.h.
shutdownTimeout
template<typename SocketT > utils::Timeval core::socket::stream::tls::SocketConnection< SocketT >::shutdownTimeout private
Definition at line 270 of file SocketConnection.h.
ssl
template<typename SocketT > SSL* core::socket::stream::tls::SocketConnection< SocketT >::ssl = nullptr private
Definition at line 265 of file SocketConnection.h.
sslErr
template<typename SocketT > int core::socket::stream::tls::SocketConnection< SocketT >::sslErr = SSL_ERROR_NONE private
Definition at line 267 of file SocketConnection.h.
The documentation for this class was generated from the following file:
core/socket/stream/tls/SocketConnection.h