snode.c: express::middleware::StaticMiddleware Class Reference
express::middleware::StaticMiddleware Class Reference
#include <StaticMiddleware.h>
Public Member Functions
StaticMiddleware & clearStdHeaders ()
StaticMiddleware & setStdHeaders (const std::map< std::string, std::string > &stdHeaders)
StaticMiddleware & appendStdHeaders (const std::map< std::string, std::string > &stdHeaders)
StaticMiddleware & appendStdHeaders (const std::string &field, const std::string &value)
StaticMiddleware & appendStdCookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
StaticMiddleware & alwaysClose ()
Public Member Functions inherited from express::Router
Router ()
Route & use (const Router &router)
Route & use (const std::string &relativeMountPath, const Router &router)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & all (const Router &router)
Route & all (const std::string &relativeMountPath, const Router &router)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & get (const Router &router)
Route & get (const std::string &relativeMountPath, const Router &router)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & put (const Router &router)
Route & put (const std::string &relativeMountPath, const Router &router)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & post (const Router &router)
Route & post (const std::string &relativeMountPath, const Router &router)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & del (const Router &router)
Route & del (const std::string &relativeMountPath, const Router &router)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & connect (const Router &router)
Route & connect (const std::string &relativeMountPath, const Router &router)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & options (const Router &router)
Route & options (const std::string &relativeMountPath, const Router &router)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & trace (const Router &router)
Route & trace (const std::string &relativeMountPath, const Router &router)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & patch (const Router &router)
Route & patch (const std::string &relativeMountPath, const Router &router)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & head (const Router &router)
Route & head (const std::string &relativeMountPath, const Router &router)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Protected Member Functions
StaticMiddleware (const std::string &root)
Static Protected Member Functions
static class StaticMiddleware & instance (const std::string &root)
Private Member Functions
StaticMiddleware (const StaticMiddleware &)=delete
StaticMiddleware & operator= (const StaticMiddleware &)=delete
Private Attributes
std::string root
std::map< std::string, std::string > stdHeaders
std::map< std::string, web::http::CookieOptions > stdCookies = {}
bool forceClose = false
Friends
class StaticMiddleware & StaticMiddleware (const std::string &root)
Additional Inherited Members
Protected Attributes inherited from express::Router
std::shared_ptr< RootRoute > rootRoute = nullptr
Detailed Description
Definition at line 35 of file StaticMiddleware.h.
Constructor & Destructor Documentation
StaticMiddleware() [1/2]
express::middleware::StaticMiddleware::StaticMiddleware (const StaticMiddleware &) private delete
StaticMiddleware() [2/2]
express::middleware::StaticMiddleware::StaticMiddleware (const std::string & root) explicit protected
Definition at line 32 of file StaticMiddleware.cpp.
         : root(root) {
         use(
             [&stdHeaders = this->stdHeaders, &stdCookies = this->stdCookies, &forceClose = this->forceClose] MIDDLEWARE(req, res, next) {
                 if (req.method == "GET") {
                     if (forceClose) {
                         res.set("Connection", "Close");
                     } else {
                         res.set("Connection", "Keep-Alive");
                     }
                     res.set(stdHeaders);
                     for (auto& [value, options] : stdCookies) {
                         res.cookie(value, options.getValue(), options.getOptions());
                     }
                     next();
                 } else {
                     LOG(DEBUG) << "Wrong method " << req.method;
                     res.set("Connection", "Close");
                     res.sendStatus(400);
                 }
             },
             [] MIDDLEWARE(req, res, next) {
                 if (req.url == "/") {
                     LOG(INFO) << "REDIRECT " + req.url + " -> " + "/index.html";
                     res.redirect(308, "/index.html");
                 } else {
                     next();
                 }
             },
             [&root = this->root] APPLICATION(req, res) {
                 LOG(INFO) << "GET " + req.url + " -> " + root + req.url;
                 res.sendFile(root + req.url, [&req, &res](int ret) -> void {
                     if (ret != 0) {
                         PLOG(ERROR) << req.url;
                         res.status(404).end();
                     }
                 });
             });
     }
References for(), forceClose, MIDDLEWARE, express::Router::options(), stdCookies, stdHeaders, and express::Router::use().
Member Function Documentation
alwaysClose()
class StaticMiddleware & express::middleware::StaticMiddleware::alwaysClose ()
Definition at line 104 of file StaticMiddleware.cpp.
{
         this->forceClose = true;
         return *this;
     }
appendStdCookie()
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdCookie (const std::string & name, const std::string & value, const std::map< std::string, std::string > & options = {})
Definition at line 96 of file StaticMiddleware.cpp.
{
         this->stdCookies.insert({name, web::http::CookieOptions(value, options)});
         return *this;
     }
appendStdHeaders() [1/2]
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdHeaders (const std::map< std::string, std::string > & stdHeaders)
Definition at line 84 of file StaticMiddleware.cpp.
{
         this->stdHeaders.insert(stdHeaders.begin(), stdHeaders.end());
         return *this;
     }
appendStdHeaders() [2/2]
class StaticMiddleware & express::middleware::StaticMiddleware::appendStdHeaders (const std::string & field, const std::string & value)
Definition at line 90 of file StaticMiddleware.cpp.
{
         this->stdHeaders[field] = value;
         return *this;
     }
clearStdHeaders()
class StaticMiddleware & express::middleware::StaticMiddleware::clearStdHeaders ()
Definition at line 72 of file StaticMiddleware.cpp.
{
         this->stdHeaders.clear();
         return *this;
     }
instance()
class StaticMiddleware & express::middleware::StaticMiddleware::instance (const std::string & root) static protected
Definition at line 110 of file StaticMiddleware.cpp.
{
         // Keep all created static middlewares alive
         static std::map<const std::string, std::shared_ptr<class StaticMiddleware>> staticMiddlewares;
         if (!staticMiddlewares.contains(root)) {
             staticMiddlewares[root] = std::shared_ptr<StaticMiddleware>(new StaticMiddleware(root));
         }
         return *staticMiddlewares[root];
     }
References express::middleware::StaticMiddleware().
operator=()
StaticMiddleware& express::middleware::StaticMiddleware::operator= (const StaticMiddleware &) private delete
setStdHeaders()
class StaticMiddleware & express::middleware::StaticMiddleware::setStdHeaders (const std::map< std::string, std::string > & stdHeaders)
Definition at line 78 of file StaticMiddleware.cpp.
{
         this->stdHeaders = stdHeaders;
         return *this;
     }
Friends And Related Function Documentation
StaticMiddleware
class StaticMiddleware& StaticMiddleware (const std::string & root) friend
Definition at line 122 of file StaticMiddleware.cpp.
{
         return StaticMiddleware::instance(root);
     }
Member Data Documentation
forceClose
bool express::middleware::StaticMiddleware::forceClose = false private
Definition at line 59 of file StaticMiddleware.h.
Referenced by StaticMiddleware().
root
std::string express::middleware::StaticMiddleware::root private
Definition at line 55 of file StaticMiddleware.h.
stdCookies
std::map<std::string, web::http::CookieOptions> express::middleware::StaticMiddleware::stdCookies = {} private
Definition at line 58 of file StaticMiddleware.h.
Referenced by StaticMiddleware().
stdHeaders
std::map<std::string, std::string> express::middleware::StaticMiddleware::stdHeaders private
Initial value:
= {
            {"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}, {"X-Powered-By", "snode.c"}}
Definition at line 56 of file StaticMiddleware.h.
Referenced by StaticMiddleware().
The documentation for this class was generated from the following files:
express/middleware/StaticMiddleware.h
express/middleware/StaticMiddleware.cpp