snode.c: core::EventReceiver Class Reference
core::EventReceiver Class Reference abstract
#include <EventReceiver.h>
Classes
class TIMEOUT
Public Member Functions
int getRegisteredFd ()
virtual bool continueImmediately () const =0
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime)
void triggered (const utils::Timeval &currentTime)
void disabled ()
virtual void terminate ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Protected Member Functions
EventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
Private Member Functions
EventReceiver (const EventReceiver &)=delete
EventReceiver & operator= (const EventReceiver &)=delete
virtual void dispatchEvent ()=0
virtual void timeoutEvent ()=0
Private Attributes
DescriptorEventDispatcher & descriptorEventDispatcher
int registeredFd = -1
bool enabled = false
bool suspended = false
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
Detailed Description
Definition at line 58 of file EventReceiver.h.
Constructor & Destructor Documentation
EventReceiver() [1/2]
core::EventReceiver::EventReceiver (const EventReceiver &) private delete
EventReceiver() [2/2]
core::EventReceiver::EventReceiver (DescriptorEventDispatcher & descriptorEventDispatcher, const utils::Timeval & timeout = TIMEOUT::DISABLE) explicit protected
Definition at line 35 of file EventReceiver.cpp.
         : descriptorEventDispatcher(descriptorEventDispatcher)
         , maxInactivity(timeout)
         , initialTimeout(timeout) {
     }
~EventReceiver()
virtual core::EventReceiver::~EventReceiver () protected virtual default
Member Function Documentation
checkTimeout()
void core::EventReceiver::checkTimeout (const utils::Timeval & currentTime)
Definition at line 123 of file EventReceiver.cpp.
{
         if (maxInactivity >= 0 && currentTime - lastTriggered >= maxInactivity) {
             timeoutEvent();
         }
     }
References lastTriggered, maxInactivity, and timeoutEvent().
Referenced by core::DescriptorEventDispatcher::dispatchImmediateEvents().
continueImmediately()
virtual bool core::EventReceiver::continueImmediately () const pure virtual
Implemented in core::WriteEventReceiver, core::ReadEventReceiver, core::ExceptionalConditionEventReceiver, core::ConnectEventReceiver, and core::AcceptEventReceiver.
Referenced by core::epoll::DescriptorEventDispatcher::dispatchActiveEvents(), core::poll::DescriptorEventDispatcher::dispatchActiveEvents(), core::select::DescriptorEventDispatcher::dispatchActiveEvents(), core::DescriptorEventDispatcher::dispatchImmediateEvents(), and core::DescriptorEventDispatcher::getNextTimeout().
disable()
void core::EventReceiver::disable ()
Definition at line 56 of file EventReceiver.cpp.
{
         if (!isSuspended()) {
             suspend();
         }
         descriptorEventDispatcher.disable(this);
         enabled = false;
     }
References descriptorEventDispatcher, core::DescriptorEventDispatcher::disable(), enabled, isSuspended(), and suspend().
Referenced by core::AcceptEventReceiver::acceptTimeout(), core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::close(), core::socket::stream::SocketConnector< SocketConnectionT >::connectEvent(), core::ConnectEventReceiver::connectTimeout(), core::socket::stream::SocketReader< SocketT >::doRead(), core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), core::socket::stream::SocketWriter< SocketT >::doWrite(), core::socket::stream::SocketWriter< SocketT >::doWriteShutdown(), core::socket::stream::tls::SocketConnection< SocketT >::doWriteShutdown(), core::pipe::PipeSource::eof(), core::ExceptionalConditionEventReceiver::outOfBandTimeout(), core::file::FileReader::readEvent(), core::pipe::PipeSink::readEvent(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::ReadEventReceiver::readTimeout(), core::socket::stream::tls::TLSHandshake::readTimeout(), core::socket::stream::tls::TLSShutdown::readTimeout(), core::file::FileReader::sinkDisconnected(), terminate(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::pipe::PipeSource::writeEvent(), core::socket::stream::tls::TLSHandshake::writeEvent(), core::socket::stream::tls::TLSShutdown::writeEvent(), core::WriteEventReceiver::writeTimeout(), core::socket::stream::tls::TLSHandshake::writeTimeout(), and core::socket::stream::tls::TLSShutdown::writeTimeout().
disabled()
void core::EventReceiver::disabled ()
Definition at line 65 of file EventReceiver.cpp.
{
         unObserved();
     }
References core::Observer::unObserved().
Referenced by core::DescriptorEventDispatcher::disable().
dispatch()
void core::EventReceiver::dispatch (const utils::Timeval & currentTime)
Definition at line 112 of file EventReceiver.cpp.
{
         eventCounter++;
         triggered(currentTime);
         dispatchEvent();
     }
References dispatchEvent(), eventCounter, and triggered().
Referenced by core::epoll::DescriptorEventDispatcher::dispatchActiveEvents(), core::poll::DescriptorEventDispatcher::dispatchActiveEvents(), core::select::DescriptorEventDispatcher::dispatchActiveEvents(), and core::DescriptorEventDispatcher::dispatchImmediateEvents().
dispatchEvent()
virtual void core::EventReceiver::dispatchEvent () private pure virtual
Implemented in core::WriteEventReceiver, core::ReadEventReceiver, core::ExceptionalConditionEventReceiver, core::ConnectEventReceiver, and core::AcceptEventReceiver.
Referenced by dispatch().
enable()
void core::EventReceiver::enable (int fd)
Definition at line 45 of file EventReceiver.cpp.
{
         this->registeredFd = fd;
         observed();
         descriptorEventDispatcher.enable(this);
         lastTriggered = utils::Timeval::currentTime();
         enabled = true;
     }
References utils::Timeval::currentTime(), descriptorEventDispatcher, core::DescriptorEventDispatcher::enable(), enabled, lastTriggered, core::Observer::observed(), and registeredFd.
Referenced by core::socket::stream::SocketConnector< SocketConnectionT >::connect(), core::file::FileReader::FileReader(), core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::listen(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::socket::stream::SocketReader< SocketT >::SocketReader(), core::socket::stream::SocketWriter< SocketT >::SocketWriter(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), and core::socket::stream::tls::TLSShutdown::TLSShutdown().
getRegisteredFd()
int core::EventReceiver::getRegisteredFd ()
Definition at line 41 of file EventReceiver.cpp.
{
         return registeredFd;
     }
References registeredFd.
Referenced by core::DescriptorEventDispatcher::disable(), core::DescriptorEventDispatcher::enable(), core::epoll::DescriptorEventDispatcher::EPollEvents::mod(), core::epoll::DescriptorEventDispatcher::EPollEvents::modAdd(), core::select::DescriptorEventDispatcher::modAdd(), core::poll::PollFds::modAdd(), core::epoll::DescriptorEventDispatcher::EPollEvents::modDel(), core::select::DescriptorEventDispatcher::modDel(), core::poll::PollFds::modDel(), core::select::DescriptorEventDispatcher::modOff(), core::poll::PollFds::modOff(), core::select::DescriptorEventDispatcher::modOn(), core::poll::PollFds::modOn(), core::DescriptorEventDispatcher::resume(), and core::DescriptorEventDispatcher::suspend().
getTimeout()
utils::Timeval core::EventReceiver::getTimeout (const utils::Timeval & currentTime) const
Definition at line 108 of file EventReceiver.cpp.
{
         return (maxInactivity >= 0) ? maxInactivity - (currentTime - lastTriggered) : TIMEOUT::MAX;
     }
References lastTriggered, core::EventReceiver::TIMEOUT::MAX, and maxInactivity.
Referenced by core::DescriptorEventDispatcher::getNextTimeout().
isEnabled()
bool core::EventReceiver::isEnabled () const
Definition at line 69 of file EventReceiver.cpp.
{
         return enabled;
     }
References enabled.
Referenced by core::DescriptorEventDispatcher::disable(), core::DescriptorEventDispatcher::dispatchImmediateEvents(), core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), core::DescriptorEventDispatcher::enable(), core::DescriptorEventDispatcher::getNextTimeout(), resume(), core::file::FileReader::sinkDisconnected(), suspend(), and terminate().
isSuspended()
bool core::EventReceiver::isSuspended () const
Definition at line 88 of file EventReceiver.cpp.
{
         return suspended;
     }
References suspended.
Referenced by disable(), core::epoll::DescriptorEventDispatcher::dispatchActiveEvents(), core::poll::DescriptorEventDispatcher::dispatchActiveEvents(), core::select::DescriptorEventDispatcher::dispatchActiveEvents(), core::DescriptorEventDispatcher::dispatchImmediateEvents(), core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), core::socket::stream::tls::SocketConnection< SocketT >::doSSLShutdown(), core::DescriptorEventDispatcher::getNextTimeout(), core::DescriptorEventDispatcher::resume(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter< SocketT >::sendToPeer(), core::socket::stream::SocketWriter< SocketT >::shutdown(), and core::DescriptorEventDispatcher::suspend().
operator=()
EventReceiver& core::EventReceiver::operator= (const EventReceiver &) private delete
resume()
void core::EventReceiver::resume ()
Definition at line 80 of file EventReceiver.cpp.
{
         if (isEnabled()) {
             descriptorEventDispatcher.resume(this);
             suspended = false;
             lastTriggered = utils::Timeval::currentTime();
         }
     }
References utils::Timeval::currentTime(), descriptorEventDispatcher, isEnabled(), lastTriggered, core::DescriptorEventDispatcher::resume(), and suspended.
Referenced by core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), core::socket::stream::tls::SocketConnection< SocketT >::doSSLShutdown(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::pipe::PipeSource::send(), core::socket::stream::SocketWriter< SocketT >::sendToPeer(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
setTimeout()
void core::EventReceiver::setTimeout (const utils::Timeval & timeout)
Definition at line 98 of file EventReceiver.cpp.
{
         if (timeout == TIMEOUT::DEFAULT) {
             this->maxInactivity = initialTimeout;
         } else {
             this->maxInactivity = timeout;
         }
         triggered(utils::Timeval::currentTime());
     }
References utils::Timeval::currentTime(), core::EventReceiver::TIMEOUT::DEFAULT, initialTimeout, maxInactivity, and triggered().
Referenced by core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::setTimeout(), core::socket::stream::SocketReader< SocketT >::SocketReader(), core::socket::stream::SocketWriter< SocketT >::SocketWriter(), core::socket::stream::SocketReader< SocketT >::terminate(), and core::socket::stream::SocketWriter< SocketT >::terminate().
suspend()
void core::EventReceiver::suspend ()
Definition at line 73 of file EventReceiver.cpp.
{
         if (isEnabled()) {
             descriptorEventDispatcher.suspend(this);
             suspended = true;
         }
     }
References descriptorEventDispatcher, isEnabled(), core::DescriptorEventDispatcher::suspend(), and suspended.
Referenced by disable(), core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), core::socket::stream::tls::SocketConnection< SocketT >::doSSLShutdown(), core::socket::stream::SocketWriter< SocketT >::doWrite(), core::pipe::PipeSource::PipeSource(), core::socket::stream::tls::TLSHandshake::readEvent(), core::socket::stream::tls::TLSShutdown::readEvent(), core::socket::stream::SocketWriter< SocketT >::SocketWriter(), core::socket::stream::tls::TLSHandshake::TLSHandshake(), core::socket::stream::tls::TLSShutdown::TLSShutdown(), core::pipe::PipeSource::writeEvent(), core::socket::stream::tls::TLSHandshake::writeEvent(), and core::socket::stream::tls::TLSShutdown::writeEvent().
terminate()
void core::EventReceiver::terminate () virtual
Reimplemented in core::socket::stream::tls::SocketWriter< SocketT >, core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::SocketWriter< SocketT >, core::socket::stream::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, core::socket::stream::legacy::SocketReader< SocketT >, core::pipe::PipeSource, core::pipe::PipeSink, and core::file::FileReader.
Definition at line 92 of file EventReceiver.cpp.
{
         if (isEnabled()) {
             disable();
         }
     }
References disable(), and isEnabled().
Referenced by core::file::FileReader::terminate(), core::pipe::PipeSink::terminate(), and core::pipe::PipeSource::terminate().
timeoutEvent()
virtual void core::EventReceiver::timeoutEvent () private pure virtual
Implemented in core::WriteEventReceiver, core::ReadEventReceiver, core::ExceptionalConditionEventReceiver, core::ConnectEventReceiver, and core::AcceptEventReceiver.
Referenced by checkTimeout().
triggered()
void core::EventReceiver::triggered (const utils::Timeval & currentTime)
Definition at line 119 of file EventReceiver.cpp.
{
         lastTriggered = currentTime;
     }
References lastTriggered.
Referenced by dispatch(), and setTimeout().
Member Data Documentation
descriptorEventDispatcher
DescriptorEventDispatcher& core::EventReceiver::descriptorEventDispatcher private
Definition at line 102 of file EventReceiver.h.
Referenced by disable(), enable(), resume(), and suspend().
enabled
bool core::EventReceiver::enabled = false private
Definition at line 106 of file EventReceiver.h.
Referenced by disable(), enable(), and isEnabled().
eventCounter
int core::EventReceiver::eventCounter = 0 private
Definition at line 113 of file EventReceiver.h.
Referenced by dispatch().
initialTimeout
const utils::Timeval core::EventReceiver::initialTimeout private
Definition at line 111 of file EventReceiver.h.
Referenced by setTimeout().
lastTriggered
utils::Timeval core::EventReceiver::lastTriggered private
Definition at line 109 of file EventReceiver.h.
Referenced by checkTimeout(), enable(), getTimeout(), resume(), and triggered().
maxInactivity
utils::Timeval core::EventReceiver::maxInactivity private
Definition at line 110 of file EventReceiver.h.
Referenced by checkTimeout(), getTimeout(), and setTimeout().
registeredFd
int core::EventReceiver::registeredFd = -1 private
Definition at line 104 of file EventReceiver.h.
Referenced by enable(), and getRegisteredFd().
suspended
bool core::EventReceiver::suspended = false private
Definition at line 107 of file EventReceiver.h.
Referenced by isSuspended(), resume(), and suspend().
The documentation for this class was generated from the following files:
core/EventReceiver.h
core/EventReceiver.cpp