snode.c: core::socket::Socket Class Reference
core::socket::Socket Class Reference
#include <Socket.h>
Public Types
enum Flags { NONE = 0 , NONBLOCK = SOCK_NONBLOCK , CLOEXIT = SOCK_CLOEXEC }
enum SHUT { WR = SHUT_WR , RD = SHUT_RD , RDWR = SHUT_RDWR }
Public Member Functions
Socket ()
Socket (int fd)
Socket (int domain, int type, int protocol)
Socket & operator= (int fd)
virtual ~Socket ()=default
int open (Flags flags=Flags::NONE)
bool isValid () const
int reuseAddress () const
int reusePort () const
int getSockError () const
int setSockopt (int level, int optname, const void *optval, socklen_t optlen) const
int getSockopt (int level, int optname, void *optval, socklen_t *optlen) const
void shutdown (SHUT how)
Public Member Functions inherited from core::Descriptor
Descriptor ()=default
~Descriptor ()
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
int open (int fd)
void close ()
int getFd () const
void dontClose ()
Protected Member Functions
int create (Flags flags) const
virtual void setSockopt ()
Protected Attributes
int domain {}
int type {}
int protocol {}
Detailed Description
Definition at line 32 of file Socket.h.
Member Enumeration Documentation
Flags
enum core::socket::Socket::Flags
Enumerator
NONE
NONBLOCK
CLOEXIT
Definition at line 42 of file Socket.h.
 { NONE = 0, NONBLOCK = SOCK_NONBLOCK, CLOEXIT = SOCK_CLOEXEC };
SHUT
enum core::socket::Socket::SHUT
Enumerator
WR
RD
RDWR
Definition at line 62 of file Socket.h.
 { WR = SHUT_WR, RD = SHUT_RD, RDWR = SHUT_RDWR };
Constructor & Destructor Documentation
Socket() [1/3]
core::socket::Socket::Socket ()
Definition at line 27 of file Socket.cpp.
                    {
         Descriptor::open(-1);
     }
References core::Descriptor::open().
Socket() [2/3]
core::socket::Socket::Socket (int fd)
Definition at line 31 of file Socket.cpp.
{
         Descriptor::open(fd);
         socklen_t optLen = sizeof(domain);
         getSockopt(SOL_SOCKET, SO_DOMAIN, &domain, &optLen);
         getSockopt(SOL_SOCKET, SO_TYPE, &type, &optLen);
         getSockopt(SOL_SOCKET, SO_PROTOCOL, &protocol, &optLen);
     }
References domain, core::Descriptor::fd, getSockopt(), core::Descriptor::open(), protocol, and type.
Socket() [3/3]
core::socket::Socket::Socket (int domain, int type, int protocol)
Definition at line 40 of file Socket.cpp.
         : domain(domain)
         , type(type)
         , protocol(protocol) {
     }
~Socket()
virtual core::socket::Socket::~Socket () virtual default
Reimplemented in net::un::Socket.
Member Function Documentation
create()
int core::socket::Socket::create (Flags flags) const protected
Definition at line 57 of file Socket.cpp.
{
         return core::system::socket(domain, type | flags, protocol);
     }
References domain, protocol, core::system::socket(), and type.
Referenced by open().
getSockError()
int core::socket::Socket::getSockError () const
Definition at line 88 of file Socket.cpp.
{
         int cErrno = 0;
         socklen_t cErrnoLen = sizeof(cErrno);
         int err = getSockopt(SOL_SOCKET, SO_ERROR, &cErrno, &cErrnoLen);
         return err < 0 ? err : cErrno;
     }
References getSockopt().
getSockopt()
int core::socket::Socket::getSockopt (int level, int optname, void * optval, socklen_t * optlen) const
Definition at line 100 of file Socket.cpp.
{
         return core::system::getsockopt(Socket::getFd(), level, optname, optval, optlen);
     }
References core::Descriptor::getFd(), and core::system::getsockopt().
Referenced by getSockError(), operator=(), and Socket().
isValid()
bool core::socket::Socket::isValid () const
Definition at line 74 of file Socket.cpp.
{
         return getFd() >= 0;
     }
References core::Descriptor::getFd().
open()
int core::socket::Socket::open (Flags flags = Flags::NONE)
Definition at line 61 of file Socket.cpp.
{
         int ret = Descriptor::open(create(flags));
         if (ret >= 0) {
             setSockopt();
         }
         return ret;
     }
References create(), core::Descriptor::open(), and setSockopt().
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent().
operator=()
Socket & core::socket::Socket::operator= (int fd)
Definition at line 46 of file Socket.cpp.
{
         Descriptor::open(fd);
         socklen_t optLen = sizeof(domain);
         getSockopt(SOL_SOCKET, SO_DOMAIN, &domain, &optLen);
         getSockopt(SOL_SOCKET, SO_TYPE, &type, &optLen);
         getSockopt(SOL_SOCKET, SO_PROTOCOL, &protocol, &optLen);
         return *this;
     }
References domain, core::Descriptor::fd, getSockopt(), core::Descriptor::open(), protocol, and type.
reuseAddress()
int core::socket::Socket::reuseAddress () const
Definition at line 78 of file Socket.cpp.
{
         int sockopt = 1;
         return setSockopt(SOL_SOCKET, SO_REUSEADDR, &sockopt, sizeof(sockopt));
     }
References setSockopt().
reusePort()
int core::socket::Socket::reusePort () const
Definition at line 83 of file Socket.cpp.
{
         int sockopt = 1;
         return setSockopt(SOL_SOCKET, SO_REUSEPORT, &sockopt, sizeof(sockopt));
     }
References setSockopt().
setSockopt() [1/2]
void core::socket::Socket::setSockopt () protected virtual
Reimplemented in net::in6::Socket.
Definition at line 71 of file Socket.cpp.
{
     }
Referenced by open(), reuseAddress(), and reusePort().
setSockopt() [2/2]
int core::socket::Socket::setSockopt (int level, int optname, const void * optval, socklen_t optlen) const
Definition at line 96 of file Socket.cpp.
{
         return core::system::setsockopt(Socket::getFd(), level, optname, optval, optlen);
     }
References core::Descriptor::getFd(), and core::system::setsockopt().
shutdown()
void core::socket::Socket::shutdown (SHUT how)
Definition at line 104 of file Socket.cpp.
{
         core::system::shutdown(getFd(), how);
     }
References core::Descriptor::getFd(), and core::system::shutdown().
Referenced by core::socket::stream::SocketWriter< SocketT >::doWriteShutdown(), and core::socket::stream::SocketReader< SocketT >::shutdown().
Member Data Documentation
domain
int core::socket::Socket::domain {} protected
Definition at line 67 of file Socket.h.
Referenced by create(), operator=(), and Socket().
protocol
int core::socket::Socket::protocol {} protected
Definition at line 69 of file Socket.h.
Referenced by create(), operator=(), and Socket().
type
int core::socket::Socket::type {} protected
Definition at line 68 of file Socket.h.
Referenced by create(), operator=(), and Socket().
The documentation for this class was generated from the following files:
core/socket/Socket.h
core/socket/Socket.cpp