snode.c: net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT > Class Template Reference
net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT > Class Template Reference
#include <SocketClient.h>
Public Types
using SocketAddress = typename net::socket::stream::legacy::SocketClient< l2cap::Socket, SocketContextFactoryT >::SocketAddress
Public Types inherited from net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >
using SocketContextFactory = SocketContextFactoryT
using SocketConnector = SocketConnectorT
using SocketConnection = typename SocketConnector::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Member Functions
void connect (const std::string &address, uint16_t psm, const std::function< void(int)> &onError)
void connect (const std::string &address, uint16_t psm, const std::string &bindAddress, const std::function< void(int)> &onError)
void connect (const std::string &address, uint16_t psm, const std::string &bindAddress, uint16_t bindPsm, const std::function< void(int)> &onError)
Public Member Functions inherited from net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >
SocketClient (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketClient ()=default
void connect (const SocketAddress &remoteAddress, const SocketAddress &bindAddress, const std::function< void(int)> &onError) const
void connect (const SocketAddress &remoteAddress, const std::function< void(int)> &onError) const
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Detailed Description
template<typename SocketContextFactoryT>
class net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >
Definition at line 32 of file SocketClient.h.
Member Typedef Documentation
SocketAddress
template<typename SocketContextFactoryT > using net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >::SocketAddress = typename net::socket::stream::legacy::SocketClient<l2cap::Socket, SocketContextFactoryT>::SocketAddress
Definition at line 36 of file SocketClient.h.
Member Function Documentation
connect() [1/3]
template<typename SocketContextFactoryT > void net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >::connect (const std::string & address, uint16_t psm, const std::function< void(int)> & onError) inline
Definition at line 40 of file SocketClient.h.
{
             connect(SocketAddress(address, psm), onError);
         }
Referenced by net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >::connect().
connect() [2/3]
template<typename SocketContextFactoryT > void net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >::connect (const std::string & address, uint16_t psm, const std::string & bindAddress, const std::function< void(int)> & onError) inline
Definition at line 44 of file SocketClient.h.
{
             connect(SocketAddress(address, psm), SocketAddress(bindAddress), onError);
         }
References net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >::connect().
connect() [3/3]
template<typename SocketContextFactoryT > void net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >::connect (const std::string & address, uint16_t psm, const std::string & bindAddress, uint16_t bindPsm, const std::function< void(int)> & onError) inline
Definition at line 48 of file SocketClient.h.
{
             connect(SocketAddress(address, psm), SocketAddress(bindAddress, bindPsm), onError);
         }
References net::socket::bluetooth::l2cap::SocketClient< SocketContextFactoryT >::connect().
The documentation for this class was generated from the following file:
net/socket/bluetooth/l2cap/SocketClient.h