snode.c: core::socket::stream::SocketReader< SocketT > Class Template Reference
core::socket::stream::SocketReader< SocketT > Class Template Reference abstract
#include <SocketReader.h>
Public Types
using Socket = SocketT
Protected Member Functions
SocketReader (const std::function< void(int)> &onError, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
virtual ~SocketReader ()=default
void setBlockSize (std::size_t readBlockSize)
virtual void doReadShutdown ()
ssize_t readFromPeer (char *junk, std::size_t junkLen)
void doRead ()
bool continueReadImmediately () const override
void shutdown ()
void terminate () override
Protected Member Functions inherited from core::ReadEventReceiver
ReadEventReceiver (const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
~DescriptorEventReceiver ()=default
Private Member Functions
SocketReader ()=delete
virtual ssize_t read (char *junk, std::size_t junkLen)=0
void readEvent () override=0
Private Attributes
std::function< void(int)> onError
std::vector< char > readBuffer
std::size_t blockSize
std::size_t size = 0
std::size_t cursor = 0
bool shutdownTriggered = false
bool terminateInProgress = false
utils::Timeval terminateTimeout
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
int getRegisteredFd ()
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime) override
void triggered (const utils::Timeval &currentTime)
void disabled ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Public Member Functions inherited from core::EventReceiver
EventReceiver ()
virtual ~EventReceiver ()=default
void publish ()
Public Attributes inherited from core::DescriptorEventReceiver
utils::Timeval publisedTime
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
Protected Attributes inherited from core::EventReceiver
Event event
Detailed Description
template<typename SocketT>
class core::socket::stream::SocketReader< SocketT >
Definition at line 39 of file SocketReader.h.
Member Typedef Documentation
Socket
template<typename SocketT > using core::socket::stream::SocketReader< SocketT >::Socket = SocketT
Definition at line 45 of file SocketReader.h.
Constructor & Destructor Documentation
SocketReader() [1/2]
template<typename SocketT > core::socket::stream::SocketReader< SocketT >::SocketReader () private delete
SocketReader() [2/2]
template<typename SocketT > core::socket::stream::SocketReader< SocketT >::SocketReader (const std::function< void(int)> & onError, const utils::Timeval & timeout, std::size_t blockSize, const utils::Timeval & terminateTimeout) inline explicit protected
Definition at line 48 of file SocketReader.h.
             : onError(onError)
             , terminateTimeout(terminateTimeout) {
             setBlockSize(blockSize);
             setTimeout(timeout);
             enable(Socket::fd);
         }
References core::socket::stream::SocketReader< SocketT >::blockSize, core::DescriptorEventReceiver::enable(), core::Descriptor::fd, core::socket::stream::SocketReader< SocketT >::setBlockSize(), and core::DescriptorEventReceiver::setTimeout().
~SocketReader()
template<typename SocketT > virtual core::socket::stream::SocketReader< SocketT >::~SocketReader () protected virtual default
Member Function Documentation
continueReadImmediately()
template<typename SocketT > bool core::socket::stream::SocketReader< SocketT >::continueReadImmediately () const inline override protected virtual
Reimplemented from core::ReadEventReceiver.
Reimplemented in core::socket::stream::tls::SocketReader< SocketT >.
Definition at line 108 of file SocketReader.h.
{
             return size > 0;
         }
References core::socket::stream::SocketReader< SocketT >::size.
Referenced by core::socket::stream::legacy::SocketReader< SocketT >::continueReadImmediately(), and core::socket::stream::tls::SocketReader< SocketT >::continueReadImmediately().
doRead()
template<typename SocketT > void core::socket::stream::SocketReader< SocketT >::doRead () inline protected
Definition at line 88 of file SocketReader.h.
                       {
             errno = 0;
             if (size == 0) {
                 cursor = 0;
                 ssize_t retRead = 0;
                 std::size_t readLen = blockSize - size;
                 retRead = read(readBuffer.data() + size, readLen);
                 if (retRead > 0) {
                     size += static_cast<std::size_t>(retRead);
                 } else if (errno != EINTR && errno != EAGAIN && errno != EWOULDBLOCK) {
                     disable();
                     onError(errno);
                 }
             }
         }
References core::socket::stream::SocketReader< SocketT >::blockSize, core::socket::stream::SocketReader< SocketT >::cursor, core::DescriptorEventReceiver::disable(), core::socket::stream::SocketReader< SocketT >::onError, core::socket::stream::SocketReader< SocketT >::read(), core::socket::stream::SocketReader< SocketT >::readBuffer, and core::socket::stream::SocketReader< SocketT >::size.
Referenced by core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::readEvent().
doReadShutdown()
template<typename SocketT > virtual void core::socket::stream::SocketReader< SocketT >::doReadShutdown () inline protected virtual
Reimplemented in core::socket::stream::tls::SocketConnection< SocketT >.
Definition at line 72 of file SocketReader.h.
{
             Socket::shutdown(Socket::shutdown::RD);
         }
Referenced by core::socket::stream::tls::SocketReader< SocketT >::read(), and core::socket::stream::SocketReader< SocketT >::shutdown().
read()
template<typename SocketT > virtual ssize_t core::socket::stream::SocketReader< SocketT >::read (char * junk, std::size_t junkLen) private pure virtual
Implemented in core::socket::stream::tls::SocketReader< SocketT >, and core::socket::stream::legacy::SocketReader< SocketT >.
Referenced by core::socket::stream::SocketReader< SocketT >::doRead().
readEvent()
template<typename SocketT > void core::socket::stream::SocketReader< SocketT >::readEvent () override private pure virtual
Implements core::ReadEventReceiver.
Implemented in core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
readFromPeer()
template<typename SocketT > ssize_t core::socket::stream::SocketReader< SocketT >::readFromPeer (char * junk, std::size_t junkLen) inline protected
Definition at line 76 of file SocketReader.h.
{
             std::size_t maxReturn = std::min(junkLen, size);
             std::copy(readBuffer.data() + cursor, readBuffer.data() + cursor + maxReturn, junk);
             cursor += maxReturn;
             size -= maxReturn;
             ssize_t ret = static_cast<ssize_t>(maxReturn);
             return ret;
         }
References core::socket::stream::SocketReader< SocketT >::cursor, core::socket::stream::SocketReader< SocketT >::readBuffer, and core::socket::stream::SocketReader< SocketT >::size.
Referenced by core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::readFromPeer().
setBlockSize()
template<typename SocketT > void core::socket::stream::SocketReader< SocketT >::setBlockSize (std::size_t readBlockSize) inline protected
Definition at line 67 of file SocketReader.h.
{
             readBuffer.resize(readBlockSize);
             this->blockSize = readBlockSize;
         }
References core::socket::stream::SocketReader< SocketT >::blockSize, and core::socket::stream::SocketReader< SocketT >::readBuffer.
Referenced by core::socket::stream::SocketReader< SocketT >::SocketReader().
shutdown()
template<typename SocketT > void core::socket::stream::SocketReader< SocketT >::shutdown () inline protected
Definition at line 112 of file SocketReader.h.
{
             if (!shutdownTriggered) {
                 doReadShutdown();
                 shutdownTriggered = true;
             }
         }
References core::socket::stream::SocketReader< SocketT >::doReadShutdown(), and core::socket::stream::SocketReader< SocketT >::shutdownTriggered.
Referenced by core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >::shutdownRead().
terminate()
template<typename SocketT > void core::socket::stream::SocketReader< SocketT >::terminate () inline override protected virtual
Reimplemented from core::DescriptorEventReceiver.
Reimplemented in core::socket::stream::tls::SocketReader< SocketT >.
Definition at line 119 of file SocketReader.h.
{
             if (!terminateInProgress) {
                 setTimeout(terminateTimeout);
                 // shutdown();
                 // do not shutdown our read side because we try to do a full tcp shutdown sequence.
                 // In case we do not receive a TCP-FIN (or equivalent depending on the protocol) the
                 // connection is hard closed after "terminateTimeout".
                 terminateInProgress = true;
             }
         }
References core::DescriptorEventReceiver::setTimeout(), core::socket::stream::SocketReader< SocketT >::terminateInProgress, and core::socket::stream::SocketReader< SocketT >::terminateTimeout.
Referenced by core::socket::stream::legacy::SocketReader< SocketT >::terminate(), and core::socket::stream::tls::SocketReader< SocketT >::terminate().
Member Data Documentation
blockSize
template<typename SocketT > std::size_t core::socket::stream::SocketReader< SocketT >::blockSize private
Definition at line 134 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::doRead(), core::socket::stream::SocketReader< SocketT >::setBlockSize(), and core::socket::stream::SocketReader< SocketT >::SocketReader().
cursor
template<typename SocketT > std::size_t core::socket::stream::SocketReader< SocketT >::cursor = 0 private
Definition at line 137 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::doRead(), and core::socket::stream::SocketReader< SocketT >::readFromPeer().
onError
template<typename SocketT > std::function<void(int)> core::socket::stream::SocketReader< SocketT >::onError private
Definition at line 131 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::doRead().
readBuffer
template<typename SocketT > std::vector<char> core::socket::stream::SocketReader< SocketT >::readBuffer private
Definition at line 133 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::doRead(), core::socket::stream::SocketReader< SocketT >::readFromPeer(), and core::socket::stream::SocketReader< SocketT >::setBlockSize().
shutdownTriggered
template<typename SocketT > bool core::socket::stream::SocketReader< SocketT >::shutdownTriggered = false private
Definition at line 139 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::shutdown().
size
template<typename SocketT > std::size_t core::socket::stream::SocketReader< SocketT >::size = 0 private
Definition at line 136 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::continueReadImmediately(), core::socket::stream::SocketReader< SocketT >::doRead(), and core::socket::stream::SocketReader< SocketT >::readFromPeer().
terminateInProgress
template<typename SocketT > bool core::socket::stream::SocketReader< SocketT >::terminateInProgress = false private
Definition at line 141 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::terminate().
terminateTimeout
template<typename SocketT > utils::Timeval core::socket::stream::SocketReader< SocketT >::terminateTimeout private
Definition at line 143 of file SocketReader.h.
Referenced by core::socket::stream::SocketReader< SocketT >::terminate().
The documentation for this class was generated from the following file:
core/socket/stream/SocketReader.h