snode.c: net::Socket< SocketAddressT > Class Template Reference
net::Socket< SocketAddressT > Class Template Reference
#include <Socket.h>
Public Types
enum SOCK { NONE = 0 , NONBLOCK = SOCK_NONBLOCK , CLOEXIT = SOCK_CLOEXEC }
enum SHUT { WR = SHUT_WR , RD = SHUT_RD , RDWR = SHUT_RDWR }
using SocketAddress = SocketAddressT
Public Member Functions
Socket ()
Socket (int fd)
Socket (int domain, int type, int protocol)
Socket & operator= (int fd)
virtual ~Socket ()=default
int open (SOCK flags=SOCK::NONE)
int bind (const SocketAddress &bindAddress)
bool isValid () const
int reuseAddress ()
int getSockname (SocketAddress &socketAddress)
int getPeername (SocketAddress &socketAddress)
int getSockError ()
int setSockopt (int level, int optname, const void *optval, socklen_t optlen)
int getSockopt (int level, int optname, void *optval, socklen_t *optlen)
ssize_t write_fd (const SocketAddress &destAddress, void *ptr, size_t nbytes, int sendfd)
ssize_t read_fd (void *ptr, size_t nbytes, int *recvfd)
void shutdown (SHUT how)
const SocketAddress & getBindAddress () const
Public Member Functions inherited from core::Descriptor
Descriptor ()=default
~Descriptor ()
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
int open (int fd)
void close ()
int getFd () const
void dontClose ()
Protected Member Functions
int create (SOCK flags)
Protected Attributes
SocketAddress bindAddress {}
Private Attributes
int domain {}
int type {}
int protocol {}
Detailed Description
template<typename SocketAddressT>
class net::Socket< SocketAddressT >
Definition at line 35 of file Socket.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::Socket< SocketAddressT >::SocketAddress = SocketAddressT
Definition at line 37 of file Socket.h.
Member Enumeration Documentation
SHUT
template<typename SocketAddressT > enum net::Socket::SHUT
Enumerator
WR
RD
RDWR
Definition at line 71 of file Socket.h.
 { WR = SHUT_WR, RD = SHUT_RD, RDWR = SHUT_RDWR };
SOCK
template<typename SocketAddressT > enum net::Socket::SOCK
Enumerator
NONE
NONBLOCK
CLOEXIT
Definition at line 47 of file Socket.h.
 { NONE = 0, NONBLOCK = SOCK_NONBLOCK, CLOEXIT = SOCK_CLOEXEC };
Constructor & Destructor Documentation
Socket() [1/3]
template<typename SocketAddress > net::Socket< SocketAddress >::Socket
Definition at line 30 of file Socket.hpp.
{
         Descriptor::open(-1);
     }
References core::system::open().
Socket() [2/3]
template<typename SocketAddress > net::Socket< SocketAddress >::Socket (int fd)
Definition at line 35 of file Socket.hpp.
{
         Descriptor::open(fd);
         socklen_t optLen = sizeof(domain);
         getSockopt(SOL_SOCKET, SO_DOMAIN, &domain, &optLen);
         getSockopt(SOL_SOCKET, SO_TYPE, &type, &optLen);
         getSockopt(SOL_SOCKET, SO_PROTOCOL, &protocol, &optLen);
     }
References core::system::open().
Socket() [3/3]
template<typename SocketAddress > net::Socket< SocketAddress >::Socket (int domain, int type, int protocol)
Definition at line 45 of file Socket.hpp.
         : domain(domain)
         , type(type)
         , protocol(protocol) {
     }
~Socket()
template<typename SocketAddressT > virtual net::Socket< SocketAddressT >::~Socket () virtual default
Reimplemented in net::un::Socket.
Member Function Documentation
bind()
template<typename SocketAddress > int net::Socket< SocketAddress >::bind (const SocketAddress & bindAddress)
Definition at line 74 of file Socket.hpp.
{
         this->bindAddress = bindAddress;
         return core::system::bind(getFd(), bindAddress, bindAddress.getAddrLen());
     }
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent().
create()
template<typename SocketAddressT > int net::Socket< SocketAddressT >::create (SOCK flags) protected
Definition at line 64 of file Socket.hpp.
{
         return core::system::socket(domain, type | flags, protocol);
     }
getBindAddress()
template<typename SocketAddress > const SocketAddress & net::Socket< SocketAddress >::getBindAddress
Definition at line 200 of file Socket.hpp.
{
         return bindAddress;
     }
getPeername()
template<typename SocketAddress > int net::Socket< SocketAddress >::getPeername (SocketAddress & socketAddress)
Definition at line 98 of file Socket.hpp.
{
         socketAddress.getAddrLen() = sizeof(typename SocketAddress::SockAddr);
         return core::system::getpeername(getFd(), socketAddress, &socketAddress.getAddrLen());
     }
References core::system::getpeername().
getSockError()
template<typename SocketAddress > int net::Socket< SocketAddress >::getSockError
Definition at line 104 of file Socket.hpp.
{
         int cErrno = 0;
         socklen_t cErrnoLen = sizeof(cErrno);
         int err = getSockopt(SOL_SOCKET, SO_ERROR, &cErrno, &cErrnoLen);
         return err == 0 ? cErrno : err;
     }
getSockname()
template<typename SocketAddress > int net::Socket< SocketAddress >::getSockname (SocketAddress & socketAddress)
Definition at line 92 of file Socket.hpp.
{
         socketAddress.getAddrLen() = sizeof(typename SocketAddress::SockAddr);
         return core::system::getsockname(getFd(), socketAddress, &socketAddress.getAddrLen());
     }
References core::system::getsockname().
getSockopt()
template<typename SocketAddress > int net::Socket< SocketAddress >::getSockopt (int level, int optname, void * optval, socklen_t * optlen)
Definition at line 118 of file Socket.hpp.
{
         return core::system::getsockopt(Socket::getFd(), level, optname, optval, optlen);
     }
References core::Descriptor::getFd(), and core::system::getsockopt().
isValid()
template<typename SocketAddress > bool net::Socket< SocketAddress >::isValid
Definition at line 81 of file Socket.hpp.
{
         return getFd() >= 0;
     }
open()
template<typename SocketAddress > int net::Socket< SocketAddress >::open (SOCK flags = SOCK::NONE)
Definition at line 69 of file Socket.hpp.
{
         return Descriptor::open(create(flags));
     }
References core::system::open().
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent().
operator=()
template<typename SocketAddress > Socket< SocketAddress > & net::Socket< SocketAddress >::operator= (int fd)
Definition at line 52 of file Socket.hpp.
{
         Descriptor::open(fd);
         socklen_t optLen = sizeof(domain);
         getSockopt(SOL_SOCKET, SO_DOMAIN, &domain, &optLen);
         getSockopt(SOL_SOCKET, SO_TYPE, &type, &optLen);
         getSockopt(SOL_SOCKET, SO_PROTOCOL, &protocol, &optLen);
         return *this;
     }
read_fd()
template<typename SocketAddress > ssize_t net::Socket< SocketAddress >::read_fd (void * ptr, size_t nbytes, int * recvfd)
Definition at line 152 of file Socket.hpp.
{
         union {
             struct cmsghdr cm;
             char control[CMSG_SPACE(sizeof(int))] = {};
         } control_un;
         msghdr msg;
         msg.msg_control = control_un.control;
         msg.msg_controllen = sizeof(control_un.control);
         msg.msg_name = nullptr;
         msg.msg_namelen = 0;
         iovec iov[1];
         msg.msg_iov = iov;
         msg.msg_iovlen = 1;
         msg.msg_iov[0].iov_base = ptr;
         msg.msg_iov[0].iov_len = nbytes;
         ssize_t n = 0;
         if ((n = recvmsg(getFd(), &msg, 0)) > 0) {
             cmsghdr* cmptr;
             if ((cmptr = CMSG_FIRSTHDR(&msg)) != nullptr && cmptr->cmsg_len == CMSG_LEN(sizeof(int))) {
                 if (cmptr->cmsg_level != SOL_SOCKET || cmptr->cmsg_type != SCM_RIGHTS) {
                     errno = EBADE;
                     *recvfd = -1;
                     n = -1;
                 } else {
                     *recvfd = *reinterpret_cast<int*>(CMSG_DATA(cmptr));
                 }
             } else {
                 errno = ENOMSG;
                 *recvfd = -1;
                 n = -1;
             }
         }
         return n;
     }
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent().
reuseAddress()
template<typename SocketAddress > int net::Socket< SocketAddress >::reuseAddress
Definition at line 86 of file Socket.hpp.
{
         int sockopt = 1;
         return setSockopt(SOL_SOCKET, SO_REUSEADDR, &sockopt, sizeof(sockopt));
     }
setSockopt()
template<typename SocketAddress > int net::Socket< SocketAddress >::setSockopt (int level, int optname, const void * optval, socklen_t optlen)
Definition at line 113 of file Socket.hpp.
{
         return core::system::setsockopt(Socket::getFd(), level, optname, optval, optlen);
     }
References core::Descriptor::getFd(), and core::system::setsockopt().
shutdown()
template<typename SocketAddress > void net::Socket< SocketAddress >::shutdown (SHUT how)
Definition at line 195 of file Socket.hpp.
{
         core::system::shutdown(getFd(), how);
     }
References core::system::shutdown().
write_fd()
template<typename SocketAddress > ssize_t net::Socket< SocketAddress >::write_fd (const SocketAddress & destAddress, void * ptr, size_t nbytes, int sendfd)
Definition at line 123 of file Socket.hpp.
{
         union {
             struct cmsghdr cm;
             char control[CMSG_SPACE(sizeof(int))] = {};
         } control_un;
         msghdr msg;
         msg.msg_name = const_cast<sockaddr*>(&destAddress.getSockAddr());
         msg.msg_namelen = destAddress.getAddrLen();
         msg.msg_control = control_un.control;
         msg.msg_controllen = sizeof(control_un.control);
         iovec iov[1];
         msg.msg_iov = iov;
         msg.msg_iovlen = 1;
         msg.msg_iov[0].iov_base = ptr;
         msg.msg_iov[0].iov_len = nbytes;
         cmsghdr* cmptr = CMSG_FIRSTHDR(&msg);
         cmptr->cmsg_level = SOL_SOCKET;
         cmptr->cmsg_type = SCM_RIGHTS;
         *reinterpret_cast<int*>(CMSG_DATA(cmptr)) = sendfd;
         cmptr->cmsg_len = CMSG_LEN(sizeof(int));
         return sendmsg(getFd(), &msg, 0);
     }
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent().
Member Data Documentation
bindAddress
template<typename SocketAddressT > SocketAddress net::Socket< SocketAddressT >::bindAddress {} protected
Definition at line 78 of file Socket.h.
domain
template<typename SocketAddressT > int net::Socket< SocketAddressT >::domain {} private
Definition at line 81 of file Socket.h.
protocol
template<typename SocketAddressT > int net::Socket< SocketAddressT >::protocol {} private
Definition at line 83 of file Socket.h.
type
template<typename SocketAddressT > int net::Socket< SocketAddressT >::type {} private
Definition at line 82 of file Socket.h.
The documentation for this class was generated from the following files:
net/Socket.h
net/Socket.hpp