snode.c: core::file::FileReader Class Reference
core::file::FileReader Class Reference
#include <FileReader.h>
Public Member Functions
void event (const utils::Timeval &currentTime) override
void suspend ()
void resume ()
bool isSuspended ()
Public Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish ()
void unPublish ()
const std::string & getName ()
Public Member Functions inherited from core::pipe::Source
Source ()
virtual ~Source ()
void disconnect ()
void connect (Sink &sink)
void disconnect (Sink &sink)
ssize_t send (const char *junk, std::size_t junkLen)
void eof ()
void error (int errnum)
Static Public Member Functions
static FileReader * connect (const std::string &path, core::pipe::Sink &writeStream, const std::function< void(int err)> &onError)
Protected Member Functions
FileReader (int fd, core::pipe::Sink &writeStream, const std::string &name)
Protected Member Functions inherited from core::Descriptor
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
void attachFd (int fd)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Private Attributes
bool suspended = false
Additional Inherited Members
Protected Types inherited from core::Descriptor
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Protected Attributes inherited from core::EventReceiver
Event _event
Protected Attributes inherited from core::pipe::Source
Sink * sink
Protected Attributes inherited from core::Descriptor
enum core::Descriptor::FLAGS none
Detailed Description
Definition at line 43 of file FileReader.h.
Constructor & Destructor Documentation
FileReader()
core::file::FileReader::FileReader (int fd, core::pipe::Sink & writeStream, const std::string & name) protected
Definition at line 34 of file FileReader.cpp.
         : Descriptor(fd)
         , EventReceiver(name) {
         Source::connect(sink);
         publish();
     }
References core::system::connect(), core::EventReceiver::publish(), and core::pipe::Source::sink.
Referenced by connect().
Member Function Documentation
connect()
FileReader * core::file::FileReader::connect (const std::string & path, core::pipe::Sink & writeStream, const std::function< void(int err)> & onError) static
Definition at line 42 of file FileReader.cpp.
{
         errno = 0;
         FileReader* fileReader = nullptr;
         int fd = core::system::open(path.c_str(), O_RDONLY);
         if (fd >= 0) {
             fileReader = new FileReader(fd, writeStream, "FileReader: " + path);
         }
         onError(errno);
         return fileReader;
     }
References core::Descriptor::fd, FileReader(), and core::system::open().
Referenced by express::Response::sendFile().
event()
void core::file::FileReader::event (const utils::Timeval & currentTime) override virtual
Implements core::EventReceiver.
Definition at line 58 of file FileReader.cpp.
{
         if (!suspended) {
             // NOLINTNEXTLINE(cppcoreguidelines-avoid-c-arrays, hicpp-avoid-c-arrays, modernize-avoid-c-arrays)
             static char junk[MFREADSIZE];
             ssize_t ret = core::system::read(getFd(), junk, MFREADSIZE);
             if (ret > 0) {
                 if (send(junk, static_cast<std::size_t>(ret)) >= 0) {
                     publish();
                 } else {
                     delete this;
                 }
             } else {
                 if (ret == 0) {
                     this->eof();
                 } else {
                     this->error(errno);
                 }
                 delete this;
             }
         }
     }
References core::pipe::Source::eof(), core::pipe::Source::error(), core::Descriptor::getFd(), MFREADSIZE, core::EventReceiver::publish(), core::system::read(), core::pipe::Source::send(), and suspended.
isSuspended()
bool core::file::FileReader::isSuspended ()
Definition at line 91 of file FileReader.cpp.
{
         return suspended;
     }
References suspended.
resume()
void core::file::FileReader::resume ()
Definition at line 86 of file FileReader.cpp.
{
         suspended = false;
         publish();
     }
References core::EventReceiver::publish(), and suspended.
suspend()
void core::file::FileReader::suspend ()
Definition at line 82 of file FileReader.cpp.
{
         suspended = true;
     }
References suspended.
Member Data Documentation
suspended
bool core::file::FileReader::suspended = false private
Definition at line 61 of file FileReader.h.
Referenced by event(), isSuspended(), resume(), and suspend().
The documentation for this class was generated from the following files:
core/file/FileReader.h
core/file/FileReader.cpp