snode.c: net::rf::ConfigRemote Class Reference
net::rf::ConfigRemote Class Reference
#include <ConfigRemote.h>
Public Member Functions
ConfigRemote (CLI::App *baseSc)
Public Member Functions inherited from net::ConfigRemote< SocketAddress >
const SocketAddress & getRemoteAddress () const
void setRemoteAddress (const SocketAddress &remoteAddress) const
Protected Member Functions
void required () const
Protected Member Functions inherited from net::ConfigRemote< SocketAddress >
ConfigRemote ()=default
virtual ~ConfigRemote ()=default
Protected Attributes
CLI::App * connectSc = nullptr
CLI::Option * connectHostOpt = nullptr
CLI::Option * connectChannelOpt = nullptr
Private Member Functions
SocketAddress getAddress () const override
Private Attributes
std::string connectHost = ""
uint8_t connectChannel = 0
Additional Inherited Members
Protected Types inherited from net::ConfigRemote< SocketAddress >
using SocketAddress = SocketAddress
Detailed Description
Definition at line 39 of file ConfigRemote.h.
Constructor & Destructor Documentation
ConfigRemote()
net::rf::ConfigRemote::ConfigRemote (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigRemote.cpp.
{
         connectSc = baseSc->add_subcommand("remote");
         connectSc->description("Connect options");
         connectSc->configurable();
         connectSc->required();
         connectHostOpt = connectSc->add_option("-a,--host", connectHost, "Bluetooth address");
         connectHostOpt->type_name("[bluetooth address]");
         connectHostOpt->default_val("00:00:00:00:00:00");
         connectHostOpt->take_first();
         connectHostOpt->configurable();
         connectChannelOpt = connectSc->add_option("-c,--channel", connectChannel, "Channel number");
         connectChannelOpt->type_name("[uint8_t]");
         connectChannelOpt->default_val(0);
         connectChannelOpt->take_first();
         connectChannelOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), connectChannel, connectChannelOpt, connectHost, connectHostOpt, connectSc, CLI::Option::default_val(), CLI::App::description(), CLI::App::required(), CLI::OptionBase< CRTP >::take_first(), and CLI::Option::type_name().
Member Function Documentation
getAddress()
SocketAddress net::rf::ConfigRemote::getAddress () const override private virtual
Implements net::ConfigRemote< SocketAddress >.
Definition at line 48 of file ConfigRemote.cpp.
{
         return SocketAddress(connectHost, connectChannel);
     }
References connectChannel, and connectHost.
required()
void net::rf::ConfigRemote::required () const protected
Definition at line 52 of file ConfigRemote.cpp.
{
         connectSc->required();
         connectHostOpt->required();
         connectChannelOpt->required();
     }
References connectChannelOpt, connectHostOpt, connectSc, CLI::App::required(), and CLI::OptionBase< CRTP >::required().
Referenced by net::rf::stream::ClientConfig::ClientConfig().
Member Data Documentation
connectChannel
uint8_t net::rf::ConfigRemote::connectChannel = 0 private
Definition at line 54 of file ConfigRemote.h.
Referenced by ConfigRemote(), and getAddress().
connectChannelOpt
CLI::Option* net::rf::ConfigRemote::connectChannelOpt = nullptr protected
Definition at line 48 of file ConfigRemote.h.
Referenced by ConfigRemote(), and required().
connectHost
std::string net::rf::ConfigRemote::connectHost = "" private
Definition at line 53 of file ConfigRemote.h.
Referenced by ConfigRemote(), and getAddress().
connectHostOpt
CLI::Option* net::rf::ConfigRemote::connectHostOpt = nullptr protected
Definition at line 47 of file ConfigRemote.h.
Referenced by ConfigRemote(), and required().
connectSc
CLI::App* net::rf::ConfigRemote::connectSc = nullptr protected
Definition at line 46 of file ConfigRemote.h.
Referenced by ConfigRemote(), and required().
The documentation for this class was generated from the following files:
net/rf/ConfigRemote.h
net/rf/ConfigRemote.cpp