snode.c: database::mariadb::commands::async::MariaDBConnectCommand Class Reference
database::mariadb::commands::async::MariaDBConnectCommand Class Reference
#include <MariaDBConnectCommand.h>
Public Member Functions
MariaDBConnectCommand (const database::mariadb::MariaDBConnectionDetails &details, const std::function< void(void)> &onConnecting, const std::function< void(void)> &onConnect, const std::function< void(const std::string &, unsigned int)> &onError)
int commandStart () override
int commandContinue (int status) override
bool commandCompleted () override
void commandError (const std::string &errorString, unsigned int errorNumber) override
std::string commandInfo () override
Public Member Functions inherited from database::mariadb::MariaDBCommandASync
MariaDBCommand (const std::string &name, const std::function< void(const std::string &, unsigned int)> &onError)
Public Member Functions inherited from database::mariadb::MariaDBCommand
MariaDBCommand (const std::string &name, const std::function< void(const std::string &, unsigned int)> &onError)
virtual ~MariaDBCommand ()=default
const std::string & commandName ()
int commandStart (MYSQL *mysql, const utils::Timeval &currentTime)
void setMariaDBConnection (MariaDBConnection *mariaDBConnection)
Protected Attributes
MYSQL * ret = nullptr
const database::mariadb::MariaDBConnectionDetails details
const std::function< void(void)> onConnecting
const std::function< void(void)> onConnect
Protected Attributes inherited from database::mariadb::MariaDBCommand
std::string name
MariaDBConnection * mariaDBConnection = nullptr
MYSQL * mysql = nullptr
utils::Timeval startTime = 0
Additional Inherited Members
Public Attributes inherited from database::mariadb::MariaDBCommand
const std::function< void(const std::string &, unsigned int)> onError
Detailed Description
Definition at line 38 of file MariaDBConnectCommand.h.
Constructor & Destructor Documentation
MariaDBConnectCommand()
database::mariadb::commands::async::MariaDBConnectCommand::MariaDBConnectCommand (const database::mariadb::MariaDBConnectionDetails & details, const std::function< void(void)> & onConnecting, const std::function< void(void)> & onConnect, const std::function< void(const std::string &, unsigned int)> & onError)
Definition at line 30 of file MariaDBConnectCommand.cpp.
         : MariaDBCommandASync("Connect", onError)
         , details(details)
         , onConnecting(onConnecting)
         , onConnect(onConnect) {
     }
Member Function Documentation
commandCompleted()
bool database::mariadb::commands::async::MariaDBConnectCommand::commandCompleted () override virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 60 of file MariaDBConnectCommand.cpp.
{
         onConnect();
         return true;
     }
References onConnect.
commandContinue()
int database::mariadb::commands::async::MariaDBConnectCommand::commandContinue (int status) override virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 56 of file MariaDBConnectCommand.cpp.
{
         return mysql_real_connect_cont(&ret, mysql, status);
     }
References database::mariadb::MariaDBCommand::mysql, and ret.
commandError()
void database::mariadb::commands::async::MariaDBConnectCommand::commandError (const std::string & errorString, unsigned int errorNumber) override virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 66 of file MariaDBConnectCommand.cpp.
{
         onError(errorString, errorNumber);
     }
References database::mariadb::MariaDBCommand::onError.
commandInfo()
std::string database::mariadb::commands::async::MariaDBConnectCommand::commandInfo () override virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 70 of file MariaDBConnectCommand.cpp.
{
         return commandName() + ": " + details.hostname + ":" + std::to_string(details.port) + " | " + details.socket;
     }
References database::mariadb::MariaDBCommand::commandName(), details, database::mariadb::MariaDBConnectionDetails::hostname, database::mariadb::MariaDBConnectionDetails::port, database::mariadb::MariaDBConnectionDetails::socket, and CLI::detail::to_string().
commandStart()
int database::mariadb::commands::async::MariaDBConnectCommand::commandStart () override virtual
Implements database::mariadb::MariaDBCommand.
Definition at line 40 of file MariaDBConnectCommand.cpp.
{
         int status = mysql_real_connect_start(&ret,
                                               mysql,
                                               details.hostname.c_str(),
                                               details.username.c_str(),
                                               details.password.c_str(),
                                               details.database.c_str(),
                                               details.port,
                                               details.socket.c_str(),
                                               details.flags);
         onConnecting();
         return status;
     }
References database::mariadb::MariaDBConnectionDetails::database, details, database::mariadb::MariaDBConnectionDetails::flags, database::mariadb::MariaDBConnectionDetails::hostname, database::mariadb::MariaDBCommand::mysql, onConnecting, database::mariadb::MariaDBConnectionDetails::password, database::mariadb::MariaDBConnectionDetails::port, ret, database::mariadb::MariaDBConnectionDetails::socket, and database::mariadb::MariaDBConnectionDetails::username.
Member Data Documentation
details
const database::mariadb::MariaDBConnectionDetails database::mariadb::commands::async::MariaDBConnectCommand::details protected
Definition at line 53 of file MariaDBConnectCommand.h.
Referenced by commandInfo(), and commandStart().
onConnect
const std::function<void(void)> database::mariadb::commands::async::MariaDBConnectCommand::onConnect protected
Definition at line 56 of file MariaDBConnectCommand.h.
Referenced by commandCompleted().
onConnecting
const std::function<void(void)> database::mariadb::commands::async::MariaDBConnectCommand::onConnecting protected
Definition at line 55 of file MariaDBConnectCommand.h.
Referenced by commandStart().
ret
MYSQL* database::mariadb::commands::async::MariaDBConnectCommand::ret = nullptr protected
Definition at line 52 of file MariaDBConnectCommand.h.
Referenced by commandContinue(), and commandStart().
The documentation for this class was generated from the following files:
database/mariadb/commands/async/MariaDBConnectCommand.h
database/mariadb/commands/async/MariaDBConnectCommand.cpp