snode.c: net::socket::stream::SocketAcceptor< SocketConnectionT > Class Template Reference
net::socket::stream::SocketAcceptor< SocketConnectionT > Class Template Reference
#include <SocketAcceptor.h>
Public Types
using SocketConnection = SocketConnectionT
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
SocketAcceptor (const std::shared_ptr< SocketContextFactory > &socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
virtual ~SocketAcceptor ()=default
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(int)> &onError)
Public Member Functions inherited from net::EventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Protected Member Functions
void destruct ()
Protected Member Functions inherited from net::AcceptEventReceiver
AcceptEventReceiver (long timeout=LONG_MAX)
virtual bool continueAcceptImmediately ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (EventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Attributes
std::map< std::string, std::any > options
std::function< void(const SocketAddress &, const SocketAddress &)> onConnect
std::function< void(SocketConnection *)> onDestruct
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Private Member Functions
SocketAcceptor ()=delete
SocketAcceptor (const SocketAcceptor &)=delete
SocketAcceptor & operator= (const SocketAcceptor &)=delete
void reuseAddress (const std::function< void(int)> &onError)
void acceptEvent () override
void end ()
void unobserved () override
Private Attributes
std::shared_ptr< SocketContextFactory > socketContextFactory = nullptr
Detailed Description
template<typename SocketConnectionT>
class net::socket::stream::SocketAcceptor< SocketConnectionT >
Definition at line 43 of file SocketAcceptor.h.
Member Typedef Documentation
Socket
template<typename SocketConnectionT > using net::socket::stream::SocketAcceptor< SocketConnectionT >::Socket = typename SocketConnection::Socket
Definition at line 52 of file SocketAcceptor.h.
SocketAddress
template<typename SocketConnectionT > using net::socket::stream::SocketAcceptor< SocketConnectionT >::SocketAddress = typename Socket::SocketAddress
Definition at line 53 of file SocketAcceptor.h.
SocketConnection
template<typename SocketConnectionT > using net::socket::stream::SocketAcceptor< SocketConnectionT >::SocketConnection = SocketConnectionT
Definition at line 51 of file SocketAcceptor.h.
Constructor & Destructor Documentation
SocketAcceptor() [1/3]
template<typename SocketConnectionT > net::socket::stream::SocketAcceptor< SocketConnectionT >::SocketAcceptor () private delete
SocketAcceptor() [2/3]
template<typename SocketConnectionT > net::socket::stream::SocketAcceptor< SocketConnectionT >::SocketAcceptor (const SocketAcceptor< SocketConnectionT > &) private delete
SocketAcceptor() [3/3]
template<typename SocketConnectionT > net::socket::stream::SocketAcceptor< SocketConnectionT >::SocketAcceptor (const std::shared_ptr< SocketContextFactory > & socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options) inline
Sequence diagramm of res.upgrade(req).
Definition at line 60 of file SocketAcceptor.h.
             : socketContextFactory(socketContextFactory)
             , options(options)
             , onConnect(onConnect)
             , onConnected(onConnected)
             , onDisconnect(onDisconnect) {
         }
~SocketAcceptor()
template<typename SocketConnectionT > virtual net::socket::stream::SocketAcceptor< SocketConnectionT >::~SocketAcceptor () virtual default
Reimplemented in net::socket::stream::tls::SocketAcceptor< SocketT >.
Member Function Documentation
acceptEvent()
template<typename SocketConnectionT > void net::socket::stream::SocketAcceptor< SocketConnectionT >::acceptEvent () inline override private virtual
Implements net::AcceptEventReceiver.
Definition at line 122 of file SocketAcceptor.h.
{
             typename SocketAddress::SockAddr remoteAddress{};
             socklen_t remoteAddressLength = sizeof(remoteAddress);
             int fd = -1;
             fd = net::system::accept4(
                 SocketAcceptor::getFd(), reinterpret_cast<struct sockaddr*>(&remoteAddress), &remoteAddressLength, SOCK_NONBLOCK);
             if (fd >= 0) {
                 typename SocketAddress::SockAddr localAddress{};
                 socklen_t addressLength = sizeof(localAddress);
                 if (net::system::getsockname(fd, reinterpret_cast<sockaddr*>(&localAddress), &addressLength) == 0) {
                     SocketConnection* socketConnection = new SocketConnection(
                         fd, socketContextFactory, SocketAddress(localAddress), SocketAddress(remoteAddress), onConnect, onDisconnect);
                     onConnected(socketConnection);
                 } else {
                     PLOG(ERROR) << "getsockname";
                     net::system::shutdown(fd, SHUT_RDWR);
                     net::system::close(fd);
                 }
             } else if (errno != EINTR) {
                 PLOG(ERROR) << "accept";
             }
         }
References net::system::accept4(), net::system::close(), net::EventReceiver::fd, net::system::getsockname(), net::socket::stream::SocketAcceptor< SocketConnectionT >::onConnect, net::socket::stream::SocketAcceptor< SocketConnectionT >::onConnected, net::socket::stream::SocketAcceptor< SocketConnectionT >::onDisconnect, net::system::shutdown(), and net::socket::stream::SocketAcceptor< SocketConnectionT >::socketContextFactory.
destruct()
template<typename SocketConnectionT > void net::socket::stream::SocketAcceptor< SocketConnectionT >::destruct () inline protected
Definition at line 159 of file SocketAcceptor.h.
{
             delete this;
         }
Referenced by net::socket::stream::SocketAcceptor< SocketConnectionT >::listen(), net::socket::stream::tls::SocketAcceptor< SocketT >::listen(), and net::socket::stream::SocketAcceptor< SocketConnectionT >::unobserved().
end()
template<typename SocketConnectionT > void net::socket::stream::SocketAcceptor< SocketConnectionT >::end () inline private
Definition at line 150 of file SocketAcceptor.h.
                    {
             AcceptEventReceiver::disable(SocketAcceptor::getFd());
         }
References net::EventReceiver::disable().
listen()
template<typename SocketConnectionT > void net::socket::stream::SocketAcceptor< SocketConnectionT >::listen (const SocketAddress & bindAddress, int backlog, const std::function< void(int)> & onError) inline
Definition at line 74 of file SocketAcceptor.h.
{
             Socket::open([this, &bindAddress, &backlog, &onError](int errnum) -> void {
                 if (errnum > 0) {
                     onError(errnum);
                     destruct();
                 } else {
 #if !defined(NDEBUG)
                     reuseAddress([this, &bindAddress, &backlog, &onError](int errnum) -> void {
                         if (errnum != 0) {
                             onError(errnum);
                             destruct();
                         } else {
 #endif
                             Socket::bind(bindAddress, [this, &backlog, &onError](int errnum) -> void {
                                 if (errnum > 0) {
                                     onError(errnum);
                                     destruct();
                                 } else {
                                     int ret = net::system::listen(SocketAcceptor::getFd(), backlog);
                                     if (ret == 0) {
                                         AcceptEventReceiver::enable(SocketAcceptor::getFd());
                                         onError(0);
                                     } else {
                                         onError(errno);
                                         destruct();
                                     }
                                 }
                             });
 #if !defined(NDEBUG)
                         }
                     });
 #endif
                 }
             });
         }
References net::socket::Socket< SocketAddressT >::bind(), net::socket::stream::SocketAcceptor< SocketConnectionT >::destruct(), net::EventReceiver::enable(), net::system::listen(), net::socket::Socket< SocketAddressT >::open(), and net::socket::stream::SocketAcceptor< SocketConnectionT >::reuseAddress().
Referenced by net::socket::stream::tls::SocketAcceptor< SocketT >::listen().
operator=()
template<typename SocketConnectionT > SocketAcceptor& net::socket::stream::SocketAcceptor< SocketConnectionT >::operator= (const SocketAcceptor< SocketConnectionT > &) private delete
reuseAddress()
template<typename SocketConnectionT > void net::socket::stream::SocketAcceptor< SocketConnectionT >::reuseAddress (const std::function< void(int)> & onError) inline private
Definition at line 112 of file SocketAcceptor.h.
{
             int sockopt = 1;
             if (net::system::setsockopt(SocketAcceptor::getFd(), SOL_SOCKET, SO_REUSEADDR, &sockopt, sizeof(sockopt)) < 0) {
                 onError(errno);
             } else {
                 onError(0);
             }
         }
References net::system::setsockopt().
Referenced by net::socket::stream::SocketAcceptor< SocketConnectionT >::listen().
unobserved()
template<typename SocketConnectionT > void net::socket::stream::SocketAcceptor< SocketConnectionT >::unobserved () inline override private virtual
Implements net::EventReceiver.
Definition at line 154 of file SocketAcceptor.h.
{
             destruct();
         }
References net::socket::stream::SocketAcceptor< SocketConnectionT >::destruct().
Member Data Documentation
onConnect
template<typename SocketConnectionT > std::function<void(const SocketAddress&, const SocketAddress&)> net::socket::stream::SocketAcceptor< SocketConnectionT >::onConnect protected
Definition at line 169 of file SocketAcceptor.h.
Referenced by net::socket::stream::SocketAcceptor< SocketConnectionT >::acceptEvent().
onConnected
template<typename SocketConnectionT > std::function<void(SocketConnection*)> net::socket::stream::SocketAcceptor< SocketConnectionT >::onConnected protected
Definition at line 171 of file SocketAcceptor.h.
Referenced by net::socket::stream::SocketAcceptor< SocketConnectionT >::acceptEvent().
onDestruct
template<typename SocketConnectionT > std::function<void(SocketConnection*)> net::socket::stream::SocketAcceptor< SocketConnectionT >::onDestruct protected
Definition at line 170 of file SocketAcceptor.h.
onDisconnect
template<typename SocketConnectionT > std::function<void(SocketConnection*)> net::socket::stream::SocketAcceptor< SocketConnectionT >::onDisconnect protected
Definition at line 172 of file SocketAcceptor.h.
Referenced by net::socket::stream::SocketAcceptor< SocketConnectionT >::acceptEvent().
options
template<typename SocketConnectionT > std::map<std::string, std::any> net::socket::stream::SocketAcceptor< SocketConnectionT >::options protected
Definition at line 167 of file SocketAcceptor.h.
socketContextFactory
template<typename SocketConnectionT > std::shared_ptr<SocketContextFactory> net::socket::stream::SocketAcceptor< SocketConnectionT >::socketContextFactory = nullptr private
Definition at line 164 of file SocketAcceptor.h.
Referenced by net::socket::stream::SocketAcceptor< SocketConnectionT >::acceptEvent().
The documentation for this class was generated from the following file:
net/socket/stream/SocketAcceptor.h