snode.c: web::http::legacy::rf::Server< Request, Response > Class Template Reference
web::http::legacy::rf::Server< Request, Response > Class Template Reference
#include <Server.h>
Public Member Functions
void listen (uint8_t channel, const std::function< void(const net::rf::stream::Socket &, int)> &onError)
void listen (const std::string &address, const std::function< void(const net::rf::stream::Socket &, int)> &onError)
void listen (const std::string &address, uint8_t channel, const std::function< void(const net::rf::stream::Socket &, int)> &onError)
Public Member Functions inherited from web::http::server::Server< net::rf::stream::legacy::SocketServer, web::http::server::Request, web::http::server::Response >
Server (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &, Response &)> &onRequestReady, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void listen (const SocketAddress &socketAddress, const std::function< void(int)> &onError)
Public Member Functions inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketServer ()=default
void listen (const std::function< void(const Socket &socket, int)> &onError) const override
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(const Socket &socket, int)> &onError) const override
void onConnect (const std::function< void(SocketConnection *)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
ServerConfig & getServerConfig ()
Protected Types
using SocketServer = net::rf::stream::legacy::SocketServer< web::http::server::SocketContextFactory< Request, Response > >
Protected Types inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
using ServerSocket = ServerSocketT
using ServerConfig = ServerConfigT
using SocketAcceptor = core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >
using SocketContextFactory = SocketContextFactoryT
Additional Inherited Members
Public Types inherited from web::http::server::Server< net::rf::stream::legacy::SocketServer, web::http::server::Request, web::http::server::Response >
using Request = web::http::server::Request
using Response = web::http::server::Response
using SocketConnection = typename Super::SocketConnection
using SocketAddress = typename SocketConnection::SocketAddress
Public Types inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
using Socket = typename ServerSocket::Socket
using SocketAddress = typename Socket::SocketAddress
using SocketConnection = typename SocketAcceptor::SocketConnection
Protected Attributes inherited from core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
ServerConfig serverConfig
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response>
class web::http::legacy::rf::Server< Request, Response >
Definition at line 32 of file Server.h.
Member Typedef Documentation
SocketServer
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> using web::http::legacy::rf::Server< Request, Response >::SocketServer = net::rf::stream::legacy::SocketServer<web::http::server::SocketContextFactory<Request, Response> > protected
Definition at line 36 of file Server.h.
Member Function Documentation
listen() [1/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::legacy::rf::Server< Request, Response >::listen (const std::string & address, const std::function< void(const net::rf::stream::Socket &, int)> & onError) inline
Definition at line 45 of file Server.h.
{
             SocketServer::listen(address, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
listen() [2/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::legacy::rf::Server< Request, Response >::listen (const std::string & address, uint8_t channel, const std::function< void(const net::rf::stream::Socket &, int)> & onError) inline
Definition at line 49 of file Server.h.
{
             SocketServer::listen(address, channel, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
listen() [3/3]
template<typename Request = web::http::server::Request, typename Response = web::http::server::Response> void web::http::legacy::rf::Server< Request, Response >::listen (uint8_t channel, const std::function< void(const net::rf::stream::Socket &, int)> & onError) inline
Definition at line 41 of file Server.h.
{
             SocketServer::listen(channel, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
The documentation for this class was generated from the following file:
web/http/legacy/rf/Server.h