snode.c: core::pipe::Source Class Reference
core::pipe::Source Class Reference
#include <Source.h>
Public Member Functions
Source ()
virtual ~Source ()
void disconnect ()
void connect (Sink &sink)
void disconnect (Sink &sink)
ssize_t send (const char *junk, std::size_t junkLen)
void eof ()
void error (int errnum)
Protected Attributes
Sink * sink
Detailed Description
Definition at line 33 of file Source.h.
Constructor & Destructor Documentation
Source()
core::pipe::Source::Source ()
Definition at line 31 of file Source.cpp.
         : sink(nullptr) {
     }
~Source()
core::pipe::Source::~Source () virtual
Definition at line 35 of file Source.cpp.
                     {
         disconnect();
     }
References disconnect().
Member Function Documentation
connect()
void core::pipe::Source::connect (Sink & sink)
Definition at line 45 of file Source.cpp.
{
         this->sink = &sink;
         if (this->sink != nullptr) {
             sink.connect(*this);
         }
     }
References core::pipe::Sink::connect(), and sink.
disconnect() [1/2]
void core::pipe::Source::disconnect ()
Definition at line 39 of file Source.cpp.
{
         if (sink != nullptr) {
             sink->disconnect(*this);
         }
     }
References core::pipe::Sink::disconnect(), and sink.
Referenced by core::pipe::Sink::disconnect(), and ~Source().
disconnect() [2/2]
void core::pipe::Source::disconnect (Sink & sink)
Definition at line 52 of file Source.cpp.
{
         if (&sink == this->sink) {
             this->sink = nullptr;
         }
     }
References sink.
eof()
void core::pipe::Source::eof ()
Definition at line 77 of file Source.cpp.
                      {
         if (this->sink != nullptr) {
             sink->eof();
         }
     }
References core::pipe::Sink::eof(), and sink.
Referenced by core::file::FileReader::event().
error()
void core::pipe::Source::error (int errnum)
Definition at line 71 of file Source.cpp.
{
         if (this->sink != nullptr) {
             sink->error(errnum);
         }
     }
References core::pipe::Sink::error(), and sink.
Referenced by core::file::FileReader::event().
send()
ssize_t core::pipe::Source::send (const char * junk, std::size_t junkLen)
Definition at line 58 of file Source.cpp.
{
         ssize_t ret = static_cast<ssize_t>(junkLen);
         if (this->sink != nullptr) {
             sink->receive(junk, junkLen);
         } else {
             ret = -1;
             errno = EPIPE;
         }
         return ret;
     }
References core::pipe::Sink::receive(), and sink.
Referenced by core::file::FileReader::event().
Member Data Documentation
sink
Sink* core::pipe::Source::sink protected
Definition at line 47 of file Source.h.
Referenced by connect(), disconnect(), eof(), error(), core::file::FileReader::FileReader(), and send().
The documentation for this class was generated from the following files:
core/pipe/Source.h
core/pipe/Source.cpp