snode.c: core::ConnectEventReceiver Class Reference
core::ConnectEventReceiver Class Reference abstract
#include <ConnectEventReceiver.h>
Protected Member Functions
ConnectEventReceiver (const utils::Timeval &timeout=10)
Protected Member Functions inherited from core::EventReceiver
EventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
Private Member Functions
virtual void connectEvent ()=0
virtual void connectTimeout ()
void dispatchEvent () final
void timeoutEvent () final
bool continueImmediately () const final
virtual bool continueConnectImmediately () const
Additional Inherited Members
Public Member Functions inherited from core::EventReceiver
int getRegisteredFd ()
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime)
void triggered (const utils::Timeval &currentTime)
void disabled ()
virtual void terminate ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Detailed Description
Definition at line 32 of file ConnectEventReceiver.h.
Constructor & Destructor Documentation
ConnectEventReceiver()
core::ConnectEventReceiver::ConnectEventReceiver (const utils::Timeval & timeout = 10) protected
Definition at line 30 of file ConnectEventReceiver.cpp.
         : EventReceiver(EventLoop::getEventDispatcher().getDescriptorEventDispatcher(core::EventDispatcher::DISP_TYPE::WR), timeout) {
     }
Member Function Documentation
connectEvent()
virtual void core::ConnectEventReceiver::connectEvent () private pure virtual
Implemented in core::socket::stream::SocketConnector< SocketConnectionT >, core::socket::stream::SocketConnector< core::socket::stream::legacy::SocketConnection< SocketT > >, and core::socket::stream::SocketConnector< core::socket::stream::tls::SocketConnection< SocketT > >.
Referenced by dispatchEvent().
connectTimeout()
void core::ConnectEventReceiver::connectTimeout () private virtual
Definition at line 34 of file ConnectEventReceiver.cpp.
{
         disable();
     }
References core::EventReceiver::disable().
Referenced by timeoutEvent().
continueConnectImmediately()
bool core::ConnectEventReceiver::continueConnectImmediately () const private virtual
Definition at line 38 of file ConnectEventReceiver.cpp.
{
         return false;
     }
Referenced by continueImmediately().
continueImmediately()
bool core::ConnectEventReceiver::continueImmediately () const final private virtual
Implements core::EventReceiver.
Definition at line 50 of file ConnectEventReceiver.cpp.
{
         return continueConnectImmediately();
     }
References continueConnectImmediately().
dispatchEvent()
void core::ConnectEventReceiver::dispatchEvent () final private virtual
Implements core::EventReceiver.
Definition at line 42 of file ConnectEventReceiver.cpp.
{
         connectEvent();
     }
References connectEvent().
timeoutEvent()
void core::ConnectEventReceiver::timeoutEvent () final private virtual
Implements core::EventReceiver.
Definition at line 46 of file ConnectEventReceiver.cpp.
{
         connectTimeout();
     }
References connectTimeout().
The documentation for this class was generated from the following files:
core/ConnectEventReceiver.h
core/ConnectEventReceiver.cpp