snode.c: core::epoll::DescriptorEventDispatcher Class Reference
core::epoll::DescriptorEventDispatcher Class Reference
#include <DescriptorEventDispatcher.h>
Classes
class EPollEvents
Public Member Functions
DescriptorEventDispatcher (int &epfd, uint32_t events)
Public Member Functions inherited from core::DescriptorEventDispatcher
virtual ~DescriptorEventDispatcher ()=default
void publish (Event *event)
void enable (DescriptorEventReceiver *eventReceiver)
void disable (DescriptorEventReceiver *eventReceiver)
void suspend (DescriptorEventReceiver *eventReceiver)
void resume (DescriptorEventReceiver *eventReceiver)
void observeEnabledEvents (const utils::Timeval &currentTime)
void dispatchImmediateEvents ()
void checkTimedOutEvents (const utils::Timeval &currentTime)
void unobserveDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int getMaxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void stop ()
Private Member Functions
DescriptorEventDispatcher (const DescriptorEventDispatcher &)=delete
DescriptorEventDispatcher & operator= (const DescriptorEventDispatcher &)=delete
void modAdd (core::DescriptorEventReceiver *eventReceiver) override
void modDel (core::DescriptorEventReceiver *eventReceiver) override
void modOn (core::DescriptorEventReceiver *eventReceiver) override
void modOff (core::DescriptorEventReceiver *eventReceiver) override
void dispatchActiveEvents () override
void finishTick () override
Private Attributes
EPollEvents ePollEvents
Additional Inherited Members
Protected Member Functions inherited from core::DescriptorEventDispatcher
DescriptorEventDispatcher ()=default
Protected Attributes inherited from core::DescriptorEventDispatcher
std::map< int, EventReceiverList > enabledEventReceiver
std::map< int, EventReceiverList > observedEventReceiver
std::map< int, EventReceiverList > disabledEventReceiver
unsigned long eventCounter = 0
Detailed Description
Definition at line 39 of file DescriptorEventDispatcher.h.
Constructor & Destructor Documentation
DescriptorEventDispatcher() [1/2]
core::epoll::DescriptorEventDispatcher::DescriptorEventDispatcher (const DescriptorEventDispatcher &) private delete
DescriptorEventDispatcher() [2/2]
core::epoll::DescriptorEventDispatcher::DescriptorEventDispatcher (int & epfd, uint32_t events) explicit
Definition at line 97 of file DescriptorEventDispatcher.cpp.
         : ePollEvents(epfd, events) {
     }
Member Function Documentation
dispatchActiveEvents()
void core::epoll::DescriptorEventDispatcher::dispatchActiveEvents () override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 117 of file DescriptorEventDispatcher.cpp.
{
         int count = core::system::epoll_wait(ePollEvents.getEPFd(), ePollEvents.getEvents(), ePollEvents.getInterestCount(), 0);
         for (int i = 0; i < count; i++) {
             core::DescriptorEventReceiver* eventReceiver = static_cast<core::DescriptorEventReceiver*>(ePollEvents.getEvents()[i].data.ptr);
             if (!eventReceiver->continueImmediately() && !eventReceiver->isSuspended()) {
                 eventCounter++;
                 eventReceiver->publish();
             }
         }
     }
References core::DescriptorEventReceiver::continueImmediately(), core::system::epoll_wait(), ePollEvents, core::DescriptorEventDispatcher::eventCounter, core::epoll::DescriptorEventDispatcher::EPollEvents::getEPFd(), core::epoll::DescriptorEventDispatcher::EPollEvents::getEvents(), core::epoll::DescriptorEventDispatcher::EPollEvents::getInterestCount(), core::DescriptorEventReceiver::isSuspended(), and core::EventReceiver::publish().
finishTick()
void core::epoll::DescriptorEventDispatcher::finishTick () override private virtual
Reimplemented from core::DescriptorEventDispatcher.
Definition at line 129 of file DescriptorEventDispatcher.cpp.
{
         ePollEvents.compress();
     }
modAdd()
void core::epoll::DescriptorEventDispatcher::modAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 101 of file DescriptorEventDispatcher.cpp.
{
         ePollEvents.modAdd(eventReceiver);
     }
References ePollEvents, and core::epoll::DescriptorEventDispatcher::EPollEvents::modAdd().
modDel()
void core::epoll::DescriptorEventDispatcher::modDel (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 105 of file DescriptorEventDispatcher.cpp.
{
         ePollEvents.modDel(eventReceiver);
     }
References ePollEvents, and core::epoll::DescriptorEventDispatcher::EPollEvents::modDel().
modOff()
void core::epoll::DescriptorEventDispatcher::modOff (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 113 of file DescriptorEventDispatcher.cpp.
{
         ePollEvents.modOff(eventReceiver);
     }
References ePollEvents, and core::epoll::DescriptorEventDispatcher::EPollEvents::modOff().
modOn()
void core::epoll::DescriptorEventDispatcher::modOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 109 of file DescriptorEventDispatcher.cpp.
{
         ePollEvents.modOn(eventReceiver);
     }
References ePollEvents, and core::epoll::DescriptorEventDispatcher::EPollEvents::modOn().
operator=()
DescriptorEventDispatcher& core::epoll::DescriptorEventDispatcher::operator= (const DescriptorEventDispatcher &) private delete
Member Data Documentation
ePollEvents
EPollEvents core::epoll::DescriptorEventDispatcher::ePollEvents private
Definition at line 85 of file DescriptorEventDispatcher.h.
Referenced by core::epoll::DescriptorEventDispatcher::EPollEvents::compress(), dispatchActiveEvents(), core::epoll::DescriptorEventDispatcher::EPollEvents::getEvents(), core::epoll::DescriptorEventDispatcher::EPollEvents::modAdd(), modAdd(), modDel(), modOff(), and modOn().
The documentation for this class was generated from the following files:
core/mux/epoll/DescriptorEventDispatcher.h
core/mux/epoll/DescriptorEventDispatcher.cpp