snode.c: core::socket::stream::tls::SocketReader< SocketT > Class Template Reference
core::socket::stream::tls::SocketReader< SocketT > Class Template Reference abstract
#include <SocketReader.h>
Protected Member Functions
virtual void doSSLHandshake (const std::function< void()> &onSuccess, const std::function< void()> &onTimeout, const std::function< void(int)> &onError)=0
void setSSLError (int sslErr)
Protected Member Functions inherited from core::socket::stream::SocketReader< SocketT >
SocketReader (const std::function< void(int)> &onError)
virtual ~SocketReader ()=default
virtual void doShutdown ()
void shutdown ()
ssize_t readFromPeer (char *junk, std::size_t junkLen)
Protected Member Functions inherited from core::ReadEventReceiver
ReadEventReceiver (long timeout=60)
Protected Member Functions inherited from core::EventReceiver
EventReceiver (EventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Protected Attributes
SSL * ssl = nullptr
int sslErr = SSL_ERROR_NONE
Protected Attributes inherited from core::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Private Member Functions
ssize_t read (char *junk, std::size_t junkLen) override
int getError () override
bool continueReadImmediately () override
Additional Inherited Members
Public Types inherited from core::socket::stream::SocketReader< SocketT >
using Socket = SocketT
Public Member Functions inherited from core::EventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from core::ObservationCounter
bool isObserved ()
Detailed Description
template<typename SocketT>
class core::socket::stream::tls::SocketReader< SocketT >
Definition at line 39 of file SocketReader.h.
Member Function Documentation
continueReadImmediately()
template<typename SocketT > bool core::socket::stream::tls::SocketReader< SocketT >::continueReadImmediately () inline override private virtual
Reimplemented from core::socket::stream::SocketReader< SocketT >.
Definition at line 108 of file SocketReader.h.
{
             return SSL_pending(ssl) || core::socket::stream::SocketReader<SocketT>::continueReadImmediately();
         }
References core::socket::stream::SocketReader< SocketT >::continueReadImmediately(), and core::socket::stream::tls::SocketReader< SocketT >::ssl.
doSSLHandshake()
template<typename SocketT > virtual void core::socket::stream::tls::SocketReader< SocketT >::doSSLHandshake (const std::function< void()> & onSuccess, const std::function< void()> & onTimeout, const std::function< void(int)> & onError) protected pure virtual
Referenced by core::socket::stream::tls::SocketReader< SocketT >::read().
getError()
template<typename SocketT > int core::socket::stream::tls::SocketReader< SocketT >::getError () inline override private virtual
Implements core::socket::stream::SocketReader< SocketT >.
Definition at line 89 of file SocketReader.h.
{
             int ret = errno;
             switch (sslErr) {
                 case SSL_ERROR_NONE:
                     [[fallthrough]];
                 case SSL_ERROR_ZERO_RETURN:
                     ret = 0;
                     break;
                 case SSL_ERROR_SYSCALL:
                     break;
                 default:
                     ret = -sslErr;
                     break;
             };
             return ret;
         }
References core::socket::stream::tls::SocketReader< SocketT >::sslErr.
read()
template<typename SocketT > ssize_t core::socket::stream::tls::SocketReader< SocketT >::read (char * junk, std::size_t junkLen) inline override private virtual
Implements core::socket::stream::SocketReader< SocketT >.
Definition at line 43 of file SocketReader.h.
{
             sslErr = 0;
             int ret = SSL_read(ssl, junk, static_cast<int>(junkLen));
             if (ret <= 0) {
                 sslErr = SSL_get_error(ssl, ret);
                 switch (sslErr) {
                     case SSL_ERROR_WANT_WRITE:
                         LOG(INFO) << "SSL/TLS start renegotiation on read";
                         doSSLHandshake(
                             [](void) -> void {
                                 LOG(INFO) << "SSL/TLS renegotiation on read success";
                             },
                             [](void) -> void {
                                 LOG(WARNING) << "SSL/TLS renegotiation on read timed out";
                             },
                             [this](int sslErr) -> void {
                                 ssl_log("SSL/TLS renegotiation", sslErr);
                                 setSSLError(sslErr);
                             });
                         errno = EAGAIN;
                         break;
                     case SSL_ERROR_WANT_READ:
                         ret = 0;
                         errno = EAGAIN;
                         break;
                     case SSL_ERROR_ZERO_RETURN:
                         ret = 0;
                         errno = 0;
                         break;
                     case SSL_ERROR_SYSCALL:
                         if (errno != 0) {
                             ssl_log("SSL/TLS read failed", sslErr);
                         }
                         break;
                     default:
                         ssl_log("SSL/TLS read failed", sslErr);
                         break;
                 }
             }
             return ret;
         }
References core::socket::stream::tls::SocketReader< SocketT >::doSSLHandshake(), core::socket::stream::tls::SocketReader< SocketT >::setSSLError(), core::socket::stream::tls::SocketReader< SocketT >::ssl, core::socket::stream::tls::ssl_log(), core::ssl::SSL_read(), and core::socket::stream::tls::SocketReader< SocketT >::sslErr.
setSSLError()
template<typename SocketT > void core::socket::stream::tls::SocketReader< SocketT >::setSSLError (int sslErr) inline protected
Definition at line 117 of file SocketReader.h.
{
             this->sslErr = sslErr;
         }
References core::socket::stream::tls::SocketReader< SocketT >::sslErr.
Referenced by core::socket::stream::tls::SocketReader< SocketT >::read().
Member Data Documentation
ssl
template<typename SocketT > SSL* core::socket::stream::tls::SocketReader< SocketT >::ssl = nullptr protected
Definition at line 121 of file SocketReader.h.
Referenced by core::socket::stream::tls::SocketReader< SocketT >::continueReadImmediately(), and core::socket::stream::tls::SocketReader< SocketT >::read().
sslErr
template<typename SocketT > int core::socket::stream::tls::SocketReader< SocketT >::sslErr = SSL_ERROR_NONE protected
Definition at line 123 of file SocketReader.h.
Referenced by core::socket::stream::tls::SocketReader< SocketT >::getError(), core::socket::stream::tls::SocketReader< SocketT >::read(), and core::socket::stream::tls::SocketReader< SocketT >::setSSLError().
The documentation for this class was generated from the following file:
core/socket/stream/tls/SocketReader.h