snode.c: core::poll::DescriptorEventDispatcher Class Reference
core::poll::DescriptorEventDispatcher Class Reference
#include <DescriptorEventDispatcher.h>
Public Member Functions
DescriptorEventDispatcher (core::poll::PollFds &pollFds, short events, short revents)
Public Member Functions inherited from core::DescriptorEventDispatcher
virtual ~DescriptorEventDispatcher ()=default
void enable (EventReceiver *eventReceiver)
void disable (EventReceiver *eventReceiver)
void suspend (EventReceiver *eventReceiver)
void resume (EventReceiver *eventReceiver)
void observeEnabledEvents ()
void dispatchImmediateEvents (const utils::Timeval &currentTime)
void unobserveDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int getMaxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void stop ()
Private Member Functions
DescriptorEventDispatcher (const DescriptorEventDispatcher &)=delete
DescriptorEventDispatcher & operator= (const DescriptorEventDispatcher &)=delete
void modAdd (EventReceiver *eventReceiver) override
void modDel (EventReceiver *eventReceiver) override
void modOn (EventReceiver *eventReceiver) override
void modOff (EventReceiver *eventReceiver) override
void dispatchActiveEvents (const utils::Timeval &currentTime) override
void finishTick () override
Private Attributes
core::poll::PollFds & pollFds
short events
short revents
Additional Inherited Members
Protected Member Functions inherited from core::DescriptorEventDispatcher
DescriptorEventDispatcher ()=default
Protected Attributes inherited from core::DescriptorEventDispatcher
std::map< int, EventReceiverList > enabledEventReceiver
std::map< int, EventReceiverList > observedEventReceiver
std::map< int, EventReceiverList > disabledEventReceiver
std::map< int, EventReceiverList > unobservedEventReceiver
unsigned long eventCounter = 0
Detailed Description
Definition at line 41 of file DescriptorEventDispatcher.h.
Constructor & Destructor Documentation
DescriptorEventDispatcher() [1/2]
core::poll::DescriptorEventDispatcher::DescriptorEventDispatcher (const DescriptorEventDispatcher &) private delete
DescriptorEventDispatcher() [2/2]
core::poll::DescriptorEventDispatcher::DescriptorEventDispatcher (core::poll::PollFds & pollFds, short events, short revents)
Definition at line 33 of file DescriptorEventDispatcher.cpp.
         : pollFds(pollFds)
         , events(events)
         , revents(revents) {
     }
Member Function Documentation
dispatchActiveEvents()
void core::poll::DescriptorEventDispatcher::dispatchActiveEvents (const utils::Timeval & currentTime) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 55 of file DescriptorEventDispatcher.cpp.
{
         pollfd* pollfds = pollFds.getEvents();
         std::unordered_map<int, PollFds::PollFdIndex> pollFdsIndices = pollFds.getPollFdIndices();
         for (auto& [fd, eventReceivers] : observedEventReceiver) { // cppcheck-suppress unassignedVariable
             pollfd& pollFd = pollfds[pollFdsIndices[fd].index];
             if ((pollFd.events & events) != 0 && (pollFd.revents & this->revents) != 0) {
                 EventReceiver* eventReceiver = eventReceivers.front();
                 if (!eventReceiver->continueImmediately() && !eventReceiver->isSuspended()) {
                     eventCounter++;
                     eventReceiver->dispatch(currentTime);
                 }
             }
         }
     }
References core::EventReceiver::continueImmediately(), core::EventReceiver::dispatch(), core::DescriptorEventDispatcher::eventCounter, events, core::poll::PollFds::getEvents(), core::poll::PollFds::getPollFdIndices(), core::EventReceiver::isSuspended(), core::DescriptorEventDispatcher::observedEventReceiver, and pollFds.
finishTick()
void core::poll::DescriptorEventDispatcher::finishTick () override private virtual
Reimplemented from core::DescriptorEventDispatcher.
Definition at line 73 of file DescriptorEventDispatcher.cpp.
{
         pollFds.compress();
     }
modAdd()
void core::poll::DescriptorEventDispatcher::modAdd (EventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 39 of file DescriptorEventDispatcher.cpp.
{
         pollFds.modAdd(eventReceiver, events);
     }
References events, core::poll::PollFds::modAdd(), and pollFds.
modDel()
void core::poll::DescriptorEventDispatcher::modDel (EventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 43 of file DescriptorEventDispatcher.cpp.
{
         pollFds.modDel(eventReceiver, events);
     }
References events, core::poll::PollFds::modDel(), and pollFds.
modOff()
void core::poll::DescriptorEventDispatcher::modOff (EventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 51 of file DescriptorEventDispatcher.cpp.
{
         pollFds.modOff(eventReceiver, events);
     }
References events, core::poll::PollFds::modOff(), and pollFds.
modOn()
void core::poll::DescriptorEventDispatcher::modOn (EventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 47 of file DescriptorEventDispatcher.cpp.
{
         pollFds.modOn(eventReceiver, events);
     }
References events, core::poll::PollFds::modOn(), and pollFds.
operator=()
DescriptorEventDispatcher& core::poll::DescriptorEventDispatcher::operator= (const DescriptorEventDispatcher &) private delete
Member Data Documentation
events
short core::poll::DescriptorEventDispatcher::events private
Definition at line 58 of file DescriptorEventDispatcher.h.
Referenced by dispatchActiveEvents(), modAdd(), modDel(), modOff(), and modOn().
pollFds
core::poll::PollFds& core::poll::DescriptorEventDispatcher::pollFds private
Definition at line 57 of file DescriptorEventDispatcher.h.
Referenced by dispatchActiveEvents(), modAdd(), modDel(), modOff(), and modOn().
revents
short core::poll::DescriptorEventDispatcher::revents private
Definition at line 59 of file DescriptorEventDispatcher.h.
The documentation for this class was generated from the following files:
core/poll/DescriptorEventDispatcher.h
core/poll/DescriptorEventDispatcher.cpp