snode.c: core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT > Class Template Reference
core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT > Class Template Reference
#include <SocketAcceptor.h>
Public Types
using Config = typename SocketServer::Config
using SocketAddress = typename PrimarySocket::SocketAddress
Public Member Functions
SocketAcceptor (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketAcceptor () override
void listen (const std::shared_ptr< Config > &config, const std::function< void(const SocketAddress &, int)> &onError)
Protected Types
using SocketConnection = SocketConnectionT< PrimarySocket >
using SocketConnectionFactory = core::socket::stream::SocketConnectionFactory< SocketServer, SocketConnection >
Protected Member Functions
void destruct ()
Protected Member Functions inherited from core::eventreceiver::InitAcceptEventReceiver
InitAcceptEventReceiver (const std::string &name)
Protected Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish ()
void unPublish ()
const std::string & getName ()
Protected Member Functions inherited from core::eventreceiver::AcceptEventReceiver
AcceptEventReceiver (const std::string &name, const utils::Timeval &timeout=DescriptorEventReceiver::TIMEOUT::DISABLE)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
Protected Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Protected Attributes
std::shared_ptr< Config > config = nullptr
std::function< void(const SocketAddress &, int)> onError = nullptr
PrimarySocket * primarySocket = nullptr
SecondarySocket * secondarySocket = nullptr
SocketConnectionFactory socketConnectionFactory
std::map< std::string, std::any > options
Protected Attributes inherited from core::EventReceiver
Event _event
Private Types
using SocketServer = SocketServerT
using PrimarySocket = typename SocketServer::Socket
using SecondarySocket = net::un::dgram::Socket
Private Member Functions
SocketAcceptor ()=delete
SocketAcceptor (const SocketAcceptor &)=delete
SocketAcceptor & operator= (const SocketAcceptor &)=delete
void initAcceptEvent () override
void acceptEvent () override
int reuseAddress ()
void unobservedEvent () override
Detailed Description
template<typename SocketServerT, template< typename SocketT > class SocketConnectionT>
class core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >
Definition at line 47 of file SocketAcceptor.h.
Member Typedef Documentation
Config
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::Config = typename SocketServer::Config
Definition at line 64 of file SocketAcceptor.h.
PrimarySocket
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::PrimarySocket = typename SocketServer::Socket private
Definition at line 56 of file SocketAcceptor.h.
SecondarySocket
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SecondarySocket = net::un::dgram::Socket private
Definition at line 57 of file SocketAcceptor.h.
SocketAddress
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SocketAddress = typename PrimarySocket::SocketAddress
Definition at line 65 of file SocketAcceptor.h.
SocketConnection
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SocketConnection = SocketConnectionT<PrimarySocket> protected
Definition at line 60 of file SocketAcceptor.h.
SocketConnectionFactory
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SocketConnectionFactory = core::socket::stream::SocketConnectionFactory<SocketServer, SocketConnection> protected
Definition at line 61 of file SocketAcceptor.h.
SocketServer
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SocketServer = SocketServerT private
Definition at line 55 of file SocketAcceptor.h.
Constructor & Destructor Documentation
SocketAcceptor() [1/3]
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SocketAcceptor () private delete
SocketAcceptor() [2/3]
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SocketAcceptor (const SocketAcceptor< SocketServerT, SocketConnectionT > &) private delete
SocketAcceptor() [3/3]
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::SocketAcceptor (const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options) inline
Sequence diagramm of res.upgrade(req).
Definition at line 72 of file SocketAcceptor.h.
             : core::eventreceiver::InitAcceptEventReceiver("SocketAcceptor")
             , core::eventreceiver::AcceptEventReceiver("SocketAcceptor")
             , socketConnectionFactory(socketContextFactory, onConnect, onConnected, onDisconnect)
             , options(options) {
         }
~SocketAcceptor()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::~SocketAcceptor () inline override
Definition at line 83 of file SocketAcceptor.h.
{
             if (secondarySocket != nullptr) {
                 delete secondarySocket;
             }
             if (primarySocket != nullptr) {
                 delete primarySocket;
             }
         }
References core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::primarySocket, and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::secondarySocket.
Member Function Documentation
acceptEvent()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent () inline override private virtual
Implements core::eventreceiver::AcceptEventReceiver.
Definition at line 155 of file SocketAcceptor.h.
{
             if (config->getClusterMode() == net::config::ConfigCluster::MODE::NONE ||
                 config->getClusterMode() == net::config::ConfigCluster::MODE::PRIMARY) {
                 PrimarySocket socket;
                 int acceptsPerTick = config->getAcceptsPerTick();
                 do {
                     SocketAddress remoteAddress{};
                     socket = primarySocket->accept4(remoteAddress, SOCK_NONBLOCK);
                     if (socket.isValid()) {
                         if (config->getClusterMode() == net::config::ConfigCluster::MODE::NONE) {
                             socketConnectionFactory.create(socket, config);
                         } else {
                             // Send descriptor to SECONDARY
                             VLOG(0) << "Sending to secondary";
                             secondarySocket->sendFd(SecondarySocket::SocketAddress("/tmp/secondary"), socket.getFd());
                             SecondarySocket::SocketAddress address;
                         }
                     } else if (errno != EINTR && errno != EAGAIN && errno != EWOULDBLOCK) {
                         PLOG(ERROR) << "accept";
                     }
                 } while (--acceptsPerTick > 0 && socket.isValid());
             } else if (config->getClusterMode() == net::config::ConfigCluster::MODE::SECONDARY ||
                        config->getClusterMode() == net::config::ConfigCluster::MODE::PROXY) {
                 // Receive socketfd via SOCK_UNIX, SOCK_DGRAM
                 int fd = -1;
                 if (secondarySocket->recvFd(&fd) >= 0) {
                     PrimarySocket socket(fd);
                     if (config->getClusterMode() == net::config::ConfigCluster::MODE::SECONDARY) {
                         socketConnectionFactory.create(socket, config);
                     } else { // PROXY
                         // Send to SECONDARY (TERTIARY)
                     }
                 } else {
                     PLOG(ERROR) << "read_fd";
                 }
             }
         }
References core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::config, core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::create(), core::ERROR, core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::primarySocket, net::Socket< SocketAddressT >::recvFd(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::secondarySocket, net::Socket< SocketAddressT >::sendFd(), core::system::socket(), and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::socketConnectionFactory.
destruct()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::destruct () inline protected
Definition at line 198 of file SocketAcceptor.h.
{
             delete this;
         }
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent(), and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::unobservedEvent().
initAcceptEvent()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent () inline override private virtual
Implements core::eventreceiver::InitAcceptEventReceiver.
Definition at line 100 of file SocketAcceptor.h.
{
             if (config->getClusterMode() == net::config::ConfigCluster::MODE::NONE ||
                 config->getClusterMode() == net::config::ConfigCluster::MODE::PRIMARY) {
                 VLOG(0) << "Mode: STANDALONE or PRIMARY";
                 primarySocket = new PrimarySocket();
                 if (primarySocket->open(PrimarySocket::Flags::NONBLOCK) < 0) {
                     onError(config->getLocalAddress(), errno);
                     destruct();
 #if !defined(NDEBUG)
                 } else if (primarySocket->reuseAddress() < 0) {
                     onError(config->getLocalAddress(), errno);
                     destruct();
 #endif // !defined(NDEBUG)
                 } else if (primarySocket->bind(config->getLocalAddress()) < 0) {
                     onError(config->getLocalAddress(), errno);
                     destruct();
                 } else if (primarySocket->listen(config->getBacklog()) < 0) {
                     onError(config->getLocalAddress(), errno);
                     destruct();
                 } else if (config->getClusterMode() == net::config::ConfigCluster::MODE::PRIMARY) {
                     VLOG(0) << "    Cluster: PRIMARY";
                     secondarySocket = new SecondarySocket();
                     if (secondarySocket->open(SecondarySocket::Flags::NONBLOCK) < 0) {
                         onError(config->getLocalAddress(), errno);
                         destruct();
                     } else if (secondarySocket->bind(SecondarySocket::SocketAddress("/tmp/primary")) < 0) {
                         onError(config->getLocalAddress(), errno);
                         destruct();
                     } else {
                         onError(config->getLocalAddress(), 0);
                         enable(primarySocket->getFd());
                     }
                 } else {
                     VLOG(0) << "    Cluster: NONE";
                     onError(config->getLocalAddress(), 0);
                     enable(primarySocket->getFd());
                 }
             } else if (config->getClusterMode() == net::config::ConfigCluster::MODE::SECONDARY ||
                        config->getClusterMode() == net::config::ConfigCluster::MODE::PROXY) {
                 VLOG(0) << "    Mode: SECONDARY or PROXY";
                 secondarySocket = new SecondarySocket();
                 if (secondarySocket->open(SecondarySocket::Flags::NONBLOCK) < 0) {
                     onError(config->getLocalAddress(), errno);
                     destruct();
                 } else if (secondarySocket->bind(SecondarySocket::SocketAddress("/tmp/secondary")) < 0) {
                     onError(config->getLocalAddress(), errno);
                     destruct();
                 } else {
                     onError(config->getLocalAddress(), errno);
                     enable(secondarySocket->getFd());
                 }
             }
         }
References net::Socket< SocketAddressT >::bind(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::config, core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::destruct(), core::DescriptorEventReceiver::enable(), core::Descriptor::getFd(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::onError, core::socket::Socket::open(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::primarySocket, and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::secondarySocket.
listen()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::listen (const std::shared_ptr< Config > & config, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 92 of file SocketAcceptor.h.
{
             this->config = config;
             this->onError = onError;
             InitAcceptEventReceiver::publish();
         }
References core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::config, and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::onError.
operator=()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> SocketAcceptor& core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::operator= (const SocketAcceptor< SocketServerT, SocketConnectionT > &) private delete
reuseAddress()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> int core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::reuseAddress () inline private
Definition at line 205 of file SocketAcceptor.h.
{
             int sockopt = 1;
             return primarySocket->setSockopt(SOL_SOCKET, SO_REUSEADDR, &sockopt, sizeof(sockopt));
         }
References core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::primarySocket.
unobservedEvent()
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::unobservedEvent () inline override private virtual
Implements core::Observer.
Definition at line 211 of file SocketAcceptor.h.
{
             destruct();
         }
References core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::destruct().
Member Data Documentation
config
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> std::shared_ptr<Config> core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::config = nullptr protected
Definition at line 202 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent(), and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::listen().
onError
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> std::function<void(const SocketAddress&, int)> core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::onError = nullptr protected
Definition at line 216 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent(), and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::listen().
options
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> std::map<std::string, std::any> core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::options protected
Definition at line 223 of file SocketAcceptor.h.
primarySocket
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> PrimarySocket* core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::primarySocket = nullptr protected
Definition at line 218 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::reuseAddress(), and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::~SocketAcceptor().
secondarySocket
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> SecondarySocket* core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::secondarySocket = nullptr protected
Definition at line 219 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent(), core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::initAcceptEvent(), and core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::~SocketAcceptor().
socketConnectionFactory
template<typename SocketServerT , template< typename SocketT > class SocketConnectionT> SocketConnectionFactory core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::socketConnectionFactory protected
Definition at line 221 of file SocketAcceptor.h.
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent().
The documentation for this class was generated from the following file:
core/socket/stream/SocketAcceptor.h