snode.c: CLI::HorribleError Class Reference
CLI::HorribleError Class Reference
Errors
#include <CLI11.hpp>
Public Member Functions
HorribleError (std::string msg, ExitCodes exit_code)
HorribleError (std::string msg, int exit_code)
HorribleError (std::string msg)
Public Member Functions inherited from CLI::ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from CLI::Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Protected Member Functions
HorribleError (std::string ename, std::string msg, int exit_code)
HorribleError (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from CLI::ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
This is just a safety check to verify selection and parsing match - you should not ever see it Strings are directly added to this error, but again, it should never be seen.
Definition at line 921 of file CLI11.hpp.
Constructor & Destructor Documentation
HorribleError() [1/5]
CLI::HorribleError::HorribleError (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 922 of file CLI11.hpp.
 : public Error {
Referenced by CLI::App::_get_fallthrough_parent(), CLI::App::_parse_arg(), CLI::App::_parse_single(), and CLI::App::_parse_subcommand().
HorribleError() [2/5]
CLI::HorribleError::HorribleError (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 922 of file CLI11.hpp.
 : public Error {
HorribleError() [3/5]
CLI::HorribleError::HorribleError (std::string msg, ExitCodes exit_code) inline
Definition at line 922 of file CLI11.hpp.
 : public Error {
HorribleError() [4/5]
CLI::HorribleError::HorribleError (std::string msg, int exit_code) inline
Definition at line 922 of file CLI11.hpp.
 : public Error {
HorribleError() [5/5]
CLI::HorribleError::HorribleError (std::string msg) inline explicit
Definition at line 923 of file CLI11.hpp.
 : public Error {
The documentation for this class was generated from the following file:
utils/CLI11.hpp