snode.c: net::ConfigConn Class Reference
net::ConfigConn Class Reference
#include <ConfigConn.h>
Public Member Functions
ConfigConn (CLI::App *baseSc)
const utils::Timeval & getReadTimeout () const
const utils::Timeval & getWriteTimeout () const
std::size_t getReadBlockSize () const
std::size_t getWriteBlockSize () const
const utils::Timeval & getTerminateTimeout () const
Private Attributes
CLI::App * connectionSc = nullptr
CLI::Option * readTimeoutOpt = nullptr
CLI::Option * writeTimeoutOpt = nullptr
CLI::Option * readBlockSizeOpt = nullptr
CLI::Option * writeBlockSizeOpt = nullptr
CLI::Option * terminateTimeoutOpt = nullptr
std::string name
utils::Timeval readTimeout
utils::Timeval writeTimeout
std::size_t readBlockSize
std::size_t writeBlockSize
utils::Timeval terminateTimeout
Detailed Description
Definition at line 37 of file ConfigConn.h.
Constructor & Destructor Documentation
ConfigConn()
net::ConfigConn::ConfigConn (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigConn.cpp.
{
         connectionSc = baseSc->add_subcommand("conn");
         connectionSc->description("Options for established client connections");
         connectionSc->configurable();
         connectionSc->group("Sub-Options (use -h,--help on them)");
         readTimeoutOpt = connectionSc->add_option("-r,--read-timeout", readTimeout, "Read timeout");
         readTimeoutOpt->type_name("[sec]");
         readTimeoutOpt->default_val(60);
         readTimeoutOpt->configurable();
         writeTimeoutOpt = connectionSc->add_option("-w,--write-timeout", writeTimeout, "Write timeout");
         writeTimeoutOpt->type_name("[sec]");
         writeTimeoutOpt->default_val(60);
         writeTimeoutOpt->configurable();
         readBlockSizeOpt = connectionSc->add_option("--read-block-size", readBlockSize, "Read block size");
         readBlockSizeOpt->type_name("[bytes]");
         readBlockSizeOpt->default_val(16384);
         readBlockSizeOpt->configurable();
         writeBlockSizeOpt = connectionSc->add_option("--write-block-size", writeBlockSize, "Write block size");
         writeBlockSizeOpt->type_name("[bytes]");
         writeBlockSizeOpt->default_val(16384);
         writeBlockSizeOpt->configurable();
         terminateTimeoutOpt = connectionSc->add_option("-t,--terminate-timeout", terminateTimeout, "Terminate timeout");
         terminateTimeoutOpt->type_name("[sec]");
         terminateTimeoutOpt->default_val(1);
         terminateTimeoutOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), connectionSc, CLI::Option::default_val(), CLI::App::description(), CLI::App::group(), readBlockSize, readBlockSizeOpt, readTimeout, readTimeoutOpt, terminateTimeout, terminateTimeoutOpt, CLI::Option::type_name(), writeBlockSize, writeBlockSizeOpt, writeTimeout, and writeTimeoutOpt.
Member Function Documentation
getReadBlockSize()
std::size_t net::ConfigConn::getReadBlockSize () const
Definition at line 70 of file ConfigConn.cpp.
{
         return readBlockSize;
     }
References readBlockSize.
getReadTimeout()
const utils::Timeval & net::ConfigConn::getReadTimeout () const
Definition at line 62 of file ConfigConn.cpp.
{
         return readTimeout;
     }
References readTimeout.
getTerminateTimeout()
const utils::Timeval & net::ConfigConn::getTerminateTimeout () const
Definition at line 78 of file ConfigConn.cpp.
{
         return terminateTimeout;
     }
References terminateTimeout.
getWriteBlockSize()
std::size_t net::ConfigConn::getWriteBlockSize () const
Definition at line 74 of file ConfigConn.cpp.
{
         return writeBlockSize;
     }
References writeBlockSize.
getWriteTimeout()
const utils::Timeval & net::ConfigConn::getWriteTimeout () const
Definition at line 66 of file ConfigConn.cpp.
{
         return writeTimeout;
     }
References writeTimeout.
Member Data Documentation
connectionSc
CLI::App* net::ConfigConn::connectionSc = nullptr private
Definition at line 53 of file ConfigConn.h.
Referenced by ConfigConn().
name
std::string net::ConfigConn::name private
Definition at line 60 of file ConfigConn.h.
readBlockSize
std::size_t net::ConfigConn::readBlockSize private
Definition at line 65 of file ConfigConn.h.
Referenced by ConfigConn(), and getReadBlockSize().
readBlockSizeOpt
CLI::Option* net::ConfigConn::readBlockSizeOpt = nullptr private
Definition at line 56 of file ConfigConn.h.
Referenced by ConfigConn().
readTimeout
utils::Timeval net::ConfigConn::readTimeout private
Definition at line 62 of file ConfigConn.h.
Referenced by ConfigConn(), and getReadTimeout().
readTimeoutOpt
CLI::Option* net::ConfigConn::readTimeoutOpt = nullptr private
Definition at line 54 of file ConfigConn.h.
Referenced by ConfigConn().
terminateTimeout
utils::Timeval net::ConfigConn::terminateTimeout private
Definition at line 68 of file ConfigConn.h.
Referenced by ConfigConn(), and getTerminateTimeout().
terminateTimeoutOpt
CLI::Option* net::ConfigConn::terminateTimeoutOpt = nullptr private
Definition at line 58 of file ConfigConn.h.
Referenced by ConfigConn().
writeBlockSize
std::size_t net::ConfigConn::writeBlockSize private
Definition at line 66 of file ConfigConn.h.
Referenced by ConfigConn(), and getWriteBlockSize().
writeBlockSizeOpt
CLI::Option* net::ConfigConn::writeBlockSizeOpt = nullptr private
Definition at line 57 of file ConfigConn.h.
Referenced by ConfigConn().
writeTimeout
utils::Timeval net::ConfigConn::writeTimeout private
Definition at line 63 of file ConfigConn.h.
Referenced by ConfigConn(), and getWriteTimeout().
writeTimeoutOpt
CLI::Option* net::ConfigConn::writeTimeoutOpt = nullptr private
Definition at line 55 of file ConfigConn.h.
Referenced by ConfigConn().
The documentation for this class was generated from the following files:
net/ConfigConn.h
net/ConfigConn.cpp