snode.c: core::EventDispatcher Class Reference
core::EventDispatcher Class Reference
#include <EventDispatcher.h>
Classes
class DescriptorEventReceiverList
class FdSet
Public Member Functions
EventDispatcher ()=default
void enable (EventReceiver *eventReceiver, int fd)
void disable (EventReceiver *eventReceiver, int fd)
void suspend (EventReceiver *eventReceiver, int fd)
void resume (EventReceiver *eventReceiver, int fd)
unsigned long getEventCounter () const
Private Member Functions
EventDispatcher (const EventDispatcher &)=delete
EventDispatcher & operator= (const EventDispatcher &)=delete
int getMaxFd () const
fd_set & getFdSet ()
struct timeval dispatchActiveEvents (struct timeval currentTime)
struct timeval observeEnabledEvents ()
void unobserveDisabledEvents ()
void releaseUnobservedEvents ()
void disableObservedEvents ()
Private Attributes
std::map< int, DescriptorEventReceiverList > enabledEventReceiver
std::map< int, DescriptorEventReceiverList > observedEventReceiver
std::map< int, DescriptorEventReceiverList > disabledEventReceiver
DescriptorEventReceiverList unobservedEventReceiver
FdSet fdSet
unsigned long eventCounter = 0
Friends
class EventLoop
Detailed Description
Definition at line 36 of file EventDispatcher.h.
Constructor & Destructor Documentation
EventDispatcher() [1/2]
core::EventDispatcher::EventDispatcher (const EventDispatcher &) private delete
EventDispatcher() [2/2]
core::EventDispatcher::EventDispatcher () default
Member Function Documentation
disable()
void core::EventDispatcher::disable (EventReceiver * eventReceiver, int fd)
Definition at line 85 of file EventDispatcher.cpp.
{
         if (enabledEventReceiver[fd].contains(eventReceiver)) {
             // same tick as enable
             enabledEventReceiver[fd].remove(eventReceiver);
             eventReceiver->disabled();
             if (eventReceiver->observationCounter == 0) {
                 unobservedEventReceiver.push_back(eventReceiver);
             }
         } else if (eventReceiver->isEnabled() &&
                    (!disabledEventReceiver.contains(fd) || !disabledEventReceiver[fd].contains(eventReceiver))) {
             // next tick as enable
             disabledEventReceiver[fd].push_back(eventReceiver);
         } else {
             LOG(WARNING) << "EventReceiver double disable";
         }
     }
References core::EventReceiver::disabled(), disabledEventReceiver, enabledEventReceiver, core::EventReceiver::isEnabled(), core::ObservationCounter::observationCounter, and unobservedEventReceiver.
Referenced by core::EventReceiver::disable().
disableObservedEvents()
void core::EventDispatcher::disableObservedEvents () private
Definition at line 223 of file EventDispatcher.cpp.
{
         for (const auto& [fd, eventReceivers] : observedEventReceiver) {
             for (EventReceiver* eventReceiver : eventReceivers) {
                 disabledEventReceiver[fd].push_back(eventReceiver);
             }
         }
     }
References disabledEventReceiver, and observedEventReceiver.
Referenced by core::EventLoop::_free().
dispatchActiveEvents()
struct timeval core::EventDispatcher::dispatchActiveEvents (struct timeval currentTime) private
Definition at line 138 of file EventDispatcher.cpp.
{
         struct timeval nextInactivityTimeout {
             LONG_MAX, 0
         };
         for (const auto& [fd, eventReceivers] : observedEventReceiver) {
             EventReceiver* eventReceiver = eventReceivers.front();
             struct timeval maxInactivity = eventReceiver->getTimeout();
             if (fdSet.isSet(fd) || (eventReceiver->continueImmediately())) {
                 eventCounter++;
                 eventReceiver->dispatchEvent();
                 eventReceiver->triggered(currentTime);
                 if (!eventReceiver->isSuspended()) {
                     if (eventReceiver->continueImmediately()) {
                         nextInactivityTimeout = {0, 0};
                     } else {
                         nextInactivityTimeout = std::min(nextInactivityTimeout, maxInactivity);
                     }
                 }
             } else {
                 struct timeval inactivity = currentTime - eventReceiver->getLastTriggered();
                 if (inactivity >= maxInactivity) {
                     eventReceiver->timeoutEvent();
                 } else {
                     nextInactivityTimeout = std::min(maxInactivity - inactivity, nextInactivityTimeout);
                 }
             }
         }
         return nextInactivityTimeout;
     }
References fdSet, and core::EventDispatcher::FdSet::get().
Referenced by core::EventLoop::_tick().
enable()
void core::EventDispatcher::enable (EventReceiver * eventReceiver, int fd)
Definition at line 68 of file EventDispatcher.cpp.
{
         if (disabledEventReceiver[fd].contains(eventReceiver)) {
             // same tick as disable
             disabledEventReceiver[fd].remove(eventReceiver);
         } else if (!eventReceiver->isEnabled() &&
                    (!enabledEventReceiver.contains(fd) || !enabledEventReceiver[fd].contains(eventReceiver))) {
             // next tick as disable
             enabledEventReceiver[fd].push_back(eventReceiver);
             eventReceiver->enabled();
             if (unobservedEventReceiver.contains(eventReceiver)) {
                 unobservedEventReceiver.remove(eventReceiver);
             }
         } else {
             LOG(WARNING) << "EventReceiver double enable";
         }
     }
References core::EventDispatcher::DescriptorEventReceiverList::contains(), disabledEventReceiver, core::EventReceiver::enabled(), enabledEventReceiver, core::EventReceiver::isEnabled(), and unobservedEventReceiver.
Referenced by core::EventReceiver::enable().
getEventCounter()
unsigned long core::EventDispatcher::getEventCounter () const
Definition at line 124 of file EventDispatcher.cpp.
{
         return eventCounter;
     }
References eventCounter.
Referenced by core::EventLoop::getEventCounter().
getFdSet()
fd_set & core::EventDispatcher::getFdSet () private
Definition at line 138 of file EventDispatcher.cpp.
{
         return fdSet.get();
     }
Referenced by core::EventLoop::_tick().
getMaxFd()
int core::EventDispatcher::getMaxFd () const private
Definition at line 128 of file EventDispatcher.cpp.
{
         int maxFd = -1;
         if (!observedEventReceiver.empty()) {
             maxFd = observedEventReceiver.rbegin()->first;
         }
         return maxFd;
     }
References observedEventReceiver.
Referenced by core::EventLoop::_tick().
observeEnabledEvents()
struct timeval core::EventDispatcher::observeEnabledEvents () private
Definition at line 138 of file EventDispatcher.cpp.
{
         struct timeval nextTimeout = {LONG_MAX, 0};
         for (const auto& [fd, eventReceivers] : enabledEventReceiver) {
             for (EventReceiver* eventReceiver : eventReceivers) {
                 observedEventReceiver[fd].push_front(eventReceiver);
                 if (!eventReceiver->isSuspended()) {
                     fdSet.set(fd);
                     nextTimeout = std::min(nextTimeout, eventReceiver->getTimeout());
                 } else {
                     fdSet.clr(fd);
                 }
             }
         }
         enabledEventReceiver.clear();
         return nextTimeout;
     }
Referenced by core::EventLoop::_free(), and core::EventLoop::_tick().
operator=()
EventDispatcher& core::EventDispatcher::operator= (const EventDispatcher &) private delete
releaseUnobservedEvents()
void core::EventDispatcher::releaseUnobservedEvents () private
Definition at line 216 of file EventDispatcher.cpp.
{
         for (EventReceiver* eventReceiver : unobservedEventReceiver) {
             eventReceiver->unobservedEvent();
         }
         unobservedEventReceiver.clear();
     }
References unobservedEventReceiver.
Referenced by core::EventLoop::_free(), and core::EventLoop::_tick().
resume()
void core::EventDispatcher::resume (EventReceiver * eventReceiver, int fd)
Definition at line 113 of file EventDispatcher.cpp.
{
         if (eventReceiver->isSuspended()) {
             eventReceiver->resumed();
             if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                 fdSet.set(fd);
             }
         } else {
             LOG(WARNING) << "EventReceiver double resume";
         }
     }
References fdSet, core::EventReceiver::isSuspended(), observedEventReceiver, core::EventReceiver::resumed(), and core::EventDispatcher::FdSet::set().
Referenced by core::EventReceiver::resume().
suspend()
void core::EventDispatcher::suspend (EventReceiver * eventReceiver, int fd)
Definition at line 102 of file EventDispatcher.cpp.
{
         if (!eventReceiver->isSuspended()) {
             eventReceiver->suspended();
             if (observedEventReceiver.contains(fd) && observedEventReceiver[fd].front() == eventReceiver) {
                 fdSet.clr(fd);
             }
         } else {
             LOG(WARNING) << "EventReceiver double suspend";
         }
     }
References core::EventDispatcher::FdSet::clr(), fdSet, core::EventReceiver::isSuspended(), observedEventReceiver, and core::EventReceiver::suspended().
Referenced by core::EventReceiver::suspend().
unobserveDisabledEvents()
void core::EventDispatcher::unobserveDisabledEvents () private
Definition at line 193 of file EventDispatcher.cpp.
{
         for (const auto& [fd, eventReceivers] : disabledEventReceiver) {
             for (EventReceiver* eventReceiver : eventReceivers) {
                 observedEventReceiver[fd].remove(eventReceiver);
                 if (observedEventReceiver[fd].empty() || observedEventReceiver[fd].front()->isSuspended()) {
                     if (observedEventReceiver[fd].empty()) {
                         observedEventReceiver.erase(fd);
                     }
                     fdSet.clr(fd);
                 } else {
                     fdSet.set(fd);
                     observedEventReceiver[fd].front()->triggered();
                 }
                 eventReceiver->disabled();
                 if (eventReceiver->observationCounter == 0) {
                     unobservedEventReceiver.push_back(eventReceiver);
                 }
                 eventReceiver->fd = -1;
             }
         }
         disabledEventReceiver.clear();
     }
References core::EventDispatcher::FdSet::clr(), disabledEventReceiver, fdSet, observedEventReceiver, core::EventDispatcher::FdSet::set(), and unobservedEventReceiver.
Referenced by core::EventLoop::_free(), and core::EventLoop::_tick().
Friends And Related Function Documentation
EventLoop
friend class EventLoop friend
Definition at line 95 of file EventDispatcher.h.
Member Data Documentation
disabledEventReceiver
std::map<int, DescriptorEventReceiverList> core::EventDispatcher::disabledEventReceiver private
Definition at line 88 of file EventDispatcher.h.
Referenced by disable(), disableObservedEvents(), enable(), and unobserveDisabledEvents().
enabledEventReceiver
std::map<int, DescriptorEventReceiverList> core::EventDispatcher::enabledEventReceiver private
Definition at line 86 of file EventDispatcher.h.
Referenced by disable(), and enable().
eventCounter
unsigned long core::EventDispatcher::eventCounter = 0 private
Definition at line 93 of file EventDispatcher.h.
Referenced by getEventCounter().
fdSet
FdSet core::EventDispatcher::fdSet private
Definition at line 91 of file EventDispatcher.h.
Referenced by dispatchActiveEvents(), resume(), suspend(), and unobserveDisabledEvents().
observedEventReceiver
std::map<int, DescriptorEventReceiverList> core::EventDispatcher::observedEventReceiver private
Definition at line 87 of file EventDispatcher.h.
Referenced by disableObservedEvents(), getMaxFd(), resume(), suspend(), and unobserveDisabledEvents().
unobservedEventReceiver
DescriptorEventReceiverList core::EventDispatcher::unobservedEventReceiver private
Definition at line 89 of file EventDispatcher.h.
Referenced by disable(), enable(), releaseUnobservedEvents(), and unobserveDisabledEvents().
The documentation for this class was generated from the following files:
core/EventDispatcher.h
core/EventDispatcher.cpp