snode.c: core::select::DescriptorEventPublisher Class Reference
core::select::DescriptorEventPublisher Class Reference
#include <DescriptorEventPublisher.h>
Public Member Functions
DescriptorEventPublisher (const std::string &name, FdSet &fdSet)
Public Member Functions inherited from core::DescriptorEventPublisher
virtual ~DescriptorEventPublisher ()=default
void publish (Event *event)
void enable (DescriptorEventReceiver *descriptorEventReceiver)
void disable (DescriptorEventReceiver *descriptorEventReceiver)
void suspend (DescriptorEventReceiver *descriptorEventReceiver)
void resume (DescriptorEventReceiver *descriptorEventReceiver)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void unobserveDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int getMaxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void stop ()
const std::string & getName () const
Private Member Functions
DescriptorEventPublisher (const DescriptorEventPublisher &)=delete
DescriptorEventPublisher & operator= (const DescriptorEventPublisher &)=delete
void muxAdd (core::DescriptorEventReceiver *eventReceiver) override
void muxDel (int fd) override
void muxOn (core::DescriptorEventReceiver *eventReceiver) override
void muxOff (core::DescriptorEventReceiver *eventReceiver) override
int publishActiveEvents () override
Private Attributes
FdSet & fdSet
Additional Inherited Members
Protected Member Functions inherited from core::DescriptorEventPublisher
DescriptorEventPublisher ()=delete
DescriptorEventPublisher (const std::string &name)
Protected Attributes inherited from core::DescriptorEventPublisher
std::map< int, std::list< DescriptorEventReceiver * > > observedEventReceivers
unsigned long eventCounter = 0
bool observedEventReceiversDirty = false
std::string name
Detailed Description
Definition at line 51 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
DescriptorEventPublisher() [1/2]
core::select::DescriptorEventPublisher::DescriptorEventPublisher (const DescriptorEventPublisher &) private delete
DescriptorEventPublisher() [2/2]
core::select::DescriptorEventPublisher::DescriptorEventPublisher (const std::string & name, FdSet & fdSet) explicit
Definition at line 58 of file DescriptorEventPublisher.cpp.
         : core::DescriptorEventPublisher(name)
         , fdSet(fdSet) {
     }
Member Function Documentation
muxAdd()
void core::select::DescriptorEventPublisher::muxAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 63 of file DescriptorEventPublisher.cpp.
{
         fdSet.set(eventReceiver->getRegisteredFd());
     }
References fdSet, core::DescriptorEventReceiver::getRegisteredFd(), and core::select::FdSet::set().
muxDel()
void core::select::DescriptorEventPublisher::muxDel (int fd) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 67 of file DescriptorEventPublisher.cpp.
{
         fdSet.clr(fd);
     }
References core::select::FdSet::clr(), and fdSet.
muxOff()
void core::select::DescriptorEventPublisher::muxOff (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 75 of file DescriptorEventPublisher.cpp.
{
         fdSet.clr(eventReceiver->getRegisteredFd());
     }
References core::select::FdSet::clr(), fdSet, and core::DescriptorEventReceiver::getRegisteredFd().
muxOn()
void core::select::DescriptorEventPublisher::muxOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 71 of file DescriptorEventPublisher.cpp.
{
         fdSet.set(eventReceiver->getRegisteredFd());
     }
References fdSet, core::DescriptorEventReceiver::getRegisteredFd(), and core::select::FdSet::set().
operator=()
DescriptorEventPublisher& core::select::DescriptorEventPublisher::operator= (const DescriptorEventPublisher &) private delete
publishActiveEvents()
int core::select::DescriptorEventPublisher::publishActiveEvents () override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 79 of file DescriptorEventPublisher.cpp.
{
         int count = 0;
         for (const auto& [fd, eventReceivers] : observedEventReceivers) {
             if (fdSet.isSet(fd)) {
                 core::DescriptorEventReceiver* eventReceiver = eventReceivers.front();
                 eventCounter++;
                 eventReceiver->publish();
                 count++;
             }
         }
         return count;
     }
References core::DescriptorEventPublisher::eventCounter, fdSet, core::select::FdSet::isSet(), core::DescriptorEventPublisher::observedEventReceivers, and core::EventReceiver::publish().
Member Data Documentation
fdSet
FdSet& core::select::DescriptorEventPublisher::fdSet private
Definition at line 66 of file DescriptorEventPublisher.h.
Referenced by muxAdd(), muxDel(), muxOff(), muxOn(), and publishActiveEvents().
The documentation for this class was generated from the following files:
core/multiplexer/select/DescriptorEventPublisher.h
core/multiplexer/select/DescriptorEventPublisher.cpp