snode.c: database::mariadb::MariaDBCommandStartEvent Class Reference
database::mariadb::MariaDBCommandStartEvent Class Reference
#include <MariaDBConnection.h>
Public Member Functions
MariaDBCommandStartEvent (const std::string &name, MariaDBConnection *mariaDBConnection)
~MariaDBCommandStartEvent () override
void publish ()
Private Member Functions
void event (const utils::Timeval &currentTime) override
Private Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish ()
void unPublish ()
const std::string & getName ()
Private Attributes
MariaDBConnection * mariaDBConnection = nullptr
Private Attributes inherited from core::EventReceiver
Event _event
Detailed Description
Definition at line 45 of file MariaDBConnection.h.
Constructor & Destructor Documentation
MariaDBCommandStartEvent()
database::mariadb::MariaDBCommandStartEvent::MariaDBCommandStartEvent (const std::string & name, MariaDBConnection * mariaDBConnection)
Definition at line 247 of file MariaDBConnection.cpp.
         : core::EventReceiver(name)
         , mariaDBConnection(mariaDBConnection) {
     }
~MariaDBCommandStartEvent()
database::mariadb::MariaDBCommandStartEvent::~MariaDBCommandStartEvent () override
Definition at line 252 of file MariaDBConnection.cpp.
{
         core::EventReceiver::unPublish();
     }
References core::EventReceiver::unPublish().
Member Function Documentation
event()
void database::mariadb::MariaDBCommandStartEvent::event (const utils::Timeval & currentTime) override private virtual
Implements core::EventReceiver.
Definition at line 260 of file MariaDBConnection.cpp.
{
         mariaDBConnection->commandStart(currentTime);
     }
References database::mariadb::MariaDBConnection::commandStart(), and mariaDBConnection.
publish()
void database::mariadb::MariaDBCommandStartEvent::publish ()
Definition at line 256 of file MariaDBConnection.cpp.
{
         core::EventReceiver::publish();
     }
References core::EventReceiver::publish().
Referenced by database::mariadb::MariaDBConnection::checkStatus(), and database::mariadb::MariaDBConnection::execute_async().
Member Data Documentation
mariaDBConnection
MariaDBConnection* database::mariadb::MariaDBCommandStartEvent::mariaDBConnection = nullptr private
Definition at line 57 of file MariaDBConnection.h.
Referenced by event().
The documentation for this class was generated from the following files:
database/mariadb/MariaDBConnection.h
database/mariadb/MariaDBConnection.cpp