snode.c: CLI::RequiredError Class Reference
CLI::RequiredError Class Reference
Errors
Thrown when a required option is missing.
#include <CLI11.hpp>
Public Member Functions
RequiredError (std::string msg, ExitCodes exit_code)
RequiredError (std::string msg, int exit_code)
RequiredError (std::string name)
Public Member Functions inherited from CLI::ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from CLI::Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static RequiredError Subcommand (std::size_t min_subcom)
static RequiredError Option (std::size_t min_option, std::size_t max_option, std::size_t used, const std::string &option_list)
Protected Member Functions
RequiredError (std::string ename, std::string msg, int exit_code)
RequiredError (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from CLI::ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when a required option is missing.
Definition at line 783 of file CLI11.hpp.
Constructor & Destructor Documentation
RequiredError() [1/5]
CLI::RequiredError::RequiredError (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 784 of file CLI11.hpp.
Referenced by Option(), and Subcommand().
RequiredError() [2/5]
CLI::RequiredError::RequiredError (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 784 of file CLI11.hpp.
RequiredError() [3/5]
CLI::RequiredError::RequiredError (std::string msg, ExitCodes exit_code) inline
Definition at line 784 of file CLI11.hpp.
RequiredError() [4/5]
CLI::RequiredError::RequiredError (std::string msg, int exit_code) inline
Definition at line 784 of file CLI11.hpp.
RequiredError() [5/5]
CLI::RequiredError::RequiredError (std::string name) inline explicit
Definition at line 785 of file CLI11.hpp.
             : RequiredError(name + " is required", ExitCodes::RequiredError) {
         }
Member Function Documentation
Option()
static RequiredError CLI::RequiredError::Option (std::size_t min_option, std::size_t max_option, std::size_t used, const std::string & option_list) inline static
Definition at line 794 of file CLI11.hpp.
{
             if ((min_option == 1) && (max_option == 1) && (used == 0))
                 return RequiredError("Exactly 1 option from [" + option_list + "]");
             if ((min_option == 1) && (max_option == 1) && (used > 1)) {
                 return RequiredError("Exactly 1 option from [" + option_list + "] is required and " + std::to_string(used) + " were given",
                                      ExitCodes::RequiredError);
             }
             if ((min_option == 1) && (used == 0))
                 return RequiredError("At least 1 option from [" + option_list + "]");
             if (used < min_option) {
                 return RequiredError("Requires at least " + std::to_string(min_option) + " options used and only " + std::to_string(used) +
                                          "were given from [" + option_list + "]",
                                      ExitCodes::RequiredError);
             }
             if (max_option == 1)
                 return RequiredError("Requires at most 1 options be given from [" + option_list + "]", ExitCodes::RequiredError);
             return RequiredError("Requires at most " + std::to_string(max_option) + " options be used and " + std::to_string(used) +
                                      "were given from [" + option_list + "]",
                                  ExitCodes::RequiredError);
         }
References CLI::RequiredError, RequiredError(), and CLI::detail::to_string().
Referenced by CLI::App::_process_requirements().
Subcommand()
static RequiredError CLI::RequiredError::Subcommand (std::size_t min_subcom) inline static
Definition at line 788 of file CLI11.hpp.
{
             if (min_subcom == 1) {
                 return RequiredError("A subcommand");
             }
             return RequiredError("Requires at least " + std::to_string(min_subcom) + " subcommands", ExitCodes::RequiredError);
         }
References CLI::RequiredError, RequiredError(), and CLI::detail::to_string().
Referenced by CLI::App::_process_requirements().
The documentation for this class was generated from the following file:
utils/CLI11.hpp