snode.c: net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT > Class Template Reference
net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT > Class Template Reference
#include <SocketServer.h>
Public Types
using SocketAddress = typename ConcreteSocketServer< rfcomm::Socket, SocketContextFactoryT >::SocketAddress
Public Member Functions
void listen (uint8_t channel, int backlog, const std::function< void(int)> &onError)
void listen (const std::string &address, int backlog, const std::function< void(int)> &onError)
void listen (const std::string &address, uint8_t channel, int backlog, const std::function< void(int)> &onError)
Detailed Description
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketServer, typename SocketContextFactoryT>
class net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >
Definition at line 35 of file SocketServer.h.
Member Typedef Documentation
SocketAddress
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketServer, typename SocketContextFactoryT > using net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::SocketAddress = typename ConcreteSocketServer<rfcomm::Socket, SocketContextFactoryT>::SocketAddress
Definition at line 39 of file SocketServer.h.
Member Function Documentation
listen() [1/3]
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketServer, typename SocketContextFactoryT > void net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen (const std::string & address, int backlog, const std::function< void(int)> & onError) inline
Definition at line 47 of file SocketServer.h.
{
             listen(SocketAddress(address), backlog, onError);
         }
References net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen().
listen() [2/3]
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketServer, typename SocketContextFactoryT > void net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen (const std::string & address, uint8_t channel, int backlog, const std::function< void(int)> & onError) inline
Definition at line 51 of file SocketServer.h.
{
             listen(SocketAddress(address, channel), backlog, onError);
         }
References net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen().
listen() [3/3]
template<template< typename SocketT, typename SocketContextFactoryT > typename ConcreteSocketServer, typename SocketContextFactoryT > void net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen (uint8_t channel, int backlog, const std::function< void(int)> & onError) inline
Definition at line 43 of file SocketServer.h.
{
             listen(SocketAddress(channel), backlog, onError);
         }
Referenced by net::socket::bluetooth::rfcomm::SocketServer< ConcreteSocketServer, SocketContextFactoryT >::listen(), web::http::server::legacy::ServerRfComm< Request, Response >::listen(), and web::http::server::tls::ServerRfComm< Request, Response >::listen().
The documentation for this class was generated from the following file:
net/socket/bluetooth/rfcomm/SocketServer.h