snode.c: CLI::ConfigBase Class Reference
CLI::ConfigBase Class Reference
This converter works with INI/TOML files; to write INI files use ConfigINI.
#include <CLI11.hpp>
Public Member Functions
std::string to_config (const App *, bool default_also, bool write_description, std::string prefix) const override
Convert an app into a configuration.
std::vector< ConfigItem > from_config (std::istream &input) const override
Convert a configuration into an app.
ConfigBase * comment (char cchar)
Specify the configuration for comment characters.
ConfigBase * arrayBounds (char aStart, char aEnd)
Specify the start and end characters for an array.
ConfigBase * arrayDelimiter (char aSep)
Specify the delimiter character for an array.
ConfigBase * valueSeparator (char vSep)
Specify the delimiter between a name and value.
ConfigBase * quoteCharacter (char qString, char qChar)
Specify the quote characters used around strings and characters.
ConfigBase * maxLayers (uint8_t layers)
Specify the maximum number of parents.
ConfigBase * parentSeparator (char sep)
Specify the separator to use for parent layers.
std::string & sectionRef ()
get a reference to the configuration section
const std::string & section () const
get the section
ConfigBase * section (const std::string &sectionName)
specify a particular section of the configuration file to use
int16_t & indexRef ()
get a reference to the configuration index
int16_t index () const
get the section index
ConfigBase * index (int16_t sectionIndex)
specify a particular index in the section to use (-1) for all sections to use
Public Member Functions inherited from CLI::Config
virtual std::string to_flag (const ConfigItem &item) const
Get a flag value.
std::vector< ConfigItem > from_file (const std::string &name)
Parse a config file, throw an error (ParseError:ConfigParseError or FileError) on failure.
virtual ~Config ()=default
Virtual destructor.
Protected Attributes
char commentChar = '#'
the character used for comments
char arrayStart = '['
the character used to start an array '\0' is a default to not use
char arrayEnd = ']'
the character used to end an array '\0' is a default to not use
char arraySeparator = ','
the character used to separate elements in an array
char valueDelimiter = '='
the character used separate the name from the value
char stringQuote = '"'
the character to use around strings
char characterQuote = '\''
the character to use around single characters
uint8_t maximumLayers {255}
the maximum number of layers to allow
char parentSeparatorChar {'.'}
the separator used to separator parent layers
int16_t configIndex {-1}
Specify the configuration index to use for arrayed sections.
std::string configSection {}
Specify the configuration section that should be used.
Protected Attributes inherited from CLI::Config
std::vector< ConfigItem > items {}
Detailed Description
This converter works with INI/TOML files; to write INI files use ConfigINI.
Definition at line 2685 of file CLI11.hpp.
Member Function Documentation
arrayBounds()
ConfigBase* CLI::ConfigBase::arrayBounds (char aStart, char aEnd) inline
Specify the start and end characters for an array.
Definition at line 2720 of file CLI11.hpp.
{
             arrayStart = aStart;
             arrayEnd = aEnd;
             return this;
         }
arrayDelimiter()
ConfigBase* CLI::ConfigBase::arrayDelimiter (char aSep) inline
Specify the delimiter character for an array.
Definition at line 2726 of file CLI11.hpp.
{
             arraySeparator = aSep;
             return this;
         }
comment()
ConfigBase* CLI::ConfigBase::comment (char cchar) inline
Specify the configuration for comment characters.
Definition at line 2715 of file CLI11.hpp.
{
             commentChar = cchar;
             return this;
         }
from_config()
std::vector< ConfigItem > CLI::ConfigBase::from_config (std::istream &) const inline override virtual
Convert a configuration into an app.
Implements CLI::Config.
Definition at line 9041 of file CLI11.hpp.
{
         std::string line;
         std::string currentSection = "default";
         std::string previousSection = "default";
         std::vector<ConfigItem> output;
         bool isDefaultArray = (arrayStart == '[' && arrayEnd == ']' && arraySeparator == ',');
         bool isINIArray = (arrayStart == '\0' || arrayStart == ' ') && arrayStart == arrayEnd;
         bool inSection{false};
         char aStart = (isINIArray) ? '[' : arrayStart;
         char aEnd = (isINIArray) ? ']' : arrayEnd;
         char aSep = (isINIArray && arraySeparator == ' ') ? ',' : arraySeparator;
         int currentSectionIndex{0};
         while (getline(input, line)) {
             std::vector<std::string> items_buffer;
             std::string name;
             detail::trim(line);
             std::size_t len = line.length();
             // lines have to be at least 3 characters to have any meaning to CLI just skip the rest
             if (len < 3) {
                 continue;
             }
             if (line.front() == '[' && line.back() == ']') {
                 if (currentSection != "default") {
                     // insert a section end which is just an empty items_buffer
                     output.emplace_back();
                     output.back().parents = detail::generate_parents(currentSection, name, parentSeparatorChar);
                     output.back().name = "--";
                 }
                 currentSection = line.substr(1, len - 2);
                 // deal with double brackets for TOML
                 if (currentSection.size() > 1 && currentSection.front() == '[' && currentSection.back() == ']') {
                     currentSection = currentSection.substr(1, currentSection.size() - 2);
                 }
                 if (detail::to_lower(currentSection) == "default") {
                     currentSection = "default";
                 } else {
                     detail::checkParentSegments(output, currentSection, parentSeparatorChar);
                 }
                 inSection = false;
                 if (currentSection == previousSection) {
                     ++currentSectionIndex;
                 } else {
                     currentSectionIndex = 0;
                     previousSection = currentSection;
                 }
                 continue;
             }
             // comment lines
             if (line.front() == ';' || line.front() == '#' || line.front() == commentChar) {
                 continue;
             }
             // Find = in string, split and recombine
             auto pos = line.find(valueDelimiter);
             if (pos != std::string::npos) {
                 name = detail::trim_copy(line.substr(0, pos));
                 std::string item = detail::trim_copy(line.substr(pos + 1));
                 auto cloc = item.find(commentChar);
                 if (cloc != std::string::npos) {
                     item.erase(cloc, std::string::npos);
                     detail::trim(item);
                 }
                 if (item.size() > 1 && item.front() == aStart) {
                     for (std::string multiline; item.back() != aEnd && std::getline(input, multiline);) {
                         detail::trim(multiline);
                         item += multiline;
                     }
                     items_buffer = detail::split_up(item.substr(1, item.length() - 2), aSep);
                 } else if ((isDefaultArray || isINIArray) && item.find_first_of(aSep) != std::string::npos) {
                     items_buffer = detail::split_up(item, aSep);
                 } else if ((isDefaultArray || isINIArray) && item.find_first_of(' ') != std::string::npos) {
                     items_buffer = detail::split_up(item);
                 } else {
                     items_buffer = {item};
                 }
             } else {
                 name = detail::trim_copy(line);
                 auto cloc = name.find(commentChar);
                 if (cloc != std::string::npos) {
                     name.erase(cloc, std::string::npos);
                     detail::trim(name);
                 }
                 items_buffer = {"true"};
             }
             if (name.find(parentSeparatorChar) == std::string::npos) {
                 detail::remove_quotes(name);
             }
             // clean up quotes on the items
             for (auto& it : items_buffer) {
                 detail::remove_quotes(it);
             }
             std::vector<std::string> parents = detail::generate_parents(currentSection, name, parentSeparatorChar);
             if (parents.size() > maximumLayers) {
                 continue;
             }
             if (!configSection.empty() && !inSection) {
                 if (parents.empty() || parents.front() != configSection) {
                     continue;
                 }
                 if (configIndex >= 0 && currentSectionIndex != configIndex) {
                     continue;
                 }
                 parents.erase(parents.begin());
                 inSection = true;
             }
             if (!output.empty() && name == output.back().name && parents == output.back().parents) {
                 output.back().inputs.insert(output.back().inputs.end(), items_buffer.begin(), items_buffer.end());
             } else {
                 output.emplace_back();
                 output.back().parents = std::move(parents);
                 output.back().name = std::move(name);
                 output.back().inputs = std::move(items_buffer);
             }
         }
         if (currentSection != "default") {
             // insert a section end which is just an empty items_buffer
             std::string ename;
             output.emplace_back();
             output.back().parents = detail::generate_parents(currentSection, ename, parentSeparatorChar);
             output.back().name = "--";
             while (output.back().parents.size() > 1) {
                 output.push_back(output.back());
                 output.back().parents.pop_back();
             }
         }
         return output;
     }
References CLI::detail::checkParentSegments(), CLI::detail::generate_parents(), CLI::detail::remove_quotes(), CLI::detail::split_up(), CLI::detail::to_lower(), CLI::detail::trim(), and CLI::detail::trim_copy().
index() [1/2]
int16_t CLI::ConfigBase::index () const inline
get the section index
Definition at line 2770 of file CLI11.hpp.
{
             return configIndex;
         }
index() [2/2]
ConfigBase* CLI::ConfigBase::index (int16_t sectionIndex) inline
specify a particular index in the section to use (-1) for all sections to use
Definition at line 2774 of file CLI11.hpp.
{
             configIndex = sectionIndex;
             return this;
         }
indexRef()
int16_t& CLI::ConfigBase::indexRef () inline
get a reference to the configuration index
Definition at line 2766 of file CLI11.hpp.
{
             return configIndex;
         }
maxLayers()
ConfigBase* CLI::ConfigBase::maxLayers (uint8_t layers) inline
Specify the maximum number of parents.
Definition at line 2742 of file CLI11.hpp.
{
             maximumLayers = layers;
             return this;
         }
parentSeparator()
ConfigBase* CLI::ConfigBase::parentSeparator (char sep) inline
Specify the separator to use for parent layers.
Definition at line 2747 of file CLI11.hpp.
{
             parentSeparatorChar = sep;
             return this;
         }
quoteCharacter()
ConfigBase* CLI::ConfigBase::quoteCharacter (char qString, char qChar) inline
Specify the quote characters used around strings and characters.
Definition at line 2736 of file CLI11.hpp.
{
             stringQuote = qString;
             characterQuote = qChar;
             return this;
         }
section() [1/2]
const std::string& CLI::ConfigBase::section () const inline
get the section
Definition at line 2756 of file CLI11.hpp.
{
             return configSection;
         }
section() [2/2]
ConfigBase* CLI::ConfigBase::section (const std::string & sectionName) inline
specify a particular section of the configuration file to use
Definition at line 2760 of file CLI11.hpp.
{
             configSection = sectionName;
             return this;
         }
sectionRef()
std::string& CLI::ConfigBase::sectionRef () inline
get a reference to the configuration section
Definition at line 2752 of file CLI11.hpp.
{
             return configSection;
         }
to_config()
std::string CLI::ConfigBase::to_config (const App * , bool , bool , std::string) const inline override virtual
Convert an app into a configuration.
Implements CLI::Config.
Definition at line 9173 of file CLI11.hpp.
{
         std::stringstream out;
         std::string commentLead;
         commentLead.push_back(commentChar);
         commentLead.push_back(' ');
         std::vector<std::string> groups = app->get_groups();
         bool defaultUsed = false;
         groups.insert(groups.begin(), std::string("Options"));
         if (write_description && (app->get_configurable() || app->get_parent() == nullptr || app->get_name().empty())) {
             out << commentLead << detail::fix_newlines(commentLead, app->get_description()) << '\n';
         }
         for (auto& group : groups) {
             if (group == "Options" || group.empty()) {
                 if (defaultUsed) {
                     continue;
                 }
                 defaultUsed = true;
             }
             if (write_description && group != "Options" && !group.empty()) {
                 out << '\n' << commentLead << group << " Options\n";
             }
             for (const Option* opt : app->get_options({})) {
                 // Only process options that are configurable
                 if (opt->get_configurable()) {
                     if (opt->get_group() != group) {
                         if (!(group == "Options" && opt->get_group().empty())) {
                             continue;
                         }
                     }
                     std::string name = prefix + opt->get_single_name();
                     std::string value =
                         detail::ini_join(opt->reduced_results(), arraySeparator, arrayStart, arrayEnd, stringQuote, characterQuote);
                     if (value.empty() && default_also) {
                         if (!opt->get_default_str().empty()) {
                             value = detail::convert_arg_for_ini(opt->get_default_str(), stringQuote, characterQuote);
                         } else if (opt->get_expected_min() == 0) {
                             value = "false";
                         } else if (opt->get_run_callback_for_default()) {
                             value = "\"\""; // empty string default value
                         }
                     }
                     if (!value.empty()) {
                         if (write_description && opt->has_description()) {
                             out << '\n';
                             out << commentLead << detail::fix_newlines(commentLead, opt->get_description()) << '\n';
                         }
                         out << name << valueDelimiter << value << '\n';
                     }
                 }
             }
         }
         auto subcommands = app->get_subcommands({});
         for (const App* subcom : subcommands) {
             if (subcom->get_name().empty()) {
                 if (write_description && !subcom->get_group().empty()) {
                     out << '\n' << commentLead << subcom->get_group() << " Options\n";
                 }
                 out << to_config(subcom, default_also, write_description, prefix);
             }
         }
         for (const App* subcom : subcommands) {
             if (!subcom->get_name().empty()) {
                 if (subcom->get_configurable() && app->got_subcommand(subcom)) {
                     if (!prefix.empty() || app->get_parent() == nullptr) {
                         out << '[' << prefix << subcom->get_name() << "]\n";
                     } else {
                         std::string subname = app->get_name() + parentSeparatorChar + subcom->get_name();
                         auto p = app->get_parent();
                         while (p->get_parent() != nullptr) {
                             subname = p->get_name() + parentSeparatorChar + subname;
                             p = p->get_parent();
                         }
                         out << '[' << subname << "]\n";
                     }
                     out << to_config(subcom, default_also, write_description, "");
                 } else {
                     out << to_config(subcom, default_also, write_description, prefix + subcom->get_name() + parentSeparatorChar);
                 }
             }
         }
         return out.str();
     }
References CLI::detail::convert_arg_for_ini(), CLI::detail::fix_newlines(), CLI::OptionBase< CRTP >::get_configurable(), CLI::App::get_configurable(), CLI::Option::get_default_str(), CLI::Option::get_description(), CLI::App::get_description(), CLI::Option::get_expected_min(), CLI::OptionBase< CRTP >::get_group(), CLI::App::get_groups(), CLI::App::get_name(), CLI::App::get_options(), CLI::App::get_parent(), CLI::Option::get_run_callback_for_default(), CLI::Option::get_single_name(), CLI::App::get_subcommands(), CLI::App::got_subcommand(), CLI::Option::has_description(), CLI::detail::ini_join(), and CLI::Option::reduced_results().
valueSeparator()
ConfigBase* CLI::ConfigBase::valueSeparator (char vSep) inline
Specify the delimiter between a name and value.
Definition at line 2731 of file CLI11.hpp.
{
             valueDelimiter = vSep;
             return this;
         }
Member Data Documentation
arrayEnd
char CLI::ConfigBase::arrayEnd = ']' protected
the character used to end an array '\0' is a default to not use
Definition at line 2692 of file CLI11.hpp.
arraySeparator
char CLI::ConfigBase::arraySeparator = ',' protected
the character used to separate elements in an array
Definition at line 2694 of file CLI11.hpp.
arrayStart
char CLI::ConfigBase::arrayStart = '[' protected
the character used to start an array '\0' is a default to not use
Definition at line 2690 of file CLI11.hpp.
characterQuote
char CLI::ConfigBase::characterQuote = '\'' protected
the character to use around single characters
Definition at line 2700 of file CLI11.hpp.
commentChar
char CLI::ConfigBase::commentChar = '#' protected
the character used for comments
Definition at line 2688 of file CLI11.hpp.
configIndex
int16_t CLI::ConfigBase::configIndex {-1} protected
Specify the configuration index to use for arrayed sections.
Definition at line 2706 of file CLI11.hpp.
configSection
std::string CLI::ConfigBase::configSection {} protected
Specify the configuration section that should be used.
Definition at line 2708 of file CLI11.hpp.
maximumLayers
uint8_t CLI::ConfigBase::maximumLayers {255} protected
the maximum number of layers to allow
Definition at line 2702 of file CLI11.hpp.
parentSeparatorChar
char CLI::ConfigBase::parentSeparatorChar {'.'} protected
the separator used to separator parent layers
Definition at line 2704 of file CLI11.hpp.
stringQuote
char CLI::ConfigBase::stringQuote = '"' protected
the character to use around strings
Definition at line 2698 of file CLI11.hpp.
valueDelimiter
char CLI::ConfigBase::valueDelimiter = '=' protected
the character used separate the name from the value
Definition at line 2696 of file CLI11.hpp.
The documentation for this class was generated from the following file:
utils/CLI11.hpp