snode.c: core::timer::IntervalTimer Class Reference
core::timer::IntervalTimer Class Reference
#include <IntervalTimer.h>
Public Member Functions
IntervalTimer (const std::function< void(const void *, const std::function< void()> &stop)> &dispatcher, const utils::Timeval &timeout, const void *arg)
IntervalTimer (const std::function< void(const void *)> &dispatcher, const utils::Timeval &timeout, const void *arg)
~IntervalTimer () override=default
bool dispatch () override
Private Member Functions
IntervalTimer & operator= (const IntervalTimer &timer)=delete
void cancel () override
void unobservedEvent () override
Private Attributes
std::function< void(const void *, const std::function< void()> &)> dispatcherS = nullptr
std::function< void(const void *)> dispatcherC = nullptr
Additional Inherited Members
Static Public Member Functions inherited from core::timer::Timer
static IntervalTimer & intervalTimer (const std::function< void(const void *, const std::function< void()> &stop)> &dispatcher, const utils::Timeval &timeout, const void *arg)
static IntervalTimer & intervalTimer (const std::function< void(const void *)> &dispatcher, const utils::Timeval &timeout, const void *arg)
static SingleshotTimer & singleshotTimer (const std::function< void(const void *)> &dispatcher, const utils::Timeval &timeout, const void *arg)
Protected Member Functions inherited from core::timer::Timer
virtual ~Timer ()=default
void unobservedEvent () override
utils::Timeval getTimeout () const override
TimerEventReceiver (const TimerEventReceiver &)=delete
TimerEventReceiver (const utils::Timeval &delay, const void *arg)
Protected Member Functions inherited from core::TimerEventReceiver
void update ()
TimerEventReceiver (const TimerEventReceiver &)=delete
TimerEventReceiver & operator= (const TimerEventReceiver &)=delete
TimerEventReceiver (const utils::Timeval &delay, const void *arg)
Protected Attributes inherited from core::TimerEventReceiver
utils::Timeval absoluteTimeout
utils::Timeval delay
const void * arg
Detailed Description
Definition at line 32 of file IntervalTimer.h.
Constructor & Destructor Documentation
IntervalTimer() [1/2]
core::timer::IntervalTimer::IntervalTimer (const std::function< void(const void *, const std::function< void()> &stop)> & dispatcher, const utils::Timeval & timeout, const void * arg) inline
Definition at line 36 of file IntervalTimer.h.
             : Timer(timeout, arg)
             , dispatcherS(dispatcher) {
         }
IntervalTimer() [2/2]
core::timer::IntervalTimer::IntervalTimer (const std::function< void(const void *)> & dispatcher, const utils::Timeval & timeout, const void * arg) inline
Definition at line 43 of file IntervalTimer.h.
             : Timer(timeout, arg)
             , dispatcherC(dispatcher) {
         }
~IntervalTimer()
core::timer::IntervalTimer::~IntervalTimer () override default
Member Function Documentation
cancel()
void core::timer::IntervalTimer::cancel () inline override private virtual
Reimplemented from core::timer::Timer.
Definition at line 71 of file IntervalTimer.h.
{
             dispatcherS = nullptr;
             dispatcherC = nullptr;
             core::timer::Timer::cancel();
         }
References core::timer::Timer::cancel(), dispatcherC, and dispatcherS.
Referenced by dispatch().
dispatch()
bool core::timer::IntervalTimer::dispatch () inline override virtual
Implements core::TimerEventReceiver.
Definition at line 50 of file IntervalTimer.h.
{
             bool stop = false;
             if (dispatcherS) {
                 dispatcherS(arg, [&stop]() -> void {
                     stop = true;
                 });
                 if (stop) {
                     cancel();
                 } else {
                     update();
                 }
             } else if (dispatcherC) {
                 dispatcherC(arg);
                 update();
             }
             return !stop;
         }
References core::TimerEventReceiver::arg, cancel(), dispatcherC, dispatcherS, and core::TimerEventReceiver::update().
operator=()
IntervalTimer& core::timer::IntervalTimer::operator= (const IntervalTimer & timer) private delete
unobservedEvent()
void core::timer::IntervalTimer::unobservedEvent () inline override private virtual
Implements core::TimerEventReceiver.
Definition at line 77 of file IntervalTimer.h.
{
             core::timer::Timer::unobservedEvent();
         }
References core::timer::Timer::unobservedEvent().
Member Data Documentation
dispatcherC
std::function<void(const void*)> core::timer::IntervalTimer::dispatcherC = nullptr private
Definition at line 82 of file IntervalTimer.h.
Referenced by cancel(), and dispatch().
dispatcherS
std::function<void(const void*, const std::function<void()>&)> core::timer::IntervalTimer::dispatcherS = nullptr private
Definition at line 81 of file IntervalTimer.h.
Referenced by cancel(), and dispatch().
The documentation for this class was generated from the following file:
core/timer/IntervalTimer.h