snode.c: express::dispatcher::ApplicationDispatcher Class Reference
express::dispatcher::ApplicationDispatcher Class Reference
#include <ApplicationDispatcher.h>
Public Member Functions
ApplicationDispatcher (const std::function< void(express::Request &req, express::Response &res)> &lambda)
Public Member Functions inherited from express::Dispatcher
Dispatcher ()=default
virtual ~Dispatcher ()=default
bool dispatchNext (Controller &state, const std::string &parentMountPath)
Private Member Functions
bool dispatch (express::Controller &state, const std::string &parentMountPath, const express::MountPoint &mountPoint) override
Private Attributes
const std::function< void(express::Request &req, express::Response &res)> lambda
Additional Inherited Members
Protected Attributes inherited from express::Dispatcher
std::shared_ptr< Route > next = nullptr
Detailed Description
Definition at line 42 of file ApplicationDispatcher.h.
Constructor & Destructor Documentation
ApplicationDispatcher()
express::dispatcher::ApplicationDispatcher::ApplicationDispatcher (const std::function< void(express::Request &req, express::Response &res)> & lambda) explicit
Definition at line 32 of file ApplicationDispatcher.cpp.
         : lambda(lambda) {
     }
Member Function Documentation
dispatch()
bool express::dispatcher::ApplicationDispatcher::dispatch (express::Controller & state, const std::string & parentMountPath, const express::MountPoint & mountPoint) override private virtual
Implements express::Dispatcher.
Definition at line 36 of file ApplicationDispatcher.cpp.
{
         bool dispatched = false;
         if ((state.getFlags() & Controller::NEXT) == 0) {
             std::string absoluteMountPath = path_concat(parentMountPath, mountPoint.relativeMountPath);
             if ((state.getRequest()->path.rfind(absoluteMountPath, 0) == 0 && mountPoint.method == "use") ||
                 ((absoluteMountPath == state.getRequest()->path || checkForUrlMatch(absoluteMountPath, state.getRequest()->url)) &&
                  (state.getRequest()->method == mountPoint.method || mountPoint.method == "all"))) {
                 dispatched = true;
                 if (hasResult(absoluteMountPath)) {
                     setParams(absoluteMountPath, *state.getRequest());
                 }
                 lambda(*state.getRequest(), *state.getResponse());
             }
         }
         return dispatched;
     }
References express::dispatcher::checkForUrlMatch(), express::Controller::getFlags(), express::Controller::getRequest(), express::Controller::getResponse(), express::dispatcher::hasResult(), lambda, express::MountPoint::method, web::http::server::Request::method, express::Controller::NEXT, express::Request::path, express::dispatcher::path_concat(), express::MountPoint::relativeMountPath, express::dispatcher::setParams(), and web::http::server::Request::url.
Member Data Documentation
lambda
const std::function<void(express::Request& req, express::Response& res)> express::dispatcher::ApplicationDispatcher::lambda private
Definition at line 49 of file ApplicationDispatcher.h.
Referenced by dispatch().
The documentation for this class was generated from the following files:
express/dispatcher/ApplicationDispatcher.h
express/dispatcher/ApplicationDispatcher.cpp