snode.c: logger::Logger Class Reference
logger::Logger Class Reference
#include <Logger.h>
Public Types
enum Level {
INFO , DEBUG , WARNING , ERROR ,
FATAL
}
Static Public Member Functions
static void init (int argc, char *argv[])
static void setLogLevel (int level)
static void setVerboseLevel (unsigned short level)
static void logToFile (const std::string &logFile)
static void quiet ()
static void setCustomFormatSpec (const char *format, const el::FormatSpecifierValueResolver &resolver)
Static Protected Attributes
static el::Configurations conf
Private Member Functions
Logger ()=delete
~Logger ()=delete
Detailed Description
Definition at line 31 of file Logger.h.
Member Enumeration Documentation
Level
enum logger::Logger::Level
Enumerator
INFO
DEBUG
WARNING
ERROR
FATAL
Definition at line 36 of file Logger.h.
 { INFO, DEBUG, WARNING, ERROR, FATAL };
Constructor & Destructor Documentation
Logger()
logger::Logger::Logger () private delete
~Logger()
logger::Logger::~Logger () private delete
Member Function Documentation
init()
void logger::Logger::init (int argc, char * argv[]) static
Definition at line 33 of file Logger.cpp.
{
         START_EASYLOGGINGPP(argc, argv);
         conf.setGlobally(el::ConfigurationType::Enabled, "true");
         conf.setGlobally(el::ConfigurationType::Format, "%datetime{%Y-%M-%d %H:%m:%s} %tick: %level %msg");
         conf.setGlobally(el::ConfigurationType::ToFile, "false");
         conf.setGlobally(el::ConfigurationType::ToStandardOutput, "true");
         conf.setGlobally(el::ConfigurationType::SubsecondPrecision, "2");
         conf.setGlobally(el::ConfigurationType::PerformanceTracking, "false");
         conf.setGlobally(el::ConfigurationType::MaxLogFileSize, "2097152");
         conf.setGlobally(el::ConfigurationType::LogFlushThreshold, "0");
         conf.set(el::Level::Verbose, el::ConfigurationType::Format, "%datetime{%Y-%M-%d %H:%m:%s} %tick: %msg");
         el::Loggers::addFlag(el::LoggingFlag::DisableApplicationAbortOnFatalLog);
         el::Loggers::addFlag(el::LoggingFlag::DisablePerformanceTrackingCheckpointComparison);
         el::Loggers::addFlag(el::LoggingFlag::ColoredTerminalOutput);
         el::Loggers::reconfigureLogger("default", conf);
         el::Logger* logger = el::Loggers::getLogger("default");
         std::string logFilename = logger->typedConfigurations()->filename(el::Level::Verbose).c_str();
         if (logFilename != "/dev/null") {
             conf.setGlobally(el::ConfigurationType::ToFile, "true");
             el::Loggers::reconfigureLogger("default", conf);
         }
         setLogLevel(6);
     }
References conf, and setLogLevel().
Referenced by utils::Config::init().
logToFile()
void logger::Logger::logToFile (const std::string & logFile) static
Definition at line 108 of file Logger.cpp.
{
         conf.setGlobally(el::ConfigurationType::Filename, logFile);
         conf.setGlobally(el::ConfigurationType::ToFile, "true");
         el::Loggers::reconfigureLogger("default", conf);
     }
References conf.
Referenced by utils::Config::init().
quiet()
void logger::Logger::quiet () static
Definition at line 115 of file Logger.cpp.
{
         conf.setGlobally(el::ConfigurationType::ToStandardOutput, "false");
         el::Loggers::reconfigureLogger("default", conf);
     }
References conf.
Referenced by utils::Config::init().
setCustomFormatSpec()
void logger::Logger::setCustomFormatSpec (const char * format, const el::FormatSpecifierValueResolver & resolver) static
Definition at line 63 of file Logger.cpp.
{
         el::Helpers::installCustomFormatSpecifier(el::CustomFormatSpecifier(format, resolver));
     }
Referenced by core::EventLoop::init().
setLogLevel()
void logger::Logger::setLogLevel (int level) static
Definition at line 69 of file Logger.cpp.
{
         conf.set(el::Level::Trace, el::ConfigurationType::Enabled, "false");   // trace method/function calling
         conf.set(el::Level::Debug, el::ConfigurationType::Enabled, "false");   // typical assert messages - but we can go on
         conf.set(el::Level::Info, el::ConfigurationType::Enabled, "false");    // additional infos - what 's going on
         conf.set(el::Level::Warning, el::ConfigurationType::Enabled, "false"); // not that serious but mentioning
         conf.set(el::Level::Error, el::ConfigurationType::Enabled, "false");   // serious errors - but we can go on
         conf.set(el::Level::Fatal, el::ConfigurationType::Enabled, "false");   // asserts - stop - we can not go on
         switch (level) {
             case 6:
                 conf.set(el::Level::Trace, el::ConfigurationType::Enabled, "true");
                 [[fallthrough]];
             case 5:
                 conf.set(el::Level::Debug, el::ConfigurationType::Enabled, "true");
                 [[fallthrough]];
             case 4:
                 conf.set(el::Level::Info, el::ConfigurationType::Enabled, "true");
                 [[fallthrough]];
             case 3:
                 conf.set(el::Level::Warning, el::ConfigurationType::Enabled, "true");
                 [[fallthrough]];
             case 2:
                 conf.set(el::Level::Error, el::ConfigurationType::Enabled, "true");
                 [[fallthrough]];
             case 1:
                 conf.set(el::Level::Fatal, el::ConfigurationType::Enabled, "true");
                 [[fallthrough]];
             case 0:
                 [[fallthrough]];
             default:;
         };
         el::Loggers::reconfigureLogger("default", conf);
     }
References conf.
Referenced by init().
setVerboseLevel()
void logger::Logger::setVerboseLevel (unsigned short level) static
Definition at line 104 of file Logger.cpp.
{
         el::Loggers::setVerboseLevel(level);
     }
Member Data Documentation
conf
el::Configurations logger::Logger::conf static protected
Definition at line 52 of file Logger.h.
Referenced by init(), logToFile(), quiet(), and setLogLevel().
The documentation for this class was generated from the following files:
log/Logger.h
log/Logger.cpp