snode.c: core::timer::Timer Class Reference
core::timer::Timer Class Reference
#include <Timer.h>
Classes
struct absoluteTimeout
Public Member Functions
void cancel ()
Static Public Member Functions
static IntervalTimer & intervalTimer (const std::function< void(const void *, const std::function< void()> &stop)> &dispatcher, const struct timeval &timeout, const void *arg)
static IntervalTimer & intervalTimer (const std::function< void(const void *)> &dispatcher, const struct timeval &timeout, const void *arg)
static SingleshotTimer & singleshotTimer (const std::function< void(const void *)> &dispatcher, const struct timeval &timeout, const void *arg)
Protected Member Functions
Timer (const struct timeval &timeout, const void *arg)
virtual ~Timer ()=default
void update ()
void destroy () override
struct timeval & timeout () override
operator struct timeval () const override
Protected Attributes
const void * arg
Private Member Functions
Timer (const Timer &)=delete
Timer & operator= (const Timer &timer)=delete
Private Attributes
struct timeval delay
Detailed Description
Definition at line 37 of file Timer.h.
Constructor & Destructor Documentation
Timer() [1/2]
core::timer::Timer::Timer (const Timer &) private delete
Timer() [2/2]
core::timer::Timer::Timer (const struct timeval & timeout, const void * arg) protected
Definition at line 32 of file Timer.cpp.
         : arg(arg)
         , delay(timeout) {
         gettimeofday(&absoluteTimeout, nullptr);
         update();
     }
References core::system::gettimeofday(), and update().
~Timer()
virtual core::timer::Timer::~Timer () protected virtual default
Member Function Documentation
cancel()
void core::timer::Timer::cancel ()
Definition at line 67 of file Timer.cpp.
{
         EventLoop::instance().getTimerEventDispatcher().remove(this);
     }
References core::EventLoop::getTimerEventDispatcher(), core::EventLoop::instance(), and core::TimerEventDispatcher::remove().
Referenced by core::timer::IntervalTimer::dispatch(), and core::timer::SingleshotTimer::dispatch().
destroy()
void core::timer::Timer::destroy () override protected virtual
Implements core::TimerEventReceiver.
Definition at line 75 of file Timer.cpp.
{
         delete this;
     }
intervalTimer() [1/2]
IntervalTimer & core::timer::Timer::intervalTimer (const std::function< void(const void *)> & dispatcher, const struct timeval & timeout, const void * arg) static
Definition at line 59 of file Timer.cpp.
{
         IntervalTimer* ct = new IntervalTimer(dispatcher, timeout, arg);
         EventLoop::instance().getTimerEventDispatcher().add(ct);
         return *ct;
     }
References core::TimerEventDispatcher::add(), arg, core::EventLoop::getTimerEventDispatcher(), core::EventLoop::instance(), and timeout().
intervalTimer() [2/2]
IntervalTimer & core::timer::Timer::intervalTimer (const std::function< void(const void *, const std::function< void()> &stop)> & dispatcher, const struct timeval & timeout, const void * arg) static
Definition at line 48 of file Timer.cpp.
{
         IntervalTimer* ct = new IntervalTimer(dispatcher, timeout, arg);
         EventLoop::instance().getTimerEventDispatcher().add(ct);
         return *ct;
     }
References core::TimerEventDispatcher::add(), arg, core::EventLoop::getTimerEventDispatcher(), core::EventLoop::instance(), and timeout().
operator struct timeval()
core::timer::Timer::operator struct timeval () const explicit override protected virtual
Implements core::TimerEventReceiver.
Definition at line 83 of file Timer.cpp.
{
         return absoluteTimeout;
     }
operator=()
Timer& core::timer::Timer::operator= (const Timer & timer) private delete
singleshotTimer()
SingleshotTimer & core::timer::Timer::singleshotTimer (const std::function< void(const void *)> & dispatcher, const struct timeval & timeout, const void * arg) static
Definition at line 40 of file Timer.cpp.
{
         SingleshotTimer* st = new SingleshotTimer(dispatcher, timeout, arg);
         EventLoop::instance().getTimerEventDispatcher().add(st);
         return *st;
     }
References core::TimerEventDispatcher::add(), arg, core::EventLoop::getTimerEventDispatcher(), core::EventLoop::instance(), and timeout().
timeout()
struct timeval & core::timer::Timer::timeout () override protected virtual
Implements core::TimerEventReceiver.
Definition at line 79 of file Timer.cpp.
{
         return absoluteTimeout;
     }
Referenced by intervalTimer(), and singleshotTimer().
update()
void core::timer::Timer::update () protected
Definition at line 71 of file Timer.cpp.
{
         absoluteTimeout = absoluteTimeout + delay;
     }
References delay.
Referenced by core::timer::IntervalTimer::dispatch(), and Timer().
Member Data Documentation
arg
const void* core::timer::Timer::arg protected
Definition at line 60 of file Timer.h.
Referenced by core::timer::IntervalTimer::dispatch(), core::timer::SingleshotTimer::dispatch(), intervalTimer(), and singleshotTimer().
delay
struct timeval core::timer::Timer::delay private
Definition at line 67 of file Timer.h.
Referenced by update().
The documentation for this class was generated from the following files:
core/timer/Timer.h
core/timer/Timer.cpp