snode.c: core::epoll::EventDispatcher Class Reference
core::epoll::EventDispatcher Class Reference
#include <EventDispatcher.h>
Public Member Functions
EventDispatcher ()
~EventDispatcher ()=default
Public Member Functions inherited from core::EventDispatcher
DescriptorEventDispatcher & getDescriptorEventDispatcher (core::EventDispatcher::DISP_TYPE dispType)
TimerEventDispatcher & getTimerEventDispatcher ()
TickStatus dispatch (const utils::Timeval &tickTimeOut, bool stopped)
void stop ()
void stopDescriptorEvents ()
void stopTimerEvents ()
Private Member Functions
EventDispatcher (const EventDispatcher &)=delete
EventDispatcher & operator= (const EventDispatcher &)=delete
int multiplex (utils::Timeval &tickTimeout) override
void dispatchActiveEvents (int count, const utils::Timeval &currentTime) override
Private Attributes
int epfd
int epfds [3]
epoll_event ePollEvents [3]
Additional Inherited Members
Public Types inherited from core::EventDispatcher
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Protected Member Functions inherited from core::EventDispatcher
EventDispatcher (core::DescriptorEventDispatcher *const readDescriptorEventDispatcher, core::DescriptorEventDispatcher *const writeDescriptorEventDispatcher, core::DescriptorEventDispatcher *const exceptionDescriptorEventDispatcher)
~EventDispatcher ()
int getObservedEventReceiverCount ()
int getMaxFd ()
Protected Attributes inherited from core::EventDispatcher
std::array< core::DescriptorEventDispatcher *, 3 > descriptorEventDispatcher
Detailed Description
Definition at line 36 of file EventDispatcher.h.
Constructor & Destructor Documentation
EventDispatcher() [1/2]
core::epoll::EventDispatcher::EventDispatcher (const EventDispatcher &) private delete
EventDispatcher() [2/2]
core::epoll::EventDispatcher::EventDispatcher ()
Definition at line 37 of file EventDispatcher.cpp.
         : core::EventDispatcher(new core::epoll::DescriptorEventDispatcher(epfds[RD], EPOLLIN),
                                 new core::epoll::DescriptorEventDispatcher(epfds[WR], EPOLLOUT),
                                 new core::epoll::DescriptorEventDispatcher(epfds[EX], EPOLLPRI)) {
         epfd = core::system::epoll_create1(EPOLL_CLOEXEC);
         epoll_event event;
         event.events = EPOLLIN;
         event.data.ptr = descriptorEventDispatcher[0];
         core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[RD], &event);
         event.data.ptr = descriptorEventDispatcher[1];
         core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[WR], &event);
         event.data.ptr = descriptorEventDispatcher[2];
         core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[EX], &event);
     }
References core::EventDispatcher::descriptorEventDispatcher, epfd, epfds, core::system::epoll_create1(), core::system::epoll_ctl(), core::EventDispatcher::EX, core::EventDispatcher::RD, and core::EventDispatcher::WR.
~EventDispatcher()
core::epoll::EventDispatcher::~EventDispatcher () default
Member Function Documentation
dispatchActiveEvents()
void core::epoll::EventDispatcher::dispatchActiveEvents (int count, const utils::Timeval & currentTime) override private virtual
Implements core::EventDispatcher.
Definition at line 60 of file EventDispatcher.cpp.
{
         for (int i = 0; i < count; i++) {
             if ((ePollEvents[i].events & EPOLLIN) != 0) {
                 static_cast<core::DescriptorEventDispatcher*>(ePollEvents[i].data.ptr)->dispatchActiveEvents(currentTime);
             }
         }
         for (core::DescriptorEventDispatcher* const eventDispatcher : descriptorEventDispatcher) {
             eventDispatcher->dispatchImmediateEvents(currentTime);
         }
     }
References core::EventDispatcher::descriptorEventDispatcher, and ePollEvents.
multiplex()
int core::epoll::EventDispatcher::multiplex (utils::Timeval & tickTimeout) override private virtual
Implements core::EventDispatcher.
Definition at line 56 of file EventDispatcher.cpp.
{
         return core::system::epoll_wait(epfd, ePollEvents, 3, tickTimeout.ms());
     }
References epfd, core::system::epoll_wait(), ePollEvents, and utils::Timeval::ms().
operator=()
EventDispatcher& core::epoll::EventDispatcher::operator= (const EventDispatcher &) private delete
Member Data Documentation
epfd
int core::epoll::EventDispatcher::epfd private
Definition at line 48 of file EventDispatcher.h.
Referenced by EventDispatcher(), and multiplex().
epfds
int core::epoll::EventDispatcher::epfds[3] private
Definition at line 50 of file EventDispatcher.h.
Referenced by EventDispatcher().
ePollEvents
epoll_event core::epoll::EventDispatcher::ePollEvents[3] private
Definition at line 51 of file EventDispatcher.h.
Referenced by dispatchActiveEvents(), and multiplex().
The documentation for this class was generated from the following files:
core/epoll/EventDispatcher.h
core/epoll/EventDispatcher.cpp