snode.c: core::poll::PollFds Class Reference
core::poll::PollFds Class Reference
#include <EventDispatcher.h>
Classes
struct PollFdIndex
Public Types
using pollfds_size_type = std::vector< pollfd >::size_type
Public Member Functions
PollFds ()
void modAdd (core::EventReceiver *eventReceiver, short event)
void modDel (core::EventReceiver *eventReceiver, short event)
void modOn (core::EventReceiver *eventReceiver, short event)
void modOff (core::EventReceiver *eventReceiver, short event)
void compress ()
pollfd * getEvents ()
const std::unordered_map< int, PollFdIndex > & getPollFdIndices () const
nfds_t getInterestCount () const
Private Attributes
std::vector< pollfd > pollfds
std::unordered_map< int, PollFdIndex > pollFdIndices
uint32_t interestCount
Detailed Description
Definition at line 44 of file EventDispatcher.h.
Member Typedef Documentation
pollfds_size_type
using core::poll::PollFds::pollfds_size_type = std::vector<pollfd>::size_type
Definition at line 53 of file EventDispatcher.h.
Constructor & Destructor Documentation
PollFds()
core::poll::PollFds::PollFds () explicit
Definition at line 42 of file EventDispatcher.cpp.
         : interestCount(0) {
         pollfd pollFd;
         pollFd.fd = -1;
         pollFd.events = 0;
         pollFd.revents = 0;
         pollfds.resize(1, pollFd);
     }
References pollfds.
Member Function Documentation
compress()
void core::poll::PollFds::compress ()
Definition at line 115 of file EventDispatcher.cpp.
{
         std::vector<pollfd>::iterator it = pollfds.begin();
         std::vector<pollfd>::iterator rit = pollfds.begin() + static_cast<long>(pollfds.size()) - 1;
         while (it < rit) {
             while (it != pollfds.end() && it->fd != -1) {
                 ++it;
             }
             while (rit >= it && rit->fd == -1) {
                 --rit;
             }
             while (it < rit && it->fd == -1 && rit->fd != -1) {
                 pollfd tPollFd = *it;
                 *it = *rit;
                 *rit = tPollFd;
                 ++it;
                 --rit;
             }
         }
         while (pollfds.size() > (interestCount * 2) + 1) {
             pollfds.resize(pollfds.size() / 2);
         }
         for (uint32_t i = 0; i < interestCount; i++) {
             if (pollfds[i].fd >= 0) {
                 pollFdIndices[pollfds[i].fd].index = i;
             }
         }
     }
References interestCount, pollFdIndices, and pollfds.
getEvents()
pollfd * core::poll::PollFds::getEvents ()
Definition at line 148 of file EventDispatcher.cpp.
{
         return pollfds.data();
     }
References pollfds.
Referenced by core::poll::DescriptorEventDispatcher::dispatchActiveEvents(), and core::poll::EventDispatcher::multiplex().
getInterestCount()
nfds_t core::poll::PollFds::getInterestCount () const
Definition at line 156 of file EventDispatcher.cpp.
{
         return interestCount;
     }
References interestCount.
Referenced by core::poll::EventDispatcher::multiplex().
getPollFdIndices()
const std::unordered_map< int, PollFds::PollFdIndex > & core::poll::PollFds::getPollFdIndices () const
Definition at line 152 of file EventDispatcher.cpp.
{
         return pollFdIndices;
     }
References pollFdIndices.
Referenced by core::poll::DescriptorEventDispatcher::dispatchActiveEvents().
modAdd()
void core::poll::PollFds::modAdd (core::EventReceiver * eventReceiver, short event)
Definition at line 53 of file EventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         std::unordered_map<int, PollFdIndex>::iterator itPollFdIndex = pollFdIndices.find(fd);
         if (itPollFdIndex == pollFdIndices.end()) {
             pollfds[interestCount].events = event;
             pollfds[interestCount].fd = fd;
             pollFdIndices[fd].index = interestCount;
             pollFdIndices[fd].events = event;
             interestCount++;
             if (interestCount == pollfds.size()) {
                 pollfd pollFd;
                 pollFd.fd = -1;
                 pollFd.events = 0;
                 pollFd.revents = 0;
                 pollfds.resize(pollfds.size() * 2, pollFd);
             }
         } else {
             PollFdIndex& pollFdIndex = itPollFdIndex->second;
             pollfds[pollFdIndex.index].events |= event;
             pollFdIndex.events |= event;
         }
     }
References core::poll::PollFds::PollFdIndex::events, core::EventReceiver::getRegisteredFd(), core::poll::PollFds::PollFdIndex::index, interestCount, pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventDispatcher::modAdd().
modDel()
void core::poll::PollFds::modDel (core::EventReceiver * eventReceiver, short event)
Definition at line 84 of file EventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         std::unordered_map<int, PollFdIndex>::iterator itPollFdIndex = pollFdIndices.find(fd);
         PollFdIndex& pollFdIndex = itPollFdIndex->second;
         pollfds[pollFdIndex.index].events &= static_cast<short>(~event); // tilde promotes to int
         pollFdIndex.events &= static_cast<short>(~event);                // tilde promotes to int
         if (pollFdIndex.events == 0) {
             pollfds[pollFdIndex.index].fd = -1; // Compress will keep track of that descriptor
             pollFdIndices.erase(itPollFdIndex);
             interestCount--;
         }
     }
References core::poll::PollFds::PollFdIndex::events, core::EventReceiver::getRegisteredFd(), core::poll::PollFds::PollFdIndex::index, interestCount, pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventDispatcher::modDel().
modOff()
void core::poll::PollFds::modOff (core::EventReceiver * eventReceiver, short event)
Definition at line 109 of file EventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         pollfds[pollFdIndices.find(fd)->second.index].events &= static_cast<short>(~event); // Tilde promotes to int
     }
References core::EventReceiver::getRegisteredFd(), pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventDispatcher::modOff().
modOn()
void core::poll::PollFds::modOn (core::EventReceiver * eventReceiver, short event)
Definition at line 103 of file EventDispatcher.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         pollfds[pollFdIndices.find(fd)->second.index].events |= event;
     }
References core::EventReceiver::getRegisteredFd(), pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventDispatcher::modOn().
Member Data Documentation
interestCount
uint32_t core::poll::PollFds::interestCount private
Definition at line 74 of file EventDispatcher.h.
Referenced by compress(), getInterestCount(), modAdd(), and modDel().
pollFdIndices
std::unordered_map<int, PollFdIndex> core::poll::PollFds::pollFdIndices private
Definition at line 72 of file EventDispatcher.h.
Referenced by compress(), getPollFdIndices(), modAdd(), modDel(), modOff(), and modOn().
pollfds
std::vector<pollfd> core::poll::PollFds::pollfds private
Definition at line 71 of file EventDispatcher.h.
Referenced by compress(), getEvents(), modAdd(), modDel(), modOff(), modOn(), and PollFds().
The documentation for this class was generated from the following files:
core/mux/poll/EventDispatcher.h
core/mux/poll/EventDispatcher.cpp