snode.c: CLI::BadNameString Class Reference
CLI::BadNameString Class Reference
Errors
Thrown on construction of a bad name.
#include <CLI11.hpp>
Public Member Functions
BadNameString (std::string msg, ExitCodes exit_code)
BadNameString (std::string msg, int exit_code)
BadNameString (std::string msg)
Public Member Functions inherited from CLI::ConstructionError
ConstructionError (std::string msg, ExitCodes exit_code)
ConstructionError (std::string msg, int exit_code)
Public Member Functions inherited from CLI::Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static BadNameString OneCharName (std::string name)
static BadNameString BadLongName (std::string name)
static BadNameString DashesOnly (std::string name)
static BadNameString MultiPositionalNames (std::string name)
Protected Member Functions
BadNameString (std::string ename, std::string msg, int exit_code)
BadNameString (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from CLI::ConstructionError
ConstructionError (std::string ename, std::string msg, int exit_code)
ConstructionError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown on construction of a bad name.
Definition at line 666 of file CLI11.hpp.
Constructor & Destructor Documentation
BadNameString() [1/5]
CLI::BadNameString::BadNameString (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 667 of file CLI11.hpp.
Referenced by BadLongName(), DashesOnly(), MultiPositionalNames(), and OneCharName().
BadNameString() [2/5]
CLI::BadNameString::BadNameString (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 667 of file CLI11.hpp.
BadNameString() [3/5]
CLI::BadNameString::BadNameString (std::string msg, ExitCodes exit_code) inline
Definition at line 667 of file CLI11.hpp.
BadNameString() [4/5]
CLI::BadNameString::BadNameString (std::string msg, int exit_code) inline
Definition at line 667 of file CLI11.hpp.
BadNameString() [5/5]
CLI::BadNameString::BadNameString (std::string msg) inline explicit
Definition at line 668 of file CLI11.hpp.
Member Function Documentation
BadLongName()
static BadNameString CLI::BadNameString::BadLongName (std::string name) inline static
Definition at line 672 of file CLI11.hpp.
{
             return BadNameString("Bad long name: " + name);
         }
References BadNameString().
Referenced by CLI::detail::get_names().
DashesOnly()
static BadNameString CLI::BadNameString::DashesOnly (std::string name) inline static
Definition at line 675 of file CLI11.hpp.
{
             return BadNameString("Must have a name, not just dashes: " + name);
         }
References BadNameString().
Referenced by CLI::detail::get_names().
MultiPositionalNames()
static BadNameString CLI::BadNameString::MultiPositionalNames (std::string name) inline static
Definition at line 678 of file CLI11.hpp.
{
             return BadNameString("Only one positional name allowed, remove: " + name);
         }
References BadNameString().
Referenced by CLI::detail::get_names().
OneCharName()
static BadNameString CLI::BadNameString::OneCharName (std::string name) inline static
Definition at line 669 of file CLI11.hpp.
{
             return BadNameString("Invalid one char name: " + name);
         }
References BadNameString().
Referenced by CLI::detail::get_names().
The documentation for this class was generated from the following file:
utils/CLI11.hpp