snode.c: core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT > Class Template Reference
core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT > Class Template Reference
#include <SocketAcceptor.h>
Public Types
using Config = typename Super::Config
using SocketConnection = typename Super::SocketConnection
Public Member Functions
SocketAcceptor (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketAcceptor () override
void listen (const std::shared_ptr< Config > &config, const std::function< void(const SocketAddress &, int)> &onError)
Private Types
using Super = core::socket::stream::SocketAcceptor< ServerConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
using SocketAddress = typename Super::SocketAddress
Private Member Functions
void addMasterCtx (SSL_CTX *sslCtx)
Static Private Member Functions
static int serverNameCallback (SSL *ssl, [[maybe_unused]] int *al, [[maybe_unused]] void *arg)
Private Attributes
SSL_CTX * masterSslCtx = nullptr
std::set< std::string > masterSslCtxDomains
std::shared_ptr< std::map< std::string, SSL_CTX * > > sniSslCtxs
bool forceSni = false
Additional Inherited Members
Protected Types inherited from core::socket::stream::SocketAcceptor< ServerConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
using Config = ServerConfigT
using SocketConnection = core::socket::stream::tls::SocketConnection< SocketT >
using SocketAddress = typename Socket::SocketAddress
Protected Member Functions inherited from core::socket::stream::SocketAcceptor< ServerConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
void destruct ()
SocketAcceptor (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketAcceptor () override=default
void listen (const std::shared_ptr< Config > &config, const std::function< void(const SocketAddress &, int)> &onError)
Protected Member Functions inherited from core::eventreceiver::InitAcceptEventReceiver
InitAcceptEventReceiver (const std::string &name)
void dispatch (const utils::Timeval &currentTime) override
Protected Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish () const
const std::string & getName ()
Protected Member Functions inherited from core::eventreceiver::AcceptEventReceiver
AcceptEventReceiver (const std::string &name, const utils::Timeval &timeout=DescriptorEventReceiver::TIMEOUT::DISABLE)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
void enable (int fd)
void disable ()
void suspend ()
void resume ()
void setTimeout (const utils::Timeval &timeout)
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
int getRegisteredFd ()
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
bool isEnabled () const
bool isSuspended () const
Protected Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Protected Attributes inherited from core::socket::stream::SocketAcceptor< ServerConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
std::shared_ptr< Config > config
std::map< std::string, std::any > options
Protected Attributes inherited from core::EventReceiver
Event event
Detailed Description
template<typename ServerConfigT, typename SocketT>
class core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >
Definition at line 41 of file SocketAcceptor.h.
Member Typedef Documentation
Config
template<typename ServerConfigT , typename SocketT > using core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::Config = typename Super::Config
Definition at line 49 of file SocketAcceptor.h.
SocketAddress
template<typename ServerConfigT , typename SocketT > using core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::SocketAddress = typename Super::SocketAddress private
Definition at line 46 of file SocketAcceptor.h.
SocketConnection
template<typename ServerConfigT , typename SocketT > using core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::SocketConnection = typename Super::SocketConnection
Definition at line 50 of file SocketAcceptor.h.
Super
template<typename ServerConfigT , typename SocketT > using core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::Super = core::socket::stream::SocketAcceptor<ServerConfigT, core::socket::stream::tls::SocketConnection<SocketT> > private
Definition at line 44 of file SocketAcceptor.h.
Constructor & Destructor Documentation
SocketAcceptor()
template<typename ServerConfigT , typename SocketT > core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::SocketAcceptor (const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options) inline
Definition at line 52 of file SocketAcceptor.h.
             : Super(
                   socketContextFactory,
                   onConnect,
                   [onConnected, this](SocketConnection* socketConnection) -> void {
                       SSL* ssl = socketConnection->startSSL(
                           this->masterSslCtx, this->config->getInitTimeout(), this->config->getShutdownTimeout());
                       if (ssl != nullptr) {
                           SSL_CTX_set_tlsext_servername_arg(this->masterSslCtx, this);
                           SSL_set_accept_state(ssl);
                           socketConnection->doSSLHandshake(
                               [&onConnected, socketConnection](void) -> void { // onSuccess
                                   LOG(INFO) << "SSL/TLS initial handshake success";
                                   onConnected(socketConnection);
                               },
                               [](void) -> void { // onTimeout
                                   LOG(WARNING) << "SSL/TLS initial handshake timed out";
                               },
                               [](int sslErr) -> void { // onError
                                   ssl_log("SSL/TLS initial handshake failed", sslErr);
                               });
                       } else {
                           socketConnection->close();
                           ssl_log_error("SSL/TLS initialization failed");
                       }
                   },
                   [onDisconnect](SocketConnection* socketConnection) -> void { // onDisconnect
                       socketConnection->stopSSL();
                       onDisconnect(socketConnection);
                   },
                   options) {
             masterSslCtx = ssl_ctx_new(options, true);
             if (masterSslCtx != nullptr) {
                 SSL_CTX_set_tlsext_servername_callback(masterSslCtx, serverNameCallback);
                 addMasterCtx(masterSslCtx);
             }
             sniSslCtxs = std::any_cast<std::shared_ptr<std::map<std::string, SSL_CTX*>>>(options.find("SNI_SSL_CTXS")->second);
             forceSni = *std::any_cast<bool*>(options.find("FORCE_SNI")->second);
         }
References core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::masterSslCtx, core::socket::stream::SocketAcceptor< ServerConfigT, core::socket::stream::tls::SocketConnection< SocketT > >::onConnected, and core::socket::stream::tls::ssl_log().
~SocketAcceptor()
template<typename ServerConfigT , typename SocketT > core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::~SocketAcceptor () inline override
Definition at line 101 of file SocketAcceptor.h.
{
             ssl_ctx_free(masterSslCtx);
         }
References core::socket::stream::tls::ssl_ctx_free().
Member Function Documentation
addMasterCtx()
template<typename ServerConfigT , typename SocketT > void core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::addMasterCtx (SSL_CTX * sslCtx) inline private
Definition at line 116 of file SocketAcceptor.h.
{
             if (sslCtx != nullptr) {
                 X509* x509 = SSL_CTX_get0_certificate(sslCtx);
                 if (x509 != nullptr) {
                     GENERAL_NAMES* subjectAltNames =
                         static_cast<GENERAL_NAMES*>(X509_get_ext_d2i(x509, NID_subject_alt_name, nullptr, nullptr));
                     int32_t altNameCount = sk_GENERAL_NAME_num(subjectAltNames);
                     for (int32_t i = 0; i < altNameCount; ++i) {
                         GENERAL_NAME* generalName = sk_GENERAL_NAME_value(subjectAltNames, i);
                         if (generalName->type == GEN_DNS) {
                             std::string subjectAltName =
                                 std::string(reinterpret_cast<const char*>(ASN1_STRING_get0_data(generalName->d.dNSName)),
                                             static_cast<std::size_t>(ASN1_STRING_length(generalName->d.dNSName)));
                             VLOG(2) << "SSL_CTX for domain '" << subjectAltName << "' installed";
                             masterSslCtxDomains.insert(subjectAltName);
                         }
                     }
                     sk_GENERAL_NAME_pop_free(subjectAltNames, GENERAL_NAME_free);
                 } else {
                     VLOG(2) << "\tClient certificate: no certificate";
                 }
             }
         }
listen()
template<typename ServerConfigT , typename SocketT > void core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::listen (const std::shared_ptr< Config > & config, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 105 of file SocketAcceptor.h.
{
             if (masterSslCtx == nullptr) {
                 errno = EINVAL;
                 onError(config->getLocalAddress(), errno);
                 Super::destruct();
             } else {
                 Super::listen(config, onError);
             }
         }
References core::system::listen().
serverNameCallback()
template<typename ServerConfigT , typename SocketT > static int core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::serverNameCallback (SSL * ssl, [[maybe_unused] ] int * al, [[maybe_unused] ] void * arg) inline static private
Definition at line 142 of file SocketAcceptor.h.
{
             int ret = SSL_TLSEXT_ERR_OK;
             SocketAcceptor* socketAcceptor = static_cast<SocketAcceptor*>(arg);
             if (SSL_get_servername_type(ssl) != -1) {
                 std::string serverNameIndication = SSL_get_servername(ssl, TLSEXT_NAMETYPE_host_name);
                 if (!socketAcceptor->masterSslCtxDomains.contains(serverNameIndication)) {
                     if (socketAcceptor->sniSslCtxs->contains(serverNameIndication)) {
                         SSL_CTX* sniSslCtx = (*socketAcceptor->sniSslCtxs.get())[serverNameIndication];
                         SSL_CTX* nowUsedSslCtx = SSL_set_SSL_CTX(ssl, sniSslCtx);
                         if (nowUsedSslCtx == sniSslCtx) {
                             LOG(INFO) << "SSL_CTX: Switched for SNI '" << serverNameIndication << "'";
                         } else if (nowUsedSslCtx != nullptr) {
                             if (!socketAcceptor->forceSni) {
                                 LOG(WARNING) << "SSL_CTX: Not switcher for SNI '" << serverNameIndication
                                              << "'. Master SSL_CTX still used.";
                                 ret = SSL_TLSEXT_ERR_ALERT_WARNING;
                             } else {
                                 LOG(ERROR) << "SSL_CTX: Not switcher for SNI '" << serverNameIndication << "'.";
                                 ret = SSL_TLSEXT_ERR_ALERT_FATAL;
                             }
                         } else {
                             if (!socketAcceptor->forceSni) {
                                 LOG(WARNING) << "SSL_CTX: Not switcher for SNI '" << serverNameIndication
                                              << "'. Master SSL_CTX still used.";
                                 ret = SSL_TLSEXT_ERR_ALERT_WARNING;
                             } else {
                                 LOG(ERROR) << "SSL_CTX: Found but none used for SNI '" << serverNameIndication << '"';
                                 ret = SSL_TLSEXT_ERR_ALERT_FATAL;
                             }
                         }
                     } else {
                         if (!socketAcceptor->forceSni) {
                             LOG(WARNING) << "SSL_CTX: Not found for SNI '" << serverNameIndication << "'. Master SSL_CTX still used.";
                         } else {
                             LOG(ERROR) << "SSL_CTX: Not found for SNI '" << serverNameIndication << "'.";
                             ret = SSL_TLSEXT_ERR_ALERT_FATAL;
                         }
                     }
                 } else {
                     LOG(INFO) << "SSL_CTX: Master SSL_CTX already provides SNI '" << serverNameIndication << "'";
                 }
             }
             return ret;
         }
References core::ERROR, core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::forceSni, core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::masterSslCtxDomains, and core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::sniSslCtxs.
Member Data Documentation
forceSni
template<typename ServerConfigT , typename SocketT > bool core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::forceSni = false private
Definition at line 198 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::serverNameCallback().
masterSslCtx
template<typename ServerConfigT , typename SocketT > SSL_CTX* core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::masterSslCtx = nullptr private
Definition at line 194 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::SocketAcceptor().
masterSslCtxDomains
template<typename ServerConfigT , typename SocketT > std::set<std::string> core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::masterSslCtxDomains private
Definition at line 195 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::serverNameCallback().
sniSslCtxs
template<typename ServerConfigT , typename SocketT > std::shared_ptr<std::map<std::string, SSL_CTX*> > core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::sniSslCtxs private
Definition at line 197 of file SocketAcceptor.h.
Referenced by core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::serverNameCallback().
The documentation for this class was generated from the following file:
core/socket/stream/tls/SocketAcceptor.h