snode.c: web::websocket::server::SocketContextUpgradeFactory Class Reference
web::websocket::server::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Member Functions
SocketContextUpgradeFactory ()=default
SocketContextUpgradeFactory (const SocketContextUpgradeFactory &)=delete
SocketContextUpgradeFactory & operator= (const SocketContextUpgradeFactory &)=delete
Public Member Functions inherited from web::http::server::SocketContextUpgradeFactory
void checkRefCount () final
Public Member Functions inherited from web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >
void prepare (Request &request, Response &response)
void incRefCount ()
void decRefCount ()
Static Public Member Functions
static void link ()
Private Member Functions
std::string name () override
SocketContextUpgrade * create (core::socket::SocketConnection *socketConnection, web::http::server::Request *request, web::http::server::Response *response) override
Additional Inherited Members
Public Types inherited from web::http::server::SocketContextUpgradeFactory
using Resquest = web::http::server::Request
using Reponse = web::http::server::Response
Public Types inherited from web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >
using Request = web::http::server::Request
using Response = web::http::server::Response
Protected Member Functions inherited from web::http::server::SocketContextUpgradeFactory
SocketContextUpgradeFactory ()
Protected Member Functions inherited from web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >
SocketContextUpgradeFactory ()
~SocketContextUpgradeFactory () override=default
Protected Member Functions inherited from core::socket::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()=default
Static Protected Member Functions inherited from web::http::server::SocketContextUpgradeFactory
static void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
Protected Attributes inherited from web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >
std::size_t refCount
Detailed Description
Definition at line 42 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory() [1/2]
web::websocket::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory () default
SocketContextUpgradeFactory() [2/2]
web::websocket::server::SocketContextUpgradeFactory::SocketContextUpgradeFactory (const SocketContextUpgradeFactory &) delete
Member Function Documentation
create()
SocketContextUpgrade * web::websocket::server::SocketContextUpgradeFactory::create (core::socket::SocketConnection * socketConnection, web::http::server::Request * request, web::http::server::Response * response) override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >.
Definition at line 39 of file SocketContextUpgradeFactory.cpp.
{
         SocketContextUpgrade* socketContext = nullptr;
         if (request->get("Sec-WebSocket-Version") == "13") {
             std::string subProtocolNames = request->get("sec-websocket-protocol");
             std::string subProtocolName;
             do {
                 std::tie(subProtocolName, subProtocolNames) = httputils::str_split(subProtocolNames, ',');
                 httputils::str_trimm(subProtocolName);
                 socketContext = SocketContextUpgrade::create(this, socketConnection, subProtocolName);
             } while (subProtocolNames.length() > 0 && socketContext == nullptr);
             if (socketContext != nullptr) {
                 response->set("Upgrade", "websocket");
                 response->set("Connection", "Upgrade");
                 response->set("Sec-WebSocket-Protocol", subProtocolName);
                 response->set("Sec-WebSocket-Accept", base64::serverWebSocketKey(request->get("sec-websocket-key")));
                 response->status(101).end(); // Switch Protocol
             } else {
                 response->set("Connection", "close");
                 response->status(400).end();
             }
         } else {
             response->set("Sec-WebSocket-Version", "13");
             response->set("Connection", "close");
             response->status(400).end();
         }
         return socketContext;
     }
References web::websocket::server::SocketContextUpgrade::create(), web::http::server::Response::end(), web::http::server::Request::get(), web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >::request, web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >::response, base64::serverWebSocketKey(), web::http::server::Response::set(), web::http::server::Response::status(), httputils::str_split(), and httputils::str_trimm().
link()
void web::websocket::server::SocketContextUpgradeFactory::link () static
Definition at line 75 of file SocketContextUpgradeFactory.cpp.
{
         static bool linked = false;
         if (!linked) {
             web::http::server::SocketContextUpgradeFactory::link(
                 "websocket", websocketServerContextUpgradeFactory); // cppcheck-suppress leakNoVarFunctionCall
             linked = true;
         }
     }
References web::http::server::SocketContextUpgradeFactory::link(), and web::websocket::server::websocketServerContextUpgradeFactory().
name()
std::string web::websocket::server::SocketContextUpgradeFactory::name () override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::server::Request, web::http::server::Response >.
Definition at line 35 of file SocketContextUpgradeFactory.cpp.
{
         return "websocket";
     }
operator=()
SocketContextUpgradeFactory& web::websocket::server::SocketContextUpgradeFactory::operator= (const SocketContextUpgradeFactory &) delete
The documentation for this class was generated from the following files:
web/websocket/server/SocketContextUpgradeFactory.h
web/websocket/server/SocketContextUpgradeFactory.cpp