snode.c: net::un::ConfigLocal Class Reference
net::un::ConfigLocal Class Reference
#include <ConfigLocal.h>
Public Member Functions
ConfigLocal (CLI::App *baseSc)
Public Member Functions inherited from net::ConfigLocal< SocketAddress >
const SocketAddress & getLocalAddress () const
void setLocalAddress (const SocketAddress &localAddress) const
Protected Member Functions
net::un::SocketAddress getAddress () const override
void required () const
Protected Member Functions inherited from net::ConfigLocal< SocketAddress >
ConfigLocal ()=default
virtual ~ConfigLocal ()=default
Protected Attributes
CLI::App * bindSc = nullptr
CLI::Option * bindSunPathOpt = nullptr
std::string bindSunPath = ""
Additional Inherited Members
Protected Types inherited from net::ConfigLocal< SocketAddress >
using SocketAddress = SocketAddress
Detailed Description
Definition at line 38 of file ConfigLocal.h.
Constructor & Destructor Documentation
ConfigLocal()
net::un::ConfigLocal::ConfigLocal (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigLocal.cpp.
{
         bindSc = baseSc->add_subcommand("local");
         bindSc->description("Bind options");
         bindSc->configurable();
         bindSunPathOpt = bindSc->add_option("-p,--path", bindSunPath, "Unix domain socket");
         bindSunPathOpt->type_name("[filesystem path]");
         bindSunPathOpt->default_val("/tmp/sun.sock");
         bindSunPathOpt->take_first();
         bindSunPathOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindSc, bindSunPath, bindSunPathOpt, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), CLI::OptionBase< CRTP >::take_first(), and CLI::Option::type_name().
Member Function Documentation
getAddress()
SocketAddress net::un::ConfigLocal::getAddress () const override protected virtual
Implements net::ConfigLocal< SocketAddress >.
Definition at line 41 of file ConfigLocal.cpp.
{
         return net::un::SocketAddress(bindSunPath);
     }
References bindSunPath.
required()
void net::un::ConfigLocal::required () const protected
Definition at line 45 of file ConfigLocal.cpp.
{
         bindSc->required();
         bindSunPathOpt->required();
     }
References bindSc, bindSunPathOpt, CLI::App::required(), and CLI::OptionBase< CRTP >::required().
Referenced by net::un::stream::ServerConfig::ServerConfig().
Member Data Documentation
bindSc
CLI::App* net::un::ConfigLocal::bindSc = nullptr protected
Definition at line 47 of file ConfigLocal.h.
Referenced by ConfigLocal(), and required().
bindSunPath
std::string net::un::ConfigLocal::bindSunPath = "" protected
Definition at line 50 of file ConfigLocal.h.
Referenced by ConfigLocal(), and getAddress().
bindSunPathOpt
CLI::Option* net::un::ConfigLocal::bindSunPathOpt = nullptr protected
Definition at line 48 of file ConfigLocal.h.
Referenced by ConfigLocal(), and required().
The documentation for this class was generated from the following files:
net/un/ConfigLocal.h
net/un/ConfigLocal.cpp