snode.c: net::un::SocketAddress Class Reference
net::un::SocketAddress Class Reference
#include <SocketAddress.h>
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &sunPath)
void setSunPath (const std::string &sunPath)
std::string address () const override
std::string toString () const override
Public Member Functions inherited from net::SocketAddress< sockaddr_un >
SocketAddress (socklen_t addrLen=sizeof(SockAddr))
SocketAddress (const SocketAddress &socketAddress)
virtual ~SocketAddress ()=default
SocketAddress & operator= (const SocketAddress &socketAddress)
operator sockaddr * ()
operator const sockaddr * () const
sockaddr & getSockAddr ()
const sockaddr & getSockAddr () const
socklen_t & getAddrLen ()
const socklen_t & getAddrLen () const
Private Types
using Super = net::SocketAddress< sockaddr_un >
Additional Inherited Members
Public Types inherited from net::SocketAddress< sockaddr_un >
using SockAddr = sockaddr_un
Protected Attributes inherited from net::SocketAddress< sockaddr_un >
SockAddr sockAddr
socklen_t addrLen
Detailed Description
Definition at line 46 of file SocketAddress.h.
Member Typedef Documentation
Super
using net::un::SocketAddress::Super = net::SocketAddress<sockaddr_un> private
Definition at line 48 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/2]
net::un::SocketAddress::SocketAddress ()
Definition at line 33 of file SocketAddress.cpp.
         : Super(offsetof(sockaddr_un, sun_path)) {
         sockAddr.sun_family = AF_UNIX;
         *sockAddr.sun_path = 0;
     }
References net::SocketAddress< sockaddr_un >::sockAddr.
SocketAddress() [2/2]
net::un::SocketAddress::SocketAddress (const std::string & sunPath) explicit
Definition at line 39 of file SocketAddress.cpp.
         : SocketAddress() {
         setSunPath(sunPath);
         addrLen = static_cast<socklen_t>(offsetof(sockaddr_un, sun_path) + sunPath.length() + 1);
     }
References net::SocketAddress< sockaddr_un >::addrLen, and setSunPath().
Member Function Documentation
address()
std::string net::un::SocketAddress::address () const override virtual
Implements net::SocketAddress< sockaddr_un >.
Definition at line 55 of file SocketAddress.cpp.
{
         return std::string(sockAddr.sun_path);
     }
References net::SocketAddress< sockaddr_un >::sockAddr.
Referenced by toString(), and net::un::Socket::~Socket().
setSunPath()
void net::un::SocketAddress::setSunPath (const std::string & sunPath)
Definition at line 45 of file SocketAddress.cpp.
{
         if (sunPath.length() < sizeof(sockAddr.sun_path)) {
             std::size_t len = sizeof(sockAddr.sun_path) - 1 < sunPath.size() + 1 ? sizeof(sockAddr.sun_path) - 1 : sunPath.size() + 1;
             std::memcpy(sockAddr.sun_path, sunPath.data(), len);
             addrLen = static_cast<socklen_t>(offsetof(sockaddr_un, sun_path) + sunPath.length() + 1);
         } else {
             throw bad_sunpath(sunPath);
         }
     }
References net::SocketAddress< sockaddr_un >::addrLen, and net::SocketAddress< sockaddr_un >::sockAddr.
Referenced by SocketAddress().
toString()
std::string net::un::SocketAddress::toString () const override virtual
Implements net::SocketAddress< sockaddr_un >.
Definition at line 59 of file SocketAddress.cpp.
{
         return address();
     }
References address().
The documentation for this class was generated from the following files:
net/un/SocketAddress.h
net/un/SocketAddress.cpp