snode.c: net::un::stream::Socket Class Reference
net::un::stream::Socket Class Reference
#include <Socket.h>
Protected Member Functions
~Socket () override
int create (int flags) override
Protected Member Functions inherited from core::Descriptor
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
void attachFd (int fd)
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Additional Inherited Members
Public Types inherited from net::Socket< net::un::SocketAddress >
enum shutdown
using SocketAddress = net::un::SocketAddress
Public Member Functions inherited from net::Socket< net::un::SocketAddress >
void shutdown (shutdown how)
Socket ()=default
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
void open (const std::function< void(int)> &onError, int flags=0)
void bind (const SocketAddress &localAddress, const std::function< void(int)> &onError)
const SocketAddress & getBindAddress () const
Protected Types inherited from core::Descriptor
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Protected Attributes inherited from net::Socket< net::un::SocketAddress >
SocketAddress bindAddress
Protected Attributes inherited from core::Descriptor
enum core::Descriptor::FLAGS none
Detailed Description
Definition at line 31 of file Socket.h.
Constructor & Destructor Documentation
~Socket()
net::un::stream::Socket::~Socket () override protected virtual
Reimplemented from net::Socket< net::un::SocketAddress >.
Definition at line 34 of file Socket.cpp.
                     {
         if (!getBindAddress().toString().empty() && std::remove(getBindAddress().address().data()) != 0) {
             PLOG(ERROR) << "remove: sunPath: " << getBindAddress().toString();
         }
     }
References net::Socket< net::un::SocketAddress >::getBindAddress(), and net::un::SocketAddress::toString().
Member Function Documentation
create()
int net::un::stream::Socket::create (int flags) override protected virtual
Implements net::Socket< net::un::SocketAddress >.
Definition at line 40 of file Socket.cpp.
{
         return core::system::socket(PF_UNIX, SOCK_STREAM | flags, 0);
     }
References core::system::socket().
The documentation for this class was generated from the following files:
net/un/stream/Socket.h
net/un/stream/Socket.cpp