snode.c: net::in::ConfigRemote Class Reference
net::in::ConfigRemote Class Reference
#include <ConfigRemote.h>
Public Member Functions
ConfigRemote (CLI::App *baseSc)
Public Member Functions inherited from net::ConfigRemote< net::in::SocketAddress >
const SocketAddress & getRemoteAddress () const
void setRemoteAddress (const SocketAddress &remoteAddress) const
Protected Member Functions
void required () const
Protected Member Functions inherited from net::ConfigRemote< net::in::SocketAddress >
ConfigRemote ()=default
virtual ~ConfigRemote ()=default
Protected Attributes
CLI::App * connectSc = nullptr
CLI::Option * connectHostOpt = nullptr
CLI::Option * connectPortOpt = nullptr
Private Member Functions
SocketAddress getAddress () const override
Private Attributes
std::string connectHost = ""
uint16_t connectPort = 0
Additional Inherited Members
Protected Types inherited from net::ConfigRemote< net::in::SocketAddress >
using SocketAddress = net::in::SocketAddress
Detailed Description
Definition at line 39 of file ConfigRemote.h.
Constructor & Destructor Documentation
ConfigRemote()
net::in::ConfigRemote::ConfigRemote (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigRemote.cpp.
{
         connectSc = baseSc->add_subcommand("remote");
         connectSc->description("Connect options");
         connectSc->configurable();
         connectHostOpt = connectSc->add_option("-a,--host", connectHost, "Host name or IP address");
         connectHostOpt->type_name("[hostname|ip]");
         connectHostOpt->default_val("0.0.0.0");
         connectHostOpt->take_first();
         connectHostOpt->configurable();
         connectPortOpt = connectSc->add_option("-p,--port", connectPort, "Port number");
         connectPortOpt->type_name("[uint16_t]");
         connectPortOpt->default_val(0);
         connectPortOpt->take_first();
         connectPortOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), connectHost, connectHostOpt, connectPort, connectPortOpt, connectSc, CLI::Option::default_val(), CLI::App::description(), CLI::OptionBase< CRTP >::take_first(), and CLI::Option::type_name().
Member Function Documentation
getAddress()
SocketAddress net::in::ConfigRemote::getAddress () const override private virtual
Implements net::ConfigRemote< net::in::SocketAddress >.
Definition at line 47 of file ConfigRemote.cpp.
{
         return SocketAddress(connectHost, connectPort);
     }
References connectHost, and connectPort.
required()
void net::in::ConfigRemote::required () const protected
Definition at line 51 of file ConfigRemote.cpp.
{
         connectSc->required();
         connectHostOpt->required();
         connectPortOpt->required();
     }
References connectHostOpt, connectPortOpt, connectSc, CLI::App::required(), and CLI::OptionBase< CRTP >::required().
Referenced by net::in::stream::ClientConfig::ClientConfig().
Member Data Documentation
connectHost
std::string net::in::ConfigRemote::connectHost = "" private
Definition at line 53 of file ConfigRemote.h.
Referenced by ConfigRemote(), and getAddress().
connectHostOpt
CLI::Option* net::in::ConfigRemote::connectHostOpt = nullptr protected
Definition at line 47 of file ConfigRemote.h.
Referenced by ConfigRemote(), and required().
connectPort
uint16_t net::in::ConfigRemote::connectPort = 0 private
Definition at line 54 of file ConfigRemote.h.
Referenced by ConfigRemote(), and getAddress().
connectPortOpt
CLI::Option* net::in::ConfigRemote::connectPortOpt = nullptr protected
Definition at line 48 of file ConfigRemote.h.
Referenced by ConfigRemote(), and required().
connectSc
CLI::App* net::in::ConfigRemote::connectSc = nullptr protected
Definition at line 46 of file ConfigRemote.h.
Referenced by ConfigRemote(), and required().
The documentation for this class was generated from the following files:
net/in/ConfigRemote.h
net/in/ConfigRemote.cpp