snode.c: express::dispatcher::RouterDispatcher Class Reference
express::dispatcher::RouterDispatcher Class Reference
#include <RouterDispatcher.h>
Public Member Functions
void dispatch (Request &req, Response &res) const
Public Member Functions inherited from express::dispatcher::Dispatcher
Dispatcher ()=default
virtual ~Dispatcher ()=default
Private Member Functions
void dispatch (const RouterDispatcher *parentRouter, const std::string &parentMountPath, const MountPoint &mountPoint, Request &req, Response &res) const override
void terminate () const
State & getState () const
void returnTo (const RouterDispatcher *parentRouter) const
Private Attributes
std::list< Route > routes
State state
Friends
class express::Router
class ApplicationDispatcher
class MiddlewareDispatcher
Additional Inherited Members
Detailed Description
Definition at line 47 of file RouterDispatcher.h.
Member Function Documentation
dispatch() [1/2]
void express::dispatcher::RouterDispatcher::dispatch (const RouterDispatcher * parentRouter, const std::string & parentMountPath, const MountPoint & mountPoint, Request & req, Response & res) const override private virtual
Implements express::dispatcher::Dispatcher.
Definition at line 36 of file RouterDispatcher.cpp.
{
         std::string absoluteMountPath = path_concat(parentMountPath, mountPoint.relativeMountPath);
         // TODO: Fix regex-match
         if ((req.path.rfind(absoluteMountPath, 0) == 0 &&
              (mountPoint.method == "use" || req.method == mountPoint.method || mountPoint.method == "all"))) {
             for (const Route& route : routes) {
                 route.dispatch(absoluteMountPath, req, res);
                 if (!state.proceed) {
                     break;
                 }
             }
         }
         returnTo(parentRouter);
     }
References express::dispatcher::MountPoint::method, web::http::server::Request::method, express::Request::path, express::dispatcher::path_concat(), express::dispatcher::State::proceed, express::dispatcher::MountPoint::relativeMountPath, returnTo(), routes, and state.
dispatch() [2/2]
void express::dispatcher::RouterDispatcher::dispatch (Request & req, Response & res) const
Definition at line 32 of file RouterDispatcher.cpp.
{
         dispatch(nullptr, "/", MountPoint("use", "/"), req, res);
     }
getState()
State & express::dispatcher::RouterDispatcher::getState () const private
Definition at line 62 of file RouterDispatcher.cpp.
{
         return state;
     }
References state.
Referenced by express::dispatcher::MiddlewareDispatcher::dispatch().
returnTo()
void express::dispatcher::RouterDispatcher::returnTo (const RouterDispatcher * parentRouter) const private
Definition at line 66 of file RouterDispatcher.cpp.
{
         if (parentRouter) {
             parentRouter->state.proceed = state.proceed | state.parentProceed;
         }
         state.proceed = true;
         state.parentProceed = false;
     }
References express::dispatcher::State::parentProceed, express::dispatcher::State::proceed, and state.
Referenced by dispatch().
terminate()
void express::dispatcher::RouterDispatcher::terminate () const private
Definition at line 58 of file RouterDispatcher.cpp.
{
         state.proceed = false;
     }
References express::dispatcher::State::proceed, and state.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), and express::dispatcher::MiddlewareDispatcher::dispatch().
Friends And Related Function Documentation
ApplicationDispatcher
friend class ApplicationDispatcher friend
Definition at line 68 of file RouterDispatcher.h.
express::Router
friend class express::Router friend
Definition at line 67 of file RouterDispatcher.h.
MiddlewareDispatcher
friend class MiddlewareDispatcher friend
Definition at line 69 of file RouterDispatcher.h.
Member Data Documentation
routes
std::list<Route> express::dispatcher::RouterDispatcher::routes private
Definition at line 64 of file RouterDispatcher.h.
Referenced by dispatch().
state
State express::dispatcher::RouterDispatcher::state mutable private
Definition at line 65 of file RouterDispatcher.h.
Referenced by dispatch(), getState(), returnTo(), and terminate().
The documentation for this class was generated from the following files:
express/dispatcher/RouterDispatcher.h
express/dispatcher/RouterDispatcher.cpp