snode.c: express::middleware::VHost Class Reference
express::middleware::VHost Class Reference
#include <VHost.h>
Protected Member Functions
VHost (const std::string &host)
Static Protected Member Functions
static class VHost & instance (const std::string &host)
Private Attributes
std::string host
Friends
class VHost & VHost (const std::string &host)
Additional Inherited Members
Public Member Functions inherited from express::Router
Router ()
Router (const Router &router)
Router (Router &&router)
Router & operator= (const Router &router)
Router & operator= (Router &&router)
Router & use (const Router &router)
Router & use (const std::string &relativeMountPath, const Router &router)
Router & use (const std::function< void(Request &req, Response &res)> &lambda)
Router & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & use (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & all (const Router &router)
Router & all (const std::string &relativeMountPath, const Router &router)
Router & all (const std::function< void(Request &req, Response &res)> &lambda)
Router & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & all (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & get (const Router &router)
Router & get (const std::string &relativeMountPath, const Router &router)
Router & get (const std::function< void(Request &req, Response &res)> &lambda)
Router & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & get (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & put (const Router &router)
Router & put (const std::string &relativeMountPath, const Router &router)
Router & put (const std::function< void(Request &req, Response &res)> &lambda)
Router & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & put (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & post (const Router &router)
Router & post (const std::string &relativeMountPath, const Router &router)
Router & post (const std::function< void(Request &req, Response &res)> &lambda)
Router & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & post (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & del (const Router &router)
Router & del (const std::string &relativeMountPath, const Router &router)
Router & del (const std::function< void(Request &req, Response &res)> &lambda)
Router & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & del (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & connect (const Router &router)
Router & connect (const std::string &relativeMountPath, const Router &router)
Router & connect (const std::function< void(Request &req, Response &res)> &lambda)
Router & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & connect (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & options (const Router &router)
Router & options (const std::string &relativeMountPath, const Router &router)
Router & options (const std::function< void(Request &req, Response &res)> &lambda)
Router & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & options (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & trace (const Router &router)
Router & trace (const std::string &relativeMountPath, const Router &router)
Router & trace (const std::function< void(Request &req, Response &res)> &lambda)
Router & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & trace (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & patch (const Router &router)
Router & patch (const std::string &relativeMountPath, const Router &router)
Router & patch (const std::function< void(Request &req, Response &res)> &lambda)
Router & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & patch (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & head (const Router &router)
Router & head (const std::string &relativeMountPath, const Router &router)
Router & head (const std::function< void(Request &req, Response &res)> &lambda)
Router & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & head (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Protected Attributes inherited from express::Router
std::shared_ptr< express::dispatcher::RouterDispatcher > routerDispatcher
Detailed Description
Definition at line 32 of file VHost.h.
Constructor & Destructor Documentation
VHost()
express::middleware::VHost::VHost (const std::string & host) explicit protected
Definition at line 30 of file VHost.cpp.
         : host(host) {
         use([&host = this->host] MIDDLEWARE(req, res, next) {
             if (req.header("Host") == host) {
                 next();
             } else {
                 next("route");
             }
         });
     }
References host, MIDDLEWARE, and express::Router::use().
Referenced by instance().
Member Function Documentation
instance()
class VHost & express::middleware::VHost::instance (const std::string & host) static protected
Definition at line 41 of file VHost.cpp.
{
         // Keep all created vhost middlewares alive
         static std::list<std::shared_ptr<class VHost>> vhostMiddlewares;
         std::shared_ptr<VHost> vhost = std::shared_ptr<VHost>(new VHost(host));
         vhostMiddlewares.push_back(vhost);
         return *vhost;
     }
References host, and VHost().
Referenced by VHost.
Friends And Related Function Documentation
VHost
class VHost& VHost (const std::string & host) friend
Definition at line 52 of file VHost.cpp.
{
         return VHost::instance(host);
     }
References instance().
Member Data Documentation
host
std::string express::middleware::VHost::host private
Definition at line 38 of file VHost.h.
Referenced by instance(), and VHost().
The documentation for this class was generated from the following files:
express/middleware/VHost.h
express/middleware/VHost.cpp