snode.c: net::ServerConfig Class Reference
net::ServerConfig Class Reference
#include <ServerConfig.h>
Public Member Functions
ServerConfig (const std::string &name)
int getBacklog () const
Public Member Functions inherited from net::Config
Config (const std::string &name)
const std::string & getName () const
int getReadTimeout () const
int getWriteTimeout () const
Private Attributes
CLI::Option * serverBacklogOpt = nullptr
int backlog
Additional Inherited Members
Public Attributes inherited from net::Config
CLI::App * serverSc = nullptr
Protected Member Functions inherited from net::Config
void finish ()
Detailed Description
Definition at line 36 of file ServerConfig.h.
Constructor & Destructor Documentation
ServerConfig()
net::ServerConfig::ServerConfig (const std::string & name) explicit
Definition at line 29 of file ServerConfig.cpp.
         : Config(name) {
         serverBacklogOpt = serverSc->add_option("-b,--backlog", backlog, "Server listen backlog");
         serverBacklogOpt->type_name("[backlog]");
         serverBacklogOpt->default_val(5);
         serverBacklogOpt->configurable();
     }
References CLI::App::add_option(), backlog, CLI::OptionBase< CRTP >::configurable(), CLI::Option::default_val(), serverBacklogOpt, net::Config::serverSc, and CLI::Option::type_name().
Member Function Documentation
getBacklog()
int net::ServerConfig::getBacklog () const
Definition at line 37 of file ServerConfig.cpp.
{
         return backlog;
     }
References backlog.
Referenced by net::in::stream::ServerSocket::listen(), and net::in6::stream::ServerSocket::listen().
Member Data Documentation
backlog
int net::ServerConfig::backlog private
Definition at line 45 of file ServerConfig.h.
Referenced by getBacklog(), and ServerConfig().
serverBacklogOpt
CLI::Option* net::ServerConfig::serverBacklogOpt = nullptr private
Definition at line 43 of file ServerConfig.h.
Referenced by ServerConfig().
The documentation for this class was generated from the following files:
net/ServerConfig.h
net/ServerConfig.cpp