snode.c: core::socket::SocketContext Class Reference
core::socket::SocketContext Class Reference abstract
#include <SocketContext.h>
Public Member Functions
void setTimeout (const utils::Timeval &timeout)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
ssize_t readFromPeer (char *junk, std::size_t junklen)
void shutdownRead ()
void shutdownWrite ()
void shutdown ()
void close ()
SocketContext * switchSocketContext (core::socket::SocketContextFactory *socketContextFactory)
Protected Member Functions
SocketContext (core::socket::SocketConnection *socketConnection)
virtual ~SocketContext ()=default
Private Member Functions
virtual void onConnected ()
virtual void onDisconnected ()
virtual void onReceiveFromPeer ()=0
virtual void onWriteError (int errnum)
virtual void onReadError (int errnum)
Private Attributes
core::socket::SocketConnection * socketConnection
Friends
class core::socket::SocketConnection
Detailed Description
Definition at line 43 of file SocketContext.h.
Constructor & Destructor Documentation
SocketContext()
core::socket::SocketContext::SocketContext (core::socket::SocketConnection * socketConnection) explicit protected
Definition at line 31 of file SocketContext.cpp.
         : socketConnection(socketConnection) {
     }
~SocketContext()
virtual core::socket::SocketContext::~SocketContext () protected virtual default
Reimplemented in web::http::server::SocketContext< RequestT, ResponseT >, and web::http::client::SocketContext< RequestT, ResponseT >.
Member Function Documentation
close()
void core::socket::SocketContext::close ()
Definition at line 84 of file SocketContext.cpp.
{
         socketConnection->close();
     }
References core::socket::SocketConnection::close(), and socketConnection.
Referenced by web::http::client::Request::enqueue(), web::http::server::Response::enqueue(), web::http::client::Request::error(), web::http::server::Response::error(), express::Response::sendFile(), web::http::client::Request::upgrade(), and web::http::client::Response::upgrade().
getLocalAddressAsString()
std::string core::socket::SocketContext::getLocalAddressAsString () const
Definition at line 47 of file SocketContext.cpp.
{
         return socketConnection->getLocalAddressAsString();
     }
References core::socket::SocketConnection::getLocalAddressAsString(), and socketConnection.
getRemoteAddressAsString()
std::string core::socket::SocketContext::getRemoteAddressAsString () const
Definition at line 51 of file SocketContext.cpp.
{
         return socketConnection->getRemoteAddressAsString();
     }
References core::socket::SocketConnection::getRemoteAddressAsString(), and socketConnection.
onConnected()
void core::socket::SocketContext::onConnected () private virtual
Reimplemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, web::http::server::SocketContext< RequestT, ResponseT >, and web::http::client::SocketContext< RequestT, ResponseT >.
Definition at line 63 of file SocketContext.cpp.
{
         PLOG(INFO) << "Protocol connected";
     }
Referenced by core::socket::SocketConnection::onConnected().
onDisconnected()
void core::socket::SocketContext::onDisconnected () private virtual
Reimplemented in web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, web::http::server::SocketContext< RequestT, ResponseT >, and web::http::client::SocketContext< RequestT, ResponseT >.
Definition at line 67 of file SocketContext.cpp.
{
         PLOG(INFO) << "Protocol disconnected";
     }
Referenced by core::socket::SocketConnection::onDisconnected().
onReadError()
void core::socket::SocketContext::onReadError (int errnum) private virtual
Definition at line 95 of file SocketContext.cpp.
                                               { // By default we do a cross-shutdown. Override this method in case your protocol still
                                                   // wants to send data after peers sending side has closed the connection.
         if (errnum != 0) {
             PLOG(ERROR) << "OnReadError: " << errnum;
         }
         shutdownWrite();
     }
References core::ERROR, and shutdownWrite().
Referenced by core::socket::SocketConnection::onReadError().
onReceiveFromPeer()
virtual void core::socket::SocketContext::onReceiveFromPeer () private pure virtual
Implemented in web::http::SocketContext, web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >, web::websocket::SocketContextUpgrade< SubProtocol, web::http::server::Request, web::http::server::Response >, web::http::server::SocketContext< RequestT, ResponseT >, and web::http::client::SocketContext< RequestT, ResponseT >.
Referenced by core::socket::SocketConnection::onReceiveFromPeer().
onWriteError()
void core::socket::SocketContext::onWriteError (int errnum) private virtual
Definition at line 88 of file SocketContext.cpp.
{
         if (errnum != 0) {
             PLOG(ERROR) << "OnWriteError: " << errnum;
         }
         shutdownRead();
     }
References core::ERROR, and shutdownRead().
Referenced by core::socket::SocketConnection::onWriteError().
readFromPeer()
ssize_t core::socket::SocketContext::readFromPeer (char * junk, std::size_t junklen)
Definition at line 43 of file SocketContext.cpp.
{
         return socketConnection->readFromPeer(junk, junklen);
     }
References core::socket::SocketConnection::readFromPeer(), and socketConnection.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::readFrameData(), web::http::Parser::readHeaderLine(), and web::http::Parser::readStartLine().
sendToPeer() [1/2]
void core::socket::SocketContext::sendToPeer (const char * junk, std::size_t junkLen)
Definition at line 35 of file SocketContext.cpp.
{
         socketConnection->sendToPeer(junk, junkLen);
     }
References core::socket::SocketConnection::sendToPeer(), and socketConnection.
Referenced by web::http::client::Request::enqueue(), web::http::server::Response::enqueue(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendFrameData(), and sendToPeer().
sendToPeer() [2/2]
void core::socket::SocketContext::sendToPeer (const std::string & data)
Definition at line 39 of file SocketContext.cpp.
{
         sendToPeer(data.data(), data.length());
     }
References sendToPeer().
setTimeout()
void core::socket::SocketContext::setTimeout (const utils::Timeval & timeout)
Definition at line 59 of file SocketContext.cpp.
{
         socketConnection->setTimeout(timeout);
     }
References core::socket::SocketConnection::setTimeout(), and socketConnection.
Referenced by web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose().
shutdown()
void core::socket::SocketContext::shutdown ()
Definition at line 79 of file SocketContext.cpp.
{
         shutdownRead();
         shutdownWrite();
     }
References shutdownRead(), and shutdownWrite().
shutdownRead()
void core::socket::SocketContext::shutdownRead ()
Definition at line 71 of file SocketContext.cpp.
{
         socketConnection->shutdownRead();
     }
References core::socket::SocketConnection::shutdownRead(), and socketConnection.
Referenced by onWriteError(), and shutdown().
shutdownWrite()
void core::socket::SocketContext::shutdownWrite ()
Definition at line 75 of file SocketContext.cpp.
{
         socketConnection->shutdownWrite();
     }
References core::socket::SocketConnection::shutdownWrite(), and socketConnection.
Referenced by onReadError(), web::websocket::SocketContextUpgrade< SubProtocolT, RequestT, ResponseT >::sendClose(), and shutdown().
switchSocketContext()
SocketContext * core::socket::SocketContext::switchSocketContext (core::socket::SocketContextFactory * socketContextFactory)
Definition at line 55 of file SocketContext.cpp.
{
         return socketConnection->switchSocketContext(socketContextFactory);
     }
References socketConnection, and core::socket::SocketConnection::switchSocketContext().
Referenced by web::http::server::Response::upgrade(), and web::http::client::Response::upgrade().
Friends And Related Function Documentation
core::socket::SocketConnection
friend class core::socket::SocketConnection friend
Definition at line 78 of file SocketContext.h.
Member Data Documentation
socketConnection
core::socket::SocketConnection* core::socket::SocketContext::socketConnection private
Definition at line 76 of file SocketContext.h.
Referenced by close(), web::websocket::client::SocketContextUpgrade::create(), web::websocket::server::SocketContextUpgrade::create(), getLocalAddressAsString(), getRemoteAddressAsString(), readFromPeer(), sendToPeer(), setTimeout(), shutdownRead(), shutdownWrite(), and switchSocketContext().
The documentation for this class was generated from the following files:
core/socket/SocketContext.h
core/socket/SocketContext.cpp