snode.c: core::SNodeC Class Reference
core::SNodeC Class Reference
#include <SNodeC.h>
Static Public Member Functions
static void init (int argc, char *argv[])
static int start (const utils::Timeval &timeOut={LONG_MAX, 0})
static void stop ()
static TickStatus tick (const utils::Timeval &timeOut=0)
static void free ()
Private Member Functions
SNodeC ()=delete
~SNodeC ()=delete
void * operator new (std::size_t count)=delete
Detailed Description
Definition at line 36 of file SNodeC.h.
Constructor & Destructor Documentation
SNodeC()
core::SNodeC::SNodeC () private delete
~SNodeC()
core::SNodeC::~SNodeC () private delete
Member Function Documentation
free()
void core::SNodeC::free () static
Definition at line 45 of file SNodeC.cpp.
                       {
         EventLoop::free();
     }
References core::EventLoop::free().
Referenced by express::WebApp::free().
init()
void core::SNodeC::init (int argc, char * argv[]) static
Definition at line 29 of file SNodeC.cpp.
{
         EventLoop::init(argc, argv);
     }
References core::EventLoop::init().
Referenced by express::WebApp::init().
operator new()
void* core::SNodeC::operator new (std::size_t count) private delete
start()
int core::SNodeC::start (const utils::Timeval & timeOut = {LONG_MAX, 0}) static
Definition at line 33 of file SNodeC.cpp.
{
         return EventLoop::start(timeOut);
     }
References core::EventLoop::start().
Referenced by express::WebApp::start().
stop()
void core::SNodeC::stop () static
Definition at line 37 of file SNodeC.cpp.
                       {
         EventLoop::stop();
     }
References core::EventLoop::stop().
Referenced by express::WebApp::stop().
tick()
TickStatus core::SNodeC::tick (const utils::Timeval & timeOut = 0) static
Definition at line 41 of file SNodeC.cpp.
{
         return EventLoop::tick(timeOut);
     }
References core::EventLoop::tick().
Referenced by express::WebApp::tick().
The documentation for this class was generated from the following files:
core/SNodeC.h
core/SNodeC.cpp