snode.c: core::timer::SingleshotTimer Class Reference
core::timer::SingleshotTimer Class Reference
#include <SingleshotTimer.h>
Public Member Functions
SingleshotTimer (const std::function< void(const void *)> &dispatcher, const utils::Timeval &timeout, const void *arg)
~SingleshotTimer () override=default
bool trigger () override
Private Member Functions
SingleshotTimer & operator= (const SingleshotTimer &timer)=delete
void cancel () override
void unobservedEvent () override
Private Attributes
std::function< void(const void *)> dispatcher
Additional Inherited Members
Static Public Member Functions inherited from core::timer::Timer
static IntervalTimer & intervalTimer (const std::function< void(const void *, const std::function< void()> &stop)> &dispatcher, const utils::Timeval &timeout, const void *arg)
static IntervalTimer & intervalTimer (const std::function< void(const void *)> &dispatcher, const utils::Timeval &timeout, const void *arg)
static SingleshotTimer & singleshotTimer (const std::function< void(const void *)> &dispatcher, const utils::Timeval &timeout, const void *arg)
Protected Member Functions inherited from core::timer::Timer
virtual ~Timer ()=default
void unobservedEvent () override
utils::Timeval getTimeout () const override
TimerEventReceiver (const TimerEventReceiver &)=delete
TimerEventReceiver (const utils::Timeval &delay, const void *arg)
Protected Member Functions inherited from core::TimerEventReceiver
void update ()
TimerEventReceiver (const TimerEventReceiver &)=delete
TimerEventReceiver & operator= (const TimerEventReceiver &)=delete
TimerEventReceiver (const utils::Timeval &delay, const void *arg)
Protected Attributes inherited from core::TimerEventReceiver
utils::Timeval absoluteTimeout
utils::Timeval delay
const void * arg
Detailed Description
Definition at line 30 of file SingleshotTimer.h.
Constructor & Destructor Documentation
SingleshotTimer()
core::timer::SingleshotTimer::SingleshotTimer (const std::function< void(const void *)> & dispatcher, const utils::Timeval & timeout, const void * arg) inline
Definition at line 34 of file SingleshotTimer.h.
             : Timer(timeout, arg)
             , dispatcher(dispatcher) {
         }
~SingleshotTimer()
core::timer::SingleshotTimer::~SingleshotTimer () override default
Member Function Documentation
cancel()
void core::timer::SingleshotTimer::cancel () inline override private virtual
Reimplemented from core::timer::Timer.
Definition at line 48 of file SingleshotTimer.h.
{
             dispatcher = nullptr;
             core::timer::Timer::cancel();
         }
References core::timer::Timer::cancel(), and dispatcher.
Referenced by trigger().
operator=()
SingleshotTimer& core::timer::SingleshotTimer::operator= (const SingleshotTimer & timer) private delete
trigger()
bool core::timer::SingleshotTimer::trigger () inline override virtual
Implements core::TimerEventReceiver.
Definition at line 41 of file SingleshotTimer.h.
{
             dispatcher(arg);
             cancel();
             return false;
         }
References core::TimerEventReceiver::arg, cancel(), and dispatcher.
unobservedEvent()
void core::timer::SingleshotTimer::unobservedEvent () inline override private virtual
Implements core::TimerEventReceiver.
Definition at line 53 of file SingleshotTimer.h.
{
             dispatcher = nullptr;
             core::timer::Timer::unobservedEvent();
         }
References dispatcher, and core::timer::Timer::unobservedEvent().
Member Data Documentation
dispatcher
std::function<void(const void*)> core::timer::SingleshotTimer::dispatcher private
Definition at line 58 of file SingleshotTimer.h.
Referenced by cancel(), trigger(), and unobservedEvent().
The documentation for this class was generated from the following file:
core/timer/SingleshotTimer.h