snode.c: core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT > Class Template Reference
core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT > Class Template Reference
#include <SocketConnector.h>
Public Types
using ClientConfig = typename Super::ClientConfig
using SocketConnection = typename Super::SocketConnection
Public Member Functions
SocketConnector (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketConnector () override
void connect (const std::shared_ptr< ClientConfig > &clientConfig, const std::function< void(const SocketAddress &, int)> &onError)
Protected Attributes
SSL_CTX * ctx = nullptr
Protected Attributes inherited from core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
std::shared_ptr< ClientConfig > clientConfig
std::function< void(const SocketAddress &socketAddress, int err)> onError
std::map< std::string, std::any > options
Protected Attributes inherited from core::EventReceiver
Event event
Private Types
using Super = core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
using SocketAddress = typename Super::SocketAddress
Additional Inherited Members
Protected Types inherited from core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
using ClientConfig = ClientConfigT
using SocketConnection = core::socket::stream::tls::SocketConnection< SocketT >
using SocketAddress = typename Socket::SocketAddress
Protected Member Functions inherited from core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >
void destruct ()
SocketConnector (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketConnector () override=default
void connect (const std::shared_ptr< ClientConfig > &clientConfig, const std::function< void(const SocketAddress &, int)> &onError)
Protected Member Functions inherited from core::eventreceiver::InitConnectEventReceiver
InitConnectEventReceiver (const std::string &name)
void dispatch (const utils::Timeval &currentTime) override
Protected Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish () const
const std::string & getName ()
Protected Member Functions inherited from core::eventreceiver::ConnectEventReceiver
ConnectEventReceiver (const std::string &name, const utils::Timeval &timeout=10)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
void enable (int fd)
void disable ()
void suspend ()
void resume ()
void setTimeout (const utils::Timeval &timeout)
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
int getRegisteredFd ()
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
bool isEnabled () const
bool isSuspended () const
Protected Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Detailed Description
template<typename ClientConfigT, typename SocketT>
class core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >
Definition at line 36 of file SocketConnector.h.
Member Typedef Documentation
ClientConfig
template<typename ClientConfigT , typename SocketT > using core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::ClientConfig = typename Super::ClientConfig
Definition at line 44 of file SocketConnector.h.
SocketAddress
template<typename ClientConfigT , typename SocketT > using core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::SocketAddress = typename Super::SocketAddress private
Definition at line 41 of file SocketConnector.h.
SocketConnection
template<typename ClientConfigT , typename SocketT > using core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::SocketConnection = typename Super::SocketConnection
Definition at line 45 of file SocketConnector.h.
Super
template<typename ClientConfigT , typename SocketT > using core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::Super = core::socket::stream::SocketConnector<ClientConfigT, core::socket::stream::tls::SocketConnection<SocketT> > private
Definition at line 39 of file SocketConnector.h.
Constructor & Destructor Documentation
SocketConnector()
template<typename ClientConfigT , typename SocketT > core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::SocketConnector (const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options) inline
Definition at line 47 of file SocketConnector.h.
             : Super(
                   socketContextFactory,
                   onConnect,
                   [onConnected, this](SocketConnection* socketConnection) -> void { // onConnect
                       SSL* ssl = socketConnection->startSSL(
                           this->ctx, this->clientConfig->getInitTimeout(), this->clientConfig->getShutdownTimeout());
                       if (ssl != nullptr) {
                           ssl_set_sni(ssl, this->options);
                           SSL_set_connect_state(ssl);
                           socketConnection->doSSLHandshake(
                               [onConnected, socketConnection](void) -> void { // onSuccess
                                   LOG(INFO) << "SSL/TLS initial handshake success";
                                   onConnected(socketConnection);
                               },
                               [this](void) -> void { // onTimeout
                                   LOG(WARNING) << "SSL/TLS initial handshake timed out";
                                   this->onError(this->clientConfig->getRemoteAddress(), ETIMEDOUT);
                               },
                               [this](int sslErr) -> void { // onError
                                   ssl_log("SSL/TLS initial handshake failed", sslErr);
                                   this->onError(this->clientConfig->getRemoteAddress(), -sslErr);
                               });
                       } else {
                           socketConnection->close();
                           ssl_log_error("SSL/TLS initialization failed");
                           this->onError(this->clientConfig->getRemoteAddress(), -SSL_ERROR_SSL);
                       }
                   },
                   [onDisconnect](SocketConnection* socketConnection) -> void { // onDisconnect
                       socketConnection->stopSSL();
                       onDisconnect(socketConnection);
                   },
                   options) {
             ctx = ssl_ctx_new(options, false);
         }
References core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >::clientConfig, core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >::onConnected, core::socket::stream::SocketConnector< ClientConfigT, core::socket::stream::tls::SocketConnection< SocketT > >::onError, core::socket::stream::tls::ssl_log(), and core::socket::stream::tls::ssl_set_sni().
~SocketConnector()
template<typename ClientConfigT , typename SocketT > core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::~SocketConnector () inline override
Definition at line 91 of file SocketConnector.h.
{
             ssl_ctx_free(ctx);
         }
References core::socket::stream::tls::ssl_ctx_free().
Member Function Documentation
connect()
template<typename ClientConfigT , typename SocketT > void core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::connect (const std::shared_ptr< ClientConfig > & clientConfig, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 95 of file SocketConnector.h.
{
             if (ctx == nullptr) {
                 errno = EINVAL;
                 onError(clientConfig->getRemoteAddress(), errno);
                 Super::destruct();
             } else {
                 Super::connect(clientConfig, onError);
             }
         }
References core::system::connect().
Member Data Documentation
ctx
template<typename ClientConfigT , typename SocketT > SSL_CTX* core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::ctx = nullptr protected
Definition at line 106 of file SocketConnector.h.
The documentation for this class was generated from the following file:
core/socket/stream/tls/SocketConnector.h