snode.c: core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT > Class Template Reference
core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT > Class Template Reference
#include <SocketConnector.h>
Public Types
using Config = typename ClientSocket::Config
using SocketAddress = typename ClientSocket::SocketAddress
Public Member Functions
SocketConnector (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketConnector () override=default
void connect (const std::shared_ptr< Config > &clientConfig, const std::function< void(const SocketAddress &, int)> &onError)
Protected Types
using SocketConnection = SocketConnectionT< Socket >
Protected Member Functions
void destruct ()
Protected Member Functions inherited from core::eventreceiver::InitConnectEventReceiver
InitConnectEventReceiver (const std::string &name)
Protected Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish ()
void unPublish ()
const std::string & getName ()
Protected Member Functions inherited from core::eventreceiver::ConnectEventReceiver
ConnectEventReceiver (const std::string &name, const utils::Timeval &timeout=10)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
void enable (int fd)
void disable ()
void suspend ()
void resume ()
void setTimeout (const utils::Timeval &timeout)
void checkTimeout (const utils::Timeval &currentTime)
virtual void terminate ()
int getRegisteredFd ()
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
bool isEnabled () const
bool isSuspended () const
Protected Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
Protected Attributes
std::shared_ptr< Config > config = nullptr
std::function< void(const SocketAddress &socketAddress, int err)> onError
std::map< std::string, std::any > options
Protected Attributes inherited from core::EventReceiver
Event _event
Private Types
using ClientSocket = ClientSocketT
using Socket = typename ClientSocket::Socket
Private Member Functions
SocketConnector ()=delete
SocketConnector (const SocketConnector &)=delete
SocketConnector & operator= (const SocketConnector &)=delete
void initConnectEvent () override
void connectEvent () override
void unobservedEvent () override
Private Attributes
std::shared_ptr< core::socket::SocketContextFactory > socketContextFactory = nullptr
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onDestruct
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Detailed Description
template<typename ClientSocketT, template< typename SocketT > class SocketConnectionT>
class core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >
Definition at line 44 of file SocketConnector.h.
Member Typedef Documentation
ClientSocket
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::ClientSocket = ClientSocketT private
Definition at line 53 of file SocketConnector.h.
Config
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::Config = typename ClientSocket::Config
Definition at line 60 of file SocketConnector.h.
Socket
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::Socket = typename ClientSocket::Socket private
Definition at line 54 of file SocketConnector.h.
SocketAddress
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::SocketAddress = typename ClientSocket::SocketAddress
Definition at line 61 of file SocketConnector.h.
SocketConnection
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> using core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::SocketConnection = SocketConnectionT<Socket> protected
Definition at line 57 of file SocketConnector.h.
Constructor & Destructor Documentation
SocketConnector() [1/3]
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::SocketConnector () private delete
SocketConnector() [2/3]
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::SocketConnector (const SocketConnector< ClientSocketT, SocketConnectionT > &) private delete
SocketConnector() [3/3]
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::SocketConnector (const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options) inline
Definition at line 63 of file SocketConnector.h.
             : core::eventreceiver::InitConnectEventReceiver("SocketConnector")
             , core::eventreceiver::ConnectEventReceiver("SocketConnector")
             , socketContextFactory(socketContextFactory)
             , onConnect(onConnect)
             , onConnected(onConnected)
             , onDisconnect(onDisconnect)
             , options(options) {
         }
~SocketConnector()
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::~SocketConnector () override default
Member Function Documentation
connect()
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::connect (const std::shared_ptr< Config > & clientConfig, const std::function< void(const SocketAddress &, int)> & onError) inline
Definition at line 79 of file SocketConnector.h.
{
             this->config = clientConfig;
             this->onError = onError;
             InitConnectEventReceiver::publish();
         }
References core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::config, and core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::onError.
connectEvent()
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::connectEvent () inline override private virtual
Implements core::eventreceiver::ConnectEventReceiver.
Definition at line 117 of file SocketConnector.h.
{
             int cErrno = -1;
             socklen_t cErrnoLen = sizeof(cErrno);
             int err = core::system::getsockopt(SocketConnector::getFd(), SOL_SOCKET, SO_ERROR, &cErrno, &cErrnoLen);
             if (err == 0) {
                 errno = cErrno;
                 if (errno != EINPROGRESS) {
                     if (errno == 0) {
                         disable();
                         typename SocketAddress::SockAddr localAddress{};
                         socklen_t localAddressLength = sizeof(localAddress);
                         typename SocketAddress::SockAddr remoteAddress{};
                         socklen_t remoteAddressLength = sizeof(remoteAddress);
                         if (core::system::getsockname(Socket::getFd(), reinterpret_cast<sockaddr*>(&localAddress), &localAddressLength) ==
                                 0 &&
                             core::system::getpeername(Socket::getFd(), reinterpret_cast<sockaddr*>(&remoteAddress), &remoteAddressLength) ==
                                 0) {
                             SocketConnection* socketConnection = new SocketConnection(SocketConnector::getFd(),
                                                                                       socketContextFactory,
                                                                                       SocketAddress(localAddress),
                                                                                       SocketAddress(remoteAddress),
                                                                                       onConnect,
                                                                                       onDisconnect,
                                                                                       config->getReadTimeout(),
                                                                                       config->getWriteTimeout(),
                                                                                       config->getReadBlockSize(),
                                                                                       config->getWriteBlockSize(),
                                                                                       config->getTerminateTimeout());
                             onConnected(socketConnection);
                             Socket::dontClose(true);
                         } else {
                             onError(config->getRemoteAddress(), errno);
                             disable();
                         }
                     } else {
                         onError(config->getRemoteAddress(), errno);
                         disable();
                     }
                 } else {
                     // Do nothing: connect() still in progress
                 }
             } else {
                 onError(config->getRemoteAddress(), errno);
                 disable();
             }
         }
References core::system::getpeername(), core::system::getsockname(), and core::system::getsockopt().
destruct()
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::destruct () inline protected
Definition at line 172 of file SocketConnector.h.
{
             delete this;
         }
Referenced by core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::initConnectEvent().
initConnectEvent()
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::initConnectEvent () inline override private virtual
Implements core::eventreceiver::InitConnectEventReceiver.
Definition at line 87 of file SocketConnector.h.
{
             Socket::open(
                 [this](int errnum) -> void {
                     if (errnum > 0) {
                         onError(config->getRemoteAddress(), errnum);
                         destruct();
                     } else {
                         Socket::bind(config->getLocalAddress(), [this](int errnum) -> void {
                             if (errnum > 0) {
                                 onError(config->getRemoteAddress(), errnum);
                                 destruct();
                             } else {
                                 int ret = core::system::connect(Socket::getFd(),
                                                                 &config->getRemoteAddress().getSockAddr(),
                                                                 config->getRemoteAddress().getSockAddrLen());
                                 if (ret == 0 || errno == EINPROGRESS) {
                                     enable(Socket::getFd());
                                     onError(config->getRemoteAddress(), 0);
                                 } else {
                                     onError(config->getRemoteAddress(), errno);
                                     destruct();
                                 }
                             }
                         });
                     }
                 },
                 SOCK_NONBLOCK);
         }
References core::system::bind(), core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::config, core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::destruct(), core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::onError, and core::system::open().
operator=()
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> SocketConnector& core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::operator= (const SocketConnector< ClientSocketT, SocketConnectionT > &) private delete
unobservedEvent()
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> void core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::unobservedEvent () inline override private virtual
Implements core::Observer.
Definition at line 179 of file SocketConnector.h.
{
             destruct();
         }
Member Data Documentation
config
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::shared_ptr<Config> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::config = nullptr protected
Definition at line 176 of file SocketConnector.h.
Referenced by core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::connect(), and core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::initConnectEvent().
onConnect
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::function<void(SocketConnection*)> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::onConnect private
Definition at line 185 of file SocketConnector.h.
onConnected
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::function<void(SocketConnection*)> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::onConnected private
Definition at line 187 of file SocketConnector.h.
onDestruct
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::function<void(SocketConnection*)> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::onDestruct private
Definition at line 186 of file SocketConnector.h.
onDisconnect
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::function<void(SocketConnection*)> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::onDisconnect private
Definition at line 188 of file SocketConnector.h.
onError
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::function<void(const SocketAddress& socketAddress, int err)> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::onError protected
Definition at line 191 of file SocketConnector.h.
Referenced by core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::connect(), and core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::initConnectEvent().
options
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::map<std::string, std::any> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::options protected
Definition at line 193 of file SocketConnector.h.
socketContextFactory
template<typename ClientSocketT , template< typename SocketT > class SocketConnectionT> std::shared_ptr<core::socket::SocketContextFactory> core::socket::stream::SocketConnector< ClientSocketT, SocketConnectionT >::socketContextFactory = nullptr private
Definition at line 183 of file SocketConnector.h.
The documentation for this class was generated from the following file:
core/socket/stream/SocketConnector.h