snode.c: core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT > Class Template Reference
core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT > Class Template Reference
#include <SocketClient.h>
Public Types
using Socket = typename ClientSocket::Socket
using SocketConnection = typename SocketConnector::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Member Functions
SocketClient (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketClient ()=default
void connect (const std::function< void(int)> &onError) const override
void connect (const SocketAddress &remoteAddress, const SocketAddress &bindAddress, const std::function< void(int)> &onError) const override
void connect (const SocketAddress &remoteAddress, const std::function< void(int)> &onError) const override
void onConnect (const std::function< void(SocketConnection *)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Protected Types
using ClientSocket = ClientSocketT
using ClientConfig = ClientConfigT
using SocketConnector = SocketConnectorT
using SocketContextFactory = SocketContextFactoryT
Protected Attributes
ClientConfig clientConfig
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Private Member Functions
SocketClient ()=delete
Detailed Description
template<typename ClientSocketT, typename ClientConfigT, typename SocketConnectorT, typename SocketContextFactoryT>
class core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >
Definition at line 36 of file SocketClient.h.
Member Typedef Documentation
ClientConfig
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > using core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::ClientConfig = ClientConfigT protected
Definition at line 47 of file SocketClient.h.
ClientSocket
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > using core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::ClientSocket = ClientSocketT protected
Definition at line 46 of file SocketClient.h.
Socket
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > using core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::Socket = typename ClientSocket::Socket
Definition at line 52 of file SocketClient.h.
SocketAddress
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > using core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::SocketAddress = typename SocketConnection::Socket::SocketAddress
Definition at line 54 of file SocketClient.h.
SocketConnection
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > using core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::SocketConnection = typename SocketConnector::SocketConnection
Definition at line 53 of file SocketClient.h.
SocketConnector
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > using core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::SocketConnector = SocketConnectorT protected
Definition at line 48 of file SocketClient.h.
SocketContextFactory
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > using core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::SocketContextFactory = SocketContextFactoryT protected
Definition at line 49 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient() [1/2]
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::SocketClient () private delete
Sequence diagramm showing how a connect to a peer is performed.
SocketClient() [2/2]
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::SocketClient (const std::string & name, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 56 of file SocketClient.h.
                                                                 {{}})
             : clientConfig(name)
             , socketContextFactory(std::make_shared<SocketContextFactory>())
             , _onConnect(onConnect)
             , _onConnected(onConnected)
             , _onDisconnect(onDisconnect)
             , options(options) {
         }
~SocketClient()
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > virtual core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::~SocketClient () virtual default
Member Function Documentation
connect() [1/3]
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > void core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect (const SocketAddress & remoteAddress, const SocketAddress & bindAddress, const std::function< void(int)> & onError) const inline override
Definition at line 79 of file SocketClient.h.
{
             SocketConnector* socketConnector =
                 new SocketConnector(clientConfig, socketContextFactory, _onConnect, _onConnected, _onDisconnect, options);
             socketConnector->connect(remoteAddress, bindAddress, onError);
         }
References core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onConnect, core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onConnected, core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onDisconnect, core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::clientConfig, core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::options, and core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::socketContextFactory.
connect() [2/3]
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > void core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect (const SocketAddress & remoteAddress, const std::function< void(int)> & onError) const inline override
Definition at line 88 of file SocketClient.h.
{
             connect(remoteAddress, SocketAddress(), onError);
         }
References core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect().
connect() [3/3]
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > void core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect (const std::function< void(int)> & onError) const inline override
Definition at line 73 of file SocketClient.h.
{
             clientConfig.parse(true);
             connect(clientConfig.getConnectAddress(), clientConfig.getBindAddress(), onError);
         }
References core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::clientConfig.
Referenced by core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect().
getSocketContextFactory()
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::getSocketContextFactory () inline
Definition at line 104 of file SocketClient.h.
{
             return socketContextFactory;
         }
References core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::socketContextFactory.
onConnect()
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > void core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::onConnect (const std::function< void(SocketConnection *)> & onConnect) inline
Definition at line 92 of file SocketClient.h.
{
             _onConnect = onConnect;
         }
References core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onConnect.
onConnected()
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > void core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::onConnected (const std::function< void(SocketConnection *)> & onConnected) inline
Definition at line 96 of file SocketClient.h.
{
             _onConnected = onConnected;
         }
References core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onConnected.
onDisconnect()
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > void core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::onDisconnect (const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 100 of file SocketClient.h.
{
             _onDisconnect = onDisconnect;
         }
References core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onDisconnect.
Member Data Documentation
_onConnect
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onConnect protected
Definition at line 113 of file SocketClient.h.
Referenced by core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect(), and core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::onConnect().
_onConnected
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onConnected protected
Definition at line 114 of file SocketClient.h.
Referenced by core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect(), and core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::onConnected().
_onDisconnect
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::_onDisconnect protected
Definition at line 115 of file SocketClient.h.
Referenced by core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect(), and core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::onDisconnect().
clientConfig
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > ClientConfig core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::clientConfig protected
Definition at line 109 of file SocketClient.h.
Referenced by core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect().
options
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > std::map<std::string, std::any> core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::options protected
Definition at line 117 of file SocketClient.h.
Referenced by core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect().
socketContextFactory
template<typename ClientSocketT , typename ClientConfigT , typename SocketConnectorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::socketContextFactory protected
Definition at line 111 of file SocketClient.h.
Referenced by core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::connect(), and core::socket::stream::SocketClient< ClientSocketT, ClientConfigT, SocketConnectorT, SocketContextFactoryT >::getSocketContextFactory().
The documentation for this class was generated from the following file:
core/socket/stream/SocketClient.h