snode.c: net::in6::stream::ConfigConnect Class Reference
net::in6::stream::ConfigConnect Class Reference
#include <ConfigConnect.h>
Public Member Functions
ConfigConnect (CLI::App *baseSc)
const std::string & getConnectHost () const
uint16_t getConnectPort () const
SocketAddress getConnectAddress () const
Protected Member Functions
void required (bool req) const
Protected Attributes
CLI::App * connectSc = nullptr
CLI::Option * connectHostOpt = nullptr
CLI::Option * connectPortOpt = nullptr
Private Attributes
std::string connectHost = ""
uint16_t connectPort = 0
Detailed Description
Definition at line 38 of file ConfigConnect.h.
Constructor & Destructor Documentation
ConfigConnect()
net::in6::stream::ConfigConnect::ConfigConnect (CLI::App * baseSc) explicit
Definition at line 31 of file ConfigConnect.cpp.
{
         connectSc = baseSc->add_subcommand("connect");
         connectSc->description("Connect options");
         connectSc->configurable();
         connectHostOpt = connectSc->add_option("-a,--host", connectHost, "Host name or IP address");
         connectHostOpt->type_name("[hostname|ip]");
         connectHostOpt->default_val("0.0.0.0");
         connectHostOpt->configurable();
         connectPortOpt = connectSc->add_option("-p,--port", connectPort, "Port number");
         connectPortOpt->type_name("[uint16_t]");
         connectPortOpt->default_val(0);
         connectPortOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), connectHost, connectHostOpt, connectPort, connectPortOpt, connectSc, CLI::Option::default_val(), CLI::App::description(), and CLI::Option::type_name().
Member Function Documentation
getConnectAddress()
SocketAddress net::in6::stream::ConfigConnect::getConnectAddress () const
Definition at line 55 of file ConfigConnect.cpp.
{
         return SocketAddress(connectHost, connectPort);
     }
References connectHost, and connectPort.
getConnectHost()
const std::string & net::in6::stream::ConfigConnect::getConnectHost () const
Definition at line 47 of file ConfigConnect.cpp.
{
         return connectHost;
     }
References connectHost.
getConnectPort()
uint16_t net::in6::stream::ConfigConnect::getConnectPort () const
Definition at line 51 of file ConfigConnect.cpp.
{
         return connectPort;
     }
References connectPort.
required()
void net::in6::stream::ConfigConnect::required (bool req) const protected
Definition at line 59 of file ConfigConnect.cpp.
{
         utils::Config::instance().required(connectSc, req);
         utils::Config::instance().required(connectHostOpt, req);
         utils::Config::instance().required(connectPortOpt, req);
     }
References connectHostOpt, connectPortOpt, connectSc, utils::Config::instance(), and utils::Config::required().
Referenced by net::in6::stream::ClientConfig::required().
Member Data Documentation
connectHost
std::string net::in6::stream::ConfigConnect::connectHost = "" private
Definition at line 56 of file ConfigConnect.h.
Referenced by ConfigConnect(), getConnectAddress(), and getConnectHost().
connectHostOpt
CLI::Option* net::in6::stream::ConfigConnect::connectHostOpt = nullptr protected
Definition at line 52 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
connectPort
uint16_t net::in6::stream::ConfigConnect::connectPort = 0 private
Definition at line 57 of file ConfigConnect.h.
Referenced by ConfigConnect(), getConnectAddress(), and getConnectPort().
connectPortOpt
CLI::Option* net::in6::stream::ConfigConnect::connectPortOpt = nullptr protected
Definition at line 53 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
connectSc
CLI::App* net::in6::stream::ConfigConnect::connectSc = nullptr protected
Definition at line 51 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
The documentation for this class was generated from the following files:
net/in6/stream/ConfigConnect.h
net/in6/stream/ConfigConnect.cpp