snode.c: core::WriteEventReceiver Class Reference
core::WriteEventReceiver Class Reference abstract
#include <WriteEventReceiver.h>
Protected Member Functions
WriteEventReceiver (const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
~DescriptorEventReceiver ()=default
Private Member Functions
virtual void writeEvent ()=0
virtual void writeTimeout ()
void dispatchEvent () final
void timeoutEvent () final
bool continueImmediately () const final
virtual bool continueWriteImmediately () const
Additional Inherited Members
Public Member Functions inherited from core::DescriptorEventReceiver
int getRegisteredFd ()
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime) override
void triggered (const utils::Timeval &currentTime)
void disabled ()
virtual void terminate ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Public Member Functions inherited from core::EventReceiver
EventReceiver ()
virtual ~EventReceiver ()=default
void publish ()
Public Attributes inherited from core::DescriptorEventReceiver
utils::Timeval publisedTime
utils::Timeval lastTriggered
utils::Timeval maxInactivity
const utils::Timeval initialTimeout
int eventCounter = 0
Protected Attributes inherited from core::EventReceiver
Event event
Detailed Description
Definition at line 32 of file WriteEventReceiver.h.
Constructor & Destructor Documentation
WriteEventReceiver()
core::WriteEventReceiver::WriteEventReceiver (const utils::Timeval & timeout = 60) protected
Definition at line 30 of file WriteEventReceiver.cpp.
         : DescriptorEventReceiver(
               EventLoop::instance().getEventDispatcher().getDescriptorEventDispatcher(core::EventDispatcher::DISP_TYPE::WR), timeout) {
     }
Member Function Documentation
continueImmediately()
bool core::WriteEventReceiver::continueImmediately () const final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 51 of file WriteEventReceiver.cpp.
{
         return continueWriteImmediately();
     }
References continueWriteImmediately().
continueWriteImmediately()
bool core::WriteEventReceiver::continueWriteImmediately () const private virtual
Definition at line 39 of file WriteEventReceiver.cpp.
{
         return false;
     }
Referenced by continueImmediately().
dispatchEvent()
void core::WriteEventReceiver::dispatchEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 43 of file WriteEventReceiver.cpp.
{
         writeEvent();
     }
References writeEvent().
timeoutEvent()
void core::WriteEventReceiver::timeoutEvent () final private virtual
Implements core::DescriptorEventReceiver.
Definition at line 47 of file WriteEventReceiver.cpp.
{
         writeTimeout();
     }
References writeTimeout().
writeEvent()
virtual void core::WriteEventReceiver::writeEvent () private pure virtual
Implemented in core::socket::stream::SocketWriter< SocketT >, core::socket::stream::tls::TLSShutdown, core::socket::stream::tls::TLSHandshake, core::pipe::PipeSource, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by dispatchEvent().
writeTimeout()
void core::WriteEventReceiver::writeTimeout () private virtual
Reimplemented in core::socket::stream::tls::TLSShutdown, and core::socket::stream::tls::TLSHandshake.
Definition at line 35 of file WriteEventReceiver.cpp.
{
         disable();
     }
References core::DescriptorEventReceiver::disable().
Referenced by timeoutEvent().
The documentation for this class was generated from the following files:
core/WriteEventReceiver.h
core/WriteEventReceiver.cpp