snode.c: core::socket::SocketConnection Class Reference
core::socket::SocketConnection Class Reference abstract
#include <SocketConnection.h>
Public Member Functions
core::socket::SocketContext * getSocketContext ()
virtual void close ()=0
virtual void shutdownRead ()=0
virtual void shutdownWrite ()=0
virtual void setTimeout (const utils::Timeval &timeout)=0
virtual std::string getLocalAddressAsString () const =0
virtual std::string getRemoteAddressAsString () const =0
virtual void sendToPeer (const char *junk, std::size_t junkLen)=0
virtual void sendToPeer (const std::string &data)=0
virtual ssize_t readFromPeer (char *junk, std::size_t junkLen)=0
core::socket::SocketContext * switchSocketContext (core::socket::SocketContextFactory *socketContextFactory)
Protected Member Functions
SocketConnection (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory)
virtual ~SocketConnection ()
void onConnected ()
void onDisconnected ()
void onReceiveFromPeer ()
void onWriteError (int errnum)
void onReadError (int errnum)
Private Member Functions
SocketConnection ()=delete
SocketConnection (const core::socket::SocketConnection &)=delete
SocketConnection & operator= (const core::socket::SocketConnection &)=delete
Private Attributes
core::socket::SocketContext * socketContext = nullptr
core::socket::SocketContext * newSocketContext = nullptr
Detailed Description
Definition at line 44 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection() [1/3]
core::socket::SocketConnection::SocketConnection () private delete
SocketConnection() [2/3]
core::socket::SocketConnection::SocketConnection (const core::socket::SocketConnection &) private delete
SocketConnection() [3/3]
core::socket::SocketConnection::SocketConnection (const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory) protected
Definition at line 32 of file SocketConnection.cpp.
         : socketContext(socketContextFactory->create(this)) {
     }
~SocketConnection()
core::socket::SocketConnection::~SocketConnection () protected virtual
Reimplemented in core::socket::stream::tls::SocketConnection< SocketT >, core::socket::stream::legacy::SocketConnection< SocketT >, core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Definition at line 36 of file SocketConnection.cpp.
{
         delete socketContext;
     }
References socketContext.
Member Function Documentation
close()
virtual void core::socket::SocketConnection::close () pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::close().
getLocalAddressAsString()
virtual std::string core::socket::SocketConnection::getLocalAddressAsString () const pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::getLocalAddressAsString().
getRemoteAddressAsString()
virtual std::string core::socket::SocketConnection::getRemoteAddressAsString () const pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::getRemoteAddressAsString().
getSocketContext()
core::socket::SocketContext * core::socket::SocketConnection::getSocketContext ()
Definition at line 68 of file SocketConnection.cpp.
{
         return socketContext;
     }
References socketContext.
onConnected()
void core::socket::SocketConnection::onConnected () protected
Definition at line 40 of file SocketConnection.cpp.
{
         socketContext->onConnected();
     }
References core::socket::SocketContext::onConnected(), and socketContext.
onDisconnected()
void core::socket::SocketConnection::onDisconnected () protected
Definition at line 44 of file SocketConnection.cpp.
{
         socketContext->onDisconnected();
     }
References core::socket::SocketContext::onDisconnected(), and socketContext.
Referenced by onReceiveFromPeer().
onReadError()
void core::socket::SocketConnection::onReadError (int errnum) protected
Definition at line 64 of file SocketConnection.cpp.
{
         socketContext->onReadError(errnum);
     }
References core::socket::SocketContext::onReadError(), and socketContext.
onReceiveFromPeer()
void core::socket::SocketConnection::onReceiveFromPeer () protected
Definition at line 48 of file SocketConnection.cpp.
{
         socketContext->onReceiveFromPeer();
         if (newSocketContext != nullptr) { // Perform a pending SocketContextSwitch
             onDisconnected();
             delete socketContext;
             socketContext = newSocketContext;
             newSocketContext = nullptr;
             onConnected();
         }
     }
References newSocketContext, onDisconnected(), core::socket::SocketContext::onReceiveFromPeer(), and socketContext.
onWriteError()
void core::socket::SocketConnection::onWriteError (int errnum) protected
Definition at line 60 of file SocketConnection.cpp.
{
         socketContext->onWriteError(errnum);
     }
References core::socket::SocketContext::onWriteError(), and socketContext.
operator=()
SocketConnection& core::socket::SocketConnection::operator= (const core::socket::SocketConnection &) private delete
readFromPeer()
virtual ssize_t core::socket::SocketConnection::readFromPeer (char * junk, std::size_t junkLen) pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::readFromPeer().
sendToPeer() [1/2]
virtual void core::socket::SocketConnection::sendToPeer (const char * junk, std::size_t junkLen) pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::sendToPeer().
sendToPeer() [2/2]
virtual void core::socket::SocketConnection::sendToPeer (const std::string & data) pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
setTimeout()
virtual void core::socket::SocketConnection::setTimeout (const utils::Timeval & timeout) pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::setTimeout().
shutdownRead()
virtual void core::socket::SocketConnection::shutdownRead () pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::shutdownRead().
shutdownWrite()
virtual void core::socket::SocketConnection::shutdownWrite () pure virtual
Implemented in core::socket::stream::SocketConnection< SocketReaderT, SocketWriterT, SocketAddressT >, core::socket::stream::SocketConnection< core::socket::stream::tls::SocketReader< SocketT >, core::socket::stream::tls::SocketWriter< SocketT >, SocketT::SocketAddress >, and core::socket::stream::SocketConnection< core::socket::stream::legacy::SocketReader< SocketT >, core::socket::stream::legacy::SocketWriter< SocketT >, SocketT::SocketAddress >.
Referenced by core::socket::SocketContext::shutdownWrite().
switchSocketContext()
core::socket::SocketContext * core::socket::SocketConnection::switchSocketContext (core::socket::SocketContextFactory * socketContextFactory)
Definition at line 72 of file SocketConnection.cpp.
{
         newSocketContext = socketContextFactory->create(this);
         if (newSocketContext == nullptr) {
             VLOG(0) << "Switch socket context unsuccessull: new socket context not created";
         }
         return newSocketContext;
     }
References core::socket::SocketContextFactory::create(), and newSocketContext.
Referenced by core::socket::SocketContext::switchSocketContext().
Member Data Documentation
newSocketContext
core::socket::SocketContext* core::socket::SocketConnection::newSocketContext = nullptr private
Definition at line 86 of file SocketConnection.h.
Referenced by onReceiveFromPeer(), and switchSocketContext().
socketContext
core::socket::SocketContext* core::socket::SocketConnection::socketContext = nullptr private
Definition at line 85 of file SocketConnection.h.
Referenced by getSocketContext(), onConnected(), onDisconnected(), onReadError(), onReceiveFromPeer(), onWriteError(), and ~SocketConnection().
The documentation for this class was generated from the following files:
core/socket/SocketConnection.h
core/socket/SocketConnection.cpp