snode.c: web::http::legacy::in::Server< Request, Response > Class Template Reference
web::http::legacy::in::Server< Request, Response > Class Template Reference
#include <Server.h>
Public Member Functions
void listen (uint16_t port, const std::function< void(const net::in::stream::Socket &, int)> &onError)
void listen (const std::string &ipOrHostname, const std::function< void(const net::in::stream::Socket &, int)> &onError)
void listen (const std::string &ipOrHostname, uint16_t port, const std::function< void(const net::in::stream::Socket &, int)> &onError)
Public Member Functions inherited from web::http::server::Server< net::in::stream::legacy::SocketServer, Request, Response >
Server (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &, Response &)> &onRequestReady, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void listen (const SocketAddress &socketAddress, const std::function< void(int)> &onError)
Public Member Functions inherited from core::socket::stream::SocketServer< ServerConfigT, ServerSocketT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketServer ()=default
void listen (const std::function< void(const Socket &socket, int)> &onError) const override
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(const Socket &socket, int)> &onError) const override
void onConnect (const std::function< void(SocketConnection *)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
ServerConfig & getServerConfig ()
Protected Types
using SocketServer = net::in::stream::legacy::SocketServer< web::http::server::SocketContextFactory< Request, Response > >
Protected Types inherited from core::socket::stream::SocketServer< ServerConfigT, ServerSocketT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
using ServerConfig = ServerConfigT
using ServerSocket = ServerSocketT
using SocketAcceptor = core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >
using SocketContextFactory = SocketContextFactoryT
Additional Inherited Members
Public Types inherited from web::http::server::Server< net::in::stream::legacy::SocketServer, Request, Response >
using Request = Request
using Response = Response
using SocketConnection = typename Super::SocketConnection
using SocketAddress = typename SocketConnection::SocketAddress
Public Types inherited from core::socket::stream::SocketServer< ServerConfigT, ServerSocketT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
using Socket = typename ServerSocket::Socket
using SocketAddress = typename Socket::SocketAddress
using SocketConnection = typename SocketAcceptor::SocketConnection
Protected Attributes inherited from core::socket::stream::SocketServer< ServerConfigT, ServerSocketT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >
ServerConfig serverConfig
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename Request, typename Response>
class web::http::legacy::in::Server< Request, Response >
Definition at line 32 of file Server.h.
Member Typedef Documentation
SocketServer
template<typename Request , typename Response > using web::http::legacy::in::Server< Request, Response >::SocketServer = net::in::stream::legacy::SocketServer<web::http::server::SocketContextFactory<Request, Response> > protected
Definition at line 36 of file Server.h.
Member Function Documentation
listen() [1/3]
template<typename Request , typename Response > void web::http::legacy::in::Server< Request, Response >::listen (const std::string & ipOrHostname, const std::function< void(const net::in::stream::Socket &, int)> & onError) inline
Definition at line 45 of file Server.h.
{
             SocketServer::listen(ipOrHostname, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerConfigT, ServerSocketT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
listen() [2/3]
template<typename Request , typename Response > void web::http::legacy::in::Server< Request, Response >::listen (const std::string & ipOrHostname, uint16_t port, const std::function< void(const net::in::stream::Socket &, int)> & onError) inline
Definition at line 50 of file Server.h.
{
             SocketServer::listen(ipOrHostname, port, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerConfigT, ServerSocketT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
listen() [3/3]
template<typename Request , typename Response > void web::http::legacy::in::Server< Request, Response >::listen (uint16_t port, const std::function< void(const net::in::stream::Socket &, int)> & onError) inline
Definition at line 41 of file Server.h.
{
             SocketServer::listen(port, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerConfigT, ServerSocketT, core::socket::stream::legacy::SocketAcceptor< ServerConfigT, ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
The documentation for this class was generated from the following file:
web/http/legacy/in/Server.h