snode.c: express::WebApp Class Reference
express::WebApp Class Reference
#include <WebApp.h>
Static Public Member Functions
static void init (int argc, char *argv[])
static int start (const utils::Timeval &timeOut={LONG_MAX, 0})
static void stop ()
static core::TickStatus tick (const utils::Timeval &timeOut=0)
static void free ()
Protected Member Functions
WebApp (const Router &router)
Additional Inherited Members
Public Member Functions inherited from express::Router
Router ()
Router (const Router &router)
Router (Router &&router)
Router & operator= (const Router &router)
Router & operator= (Router &&router)
Router & use (const Router &router)
Router & use (const std::string &relativeMountPath, const Router &router)
Router & use (const std::function< void(Request &req, Response &res)> &lambda)
Router & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & use (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & use (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & all (const Router &router)
Router & all (const std::string &relativeMountPath, const Router &router)
Router & all (const std::function< void(Request &req, Response &res)> &lambda)
Router & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & all (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & all (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & get (const Router &router)
Router & get (const std::string &relativeMountPath, const Router &router)
Router & get (const std::function< void(Request &req, Response &res)> &lambda)
Router & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & get (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & get (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & put (const Router &router)
Router & put (const std::string &relativeMountPath, const Router &router)
Router & put (const std::function< void(Request &req, Response &res)> &lambda)
Router & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & put (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & put (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & post (const Router &router)
Router & post (const std::string &relativeMountPath, const Router &router)
Router & post (const std::function< void(Request &req, Response &res)> &lambda)
Router & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & post (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & post (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & del (const Router &router)
Router & del (const std::string &relativeMountPath, const Router &router)
Router & del (const std::function< void(Request &req, Response &res)> &lambda)
Router & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & del (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & del (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & connect (const Router &router)
Router & connect (const std::string &relativeMountPath, const Router &router)
Router & connect (const std::function< void(Request &req, Response &res)> &lambda)
Router & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & connect (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & connect (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & options (const Router &router)
Router & options (const std::string &relativeMountPath, const Router &router)
Router & options (const std::function< void(Request &req, Response &res)> &lambda)
Router & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & options (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & options (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & trace (const Router &router)
Router & trace (const std::string &relativeMountPath, const Router &router)
Router & trace (const std::function< void(Request &req, Response &res)> &lambda)
Router & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & trace (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & trace (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & patch (const Router &router)
Router & patch (const std::string &relativeMountPath, const Router &router)
Router & patch (const std::function< void(Request &req, Response &res)> &lambda)
Router & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & patch (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & patch (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & head (const Router &router)
Router & head (const std::string &relativeMountPath, const Router &router)
Router & head (const std::function< void(Request &req, Response &res)> &lambda)
Router & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res)> &lambda)
Router & head (const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Router & head (const std::string &relativeMountPath, const std::function< void(Request &req, Response &res, express::dispatcher::State &state)> &lambda)
Protected Attributes inherited from express::Router
std::shared_ptr< express::dispatcher::RouterDispatcher > routerDispatcher
Detailed Description
Definition at line 35 of file WebApp.h.
Constructor & Destructor Documentation
WebApp()
express::WebApp::WebApp (const Router & router) explicit protected
Definition at line 29 of file WebApp.cpp.
         : Router(router) {
     }
Member Function Documentation
free()
void express::WebApp::free () static
Definition at line 49 of file WebApp.cpp.
                       {
         core::SNodeC::free();
     }
References core::SNodeC::free().
init()
void express::WebApp::init (int argc, char * argv[]) static
Definition at line 33 of file WebApp.cpp.
{
         core::SNodeC::init(argc, argv);
     }
References core::SNodeC::init().
start()
int express::WebApp::start (const utils::Timeval & timeOut = {LONG_MAX, 0}) static
Definition at line 37 of file WebApp.cpp.
{
         return core::SNodeC::start(timeOut);
     }
References core::SNodeC::start().
stop()
void express::WebApp::stop () static
Definition at line 41 of file WebApp.cpp.
                       {
         core::SNodeC::stop();
     }
References core::SNodeC::stop().
tick()
core::TickStatus express::WebApp::tick (const utils::Timeval & timeOut = 0) static
Definition at line 45 of file WebApp.cpp.
{
         return core::SNodeC::tick(timeOut);
     }
References core::SNodeC::tick().
The documentation for this class was generated from the following files:
express/WebApp.h
express/WebApp.cpp