snode.c: net::socket::stream::tls::SocketAcceptor< SocketT > Class Template Reference
net::socket::stream::tls::SocketAcceptor< SocketT > Class Template Reference
#include <SocketAcceptor.h>
Public Types
using SocketConnection = net::socket::stream::tls::SocketConnection< SocketT >
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Types inherited from net::socket::stream::SocketAcceptor< net::socket::stream::tls::SocketConnection< SocketT > >
using SocketConnection = net::socket::stream::tls::SocketConnection< SocketT >
using Socket = typename SocketConnection::Socket
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
SocketAcceptor (const std::shared_ptr< SocketContextFactory > &socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
~SocketAcceptor () override
void listen (const SocketAddress &localAddress, int backlog, const std::function< void(int)> &onError)
Public Member Functions inherited from net::socket::stream::SocketAcceptor< net::socket::stream::tls::SocketConnection< SocketT > >
SocketAcceptor (const std::shared_ptr< SocketContextFactory > &socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options)
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(int)> &onError)
Public Member Functions inherited from net::EventReceiver
void enable (int fd)
void disable ()
void suspend ()
void resume ()
Public Member Functions inherited from net::ObservationCounter
bool isObserved ()
Static Protected Member Functions
static int serverNameCallback (SSL *ssl, [[maybe_unused]] int *al, void *arg)
Protected Attributes
SSL_CTX * ctx = nullptr
Protected Attributes inherited from net::socket::stream::SocketAcceptor< net::socket::stream::tls::SocketConnection< SocketT > >
std::map< std::string, std::any > options
std::function< void(const SocketAddress &, const SocketAddress &)> onConnect
std::function< void(SocketConnection *)> onDestruct
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Protected Attributes inherited from net::ObservationCounter
int observationCounter = 0
struct timeval lastTriggered = {0, 0}
Additional Inherited Members
Protected Member Functions inherited from net::socket::stream::SocketAcceptor< net::socket::stream::tls::SocketConnection< SocketT > >
void destruct ()
Protected Member Functions inherited from net::AcceptEventReceiver
AcceptEventReceiver (long timeout=LONG_MAX)
virtual bool continueAcceptImmediately ()
Protected Member Functions inherited from net::EventReceiver
EventReceiver (EventDispatcher &descriptorEventDispatcher, long timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
void setTimeout (long timeout)
bool isEnabled () const
bool isSuspended () const
Detailed Description
template<typename SocketT>
class net::socket::stream::tls::SocketAcceptor< SocketT >
Definition at line 36 of file SocketAcceptor.h.
Member Typedef Documentation
Socket
template<typename SocketT > using net::socket::stream::tls::SocketAcceptor< SocketT >::Socket = typename SocketConnection::Socket
Definition at line 39 of file SocketAcceptor.h.
SocketAddress
template<typename SocketT > using net::socket::stream::tls::SocketAcceptor< SocketT >::SocketAddress = typename Socket::SocketAddress
Definition at line 40 of file SocketAcceptor.h.
SocketConnection
template<typename SocketT > using net::socket::stream::tls::SocketAcceptor< SocketT >::SocketConnection = net::socket::stream::tls::SocketConnection<SocketT>
Definition at line 38 of file SocketAcceptor.h.
Constructor & Destructor Documentation
SocketAcceptor()
template<typename SocketT > net::socket::stream::tls::SocketAcceptor< SocketT >::SocketAcceptor (const std::shared_ptr< SocketContextFactory > & socketContextFactory, const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options) inline
Definition at line 42 of file SocketAcceptor.h.
             : net::socket::stream::SocketAcceptor<SocketConnection>(
                   socketContextFactory,
                   onConnect,
                   [onConnected, this](SocketConnection* socketConnection) -> void {
                       SSL* ssl = socketConnection->startSSL(this->ctx);
                       if (ssl != nullptr) {
                           SSL_CTX_set_tlsext_servername_arg(this->ctx, socketConnection);
                           SSL_set_accept_state(ssl);
                           socketConnection->doSSLHandshake(
                               [&onConnected, socketConnection](void) -> void { // onSuccess
                                   LOG(INFO) << "SSL/TLS initial handshake success";
                                   socketConnection->SocketConnection::SocketReader::resume();
                                   onConnected(socketConnection);
                               },
                               [](void) -> void { // onTimeout
                                   LOG(WARNING) << "SSL/TLS initial handshake timed out";
                               },
                               [](int sslErr) -> void { // onError
                                   ssl_log("SSL/TLS initial handshake failed", sslErr);
                               });
                       } else {
                           socketConnection->SocketConnection::SocketReader::disable();
                           socketConnection->SocketConnection::SocketWriter::disable();
                           ssl_log_error("SSL/TLS initialization failed");
                       }
                   },
                   [onDisconnect](SocketConnection* socketConnection) -> void { // onDisconnect
                       socketConnection->stopSSL();
                       onDisconnect(socketConnection);
                   },
                   options) {
             ctx = ssl_ctx_new(options, true);
             if (ctx != nullptr) {
                 SSL_CTX_set_tlsext_servername_callback(ctx, serverNameCallback);
             }
         }
References net::socket::stream::tls::SocketAcceptor< SocketT >::ctx, net::socket::stream::SocketAcceptor< net::socket::stream::tls::SocketConnection< SocketT > >::onConnected, and net::socket::stream::tls::ssl_log().
~SocketAcceptor()
template<typename SocketT > net::socket::stream::tls::SocketAcceptor< SocketT >::~SocketAcceptor () inline override virtual
Reimplemented from net::socket::stream::SocketAcceptor< net::socket::stream::tls::SocketConnection< SocketT > >.
Definition at line 87 of file SocketAcceptor.h.
{
             ssl_ctx_free(ctx);
         }
References net::socket::stream::tls::ssl_ctx_free().
Member Function Documentation
listen()
template<typename SocketT > void net::socket::stream::tls::SocketAcceptor< SocketT >::listen (const SocketAddress & localAddress, int backlog, const std::function< void(int)> & onError) inline
Definition at line 91 of file SocketAcceptor.h.
{
             if (ctx == nullptr) {
                 errno = EINVAL;
                 onError(errno);
                 net::socket::stream::SocketAcceptor<SocketConnection>::destruct();
             } else {
                 net::socket::stream::SocketAcceptor<SocketConnection>::listen(localAddress, backlog, onError);
             }
         }
References net::socket::stream::SocketAcceptor< SocketConnectionT >::destruct(), and net::socket::stream::SocketAcceptor< SocketConnectionT >::listen().
serverNameCallback()
template<typename SocketT > static int net::socket::stream::tls::SocketAcceptor< SocketT >::serverNameCallback (SSL * ssl, [[maybe_unused] ] int * al, void * arg) inline static protected
Definition at line 102 of file SocketAcceptor.h.
{
             SocketConnection* socketConnection = static_cast<SocketConnection*>(arg);
             if (SSL_get_servername_type(ssl) != -1) {
                 socketConnection->serverNameIndication = SSL_get_servername(ssl, TLSEXT_NAMETYPE_host_name);
                 LOG(INFO) << "ServerNameIndication: " << socketConnection->serverNameIndication;
             }
             return SSL_TLSEXT_ERR_OK;
         }
References net::socket::stream::tls::SocketConnection< SocketT >::serverNameIndication.
Member Data Documentation
ctx
template<typename SocketT > SSL_CTX* net::socket::stream::tls::SocketAcceptor< SocketT >::ctx = nullptr protected
Definition at line 113 of file SocketAcceptor.h.
Referenced by net::socket::stream::tls::SocketAcceptor< SocketT >::SocketAcceptor().
The documentation for this class was generated from the following file:
net/socket/stream/tls/SocketAcceptor.h