snode.c: core::poll::EventMultiplexer Class Reference
core::poll::EventMultiplexer Class Reference
#include <EventMultiplexer.h>
Public Member Functions
EventMultiplexer ()
~EventMultiplexer () override=default
Public Member Functions inherited from core::EventMultiplexer
DescriptorEventPublisher & getDescriptorEventPublisher (core::EventMultiplexer::DISP_TYPE dispType)
TimerEventPublisher & getTimerEventPublisher ()
void publish (core::Event *event)
void unPublish (core::Event *event)
TickStatus tick (const utils::Timeval &tickTimeOut)
void stop ()
Private Member Functions
EventMultiplexer (const EventMultiplexer &)=delete
EventMultiplexer & operator= (const EventMultiplexer &)=delete
int multiplex (utils::Timeval &tickTimeOut) override
void publishActiveEvents (int count) override
Private Attributes
PollFdsManager pollFdsManager
Additional Inherited Members
Public Types inherited from core::EventMultiplexer
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Protected Member Functions inherited from core::EventMultiplexer
EventMultiplexer (DescriptorEventPublisher *const readDescriptorEventPublisher, DescriptorEventPublisher *const writeDescriptorEventPublisher, DescriptorEventPublisher *const exceptionDescriptorEventPublisher)
int getObservedEventReceiverCount ()
int getMaxFd ()
Protected Attributes inherited from core::EventMultiplexer
std::array< DescriptorEventPublisher *, 3 > descriptorEventPublishers
core::TimerEventPublisher *const timerEventPublisher
Detailed Description
Definition at line 74 of file EventMultiplexer.h.
Constructor & Destructor Documentation
EventMultiplexer() [1/2]
core::poll::EventMultiplexer::EventMultiplexer (const EventMultiplexer &) private delete
EventMultiplexer() [2/2]
core::poll::EventMultiplexer::EventMultiplexer ()
Definition at line 131 of file EventMultiplexer.cpp.
         : core::EventMultiplexer(
               new core::poll::DescriptorEventPublisher("READ", pollFdsManager, POLLIN, POLLIN | POLLHUP | POLLRDHUP | POLLERR),
               new core::poll::DescriptorEventPublisher("WRITE", pollFdsManager, POLLOUT, POLLOUT),
               new core::poll::DescriptorEventPublisher("EXCEPT", pollFdsManager, POLLPRI, POLLPRI)) {
     }
~EventMultiplexer()
core::poll::EventMultiplexer::~EventMultiplexer () override virtual default
Reimplemented from core::EventMultiplexer.
Member Function Documentation
multiplex()
int core::poll::EventMultiplexer::multiplex (utils::Timeval & tickTimeOut) override private virtual
Implements core::EventMultiplexer.
Definition at line 138 of file EventMultiplexer.cpp.
{
         return core::system::poll(pollFdsManager.getEvents(), pollFdsManager.getCurrentSize(), tickTimeOut.ms());
     }
References core::poll::PollFdsManager::getCurrentSize(), core::poll::PollFdsManager::getEvents(), utils::Timeval::ms(), core::system::poll(), and pollFdsManager.
operator=()
EventMultiplexer& core::poll::EventMultiplexer::operator= (const EventMultiplexer &) private delete
publishActiveEvents()
void core::poll::EventMultiplexer::publishActiveEvents (int count) override private virtual
Implements core::EventMultiplexer.
Definition at line 142 of file EventMultiplexer.cpp.
{
         if (count > 0) {
             for (core::DescriptorEventPublisher* const descriptorEventPublisher : descriptorEventPublishers) {
                 descriptorEventPublisher->publishActiveEvents();
             }
         }
     }
References core::EventMultiplexer::descriptorEventPublishers.
Member Data Documentation
pollFdsManager
PollFdsManager core::poll::EventMultiplexer::pollFdsManager private
Definition at line 87 of file EventMultiplexer.h.
Referenced by multiplex().
The documentation for this class was generated from the following files:
core/multiplexer/poll/EventMultiplexer.h
core/multiplexer/poll/EventMultiplexer.cpp