snode.c: core::EventDispatcher::FdSet Class Reference
core::EventDispatcher::FdSet Class Reference
Public Member Functions
FdSet ()
void set (int fd)
void clr (int fd)
int isSet (int fd) const
void zero ()
fd_set & get ()
Protected Attributes
fd_set registered
fd_set active
Detailed Description
Definition at line 41 of file EventDispatcher.h.
Constructor & Destructor Documentation
FdSet()
core::EventDispatcher::FdSet::FdSet ()
Definition at line 37 of file EventDispatcher.cpp.
{
         zero();
     }
References zero().
Member Function Documentation
clr()
void core::EventDispatcher::FdSet::clr (int fd)
Definition at line 45 of file EventDispatcher.cpp.
{
         FD_CLR(fd, &registered);
         FD_CLR(fd, &active);
     }
Referenced by core::EventDispatcher::suspend(), and core::EventDispatcher::unobserveDisabledEvents().
get()
fd_set & core::EventDispatcher::FdSet::get ()
Definition at line 59 of file EventDispatcher.cpp.
{
         active = registered;
         return active;
     }
Referenced by core::EventDispatcher::dispatchActiveEvents().
isSet()
int core::EventDispatcher::FdSet::isSet (int fd) const
Definition at line 50 of file EventDispatcher.cpp.
{
         return FD_ISSET(fd, &active);
     }
set()
void core::EventDispatcher::FdSet::set (int fd)
Definition at line 41 of file EventDispatcher.cpp.
{
         FD_SET(fd, &registered);
     }
Referenced by core::EventDispatcher::resume(), and core::EventDispatcher::unobserveDisabledEvents().
zero()
void core::EventDispatcher::FdSet::zero ()
Definition at line 54 of file EventDispatcher.cpp.
{
         FD_ZERO(&registered);
         FD_ZERO(&active);
     }
Referenced by FdSet().
Member Data Documentation
active
fd_set core::EventDispatcher::FdSet::active protected
Definition at line 53 of file EventDispatcher.h.
registered
fd_set core::EventDispatcher::FdSet::registered protected
Definition at line 52 of file EventDispatcher.h.
The documentation for this class was generated from the following files:
core/EventDispatcher.h
core/EventDispatcher.cpp