snode.c: net::l2::SocketAddress Class Reference
net::l2::SocketAddress Class Reference
#include <SocketAddress.h>
Public Member Functions
SocketAddress ()
SocketAddress (const std::string &btAddress)
SocketAddress (const std::string &btAddress, uint16_t psm)
SocketAddress (uint16_t psm)
void setAddress (const std::string &btAddress)
void setPsm (uint16_t psm)
uint16_t psm () const
std::string address () const override
std::string toString () const override
Public Member Functions inherited from core::socket::SocketAddress< struct sockaddr_l2 >
SocketAddress ()
SocketAddress (const SocketAddress &socketAddress)
SocketAddress (const SockAddr &sockAddr)
virtual ~SocketAddress ()=default
SocketAddress & operator= (const SocketAddress &socketAddress)
SocketAddress & operator= (const SockAddr &sockAddr)
const sockaddr & getSockAddr () const
socklen_t getSockAddrLen () const
Additional Inherited Members
Public Types inherited from core::socket::SocketAddress< struct sockaddr_l2 >
using SockAddr = struct sockaddr_l2
Protected Attributes inherited from core::socket::SocketAddress< struct sockaddr_l2 >
SockAddr sockAddr
Detailed Description
Definition at line 37 of file SocketAddress.h.
Constructor & Destructor Documentation
SocketAddress() [1/4]
net::l2::SocketAddress::SocketAddress ()
Definition at line 48 of file SocketAddress.cpp.
{
         std::memset(&sockAddr, 0, sizeof(sockAddr));
         sockAddr.l2_family = AF_BLUETOOTH;
         sockAddr.l2_bdaddr = {{0, 0, 0, 0, 0, 0}};
         sockAddr.l2_psm = htobs(0);
     }
References core::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
SocketAddress() [2/4]
net::l2::SocketAddress::SocketAddress (const std::string & btAddress) explicit
Definition at line 56 of file SocketAddress.cpp.
         : SocketAddress() {
         setAddress(btAddress);
     }
References setAddress().
SocketAddress() [3/4]
net::l2::SocketAddress::SocketAddress (const std::string & btAddress, uint16_t psm)
Definition at line 66 of file SocketAddress.cpp.
         : SocketAddress() {
         setAddress(btAddress);
         setPsm(psm);
     }
References psm(), setAddress(), and setPsm().
SocketAddress() [4/4]
net::l2::SocketAddress::SocketAddress (uint16_t psm) explicit
Definition at line 61 of file SocketAddress.cpp.
         : SocketAddress() {
         setPsm(psm);
     }
References psm(), and setPsm().
Member Function Documentation
address()
std::string net::l2::SocketAddress::address () const override virtual
Implements core::socket::SocketAddress< struct sockaddr_l2 >.
Definition at line 84 of file SocketAddress.cpp.
{
         char address[256];
         ba2str(&sockAddr.l2_bdaddr, address);
         return address;
     }
References core::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
Referenced by toString().
psm()
uint16_t net::l2::SocketAddress::psm () const
Definition at line 80 of file SocketAddress.cpp.
{
         return btohs(sockAddr.l2_psm);
     }
References core::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
Referenced by setPsm(), SocketAddress(), and toString().
setAddress()
void net::l2::SocketAddress::setAddress (const std::string & btAddress)
Definition at line 72 of file SocketAddress.cpp.
{
         str2ba(btAddress.c_str(), &sockAddr.l2_bdaddr);
     }
References core::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
Referenced by SocketAddress().
setPsm()
void net::l2::SocketAddress::setPsm (uint16_t psm)
Definition at line 76 of file SocketAddress.cpp.
{
         sockAddr.l2_psm = htobs(psm);
     }
References psm(), and core::socket::SocketAddress< struct sockaddr_l2 >::sockAddr.
Referenced by SocketAddress().
toString()
std::string net::l2::SocketAddress::toString () const override virtual
Implements core::socket::SocketAddress< struct sockaddr_l2 >.
Definition at line 91 of file SocketAddress.cpp.
{
         return address() + ":" + std::to_string(psm());
     }
References address(), psm(), and CLI::detail::to_string().
The documentation for this class was generated from the following files:
net/l2/SocketAddress.h
net/l2/SocketAddress.cpp