snode.c: CLI::OptionBase< CRTP > Class Template Reference
CLI::OptionBase< CRTP > Class Template Reference
#include <CLI11.hpp>
Public Member Functions
CRTP * group (const std::string &name)
Changes the group membership.
CRTP * required (bool value=true)
Set the option as required.
CRTP * mandatory (bool value=true)
Support Plumbum term.
CRTP * always_capture_default (bool value=true)
const std::string & get_group () const
Get the group of this option.
bool get_required () const
True if this is a required option.
bool get_ignore_case () const
The status of ignore case.
bool get_ignore_underscore () const
The status of ignore_underscore.
bool get_configurable () const
The status of configurable.
bool get_disable_flag_override () const
The status of configurable.
char get_delimiter () const
Get the current delimiter char.
bool get_always_capture_default () const
Return true if this will automatically capture the default value for help printing.
MultiOptionPolicy get_multi_option_policy () const
The status of the multi option policy.
CRTP * take_last ()
Set the multi option policy to take last.
CRTP * take_first ()
Set the multi option policy to take last.
CRTP * take_all ()
Set the multi option policy to take all arguments.
CRTP * join ()
Set the multi option policy to join.
CRTP * join (char delim)
Set the multi option policy to join with a specific delimiter.
CRTP * configurable (bool value=true)
Allow in a configuration file.
CRTP * delimiter (char value='\0')
Allow in a configuration file.
Protected Member Functions
template<typename T >
void copy_to (T *other) const
Copy the contents to another similar class (one based on OptionBase)
Protected Attributes
std::string group_ = std::string("Options")
The group membership.
bool required_ {false}
True if this is a required option.
bool ignore_case_ {false}
Ignore the case when matching (option, not value)
bool ignore_underscore_ {false}
Ignore underscores when matching (option, not value)
bool configurable_ {true}
Allow this option to be given in a configuration file.
bool disable_flag_override_ {false}
Disable overriding flag values with '=value'.
char delimiter_ {'\0'}
Specify a delimiter character for vector arguments.
bool always_capture_default_ {false}
Automatically capture default value.
MultiOptionPolicy multi_option_policy_ {MultiOptionPolicy::Throw}
Policy for handling multiple arguments beyond the expected Max.
Private Attributes
friend App
Detailed Description
template<typename CRTP>
class CLI::OptionBase< CRTP >
This is the CRTP base class for Option and OptionDefaults. It was designed this way to share parts of the class; an OptionDefaults can copy to an Option.
Definition at line 4165 of file CLI11.hpp.
Member Function Documentation
always_capture_default()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::always_capture_default (bool value = true) inline
Definition at line 4233 of file CLI11.hpp.
{
             always_capture_default_ = value;
             return static_cast<CRTP*>(this);
         }
Referenced by CLI::detail::default_flag_modifiers().
configurable()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::configurable (bool value = true) inline
Allow in a configuration file.
Definition at line 4324 of file CLI11.hpp.
{
             configurable_ = value;
             return static_cast<CRTP*>(this);
         }
Referenced by net::config::ConfigCluster::ConfigCluster(), and utils::Config::init().
copy_to()
template<typename CRTP > template<typename T > void CLI::OptionBase< CRTP >::copy_to (T * other) const inline protected
Copy the contents to another similar class (one based on OptionBase)
Definition at line 4198 of file CLI11.hpp.
{
             other->group(group_);
             other->required(required_);
             other->ignore_case(ignore_case_);
             other->ignore_underscore(ignore_underscore_);
             other->configurable(configurable_);
             other->disable_flag_override(disable_flag_override_);
             other->delimiter(delimiter_);
             other->always_capture_default(always_capture_default_);
             other->multi_option_policy(multi_option_policy_);
         }
delimiter()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::delimiter (char value = '\0') inline
Allow in a configuration file.
Definition at line 4330 of file CLI11.hpp.
{
             delimiter_ = value;
             return static_cast<CRTP*>(this);
         }
get_always_capture_default()
template<typename CRTP > bool CLI::OptionBase< CRTP >::get_always_capture_default () const inline
Return true if this will automatically capture the default value for help printing.
Definition at line 4276 of file CLI11.hpp.
{
             return always_capture_default_;
         }
get_configurable()
template<typename CRTP > bool CLI::OptionBase< CRTP >::get_configurable () const inline
The status of configurable.
Definition at line 4261 of file CLI11.hpp.
{
             return configurable_;
         }
Referenced by CLI::App::_parse_single_config(), and CLI::ConfigBase::to_config().
get_delimiter()
template<typename CRTP > char CLI::OptionBase< CRTP >::get_delimiter () const inline
Get the current delimiter char.
Definition at line 4271 of file CLI11.hpp.
{
             return delimiter_;
         }
get_disable_flag_override()
template<typename CRTP > bool CLI::OptionBase< CRTP >::get_disable_flag_override () const inline
The status of configurable.
Definition at line 4266 of file CLI11.hpp.
{
             return disable_flag_override_;
         }
get_group()
template<typename CRTP > const std::string& CLI::OptionBase< CRTP >::get_group () const inline
Get the group of this option.
Definition at line 4241 of file CLI11.hpp.
{
             return group_;
         }
Referenced by CLI::App::get_groups(), CLI::Formatter::make_groups(), CLI::Formatter::make_positionals(), and CLI::ConfigBase::to_config().
get_ignore_case()
template<typename CRTP > bool CLI::OptionBase< CRTP >::get_ignore_case () const inline
The status of ignore case.
Definition at line 4251 of file CLI11.hpp.
{
             return ignore_case_;
         }
get_ignore_underscore()
template<typename CRTP > bool CLI::OptionBase< CRTP >::get_ignore_underscore () const inline
The status of ignore_underscore.
Definition at line 4256 of file CLI11.hpp.
{
             return ignore_underscore_;
         }
get_multi_option_policy()
template<typename CRTP > MultiOptionPolicy CLI::OptionBase< CRTP >::get_multi_option_policy () const inline
The status of the multi option policy.
Definition at line 4281 of file CLI11.hpp.
{
             return multi_option_policy_;
         }
get_required()
template<typename CRTP > bool CLI::OptionBase< CRTP >::get_required () const inline
True if this is a required option.
Definition at line 4246 of file CLI11.hpp.
{
             return required_;
         }
Referenced by CLI::App::_count_remaining_positionals(), CLI::App::_process_requirements(), CLI::Formatter::make_option_opts(), and CLI::Formatter::make_option_usage().
group()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::group (const std::string & name) inline
Changes the group membership.
Definition at line 4214 of file CLI11.hpp.
{
             if (!detail::valid_alias_name_string(name)) {
                 throw IncorrectConstruction("Group names may not contain newlines or null characters");
             }
             group_ = name;
             return static_cast<CRTP*>(this);
         }
References CLI::detail::valid_alias_name_string().
join() [1/2]
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::join () inline
Set the multi option policy to join.
Definition at line 4309 of file CLI11.hpp.
                      {
             auto self = static_cast<CRTP*>(this);
             self->multi_option_policy(MultiOptionPolicy::Join);
             return self;
         }
References CLI::Join.
join() [2/2]
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::join (char delim) inline
Set the multi option policy to join with a specific delimiter.
Definition at line 4316 of file CLI11.hpp.
{
             auto self = static_cast<CRTP*>(this);
             self->delimiter_ = delim;
             self->multi_option_policy(MultiOptionPolicy::Join);
             return self;
         }
References CLI::Join.
mandatory()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::mandatory (bool value = true) inline
Support Plumbum term.
Definition at line 4229 of file CLI11.hpp.
{
             return required(value);
         }
required()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::required (bool value = true) inline
Set the option as required.
Definition at line 4223 of file CLI11.hpp.
{
             required_ = value;
             return static_cast<CRTP*>(this);
         }
Referenced by CLI::App::_add_flag_internal(), and net::config::ConfigAddress< SocketAddressT >::require().
take_all()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::take_all () inline
Set the multi option policy to take all arguments.
Definition at line 4302 of file CLI11.hpp.
{
             auto self = static_cast<CRTP*>(this);
             self->multi_option_policy(MultiOptionPolicy::TakeAll);
             return self;
         }
References CLI::TakeAll.
take_first()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::take_first () inline
Set the multi option policy to take last.
Definition at line 4295 of file CLI11.hpp.
{
             auto self = static_cast<CRTP*>(this);
             self->multi_option_policy(MultiOptionPolicy::TakeFirst);
             return self;
         }
References CLI::TakeFirst.
Referenced by utils::Config::init().
take_last()
template<typename CRTP > CRTP* CLI::OptionBase< CRTP >::take_last () inline
Set the multi option policy to take last.
Definition at line 4288 of file CLI11.hpp.
{
             auto self = static_cast<CRTP*>(this);
             self->multi_option_policy(MultiOptionPolicy::TakeLast);
             return self;
         }
References CLI::TakeLast.
Member Data Documentation
always_capture_default_
template<typename CRTP > bool CLI::OptionBase< CRTP >::always_capture_default_ {false} protected
Automatically capture default value.
Definition at line 4191 of file CLI11.hpp.
App
template<typename CRTP > friend CLI::OptionBase< CRTP >::App private
Definition at line 4166 of file CLI11.hpp.
configurable_
template<typename CRTP > bool CLI::OptionBase< CRTP >::configurable_ {true} protected
Allow this option to be given in a configuration file.
Definition at line 4182 of file CLI11.hpp.
delimiter_
template<typename CRTP > char CLI::OptionBase< CRTP >::delimiter_ {'\0'} protected
Specify a delimiter character for vector arguments.
Definition at line 4188 of file CLI11.hpp.
disable_flag_override_
template<typename CRTP > bool CLI::OptionBase< CRTP >::disable_flag_override_ {false} protected
Disable overriding flag values with '=value'.
Definition at line 4185 of file CLI11.hpp.
group_
template<typename CRTP > std::string CLI::OptionBase< CRTP >::group_ = std::string("Options") protected
The group membership.
Definition at line 4170 of file CLI11.hpp.
ignore_case_
template<typename CRTP > bool CLI::OptionBase< CRTP >::ignore_case_ {false} protected
Ignore the case when matching (option, not value)
Definition at line 4176 of file CLI11.hpp.
ignore_underscore_
template<typename CRTP > bool CLI::OptionBase< CRTP >::ignore_underscore_ {false} protected
Ignore underscores when matching (option, not value)
Definition at line 4179 of file CLI11.hpp.
multi_option_policy_
template<typename CRTP > MultiOptionPolicy CLI::OptionBase< CRTP >::multi_option_policy_ {MultiOptionPolicy::Throw} protected
Policy for handling multiple arguments beyond the expected Max.
Definition at line 4194 of file CLI11.hpp.
required_
template<typename CRTP > bool CLI::OptionBase< CRTP >::required_ {false} protected
True if this is a required option.
Definition at line 4173 of file CLI11.hpp.
Referenced by CLI::App::_parse_positional().
The documentation for this class was generated from the following file:
utils/CLI11.hpp