snode.c: net::in6::stream::ServerSocket< ConfigT > Class Template Reference
net::in6::stream::ServerSocket< ConfigT > Class Template Reference
#include <ServerSocket.h>
Public Types
using Config = ConfigT
Public Types inherited from net::ServerSocket< ConfigT, net::in6::stream::Socket >
using Config = ConfigT
using Socket = net::in6::stream::Socket
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
void listen (uint16_t port, int backlog, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &ipOrHostname, int backlog, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &ipOrHostname, uint16_t port, int backlog, const std::function< void(const SocketAddress &, int)> &onError)
Public Member Functions inherited from net::ServerSocket< ConfigT, net::in6::stream::Socket >
virtual void listen (const std::function< void(const SocketAddress &, int)> &onError) const=0
void listen (const SocketAddress &localAddress, int backlog, const std::function< void(const SocketAddress &, int)> &onError) const
Config & getConfig ()
Protected Member Functions
ServerSocket (const std::string &name)
Protected Member Functions inherited from net::ServerSocket< ConfigT, net::in6::stream::Socket >
ServerSocket (const std::string &name)
ServerSocket (const ServerSocket &)=default
virtual ~ServerSocket ()=default
Private Types
using Super = net::ServerSocket< ConfigT, net::in6::stream::Socket >
Additional Inherited Members
Protected Attributes inherited from net::ServerSocket< ConfigT, net::in6::stream::Socket >
std::shared_ptr< Config > config
Detailed Description
template<typename ConfigT>
class net::in6::stream::ServerSocket< ConfigT >
Definition at line 36 of file ServerSocket.h.
Member Typedef Documentation
Config
template<typename ConfigT > using net::in6::stream::ServerSocket< ConfigT >::Config = ConfigT
Definition at line 43 of file ServerSocket.h.
Super
template<typename ConfigT > using net::in6::stream::ServerSocket< ConfigT >::Super = net::ServerSocket<ConfigT, net::in6::stream::Socket> private
Definition at line 37 of file ServerSocket.h.
Constructor & Destructor Documentation
ServerSocket()
template<typename Config > net::in6::stream::ServerSocket< Config >::ServerSocket (const std::string & name) explicit protected
Definition at line 28 of file ServerSocket.hpp.
         : Super(name) {
     }
Member Function Documentation
listen() [1/3]
template<typename Config > void net::in6::stream::ServerSocket< Config >::listen (const std::string & ipOrHostname, int backlog, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 38 of file ServerSocket.hpp.
{
         listen(SocketAddress(ipOrHostname), backlog, onError);
     }
References core::system::listen().
listen() [2/3]
template<typename Config > void net::in6::stream::ServerSocket< Config >::listen (const std::string & ipOrHostname, uint16_t port, int backlog, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 45 of file ServerSocket.hpp.
{
         listen(SocketAddress(ipOrHostname, port), backlog, onError);
     }
References core::system::listen().
listen() [3/3]
template<typename Config > void net::in6::stream::ServerSocket< Config >::listen (uint16_t port, int backlog, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 33 of file ServerSocket.hpp.
{
         listen(SocketAddress(port), backlog, onError);
     }
References core::system::listen().
The documentation for this class was generated from the following files:
net/in6/stream/ServerSocket.h
net/in6/stream/ServerSocket.hpp