snode.c: net::ConfigLocal< SocketAddressT > Class Template Reference
net::ConfigLocal< SocketAddressT > Class Template Reference abstract
#include <ConfigLocal.h>
Public Member Functions
const SocketAddress & getLocalAddress () const
void setLocalAddress (const SocketAddress &localAddress) const
Protected Types
using SocketAddress = SocketAddressT
Protected Member Functions
ConfigLocal ()=default
virtual ~ConfigLocal ()=default
Private Member Functions
virtual SocketAddress getAddress () const =0
Private Attributes
SocketAddress localAddress
bool initialized = false
Detailed Description
template<typename SocketAddressT>
class net::ConfigLocal< SocketAddressT >
Definition at line 31 of file ConfigLocal.h.
Member Typedef Documentation
SocketAddress
template<typename SocketAddressT > using net::ConfigLocal< SocketAddressT >::SocketAddress = SocketAddressT protected
Definition at line 36 of file ConfigLocal.h.
Constructor & Destructor Documentation
ConfigLocal()
template<typename SocketAddressT > net::ConfigLocal< SocketAddressT >::ConfigLocal () protected default
~ConfigLocal()
template<typename SocketAddressT > virtual net::ConfigLocal< SocketAddressT >::~ConfigLocal () protected virtual default
Member Function Documentation
getAddress()
template<typename SocketAddressT > virtual SocketAddress net::ConfigLocal< SocketAddressT >::getAddress () const private pure virtual
Implemented in net::un::ConfigLocal, net::rf::ConfigLocal, net::l2::ConfigLocal, net::in6::ConfigLocal, and net::in::ConfigLocal.
Referenced by net::ConfigLocal< SocketAddressT >::getLocalAddress().
getLocalAddress()
template<typename SocketAddressT > const SocketAddress& net::ConfigLocal< SocketAddressT >::getLocalAddress () const inline
Definition at line 39 of file ConfigLocal.h.
{
             if (!initialized) {
                 utils::Config::instance().parse(true); // Try command line parsing in case Address is not initialized using setLocalAddress
                 localAddress = getAddress();
                 initialized = true;
             }
             return localAddress;
         }
References net::ConfigLocal< SocketAddressT >::getAddress(), net::ConfigLocal< SocketAddressT >::initialized, utils::Config::instance(), net::ConfigLocal< SocketAddressT >::localAddress, and utils::Config::parse().
setLocalAddress()
template<typename SocketAddressT > void net::ConfigLocal< SocketAddressT >::setLocalAddress (const SocketAddress & localAddress) const inline
Definition at line 50 of file ConfigLocal.h.
{
             this->localAddress = localAddress;
             this->initialized = true;
         }
References net::ConfigLocal< SocketAddressT >::initialized, and net::ConfigLocal< SocketAddressT >::localAddress.
Member Data Documentation
initialized
template<typename SocketAddressT > bool net::ConfigLocal< SocketAddressT >::initialized = false mutable private
Definition at line 59 of file ConfigLocal.h.
Referenced by net::ConfigLocal< SocketAddressT >::getLocalAddress(), and net::ConfigLocal< SocketAddressT >::setLocalAddress().
localAddress
template<typename SocketAddressT > SocketAddress net::ConfigLocal< SocketAddressT >::localAddress mutable private
Definition at line 58 of file ConfigLocal.h.
Referenced by net::ConfigLocal< SocketAddressT >::getLocalAddress(), and net::ConfigLocal< SocketAddressT >::setLocalAddress().
The documentation for this class was generated from the following file:
net/ConfigLocal.h