snode.c: net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT > Class Template Reference
net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT > Class Template Reference
#include <SocketClient.h>
Public Types
using SocketContextFactory = SocketContextFactoryT
using SocketConnector = SocketConnectorT
using SocketConnection = typename SocketConnector::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Member Functions
SocketClient (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketClient ()=default
void connect (const SocketAddress &remoteAddress, const SocketAddress &bindAddress, const std::function< void(int)> &onError) const
void connect (const SocketAddress &remoteAddress, const std::function< void(int)> &onError) const
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Private Member Functions
SocketClient ()=delete
Private Attributes
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(const SocketAddress &, const SocketAddress &)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename SocketConnectorT, typename SocketContextFactoryT>
class net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >
Definition at line 36 of file SocketClient.h.
Member Typedef Documentation
SocketAddress
template<typename SocketConnectorT , typename SocketContextFactoryT > using net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::SocketAddress = typename SocketConnection::Socket::SocketAddress
Definition at line 49 of file SocketClient.h.
SocketConnection
template<typename SocketConnectorT , typename SocketContextFactoryT > using net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::SocketConnection = typename SocketConnector::SocketConnection
Definition at line 48 of file SocketClient.h.
SocketConnector
template<typename SocketConnectorT , typename SocketContextFactoryT > using net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::SocketConnector = SocketConnectorT
Definition at line 47 of file SocketClient.h.
SocketContextFactory
template<typename SocketConnectorT , typename SocketContextFactoryT > using net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::SocketContextFactory = SocketContextFactoryT
Definition at line 46 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient() [1/2]
template<typename SocketConnectorT , typename SocketContextFactoryT > net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::SocketClient () private delete
Sequence diagramm showing how a connect to a peer is performed.
SocketClient() [2/2]
template<typename SocketConnectorT , typename SocketContextFactoryT > net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::SocketClient (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 51 of file SocketClient.h.
                                                                 {{}})
             : socketContextFactory(std::make_shared<SocketContextFactory>())
             , _onConnect(onConnect)
             , _onConnected(onConnected)
             , _onDisconnect(onDisconnect)
             , options(options) {
         }
~SocketClient()
template<typename SocketConnectorT , typename SocketContextFactoryT > virtual net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::~SocketClient () virtual default
Member Function Documentation
connect() [1/2]
template<typename SocketConnectorT , typename SocketContextFactoryT > void net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect (const SocketAddress & remoteAddress, const SocketAddress & bindAddress, const std::function< void(int)> & onError) const inline
Definition at line 64 of file SocketClient.h.
{
             SocketConnector* socketConnector = new SocketConnector(socketContextFactory, _onConnect, _onConnected, _onDisconnect, options);
             socketConnector->connect(remoteAddress, bindAddress, onError);
         }
References net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onConnect, net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onConnected, net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onDisconnect, net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::options, and net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::socketContextFactory.
Referenced by net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect().
connect() [2/2]
template<typename SocketConnectorT , typename SocketContextFactoryT > void net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect (const SocketAddress & remoteAddress, const std::function< void(int)> & onError) const inline
Definition at line 70 of file SocketClient.h.
{
             connect(remoteAddress, SocketAddress(), onError);
         }
References net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect().
getSocketContextFactory()
template<typename SocketConnectorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::getSocketContextFactory () inline
Definition at line 86 of file SocketClient.h.
{
             return socketContextFactory;
         }
References net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::socketContextFactory.
onConnect()
template<typename SocketConnectorT , typename SocketContextFactoryT > void net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect) inline
Definition at line 74 of file SocketClient.h.
{
             _onConnect = onConnect;
         }
References net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onConnect.
onConnected()
template<typename SocketConnectorT , typename SocketContextFactoryT > void net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::onConnected (const std::function< void(SocketConnection *)> & onConnected) inline
Definition at line 78 of file SocketClient.h.
{
             _onConnected = onConnected;
         }
References net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onConnected.
onDisconnect()
template<typename SocketConnectorT , typename SocketContextFactoryT > void net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::onDisconnect (const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 82 of file SocketClient.h.
{
             _onDisconnect = onDisconnect;
         }
References net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onDisconnect.
Member Data Documentation
_onConnect
template<typename SocketConnectorT , typename SocketContextFactoryT > std::function<void(const SocketAddress&, const SocketAddress&)> net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onConnect private
Definition at line 93 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect(), and net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::onConnect().
_onConnected
template<typename SocketConnectorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onConnected private
Definition at line 94 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect(), and net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::onConnected().
_onDisconnect
template<typename SocketConnectorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::_onDisconnect private
Definition at line 95 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect(), and net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::onDisconnect().
options
template<typename SocketConnectorT , typename SocketContextFactoryT > std::map<std::string, std::any> net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::options private
Definition at line 97 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect().
socketContextFactory
template<typename SocketConnectorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::socketContextFactory private
Definition at line 91 of file SocketClient.h.
Referenced by net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::connect(), and net::socket::stream::SocketClient< SocketConnectorT, SocketContextFactoryT >::getSocketContextFactory().
The documentation for this class was generated from the following file:
net/socket/stream/SocketClient.h