snode.c: core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT > Class Template Reference
core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT > Class Template Reference
#include <SocketConnection.h>
Public Member Functions
void close () final
void shutdownRead () final
void shutdownWrite (bool forceClose) final
void setTimeout (const utils::Timeval &timeout) final
const SocketAddress & getRemoteAddress () const
const SocketAddress & getLocalAddress () const
int getDescriptor () const override
ssize_t readFromPeer (char *junk, std::size_t junkLen) final
void sendToPeer (const char *junk, std::size_t junkLen) final
void sendToPeer (const std::string &data) final
core::socket::SocketContext * getSocketContext ()
Protected Types
using Super = core::socket::SocketConnection
using Socket = SocketT
using SocketReader = SocketReaderT< Socket >
using SocketWriter = SocketWriterT< Socket >
using SocketAddress = typename Socket::SocketAddress
Protected Member Functions
SocketConnection (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const SocketAddress &localAddress, const SocketAddress &remoteAddress, [[maybe_unused]] const std::function< void()> &onConnect, const std::function< void()> &onDisconnect, const utils::Timeval &readTimeout, const utils::Timeval &writeTimeout, std::size_t readBlockSize, std::size_t writeBlockSize, const utils::Timeval &terminateTimeout)
~SocketConnection () override
Protected Member Functions inherited from core::socket::SocketConnection
SocketConnection (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory)
void onConnected ()
void onDisconnected ()
void onReceiveFromPeer ()
void onWriteError (int errnum)
void onReadError (int errnum)
core::socket::SocketContext * getSocketContext ()
core::socket::SocketContext * switchSocketContext (core::socket::SocketContextFactory *socketContextFactory)
Private Member Functions
SocketConnection ()=delete
void readEvent () final
void writeEvent () final
void unobservedEvent () final
Private Attributes
SocketAddress localAddress {}
SocketAddress remoteAddress {}
core::socket::SocketContext * newSocketContext = nullptr
std::function< void()> onDisconnect
Friends
template<typename ServerSocket , template< typename Socket > class SocketConnection>
class SocketAcceptor
template<typename ClientSocket , template< typename Socket > class SocketConnection>
class SocketConnector
Detailed Description
template<typename SocketT, template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT>
class core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >
Definition at line 37 of file SocketConnection.h.
Member Typedef Documentation
Socket
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> using core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::Socket = SocketT protected
Definition at line 46 of file SocketConnection.h.
SocketAddress
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> using core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::SocketAddress = typename Socket::SocketAddress protected
Definition at line 50 of file SocketConnection.h.
SocketReader
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> using core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::SocketReader = SocketReaderT<Socket> protected
Definition at line 47 of file SocketConnection.h.
SocketWriter
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> using core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::SocketWriter = SocketWriterT<Socket> protected
Definition at line 48 of file SocketConnection.h.
Super
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> using core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::Super = core::socket::SocketConnection protected
Definition at line 44 of file SocketConnection.h.
Constructor & Destructor Documentation
SocketConnection() [1/2]
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::SocketConnection () private delete
SocketConnection() [2/2]
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::SocketConnection (const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory, const SocketAddress & localAddress, const SocketAddress & remoteAddress, [[maybe_unused] ] const std::function< void()> & onConnect, const std::function< void()> & onDisconnect, const utils::Timeval & readTimeout, const utils::Timeval & writeTimeout, std::size_t readBlockSize, std::size_t writeBlockSize, const utils::Timeval & terminateTimeout) inline protected
Definition at line 52 of file SocketConnection.h.
             : Super(socketContextFactory)
             , SocketReader(
                   [this](int errnum) -> void {
                       onReadError(errnum);
                   },
                   readTimeout,
                   readBlockSize,
                   terminateTimeout)
             , SocketWriter(
                   [this](int errnum) -> void {
                       onWriteError(errnum);
                   },
                   writeTimeout,
                   writeBlockSize,
                   terminateTimeout)
             , localAddress(localAddress)
             , remoteAddress(remoteAddress)
             , onDisconnect(onDisconnect) {
             onConnect();
         }
~SocketConnection()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::~SocketConnection () inline override protected virtual
Reimplemented from core::socket::SocketConnection.
Definition at line 83 of file SocketConnection.h.
{
             onDisconnected();
             onDisconnect();
         }
Member Function Documentation
close()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::close () inline final virtual
Implements core::socket::SocketConnection.
Definition at line 91 of file SocketConnection.h.
{
             if (SocketWriter::isEnabled()) {
                 SocketWriter::disable();
             }
             if (SocketReader::isEnabled()) {
                 SocketReader::disable();
             }
         }
References core::DescriptorEventReceiver::disable(), and core::DescriptorEventReceiver::isEnabled().
Referenced by core::socket::stream::tls::SocketConnection< SocketT >::doSSLHandshake(), and core::socket::stream::tls::SocketConnection< SocketT >::doWriteShutdown().
getDescriptor()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> int core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::getDescriptor () const inline override virtual
Implements core::socket::SocketConnection.
Definition at line 130 of file SocketConnection.h.
{
             return SocketConnection::getFd();
         }
getLocalAddress()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> const SocketAddress& core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::getLocalAddress () const inline
Definition at line 126 of file SocketConnection.h.
{
             return localAddress;
         }
getRemoteAddress()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> const SocketAddress& core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::getRemoteAddress () const inline
Definition at line 122 of file SocketConnection.h.
{
             return remoteAddress;
         }
getSocketContext()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> core::socket::SocketContext * core::socket::SocketConnection::getSocketContext
Definition at line 55 of file SocketConnection.cpp.
{
         return socketContext;
     }
readEvent()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::readEvent () inline final private
Definition at line 159 of file SocketConnection.h.
{
             SocketReader::doRead();
             onReceiveFromPeer();
         }
References core::socket::stream::SocketReader< SocketT >::doRead().
readFromPeer()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> ssize_t core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::readFromPeer (char * junk, std::size_t junkLen) inline final virtual
Implements core::socket::SocketConnection.
Definition at line 134 of file SocketConnection.h.
{
             ssize_t ret = 0;
             if (newSocketContext == nullptr) {
                 ret = SocketReader::readFromPeer(junk, junkLen);
             } else {
                 VLOG(0) << "ReadFromPeer: OldSocketContext != nullptr: SocketContextSwitch in progress";
             }
             return ret;
         }
References core::socket::stream::SocketReader< SocketT >::readFromPeer().
sendToPeer() [1/2]
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::sendToPeer (const char * junk, std::size_t junkLen) inline final virtual
Implements core::socket::SocketConnection.
Definition at line 146 of file SocketConnection.h.
{
             if (newSocketContext == nullptr) {
                 SocketWriter::sendToPeer(junk, junkLen);
             } else {
                 VLOG(0) << "SendToPeer: OldSocketContext != nullptr: SocketContextSwitch in progress";
             }
         }
References core::socket::stream::SocketWriter< SocketT >::sendToPeer().
sendToPeer() [2/2]
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::sendToPeer (const std::string & data) inline final virtual
Implements core::socket::SocketConnection.
Definition at line 154 of file SocketConnection.h.
{
             sendToPeer(data.data(), data.size());
         }
setTimeout()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::setTimeout (const utils::Timeval & timeout) inline final virtual
Implements core::socket::SocketConnection.
Definition at line 117 of file SocketConnection.h.
{
             SocketReader::setTimeout(timeout);
             SocketWriter::setTimeout(timeout);
         }
References core::DescriptorEventReceiver::setTimeout().
shutdownRead()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::shutdownRead () inline final virtual
Implements core::socket::SocketConnection.
Definition at line 100 of file SocketConnection.h.
{
             SocketReader::shutdown();
         }
References core::socket::stream::SocketReader< SocketT >::shutdown().
shutdownWrite()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::shutdownWrite (bool forceClose) inline final virtual
Implements core::socket::SocketConnection.
Definition at line 104 of file SocketConnection.h.
{
             SocketWriter::shutdown([forceClose, this](int errnum) -> void {
                 if (errnum != 0) {
                     PLOG(INFO) << "SocketWriter::doWriteShutdown";
                 }
                 if (forceClose) {
                     close();
                 } else if (SocketWriter::isEnabled()) {
                     SocketWriter::disable();
                 }
             });
         }
References core::system::close(), core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::isEnabled(), and core::socket::stream::SocketWriter< SocketT >::shutdown().
unobservedEvent()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::unobservedEvent () inline final private
Definition at line 168 of file SocketConnection.h.
{
             delete this;
         }
writeEvent()
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> void core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::writeEvent () inline final private
Definition at line 164 of file SocketConnection.h.
{
             SocketWriter::doWrite();
         }
References core::socket::stream::SocketWriter< SocketT >::doWrite().
Friends And Related Function Documentation
SocketAcceptor
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> template<typename ServerSocket , template< typename Socket > class SocketConnection> friend class SocketAcceptor friend
Definition at line 180 of file SocketConnection.h.
SocketConnector
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> template<typename ClientSocket , template< typename Socket > class SocketConnection> friend class SocketConnector friend
Definition at line 183 of file SocketConnection.h.
Member Data Documentation
localAddress
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> SocketAddress core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::localAddress {} private
Definition at line 172 of file SocketConnection.h.
newSocketContext
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> core::socket::SocketContext* core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::newSocketContext = nullptr private
Definition at line 175 of file SocketConnection.h.
onDisconnect
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> std::function<void()> core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::onDisconnect private
Definition at line 177 of file SocketConnection.h.
remoteAddress
template<typename SocketT , template< typename Socket > class SocketReaderT, template< typename Socket > class SocketWriterT> SocketAddress core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::remoteAddress {} private
Definition at line 173 of file SocketConnection.h.
The documentation for this class was generated from the following file:
core/socket/stream/SocketConnection.h