snode.c: net::in::stream::ClientSocket< ConfigT > Class Template Reference
net::in::stream::ClientSocket< ConfigT > Class Template Reference
#include <ClientSocket.h>
Public Types
using Config = ConfigT
Public Types inherited from net::ClientSocket< ConfigT, net::in::stream::Socket >
using Config = ConfigT
using Socket = net::in::stream::Socket
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
void connect (const std::string &ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindIpOrHostname, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindIpOrHostname, uint16_t bindPort, const std::function< void(const SocketAddress &, int)> &onError)
Public Member Functions inherited from net::ClientSocket< ConfigT, net::in::stream::Socket >
virtual void connect (const std::function< void(const SocketAddress &, int)> &onError) const=0
void connect (const SocketAddress &remoteAddress, const SocketAddress &localAddress, const std::function< void(const SocketAddress &, int)> &onError) const
void connect (const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, int)> &onError) const
Config & getConfig ()
Protected Member Functions
ClientSocket (const std::string &name)
Protected Member Functions inherited from net::ClientSocket< ConfigT, net::in::stream::Socket >
ClientSocket (const std::string &name)
ClientSocket (const ClientSocket &)=default
virtual ~ClientSocket ()=default
Private Types
using Super = net::ClientSocket< ConfigT, net::in::stream::Socket >
Additional Inherited Members
Protected Attributes inherited from net::ClientSocket< ConfigT, net::in::stream::Socket >
std::shared_ptr< Config > config
Detailed Description
template<typename ConfigT>
class net::in::stream::ClientSocket< ConfigT >
Definition at line 36 of file ClientSocket.h.
Member Typedef Documentation
Config
template<typename ConfigT > using net::in::stream::ClientSocket< ConfigT >::Config = ConfigT
Definition at line 43 of file ClientSocket.h.
Super
template<typename ConfigT > using net::in::stream::ClientSocket< ConfigT >::Super = net::ClientSocket<ConfigT, net::in::stream::Socket> private
Definition at line 37 of file ClientSocket.h.
Constructor & Destructor Documentation
ClientSocket()
template<typename Config > net::in::stream::ClientSocket< Config >::ClientSocket (const std::string & name) explicit protected
Definition at line 28 of file ClientSocket.hpp.
         : Super(name) {
     }
Member Function Documentation
connect() [1/3]
template<typename Config > void net::in::stream::ClientSocket< Config >::connect (const std::string & ipOrHostname, uint16_t port, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 33 of file ClientSocket.hpp.
{
         connect(SocketAddress(ipOrHostname, port), onError);
     }
References core::system::connect().
connect() [2/3]
template<typename Config > void net::in::stream::ClientSocket< Config >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindIpOrHostname, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 40 of file ClientSocket.hpp.
{
         connect(SocketAddress(ipOrHostname, port), SocketAddress(bindIpOrHostname), onError);
     }
References core::system::connect().
connect() [3/3]
template<typename Config > void net::in::stream::ClientSocket< Config >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindIpOrHostname, uint16_t bindPort, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 48 of file ClientSocket.hpp.
{
         connect(SocketAddress(ipOrHostname, port), SocketAddress(bindIpOrHostname, bindPort), onError);
     }
References core::system::connect().
The documentation for this class was generated from the following files:
net/in/stream/ClientSocket.h
net/in/stream/ClientSocket.hpp