snode.c: express::Route Class Reference
express::Route Class Reference
#include <Route.h>
Public Member Functions
Route (const std::string &method, const std::string &relativeMountPath, const std::shared_ptr< Dispatcher > &dispatcher)
Route & use (const std::function< void(Request &req, Response &res)> &lambda)
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & use (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & all (const std::function< void(Request &req, Response &res)> &lambda)
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & all (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & get (const std::function< void(Request &req, Response &res)> &lambda)
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & get (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & put (const std::function< void(Request &req, Response &res)> &lambda)
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & put (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & post (const std::function< void(Request &req, Response &res)> &lambda)
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & post (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & del (const std::function< void(Request &req, Response &res)> &lambda)
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & del (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & connect (const std::function< void(Request &req, Response &res)> &lambda)
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & connect (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & options (const std::function< void(Request &req, Response &res)> &lambda)
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & options (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & trace (const std::function< void(Request &req, Response &res)> &lambda)
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & trace (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & patch (const std::function< void(Request &req, Response &res)> &lambda)
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & patch (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Route & head (const std::function< void(Request &req, Response &res)> &lambda)
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res)> &lambda, Lambdas... lambdas)
template<typename... Lambdas>
Route & head (const std::function< void(Request &req, Response &res, Next &next)> &lambda, Lambdas... lambdas)
Protected Member Functions
Route ()
bool dispatch (Controller &state)
bool dispatch (Controller &state, const std::string &parentMountPath)
bool dispatchNext (Controller &state, const std::string &parentMountPath)
Protected Attributes
MountPoint mountPoint
std::shared_ptr< Dispatcher > dispatcher
Friends
class dispatcher::RouterDispatcher
class Dispatcher
class RootRoute
class Controller
Detailed Description
Definition at line 64 of file Route.h.
Constructor & Destructor Documentation
Route() [1/2]
express::Route::Route (const std::string & method, const std::string & relativeMountPath, const std::shared_ptr< Dispatcher > & dispatcher)
Definition at line 51 of file Route.cpp.
         : mountPoint(method, relativeMountPath)
         , dispatcher(dispatcher) {
     }
Route() [2/2]
express::Route::Route () protected
Definition at line 46 of file Route.cpp.
         : mountPoint("use", "")
         , dispatcher(std::make_shared<dispatcher::RouterDispatcher>()) {
     }
Member Function Documentation
all() [1/4]
Route & express::Route::all (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 77 of file Route.cpp.
all() [2/4]
template<typename... Lambdas> Route & express::Route::all (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 50 of file Route.hpp.
all() [3/4]
Route & express::Route::all (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 77 of file Route.cpp.
all() [4/4]
template<typename... Lambdas> Route & express::Route::all (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 50 of file Route.hpp.
connect() [1/4]
Route & express::Route::connect (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 82 of file Route.cpp.
connect() [2/4]
template<typename... Lambdas> Route & express::Route::connect (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 55 of file Route.hpp.
connect() [3/4]
Route & express::Route::connect (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 82 of file Route.cpp.
connect() [4/4]
template<typename... Lambdas> Route & express::Route::connect (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 55 of file Route.hpp.
del() [1/4]
Route & express::Route::del (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 81 of file Route.cpp.
del() [2/4]
template<typename... Lambdas> Route & express::Route::del (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 54 of file Route.hpp.
del() [3/4]
Route & express::Route::del (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 81 of file Route.cpp.
del() [4/4]
template<typename... Lambdas> Route & express::Route::del (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 54 of file Route.hpp.
dispatch() [1/2]
bool express::Route::dispatch (Controller & state) protected
Definition at line 56 of file Route.cpp.
{
         return dispatch(state, "");
     }
Referenced by express::RootRoute::dispatch().
dispatch() [2/2]
bool express::Route::dispatch (Controller & state, const std::string & parentMountPath) protected
Definition at line 60 of file Route.cpp.
{
         state.setCurrentRoute(this);
         bool dispatched = dispatcher->dispatch(state, parentMountPath, mountPoint);
         if (!dispatched) { // TODO: only call if parent route matched
             dispatched = state.dispatchNext(parentMountPath);
         }
         return dispatched;
     }
References dispatcher, express::Controller::dispatchNext(), mountPoint, and express::Controller::setCurrentRoute().
dispatchNext()
bool express::Route::dispatchNext (Controller & state, const std::string & parentMountPath) protected
Definition at line 72 of file Route.cpp.
{
         return dispatcher->dispatchNext(state, parentMountPath);
     }
References dispatcher.
Referenced by express::Controller::dispatchNext().
get() [1/4]
Route & express::Route::get (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 78 of file Route.cpp.
get() [2/4]
template<typename... Lambdas> Route & express::Route::get (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 51 of file Route.hpp.
get() [3/4]
Route & express::Route::get (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 78 of file Route.cpp.
get() [4/4]
template<typename... Lambdas> Route & express::Route::get (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 51 of file Route.hpp.
head() [1/4]
Route & express::Route::head (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 86 of file Route.cpp.
head() [2/4]
template<typename... Lambdas> Route & express::Route::head (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 59 of file Route.hpp.
head() [3/4]
Route & express::Route::head (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 86 of file Route.cpp.
head() [4/4]
template<typename... Lambdas> Route & express::Route::head (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 59 of file Route.hpp.
options() [1/4]
Route & express::Route::options (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 83 of file Route.cpp.
options() [2/4]
template<typename... Lambdas> Route & express::Route::options (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 56 of file Route.hpp.
options() [3/4]
Route & express::Route::options (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 83 of file Route.cpp.
options() [4/4]
template<typename... Lambdas> Route & express::Route::options (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 56 of file Route.hpp.
patch() [1/4]
Route & express::Route::patch (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 85 of file Route.cpp.
patch() [2/4]
template<typename... Lambdas> Route & express::Route::patch (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 58 of file Route.hpp.
patch() [3/4]
Route & express::Route::patch (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 85 of file Route.cpp.
patch() [4/4]
template<typename... Lambdas> Route & express::Route::patch (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 58 of file Route.hpp.
post() [1/4]
Route & express::Route::post (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 80 of file Route.cpp.
post() [2/4]
template<typename... Lambdas> Route & express::Route::post (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 53 of file Route.hpp.
post() [3/4]
Route & express::Route::post (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 80 of file Route.cpp.
post() [4/4]
template<typename... Lambdas> Route & express::Route::post (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 53 of file Route.hpp.
put() [1/4]
Route & express::Route::put (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 79 of file Route.cpp.
put() [2/4]
template<typename... Lambdas> Route & express::Route::put (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 52 of file Route.hpp.
put() [3/4]
Route & express::Route::put (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 79 of file Route.cpp.
put() [4/4]
template<typename... Lambdas> Route & express::Route::put (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 52 of file Route.hpp.
trace() [1/4]
Route & express::Route::trace (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 84 of file Route.cpp.
trace() [2/4]
template<typename... Lambdas> Route & express::Route::trace (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 57 of file Route.hpp.
trace() [3/4]
Route & express::Route::trace (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 84 of file Route.cpp.
trace() [4/4]
template<typename... Lambdas> Route & express::Route::trace (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 57 of file Route.hpp.
use() [1/4]
Route & express::Route::use (const std::function< void(Request &req, Response &res)> & lambda)
Definition at line 76 of file Route.cpp.
use() [2/4]
template<typename... Lambdas> Route & express::Route::use (const std::function< void(Request &req, Response &res)> & lambda, Lambdas... lambdas)
Definition at line 49 of file Route.hpp.
use() [3/4]
Route & express::Route::use (const std::function< void(Request &req, Response &res, Next &next)> & lambda)
Definition at line 76 of file Route.cpp.
use() [4/4]
template<typename... Lambdas> Route & express::Route::use (const std::function< void(Request &req, Response &res, Next &next)> & lambda, Lambdas... lambdas)
Definition at line 49 of file Route.hpp.
Friends And Related Function Documentation
Controller
friend class Controller friend
Definition at line 94 of file Route.h.
Dispatcher
friend class Dispatcher friend
Definition at line 92 of file Route.h.
dispatcher::RouterDispatcher
friend class dispatcher::RouterDispatcher friend
Definition at line 91 of file Route.h.
RootRoute
friend class RootRoute friend
Definition at line 93 of file Route.h.
Member Data Documentation
dispatcher
std::shared_ptr<Dispatcher> express::Route::dispatcher protected
Definition at line 76 of file Route.h.
Referenced by dispatch(), dispatchNext(), express::RootRoute::getDispatcher(), and express::RootRoute::routes().
mountPoint
MountPoint express::Route::mountPoint protected
Definition at line 75 of file Route.h.
Referenced by dispatch().
The documentation for this class was generated from the following files:
express/Route.h
express/Route.cpp
express/Route.hpp