snode.c: net::rf::stream::ConfigConnect Class Reference
net::rf::stream::ConfigConnect Class Reference
#include <ConfigConnect.h>
Public Member Functions
ConfigConnect (CLI::App *baseSc)
const std::string & getConnectHost () const
uint8_t getConnectChannel () const
SocketAddress getConnectAddress () const
Protected Member Functions
void required (bool req) const
Protected Attributes
CLI::App * connectSc = nullptr
CLI::Option * connectHostOpt = nullptr
CLI::Option * connectChannelOpt = nullptr
Private Attributes
std::string connectHost = ""
uint8_t connectChannel = 0
Detailed Description
Definition at line 38 of file ConfigConnect.h.
Constructor & Destructor Documentation
ConfigConnect()
net::rf::stream::ConfigConnect::ConfigConnect (CLI::App * baseSc) explicit
Definition at line 31 of file ConfigConnect.cpp.
{
         connectSc = baseSc->add_subcommand("bind");
         connectSc->description("Bind options");
         connectSc->configurable();
         connectSc->required();
         connectHostOpt = connectSc->add_option("-a,--host", connectHost, "Bluetooth address");
         connectHostOpt->type_name("[bluetooth address]");
         connectHostOpt->default_val("00:00:00:00:00:00");
         connectHostOpt->configurable();
         connectChannelOpt = connectSc->add_option("-c,--channel", connectChannel, "Channel number");
         connectChannelOpt->type_name("[uint8_t]");
         connectChannelOpt->default_val(0);
         connectChannelOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), connectChannel, connectChannelOpt, connectHost, connectHostOpt, connectSc, CLI::Option::default_val(), CLI::App::description(), CLI::App::required(), and CLI::Option::type_name().
Member Function Documentation
getConnectAddress()
SocketAddress net::rf::stream::ConfigConnect::getConnectAddress () const
Definition at line 56 of file ConfigConnect.cpp.
{
         return SocketAddress(connectHost, connectChannel);
     }
References connectChannel, and connectHost.
getConnectChannel()
uint8_t net::rf::stream::ConfigConnect::getConnectChannel () const
Definition at line 52 of file ConfigConnect.cpp.
{
         return connectChannel;
     }
References connectChannel.
getConnectHost()
const std::string & net::rf::stream::ConfigConnect::getConnectHost () const
Definition at line 48 of file ConfigConnect.cpp.
{
         return connectHost;
     }
References connectHost.
required()
void net::rf::stream::ConfigConnect::required (bool req) const protected
Definition at line 60 of file ConfigConnect.cpp.
{
         utils::Config::instance().required(connectSc, req);
         utils::Config::instance().required(connectHostOpt, req);
         utils::Config::instance().required(connectChannelOpt, req);
     }
References connectChannelOpt, connectHostOpt, connectSc, utils::Config::instance(), and utils::Config::required().
Referenced by net::rf::stream::ClientConfig::required().
Member Data Documentation
connectChannel
uint8_t net::rf::stream::ConfigConnect::connectChannel = 0 private
Definition at line 57 of file ConfigConnect.h.
Referenced by ConfigConnect(), getConnectAddress(), and getConnectChannel().
connectChannelOpt
CLI::Option* net::rf::stream::ConfigConnect::connectChannelOpt = nullptr protected
Definition at line 53 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
connectHost
std::string net::rf::stream::ConfigConnect::connectHost = "" private
Definition at line 56 of file ConfigConnect.h.
Referenced by ConfigConnect(), getConnectAddress(), and getConnectHost().
connectHostOpt
CLI::Option* net::rf::stream::ConfigConnect::connectHostOpt = nullptr protected
Definition at line 52 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
connectSc
CLI::App* net::rf::stream::ConfigConnect::connectSc = nullptr protected
Definition at line 51 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
The documentation for this class was generated from the following files:
net/rf/stream/ConfigConnect.h
net/rf/stream/ConfigConnect.cpp