snode.c: core::TimerEventDispatcher Class Reference
core::TimerEventDispatcher Class Reference
#include <TimerEventDispatcher.h>
Classes
class timernode_lt
Public Member Functions
TimerEventDispatcher ()=default
utils::Timeval getNextTimeout (const utils::Timeval &currentTime)
void dispatchActiveEvents (const utils::Timeval &currentTime)
void remove (core::TimerEventReceiver *timer)
void add (core::TimerEventReceiver *timer)
bool empty ()
void stop ()
Private Attributes
std::list< core::TimerEventReceiver * > timerList
std::list< core::TimerEventReceiver * > addedList
std::list< core::TimerEventReceiver * > removedList
bool timerListDirty = false
Detailed Description
Definition at line 36 of file TimerEventDispatcher.h.
Constructor & Destructor Documentation
TimerEventDispatcher()
core::TimerEventDispatcher::TimerEventDispatcher () default
Member Function Documentation
add()
void core::TimerEventDispatcher::add (core::TimerEventReceiver * timer)
Definition at line 83 of file TimerEventDispatcher.cpp.
{
         addedList.push_back(timer);
     }
References addedList.
Referenced by core::timer::Timer::intervalTimer(), and core::timer::Timer::singleshotTimer().
dispatchActiveEvents()
void core::TimerEventDispatcher::dispatchActiveEvents (const utils::Timeval & currentTime)
Definition at line 66 of file TimerEventDispatcher.cpp.
{
         for (TimerEventReceiver* timer : timerList) {
             if (timer->getTimeout() <= currentTime) {
                 timerListDirty = timer->dispatch();
             } else {
                 break;
             }
         }
     }
References timerList, and timerListDirty.
Referenced by core::EventDispatcher::dispatch().
empty()
bool core::TimerEventDispatcher::empty ()
Definition at line 87 of file TimerEventDispatcher.cpp.
{
         return timerList.empty();
     }
References timerList.
Referenced by core::EventDispatcher::dispatch().
getNextTimeout()
utils::Timeval core::TimerEventDispatcher::getNextTimeout (const utils::Timeval & currentTime)
Definition at line 32 of file TimerEventDispatcher.cpp.
{
         utils::Timeval nextTimeout({LONG_MAX, 0});
         for (TimerEventReceiver* timer : addedList) {
             timerList.push_back(timer);
             timerListDirty = true;
         }
         addedList.clear();
         for (TimerEventReceiver* timer : removedList) {
             timerList.remove(timer);
             timer->unobservedEvent();
             timerListDirty = true;
         }
         removedList.clear();
         if (!timerList.empty()) {
             if (timerListDirty) {
                 timerList.sort(core::TimerEventDispatcher::timernode_lt());
                 timerListDirty = false;
             }
             nextTimeout = (*(timerList.begin()))->getTimeout();
             if (nextTimeout < currentTime) {
                 nextTimeout = 0;
             } else {
                 nextTimeout -= currentTime;
             }
         }
         return nextTimeout;
     }
References addedList, removedList, timerList, and timerListDirty.
Referenced by core::EventDispatcher::dispatch(), and stop().
remove()
void core::TimerEventDispatcher::remove (core::TimerEventReceiver * timer)
Definition at line 76 of file TimerEventDispatcher.cpp.
{
         if (std::find(timerList.begin(), timerList.end(), timer) != timerList.end() &&
             std::find(removedList.begin(), removedList.end(), timer) == removedList.end()) {
             removedList.push_back(timer);
         }
     }
References removedList, and timerList.
Referenced by core::timer::Timer::cancel(), and stop().
stop()
void core::TimerEventDispatcher::stop ()
Definition at line 91 of file TimerEventDispatcher.cpp.
{
         utils::Timeval currentTime = utils::Timeval::currentTime();
         getNextTimeout(currentTime);
         for (TimerEventReceiver* timer : timerList) {
             remove(timer);
         }
         getNextTimeout(currentTime);
     }
References utils::Timeval::currentTime(), getNextTimeout(), remove(), and timerList.
Referenced by core::EventDispatcher::stop(), and core::EventDispatcher::stopTimerEvents().
Member Data Documentation
addedList
std::list<core::TimerEventReceiver*> core::TimerEventDispatcher::addedList private
Definition at line 53 of file TimerEventDispatcher.h.
Referenced by add(), and getNextTimeout().
removedList
std::list<core::TimerEventReceiver*> core::TimerEventDispatcher::removedList private
Definition at line 54 of file TimerEventDispatcher.h.
Referenced by getNextTimeout(), and remove().
timerList
std::list<core::TimerEventReceiver*> core::TimerEventDispatcher::timerList private
Definition at line 52 of file TimerEventDispatcher.h.
Referenced by dispatchActiveEvents(), empty(), getNextTimeout(), remove(), and stop().
timerListDirty
bool core::TimerEventDispatcher::timerListDirty = false private
Definition at line 56 of file TimerEventDispatcher.h.
Referenced by dispatchActiveEvents(), and getNextTimeout().
The documentation for this class was generated from the following files:
core/TimerEventDispatcher.h
core/TimerEventDispatcher.cpp