snode.c: net::ConfigBase Class Reference
net::ConfigBase Class Reference abstract
#include <ConfigBase.h>
Public Member Functions
ConfigBase (const std::string &name)
const std::string & getName () const
int parse (bool req=false) const
Protected Member Functions
virtual void required (bool req) const =0
Protected Attributes
CLI::App * baseSc = nullptr
Private Attributes
std::string name
Detailed Description
Definition at line 34 of file ConfigBase.h.
Constructor & Destructor Documentation
ConfigBase()
net::ConfigBase::ConfigBase (const std::string & name) explicit
Definition at line 30 of file ConfigBase.cpp.
         : name(name) {
         baseSc = utils::Config::instance().add_subcommand(name, name + " configuration");
         baseSc->configurable();
         baseSc->fallthrough();
     }
References utils::Config::add_subcommand(), baseSc, CLI::App::configurable(), CLI::App::fallthrough(), utils::Config::instance(), and name.
Member Function Documentation
getName()
const std::string & net::ConfigBase::getName () const
Definition at line 37 of file ConfigBase.cpp.
{
         return name;
     }
References name.
parse()
int net::ConfigBase::parse (bool req = false) const
Definition at line 41 of file ConfigBase.cpp.
{
         required(req);
         try {
             utils::Config::instance().parse();
         } catch (const CLI::ParseError& e) {
         }
         return 0;
     }
References utils::Config::instance(), utils::Config::parse(), and required().
required()
virtual void net::ConfigBase::required (bool req) const protected pure virtual
Implemented in net::un::stream::ServerConfig, net::rf::stream::ServerConfig, net::l2::stream::ServerConfig, net::in6::stream::ServerConfig, and net::in::stream::ServerConfig.
Referenced by parse().
Member Data Documentation
baseSc
CLI::App* net::ConfigBase::baseSc = nullptr protected
Definition at line 45 of file ConfigBase.h.
Referenced by ConfigBase(), net::in::stream::ServerConfig::required(), net::in6::stream::ServerConfig::required(), net::l2::stream::ServerConfig::required(), net::rf::stream::ServerConfig::required(), and net::un::stream::ServerConfig::required().
name
std::string net::ConfigBase::name private
Definition at line 48 of file ConfigBase.h.
Referenced by ConfigBase(), and getName().
The documentation for this class was generated from the following files:
net/ConfigBase.h
net/ConfigBase.cpp