snode.c: CLI::AsNumberWithUnit Class Reference
CLI::AsNumberWithUnit Class Reference
#include <CLI11.hpp>
Public Types
enum Options {
CASE_SENSITIVE = 0 , CASE_INSENSITIVE = 1 , UNIT_OPTIONAL = 0 , UNIT_REQUIRED = 2 ,
DEFAULT = CASE_INSENSITIVE | UNIT_OPTIONAL
}
Public Member Functions
template<typename Number >
AsNumberWithUnit (std::map< std::string, Number > mapping, Options opts=DEFAULT, const std::string &unit_name="UNIT")
Public Member Functions inherited from CLI::Validator
Validator ()=default
Validator (std::string validator_desc)
Construct a Validator with just the description string.
Validator (std::function< std::string(std::string &)> op, std::string validator_desc, std::string validator_name="")
Construct Validator from basic information.
Validator & operation (std::function< std::string(std::string &)> op)
Set the Validator operation function.
std::string operator() (std::string &str) const
std::string operator() (const std::string &str) const
Validator & description (std::string validator_desc)
Specify the type string.
Validator description (std::string validator_desc) const
Specify the type string.
std::string get_description () const
Generate type description information for the Validator.
Validator & name (std::string validator_name)
Specify the type string.
Validator name (std::string validator_name) const
Specify the type string.
const std::string & get_name () const
Get the name of the Validator.
Validator & active (bool active_val=true)
Specify whether the Validator is active or not.
Validator active (bool active_val=true) const
Specify whether the Validator is active or not.
Validator & non_modifying (bool no_modify=true)
Specify whether the Validator can be modifying or not.
Validator & application_index (int app_index)
Specify the application index of a validator.
Validator application_index (int app_index) const
Specify the application index of a validator.
int get_application_index () const
Get the current value of the application index.
bool get_active () const
Get a boolean if the validator is active.
bool get_modifying () const
Get a boolean if the validator is allowed to modify the input returns true if it can modify the input.
Validator operator& (const Validator &other) const
Validator operator| (const Validator &other) const
Validator operator! () const
Create a validator that fails when a given validator succeeds.
Static Private Member Functions
template<typename Number >
static void validate_mapping (std::map< std::string, Number > &mapping, Options opts)
template<typename Number >
static std::string generate_description (const std::string &name, Options opts)
Generate description like this: NUMBER [UNIT].
Additional Inherited Members
Protected Attributes inherited from CLI::Validator
std::function< std::string()> desc_function_
This is the description function, if empty the description_ will be used.
std::function< std::string(std::string &)> func_
std::string name_ {}
The name for search purposes of the Validator.
int application_index_ = -1
A Validator will only apply to an indexed value (-1 is all elements)
bool active_ {true}
Enable for Validator to allow it to be disabled if need be.
bool non_modifying_ {false}
specify that a validator should not modify the input
Detailed Description
Multiply a number by a factor using given mapping. Can be used to write transforms for SIZE or DURATION inputs.
Example: With mapping = {"b"->1, "kb"->1024, "mb"->1024*1024} one can recognize inputs like "100", "12kb", "100 MB", that will be automatically transformed to 100, 14448, 104857600.
Output number type matches the type in the provided mapping. Therefore, if it is required to interpret real inputs like "0.42 s", the mapping should be of a type <string, float> or <string, double>.
Definition at line 3665 of file CLI11.hpp.
Member Enumeration Documentation
Options
enum CLI::AsNumberWithUnit::Options
Adjust AsNumberWithUnit behavior. CASE_SENSITIVE/CASE_INSENSITIVE controls how units are matched. UNIT_OPTIONAL/UNIT_REQUIRED throws ValidationError if UNIT_REQUIRED is set and unit literal is not found.
Enumerator
CASE_SENSITIVE
CASE_INSENSITIVE
UNIT_OPTIONAL
UNIT_REQUIRED
DEFAULT
Definition at line 3671 of file CLI11.hpp.
                      {
             CASE_SENSITIVE = 0,
             CASE_INSENSITIVE = 1,
             UNIT_OPTIONAL = 0,
             UNIT_REQUIRED = 2,
             DEFAULT = CASE_INSENSITIVE | UNIT_OPTIONAL
         };
Constructor & Destructor Documentation
AsNumberWithUnit()
template<typename Number > CLI::AsNumberWithUnit::AsNumberWithUnit (std::map< std::string, Number > mapping, Options opts = DEFAULT, const std::string & unit_name = "UNIT") inline explicit
Definition at line 3680 of file CLI11.hpp.
{
             description(generate_description<Number>(unit_name, opts));
             validate_mapping(mapping, opts);
             // transform function
             func_ = [mapping, opts](std::string& input) -> std::string {
                 Number num;
                 detail::rtrim(input);
                 if (input.empty()) {
                     throw ValidationError("Input is empty");
                 }
                 // Find split position between number and prefix
                 auto unit_begin = input.end();
                 while (unit_begin > input.begin() && std::isalpha(*(unit_begin - 1), std::locale())) {
                     --unit_begin;
                 }
                 std::string unit{unit_begin, input.end()};
                 input.resize(static_cast<std::size_t>(std::distance(input.begin(), unit_begin)));
                 detail::trim(input);
                 if (opts & UNIT_REQUIRED && unit.empty()) {
                     throw ValidationError("Missing mandatory unit");
                 }
                 if (opts & CASE_INSENSITIVE) {
                     unit = detail::to_lower(unit);
                 }
                 if (unit.empty()) {
                     if (!detail::lexical_cast(input, num)) {
                         throw ValidationError(std::string("Value ") + input + " could not be converted to " + detail::type_name<Number>());
                     }
                     // No need to modify input if no unit passed
                     return {};
                 }
                 // find corresponding factor
                 auto it = mapping.find(unit);
                 if (it == mapping.end()) {
                     throw ValidationError(unit +
                                           " unit not recognized. "
                                           "Allowed values: " +
                                           detail::generate_map(mapping, true));
                 }
                 if (!input.empty()) {
                     bool converted = detail::lexical_cast(input, num);
                     if (!converted) {
                         throw ValidationError(std::string("Value ") + input + " could not be converted to " + detail::type_name<Number>());
                     }
                     // perform safe multiplication
                     bool ok = detail::checked_multiply(num, it->second);
                     if (!ok) {
                         throw ValidationError(detail::to_string(num) + " multiplied by " + unit +
                                               " factor would cause number overflow. Use smaller value.");
                     }
                 } else {
                     num = static_cast<Number>(it->second);
                 }
                 input = detail::to_string(num);
                 return {};
             };
         }
References CLI::detail::checked_multiply(), CLI::detail::generate_map(), CLI::detail::isalpha(), CLI::detail::lexical_cast(), CLI::Number, CLI::detail::rtrim(), CLI::detail::to_lower(), CLI::detail::to_string(), and CLI::detail::trim().
Member Function Documentation
generate_description()
template<typename Number > static std::string CLI::AsNumberWithUnit::generate_description (const std::string & name, Options opts) inline static private
Generate description like this: NUMBER [UNIT].
Definition at line 3777 of file CLI11.hpp.
{
             std::stringstream out;
             out << detail::type_name<Number>() << ' ';
             if (opts & UNIT_REQUIRED) {
                 out << name;
             } else {
                 out << '[' << name << ']';
             }
             return out.str();
         }
validate_mapping()
template<typename Number > static void CLI::AsNumberWithUnit::validate_mapping (std::map< std::string, Number > & mapping, Options opts) inline static private
Check that mapping contains valid units. Update mapping for CASE_INSENSITIVE mode.
Definition at line 3751 of file CLI11.hpp.
{
             for (auto& kv : mapping) {
                 if (kv.first.empty()) {
                     throw ValidationError("Unit must not be empty.");
                 }
                 if (!detail::isalpha(kv.first)) {
                     throw ValidationError("Unit must contain only letters.");
                 }
             }
             // make all units lowercase if CASE_INSENSITIVE
             if (opts & CASE_INSENSITIVE) {
                 std::map<std::string, Number> lower_mapping;
                 for (auto& kv : mapping) {
                     auto s = detail::to_lower(kv.first);
                     if (lower_mapping.count(s)) {
                         throw ValidationError(std::string("Several matching lowercase unit representations are found: ") + s);
                     }
                     lower_mapping[detail::to_lower(kv.first)] = kv.second;
                 }
                 mapping = std::move(lower_mapping);
             }
         }
References CLI::detail::isalpha(), and CLI::detail::to_lower().
The documentation for this class was generated from the following file:
utils/CLI11.hpp