snode.c: net::un::stream::ConfigConnect Class Reference
net::un::stream::ConfigConnect Class Reference
#include <ConfigConnect.h>
Public Member Functions
ConfigConnect (CLI::App *baseSc)
const std::string & getConnectSunPath () const
SocketAddress getConnectAddress () const
Protected Member Functions
void required (bool req) const
Protected Attributes
CLI::App * connectSc = nullptr
CLI::Option * connectSunPathOpt = nullptr
std::string connectSunPath = ""
Detailed Description
Definition at line 37 of file ConfigConnect.h.
Constructor & Destructor Documentation
ConfigConnect()
net::un::stream::ConfigConnect::ConfigConnect (CLI::App * baseSc) explicit
Definition at line 31 of file ConfigConnect.cpp.
{
         connectSc = baseSc->add_subcommand("bind");
         connectSc->description("Bind options");
         connectSc->configurable();
         connectSunPathOpt = connectSc->add_option("-p,--path", connectSunPath, "Unix domain socket");
         connectSunPathOpt->type_name("[filesystem path]");
         connectSunPathOpt->default_val("/tmp/sun.sock");
         connectSunPathOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), connectSc, connectSunPath, connectSunPathOpt, CLI::Option::default_val(), CLI::App::description(), and CLI::Option::type_name().
Member Function Documentation
getConnectAddress()
SocketAddress net::un::stream::ConfigConnect::getConnectAddress () const
Definition at line 46 of file ConfigConnect.cpp.
{
         return SocketAddress(connectSunPath);
     }
References connectSunPath.
getConnectSunPath()
const std::string & net::un::stream::ConfigConnect::getConnectSunPath () const
Definition at line 42 of file ConfigConnect.cpp.
{
         return connectSunPath;
     }
References connectSunPath.
required()
void net::un::stream::ConfigConnect::required (bool req) const protected
Definition at line 50 of file ConfigConnect.cpp.
{
         utils::Config::instance().required(connectSc, req);
         utils::Config::instance().required(connectSunPathOpt, req);
     }
References connectSc, connectSunPathOpt, utils::Config::instance(), and utils::Config::required().
Referenced by net::un::stream::ClientConfig::required().
Member Data Documentation
connectSc
CLI::App* net::un::stream::ConfigConnect::connectSc = nullptr protected
Definition at line 48 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
connectSunPath
std::string net::un::stream::ConfigConnect::connectSunPath = "" protected
Definition at line 51 of file ConfigConnect.h.
Referenced by ConfigConnect(), getConnectAddress(), and getConnectSunPath().
connectSunPathOpt
CLI::Option* net::un::stream::ConfigConnect::connectSunPathOpt = nullptr protected
Definition at line 49 of file ConfigConnect.h.
Referenced by ConfigConnect(), and required().
The documentation for this class was generated from the following files:
net/un/stream/ConfigConnect.h
net/un/stream/ConfigConnect.cpp