snode.c: core::socket::stream::legacy::SocketReader< SocketT > Class Template Reference
core::socket::stream::legacy::SocketReader< SocketT > Class Template Reference
#include <SocketReader.h>
Protected Member Functions
void terminate () override
Protected Member Functions inherited from core::socket::stream::SocketReader< SocketT >
SocketReader (const std::function< void(int)> &onError, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
virtual ~SocketReader ()=default
void setBlockSize (std::size_t readBlockSize)
virtual void doReadShutdown ()
ssize_t readFromPeer (char *junk, std::size_t junkLen)
void doRead ()
bool continueReadImmediately () const override
void shutdown ()
void terminate () override
Protected Member Functions inherited from core::ReadEventReceiver
ReadEventReceiver (const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::EventReceiver
EventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
Private Types
using Super = core::socket::stream::SocketReader< SocketT >
Private Member Functions
ssize_t read (char *junk, std::size_t junkLen) override
bool continueReadImmediately () const override
Additional Inherited Members
Public Types inherited from core::socket::stream::SocketReader< SocketT >
using Socket = SocketT
Public Member Functions inherited from core::EventReceiver
int getRegisteredFd ()
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime)
void triggered (const utils::Timeval &currentTime)
void disabled ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Detailed Description
template<typename SocketT>
class core::socket::stream::legacy::SocketReader< SocketT >
Definition at line 33 of file SocketReader.h.
Member Typedef Documentation
Super
template<typename SocketT > using core::socket::stream::legacy::SocketReader< SocketT >::Super = core::socket::stream::SocketReader<SocketT> private
Definition at line 35 of file SocketReader.h.
Member Function Documentation
continueReadImmediately()
template<typename SocketT > bool core::socket::stream::legacy::SocketReader< SocketT >::continueReadImmediately () const inline override private virtual
Reimplemented from core::ReadEventReceiver.
Definition at line 42 of file SocketReader.h.
{
             return Super::continueReadImmediately();
         }
References core::socket::stream::SocketReader< SocketT >::continueReadImmediately().
read()
template<typename SocketT > ssize_t core::socket::stream::legacy::SocketReader< SocketT >::read (char * junk, std::size_t junkLen) inline override private virtual
Implements core::socket::stream::SocketReader< SocketT >.
Definition at line 38 of file SocketReader.h.
{
             return core::system::recv(this->getFd(), junk, junkLen, 0);
         }
References core::system::recv().
terminate()
template<typename SocketT > void core::socket::stream::legacy::SocketReader< SocketT >::terminate () inline override protected virtual
Reimplemented from core::EventReceiver.
Definition at line 47 of file SocketReader.h.
{
             Super::terminate();
         }
References core::socket::stream::SocketReader< SocketT >::terminate().
The documentation for this class was generated from the following file:
core/socket/stream/legacy/SocketReader.h