snode.c: net::in::stream::ServerSocket Class Reference
net::in::stream::ServerSocket Class Reference
#include <ServerSocket.h>
Public Member Functions
void listen (uint16_t port, int backlog, const std::function< void(const Socket &socket, int)> &onError)
void listen (const std::string &ipOrHostname, int backlog, const std::function< void(const Socket &socket, int)> &onError)
void listen (const std::string &ipOrHostname, uint16_t port, int backlog, const std::function< void(const Socket &socket, int)> &onError)
Public Member Functions inherited from core::socket::ServerSocket< net::in::stream::Socket >
virtual void listen (const typename Socket::SocketAddress &bindAddress, int backlog, const std::function< void(const Socket &socket, int)> &onError) const=0
Additional Inherited Members
Public Types inherited from core::socket::ServerSocket< net::in::stream::Socket >
using Socket = net::in::stream::Socket
Detailed Description
Definition at line 35 of file ServerSocket.h.
Member Function Documentation
listen() [1/3]
void net::in::stream::ServerSocket::listen (const std::string & ipOrHostname, int backlog, const std::function< void(const Socket &socket, int)> & onError)
Definition at line 31 of file ServerSocket.cpp.
{
         listen(SocketAddress(ipOrHostname), backlog, onError);
     }
References listen().
listen() [2/3]
void net::in::stream::ServerSocket::listen (const std::string & ipOrHostname, uint16_t port, int backlog, const std::function< void(const Socket &socket, int)> & onError)
Definition at line 35 of file ServerSocket.cpp.
{
         listen(SocketAddress(ipOrHostname, port), backlog, onError);
     }
References listen().
listen() [3/3]
void net::in::stream::ServerSocket::listen (uint16_t port, int backlog, const std::function< void(const Socket &socket, int)> & onError)
Definition at line 27 of file ServerSocket.cpp.
{
         listen(SocketAddress(port), backlog, onError);
     }
Referenced by listen().
The documentation for this class was generated from the following files:
net/in/stream/ServerSocket.h
net/in/stream/ServerSocket.cpp