snode.c: core::epoll::DescriptorEventPublisher::EPollEvents Class Reference
core::epoll::DescriptorEventPublisher::EPollEvents Class Reference
Public Member Functions
EPollEvents (int &epfd, uint32_t event)
void muxAdd (core::DescriptorEventReceiver *eventReceiver)
void muxDel (int fd)
void muxOn (core::DescriptorEventReceiver *eventReceiver)
void muxOff (core::DescriptorEventReceiver *eventReceiver)
int getEPFd () const
epoll_event * getEvents ()
int getInterestCount () const
Private Member Functions
void muxMod (int fd, uint32_t events, core::DescriptorEventReceiver *eventReceiver)
Private Attributes
int & epfd
uint32_t events
std::vector< epoll_event > ePollEvents
uint32_t interestCount
Detailed Description
Definition at line 44 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
EPollEvents()
core::epoll::DescriptorEventPublisher::EPollEvents::EPollEvents (int & epfd, uint32_t event) explicit
Definition at line 31 of file DescriptorEventPublisher.cpp.
         : epfd(epfd)
         , events(events) {
         epfd = core::system::epoll_create1(EPOLL_CLOEXEC);
         interestCount = 0;
         ePollEvents.resize(1);
     }
References epfd, core::system::epoll_create1(), ePollEvents, and interestCount.
Member Function Documentation
getEPFd()
int core::epoll::DescriptorEventPublisher::EPollEvents::getEPFd () const
Definition at line 83 of file DescriptorEventPublisher.cpp.
{
         return epfd;
     }
Referenced by core::epoll::DescriptorEventPublisher::publishActiveEvents().
getEvents()
epoll_event * core::epoll::DescriptorEventPublisher::EPollEvents::getEvents ()
Definition at line 87 of file DescriptorEventPublisher.cpp.
{
         return ePollEvents.data();
     }
References core::epoll::DescriptorEventPublisher::ePollEvents.
Referenced by core::epoll::DescriptorEventPublisher::publishActiveEvents().
getInterestCount()
int core::epoll::DescriptorEventPublisher::EPollEvents::getInterestCount () const
Definition at line 91 of file DescriptorEventPublisher.cpp.
{
         return static_cast<int>(interestCount);
     }
Referenced by core::epoll::DescriptorEventPublisher::publishActiveEvents().
muxAdd()
void core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd (core::DescriptorEventReceiver * eventReceiver)
Definition at line 39 of file DescriptorEventPublisher.cpp.
{
         epoll_event ePollEvent;
         ePollEvent.data.ptr = eventReceiver;
         ePollEvent.events = events;
         if (core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, eventReceiver->getRegisteredFd(), &ePollEvent) == 0) {
             interestCount++;
             if (interestCount >= ePollEvents.size()) {
                 ePollEvents.resize(ePollEvents.size() * 2);
             }
         } else if (errno == EEXIST) {
             muxMod(eventReceiver->getRegisteredFd(), events, eventReceiver);
         }
     }
References core::system::epoll_ctl(), core::epoll::DescriptorEventPublisher::ePollEvents, and core::DescriptorEventReceiver::getRegisteredFd().
Referenced by core::epoll::DescriptorEventPublisher::muxAdd().
muxDel()
void core::epoll::DescriptorEventPublisher::EPollEvents::muxDel (int fd)
Definition at line 56 of file DescriptorEventPublisher.cpp.
{
         if (core::system::epoll_ctl(epfd, EPOLL_CTL_DEL, fd, nullptr) == 0) {
             interestCount--;
         }
         while (ePollEvents.size() > (interestCount * 2) + 1) {
             ePollEvents.resize(ePollEvents.size() / 2);
         }
     }
References core::system::epoll_ctl(), and core::epoll::DescriptorEventPublisher::ePollEvents.
Referenced by core::epoll::DescriptorEventPublisher::muxDel().
muxMod()
void core::epoll::DescriptorEventPublisher::EPollEvents::muxMod (int fd, uint32_t events, core::DescriptorEventReceiver * eventReceiver) private
Definition at line 66 of file DescriptorEventPublisher.cpp.
{
         epoll_event ePollEvent;
         ePollEvent.data.ptr = eventReceiver;
         ePollEvent.events = events;
         core::system::epoll_ctl(epfd, EPOLL_CTL_MOD, fd, &ePollEvent);
     }
References core::system::epoll_ctl().
muxOff()
void core::epoll::DescriptorEventPublisher::EPollEvents::muxOff (core::DescriptorEventReceiver * eventReceiver)
Definition at line 79 of file DescriptorEventPublisher.cpp.
{
         muxMod(eventReceiver->getRegisteredFd(), 0, eventReceiver);
     }
References core::DescriptorEventReceiver::getRegisteredFd().
Referenced by core::epoll::DescriptorEventPublisher::muxOff().
muxOn()
void core::epoll::DescriptorEventPublisher::EPollEvents::muxOn (core::DescriptorEventReceiver * eventReceiver)
Definition at line 75 of file DescriptorEventPublisher.cpp.
{
         muxMod(eventReceiver->getRegisteredFd(), events, eventReceiver);
     }
References core::DescriptorEventReceiver::getRegisteredFd().
Referenced by core::epoll::DescriptorEventPublisher::muxOn().
Member Data Documentation
epfd
int& core::epoll::DescriptorEventPublisher::EPollEvents::epfd private
Definition at line 63 of file DescriptorEventPublisher.h.
Referenced by EPollEvents().
ePollEvents
std::vector<epoll_event> core::epoll::DescriptorEventPublisher::EPollEvents::ePollEvents private
Definition at line 66 of file DescriptorEventPublisher.h.
Referenced by EPollEvents().
events
uint32_t core::epoll::DescriptorEventPublisher::EPollEvents::events private
Definition at line 64 of file DescriptorEventPublisher.h.
interestCount
uint32_t core::epoll::DescriptorEventPublisher::EPollEvents::interestCount private
Definition at line 67 of file DescriptorEventPublisher.h.
Referenced by EPollEvents().
The documentation for this class was generated from the following files:
core/multiplexer/epoll/DescriptorEventPublisher.h
core/multiplexer/epoll/DescriptorEventPublisher.cpp