snode.c: net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT > Class Template Reference
net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT > Class Template Reference
#include <SocketServer.h>
Public Types
using SocketContextFactory = SocketContextFactoryT
using SocketAcceptor = SocketAcceptorT
using SocketConnection = typename SocketAcceptor::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Member Functions
SocketServer (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketServer ()=default
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(int)> &onError) const
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Private Member Functions
SocketServer ()=delete
Private Attributes
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(const SocketAddress &, const SocketAddress &)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename SocketAcceptorT, typename SocketContextFactoryT>
class net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >
Definition at line 36 of file SocketServer.h.
Member Typedef Documentation
SocketAcceptor
template<typename SocketAcceptorT , typename SocketContextFactoryT > using net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::SocketAcceptor = SocketAcceptorT
Definition at line 41 of file SocketServer.h.
SocketAddress
template<typename SocketAcceptorT , typename SocketContextFactoryT > using net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::SocketAddress = typename SocketConnection::Socket::SocketAddress
Definition at line 43 of file SocketServer.h.
SocketConnection
template<typename SocketAcceptorT , typename SocketContextFactoryT > using net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::SocketConnection = typename SocketAcceptor::SocketConnection
Definition at line 42 of file SocketServer.h.
SocketContextFactory
template<typename SocketAcceptorT , typename SocketContextFactoryT > using net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::SocketContextFactory = SocketContextFactoryT
Definition at line 40 of file SocketServer.h.
Constructor & Destructor Documentation
SocketServer() [1/2]
template<typename SocketAcceptorT , typename SocketContextFactoryT > net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::SocketServer () private delete
SocketServer() [2/2]
template<typename SocketAcceptorT , typename SocketContextFactoryT > net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::SocketServer (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 45 of file SocketServer.h.
                                                                 {{}})
             : socketContextFactory(std::make_shared<SocketContextFactory>())
             , _onConnect(onConnect)
             , _onConnected(onConnected)
             , _onDisconnect(onDisconnect)
             , options(options) {
         }
~SocketServer()
template<typename SocketAcceptorT , typename SocketContextFactoryT > virtual net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::~SocketServer () virtual default
Member Function Documentation
getSocketContextFactory()
template<typename SocketAcceptorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::getSocketContextFactory () inline
Definition at line 76 of file SocketServer.h.
{
             return socketContextFactory;
         }
References net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::socketContextFactory.
listen()
template<typename SocketAcceptorT , typename SocketContextFactoryT > void net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::listen (const SocketAddress & bindAddress, int backlog, const std::function< void(int)> & onError) const inline
Definition at line 58 of file SocketServer.h.
{
             SocketAcceptor* socketListener = new SocketAcceptor(socketContextFactory, _onConnect, _onConnected, _onDisconnect, options);
             socketListener->listen(bindAddress, backlog, onError);
         }
References net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onConnect, net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onConnected, net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onDisconnect, net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::options, and net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::socketContextFactory.
onConnect()
template<typename SocketAcceptorT , typename SocketContextFactoryT > void net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect) inline
Definition at line 64 of file SocketServer.h.
{
             _onConnect = onConnect;
         }
References net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onConnect.
onConnected()
template<typename SocketAcceptorT , typename SocketContextFactoryT > void net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::onConnected (const std::function< void(SocketConnection *)> & onConnected) inline
Definition at line 68 of file SocketServer.h.
{
             _onConnected = onConnected;
         }
References net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onConnected.
onDisconnect()
template<typename SocketAcceptorT , typename SocketContextFactoryT > void net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::onDisconnect (const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 72 of file SocketServer.h.
{
             _onDisconnect = onDisconnect;
         }
References net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onDisconnect.
Member Data Documentation
_onConnect
template<typename SocketAcceptorT , typename SocketContextFactoryT > std::function<void(const SocketAddress&, const SocketAddress&)> net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onConnect private
Definition at line 83 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::listen(), and net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::onConnect().
_onConnected
template<typename SocketAcceptorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onConnected private
Definition at line 84 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::listen(), and net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::onConnected().
_onDisconnect
template<typename SocketAcceptorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::_onDisconnect private
Definition at line 85 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::listen(), and net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::onDisconnect().
options
template<typename SocketAcceptorT , typename SocketContextFactoryT > std::map<std::string, std::any> net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::options private
Definition at line 87 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::listen().
socketContextFactory
template<typename SocketAcceptorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::socketContextFactory private
Definition at line 81 of file SocketServer.h.
Referenced by net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::getSocketContextFactory(), and net::socket::stream::SocketServer< SocketAcceptorT, SocketContextFactoryT >::listen().
The documentation for this class was generated from the following file:
net/socket/stream/SocketServer.h