snode.c: net::un::stream::ServerConfig Class Reference
net::un::stream::ServerConfig Class Reference
#include <ServerConfig.h>
Public Member Functions
ServerConfig (const std::string &name)
const std::string & getSunPath () const
int parse (bool required=false)
Public Member Functions inherited from net::ServerConfig
ServerConfig (const std::string &name)
int getBacklog () const
Public Member Functions inherited from net::Config
Config (const std::string &name)
const std::string & getName () const
int getReadTimeout () const
int getWriteTimeout () const
Private Attributes
CLI::App * serverBindSc = nullptr
CLI::Option * bindServerSunPathOpt = nullptr
std::string sunPath
Additional Inherited Members
Public Attributes inherited from net::Config
CLI::App * serverSc = nullptr
Protected Member Functions inherited from net::Config
void finish ()
Detailed Description
Definition at line 37 of file ServerConfig.h.
Constructor & Destructor Documentation
ServerConfig()
net::un::stream::ServerConfig::ServerConfig (const std::string & name) explicit
Definition at line 29 of file ServerConfig.cpp.
         : net::ServerConfig(name) {
         serverBindSc = serverSc->add_subcommand("bind");
         serverBindSc->description("Server socket bind options");
         serverBindSc->configurable();
         bindServerSunPathOpt = serverBindSc->add_option("-a,--path", sunPath, "Unix domain socket path");
         bindServerSunPathOpt->type_name("[filesystem path]");
         bindServerSunPathOpt->default_val("/tmp/" + name + ".sock");
         bindServerSunPathOpt->configurable();
         finish();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindServerSunPathOpt, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), net::Config::finish(), net::Config::name, serverBindSc, net::Config::serverSc, sunPath, and CLI::Option::type_name().
Member Function Documentation
getSunPath()
const std::string & net::un::stream::ServerConfig::getSunPath () const
Definition at line 43 of file ServerConfig.cpp.
{
         return sunPath;
     }
References sunPath.
parse()
int net::un::stream::ServerConfig::parse (bool required = false)
Member Data Documentation
bindServerSunPathOpt
CLI::Option* net::un::stream::ServerConfig::bindServerSunPathOpt = nullptr private
Definition at line 47 of file ServerConfig.h.
Referenced by ServerConfig().
serverBindSc
CLI::App* net::un::stream::ServerConfig::serverBindSc = nullptr private
Definition at line 46 of file ServerConfig.h.
Referenced by ServerConfig().
sunPath
std::string net::un::stream::ServerConfig::sunPath private
Definition at line 49 of file ServerConfig.h.
Referenced by getSunPath(), and ServerConfig().
The documentation for this class was generated from the following files:
net/un/stream/ServerConfig.h
net/un/stream/ServerConfig.cpp