snode.c: core::epoll::DescriptorEventDispatcher::EPollEvents Class Reference
core::epoll::DescriptorEventDispatcher::EPollEvents Class Reference
Public Member Functions
EPollEvents (int &epfd, uint32_t event)
void modAdd (core::DescriptorEventReceiver *eventReceiver)
void modDel (core::DescriptorEventReceiver *eventReceiver)
void modOn (core::DescriptorEventReceiver *eventReceiver)
void modOff (core::DescriptorEventReceiver *eventReceiver)
void compress ()
int getEPFd () const
epoll_event * getEvents ()
int getInterestCount () const
Private Member Functions
void mod (core::DescriptorEventReceiver *eventReceiver, uint32_t events)
Private Attributes
int & epfd
uint32_t events
std::vector< epoll_event > ePollEvents
uint32_t interestCount
Detailed Description
Definition at line 44 of file DescriptorEventDispatcher.h.
Constructor & Destructor Documentation
EPollEvents()
core::epoll::DescriptorEventDispatcher::EPollEvents::EPollEvents (int & epfd, uint32_t event) explicit
Definition at line 31 of file DescriptorEventDispatcher.cpp.
         : epfd(epfd)
         , events(events) {
         epfd = core::system::epoll_create1(EPOLL_CLOEXEC);
         interestCount = 0;
         ePollEvents.resize(1);
     }
References epfd, core::system::epoll_create1(), ePollEvents, and interestCount.
Member Function Documentation
compress()
void core::epoll::DescriptorEventDispatcher::EPollEvents::compress ()
Definition at line 79 of file DescriptorEventDispatcher.cpp.
{
         while (ePollEvents.size() > (interestCount * 2) + 1) {
             ePollEvents.resize(ePollEvents.size() / 2);
         }
     }
References core::epoll::DescriptorEventDispatcher::ePollEvents.
getEPFd()
int core::epoll::DescriptorEventDispatcher::EPollEvents::getEPFd () const
Definition at line 85 of file DescriptorEventDispatcher.cpp.
{
         return epfd;
     }
Referenced by core::epoll::DescriptorEventDispatcher::dispatchActiveEvents().
getEvents()
epoll_event * core::epoll::DescriptorEventDispatcher::EPollEvents::getEvents ()
Definition at line 89 of file DescriptorEventDispatcher.cpp.
{
         return ePollEvents.data();
     }
References core::epoll::DescriptorEventDispatcher::ePollEvents.
Referenced by core::epoll::DescriptorEventDispatcher::dispatchActiveEvents().
getInterestCount()
int core::epoll::DescriptorEventDispatcher::EPollEvents::getInterestCount () const
Definition at line 93 of file DescriptorEventDispatcher.cpp.
{
         return static_cast<int>(interestCount);
     }
Referenced by core::epoll::DescriptorEventDispatcher::dispatchActiveEvents().
mod()
void core::epoll::DescriptorEventDispatcher::EPollEvents::mod (core::DescriptorEventReceiver * eventReceiver, uint32_t events) private
Definition at line 62 of file DescriptorEventDispatcher.cpp.
{
         epoll_event ePollEvent;
         ePollEvent.data.ptr = eventReceiver;
         ePollEvent.events = events;
         core::system::epoll_ctl(epfd, EPOLL_CTL_MOD, eventReceiver->getRegisteredFd(), &ePollEvent);
     }
References core::system::epoll_ctl(), and core::DescriptorEventReceiver::getRegisteredFd().
modAdd()
void core::epoll::DescriptorEventDispatcher::EPollEvents::modAdd (core::DescriptorEventReceiver * eventReceiver)
Definition at line 39 of file DescriptorEventDispatcher.cpp.
{
         epoll_event ePollEvent;
         ePollEvent.data.ptr = eventReceiver;
         ePollEvent.events = events;
         if (core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, eventReceiver->getRegisteredFd(), &ePollEvent) == 0) {
             interestCount++;
             if (interestCount >= ePollEvents.size()) {
                 ePollEvents.resize(ePollEvents.size() * 2);
             }
         } else if (errno == EEXIST) {
             mod(eventReceiver, events);
         }
     }
References core::system::epoll_ctl(), core::epoll::DescriptorEventDispatcher::ePollEvents, and core::DescriptorEventReceiver::getRegisteredFd().
Referenced by core::epoll::DescriptorEventDispatcher::modAdd().
modDel()
void core::epoll::DescriptorEventDispatcher::EPollEvents::modDel (core::DescriptorEventReceiver * eventReceiver)
Definition at line 56 of file DescriptorEventDispatcher.cpp.
{
         if (core::system::epoll_ctl(epfd, EPOLL_CTL_DEL, eventReceiver->getRegisteredFd(), nullptr) == 0) {
             interestCount--;
         }
     }
References core::system::epoll_ctl(), and core::DescriptorEventReceiver::getRegisteredFd().
Referenced by core::epoll::DescriptorEventDispatcher::modDel().
modOff()
void core::epoll::DescriptorEventDispatcher::EPollEvents::modOff (core::DescriptorEventReceiver * eventReceiver)
Definition at line 75 of file DescriptorEventDispatcher.cpp.
{
         mod(eventReceiver, 0);
     }
Referenced by core::epoll::DescriptorEventDispatcher::modOff().
modOn()
void core::epoll::DescriptorEventDispatcher::EPollEvents::modOn (core::DescriptorEventReceiver * eventReceiver)
Definition at line 71 of file DescriptorEventDispatcher.cpp.
{
         mod(eventReceiver, events);
     }
Referenced by core::epoll::DescriptorEventDispatcher::modOn().
Member Data Documentation
epfd
int& core::epoll::DescriptorEventDispatcher::EPollEvents::epfd private
Definition at line 65 of file DescriptorEventDispatcher.h.
Referenced by EPollEvents().
ePollEvents
std::vector<epoll_event> core::epoll::DescriptorEventDispatcher::EPollEvents::ePollEvents private
Definition at line 68 of file DescriptorEventDispatcher.h.
Referenced by EPollEvents().
events
uint32_t core::epoll::DescriptorEventDispatcher::EPollEvents::events private
Definition at line 66 of file DescriptorEventDispatcher.h.
interestCount
uint32_t core::epoll::DescriptorEventDispatcher::EPollEvents::interestCount private
Definition at line 69 of file DescriptorEventDispatcher.h.
Referenced by EPollEvents().
The documentation for this class was generated from the following files:
core/mux/epoll/DescriptorEventDispatcher.h
core/mux/epoll/DescriptorEventDispatcher.cpp