snode.c: core::poll::DescriptorEventPublisher Class Reference
core::poll::DescriptorEventPublisher Class Reference
#include <DescriptorEventPublisher.h>
Public Member Functions
DescriptorEventPublisher (const std::string &name, core::poll::PollFdsManager &pollFds, short events, short revents)
Public Member Functions inherited from core::DescriptorEventPublisher
virtual ~DescriptorEventPublisher ()=default
void publish (Event *event)
void enable (DescriptorEventReceiver *descriptorEventReceiver)
void disable (DescriptorEventReceiver *descriptorEventReceiver)
void suspend (DescriptorEventReceiver *descriptorEventReceiver)
void resume (DescriptorEventReceiver *descriptorEventReceiver)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void unobserveDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int getMaxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void stop ()
const std::string & getName () const
Private Member Functions
DescriptorEventPublisher (const DescriptorEventPublisher &)=delete
DescriptorEventPublisher & operator= (const DescriptorEventPublisher &)=delete
void muxAdd (core::DescriptorEventReceiver *eventReceiver) override
void muxDel (int fd) override
void muxOn (core::DescriptorEventReceiver *eventReceiver) override
void muxOff (core::DescriptorEventReceiver *eventReceiver) override
int publishActiveEvents () override
Private Attributes
core::poll::PollFdsManager & pollFds
short events
short revents
Additional Inherited Members
Protected Member Functions inherited from core::DescriptorEventPublisher
DescriptorEventPublisher ()=delete
DescriptorEventPublisher (const std::string &name)
Protected Attributes inherited from core::DescriptorEventPublisher
std::map< int, std::list< DescriptorEventReceiver * > > observedEventReceivers
unsigned long eventCounter = 0
bool observedEventReceiversDirty = false
std::string name
Detailed Description
Definition at line 40 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
DescriptorEventPublisher() [1/2]
core::poll::DescriptorEventPublisher::DescriptorEventPublisher (const DescriptorEventPublisher &) private delete
DescriptorEventPublisher() [2/2]
core::poll::DescriptorEventPublisher::DescriptorEventPublisher (const std::string & name, core::poll::PollFdsManager & pollFds, short events, short revents)
Definition at line 33 of file DescriptorEventPublisher.cpp.
         : core::DescriptorEventPublisher(name)
         , pollFds(pollFds)
         , events(events)
         , revents(revents) {
     }
Member Function Documentation
muxAdd()
void core::poll::DescriptorEventPublisher::muxAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 40 of file DescriptorEventPublisher.cpp.
{
         pollFds.muxAdd(eventReceiver, events);
     }
References events, core::poll::PollFdsManager::muxAdd(), and pollFds.
muxDel()
void core::poll::DescriptorEventPublisher::muxDel (int fd) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 44 of file DescriptorEventPublisher.cpp.
{
         pollFds.muxDel(fd, events);
     }
References events, core::poll::PollFdsManager::muxDel(), and pollFds.
muxOff()
void core::poll::DescriptorEventPublisher::muxOff (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 52 of file DescriptorEventPublisher.cpp.
{
         pollFds.muxOff(eventReceiver, events);
     }
References events, core::poll::PollFdsManager::muxOff(), and pollFds.
muxOn()
void core::poll::DescriptorEventPublisher::muxOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 48 of file DescriptorEventPublisher.cpp.
{
         pollFds.muxOn(eventReceiver, events);
     }
References events, core::poll::PollFdsManager::muxOn(), and pollFds.
operator=()
DescriptorEventPublisher& core::poll::DescriptorEventPublisher::operator= (const DescriptorEventPublisher &) private delete
publishActiveEvents()
int core::poll::DescriptorEventPublisher::publishActiveEvents () override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 56 of file DescriptorEventPublisher.cpp.
{
         int count = 0;
         pollfd* pollfds = pollFds.getEvents();
         const std::unordered_map<int, PollFdsManager::PollFdIndex>& pollFdsIndices = pollFds.getPollFdIndices();
         for (auto& [fd, eventReceivers] : observedEventReceivers) { // cppcheck-suppress unassignedVariable
             pollfd& pollFd = pollfds[pollFdsIndices.find(fd)->second.index];
             if ((pollFd.events & events) != 0 && (pollFd.revents & revents) != 0) {
                 core::DescriptorEventReceiver* eventReceiver = eventReceivers.front();
                 eventCounter++;
                 eventReceiver->publish();
                 count++;
             }
         }
         return count;
     }
References core::DescriptorEventPublisher::eventCounter, events, core::poll::PollFdsManager::getEvents(), core::poll::PollFdsManager::getPollFdIndices(), core::DescriptorEventPublisher::observedEventReceivers, pollFds, core::EventReceiver::publish(), and revents.
Member Data Documentation
events
short core::poll::DescriptorEventPublisher::events private
Definition at line 56 of file DescriptorEventPublisher.h.
Referenced by muxAdd(), muxDel(), muxOff(), muxOn(), and publishActiveEvents().
pollFds
core::poll::PollFdsManager& core::poll::DescriptorEventPublisher::pollFds private
Definition at line 55 of file DescriptorEventPublisher.h.
Referenced by muxAdd(), muxDel(), muxOff(), muxOn(), and publishActiveEvents().
revents
short core::poll::DescriptorEventPublisher::revents private
Definition at line 57 of file DescriptorEventPublisher.h.
Referenced by publishActiveEvents().
The documentation for this class was generated from the following files:
core/multiplexer/poll/DescriptorEventPublisher.h
core/multiplexer/poll/DescriptorEventPublisher.cpp