snode.c: web::websocket::client::SocketContextUpgrade Class Reference
web::websocket::client::SocketContextUpgrade Class Reference
#include <SocketContextUpgrade.h>
Public Member Functions
SocketContextUpgrade (core::socket::SocketConnection *socketConnection, web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response > *socketContextUpgradeFactory, web::websocket::client::SubProtocol *subProtocol)
Public Member Functions inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
void sendPing (const char *reason=nullptr, std::size_t reasonLength=0)
void sendPong (const char *reason=nullptr, std::size_t reasonLength=0)
void sendClose (uint16_t statusCode=1000, const char *reason=nullptr, std::size_t reasonLength=0)
Public Member Functions inherited from core::socket::SocketContext
Role getRole () const
void setTimeout (const utils::Timeval &timeout)
std::string getLocalAddressAsString () const
std::string getRemoteAddressAsString () const
void sendToPeer (const char *junk, std::size_t junkLen)
void sendToPeer (const std::string &data)
ssize_t readFromPeer (char *junk, std::size_t junklen)
void shutdownRead ()
void shutdownWrite ()
void shutdown ()
void close ()
SocketContext * switchSocketContext (core::socket::SocketContextFactory *socketContextFactory)
Static Public Member Functions
static SocketContextUpgrade * create (web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response > *socketContextUpgradeFactory, core::socket::SocketConnection *socketConnection, const std::string &subProtocolName)
Protected Member Functions
~SocketContextUpgrade () override
Protected Member Functions inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >
SocketContextUpgrade (core::socket::SocketConnection *socketConnection, web::http::SocketContextUpgradeFactory< Request, Response > *socketContextUpgradeFactory, SubProtocol *subProtocol, core::socket::SocketContext::Role role)
SocketContextUpgrade ()=delete
SocketContextUpgrade (const SocketContextUpgrade &)=delete
SocketContextUpgrade & operator= (const SocketContextUpgrade &)=delete
Protected Member Functions inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
SocketContextUpgrade (core::socket::SocketConnection *socketConnection, core::socket::SocketContext::Role role, SocketContextUpgradeFactory *socketContextUpgradeFactory)
Protected Member Functions inherited from core::socket::SocketContext
SocketContext (core::socket::SocketConnection *socketConnection, Role role)
virtual ~SocketContext ()=default
Protected Member Functions inherited from web::websocket::Receiver
Receiver ()=default
Receiver (const Receiver &)=delete
Receiver & operator= (const Receiver &)=delete
void receive ()
Protected Member Functions inherited from web::websocket::Transmitter
Transmitter (bool masking)
void sendMessage (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageStart (uint8_t opCode, const char *message, std::size_t messageLength)
void sendMessageFrame (const char *message, std::size_t messageLength)
void sendMessageEnd (const char *message, std::size_t messageLength)
Transmitter ()=default
Transmitter (const Transmitter &)=delete
Transmitter & operator= (const Transmitter &)=delete
Additional Inherited Members
Public Types inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >
using SubProtocol = SubProtocol
using Request = web::http::client::Request
using Response = web::http::client::Response
Public Types inherited from core::socket::SocketContext
enum class Role { SERVER , CLIENT }
Protected Types inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
using Request = RequestT
using Response = ResponseT
using SocketContextUpgradeFactory = web::http::SocketContextUpgradeFactory< Request, Response >
Protected Attributes inherited from web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >
SubProtocol * subProtocol
Protected Attributes inherited from web::http::SocketContextUpgrade< RequestT, ResponseT >
SocketContextUpgradeFactory * socketContextUpgradeFactory = nullptr
Detailed Description
Definition at line 45 of file SocketContextUpgrade.h.
Constructor & Destructor Documentation
SocketContextUpgrade()
web::websocket::client::SocketContextUpgrade::SocketContextUpgrade (core::socket::SocketConnection * socketConnection, web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response > * socketContextUpgradeFactory, web::websocket::client::SubProtocol * subProtocol)
Definition at line 31 of file SocketContextUpgrade.cpp.
         : web::websocket::SocketContextUpgrade<SubProtocol, web::http::client::Request, web::http::client::Response>(
               socketConnection, socketContextUpgradeFactory, subProtocol, core::socket::SocketContext::Role::CLIENT) {
         subProtocol->setSocketContextUpgrade(this);
     }
References web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >::subProtocol.
~SocketContextUpgrade()
web::websocket::client::SocketContextUpgrade::~SocketContextUpgrade () override protected virtual
Reimplemented from web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >.
Definition at line 64 of file SocketContextUpgrade.cpp.
{
         web::websocket::SubProtocolFactory<SubProtocol>* subProtocolFactory =
             SubProtocolFactorySelector::instance()->select(subProtocol->getName());
         if (subProtocolFactory != nullptr && subProtocolFactory->deleteSubProtocol(subProtocol) == 0) {
             SubProtocolFactorySelector::instance()->unload(subProtocolFactory);
         }
     }
References web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::websocket::client::SubProtocolFactorySelector::instance(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select(), web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >::subProtocol, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
Member Function Documentation
create()
SocketContextUpgrade * web::websocket::client::SocketContextUpgrade::create (web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response > * socketContextUpgradeFactory, core::socket::SocketConnection * socketConnection, const std::string & subProtocolName) static
Definition at line 40 of file SocketContextUpgrade.cpp.
{
         SocketContextUpgrade* socketContextUpgrade = nullptr;
         web::websocket::SubProtocolFactory<SubProtocol>* subProtocolFactory =
             SubProtocolFactorySelector::instance()->select(subProtocolName, SubProtocolFactorySelector::Role::CLIENT);
         if (subProtocolFactory != nullptr) {
             SubProtocol* subProtocol = subProtocolFactory->createSubProtocol();
             if (subProtocol != nullptr) {
                 socketContextUpgrade = new SocketContextUpgrade(socketConnection, socketContextUpgradeFactory, subProtocol);
                 if (socketContextUpgrade == nullptr && subProtocolFactory->deleteSubProtocol(subProtocol) == 0) {
                     SubProtocolFactorySelector::instance()->unload(subProtocolFactory);
                 }
             }
         }
         return socketContextUpgrade;
     }
References web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::CLIENT, web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol(), web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol(), web::websocket::client::SubProtocolFactorySelector::instance(), web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::select(), core::socket::SocketContext::socketConnection, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >::SocketContextUpgrade(), web::http::SocketContextUpgrade< RequestT, ResponseT >::socketContextUpgradeFactory, web::websocket::SocketContextUpgrade< SubProtocol, web::http::client::Request, web::http::client::Response >::subProtocol, and web::websocket::SubProtocolFactorySelector< SubProtocolFactoryT >::unload().
Referenced by web::websocket::client::SocketContextUpgradeFactory::create().
The documentation for this class was generated from the following files:
web/websocket/client/SocketContextUpgrade.h
web/websocket/client/SocketContextUpgrade.cpp