snode.c: web::http::client::tls::ClientRfComm< Request, Response > Class Template Reference
web::http::client::tls::ClientRfComm< Request, Response > Class Template Reference
#include <Client.h>
Public Member Functions
void connect (const std::string &address, uint8_t channel, const std::function< void(int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &bindAddress, const std::function< void(int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &bindAddress, uint8_t bindChannel, const std::function< void(int)> &onError)
Public Member Functions inherited from web::http::client::Client< net::socket::bluetooth::rfcomm::tls::SocketClient, web::http::client::Request, web::http::client::Response >
Client (const std::function< void(const Client::SocketAddress &, const Client::SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &)> &onRequestBegin, const std::function< void(Request &, Response &)> &onResponseReady, const std::function< void(int, const std::string &)> &onResponseError, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void connect (const SocketAddress &socketAddress, const std::function< void(int)> &onError)
void connect (const SocketAddress &socketAddress, const SocketAddress &bindAddress, const std::function< void(int)> &onError)
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
Additional Inherited Members
Public Types inherited from web::http::client::Client< net::socket::bluetooth::rfcomm::tls::SocketClient, web::http::client::Request, web::http::client::Response >
using Request = web::http::client::Request
using Response = web::http::client::Response
using SocketClient = net::socket::bluetooth::rfcomm::tls::SocketClient< SocketContextFactory< Request, Response > >
using SocketConnection = typename SocketClient::SocketConnection
using SocketAddress = typename SocketConnection::SocketAddress
Protected Attributes inherited from web::http::client::Client< net::socket::bluetooth::rfcomm::tls::SocketClient, web::http::client::Request, web::http::client::Response >
SocketClient socketClient
Detailed Description
template<typename Request = web::http::client::Request, typename Response = web::http::client::Response>
class web::http::client::tls::ClientRfComm< Request, Response >
Definition at line 92 of file Client.h.
Member Function Documentation
connect() [1/3]
template<typename Request = web::http::client::Request, typename Response = web::http::client::Response> void web::http::client::tls::ClientRfComm< Request, Response >::connect (const std::string & address, uint8_t channel, const std::function< void(int)> & onError) inline
Definition at line 100 of file Client.h.
{
             socketClient.connect(address, channel, onError);
         }
References net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect(), and web::http::client::Client< net::socket::bluetooth::rfcomm::tls::SocketClient, web::http::client::Request, web::http::client::Response >::socketClient.
connect() [2/3]
template<typename Request = web::http::client::Request, typename Response = web::http::client::Response> void web::http::client::tls::ClientRfComm< Request, Response >::connect (const std::string & address, uint8_t channel, const std::string & bindAddress, const std::function< void(int)> & onError) inline
Definition at line 104 of file Client.h.
{
             socketClient.connect(address, channel, bindAddress, onError);
         }
References net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect(), and web::http::client::Client< net::socket::bluetooth::rfcomm::tls::SocketClient, web::http::client::Request, web::http::client::Response >::socketClient.
connect() [3/3]
template<typename Request = web::http::client::Request, typename Response = web::http::client::Response> void web::http::client::tls::ClientRfComm< Request, Response >::connect (const std::string & address, uint8_t channel, const std::string & bindAddress, uint8_t bindChannel, const std::function< void(int)> & onError) inline
Definition at line 108 of file Client.h.
{
             socketClient.connect(address, channel, bindAddress, bindChannel, onError);
         }
References net::socket::bluetooth::rfcomm::SocketClient< ConcreteSocketClient, SocketContextFactoryT >::connect(), and web::http::client::Client< net::socket::bluetooth::rfcomm::tls::SocketClient, web::http::client::Request, web::http::client::Response >::socketClient.
The documentation for this class was generated from the following file:
web/http/client/tls/Client.h