snode.c: core::Descriptor Class Reference
core::Descriptor Class Reference
#include <Descriptor.h>
Public Types
enum class FLAGS : unsigned short { none = 0 , dontClose = 0x01 << 0 }
Public Attributes
enum core::Descriptor::FLAGS none
Protected Member Functions
Descriptor (int fd=-1, enum Descriptor::FLAGS flags=FLAGS::none)
~Descriptor ()
int getFd () const
void dontClose (bool dontClose)
bool dontClose () const
Protected Attributes
int fd = -1
Private Member Functions
Descriptor (const Descriptor &d)=delete
Descriptor & operator= (const Descriptor &descriptor)=delete
void close ()
Friends
enum FLAGS operator| (const enum FLAGS &f1, const enum FLAGS &f2)
enum FLAGS operator& (const enum FLAGS &f1, const enum FLAGS &f2)
Detailed Description
Definition at line 28 of file Descriptor.h.
Member Enumeration Documentation
FLAGS
enum core::Descriptor::FLAGS : unsigned short strong
Enumerator
none
dontClose
Definition at line 33 of file Descriptor.h.
                           : unsigned short {
             none = 0,
             dontClose = 0x01 << 0 // do not close sys-descriptor in case of desctruction
         } flags{FLAGS::none};
Constructor & Destructor Documentation
Descriptor() [1/2]
core::Descriptor::Descriptor (const Descriptor & d) private delete
Descriptor() [2/2]
core::Descriptor::Descriptor (int fd = -1, enum Descriptor::FLAGS flags = FLAGS::none) protected
Definition at line 29 of file Descriptor.cpp.
         : flags(flags)
         , fd(fd) {
     }
~Descriptor()
core::Descriptor::~Descriptor () protected
Definition at line 34 of file Descriptor.cpp.
{
         close();
     }
References close().
Member Function Documentation
close()
void core::Descriptor::close () private
Definition at line 50 of file Descriptor.cpp.
{
         if (fd >= 0 && !dontClose()) {
             core::system::close(fd);
             fd = -1;
         }
     }
References core::system::close(), dontClose(), and fd.
Referenced by ~Descriptor().
dontClose() [1/2]
bool core::Descriptor::dontClose () const protected
Definition at line 46 of file Descriptor.cpp.
{
         return (flags & FLAGS::dontClose) == FLAGS::dontClose;
     }
References dontClose.
Referenced by close(), core::socket::stream::SocketConnector< ClientConfigT, SocketConnectionT >::connectEvent(), and dontClose().
dontClose() [2/2]
void core::Descriptor::dontClose (bool dontClose) protected
Definition at line 42 of file Descriptor.cpp.
{
         this->flags = dontClose ? FLAGS::dontClose : FLAGS::none;
     }
References dontClose(), and none.
getFd()
int core::Descriptor::getFd () const protected
Definition at line 38 of file Descriptor.cpp.
{
         return fd;
     }
References fd.
Referenced by core::socket::Socket< SocketAddressT >::bind(), core::file::FileReader::readEvent(), core::socket::Socket< SocketAddressT >::shutdown(), core::socket::stream::tls::SocketConnection< SocketT >::startSSL(), and core::pipe::PipeSource::writeEvent().
operator=()
Descriptor& core::Descriptor::operator= (const Descriptor & descriptor) private delete
Friends And Related Function Documentation
operator&
enum FLAGS operator& (const enum FLAGS & f1, const enum FLAGS & f2) friend
Definition at line 50 of file Descriptor.cpp.
{
         return static_cast<enum Descriptor::FLAGS>(static_cast<unsigned short>(f1) & static_cast<unsigned short>(f2));
     }
operator|
enum FLAGS operator| (const enum FLAGS & f1, const enum FLAGS & f2) friend
Definition at line 50 of file Descriptor.cpp.
{
         return static_cast<enum Descriptor::FLAGS>(static_cast<unsigned short>(f1) | static_cast<unsigned short>(f2));
     }
Member Data Documentation
fd
int core::Descriptor::fd = -1 protected
Definition at line 50 of file Descriptor.h.
Referenced by core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::acceptEvent(), close(), core::socket::stream::SocketConnector< ClientConfigT, SocketConnectionT >::connect(), core::file::FileReader::connect(), core::socket::stream::SocketConnector< ClientConfigT, SocketConnectionT >::connectEvent(), core::file::FileReader::FileReader(), getFd(), core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::listen(), core::socket::Socket< SocketAddressT >::open(), core::pipe::PipeSink::PipeSink(), core::pipe::PipeSource::PipeSource(), core::pipe::PipeSink::readEvent(), core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::reuseAddress(), core::socket::stream::SocketReader< SocketT >::SocketReader(), and core::socket::stream::SocketWriter< SocketT >::SocketWriter().
none
enum core::Descriptor::FLAGS core::Descriptor::none
The documentation for this class was generated from the following files:
core/Descriptor.h
core/Descriptor.cpp