snode.c: core::poll::PollFdsManager Class Reference
core::poll::PollFdsManager Class Reference
#include <EventMultiplexer.h>
Classes
struct PollFdIndex
Public Types
using pollfds_size_type = std::vector< pollfd >::size_type
Public Member Functions
PollFdsManager ()
void muxAdd (core::DescriptorEventReceiver *eventReceiver, short event)
void muxDel (int fd, short event)
void muxOn (core::DescriptorEventReceiver *eventReceiver, short event)
void muxOff (core::DescriptorEventReceiver *eventReceiver, short event)
pollfd * getEvents ()
const std::unordered_map< int, PollFdIndex > & getPollFdIndices () const
nfds_t getCurrentSize () const
Private Member Functions
void compress ()
Private Attributes
nfds_t nextIndex = 0
std::vector< pollfd > pollfds
std::unordered_map< int, PollFdIndex > pollFdIndices
Detailed Description
Definition at line 43 of file EventMultiplexer.h.
Member Typedef Documentation
pollfds_size_type
using core::poll::PollFdsManager::pollfds_size_type = std::vector<pollfd>::size_type
Definition at line 52 of file EventMultiplexer.h.
Constructor & Destructor Documentation
PollFdsManager()
core::poll::PollFdsManager::PollFdsManager () explicit
Definition at line 43 of file EventMultiplexer.cpp.
{
         pollfds.resize(1, {-1, 0, 0});
         pollFdIndices.reserve(1);
     }
References pollFdIndices, and pollfds.
Member Function Documentation
compress()
void core::poll::PollFdsManager::compress () private
Definition at line 101 of file EventMultiplexer.cpp.
{
         // cppcheck-suppress ignoredReturnValue
         // cppcheck-suppress uselessCallsRemove
         std::remove_if(pollfds.begin(), pollfds.end(), [](const pollfd& pollFd) -> bool {
             return pollFd.fd < 0;
         });
         pollfds.resize(pollFdIndices.size() + 1, {-1, 0, 0});
         pollFdIndices.reserve(pollFdIndices.size() + 1);
         for (uint32_t i = 0; i < pollFdIndices.size(); i++) {
             pollFdIndices[pollfds[i].fd].index = i;
         }
         nextIndex = pollFdIndices.size();
     }
References nextIndex, pollFdIndices, and pollfds.
Referenced by muxDel().
getCurrentSize()
nfds_t core::poll::PollFdsManager::getCurrentSize () const
Definition at line 127 of file EventMultiplexer.cpp.
{
         return nextIndex;
     }
References nextIndex.
Referenced by core::poll::EventMultiplexer::multiplex().
getEvents()
pollfd * core::poll::PollFdsManager::getEvents ()
Definition at line 119 of file EventMultiplexer.cpp.
{
         return pollfds.data();
     }
References pollfds.
Referenced by core::poll::EventMultiplexer::multiplex(), and core::poll::DescriptorEventPublisher::publishActiveEvents().
getPollFdIndices()
const std::unordered_map< int, PollFdsManager::PollFdIndex > & core::poll::PollFdsManager::getPollFdIndices () const
Definition at line 123 of file EventMultiplexer.cpp.
{
         return pollFdIndices;
     }
References pollFdIndices.
Referenced by core::poll::DescriptorEventPublisher::publishActiveEvents().
muxAdd()
void core::poll::PollFdsManager::muxAdd (core::DescriptorEventReceiver * eventReceiver, short event)
Definition at line 48 of file EventMultiplexer.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         if (!pollFdIndices.contains(fd)) {
             pollfds[nextIndex].events = event;
             pollfds[nextIndex].fd = fd;
             pollFdIndices[fd].index = nextIndex;
             pollFdIndices[fd].events = event;
             ++nextIndex;
             if (nextIndex == pollfds.size()) {
                 pollfds.resize(pollfds.size() * 2, {-1, 0, 0});
                 pollFdIndices.reserve(pollfds.size());
             }
         } else {
             PollFdIndex& pollFdIndex = pollFdIndices[fd];
             pollfds[pollFdIndex.index].events |= event;
             pollFdIndex.events |= event;
         }
     }
References core::poll::PollFdsManager::PollFdIndex::events, core::DescriptorEventReceiver::getRegisteredFd(), core::poll::PollFdsManager::PollFdIndex::index, nextIndex, pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventPublisher::muxAdd().
muxDel()
void core::poll::PollFdsManager::muxDel (int fd, short event)
Definition at line 72 of file EventMultiplexer.cpp.
{
         std::unordered_map<int, PollFdIndex>::iterator itPollFdIndex = pollFdIndices.find(fd);
         PollFdIndex& pollFdIndex = itPollFdIndex->second;
         pollfds[pollFdIndex.index].events &= static_cast<short>(~event); // tilde promotes to int
         pollFdIndex.events &= static_cast<short>(~event);                // tilde promotes to int
         if (pollFdIndex.events == 0) {
             pollfds[pollFdIndex.index].fd = -1; // Compress will keep track of that descriptor
             pollFdIndices.erase(fd);
             if (pollfds.size() > (pollFdIndices.size() * 2) + 1) {
                 compress();
             }
         }
     }
References compress(), core::poll::PollFdsManager::PollFdIndex::events, core::poll::PollFdsManager::PollFdIndex::index, pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventPublisher::muxDel().
muxOff()
void core::poll::PollFdsManager::muxOff (core::DescriptorEventReceiver * eventReceiver, short event)
Definition at line 96 of file EventMultiplexer.cpp.
{
         pollfds[pollFdIndices.find(eventReceiver->getRegisteredFd())->second.index].events &=
             static_cast<short>(~event); // Tilde promotes to int
     }
References core::DescriptorEventReceiver::getRegisteredFd(), pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventPublisher::muxOff().
muxOn()
void core::poll::PollFdsManager::muxOn (core::DescriptorEventReceiver * eventReceiver, short event)
Definition at line 90 of file EventMultiplexer.cpp.
{
         int fd = eventReceiver->getRegisteredFd();
         pollfds[pollFdIndices.find(fd)->second.index].events |= event;
     }
References core::DescriptorEventReceiver::getRegisteredFd(), pollFdIndices, and pollfds.
Referenced by core::poll::DescriptorEventPublisher::muxOn().
Member Data Documentation
nextIndex
nfds_t core::poll::PollFdsManager::nextIndex = 0 private
Definition at line 67 of file EventMultiplexer.h.
Referenced by compress(), getCurrentSize(), and muxAdd().
pollFdIndices
std::unordered_map<int, PollFdIndex> core::poll::PollFdsManager::pollFdIndices private
Definition at line 71 of file EventMultiplexer.h.
Referenced by compress(), getPollFdIndices(), muxAdd(), muxDel(), muxOff(), muxOn(), and PollFdsManager().
pollfds
std::vector<pollfd> core::poll::PollFdsManager::pollfds private
Definition at line 70 of file EventMultiplexer.h.
Referenced by compress(), getEvents(), muxAdd(), muxDel(), muxOff(), muxOn(), and PollFdsManager().
The documentation for this class was generated from the following files:
core/multiplexer/poll/EventMultiplexer.h
core/multiplexer/poll/EventMultiplexer.cpp