snode.c: net::l2::stream::ServerSocket Class Reference
net::l2::stream::ServerSocket Class Reference
#include <ServerSocket.h>
Public Member Functions
ServerSocket (const std::string &name)
void listen (const std::function< void(const Socket &socket, int)> &onError)
void listen (uint16_t psm, int backlog, const std::function< void(const Socket &socket, int)> &onError)
void listen (const std::string &address, int backlog, const std::function< void(const Socket &socket, int)> &onError)
void listen (const std::string &address, uint16_t psm, int backlog, const std::function< void(const Socket &socket, int)> &onError)
Public Member Functions inherited from core::socket::ServerSocket< net::l2::stream::Socket, net::l2::stream::ServerConfig >
virtual void listen (const typename Socket::SocketAddress &bindAddress, int backlog, const std::function< void(const Socket &socket, int)> &onError) const=0
ServerConfig & getServerConfig ()
Private Types
using Super = core::socket::ServerSocket< net::l2::stream::Socket, net::l2::stream::ServerConfig >
Additional Inherited Members
Public Types inherited from core::socket::ServerSocket< net::l2::stream::Socket, net::l2::stream::ServerConfig >
using Socket = net::l2::stream::Socket
using ServerConfig = net::l2::stream::ServerConfig
Protected Member Functions inherited from core::socket::ServerSocket< net::l2::stream::Socket, net::l2::stream::ServerConfig >
ServerSocket (const std::string &name)
Protected Attributes inherited from core::socket::ServerSocket< net::l2::stream::Socket, net::l2::stream::ServerConfig >
ServerConfig serverConfig
Detailed Description
Definition at line 36 of file ServerSocket.h.
Member Typedef Documentation
Super
using net::l2::stream::ServerSocket::Super = core::socket::ServerSocket<net::l2::stream::Socket, net::l2::stream::ServerConfig> private
Definition at line 37 of file ServerSocket.h.
Constructor & Destructor Documentation
ServerSocket()
net::l2::stream::ServerSocket::ServerSocket (const std::string & name) explicit
Definition at line 27 of file ServerSocket.cpp.
         : Super(name) {
     }
Member Function Documentation
listen() [1/4]
void net::l2::stream::ServerSocket::listen (const std::function< void(const Socket &socket, int)> & onError)
Referenced by listen().
listen() [2/4]
void net::l2::stream::ServerSocket::listen (const std::string & address, int backlog, const std::function< void(const Socket &socket, int)> & onError)
Definition at line 41 of file ServerSocket.cpp.
{
         listen(SocketAddress(address), backlog, onError);
     }
References listen().
listen() [3/4]
void net::l2::stream::ServerSocket::listen (const std::string & address, uint16_t psm, int backlog, const std::function< void(const Socket &socket, int)> & onError)
Definition at line 45 of file ServerSocket.cpp.
{
         listen(SocketAddress(address, psm), backlog, onError);
     }
References listen().
listen() [4/4]
void net::l2::stream::ServerSocket::listen (uint16_t psm, int backlog, const std::function< void(const Socket &socket, int)> & onError)
Definition at line 37 of file ServerSocket.cpp.
{
         listen(SocketAddress(psm), backlog, onError);
     }
References listen().
The documentation for this class was generated from the following files:
net/l2/stream/ServerSocket.h
net/l2/stream/ServerSocket.cpp