snode.c: core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT > Class Template Reference
core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT > Class Template Reference
#include <SocketServer.h>
Public Types
using Socket = typename ServerSocket::Socket
using SocketAddress = typename Socket::SocketAddress
using SocketConnection = typename SocketAcceptor::SocketConnection
Public Member Functions
SocketServer (const std::string &name, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketServer ()=default
void listen (const std::function< void(const Socket &socket, int)> &onError) const override
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(const Socket &socket, int)> &onError) const override
void onConnect (const std::function< void(SocketConnection *)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
ServerConfig & getServerConfig ()
Protected Types
using ServerSocket = ServerSocketT
using ServerConfig = ServerConfigT
using SocketAcceptor = SocketAcceptorT
using SocketContextFactory = SocketContextFactoryT
Protected Attributes
ServerConfig serverConfig
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(SocketConnection *)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Private Member Functions
SocketServer ()=delete
Detailed Description
template<typename ServerSocketT, typename ServerConfigT, typename SocketAcceptorT, typename SocketContextFactoryT>
class core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >
Definition at line 36 of file SocketServer.h.
Member Typedef Documentation
ServerConfig
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > using core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::ServerConfig = ServerConfigT protected
Definition at line 41 of file SocketServer.h.
ServerSocket
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > using core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::ServerSocket = ServerSocketT protected
Definition at line 40 of file SocketServer.h.
Socket
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > using core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::Socket = typename ServerSocket::Socket
Definition at line 46 of file SocketServer.h.
SocketAcceptor
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > using core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::SocketAcceptor = SocketAcceptorT protected
Definition at line 42 of file SocketServer.h.
SocketAddress
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > using core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::SocketAddress = typename Socket::SocketAddress
Definition at line 47 of file SocketServer.h.
SocketConnection
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > using core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::SocketConnection = typename SocketAcceptor::SocketConnection
Definition at line 48 of file SocketServer.h.
SocketContextFactory
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > using core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::SocketContextFactory = SocketContextFactoryT protected
Definition at line 43 of file SocketServer.h.
Constructor & Destructor Documentation
SocketServer() [1/2]
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::SocketServer () private delete
SocketServer() [2/2]
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::SocketServer (const std::string & name, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect, const std::map< std::string, std::any > & options = {{}}) inline
Definition at line 50 of file SocketServer.h.
                                                                 {{}})
             : serverConfig(name)
             , socketContextFactory(std::make_shared<SocketContextFactory>())
             , _onConnect(onConnect)
             , _onConnected(onConnected)
             , _onDisconnect(onDisconnect)
             , options(options) {
         }
~SocketServer()
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > virtual core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::~SocketServer () virtual default
Member Function Documentation
getServerConfig()
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > ServerConfig& core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::getServerConfig () inline
Definition at line 98 of file SocketServer.h.
{
             return serverConfig;
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::serverConfig.
getSocketContextFactory()
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::getSocketContextFactory () inline
Definition at line 94 of file SocketServer.h.
{
             return socketContextFactory;
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::socketContextFactory.
listen() [1/2]
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > void core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen (const SocketAddress & bindAddress, int backlog, const std::function< void(const Socket &socket, int)> & onError) const inline override
Definition at line 73 of file SocketServer.h.
{
             SocketAcceptor* socketAcceptor =
                 new SocketAcceptor(serverConfig, socketContextFactory, _onConnect, _onConnected, _onDisconnect, options);
             socketAcceptor->listen(bindAddress, backlog, onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onConnect, core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onConnected, core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onDisconnect, core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::options, core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::serverConfig, and core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::socketContextFactory.
listen() [2/2]
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > void core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen (const std::function< void(const Socket &socket, int)> & onError) const inline override
Definition at line 67 of file SocketServer.h.
{
             serverConfig.parse(true);
             listen(serverConfig.getBindAddress(), serverConfig.getBacklog(), onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::serverConfig.
onConnect()
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > void core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::onConnect (const std::function< void(SocketConnection *)> & onConnect) inline
Definition at line 82 of file SocketServer.h.
{
             _onConnect = onConnect;
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onConnect.
onConnected()
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > void core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::onConnected (const std::function< void(SocketConnection *)> & onConnected) inline
Definition at line 86 of file SocketServer.h.
{
             _onConnected = onConnected;
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onConnected.
onDisconnect()
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > void core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::onDisconnect (const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 90 of file SocketServer.h.
{
             _onDisconnect = onDisconnect;
         }
References core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onDisconnect.
Member Data Documentation
_onConnect
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onConnect protected
Definition at line 107 of file SocketServer.h.
Referenced by core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen(), and core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::onConnect().
_onConnected
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onConnected protected
Definition at line 108 of file SocketServer.h.
Referenced by core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen(), and core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::onConnected().
_onDisconnect
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > std::function<void(SocketConnection*)> core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::_onDisconnect protected
Definition at line 109 of file SocketServer.h.
Referenced by core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen(), and core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::onDisconnect().
options
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > std::map<std::string, std::any> core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::options protected
Definition at line 111 of file SocketServer.h.
Referenced by core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen().
serverConfig
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > ServerConfig core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::serverConfig protected
Definition at line 103 of file SocketServer.h.
Referenced by core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::getServerConfig(), and core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen().
socketContextFactory
template<typename ServerSocketT , typename ServerConfigT , typename SocketAcceptorT , typename SocketContextFactoryT > std::shared_ptr<SocketContextFactory> core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::socketContextFactory protected
Definition at line 105 of file SocketServer.h.
Referenced by core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::getSocketContextFactory(), and core::socket::stream::SocketServer< ServerSocketT, ServerConfigT, SocketAcceptorT, SocketContextFactoryT >::listen().
The documentation for this class was generated from the following file:
core/socket/stream/SocketServer.h