snode.c: net::l2::ConfigLocal Class Reference
net::l2::ConfigLocal Class Reference
#include <ConfigLocal.h>
Public Member Functions
ConfigLocal (CLI::App *baseSc)
Public Member Functions inherited from net::ConfigLocal< SocketAddress >
const SocketAddress & getLocalAddress () const
void setLocalAddress (const SocketAddress &localAddress) const
Protected Member Functions
void required () const
Protected Member Functions inherited from net::ConfigLocal< SocketAddress >
ConfigLocal ()=default
virtual ~ConfigLocal ()=default
Protected Attributes
CLI::App * bindSc = nullptr
CLI::Option * bindHostOpt = nullptr
CLI::Option * bindPsmOpt = nullptr
Private Member Functions
SocketAddress getAddress () const override
Private Attributes
std::string bindHost = ""
uint16_t bindPsm = 0
Additional Inherited Members
Protected Types inherited from net::ConfigLocal< SocketAddress >
using SocketAddress = SocketAddress
Detailed Description
Definition at line 39 of file ConfigLocal.h.
Constructor & Destructor Documentation
ConfigLocal()
net::l2::ConfigLocal::ConfigLocal (CLI::App * baseSc) explicit
Definition at line 29 of file ConfigLocal.cpp.
{
         bindSc = baseSc->add_subcommand("local");
         bindSc->description("Bind options");
         bindSc->configurable();
         bindSc->required();
         bindHostOpt = bindSc->add_option("-a,--host", bindHost, "Bluetooth address");
         bindHostOpt->type_name("[bluetooth address]");
         bindHostOpt->default_val("00:00:00:00:00:00");
         bindHostOpt->take_first();
         bindHostOpt->configurable();
         bindPsmOpt = bindSc->add_option("-p,--psm", bindPsm, "Protocol service multiplexer");
         bindPsmOpt->type_name("[uint16_t]");
         bindPsmOpt->default_val(0);
         bindPsmOpt->take_first();
         bindPsmOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindHost, bindHostOpt, bindPsm, bindPsmOpt, bindSc, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), CLI::App::required(), CLI::OptionBase< CRTP >::take_first(), and CLI::Option::type_name().
Member Function Documentation
getAddress()
SocketAddress net::l2::ConfigLocal::getAddress () const override private virtual
Implements net::ConfigLocal< SocketAddress >.
Definition at line 48 of file ConfigLocal.cpp.
{
         return SocketAddress(bindHost, bindPsm);
     }
References bindHost, and bindPsm.
required()
void net::l2::ConfigLocal::required () const protected
Definition at line 52 of file ConfigLocal.cpp.
{
         bindSc->required();
         bindPsmOpt->required();
     }
References bindPsmOpt, bindSc, CLI::App::required(), and CLI::OptionBase< CRTP >::required().
Referenced by net::l2::stream::ServerConfig::ServerConfig().
Member Data Documentation
bindHost
std::string net::l2::ConfigLocal::bindHost = "" private
Definition at line 53 of file ConfigLocal.h.
Referenced by ConfigLocal(), and getAddress().
bindHostOpt
CLI::Option* net::l2::ConfigLocal::bindHostOpt = nullptr protected
Definition at line 47 of file ConfigLocal.h.
Referenced by ConfigLocal().
bindPsm
uint16_t net::l2::ConfigLocal::bindPsm = 0 private
Definition at line 54 of file ConfigLocal.h.
Referenced by ConfigLocal(), and getAddress().
bindPsmOpt
CLI::Option* net::l2::ConfigLocal::bindPsmOpt = nullptr protected
Definition at line 48 of file ConfigLocal.h.
Referenced by ConfigLocal(), and required().
bindSc
CLI::App* net::l2::ConfigLocal::bindSc = nullptr protected
Definition at line 46 of file ConfigLocal.h.
Referenced by ConfigLocal(), and required().
The documentation for this class was generated from the following files:
net/l2/ConfigLocal.h
net/l2/ConfigLocal.cpp