snode.c: core::EventMultiplexer::EventQueue Class Reference
core::EventMultiplexer::EventQueue Class Reference
Public Member Functions
EventQueue ()
~EventQueue ()
void insert (Event *event)
void remove (Event *event)
void execute (const utils::Timeval &currentTime)
bool empty () const
Private Attributes
std::list< Event * > * executeQueue
std::list< Event * > * publishQueue
Detailed Description
Definition at line 55 of file EventMultiplexer.h.
Constructor & Destructor Documentation
EventQueue()
core::EventMultiplexer::EventQueue::EventQueue ()
Definition at line 158 of file EventMultiplexer.cpp.
         : executeQueue(new std::list<Event*>()) // cppcheck-suppress [noCopyConstructor, noOperatorEq]
         , publishQueue(new std::list<Event*>()) {
     }
~EventQueue()
core::EventMultiplexer::EventQueue::~EventQueue ()
Definition at line 163 of file EventMultiplexer.cpp.
{
         delete executeQueue;
         delete publishQueue;
     }
Member Function Documentation
empty()
bool core::EventMultiplexer::EventQueue::empty () const
Definition at line 186 of file EventMultiplexer.cpp.
{
         return publishQueue->empty();
     }
Referenced by core::EventMultiplexer::getNextTimeout(), and core::EventMultiplexer::tick().
execute()
void core::EventMultiplexer::EventQueue::execute (const utils::Timeval & currentTime)
Definition at line 176 of file EventMultiplexer.cpp.
{
         std::swap(executeQueue, publishQueue);
         for (Event* event : *executeQueue) {
             event->dispatch(currentTime);
         }
         executeQueue->clear();
     }
Referenced by core::EventMultiplexer::tick().
insert()
void core::EventMultiplexer::EventQueue::insert (Event * event)
Definition at line 168 of file EventMultiplexer.cpp.
{
         publishQueue->push_back(event); // do not allow two or more same events in one tick
     }
Referenced by core::EventMultiplexer::publish().
remove()
void core::EventMultiplexer::EventQueue::remove (Event * event)
Definition at line 172 of file EventMultiplexer.cpp.
{
         publishQueue->remove(event); // in case of erase remove the event from the published queue
     }
Referenced by core::EventMultiplexer::unPublish().
Member Data Documentation
executeQueue
std::list<Event*>* core::EventMultiplexer::EventQueue::executeQueue private
Definition at line 66 of file EventMultiplexer.h.
publishQueue
std::list<Event*>* core::EventMultiplexer::EventQueue::publishQueue private
Definition at line 67 of file EventMultiplexer.h.
The documentation for this class was generated from the following files:
core/EventMultiplexer.h
core/EventMultiplexer.cpp