snode.c: core::select::DescriptorEventDispatcher Class Reference
core::select::DescriptorEventDispatcher Class Reference
#include <DescriptorEventDispatcher.h>
Public Member Functions
DescriptorEventDispatcher (FdSet &fdSet)
Public Member Functions inherited from core::DescriptorEventDispatcher
virtual ~DescriptorEventDispatcher ()=default
void publish (Event *event)
void enable (DescriptorEventReceiver *eventReceiver)
void disable (DescriptorEventReceiver *eventReceiver)
void suspend (DescriptorEventReceiver *eventReceiver)
void resume (DescriptorEventReceiver *eventReceiver)
void observeEnabledEvents (const utils::Timeval &currentTime)
void dispatchImmediateEvents ()
void checkTimedOutEvents (const utils::Timeval &currentTime)
void unobserveDisabledEvents (const utils::Timeval &currentTime)
virtual void finishTick ()
int getObservedEventReceiverCount () const
int getMaxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void stop ()
Private Member Functions
DescriptorEventDispatcher (const DescriptorEventDispatcher &)=delete
DescriptorEventDispatcher & operator= (const DescriptorEventDispatcher &)=delete
void modAdd (core::DescriptorEventReceiver *eventReceiver) override
void modDel (core::DescriptorEventReceiver *eventReceiver) override
void modOn (core::DescriptorEventReceiver *eventReceiver) override
void modOff (core::DescriptorEventReceiver *eventReceiver) override
void dispatchActiveEvents () override
Private Attributes
FdSet & fdSet
Additional Inherited Members
Protected Member Functions inherited from core::DescriptorEventDispatcher
DescriptorEventDispatcher ()=default
Protected Attributes inherited from core::DescriptorEventDispatcher
std::map< int, EventReceiverList > enabledEventReceiver
std::map< int, EventReceiverList > observedEventReceiver
std::map< int, EventReceiverList > disabledEventReceiver
unsigned long eventCounter = 0
Detailed Description
Definition at line 51 of file DescriptorEventDispatcher.h.
Constructor & Destructor Documentation
DescriptorEventDispatcher() [1/2]
core::select::DescriptorEventDispatcher::DescriptorEventDispatcher (const DescriptorEventDispatcher &) private delete
DescriptorEventDispatcher() [2/2]
core::select::DescriptorEventDispatcher::DescriptorEventDispatcher (FdSet & fdSet) explicit
Definition at line 59 of file DescriptorEventDispatcher.cpp.
         : fdSet(fdSet) {
     }
Member Function Documentation
dispatchActiveEvents()
void core::select::DescriptorEventDispatcher::dispatchActiveEvents () override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 79 of file DescriptorEventDispatcher.cpp.
{
         for (const auto& [fd, eventReceivers] : observedEventReceiver) {
             core::DescriptorEventReceiver* eventReceiver = eventReceivers.front();
             if (fdSet.isSet(fd) && !eventReceiver->continueImmediately() && !eventReceiver->isSuspended()) {
                 eventCounter++;
                 eventReceiver->publish();
             }
         }
     }
References core::DescriptorEventReceiver::continueImmediately(), core::DescriptorEventDispatcher::eventCounter, fdSet, core::select::FdSet::isSet(), core::DescriptorEventReceiver::isSuspended(), core::DescriptorEventDispatcher::observedEventReceiver, and core::EventReceiver::publish().
modAdd()
void core::select::DescriptorEventDispatcher::modAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 63 of file DescriptorEventDispatcher.cpp.
{
         fdSet.set(eventReceiver->getRegisteredFd());
     }
References fdSet, core::DescriptorEventReceiver::getRegisteredFd(), and core::select::FdSet::set().
modDel()
void core::select::DescriptorEventDispatcher::modDel (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 67 of file DescriptorEventDispatcher.cpp.
{
         fdSet.clr(eventReceiver->getRegisteredFd());
     }
References core::select::FdSet::clr(), fdSet, and core::DescriptorEventReceiver::getRegisteredFd().
modOff()
void core::select::DescriptorEventDispatcher::modOff (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 75 of file DescriptorEventDispatcher.cpp.
{
         fdSet.clr(eventReceiver->getRegisteredFd());
     }
References core::select::FdSet::clr(), fdSet, and core::DescriptorEventReceiver::getRegisteredFd().
modOn()
void core::select::DescriptorEventDispatcher::modOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventDispatcher.
Definition at line 71 of file DescriptorEventDispatcher.cpp.
{
         fdSet.set(eventReceiver->getRegisteredFd());
     }
References fdSet, core::DescriptorEventReceiver::getRegisteredFd(), and core::select::FdSet::set().
operator=()
DescriptorEventDispatcher& core::select::DescriptorEventDispatcher::operator= (const DescriptorEventDispatcher &) private delete
Member Data Documentation
fdSet
FdSet& core::select::DescriptorEventDispatcher::fdSet private
Definition at line 66 of file DescriptorEventDispatcher.h.
Referenced by dispatchActiveEvents(), modAdd(), modDel(), modOff(), and modOn().
The documentation for this class was generated from the following files:
core/mux/select/DescriptorEventDispatcher.h
core/mux/select/DescriptorEventDispatcher.cpp