snode.c: web::websocket::client::SocketContextUpgradeFactory Class Reference
web::websocket::client::SocketContextUpgradeFactory Class Reference
#include <SocketContextUpgradeFactory.h>
Public Member Functions
SocketContextUpgradeFactory ()=default
SocketContextUpgradeFactory (const SocketContextUpgradeFactory &)=delete
SocketContextUpgradeFactory & operator= (const SocketContextUpgradeFactory &)=delete
Public Member Functions inherited from web::http::client::SocketContextUpgradeFactory
void checkRefCount () final
Public Member Functions inherited from web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >
void prepare (Request &request, Response &response)
void destroy ()
void incRefCount ()
void decRefCount ()
Static Public Member Functions
static void link ()
Private Member Functions
void prepare (web::http::client::Request &request) override
std::string name () override
SocketContextUpgrade * create (core::socket::SocketConnection *socketConnection, web::http::client::Request *request, web::http::client::Response *response) override
Additional Inherited Members
Public Types inherited from web::http::client::SocketContextUpgradeFactory
using Resquest = web::http::client::Request
using Reponse = web::http::client::Response
Public Types inherited from web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >
using Request = web::http::client::Request
using Response = web::http::client::Response
Protected Member Functions inherited from web::http::client::SocketContextUpgradeFactory
SocketContextUpgradeFactory ()
Protected Member Functions inherited from web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >
SocketContextUpgradeFactory ()
~SocketContextUpgradeFactory () override=default
Protected Member Functions inherited from core::socket::SocketContextFactory
SocketContextFactory ()=default
virtual ~SocketContextFactory ()=default
Static Protected Member Functions inherited from web::http::client::SocketContextUpgradeFactory
static void link (const std::string &upgradeContextName, SocketContextUpgradeFactory *(*linkedPlugin)())
Protected Attributes inherited from web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >
std::size_t refCount
Detailed Description
Definition at line 42 of file SocketContextUpgradeFactory.h.
Constructor & Destructor Documentation
SocketContextUpgradeFactory() [1/2]
web::websocket::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory () default
SocketContextUpgradeFactory() [2/2]
web::websocket::client::SocketContextUpgradeFactory::SocketContextUpgradeFactory (const SocketContextUpgradeFactory &) delete
Member Function Documentation
create()
SocketContextUpgrade * web::websocket::client::SocketContextUpgradeFactory::create (core::socket::SocketConnection * socketConnection, web::http::client::Request * request, web::http::client::Response * response) override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >.
Definition at line 46 of file SocketContextUpgradeFactory.cpp.
{
         SocketContextUpgrade* socketContext = nullptr;
         if (response->header("sec-websocket-accept") == base64::serverWebSocketKey(request->header("Sec-WebSocket-Key"))) {
             std::string subProtocolName = response->header("sec-websocket-protocol");
             socketContext = SocketContextUpgrade::create(this, socketConnection, subProtocolName);
         }
         return socketContext;
     }
References web::websocket::client::SocketContextUpgrade::create(), web::http::client::Request::header(), web::http::client::Response::header(), web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >::request, web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >::response, and base64::serverWebSocketKey().
link()
void web::websocket::client::SocketContextUpgradeFactory::link () static
Definition at line 60 of file SocketContextUpgradeFactory.cpp.
{
         static bool linked = false;
         if (!linked) {
             web::http::client::SocketContextUpgradeFactory::link(
                 "websocket", websocketClientContextUpgradeFactory); // cppcheck-suppress leakNoVarFunctionCall
             linked = true;
         }
     }
References web::http::client::SocketContextUpgradeFactory::link(), and web::websocket::client::websocketClientContextUpgradeFactory().
name()
std::string web::websocket::client::SocketContextUpgradeFactory::name () override private virtual
Implements web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >.
Definition at line 42 of file SocketContextUpgradeFactory.cpp.
{
         return "websocket";
     }
operator=()
SocketContextUpgradeFactory& web::websocket::client::SocketContextUpgradeFactory::operator= (const SocketContextUpgradeFactory &) delete
prepare()
void web::websocket::client::SocketContextUpgradeFactory::prepare (web::http::client::Request & request) override private virtual
Implements web::http::client::SocketContextUpgradeFactory.
Definition at line 34 of file SocketContextUpgradeFactory.cpp.
{
         unsigned char ebytes[16];
         getentropy(ebytes, 16);
         request.set("Sec-WebSocket-Key", base64::base64_encode(ebytes, 16));
         request.set("Sec-WebSocket-Version", "13");
     }
References base64::base64_encode(), web::http::SocketContextUpgradeFactory< web::http::client::Request, web::http::client::Response >::request, and web::http::client::Request::set().
The documentation for this class was generated from the following files:
web/websocket/client/SocketContextUpgradeFactory.h
web/websocket/client/SocketContextUpgradeFactory.cpp