snode.c: core::pipe::Sink Class Reference
core::pipe::Sink Class Reference abstract
#include <Sink.h>
Public Member Functions
Sink ()
Sink (const Sink &)=default
virtual ~Sink ()
virtual void receive (const char *junk, std::size_t junkLen)=0
virtual void eof ()=0
virtual void error (int errnum)=0
void disconnect ()
void connect (Source &source)
void disconnect (Source &source)
Protected Attributes
Source * source
Detailed Description
Definition at line 32 of file Sink.h.
Constructor & Destructor Documentation
Sink() [1/2]
core::pipe::Sink::Sink ()
Definition at line 29 of file Sink.cpp.
         : source(nullptr) {
     }
Sink() [2/2]
core::pipe::Sink::Sink (const Sink &) default
~Sink()
core::pipe::Sink::~Sink () virtual
Definition at line 33 of file Sink.cpp.
                 {
         disconnect();
     }
References disconnect().
Member Function Documentation
connect()
void core::pipe::Sink::connect (Source & source)
Definition at line 44 of file Sink.cpp.
{
         this->source = &source;
     }
References source.
Referenced by core::pipe::Source::connect().
disconnect() [1/2]
void core::pipe::Sink::disconnect ()
Definition at line 37 of file Sink.cpp.
{
         if (source != nullptr) {
             source->disconnect(*this);
             source = nullptr;
         }
     }
References core::pipe::Source::disconnect(), and source.
Referenced by core::pipe::Source::disconnect(), and ~Sink().
disconnect() [2/2]
void core::pipe::Sink::disconnect (Source & source)
Definition at line 48 of file Sink.cpp.
{
         if (&source == this->source) {
             this->source = nullptr;
         }
     }
References source.
eof()
virtual void core::pipe::Sink::eof () pure virtual
Implemented in web::http::server::Response.
Referenced by core::pipe::Source::eof().
error()
virtual void core::pipe::Sink::error (int errnum) pure virtual
Implemented in web::http::server::Response.
Referenced by core::pipe::Source::error().
receive()
virtual void core::pipe::Sink::receive (const char * junk, std::size_t junkLen) pure virtual
Implemented in web::http::server::Response.
Referenced by core::pipe::Source::send().
Member Data Documentation
source
Source* core::pipe::Sink::source protected
Definition at line 48 of file Sink.h.
Referenced by connect(), and disconnect().
The documentation for this class was generated from the following files:
core/pipe/Sink.h
core/pipe/Sink.cpp