snode.c: net::rf::stream::ConfigBind Class Reference
net::rf::stream::ConfigBind Class Reference
#include <ConfigBind.h>
Public Member Functions
ConfigBind (CLI::App *baseSc)
const std::string & getBindHost () const
uint8_t getBindChannel () const
SocketAddress getBindAddress () const
Protected Member Functions
void required (bool req) const
Protected Attributes
CLI::App * bindSc = nullptr
CLI::Option * bindHostOpt = nullptr
CLI::Option * bindChannelOpt = nullptr
Private Attributes
std::string bindHost = ""
uint8_t bindChannel = 0
Detailed Description
Definition at line 38 of file ConfigBind.h.
Constructor & Destructor Documentation
ConfigBind()
net::rf::stream::ConfigBind::ConfigBind (CLI::App * baseSc) explicit
Definition at line 31 of file ConfigBind.cpp.
{
         bindSc = baseSc->add_subcommand("bind");
         bindSc->description("Bind options");
         bindSc->configurable();
         bindSc->required();
         bindHostOpt = bindSc->add_option("-a,--host", bindHost, "Bluetooth address");
         bindHostOpt->type_name("[bluetooth address]");
         bindHostOpt->default_val("00:00:00:00:00:00");
         bindHostOpt->configurable();
         bindChannelOpt = bindSc->add_option("-c,--channel", bindChannel, "Channel number");
         bindChannelOpt->type_name("[uint8_t]");
         bindChannelOpt->default_val(0);
         bindChannelOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindChannel, bindChannelOpt, bindHost, bindHostOpt, bindSc, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), CLI::App::required(), and CLI::Option::type_name().
Member Function Documentation
getBindAddress()
SocketAddress net::rf::stream::ConfigBind::getBindAddress () const
Definition at line 56 of file ConfigBind.cpp.
{
         return SocketAddress(bindHost, bindChannel);
     }
References bindChannel, and bindHost.
getBindChannel()
uint8_t net::rf::stream::ConfigBind::getBindChannel () const
Definition at line 52 of file ConfigBind.cpp.
{
         return bindChannel;
     }
References bindChannel.
getBindHost()
const std::string & net::rf::stream::ConfigBind::getBindHost () const
Definition at line 48 of file ConfigBind.cpp.
{
         return bindHost;
     }
References bindHost.
required()
void net::rf::stream::ConfigBind::required (bool req) const protected
Definition at line 60 of file ConfigBind.cpp.
{
         utils::Config::instance().required(bindSc, req);
         utils::Config::instance().required(bindChannelOpt, req);
     }
References bindChannelOpt, bindSc, utils::Config::instance(), and utils::Config::required().
Referenced by net::rf::stream::ServerConfig::required().
Member Data Documentation
bindChannel
uint8_t net::rf::stream::ConfigBind::bindChannel = 0 private
Definition at line 57 of file ConfigBind.h.
Referenced by ConfigBind(), getBindAddress(), and getBindChannel().
bindChannelOpt
CLI::Option* net::rf::stream::ConfigBind::bindChannelOpt = nullptr protected
Definition at line 53 of file ConfigBind.h.
Referenced by ConfigBind(), and required().
bindHost
std::string net::rf::stream::ConfigBind::bindHost = "" private
Definition at line 56 of file ConfigBind.h.
Referenced by ConfigBind(), getBindAddress(), and getBindHost().
bindHostOpt
CLI::Option* net::rf::stream::ConfigBind::bindHostOpt = nullptr protected
Definition at line 52 of file ConfigBind.h.
Referenced by ConfigBind().
bindSc
CLI::App* net::rf::stream::ConfigBind::bindSc = nullptr protected
Definition at line 51 of file ConfigBind.h.
Referenced by ConfigBind(), and required().
The documentation for this class was generated from the following files:
net/rf/stream/ConfigBind.h
net/rf/stream/ConfigBind.cpp