snode.c: express::State Class Reference
express::State Class Reference
#include <State.h>
Public Types
enum Flags { NONE = 0 , NEXT = 1 << 0 , NEXT_ROUTE = 1 << 1 , NEXT_ROUTER = 1 << 2 }
Public Member Functions
State (Request &request, Response &response)
void setRootRoute (RootRoute *rootRoute)
void setCurrentRoute (Route *newCurrentRoute)
Request * getRequest () const
Response * getResponse () const
int getFlags () const
void next (const std::string &how)
bool nextRouter ()
bool dispatchNext (const std::string &parentMountPath)
Private Attributes
RootRoute * rootRoute = nullptr
Route * lastRoute = nullptr
Route * currentRoute = nullptr
unsigned long lastTick = 0
Request * request = nullptr
Response * response = nullptr
int flags = NONE
Detailed Description
Definition at line 39 of file State.h.
Member Enumeration Documentation
Flags
enum express::State::Flags
Enumerator
NONE
NEXT
NEXT_ROUTE
NEXT_ROUTER
Definition at line 54 of file State.h.
 { NONE = 0, NEXT = 1 << 0, NEXT_ROUTE = 1 << 1, NEXT_ROUTER = 1 << 2 };
Constructor & Destructor Documentation
State()
express::State::State (Request & request, Response & response)
Definition at line 31 of file State.cpp.
         : lastTick(core::EventLoop::getTickCounter())
         , request(&request)
         , response(&response) {
         request.extend();
     }
References express::Request::extend(), and request.
Member Function Documentation
dispatchNext()
bool express::State::dispatchNext (const std::string & parentMountPath)
Definition at line 85 of file State.cpp.
{
         bool dispatched = false;
         if (((flags & State::NEXT) != 0)) {
             if (lastRoute == currentRoute) {
                 flags &= ~State::NEXT;
                 if ((flags & State::NEXT_ROUTE) != 0) {
                     flags &= ~State::NEXT_ROUTE;
                 } else if ((flags & State::NEXT_ROUTER) == 0) {
                     dispatched = currentRoute->dispatchNext(*this, parentMountPath);
                 }
             } else { // ? Optimization: Dispatch only parent route matched path
                 dispatched = currentRoute->dispatchNext(*this, parentMountPath);
             }
         }
         return dispatched;
     }
References currentRoute, express::Route::dispatchNext(), flags, lastRoute, NEXT, NEXT_ROUTE, and NEXT_ROUTER.
Referenced by express::Route::dispatch().
getFlags()
int express::State::getFlags () const
Definition at line 54 of file State.cpp.
{
         return flags;
     }
References flags.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), and express::dispatcher::MiddlewareDispatcher::dispatch().
getRequest()
Request * express::State::getRequest () const
Definition at line 46 of file State.cpp.
{
         return request;
     }
References request.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), express::dispatcher::MiddlewareDispatcher::dispatch(), and express::dispatcher::RouterDispatcher::dispatch().
getResponse()
Response * express::State::getResponse () const
Definition at line 50 of file State.cpp.
{
         return response;
     }
References response.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), express::dispatcher::MiddlewareDispatcher::dispatch(), and express::RootRoute::dispatch().
next()
void express::State::next (const std::string & how)
Definition at line 58 of file State.cpp.
{
         flags = NEXT;
         if (how == "route") {
             flags |= NEXT_ROUTE;
         } else if (how == "router") {
             flags |= NEXT_ROUTER;
         }
         lastRoute = currentRoute;
         if (lastTick != core::EventLoop::getTickCounter()) { // If asynchron next() start traversing of route-tree
             rootRoute->dispatch(*this);
         }
     }
References currentRoute, express::RootRoute::dispatch(), flags, core::EventLoop::getTickCounter(), lastRoute, lastTick, NEXT, NEXT_ROUTE, NEXT_ROUTER, and rootRoute.
Referenced by express::Next::operator()().
nextRouter()
bool express::State::nextRouter ()
Definition at line 74 of file State.cpp.
{
         bool breakDispatching = false;
         if (lastRoute == currentRoute && (flags & State::NEXT_ROUTER) != 0) {
             flags &= ~State::NEXT_ROUTER;
             breakDispatching = true;
         }
         return breakDispatching;
     }
References currentRoute, flags, lastRoute, and NEXT_ROUTER.
Referenced by express::dispatcher::RouterDispatcher::dispatch().
setCurrentRoute()
void express::State::setCurrentRoute (Route * newCurrentRoute)
Definition at line 42 of file State.cpp.
{
         this->currentRoute = currentRoute;
     }
References currentRoute.
Referenced by express::Route::dispatch().
setRootRoute()
void express::State::setRootRoute (RootRoute * rootRoute)
Definition at line 38 of file State.cpp.
{
         this->rootRoute = rootRoute;
     }
References rootRoute.
Member Data Documentation
currentRoute
Route* express::State::currentRoute = nullptr private
Definition at line 60 of file State.h.
Referenced by dispatchNext(), next(), nextRouter(), and setCurrentRoute().
flags
int express::State::flags = NONE private
Definition at line 67 of file State.h.
Referenced by dispatchNext(), getFlags(), next(), and nextRouter().
lastRoute
Route* express::State::lastRoute = nullptr private
Definition at line 59 of file State.h.
Referenced by dispatchNext(), next(), and nextRouter().
lastTick
unsigned long express::State::lastTick = 0 private
Definition at line 62 of file State.h.
Referenced by next().
request
Request* express::State::request = nullptr private
Definition at line 64 of file State.h.
Referenced by getRequest(), and State().
response
Response* express::State::response = nullptr private
Definition at line 65 of file State.h.
Referenced by getResponse().
rootRoute
RootRoute* express::State::rootRoute = nullptr private
Definition at line 57 of file State.h.
Referenced by next(), and setRootRoute().
The documentation for this class was generated from the following files:
express/State.h
express/State.cpp