snode.c: net::rc::stream::ServerSocket< ConfigT > Class Template Reference
net::rc::stream::ServerSocket< ConfigT > Class Template Reference
#include <ServerSocket.h>
Public Member Functions
void listen (uint8_t channel, int backlog, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &address, int backlog, const std::function< void(const SocketAddress &, int)> &onError)
void listen (const std::string &address, uint8_t channel, int backlog, const std::function< void(const SocketAddress &, int)> &onError)
Public Member Functions inherited from net::ServerSocket< ConfigT, net::rc::stream::Socket >
virtual void listen (const std::function< void(const SocketAddress &, int)> &onError) const=0
void listen (const SocketAddress &localAddress, int backlog, const std::function< void(const SocketAddress &, int)> &onError) const
Config & getConfig ()
Protected Member Functions
ServerSocket (const std::string &name)
Protected Member Functions inherited from net::ServerSocket< ConfigT, net::rc::stream::Socket >
ServerSocket (const std::string &name)
ServerSocket (const ServerSocket &)=default
virtual ~ServerSocket ()=default
Private Types
using Super = net::ServerSocket< ConfigT, net::rc::stream::Socket >
Additional Inherited Members
Public Types inherited from net::ServerSocket< ConfigT, net::rc::stream::Socket >
using Config = ConfigT
using Socket = net::rc::stream::Socket
using SocketAddress = typename Socket::SocketAddress
Protected Attributes inherited from net::ServerSocket< ConfigT, net::rc::stream::Socket >
std::shared_ptr< Config > config
Detailed Description
template<typename ConfigT>
class net::rc::stream::ServerSocket< ConfigT >
Definition at line 36 of file ServerSocket.h.
Member Typedef Documentation
Super
template<typename ConfigT > using net::rc::stream::ServerSocket< ConfigT >::Super = net::ServerSocket<ConfigT, net::rc::stream::Socket> private
Definition at line 37 of file ServerSocket.h.
Constructor & Destructor Documentation
ServerSocket()
template<typename Config > net::rc::stream::ServerSocket< Config >::ServerSocket (const std::string & name) explicit protected
Definition at line 28 of file ServerSocket.hpp.
         : Super(name) {
     }
Member Function Documentation
listen() [1/3]
template<typename Config > void net::rc::stream::ServerSocket< Config >::listen (const std::string & address, int backlog, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 39 of file ServerSocket.hpp.
{
         listen(SocketAddress(address), backlog, onError);
     }
References core::system::listen().
listen() [2/3]
template<typename Config > void net::rc::stream::ServerSocket< Config >::listen (const std::string & address, uint8_t channel, int backlog, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 44 of file ServerSocket.hpp.
{
         listen(SocketAddress(address, channel), backlog, onError);
     }
References core::system::listen().
listen() [3/3]
template<typename Config > void net::rc::stream::ServerSocket< Config >::listen (uint8_t channel, int backlog, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 33 of file ServerSocket.hpp.
{
         listen(SocketAddress(channel), backlog, onError);
     }
References core::system::listen().
The documentation for this class was generated from the following files:
net/rc/stream/ServerSocket.h
net/rc/stream/ServerSocket.hpp