snode.c: web::websocket::SubProtocolFactory< SubProtocolT > Class Template Reference
web::websocket::SubProtocolFactory< SubProtocolT > Class Template Reference abstract
#include <SubProtocolFactory.h>
Public Types
using SubProtocol = SubProtocolT
Public Member Functions
SubProtocolFactory (const std::string &name)
SubProtocolFactory ()=delete
virtual ~SubProtocolFactory ()=default
SubProtocol * createSubProtocol ()
virtual std::size_t deleteSubProtocol (SubProtocol *subProtocol)
const std::string & getName ()
virtual SubProtocol * create ()=0
void setHandle (void *handle)
void * getHandle ()
Private Attributes
std::size_t refCount = 0
std::string subProtocolName
void * handle = nullptr
Detailed Description
template<typename SubProtocolT>
class web::websocket::SubProtocolFactory< SubProtocolT >
Definition at line 33 of file SubProtocolFactory.h.
Member Typedef Documentation
SubProtocol
template<typename SubProtocolT > using web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocol = SubProtocolT
Definition at line 35 of file SubProtocolFactory.h.
Constructor & Destructor Documentation
SubProtocolFactory() [1/2]
template<typename SubProtocolT > web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocolFactory (const std::string & name) inline
Definition at line 37 of file SubProtocolFactory.h.
             : subProtocolName(name) {
         }
SubProtocolFactory() [2/2]
template<typename SubProtocolT > web::websocket::SubProtocolFactory< SubProtocolT >::SubProtocolFactory () delete
~SubProtocolFactory()
template<typename SubProtocolT > virtual web::websocket::SubProtocolFactory< SubProtocolT >::~SubProtocolFactory () virtual default
Member Function Documentation
create()
template<typename SubProtocolT > virtual SubProtocol* web::websocket::SubProtocolFactory< SubProtocolT >::create () pure virtual
Referenced by web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol().
createSubProtocol()
template<typename SubProtocolT > SubProtocol* web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol () inline
Definition at line 45 of file SubProtocolFactory.h.
{
             SubProtocol* subProtocol = create();
             refCount++;
             return subProtocol;
         }
References web::websocket::SubProtocolFactory< SubProtocolT >::create(), and web::websocket::SubProtocolFactory< SubProtocolT >::refCount.
Referenced by web::websocket::client::SocketContextUpgrade::create(), and web::websocket::server::SocketContextUpgrade::create().
deleteSubProtocol()
template<typename SubProtocolT > virtual std::size_t web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol (SubProtocol * subProtocol) inline virtual
Definition at line 53 of file SubProtocolFactory.h.
{
             delete subProtocol;
             refCount--;
             return refCount;
         }
References web::websocket::SubProtocolFactory< SubProtocolT >::refCount.
Referenced by web::websocket::client::SocketContextUpgrade::create(), web::websocket::server::SocketContextUpgrade::create(), web::websocket::client::SocketContextUpgrade::~SocketContextUpgrade(), and web::websocket::server::SocketContextUpgrade::~SocketContextUpgrade().
getHandle()
template<typename SubProtocolT > void* web::websocket::SubProtocolFactory< SubProtocolT >::getHandle () inline
Definition at line 71 of file SubProtocolFactory.h.
{
             return handle;
         }
References web::websocket::SubProtocolFactory< SubProtocolT >::handle.
getName()
template<typename SubProtocolT > const std::string& web::websocket::SubProtocolFactory< SubProtocolT >::getName () inline
Definition at line 61 of file SubProtocolFactory.h.
{
             return subProtocolName;
         }
References web::websocket::SubProtocolFactory< SubProtocolT >::subProtocolName.
setHandle()
template<typename SubProtocolT > void web::websocket::SubProtocolFactory< SubProtocolT >::setHandle (void * handle) inline
Definition at line 67 of file SubProtocolFactory.h.
{
             this->handle = handle;
         }
References web::websocket::SubProtocolFactory< SubProtocolT >::handle.
Member Data Documentation
handle
template<typename SubProtocolT > void* web::websocket::SubProtocolFactory< SubProtocolT >::handle = nullptr private
Definition at line 80 of file SubProtocolFactory.h.
Referenced by web::websocket::SubProtocolFactory< SubProtocolT >::getHandle(), and web::websocket::SubProtocolFactory< SubProtocolT >::setHandle().
refCount
template<typename SubProtocolT > std::size_t web::websocket::SubProtocolFactory< SubProtocolT >::refCount = 0 private
Definition at line 76 of file SubProtocolFactory.h.
Referenced by web::websocket::SubProtocolFactory< SubProtocolT >::createSubProtocol(), and web::websocket::SubProtocolFactory< SubProtocolT >::deleteSubProtocol().
subProtocolName
template<typename SubProtocolT > std::string web::websocket::SubProtocolFactory< SubProtocolT >::subProtocolName private
Definition at line 78 of file SubProtocolFactory.h.
Referenced by web::websocket::SubProtocolFactory< SubProtocolT >::getName().
The documentation for this class was generated from the following files:
web/websocket/client/SubProtocolFactorySelector.h
web/websocket/SubProtocolFactory.h