snode.c: express::Response Class Reference
express::Response Class Reference
#include <Response.h>
Public Member Functions
Response (web::http::server::RequestContextBase *requestContext)
void json (const nlohmann::json &json)
void download (const std::string &file, const std::function< void(int err)> &onError)
void download (const std::string &file, const std::string &fileName, const std::function< void(int err)> &onError)
void redirect (const std::string &loc)
void redirect (int state, const std::string &loc)
void sendStatus (int state)
Response & attachment (const std::string &fileName="")
Response & location (const std::string &loc)
Response & vary (const std::string &field)
Public Member Functions inherited from web::http::server::Response
void send (const char *junk, std::size_t junkLen)
void send (const std::string &junk)
void end ()
Response & status (int status)
Response & append (const std::string &field, const std::string &value)
Response & set (const std::string &field, const std::string &value, bool overwrite=true)
Response & set (const std::map< std::string, std::string > &headers, bool overwrite=true)
Response & cookie (const std::string &name, const std::string &value, const std::map< std::string, std::string > &options={})
Response & clearCookie (const std::string &name, const std::map< std::string, std::string > &options={})
Response & type (const std::string &type)
void upgrade (Request &req)
void sendFile (const std::string &file, const std::function< void(int err)> &onError)
Public Member Functions inherited from core::pipe::Sink
Sink ()
Sink (const Sink &)=default
virtual ~Sink ()
void disconnect ()
void connect (Source &source)
void disconnect (Source &source)
Additional Inherited Members
Protected Member Functions inherited from web::http::server::Response
Response (RequestContextBase *requestContext)
Response (const Response &)=default
~Response () override=default
Protected Attributes inherited from web::http::server::Response
RequestContextBase * requestContext
int responseStatus = 200
std::map< std::string, std::string > headers
std::map< std::string, web::http::CookieOptions > cookies
Protected Attributes inherited from core::pipe::Sink
Source * source
Detailed Description
Definition at line 39 of file Response.h.
Constructor & Destructor Documentation
Response()
express::Response::Response (web::http::server::RequestContextBase * requestContext) explicit
Definition at line 32 of file Response.cpp.
         : web::http::server::Response(requestContext) {
     }
Member Function Documentation
attachment()
Response & express::Response::attachment (const std::string & fileName = "")
Definition at line 63 of file Response.cpp.
{
         set("Content-Disposition", "attachment" + ((!fileName.empty()) ? ("; filename=\"" + fileName + "\"") : ""));
         return *this;
     }
References web::http::server::Response::set().
Referenced by download().
download() [1/2]
void express::Response::download (const std::string & file, const std::function< void(int err)> & onError)
Definition at line 41 of file Response.cpp.
{
         download(file, std::filesystem::path(file).filename(), onError);
     }
download() [2/2]
void express::Response::download (const std::string & file, const std::string & fileName, const std::function< void(int err)> & onError)
Definition at line 45 of file Response.cpp.
{
         attachment(fileName);
         sendFile(file, onError);
     }
References attachment(), and web::http::server::Response::sendFile().
json()
void express::Response::json (const nlohmann::json & json)
Definition at line 36 of file Response.cpp.
{
         set("Content-Type", "application/json");
         send(json.dump());
     }
References web::http::server::Response::send(), and web::http::server::Response::set().
location()
Response & express::Response::location (const std::string & loc)
Definition at line 68 of file Response.cpp.
{
         set("Location", loc);
         return *this;
     }
References web::http::server::Response::set().
Referenced by redirect().
redirect() [1/2]
void express::Response::redirect (const std::string & loc)
Definition at line 50 of file Response.cpp.
{
         redirect(302, loc);
     }
redirect() [2/2]
void express::Response::redirect (int state, const std::string & loc)
Definition at line 54 of file Response.cpp.
{
         location(loc);
         sendStatus(state);
     }
References location(), and sendStatus().
sendStatus()
void express::Response::sendStatus (int state)
Definition at line 59 of file Response.cpp.
{
         this->status(state).send(web::http::StatusCode::reason(state));
     }
References web::http::StatusCode::reason(), web::http::server::Response::send(), and web::http::server::Response::status().
Referenced by express::RootRoute::dispatch(), and redirect().
vary()
Response & express::Response::vary (const std::string & field)
Definition at line 73 of file Response.cpp.
{
         append("Vary", field);
         return *this;
     }
References web::http::server::Response::append().
The documentation for this class was generated from the following files:
express/Response.h
express/Response.cpp