snode.c: core::socket::stream::SocketWriter< SocketT > Class Template Reference
core::socket::stream::SocketWriter< SocketT > Class Template Reference abstract
#include <SocketWriter.h>
Protected Types
using Socket = SocketT
Protected Member Functions
SocketWriter (const std::function< void(int)> &onError, const utils::Timeval &timeout, std::size_t blockSize, const utils::Timeval &terminateTimeout)
~SocketWriter () override=default
void setBlockSize (std::size_t writeBlockSize)
virtual void doWriteShutdown (const std::function< void(int)> &onShutdown)
void sendToPeer (const char *junk, std::size_t junkLen)
void doWrite ()
void shutdown (const std::function< void(int)> &onShutdown)
void terminate () override
Protected Member Functions inherited from core::eventreceiver::WriteEventReceiver
WriteEventReceiver (const std::string &name, const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::DescriptorEventReceiver
DescriptorEventReceiver (const std::string &name, DescriptorEventPublisher &descriptorEventPublisher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
int getRegisteredFd ()
void enable (int fd)
void disable ()
void suspend ()
void resume ()
bool isEnabled () const
bool isSuspended () const
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Protected Member Functions inherited from core::Observer
virtual ~Observer ()=default
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Protected Member Functions inherited from core::EventReceiver
EventReceiver (const std::string &name)
virtual ~EventReceiver ()=default
void publish ()
void unPublish ()
const std::string & getName ()
Private Member Functions
SocketWriter ()=delete
virtual ssize_t write (const char *junk, std::size_t junkLen)=0
void writeEvent () override=0
Private Attributes
std::function< void(int)> onError
std::function< void(int)> onShutdown
std::vector< char > writeBuffer
std::size_t blockSize
bool markShutdown = false
bool shutdownInProgress = false
bool terminateInProgress = false
utils::Timeval terminateTimeout
Additional Inherited Members
Protected Attributes inherited from core::EventReceiver
Event _event
Detailed Description
template<typename SocketT>
class core::socket::stream::SocketWriter< SocketT >
Definition at line 39 of file SocketWriter.h.
Member Typedef Documentation
Socket
template<typename SocketT > using core::socket::stream::SocketWriter< SocketT >::Socket = SocketT protected
Definition at line 45 of file SocketWriter.h.
Constructor & Destructor Documentation
SocketWriter() [1/2]
template<typename SocketT > core::socket::stream::SocketWriter< SocketT >::SocketWriter () private delete
SocketWriter() [2/2]
template<typename SocketT > core::socket::stream::SocketWriter< SocketT >::SocketWriter (const std::function< void(int)> & onError, const utils::Timeval & timeout, std::size_t blockSize, const utils::Timeval & terminateTimeout) inline explicit protected
Definition at line 47 of file SocketWriter.h.
             : core::eventreceiver::WriteEventReceiver("SocketWriter")
             , onError(onError)
             , terminateTimeout(terminateTimeout) {
             setBlockSize(blockSize);
             setTimeout(timeout);
         }
References core::socket::stream::SocketWriter< SocketT >::blockSize, core::socket::stream::SocketWriter< SocketT >::setBlockSize(), and core::DescriptorEventReceiver::setTimeout().
~SocketWriter()
template<typename SocketT > core::socket::stream::SocketWriter< SocketT >::~SocketWriter () override protected default
Member Function Documentation
doWrite()
template<typename SocketT > void core::socket::stream::SocketWriter< SocketT >::doWrite () inline protected
Definition at line 88 of file SocketWriter.h.
{
             errno = 0;
             if (!writeBuffer.empty()) {
                 std::size_t writeLen = (writeBuffer.size() < blockSize) ? writeBuffer.size() : blockSize;
                 ssize_t retWrite = write(writeBuffer.data(), writeLen);
                 int tempErrno = errno;
                 errno = tempErrno;
                 if (retWrite > 0) {
                     writeBuffer.erase(writeBuffer.begin(), writeBuffer.begin() + retWrite);
                     if (!isSuspended()) {
                         suspend();
                     }
                     if (!writeBuffer.empty()) {
                         if (writeBuffer.capacity() > writeBuffer.size() * 2) {
                             writeBuffer.shrink_to_fit();
                         }
                         publish();
                     } else {
                         writeBuffer.shrink_to_fit();
                         if (markShutdown) {
                             shutdown(onShutdown);
                         }
                     }
                 } else if (errno == EAGAIN || errno == EWOULDBLOCK || errno == EINTR) {
                     if (isSuspended()) {
                         resume();
                     }
                 } else {
                     disable();
                     onError(errno);
                 }
             } else if (!isSuspended()) {
                 suspend();
             }
         }
References core::socket::stream::SocketWriter< SocketT >::blockSize, core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::isSuspended(), core::socket::stream::SocketWriter< SocketT >::markShutdown, core::socket::stream::SocketWriter< SocketT >::onError, core::socket::stream::SocketWriter< SocketT >::onShutdown, core::EventReceiver::publish(), core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter< SocketT >::shutdown(), core::DescriptorEventReceiver::suspend(), core::socket::stream::SocketWriter< SocketT >::write(), and core::socket::stream::SocketWriter< SocketT >::writeBuffer.
Referenced by core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::writeEvent().
doWriteShutdown()
template<typename SocketT > virtual void core::socket::stream::SocketWriter< SocketT >::doWriteShutdown (const std::function< void(int)> & onShutdown) inline protected virtual
Definition at line 70 of file SocketWriter.h.
{
             errno = 0;
             Socket::shutdown(Socket::SHUT::WR);
             onShutdown(errno);
         }
References core::socket::stream::SocketWriter< SocketT >::onShutdown, and core::socket::Socket::shutdown().
Referenced by core::socket::stream::tls::SocketConnection< SocketT >::doReadShutdown(), core::socket::stream::tls::SocketConnection< SocketT >::doWriteShutdown(), and core::socket::stream::SocketWriter< SocketT >::shutdown().
sendToPeer()
template<typename SocketT > void core::socket::stream::SocketWriter< SocketT >::sendToPeer (const char * junk, std::size_t junkLen) inline protected
Definition at line 78 of file SocketWriter.h.
{
             if (!shutdownInProgress && !markShutdown) {
                 if (writeBuffer.empty()) {
                     resume();
                 }
                 writeBuffer.insert(writeBuffer.end(), junk, junk + junkLen);
             }
         }
References core::socket::stream::SocketWriter< SocketT >::markShutdown, core::DescriptorEventReceiver::resume(), core::socket::stream::SocketWriter< SocketT >::shutdownInProgress, and core::socket::stream::SocketWriter< SocketT >::writeBuffer.
Referenced by core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::sendToPeer().
setBlockSize()
template<typename SocketT > void core::socket::stream::SocketWriter< SocketT >::setBlockSize (std::size_t writeBlockSize) inline protected
Definition at line 66 of file SocketWriter.h.
{
             this->blockSize = writeBlockSize;
         }
References core::socket::stream::SocketWriter< SocketT >::blockSize.
Referenced by core::socket::stream::SocketWriter< SocketT >::SocketWriter().
shutdown()
template<typename SocketT > void core::socket::stream::SocketWriter< SocketT >::shutdown (const std::function< void(int)> & onShutdown) inline protected
Definition at line 128 of file SocketWriter.h.
{
             if (!shutdownInProgress) {
                 this->onShutdown = onShutdown;
                 if (writeBuffer.empty()) {
                     shutdownInProgress = true;
                     doWriteShutdown(onShutdown);
                 } else {
                     markShutdown = true;
                 }
             }
         }
References core::socket::stream::SocketWriter< SocketT >::doWriteShutdown(), core::socket::stream::SocketWriter< SocketT >::markShutdown, core::socket::stream::SocketWriter< SocketT >::onShutdown, core::socket::stream::SocketWriter< SocketT >::shutdownInProgress, and core::socket::stream::SocketWriter< SocketT >::writeBuffer.
Referenced by core::socket::stream::SocketWriter< SocketT >::doWrite(), core::socket::stream::SocketConnection< SocketT, SocketReaderT, SocketWriterT >::shutdownWrite(), and core::socket::stream::SocketWriter< SocketT >::terminate().
terminate()
template<typename SocketT > void core::socket::stream::SocketWriter< SocketT >::terminate () inline override protected virtual
Reimplemented from core::DescriptorEventReceiver.
Definition at line 140 of file SocketWriter.h.
{
             if (!terminateInProgress) {
                 setTimeout(terminateTimeout);
                 shutdown([this]([[maybe_unused]] int errnum) -> void {
                     if (errnum != 0) {
                         PLOG(INFO) << "SocketWriter::doWriteShutdown";
                     }
                     disable();
                 });
                 terminateInProgress = true;
             }
         }
References core::DescriptorEventReceiver::disable(), core::DescriptorEventReceiver::setTimeout(), core::socket::stream::SocketWriter< SocketT >::shutdown(), core::socket::stream::SocketWriter< SocketT >::terminateInProgress, and core::socket::stream::SocketWriter< SocketT >::terminateTimeout.
write()
template<typename SocketT > virtual ssize_t core::socket::stream::SocketWriter< SocketT >::write (const char * junk, std::size_t junkLen) private pure virtual
Implemented in core::socket::stream::tls::SocketWriter< SocketT >, and core::socket::stream::legacy::SocketWriter< SocketT >.
Referenced by core::socket::stream::SocketWriter< SocketT >::doWrite().
writeEvent()
template<typename SocketT > void core::socket::stream::SocketWriter< SocketT >::writeEvent () override private pure virtual
Implements core::eventreceiver::WriteEventReceiver.
Member Data Documentation
blockSize
template<typename SocketT > std::size_t core::socket::stream::SocketWriter< SocketT >::blockSize private
Definition at line 158 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::doWrite(), core::socket::stream::SocketWriter< SocketT >::setBlockSize(), and core::socket::stream::SocketWriter< SocketT >::SocketWriter().
markShutdown
template<typename SocketT > bool core::socket::stream::SocketWriter< SocketT >::markShutdown = false private
Definition at line 160 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::doWrite(), core::socket::stream::SocketWriter< SocketT >::sendToPeer(), and core::socket::stream::SocketWriter< SocketT >::shutdown().
onError
template<typename SocketT > std::function<void(int)> core::socket::stream::SocketWriter< SocketT >::onError private
Definition at line 154 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::doWrite().
onShutdown
template<typename SocketT > std::function<void(int)> core::socket::stream::SocketWriter< SocketT >::onShutdown private
Definition at line 155 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::doWrite(), core::socket::stream::SocketWriter< SocketT >::doWriteShutdown(), and core::socket::stream::SocketWriter< SocketT >::shutdown().
shutdownInProgress
template<typename SocketT > bool core::socket::stream::SocketWriter< SocketT >::shutdownInProgress = false private
Definition at line 161 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::sendToPeer(), and core::socket::stream::SocketWriter< SocketT >::shutdown().
terminateInProgress
template<typename SocketT > bool core::socket::stream::SocketWriter< SocketT >::terminateInProgress = false private
Definition at line 162 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::terminate().
terminateTimeout
template<typename SocketT > utils::Timeval core::socket::stream::SocketWriter< SocketT >::terminateTimeout private
Definition at line 164 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::terminate().
writeBuffer
template<typename SocketT > std::vector<char> core::socket::stream::SocketWriter< SocketT >::writeBuffer private
Definition at line 157 of file SocketWriter.h.
Referenced by core::socket::stream::SocketWriter< SocketT >::doWrite(), core::socket::stream::SocketWriter< SocketT >::sendToPeer(), and core::socket::stream::SocketWriter< SocketT >::shutdown().
The documentation for this class was generated from the following file:
core/socket/stream/SocketWriter.h