snode.c: CLI::Error Class Reference
CLI::Error Class Reference
Errors
All errors derive from this one.
#include <CLI11.hpp>
Public Member Functions
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Private Attributes
int actual_exit_code
std::string error_name {"Error"}
Detailed Description
All errors derive from this one.
Definition at line 607 of file CLI11.hpp.
Constructor & Destructor Documentation
Error() [1/2]
CLI::Error::Error (std::string name, std::string msg, int exit_code = static_cast<int>(ExitCodes::BaseClass)) inline
Definition at line 620 of file CLI11.hpp.
             : runtime_error(msg)
             , actual_exit_code(exit_code)
             , error_name(std::move(name)) {
         }
Error() [2/2]
CLI::Error::Error (std::string name, std::string msg, ExitCodes exit_code) inline
Definition at line 626 of file CLI11.hpp.
             : Error(name, msg, static_cast<int>(exit_code)) {
         }
Member Function Documentation
get_exit_code()
int CLI::Error::get_exit_code () const inline
Definition at line 612 of file CLI11.hpp.
{
             return actual_exit_code;
         }
References actual_exit_code.
Referenced by CLI::App::exit().
get_name()
std::string CLI::Error::get_name () const inline
Definition at line 616 of file CLI11.hpp.
{
             return error_name;
         }
References error_name.
Referenced by CLI::Option::_reduce_results(), CLI::Option::_validate_results(), CLI::App::count_all(), CLI::App::exit(), CLI::FailureMessage::help(), CLI::App::help(), CLI::Option::results(), and CLI::Option::run_callback().
Member Data Documentation
actual_exit_code
int CLI::Error::actual_exit_code private
Definition at line 608 of file CLI11.hpp.
Referenced by get_exit_code().
error_name
std::string CLI::Error::error_name {"Error"} private
Definition at line 609 of file CLI11.hpp.
Referenced by get_name().
The documentation for this class was generated from the following file:
utils/CLI11.hpp