snode.c: CLI::ArgumentMismatch Class Reference
CLI::ArgumentMismatch Class Reference
Errors
Thrown when the wrong number of arguments has been received.
#include <CLI11.hpp>
Public Member Functions
ArgumentMismatch (std::string msg, ExitCodes exit_code)
ArgumentMismatch (std::string msg, int exit_code)
ArgumentMismatch (std::string msg)
ArgumentMismatch (std::string name, int expected, std::size_t received)
Public Member Functions inherited from CLI::ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from CLI::Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static ArgumentMismatch AtLeast (std::string name, int num, std::size_t received)
static ArgumentMismatch AtMost (std::string name, int num, std::size_t received)
static ArgumentMismatch TypedAtLeast (std::string name, int num, std::string type)
static ArgumentMismatch FlagOverride (std::string name)
Protected Member Functions
ArgumentMismatch (std::string ename, std::string msg, int exit_code)
ArgumentMismatch (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from CLI::ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when the wrong number of arguments has been received.
Definition at line 818 of file CLI11.hpp.
Constructor & Destructor Documentation
ArgumentMismatch() [1/6]
CLI::ArgumentMismatch::ArgumentMismatch (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 819 of file CLI11.hpp.
Referenced by AtLeast(), AtMost(), FlagOverride(), and TypedAtLeast().
ArgumentMismatch() [2/6]
CLI::ArgumentMismatch::ArgumentMismatch (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 819 of file CLI11.hpp.
ArgumentMismatch() [3/6]
CLI::ArgumentMismatch::ArgumentMismatch (std::string msg, ExitCodes exit_code) inline
Definition at line 819 of file CLI11.hpp.
ArgumentMismatch() [4/6]
CLI::ArgumentMismatch::ArgumentMismatch (std::string msg, int exit_code) inline
Definition at line 819 of file CLI11.hpp.
ArgumentMismatch() [5/6]
CLI::ArgumentMismatch::ArgumentMismatch (std::string msg) inline explicit
Definition at line 820 of file CLI11.hpp.
ArgumentMismatch() [6/6]
CLI::ArgumentMismatch::ArgumentMismatch (std::string name, int expected, std::size_t received) inline
Definition at line 821 of file CLI11.hpp.
             : ArgumentMismatch(
                   expected > 0
                       ? ("Expected exactly " + std::to_string(expected) + " arguments to " + name + ", got " + std::to_string(received))
                       : ("Expected at least " + std::to_string(-expected) + " arguments to " + name + ", got " + std::to_string(received)),
                   ExitCodes::ArgumentMismatch) {
         }
Member Function Documentation
AtLeast()
static ArgumentMismatch CLI::ArgumentMismatch::AtLeast (std::string name, int num, std::size_t received) inline static
Definition at line 829 of file CLI11.hpp.
{
             return ArgumentMismatch(name + ": At least " + std::to_string(num) + " required but received " + std::to_string(received));
         }
References ArgumentMismatch(), and CLI::detail::to_string().
Referenced by CLI::Option::_reduce_results().
AtMost()
static ArgumentMismatch CLI::ArgumentMismatch::AtMost (std::string name, int num, std::size_t received) inline static
Definition at line 832 of file CLI11.hpp.
{
             return ArgumentMismatch(name + ": At Most " + std::to_string(num) + " required but received " + std::to_string(received));
         }
References ArgumentMismatch(), and CLI::detail::to_string().
Referenced by CLI::Option::_reduce_results().
FlagOverride()
static ArgumentMismatch CLI::ArgumentMismatch::FlagOverride (std::string name) inline static
Definition at line 838 of file CLI11.hpp.
{
             return ArgumentMismatch(name + " was given a disallowed flag override");
         }
References ArgumentMismatch().
Referenced by CLI::Option::get_flag_value().
TypedAtLeast()
static ArgumentMismatch CLI::ArgumentMismatch::TypedAtLeast (std::string name, int num, std::string type) inline static
Definition at line 835 of file CLI11.hpp.
{
             return ArgumentMismatch(name + ": " + std::to_string(num) + " required " + type + " missing");
         }
References ArgumentMismatch(), and CLI::detail::to_string().
Referenced by CLI::App::_parse_arg().
The documentation for this class was generated from the following file:
utils/CLI11.hpp