snode.c: core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT > Class Template Reference
core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT > Class Template Reference
#include <SocketConnectionT.h>
Public Types
using SocketReader = SocketReaderT
using SocketWriter = SocketWriterT
using SocketAddress = SocketAddressT
Public Member Functions
const SocketAddress & getRemoteAddress () const
const SocketAddress & getLocalAddress () const
std::string getLocalAddressAsString () const override
std::string getRemoteAddressAsString () const override
ssize_t readFromPeer (char *junk, std::size_t junkLen) override
void sendToPeer (const char *junk, std::size_t junkLen) override
void sendToPeer (const std::string &data) override
void close () final
void setTimeout (int timeout) override
SocketContext * switchSocketContext (SocketContextFactory *socketContextFactory) override
Public Member Functions inherited from core::socket::stream::SocketConnection
SocketContext * getSocketContext ()
Protected Member Functions
SocketConnectionT (const std::shared_ptr< SocketContextFactory > &socketContextFactory, const SocketAddress &localAddress, const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void()> &onDisconnect)
virtual ~SocketConnectionT ()
Protected Member Functions inherited from core::socket::stream::SocketConnection
SocketConnection (const std::shared_ptr< SocketContextFactory > &socketContextFactory)
virtual ~SocketConnection ()=default
Private Member Functions
SocketConnectionT ()=delete
void readEvent () override
void writeEvent () override
void unobservedEvent () override
Private Attributes
SocketAddress localAddress {}
SocketAddress remoteAddress {}
SocketContext * newSocketContext = nullptr
std::function< void()> onDisconnect
Additional Inherited Members
Protected Attributes inherited from core::socket::stream::SocketConnection
SocketContext * socketContext = nullptr
friend SocketContext
Detailed Description
template<typename SocketReaderT, typename SocketWriterT, typename SocketAddressT>
class core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >
Definition at line 38 of file SocketConnectionT.h.
Member Typedef Documentation
SocketAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketAddress = SocketAddressT
Definition at line 47 of file SocketConnectionT.h.
SocketReader
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketReader = SocketReaderT
Definition at line 45 of file SocketConnectionT.h.
SocketWriter
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > using core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketWriter = SocketWriterT
Definition at line 46 of file SocketConnectionT.h.
Constructor & Destructor Documentation
SocketConnectionT() [1/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketConnectionT () private delete
SocketConnectionT() [2/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::SocketConnectionT (const std::shared_ptr< SocketContextFactory > & socketContextFactory, const SocketAddress & localAddress, const SocketAddress & remoteAddress, const std::function< void(const SocketAddress &, const SocketAddress &)> & onConnect, const std::function< void()> & onDisconnect) inline protected
Definition at line 50 of file SocketConnectionT.h.
             : SocketConnection(socketContextFactory)
             , SocketReader([this](int errnum) -> void {
                 if (SocketWriter::isEnabled()) {
                     SocketWriter::disable();
                 }
                 socketContext->onReadError(errnum);
             })
             , SocketWriter([this](int errnum) -> void {
                 if (SocketReader::isEnabled()) {
                     SocketReader::disable();
                 }
                 socketContext->onWriteError(errnum);
             })
             , localAddress(localAddress)
             , remoteAddress(remoteAddress)
             , onDisconnect(onDisconnect) {
             SocketReader::enable(SocketConnectionT::getFd());
             SocketWriter::enable(SocketConnectionT::getFd());
             SocketReader::suspend();
             SocketWriter::suspend();
             onConnect(localAddress, remoteAddress);
             socketContext->onConnected();
         }
References core::EventReceiver::disable().
~SocketConnectionT()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > virtual core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::~SocketConnectionT () inline protected virtual
Definition at line 79 of file SocketConnectionT.h.
{
             socketContext->onDisconnected();
             onDisconnect();
             delete socketContext;
         }
Member Function Documentation
close()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::close () inline final virtual
Implements core::socket::stream::SocketConnection.
Definition at line 126 of file SocketConnectionT.h.
{
             SocketWriter::shutdown();
         }
References core::socket::stream::SocketWriter< SocketT >::shutdown().
getLocalAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > const SocketAddress& core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getLocalAddress () const inline
Definition at line 90 of file SocketConnectionT.h.
{
             return localAddress;
         }
getLocalAddressAsString()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::string core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getLocalAddressAsString () const inline override virtual
Implements core::socket::stream::SocketConnection.
Definition at line 94 of file SocketConnectionT.h.
{
             return localAddress.toString();
         }
getRemoteAddress()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > const SocketAddress& core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getRemoteAddress () const inline
Definition at line 86 of file SocketConnectionT.h.
{
             return remoteAddress;
         }
getRemoteAddressAsString()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::string core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::getRemoteAddressAsString () const inline override virtual
Implements core::socket::stream::SocketConnection.
Definition at line 98 of file SocketConnectionT.h.
{
             return remoteAddress.toString();
         }
readEvent()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::readEvent () inline override private
Definition at line 146 of file SocketConnectionT.h.
{
             socketContext->onReceiveFromPeer();
             if (newSocketContext != nullptr) { // Perform a pending SocketContextSwitch
                 socketContext->onDisconnected();
                 delete socketContext;
                 socketContext = newSocketContext;
                 newSocketContext = nullptr;
                 socketContext->onConnected();
             }
         }
readFromPeer()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > ssize_t core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::readFromPeer (char * junk, std::size_t junkLen) inline override virtual
Implements core::socket::stream::SocketConnection.
Definition at line 102 of file SocketConnectionT.h.
{
             ssize_t ret = 0;
             if (newSocketContext == nullptr) {
                 ret = SocketReader::readFromPeer(junk, junkLen);
             } else {
                 VLOG(0) << "ReadFromPeer: OldSocketContext != nullptr: SocketContextSwitch in progress";
             }
             return ret;
         }
References core::socket::stream::SocketReader< SocketT >::readFromPeer().
sendToPeer() [1/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::sendToPeer (const char * junk, std::size_t junkLen) inline override virtual
Implements core::socket::stream::SocketConnection.
Definition at line 114 of file SocketConnectionT.h.
{
             if (newSocketContext == nullptr) {
                 SocketWriter::sendToPeer(junk, junkLen);
             } else {
                 VLOG(0) << "SendToPeer: OldSocketContext != nullptr: SocketContextSwitch in progress";
             }
         }
References core::socket::stream::SocketWriter< SocketT >::sendToPeer().
sendToPeer() [2/2]
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::sendToPeer (const std::string & data) inline override virtual
Implements core::socket::stream::SocketConnection.
Definition at line 122 of file SocketConnectionT.h.
{
             sendToPeer(data.data(), data.size());
         }
setTimeout()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::setTimeout (int timeout) inline override virtual
Implements core::socket::stream::SocketConnection.
Definition at line 130 of file SocketConnectionT.h.
{
             SocketReader::setTimeout(timeout);
             SocketWriter::setTimeout(timeout);
         }
References core::EventReceiver::setTimeout().
switchSocketContext()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketContext* core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::switchSocketContext (SocketContextFactory * socketContextFactory) inline override virtual
Implements core::socket::stream::SocketConnection.
Definition at line 135 of file SocketConnectionT.h.
{
             newSocketContext = socketContextFactory->create(this);
             if (newSocketContext == nullptr) {
                 VLOG(0) << "Switch socket context unsuccessull: new socket context not created";
             }
             return newSocketContext;
         }
References core::socket::stream::SocketContextFactory::create().
unobservedEvent()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::unobservedEvent () inline override private
Definition at line 162 of file SocketConnectionT.h.
{
             delete this;
         }
writeEvent()
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > void core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::writeEvent () inline override private
Definition at line 158 of file SocketConnectionT.h.
{
             SocketWriter::doWrite();
         }
References core::socket::stream::SocketWriter< SocketT >::doWrite().
Member Data Documentation
localAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketAddress core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::localAddress {} private
Definition at line 166 of file SocketConnectionT.h.
newSocketContext
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketContext* core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::newSocketContext = nullptr private
Definition at line 169 of file SocketConnectionT.h.
onDisconnect
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > std::function<void()> core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::onDisconnect private
Definition at line 171 of file SocketConnectionT.h.
remoteAddress
template<typename SocketReaderT , typename SocketWriterT , typename SocketAddressT > SocketAddress core::socket::stream::SocketConnectionT< SocketReaderT, SocketWriterT, SocketAddressT >::remoteAddress {} private
Definition at line 167 of file SocketConnectionT.h.
The documentation for this class was generated from the following file:
core/socket/stream/SocketConnectionT.h