snode.c: utils::Daemon Class Reference
utils::Daemon Class Reference
#include <Daemon.h>
Public Member Functions
Daemon ()=delete
~Daemon ()=delete
Static Public Member Functions
static void daemonize (const std::string &pidFileName)
static void kill (const std::string &pidFileName)
static void erasePidFile (const std::string &pidFileName)
Static Private Member Functions
static long pidfd_open (pid_t pid, unsigned int flags)
static int waitForDaemonToExit (pid_t pid)
Static Private Attributes
static bool daemonized = false
Detailed Description
Definition at line 31 of file Daemon.h.
Constructor & Destructor Documentation
Daemon()
utils::Daemon::Daemon () delete
~Daemon()
utils::Daemon::~Daemon () delete
Member Function Documentation
daemonize()
void utils::Daemon::daemonize (const std::string & pidFileName) static
Definition at line 50 of file Daemon.cpp.
{
         if (!std::filesystem::exists(pidFileName)) {
             pid_t pid = 0;
             /* Fork off the parent process */
             pid = fork();
             /* An error occurred */
             if (pid < 0) {
                 exit(EXIT_FAILURE);
             }
             /* Success: Let the parent terminate */
             if (pid > 0) {
                 exit(EXIT_SUCCESS);
             }
             /* On success: The child process becomes session leader */
             if (setsid() < 0) {
                 exit(EXIT_FAILURE);
             }
             /* Ignore signal sent from child to parent process */
             signal(SIGCHLD, SIG_IGN);
             /* Fork off for the second time*/
             pid = fork();
             /* An error occurred */
             if (pid < 0) {
                 exit(EXIT_FAILURE);
             }
             /* Success: Let the parent terminate */
             if (pid > 0) {
                 exit(EXIT_SUCCESS);
             }
             /* Set new file permissions */
             umask(0);
             /* Change the working directory to the root directory */
             /* or another appropriated directory */
             chdir("/");
             /* Close all open file descriptors */
             for (long fd = sysconf(_SC_OPEN_MAX); fd >= 0; fd--) {
                 close(static_cast<int>(fd));
             }
             /* Reopen stdin (fd = 0), stdout (fd = 1), stderr (fd = 2) */
             if (std::freopen("/dev/null", "r", stdin) == nullptr) {
             }
             if (std::freopen("/dev/null", "w+", stdout) == nullptr) {
             }
             if (std::freopen("/dev/null", "w+", stderr) == nullptr) {
             }
             /* Try to write PID of daemon to lockfile */
             if (!pidFileName.empty()) {
                 std::ofstream pidFile(pidFileName, std::ofstream::out);
                 if (pidFile.good()) {
                     pidFile << getpid() << std::endl;
                     pidFile.close();
                 } else {
                     exit(EXIT_FAILURE);
                 }
             }
             daemonized = true;
         } else {
             VLOG(0) << "Already running: Not daemonized ... exiting";
             daemonized = false;
         }
     }
References core::system::close(), daemonized, and core::system::signal().
Referenced by utils::Config::init().
erasePidFile()
void utils::Daemon::erasePidFile (const std::string & pidFileName) static
Definition at line 175 of file Daemon.cpp.
{
         if (daemonized) {
             std::remove(pidFileName.data());
         }
     }
References daemonized.
Referenced by utils::Config::terminate().
kill()
void utils::Daemon::kill (const std::string & pidFileName) static
Definition at line 126 of file Daemon.cpp.
{
         /* Try to read PID of daemon to from lockfile and kill the daemon */
         if (!pidFileName.empty()) {
             std::ifstream pidFile(pidFileName, std::ifstream::in);
             if (pidFile.good()) {
                 int pid;
                 pidFile >> pid;
                 struct pollfd pollfd;
                 int pidfd = static_cast<int>(pidfd_open(pid, 0));
                 if (pidfd == -1) {
                     VLOG(0) << "Daemon not running";
                     exit(EXIT_FAILURE);
                 }
                 if (::kill(pid, SIGTERM) == 0) {
                     pidFile.close();
                     pollfd.fd = pidfd;
                     pollfd.events = POLLIN;
                     int ready = poll(&pollfd, 1, -1);
                     if (ready == -1) {
                         PLOG(ERROR) << "Poll";
                         exit(EXIT_FAILURE);
                     } else if (ready == 0) {
                         PLOG(ERROR) << "Daemon not responding";
                         exit(EXIT_FAILURE);
                     } else {
                         VLOG(0) << "Daemon terminated";
                     }
                     close(pidfd);
                     exit(EXIT_SUCCESS);
                 } else {
                     PLOG(ERROR) << "Kill daemon";
                     exit(EXIT_FAILURE);
                 }
             } else {
                 VLOG(0) << "Daemon not running";
                 exit(EXIT_FAILURE);
             }
         }
     }
References core::system::close(), pidfd_open(), and core::system::poll().
Referenced by utils::Config::init().
pidfd_open()
long utils::Daemon::pidfd_open (pid_t pid, unsigned int flags) static private
Definition at line 46 of file Daemon.cpp.
{
         return syscall(__NR_pidfd_open, pid, flags);
     }
References __NR_pidfd_open.
Referenced by kill().
waitForDaemonToExit()
static int utils::Daemon::waitForDaemonToExit (pid_t pid) static private
Member Data Documentation
daemonized
bool utils::Daemon::daemonized = false static private
Definition at line 44 of file Daemon.h.
Referenced by daemonize(), and erasePidFile().
The documentation for this class was generated from the following files:
utils/Daemon.h
utils/Daemon.cpp