snode.c: net::socket::ip::tcp::SocketServer< ConcreteSocketServer > Class Template Reference
net::socket::ip::tcp::SocketServer< ConcreteSocketServer > Class Template Reference
#include <SocketServer.h>
Public Types
using SocketAddress = typename ConcreteSocketServer::SocketAddress
Public Member Functions
void listen (uint16_t port, int backlog, const std::function< void(int)> &onError)
void listen (const std::string &ipOrHostname, int backlog, const std::function< void(int)> &onError)
void listen (const std::string &ipOrHostname, uint16_t port, int backlog, const std::function< void(int)> &onError)
Detailed Description
template<typename ConcreteSocketServer>
class net::socket::ip::tcp::SocketServer< ConcreteSocketServer >
Definition at line 33 of file SocketServer.h.
Member Typedef Documentation
SocketAddress
template<typename ConcreteSocketServer > using net::socket::ip::tcp::SocketServer< ConcreteSocketServer >::SocketAddress = typename ConcreteSocketServer::SocketAddress
Definition at line 37 of file SocketServer.h.
Member Function Documentation
listen() [1/3]
template<typename ConcreteSocketServer > void net::socket::ip::tcp::SocketServer< ConcreteSocketServer >::listen (const std::string & ipOrHostname, int backlog, const std::function< void(int)> & onError) inline
Definition at line 45 of file SocketServer.h.
{
             listen(SocketAddress(ipOrHostname), backlog, onError);
         }
References net::socket::ip::tcp::SocketServer< ConcreteSocketServer >::listen().
listen() [2/3]
template<typename ConcreteSocketServer > void net::socket::ip::tcp::SocketServer< ConcreteSocketServer >::listen (const std::string & ipOrHostname, uint16_t port, int backlog, const std::function< void(int)> & onError) inline
Definition at line 49 of file SocketServer.h.
{
             listen(SocketAddress(ipOrHostname, port), backlog, onError);
         }
References net::socket::ip::tcp::SocketServer< ConcreteSocketServer >::listen().
listen() [3/3]
template<typename ConcreteSocketServer > void net::socket::ip::tcp::SocketServer< ConcreteSocketServer >::listen (uint16_t port, int backlog, const std::function< void(int)> & onError) inline
Definition at line 41 of file SocketServer.h.
{
             listen(SocketAddress(port), backlog, onError);
         }
Referenced by net::socket::ip::tcp::SocketServer< ConcreteSocketServer >::listen(), web::http::server::legacy::Server< Request, Response >::listen(), web::http::server::tls::Server< Request, Response >::listen(), and web::http::server::tls::Server6< Request, Response >::listen().
The documentation for this class was generated from the following file:
net/socket/ip/tcp/SocketServer.h