snode.c: web::http::server::tls::Server< Request, Response > Class Template Reference
web::http::server::tls::Server< Request, Response > Class Template Reference
#include <Server.h>
Public Member Functions
void addSniCert (const std::string &domain, const std::map< std::string, std::any > &options)
void listen (uint16_t port, const std::function< void(int)> &onError)
void listen (const std::string &ipOrHostname, const std::function< void(int)> &onError)
void listen (const std::string &ipOrHostname, uint16_t port, const std::function< void(int)> &onError)
Public Member Functions inherited from web::http::server::Server< net::in::stream::tls::SocketServer, Request, Response >
Server (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(Request &, Response &)> &onRequestReady, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void listen (const SocketAddress &socketAddress, const std::function< void(int)> &onError)
Public Member Functions inherited from core::socket::stream::tls::SocketServer< ServerSocketT, SocketContextFactoryT >
SocketServer (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
void addSniCert (const std::string &domain, const std::map< std::string, std::any > &options)
Public Member Functions inherited from core::socket::stream::SocketServer< ServerSocketT, SocketAcceptor< ServerSocketT::Socket >, SocketContextFactoryT >
SocketServer (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect, const std::map< std::string, std::any > &options={{}})
virtual ~SocketServer ()=default
void listen (const SocketAddress &bindAddress, int backlog, const std::function< void(int)> &onError) const override
void onConnect (const std::function< void(const SocketAddress &, const SocketAddress &)> &onConnect)
void onConnected (const std::function< void(SocketConnection *)> &onConnected)
void onDisconnect (const std::function< void(SocketConnection *)> &onDisconnect)
std::shared_ptr< SocketContextFactory > getSocketContextFactory ()
Protected Types
using SocketServer = net::in::stream::tls::SocketServer< web::http::server::SocketContextFactory< Request, Response > >
Additional Inherited Members
Public Types inherited from web::http::server::Server< net::in::stream::tls::SocketServer, Request, Response >
using Request = Request
using Response = Response
using SocketServer = net::in::stream::tls::SocketServer< web::http::server::SocketContextFactory< Request, Response > >
using SocketConnection = typename SocketServer::SocketConnection
using SocketAddress = typename SocketConnection::SocketAddress
Public Types inherited from core::socket::stream::tls::SocketServer< ServerSocketT, SocketContextFactoryT >
using SocketConnection = typename SocketAcceptor< typename ServerSocketT::Socket >::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Public Types inherited from core::socket::stream::SocketServer< ServerSocketT, SocketAcceptor< ServerSocketT::Socket >, SocketContextFactoryT >
using SocketConnection = typename SocketAcceptor::SocketConnection
using SocketAddress = typename SocketConnection::Socket::SocketAddress
Protected Attributes inherited from core::socket::stream::SocketServer< ServerSocketT, SocketAcceptor< ServerSocketT::Socket >, SocketContextFactoryT >
std::shared_ptr< SocketContextFactory > socketContextFactory
std::function< void(const SocketAddress &, const SocketAddress &)> _onConnect
std::function< void(SocketConnection *)> _onConnected
std::function< void(SocketConnection *)> _onDisconnect
std::map< std::string, std::any > options
Detailed Description
template<typename Request, typename Response>
class web::http::server::tls::Server< Request, Response >
Definition at line 34 of file Server.h.
Member Typedef Documentation
SocketServer
template<typename Request , typename Response > using web::http::server::tls::Server< Request, Response >::SocketServer = net::in::stream::tls::SocketServer<web::http::server::SocketContextFactory<Request, Response> > protected
Definition at line 38 of file Server.h.
Member Function Documentation
addSniCert()
template<typename Request , typename Response > void web::http::server::tls::Server< Request, Response >::addSniCert (const std::string & domain, const std::map< std::string, std::any > & options) inline
Definition at line 43 of file Server.h.
{
             SocketServer::addSniCert(domain, options);
         }
References core::socket::stream::tls::SocketServer< ServerSocketT, SocketContextFactoryT >::addSniCert(), and core::socket::stream::SocketServer< ServerSocketT, SocketAcceptor< ServerSocketT::Socket >, SocketContextFactoryT >::options.
listen() [1/3]
template<typename Request , typename Response > void web::http::server::tls::Server< Request, Response >::listen (const std::string & ipOrHostname, const std::function< void(int)> & onError) inline
Definition at line 51 of file Server.h.
{
             SocketServer::listen(ipOrHostname, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, SocketAcceptor< ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
listen() [2/3]
template<typename Request , typename Response > void web::http::server::tls::Server< Request, Response >::listen (const std::string & ipOrHostname, uint16_t port, const std::function< void(int)> & onError) inline
Definition at line 55 of file Server.h.
{
             SocketServer::listen(ipOrHostname, port, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, SocketAcceptor< ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
listen() [3/3]
template<typename Request , typename Response > void web::http::server::tls::Server< Request, Response >::listen (uint16_t port, const std::function< void(int)> & onError) inline
Definition at line 47 of file Server.h.
{
             SocketServer::listen(port, LISTEN_BACKLOG, onError);
         }
References core::socket::stream::SocketServer< ServerSocketT, SocketAcceptor< ServerSocketT::Socket >, SocketContextFactoryT >::listen(), and LISTEN_BACKLOG.
The documentation for this class was generated from the following file:
web/http/server/tls/Server.h