snode.c: net::in::stream::ConfigBind Class Reference
net::in::stream::ConfigBind Class Reference
#include <ConfigBind.h>
Public Member Functions
ConfigBind (CLI::App *baseSc)
const std::string & getBindHost () const
uint16_t getBindPort () const
SocketAddress getBindAddress () const
Protected Member Functions
void required (bool req) const
Protected Attributes
CLI::App * bindSc = nullptr
CLI::Option * bindHostOpt = nullptr
CLI::Option * bindPortOpt = nullptr
Private Attributes
std::string bindHost = ""
uint16_t bindPort = 0
Detailed Description
Definition at line 38 of file ConfigBind.h.
Constructor & Destructor Documentation
ConfigBind()
net::in::stream::ConfigBind::ConfigBind (CLI::App * baseSc) explicit
Definition at line 31 of file ConfigBind.cpp.
{
         bindSc = baseSc->add_subcommand("bind");
         bindSc->description("Bind options");
         bindSc->configurable();
         bindHostOpt = bindSc->add_option("-a,--host", bindHost, "Host name or IP address");
         bindHostOpt->type_name("[hostname|ip]");
         bindHostOpt->default_val("0.0.0.0");
         bindHostOpt->configurable();
         bindPortOpt = bindSc->add_option("-p,--port", bindPort, "Port number");
         bindPortOpt->type_name("[uint16_t]");
         bindPortOpt->default_val(0);
         bindPortOpt->configurable();
     }
References CLI::App::add_option(), CLI::App::add_subcommand(), bindHost, bindHostOpt, bindPort, bindPortOpt, bindSc, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), CLI::App::description(), and CLI::Option::type_name().
Member Function Documentation
getBindAddress()
SocketAddress net::in::stream::ConfigBind::getBindAddress () const
Definition at line 55 of file ConfigBind.cpp.
{
         return SocketAddress(bindHost, bindPort);
     }
References bindHost, and bindPort.
getBindHost()
const std::string & net::in::stream::ConfigBind::getBindHost () const
Definition at line 47 of file ConfigBind.cpp.
{
         return bindHost;
     }
References bindHost.
getBindPort()
uint16_t net::in::stream::ConfigBind::getBindPort () const
Definition at line 51 of file ConfigBind.cpp.
{
         return bindPort;
     }
References bindPort.
required()
void net::in::stream::ConfigBind::required (bool req) const protected
Definition at line 59 of file ConfigBind.cpp.
{
         utils::Config::instance().required(bindSc, req);
         utils::Config::instance().required(bindPortOpt, req);
     }
References bindPortOpt, bindSc, utils::Config::instance(), and utils::Config::required().
Referenced by net::in::stream::ServerConfig::required().
Member Data Documentation
bindHost
std::string net::in::stream::ConfigBind::bindHost = "" private
Definition at line 56 of file ConfigBind.h.
Referenced by ConfigBind(), getBindAddress(), and getBindHost().
bindHostOpt
CLI::Option* net::in::stream::ConfigBind::bindHostOpt = nullptr protected
Definition at line 52 of file ConfigBind.h.
Referenced by ConfigBind().
bindPort
uint16_t net::in::stream::ConfigBind::bindPort = 0 private
Definition at line 57 of file ConfigBind.h.
Referenced by ConfigBind(), getBindAddress(), and getBindPort().
bindPortOpt
CLI::Option* net::in::stream::ConfigBind::bindPortOpt = nullptr protected
Definition at line 53 of file ConfigBind.h.
Referenced by ConfigBind(), and required().
bindSc
CLI::App* net::in::stream::ConfigBind::bindSc = nullptr protected
Definition at line 51 of file ConfigBind.h.
Referenced by ConfigBind(), and required().
The documentation for this class was generated from the following files:
net/in/stream/ConfigBind.h
net/in/stream/ConfigBind.cpp