snode.c: core::epoll::DescriptorEventPublisher Class Reference
core::epoll::DescriptorEventPublisher Class Reference
#include <DescriptorEventPublisher.h>
Classes
class EPollEvents
Public Member Functions
DescriptorEventPublisher (int &epfd, uint32_t events)
Public Member Functions inherited from core::DescriptorEventPublisher
virtual ~DescriptorEventPublisher ()=default
void publish (Event *event)
void enable (DescriptorEventReceiver *descriptorEventReceiver)
void disable (DescriptorEventReceiver *descriptorEventReceiver)
void suspend (DescriptorEventReceiver *descriptorEventReceiver)
void resume (DescriptorEventReceiver *descriptorEventReceiver)
void checkTimedOutEvents (const utils::Timeval &currentTime)
void unobserveDisabledEvents (const utils::Timeval &currentTime)
int getObservedEventReceiverCount () const
int getMaxFd () const
utils::Timeval getNextTimeout (const utils::Timeval &currentTime) const
void stop ()
Private Member Functions
DescriptorEventPublisher (const DescriptorEventPublisher &)=delete
DescriptorEventPublisher & operator= (const DescriptorEventPublisher &)=delete
void muxAdd (core::DescriptorEventReceiver *eventReceiver) override
void muxDel (int fd) override
void muxOn (core::DescriptorEventReceiver *eventReceiver) override
void muxOff (int fd) override
void dispatchActiveEvents () override
Private Attributes
EPollEvents ePollEvents
Additional Inherited Members
Protected Member Functions inherited from core::DescriptorEventPublisher
DescriptorEventPublisher ()=default
Protected Attributes inherited from core::DescriptorEventPublisher
std::map< int, std::list< DescriptorEventReceiver * > > observedEventReceivers
unsigned long eventCounter = 0
bool observedEventReceiversDirty = false
Detailed Description
Definition at line 39 of file DescriptorEventPublisher.h.
Constructor & Destructor Documentation
DescriptorEventPublisher() [1/2]
core::epoll::DescriptorEventPublisher::DescriptorEventPublisher (const DescriptorEventPublisher &) private delete
DescriptorEventPublisher() [2/2]
core::epoll::DescriptorEventPublisher::DescriptorEventPublisher (int & epfd, uint32_t events) explicit
Definition at line 95 of file DescriptorEventPublisher.cpp.
         : ePollEvents(epfd, events) {
     }
Member Function Documentation
dispatchActiveEvents()
void core::epoll::DescriptorEventPublisher::dispatchActiveEvents () override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 115 of file DescriptorEventPublisher.cpp.
{
         int count = core::system::epoll_wait(ePollEvents.getEPFd(), ePollEvents.getEvents(), ePollEvents.getInterestCount(), 0);
         for (int i = 0; i < count; i++) {
             core::DescriptorEventReceiver* eventReceiver = static_cast<core::DescriptorEventReceiver*>(ePollEvents.getEvents()[i].data.ptr);
             if (eventReceiver != nullptr) {
                 eventCounter++;
                 eventReceiver->publish();
             }
         }
     }
References core::system::epoll_wait(), ePollEvents, core::DescriptorEventPublisher::eventCounter, core::epoll::DescriptorEventPublisher::EPollEvents::getEPFd(), core::epoll::DescriptorEventPublisher::EPollEvents::getEvents(), core::epoll::DescriptorEventPublisher::EPollEvents::getInterestCount(), and core::EventReceiver::publish().
muxAdd()
void core::epoll::DescriptorEventPublisher::muxAdd (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 99 of file DescriptorEventPublisher.cpp.
{
         ePollEvents.muxAdd(eventReceiver);
     }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd().
muxDel()
void core::epoll::DescriptorEventPublisher::muxDel (int fd) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 103 of file DescriptorEventPublisher.cpp.
{
         ePollEvents.muxDel(fd);
     }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxDel().
muxOff()
void core::epoll::DescriptorEventPublisher::muxOff (int fd) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 111 of file DescriptorEventPublisher.cpp.
{
         ePollEvents.muxOff(fd);
     }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxOff().
muxOn()
void core::epoll::DescriptorEventPublisher::muxOn (core::DescriptorEventReceiver * eventReceiver) override private virtual
Implements core::DescriptorEventPublisher.
Definition at line 107 of file DescriptorEventPublisher.cpp.
{
         ePollEvents.muxOn(eventReceiver);
     }
References ePollEvents, and core::epoll::DescriptorEventPublisher::EPollEvents::muxOn().
operator=()
DescriptorEventPublisher& core::epoll::DescriptorEventPublisher::operator= (const DescriptorEventPublisher &) private delete
Member Data Documentation
ePollEvents
EPollEvents core::epoll::DescriptorEventPublisher::ePollEvents private
Definition at line 82 of file DescriptorEventPublisher.h.
Referenced by dispatchActiveEvents(), core::epoll::DescriptorEventPublisher::EPollEvents::getEvents(), core::epoll::DescriptorEventPublisher::EPollEvents::muxAdd(), muxAdd(), core::epoll::DescriptorEventPublisher::EPollEvents::muxDel(), muxDel(), muxOff(), and muxOn().
The documentation for this class was generated from the following files:
core/multiplexer/epoll/DescriptorEventPublisher.h
core/multiplexer/epoll/DescriptorEventPublisher.cpp