snode.c: utils::Timeval Class Reference
utils::Timeval Class Reference
#include <Timeval.h>
Public Member Functions
Timeval ()
Timeval (const std::initializer_list< time_t > &initList)
Timeval (const Timeval &timeVal)
Timeval (double time)
Timeval (const timeval &timeVal)
Timeval & operator= (const Timeval &timeVal)
Timeval & operator= (const std::initializer_list< time_t > &initList)
Timeval & operator= (const timeval &timeVal)
Timeval operator+ (const Timeval &timeVal) const
Timeval operator- (const Timeval &timeVal) const
Timeval & operator+= (const Timeval &timeVal)
Timeval & operator-= (const Timeval &timeVal)
Timeval operator- () const
bool operator< (const Timeval &timeVal) const
bool operator> (const Timeval &timeVal) const
bool operator<= (const Timeval &timeVal) const
bool operator>= (const Timeval &timeVal) const
bool operator== (const Timeval &timeVal) const
bool operator!= (const Timeval &timeVal) const
timeval * operator& ()
const timeval * operator& () const
int ms () const
double msd () const
Static Public Member Functions
static Timeval currentTime ()
Private Member Functions
const Timeval & normalize ()
Private Attributes
timeval timeVal = {0, 0}
Friends
std::ostream & operator<< (std::ostream &ostream, const utils::Timeval &timeVal)
Detailed Description
Definition at line 34 of file Timeval.h.
Constructor & Destructor Documentation
Timeval() [1/5]
utils::Timeval::Timeval ()
Definition at line 33 of file Timeval.cpp.
         : timeVal({0, 0}) {
     }
Timeval() [2/5]
utils::Timeval::Timeval (const std::initializer_list< time_t > & initList)
Definition at line 37 of file Timeval.cpp.
         : timeVal({0, 0}) {
         if (initList.size() == 2) {
             timeVal.tv_sec = *initList.begin();
             timeVal.tv_usec = static_cast<useconds_t>(*(initList.begin() + 1));
         } else {
             LOG(WARNING) << "Timeval initialized with an list size != 2. Initializing Timeval with 0";
         }
     }
Timeval() [3/5]
utils::Timeval::Timeval (const Timeval & timeVal)
Definition at line 47 of file Timeval.cpp.
{
         this->timeVal = timeVal.timeVal;
     }
References timeVal.
Timeval() [4/5]
utils::Timeval::Timeval (double time)
Definition at line 51 of file Timeval.cpp.
{
         timeVal.tv_sec = static_cast<time_t>(time);
         timeVal.tv_usec = static_cast<useconds_t>((time - static_cast<double>(timeVal.tv_sec)) * 1'000'000.0);
         normalize();
     }
References normalize(), core::system::time(), and timeVal.
Timeval() [5/5]
utils::Timeval::Timeval (const timeval & timeVal)
Definition at line 58 of file Timeval.cpp.
         : timeVal(timeVal) {
     }
Member Function Documentation
currentTime()
Timeval utils::Timeval::currentTime () static
Definition at line 62 of file Timeval.cpp.
{
         utils::Timeval currentTime;
         core::system::gettimeofday(&currentTime, nullptr);
         return currentTime;
     }
References core::system::gettimeofday().
Referenced by core::DescriptorEventReceiver::resume(), core::DescriptorEventReceiver::setTimeout(), and core::EventMultiplexer::tick().
ms()
int utils::Timeval::ms () const
Definition at line 161 of file Timeval.cpp.
{
         int ms = 0;
         if (timeVal.tv_sec > INT_MAX - 1) {
             ms = INT_MAX;
         } else {
             ms = static_cast<int>(static_cast<double>(timeVal.tv_sec) * 1'000. + static_cast<double>(timeVal.tv_usec) / 1'000. + 0.5);
         }
         return ms;
     }
References timeVal.
Referenced by core::epoll::EventMultiplexer::multiplex(), and core::poll::EventMultiplexer::multiplex().
msd()
double utils::Timeval::msd () const
Definition at line 173 of file Timeval.cpp.
{
         double msd = 0;
         if (timeVal.tv_sec > INT_MAX - 1) {
             msd = INT_MAX;
         } else {
             msd = static_cast<double>(timeVal.tv_sec) * 1'000. + static_cast<double>(timeVal.tv_usec) / 1'000.;
         }
         return msd;
     }
References timeVal.
normalize()
const Timeval & utils::Timeval::normalize () private
Definition at line 188 of file Timeval.cpp.
{
         if (timeVal.tv_usec > 999'999) {
             timeVal.tv_usec -= 1'000'000;
             timeVal.tv_sec++;
         } else if (timeVal.tv_usec < 0) {
             timeVal.tv_usec += 1'000'000;
             timeVal.tv_sec--;
         }
         return *this;
     }
References timeVal.
Referenced by operator+=(), operator-=(), and Timeval().
operator!=()
bool utils::Timeval::operator!= (const Timeval & timeVal) const
Definition at line 153 of file Timeval.cpp.
{
         return !(*this == timeVal);
     }
References timeVal.
operator&() [1/2]
timeval * utils::Timeval::operator& ()
Definition at line 157 of file Timeval.cpp.
{
         return &timeVal;
     }
References timeVal.
operator&() [2/2]
const timeval * utils::Timeval::operator& () const
Definition at line 184 of file Timeval.cpp.
{
         return &timeVal;
     }
References timeVal.
operator+()
Timeval utils::Timeval::operator+ (const Timeval & timeVal) const
Definition at line 95 of file Timeval.cpp.
{
         utils::Timeval help;
         help.timeVal.tv_sec = this->timeVal.tv_sec + timeVal.timeVal.tv_sec;
         help.timeVal.tv_usec = this->timeVal.tv_usec + timeVal.timeVal.tv_usec;
         return help.normalize();
     }
References CLI::FailureMessage::help(), and timeVal.
operator+=()
Timeval & utils::Timeval::operator+= (const Timeval & timeVal)
Definition at line 113 of file Timeval.cpp.
{
         *this = (*this + timeVal).normalize();
         return *this;
     }
References normalize(), and timeVal.
operator-() [1/2]
Timeval utils::Timeval::operator- () const
Definition at line 123 of file Timeval.cpp.
{
         Timeval timeVal;
         timeVal.timeVal.tv_sec = -this->timeVal.tv_sec;
         timeVal.timeVal.tv_usec = -this->timeVal.tv_usec;
         return timeVal.normalize();
     }
References timeVal.
operator-() [2/2]
Timeval utils::Timeval::operator- (const Timeval & timeVal) const
Definition at line 104 of file Timeval.cpp.
{
         utils::Timeval help;
         help.timeVal.tv_sec = this->timeVal.tv_sec - timeVal.timeVal.tv_sec;
         help.timeVal.tv_usec = this->timeVal.tv_usec - timeVal.timeVal.tv_usec;
         return help.normalize();
     }
References CLI::FailureMessage::help(), and timeVal.
operator-=()
Timeval & utils::Timeval::operator-= (const Timeval & timeVal)
Definition at line 118 of file Timeval.cpp.
{
         *this = (*this - timeVal).normalize();
         return *this;
     }
References normalize(), and timeVal.
operator<()
bool utils::Timeval::operator< (const Timeval & timeVal) const
Definition at line 132 of file Timeval.cpp.
{
         return (this->timeVal.tv_sec < timeVal.timeVal.tv_sec) ||
                ((this->timeVal.tv_sec == timeVal.timeVal.tv_sec) && (this->timeVal.tv_usec < timeVal.timeVal.tv_usec));
     }
References timeVal.
operator<=()
bool utils::Timeval::operator<= (const Timeval & timeVal) const
Definition at line 141 of file Timeval.cpp.
{
         return !(*this > timeVal);
     }
References timeVal.
operator=() [1/3]
Timeval & utils::Timeval::operator= (const std::initializer_list< time_t > & initList)
Definition at line 76 of file Timeval.cpp.
{
         if (initList.size() == 2) {
             timeVal.tv_sec = *initList.begin();
             timeVal.tv_usec = static_cast<useconds_t>(*(initList.begin() + 1));
         } else {
             this->timeVal.tv_sec = 0;
             this->timeVal.tv_usec = 0;
             LOG(WARNING) << "Timeval assigned with an list size != 2. Assigning Timeval with 0";
         }
         return *this;
     }
References timeVal.
operator=() [2/3]
Timeval & utils::Timeval::operator= (const Timeval & timeVal)
Definition at line 69 of file Timeval.cpp.
{
         this->timeVal.tv_sec = timeVal.timeVal.tv_sec;
         this->timeVal.tv_usec = timeVal.timeVal.tv_usec;
         return *this;
     }
References timeVal.
operator=() [3/3]
Timeval & utils::Timeval::operator= (const timeval & timeVal)
Definition at line 89 of file Timeval.cpp.
{
         this->timeVal = timeVal;
         return *this;
     }
References timeVal.
operator==()
bool utils::Timeval::operator== (const Timeval & timeVal) const
Definition at line 149 of file Timeval.cpp.
{
         return !(*this < timeVal) && !(*this > timeVal);
     }
References timeVal.
operator>()
bool utils::Timeval::operator> (const Timeval & timeVal) const
Definition at line 137 of file Timeval.cpp.
{
         return timeVal < *this;
     }
References timeVal.
operator>=()
bool utils::Timeval::operator>= (const Timeval & timeVal) const
Definition at line 145 of file Timeval.cpp.
{
         return !(*this < timeVal);
     }
References timeVal.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & ostream, const utils::Timeval & timeVal) friend
Definition at line 200 of file Timeval.cpp.
{
         return ostream << "{" + std::to_string(timeVal.timeVal.tv_sec) + ":" + std::to_string(timeVal.timeVal.tv_usec) + "}";
     }
Member Data Documentation
timeVal
timeval utils::Timeval::timeVal = {0, 0} private
Definition at line 72 of file Timeval.h.
Referenced by ms(), msd(), normalize(), operator!=(), operator&(), operator+(), operator+=(), operator-(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and Timeval().
The documentation for this class was generated from the following files:
utils/Timeval.h
utils/Timeval.cpp