snode.c: net::ConfigBacklog Class Reference
net::ConfigBacklog Class Reference
#include <ConfigBacklog.h>
Public Member Functions
ConfigBacklog (CLI::App *baseSc)
int getBacklog () const
void setBacklog (int backlog) const
Private Attributes
CLI::Option * backlogOpt = nullptr
int initBacklog
int backlog
bool initialized = false
Detailed Description
Definition at line 33 of file ConfigBacklog.h.
Constructor & Destructor Documentation
ConfigBacklog()
net::ConfigBacklog::ConfigBacklog (CLI::App * baseSc) explicit
Definition at line 31 of file ConfigBacklog.cpp.
{
         backlogOpt = baseSc->add_option("-b,--backlog", backlog, "Listen backlog");
         backlogOpt->type_name("[backlog]");
         backlogOpt->default_val(5);
         backlogOpt->take_first();
         backlogOpt->configurable();
     }
References CLI::App::add_option(), backlog, backlogOpt, CLI::OptionBase< CRTP >::configurable(), CLI::Option::default_val(), CLI::OptionBase< CRTP >::take_first(), and CLI::Option::type_name().
Member Function Documentation
getBacklog()
int net::ConfigBacklog::getBacklog () const
Definition at line 39 of file ConfigBacklog.cpp.
{
         int backlog = this->backlog;
         if (initialized) {
             backlog = this->initBacklog;
         }
         return backlog;
     }
References backlog, initBacklog, and initialized.
setBacklog()
void net::ConfigBacklog::setBacklog (int backlog) const
Definition at line 49 of file ConfigBacklog.cpp.
{
         this->initBacklog = backlog;
     }
References backlog, and initBacklog.
Member Data Documentation
backlog
int net::ConfigBacklog::backlog private
Definition at line 45 of file ConfigBacklog.h.
Referenced by ConfigBacklog(), getBacklog(), and setBacklog().
backlogOpt
CLI::Option* net::ConfigBacklog::backlogOpt = nullptr private
Definition at line 42 of file ConfigBacklog.h.
Referenced by ConfigBacklog().
initBacklog
int net::ConfigBacklog::initBacklog mutable private
Definition at line 44 of file ConfigBacklog.h.
Referenced by getBacklog(), and setBacklog().
initialized
bool net::ConfigBacklog::initialized = false mutable private
Definition at line 46 of file ConfigBacklog.h.
Referenced by getBacklog().
The documentation for this class was generated from the following files:
net/ConfigBacklog.h
net/ConfigBacklog.cpp