snode.c: CLI::ConversionError Class Reference
CLI::ConversionError Class Reference
Errors
Thrown when conversion call back fails, such as when an int fails to coerce to a string.
#include <CLI11.hpp>
Public Member Functions
ConversionError (std::string msg, ExitCodes exit_code)
ConversionError (std::string msg, int exit_code)
ConversionError (std::string msg)
ConversionError (std::string member, std::string name)
ConversionError (std::string name, std::vector< std::string > results)
Public Member Functions inherited from CLI::ParseError
ParseError (std::string msg, ExitCodes exit_code)
ParseError (std::string msg, int exit_code)
Public Member Functions inherited from CLI::Error
int get_exit_code () const
std::string get_name () const
Error (std::string name, std::string msg, int exit_code=static_cast< int >(ExitCodes::BaseClass))
Error (std::string name, std::string msg, ExitCodes exit_code)
Static Public Member Functions
static ConversionError TooManyInputsFlag (std::string name)
static ConversionError TrueFalse (std::string name)
Protected Member Functions
ConversionError (std::string ename, std::string msg, int exit_code)
ConversionError (std::string ename, std::string msg, ExitCodes exit_code)
Protected Member Functions inherited from CLI::ParseError
ParseError (std::string ename, std::string msg, int exit_code)
ParseError (std::string ename, std::string msg, ExitCodes exit_code)
Detailed Description
Thrown when conversion call back fails, such as when an int fails to coerce to a string.
Definition at line 776 of file CLI11.hpp.
Constructor & Destructor Documentation
ConversionError() [1/7]
CLI::ConversionError::ConversionError (std::string ename, std::string msg, int exit_code) inline protected
Definition at line 777 of file CLI11.hpp.
Referenced by TooManyInputsFlag(), and TrueFalse().
ConversionError() [2/7]
CLI::ConversionError::ConversionError (std::string ename, std::string msg, ExitCodes exit_code) inline protected
Definition at line 777 of file CLI11.hpp.
ConversionError() [3/7]
CLI::ConversionError::ConversionError (std::string msg, ExitCodes exit_code) inline
Definition at line 777 of file CLI11.hpp.
ConversionError() [4/7]
CLI::ConversionError::ConversionError (std::string msg, int exit_code) inline
Definition at line 777 of file CLI11.hpp.
ConversionError() [5/7]
CLI::ConversionError::ConversionError (std::string msg) inline explicit
Definition at line 778 of file CLI11.hpp.
ConversionError() [6/7]
CLI::ConversionError::ConversionError (std::string member, std::string name) inline
Definition at line 779 of file CLI11.hpp.
             : ConversionError("The value " + member + " is not an allowed value for " + name) {
         }
ConversionError() [7/7]
CLI::ConversionError::ConversionError (std::string name, std::vector< std::string > results) inline
Definition at line 782 of file CLI11.hpp.
             : ConversionError("Could not convert: " + name + " = " + detail::join(results)) {
         }
Member Function Documentation
TooManyInputsFlag()
static ConversionError CLI::ConversionError::TooManyInputsFlag (std::string name) inline static
Definition at line 785 of file CLI11.hpp.
{
             return ConversionError(name + ": too many inputs for a flag");
         }
References ConversionError().
Referenced by CLI::Config::to_flag().
TrueFalse()
static ConversionError CLI::ConversionError::TrueFalse (std::string name) inline static
Definition at line 788 of file CLI11.hpp.
{
             return ConversionError(name + ": Should be true/false or a number");
         }
References ConversionError().
The documentation for this class was generated from the following file:
utils/CLI11.hpp