snode.c: web::http::client::Request Class Reference
web::http::client::Request Class Reference
#include <Request.h>
Public Member Functions
Request & setHost (const std::string &host)
Request & append (const std::string &field, const std::string &value)
Request & set (const std::string &field, const std::string &value, bool overwrite=false)
Request & set (const std::map< std::string, std::string > &headers, bool overwrite=false)
Request & cookie (const std::string &name, const std::string &value)
Request & cookie (const std::map< std::string, std::string > &cookies)
Request & type (const std::string &type)
void send (const char *junk, std::size_t junkLen)
void send (const std::string &junk)
void upgrade (const std::string &url, const std::string &protocol)
void sendHeader ()
void start ()
const std::string & header (const std::string &field)
Public Attributes
std::string method = "GET"
std::string url
std::string host
int httpMajor = 1
int httpMinor = 1
ConnectionState connectionState = ConnectionState::Default
Protected Member Functions
Request (web::http::SocketContext *clientContext)
void enqueue (const char *junk, std::size_t junkLen)
void enqueue (const std::string &data)
virtual void reset ()
Protected Attributes
bool sendHeaderInProgress = false
bool headersSent = false
std::size_t contentSent = 0
std::size_t contentLength = 0
web::http::SocketContext * socketContext
std::map< std::string, std::string > queries
std::map< std::string, std::string > headers
std::map< std::string, std::string > cookies
std::string nullstr = ""
Friends
template<typename Request , typename Response >
class SocketContext
Detailed Description
Definition at line 38 of file Request.h.
Constructor & Destructor Documentation
Request()
web::http::client::Request::Request (web::http::SocketContext * clientContext) explicit protected
Definition at line 33 of file Request.cpp.
         : socketContext(clientContext) {
     }
Member Function Documentation
append()
Request & web::http::client::Request::append (const std::string & field, const std::string & value)
Definition at line 43 of file Request.cpp.
{
         std::map<std::string, std::string>::iterator it = headers.find(field);
         if (it != headers.end()) {
             it->second += ", " + value;
         } else {
             set(field, value);
         }
         return *this;
     }
References headers, and set().
cookie() [1/2]
Request & web::http::client::Request::cookie (const std::map< std::string, std::string > & cookies)
Definition at line 87 of file Request.cpp.
{
         for (auto& [name, value] : cookies) {
             cookie(name, value);
         }
         return *this;
     }
References cookie(), and cookies.
cookie() [2/2]
Request & web::http::client::Request::cookie (const std::string & name, const std::string & value)
Definition at line 81 of file Request.cpp.
{
         cookies.insert({name, value});
         return *this;
     }
References cookies.
Referenced by cookie().
enqueue() [1/2]
void web::http::client::Request::enqueue (const char * junk, std::size_t junkLen) protected
Definition at line 117 of file Request.cpp.
{
         if (!headersSent && !sendHeaderInProgress) {
             sendHeaderInProgress = true;
             sendHeader();
             sendHeaderInProgress = false;
             headersSent = true;
         }
         socketContext->sendToPeer(junk, junkLen);
         if (headersSent) {
             contentSent += junkLen;
             if (contentSent == contentLength) {
                 socketContext->sendToPeerCompleted();
             } else if (contentSent > contentLength) {
                 socketContext->close();
             }
         }
     }
References core::socket::SocketContext::close(), contentLength, contentSent, headersSent, sendHeader(), sendHeaderInProgress, core::socket::SocketContext::sendToPeer(), web::http::SocketContext::sendToPeerCompleted(), and socketContext.
Referenced by enqueue(), send(), and sendHeader().
enqueue() [2/2]
void web::http::client::Request::enqueue (const std::string & data) protected
Definition at line 137 of file Request.cpp.
{
         enqueue(data.data(), data.size());
     }
References enqueue().
header()
const std::string & web::http::client::Request::header (const std::string & field)
Definition at line 225 of file Request.cpp.
{
         return headers[field];
     }
References headers.
Referenced by web::websocket::client::SocketContextUpgradeFactory::create().
reset()
void web::http::client::Request::reset () protected virtual
Definition at line 100 of file Request.cpp.
{
         method = "GET";
         url.clear();
         httpMajor = 1;
         httpMinor = 1;
         host.clear();
         queries.clear();
         headers.clear();
         cookies.clear();
         headersSent = false;
         sendHeaderInProgress = false;
         contentLength = 0;
         contentSent = 0;
         connectionState = ConnectionState::Default;
     }
References connectionState, contentLength, contentSent, cookies, web::http::Default, headers, headersSent, host, httpMajor, httpMinor, method, queries, sendHeaderInProgress, and url.
send() [1/2]
void web::http::client::Request::send (const char * junk, std::size_t junkLen)
Definition at line 183 of file Request.cpp.
{
         if (junkLen > 0) {
             headers.insert({"Content-Type", "application/octet-stream"});
         }
         headers.insert_or_assign("Content-Length", std::to_string(junkLen));
         enqueue(junk, junkLen);
     }
References enqueue(), headers, and CLI::detail::to_string().
Referenced by send(), and start().
send() [2/2]
void web::http::client::Request::send (const std::string & junk)
Definition at line 192 of file Request.cpp.
{
         if (junk.size() > 0) {
             headers.insert({"Content-Type", "text/html; charset=utf-8"});
         }
         send(junk.data(), junk.size());
     }
References headers, and send().
sendHeader()
void web::http::client::Request::sendHeader ()
Definition at line 141 of file Request.cpp.
{
         std::string httpVersion = "HTTP/" + std::to_string(httpMajor) + "." + std::to_string(httpMinor);
         std::string queryString = "";
         if (queries.size() > 0) {
             queryString += "?";
             for (auto& [key, value] : queries) {
                 queryString += httputils::url_encode(key) + "=" + httputils::url_encode(value) + "&";
             }
             queryString.pop_back();
         }
         enqueue(method + " " + url + queryString + " " + httpVersion + "\r\n");
         if (!host.empty()) {
             enqueue("Host: " + host + "\r\n");
         }
         enqueue("Date: " + httputils::to_http_date() + "\r\n");
         headers.insert({{"Cache-Control", "public, max-age=0"}, {"Accept-Ranges", "bytes"}, {"X-Powered-By", "snode.c"}});
         for (const auto& [field, value] : headers) { // cppcheck-suppress unassignedVariable
             enqueue(field + ":" + value + "\r\n");
         }
         if (contentLength != 0) {
             enqueue("Content-Length: " + std::to_string(contentLength) + "\r\n");
         }
         for (const auto& [name, value] : cookies) { // cppcheck-suppress unassignedVariable
             enqueue("Cookie:" + name + "=" + value + "\r\n");
         }
         enqueue("\r\n");
         if (headers.find("Content-Length") != headers.end()) {
             contentLength = std::stoul(headers.find("Content-Length")->second);
         } else {
             contentLength = 0;
         }
     }
References contentLength, cookies, enqueue(), headers, host, httpMajor, httpMinor, method, queries, httputils::to_http_date(), CLI::detail::to_string(), url, and httputils::url_encode().
Referenced by enqueue().
set() [1/2]
Request & web::http::client::Request::set (const std::map< std::string, std::string > & headers, bool overwrite = false)
Definition at line 55 of file Request.cpp.
{
         for (auto& [field, value] : headers) {
             set(field, value, overwrite);
         }
         return *this;
     }
References headers, and set().
set() [2/2]
Request & web::http::client::Request::set (const std::string & field, const std::string & value, bool overwrite = false)
Definition at line 63 of file Request.cpp.
{
         if (overwrite) {
             headers.insert_or_assign(field, value);
         } else {
             headers.insert({field, value});
         }
         if (field == "Content-Length") {
             contentLength = std::stoul(value);
         } else if (field == "Connection" && httputils::ci_contains(value, "close")) {
             connectionState = ConnectionState::Close;
         } else if (field == "Connection" && httputils::ci_contains(value, "keep-alive")) {
             connectionState = ConnectionState::Keep;
         }
         return *this;
     }
References httputils::ci_contains(), web::http::Close, connectionState, contentLength, headers, and web::http::Keep.
Referenced by append(), web::websocket::client::SocketContextUpgradeFactory::prepare(), set(), and upgrade().
setHost()
Request & web::http::client::Request::setHost (const std::string & host)
Definition at line 37 of file Request.cpp.
{
         this->host = host;
         return *this;
     }
References host.
start()
void web::http::client::Request::start ()
Definition at line 221 of file Request.cpp.
{
         send("");
     }
References send().
Referenced by upgrade().
type()
Request & web::http::client::Request::type (const std::string & type)
Definition at line 94 of file Request.cpp.
{
         headers.insert({"Content-Type", type});
         return *this;
     }
References headers.
upgrade()
void web::http::client::Request::upgrade (const std::string & url, const std::string & protocol)
Definition at line 199 of file Request.cpp.
{
         this->url = url;
         set("Connection", "Upgrade", true);
         set("Upgrade", protocol);
         // load upgrade context
         // let upgrade context fill the request-header fields
         // send the request to the server
         // the response-code needs to check the response from the server and upgrade the context in case the server says OK
         web::http::client::SocketContextUpgradeFactory* socketContextUpgradeFactory =
             web::http::client::SocketContextUpgradeFactorySelector::instance()->select(protocol, *this);
         if (socketContextUpgradeFactory != nullptr) {
             start();
             socketContextUpgradeFactory->checkRefCount();
         } else {
             socketContext->close();
         }
     }
References web::http::client::SocketContextUpgradeFactory::checkRefCount(), core::socket::SocketContext::close(), web::http::client::SocketContextUpgradeFactorySelector::instance(), web::http::client::SocketContextUpgradeFactorySelector::select(), set(), socketContext, start(), and url.
Friends And Related Function Documentation
SocketContext
template<typename Request , typename Response > friend class SocketContext friend
Definition at line 90 of file Request.h.
Member Data Documentation
connectionState
ConnectionState web::http::client::Request::connectionState = ConnectionState::Default
Definition at line 49 of file Request.h.
Referenced by reset(), and set().
contentLength
std::size_t web::http::client::Request::contentLength = 0 protected
Definition at line 77 of file Request.h.
Referenced by enqueue(), reset(), sendHeader(), and set().
contentSent
std::size_t web::http::client::Request::contentSent = 0 protected
Definition at line 76 of file Request.h.
Referenced by enqueue(), and reset().
cookies
std::map<std::string, std::string> web::http::client::Request::cookies protected
Definition at line 85 of file Request.h.
Referenced by cookie(), reset(), and sendHeader().
headers
std::map<std::string, std::string> web::http::client::Request::headers protected
Definition at line 84 of file Request.h.
Referenced by append(), header(), reset(), send(), sendHeader(), set(), and type().
headersSent
bool web::http::client::Request::headersSent = false protected
Definition at line 75 of file Request.h.
Referenced by enqueue(), and reset().
host
std::string web::http::client::Request::host
Definition at line 45 of file Request.h.
Referenced by reset(), sendHeader(), and setHost().
httpMajor
int web::http::client::Request::httpMajor = 1
Definition at line 46 of file Request.h.
Referenced by reset(), and sendHeader().
httpMinor
int web::http::client::Request::httpMinor = 1
Definition at line 47 of file Request.h.
Referenced by reset(), and sendHeader().
method
std::string web::http::client::Request::method = "GET"
Definition at line 43 of file Request.h.
Referenced by reset(), and sendHeader().
nullstr
std::string web::http::client::Request::nullstr = "" protected
Definition at line 87 of file Request.h.
queries
std::map<std::string, std::string> web::http::client::Request::queries protected
Definition at line 83 of file Request.h.
Referenced by reset(), and sendHeader().
sendHeaderInProgress
bool web::http::client::Request::sendHeaderInProgress = false protected
Definition at line 74 of file Request.h.
Referenced by enqueue(), and reset().
socketContext
web::http::SocketContext* web::http::client::Request::socketContext protected
Definition at line 79 of file Request.h.
Referenced by enqueue(), and upgrade().
url
std::string web::http::client::Request::url
Definition at line 44 of file Request.h.
Referenced by reset(), sendHeader(), and upgrade().
The documentation for this class was generated from the following files:
web/http/client/Request.h
web/http/client/Request.cpp