snode.c: net::config::ConfigBase Class Reference
net::config::ConfigBase Class Reference
#include <ConfigBase.h>
Public Member Functions
ConfigBase ()=default
ConfigBase (const std::string &name)
ConfigBase (const ConfigBase &)=delete
ConfigBase & operator= (const ConfigBase &)=delete
virtual ~ConfigBase ()=default
const std::string & getName () const
Protected Member Functions
CLI::App * add_subcommand (const std::string &name, const std::string &description="")
CLI::Option * add_option (const std::string &name, int &variable, const std::string &description)
void parse (bool forceError=false) const
Private Attributes
CLI::App * baseSc = nullptr
std::string name
Detailed Description
Definition at line 37 of file ConfigBase.h.
Constructor & Destructor Documentation
ConfigBase() [1/3]
net::config::ConfigBase::ConfigBase () default
ConfigBase() [2/3]
net::config::ConfigBase::ConfigBase (const std::string & name) explicit
Definition at line 30 of file ConfigBase.cpp.
         : name(name) {
         if (!name.empty()) {
             baseSc = utils::Config::add_subcommand(name, name + " configuration");
             baseSc->fallthrough();
             baseSc->required();
             baseSc->group("Instances");
         }
     }
References utils::Config::add_subcommand(), baseSc, CLI::App::fallthrough(), CLI::App::group(), name, and CLI::App::required().
ConfigBase() [3/3]
net::config::ConfigBase::ConfigBase (const ConfigBase &) delete
~ConfigBase()
virtual net::config::ConfigBase::~ConfigBase () virtual default
Member Function Documentation
add_option()
CLI::Option * net::config::ConfigBase::add_option (const std::string & name, int & variable, const std::string & description) protected
Definition at line 48 of file ConfigBase.cpp.
{
         return baseSc->add_option(name, variable, description);
     }
References CLI::App::add_option(), baseSc, and name.
Referenced by net::config::ConfigListen::ConfigListen().
add_subcommand()
CLI::App * net::config::ConfigBase::add_subcommand (const std::string & name, const std::string & description = "") protected
Definition at line 44 of file ConfigBase.cpp.
{
         return baseSc->add_subcommand(name, description);
     }
References CLI::App::add_subcommand(), baseSc, and name.
Referenced by net::config::ConfigConnection::ConfigConnection(), and net::config::ConfigTls::ConfigTls().
getName()
const std::string & net::config::ConfigBase::getName () const
Definition at line 40 of file ConfigBase.cpp.
{
         return name;
     }
References name.
Referenced by net::in::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::in6::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::l2::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::rf::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::un::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::in::stream::config::ConfigClientSocket::ConfigClientSocket(), net::in6::stream::config::ConfigClientSocket::ConfigClientSocket(), net::l2::stream::config::ConfigClientSocket::ConfigClientSocket(), net::rf::stream::config::ConfigClientSocket::ConfigClientSocket(), net::un::stream::config::ConfigClientSocket::ConfigClientSocket(), net::config::ConfigConnection::ConfigConnection(), net::config::ConfigListen::ConfigListen(), net::in::stream::config::ConfigServerSocket::ConfigServerSocket(), net::in6::stream::config::ConfigServerSocket::ConfigServerSocket(), net::l2::stream::config::ConfigServerSocket::ConfigServerSocket(), net::rf::stream::config::ConfigServerSocket::ConfigServerSocket(), net::un::stream::config::ConfigServerSocket::ConfigServerSocket(), and net::config::ConfigTls::ConfigTls().
operator=()
ConfigBase& net::config::ConfigBase::operator= (const ConfigBase &) delete
parse()
void net::config::ConfigBase::parse (bool forceError = false) const protected
Definition at line 52 of file ConfigBase.cpp.
{
         utils::Config::parse(forceError);
     }
References utils::Config::parse().
Member Data Documentation
baseSc
CLI::App* net::config::ConfigBase::baseSc = nullptr private
Definition at line 56 of file ConfigBase.h.
Referenced by add_option(), add_subcommand(), and ConfigBase().
name
std::string net::config::ConfigBase::name private
Definition at line 58 of file ConfigBase.h.
Referenced by add_option(), add_subcommand(), ConfigBase(), and getName().
The documentation for this class was generated from the following files:
net/config/ConfigBase.h
net/config/ConfigBase.cpp