snode.c: net::config::ConfigCluster Class Reference
net::config::ConfigCluster Class Reference
#include <ConfigCluster.h>
Public Types
enum MODE { NONE , PRIMARY , SECONDARY , PROXY }
Public Member Functions
ConfigCluster ()
int getClusterMode () const
Public Member Functions inherited from net::config::ConfigBase
ConfigBase ()=default
ConfigBase (const std::string &name)
ConfigBase (const ConfigBase &)=delete
ConfigBase & operator= (const ConfigBase &)=delete
virtual ~ConfigBase ()=default
const std::string & getName () const
Private Attributes
CLI::App * clusterSc = nullptr
CLI::Option * modeOpt = nullptr
MODE mode = MODE::NONE
Additional Inherited Members
Protected Member Functions inherited from net::config::ConfigBase
CLI::App * add_subcommand (const std::string &name, const std::string &description="")
CLI::Option * add_option (const std::string &name, int &variable, const std::string &description)
CLI::Option * add_flag (const std::string &name, const std::string &description="")
void parse (bool forceError=false) const
Detailed Description
Definition at line 35 of file ConfigCluster.h.
Member Enumeration Documentation
MODE
enum net::config::ConfigCluster::MODE
Enumerator
NONE
PRIMARY
SECONDARY
PROXY
Definition at line 39 of file ConfigCluster.h.
 { NONE, PRIMARY, SECONDARY, PROXY };
Constructor & Destructor Documentation
ConfigCluster()
net::config::ConfigCluster::ConfigCluster ()
Definition at line 31 of file ConfigCluster.cpp.
{
         if (!getName().empty()) {
             clusterSc = add_subcommand("cluster", "Options for clustering");
             clusterSc->group("Option groups");
             clusterSc->preparse_callback([this]([[maybe_unused]] std::size_t num) -> void {
                 mode = MODE::PRIMARY;
             });
             clusterSc->configurable(false);
             modeOpt = clusterSc->add_option("--mode", mode, "Clustering mode");
             modeOpt->type_name("[" + std::to_string(MODE::NONE) + " = NONE, " + std::to_string(MODE::PRIMARY) + " = PRIMARY, " +
                                std::to_string(MODE::SECONDARY) + " = SECONDARY, " + std::to_string(MODE::PROXY) + " = PROXY]");
             modeOpt->default_val(MODE::NONE);
             modeOpt->configurable(false);
         }
     }
References CLI::App::add_option(), net::config::ConfigBase::add_subcommand(), clusterSc, CLI::OptionBase< CRTP >::configurable(), CLI::App::configurable(), CLI::Option::default_val(), net::config::ConfigBase::getName(), CLI::App::group(), mode, modeOpt, CLI::App::preparse_callback(), CLI::detail::to_string(), and CLI::Option::type_name().
Member Function Documentation
getClusterMode()
int net::config::ConfigCluster::getClusterMode () const
Definition at line 48 of file ConfigCluster.cpp.
{
         return mode;
     }
References mode.
Member Data Documentation
clusterSc
CLI::App* net::config::ConfigCluster::clusterSc = nullptr private
Definition at line 44 of file ConfigCluster.h.
Referenced by ConfigCluster().
mode
MODE net::config::ConfigCluster::mode = MODE::NONE private
Definition at line 47 of file ConfigCluster.h.
Referenced by ConfigCluster(), and getClusterMode().
modeOpt
CLI::Option* net::config::ConfigCluster::modeOpt = nullptr private
Definition at line 45 of file ConfigCluster.h.
Referenced by ConfigCluster().
The documentation for this class was generated from the following files:
net/config/ConfigCluster.h
net/config/ConfigCluster.cpp