snode.c: core::epoll::EventMultiplexer Class Reference
core::epoll::EventMultiplexer Class Reference
#include <EventMultiplexer.h>
Public Member Functions
EventMultiplexer ()
~EventMultiplexer () override=default
Public Member Functions inherited from core::EventMultiplexer
DescriptorEventPublisher & getDescriptorEventPublisher (core::EventMultiplexer::DISP_TYPE dispType)
TimerEventPublisher & getTimerEventPublisher ()
void publish (core::Event *event)
void unPublish (core::Event *event)
TickStatus tick (const utils::Timeval &tickTimeOut)
void stop ()
Private Member Functions
EventMultiplexer (const EventMultiplexer &)=delete
EventMultiplexer & operator= (const EventMultiplexer &)=delete
int multiplex (utils::Timeval &tickTimeout) override
void publishActiveEvents () override
Private Attributes
int epfd
int epfds [3]
epoll_event ePollEvents [3]
Additional Inherited Members
Public Types inherited from core::EventMultiplexer
enum DISP_TYPE { RD = 0 , WR = 1 , EX = 2 }
Protected Member Functions inherited from core::EventMultiplexer
EventMultiplexer (DescriptorEventPublisher *const readDescriptorEventPublisher, DescriptorEventPublisher *const writeDescriptorEventPublisher, DescriptorEventPublisher *const exceptionDescriptorEventPublisher)
int getObservedEventReceiverCount ()
int getMaxFd ()
Protected Attributes inherited from core::EventMultiplexer
std::array< DescriptorEventPublisher *, 3 > descriptorEventPublishers
core::TimerEventPublisher *const timerEventPublisher
int activeEventCount = 0
Detailed Description
Definition at line 36 of file EventMultiplexer.h.
Constructor & Destructor Documentation
EventMultiplexer() [1/2]
core::epoll::EventMultiplexer::EventMultiplexer (const EventMultiplexer &) private delete
EventMultiplexer() [2/2]
core::epoll::EventMultiplexer::EventMultiplexer ()
Definition at line 37 of file EventMultiplexer.cpp.
         : core::EventMultiplexer(new core::epoll::DescriptorEventPublisher("READ", epfds[DISP_TYPE::RD], EPOLLIN),
                                  new core::epoll::DescriptorEventPublisher("WRITE", epfds[DISP_TYPE::WR], EPOLLOUT),
                                  new core::epoll::DescriptorEventPublisher("EXCEPT", epfds[DISP_TYPE::EX], EPOLLPRI)) {
         epfd = core::system::epoll_create1(EPOLL_CLOEXEC);
         epoll_event event;
         event.events = EPOLLIN;
         event.data.ptr = descriptorEventPublishers[DISP_TYPE::RD];
         core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[DISP_TYPE::RD], &event);
         event.data.ptr = descriptorEventPublishers[WR];
         core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[DISP_TYPE::WR], &event);
         event.data.ptr = descriptorEventPublishers[EX];
         core::system::epoll_ctl(epfd, EPOLL_CTL_ADD, epfds[DISP_TYPE::EX], &event);
     }
References core::EventMultiplexer::descriptorEventPublishers, epfd, epfds, core::system::epoll_create1(), core::system::epoll_ctl(), core::EventMultiplexer::EX, and core::EventMultiplexer::WR.
~EventMultiplexer()
core::epoll::EventMultiplexer::~EventMultiplexer () override virtual default
Reimplemented from core::EventMultiplexer.
Member Function Documentation
multiplex()
int core::epoll::EventMultiplexer::multiplex (utils::Timeval & tickTimeout) override private virtual
Implements core::EventMultiplexer.
Definition at line 56 of file EventMultiplexer.cpp.
{
         return core::system::epoll_wait(epfd, ePollEvents, 3, tickTimeout.ms());
     }
References epfd, core::system::epoll_wait(), ePollEvents, and utils::Timeval::ms().
operator=()
EventMultiplexer& core::epoll::EventMultiplexer::operator= (const EventMultiplexer &) private delete
publishActiveEvents()
void core::epoll::EventMultiplexer::publishActiveEvents () override private virtual
Implements core::EventMultiplexer.
Definition at line 60 of file EventMultiplexer.cpp.
{
         for (int i = 0; i < activeEventCount; i++) {
             if ((ePollEvents[i].events & EPOLLIN) != 0) {
                 static_cast<core::DescriptorEventPublisher*>(ePollEvents[i].data.ptr)->publishActiveEvents();
             }
         }
     }
References core::EventMultiplexer::activeEventCount, and ePollEvents.
Member Data Documentation
epfd
int core::epoll::EventMultiplexer::epfd private
Definition at line 48 of file EventMultiplexer.h.
Referenced by EventMultiplexer(), and multiplex().
epfds
int core::epoll::EventMultiplexer::epfds[3] private
Definition at line 50 of file EventMultiplexer.h.
Referenced by EventMultiplexer().
ePollEvents
epoll_event core::epoll::EventMultiplexer::ePollEvents[3] private
Definition at line 51 of file EventMultiplexer.h.
Referenced by multiplex(), and publishActiveEvents().
The documentation for this class was generated from the following files:
core/multiplexer/epoll/EventMultiplexer.h
core/multiplexer/epoll/EventMultiplexer.cpp