snode.c: core::ExceptionalConditionEventReceiver Class Reference
core::ExceptionalConditionEventReceiver Class Reference abstract
#include <ExceptionalConditionEventReceiver.h>
Protected Member Functions
ExceptionalConditionEventReceiver (const utils::Timeval &timeout=60)
Protected Member Functions inherited from core::EventReceiver
EventReceiver (DescriptorEventDispatcher &descriptorEventDispatcher, const utils::Timeval &timeout=TIMEOUT::DISABLE)
virtual ~EventReceiver ()=default
Private Member Functions
virtual void outOfBandEvent ()=0
virtual void outOfBandTimeout ()
void dispatchEvent () final
void timeoutEvent () final
bool continueImmediately () const final
virtual bool continueOutOfBandImmediately () const
Additional Inherited Members
Public Member Functions inherited from core::EventReceiver
int getRegisteredFd ()
void enable (int fd)
void disable ()
bool isEnabled () const
void suspend ()
void resume ()
bool isSuspended () const
void dispatch (const utils::Timeval &currentTime)
void triggered (const utils::Timeval &currentTime)
void disabled ()
virtual void terminate ()
void setTimeout (const utils::Timeval &timeout)
utils::Timeval getTimeout (const utils::Timeval &currentTime) const
void checkTimeout (const utils::Timeval &currentTime)
Public Member Functions inherited from core::Observer
bool isObserved ()
void observed ()
void unObserved ()
int getObservationCounter ()
virtual void unobservedEvent ()=0
Detailed Description
Definition at line 32 of file ExceptionalConditionEventReceiver.h.
Constructor & Destructor Documentation
ExceptionalConditionEventReceiver()
core::ExceptionalConditionEventReceiver::ExceptionalConditionEventReceiver (const utils::Timeval & timeout = 60) protected
Definition at line 30 of file ExceptionalConditionEventReceiver.cpp.
         : EventReceiver(EventLoop::getEventDispatcher().getDescriptorEventDispatcher(core::EventDispatcher::DISP_TYPE::EX), timeout) {
     }
Member Function Documentation
continueImmediately()
bool core::ExceptionalConditionEventReceiver::continueImmediately () const final private virtual
Implements core::EventReceiver.
Definition at line 50 of file ExceptionalConditionEventReceiver.cpp.
{
         return continueOutOfBandImmediately();
     }
References continueOutOfBandImmediately().
continueOutOfBandImmediately()
bool core::ExceptionalConditionEventReceiver::continueOutOfBandImmediately () const private virtual
Definition at line 38 of file ExceptionalConditionEventReceiver.cpp.
{
         return false;
     }
Referenced by continueImmediately().
dispatchEvent()
void core::ExceptionalConditionEventReceiver::dispatchEvent () final private virtual
Implements core::EventReceiver.
Definition at line 42 of file ExceptionalConditionEventReceiver.cpp.
{
         outOfBandEvent();
     }
References outOfBandEvent().
outOfBandEvent()
virtual void core::ExceptionalConditionEventReceiver::outOfBandEvent () private pure virtual
Referenced by dispatchEvent().
outOfBandTimeout()
void core::ExceptionalConditionEventReceiver::outOfBandTimeout () private virtual
Definition at line 34 of file ExceptionalConditionEventReceiver.cpp.
{
         disable();
     }
References core::EventReceiver::disable().
Referenced by timeoutEvent().
timeoutEvent()
void core::ExceptionalConditionEventReceiver::timeoutEvent () final private virtual
Implements core::EventReceiver.
Definition at line 46 of file ExceptionalConditionEventReceiver.cpp.
{
         outOfBandTimeout();
     }
References outOfBandTimeout().
The documentation for this class was generated from the following files:
core/ExceptionalConditionEventReceiver.h
core/ExceptionalConditionEventReceiver.cpp