snode.c: core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT > Class Template Reference
core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT > Class Template Reference
#include <SocketConnectionFactory.h>
Public Types
using Config = typename BaseSocket::Config
using SocketAddress = typename Socket::SocketAddress
Public Member Functions
SocketConnectionFactory (const std::shared_ptr< core::socket::SocketContextFactory > &socketContextFactory, const std::function< void(SocketConnection *)> &onConnect, const std::function< void(SocketConnection *)> &onConnected, const std::function< void(SocketConnection *)> &onDisconnect)
void create (Socket &socket, const std::shared_ptr< Config > &config)
Protected Types
using SocketConnection = SocketConnectionT
Protected Attributes
std::shared_ptr< core::socket::SocketContextFactory > socketContextFactory = nullptr
std::function< void(SocketConnection *)> onConnect
std::function< void(SocketConnection *)> onConnected
std::function< void(SocketConnection *)> onDisconnect
Private Types
using BaseSocket = BaseSocketT
using Socket = typename BaseSocket::Socket
Detailed Description
template<typename BaseSocketT, typename SocketConnectionT>
class core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >
Definition at line 40 of file SocketConnectionFactory.h.
Member Typedef Documentation
BaseSocket
template<typename BaseSocketT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::BaseSocket = BaseSocketT private
Definition at line 42 of file SocketConnectionFactory.h.
Config
template<typename BaseSocketT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::Config = typename BaseSocket::Config
Definition at line 59 of file SocketConnectionFactory.h.
Socket
template<typename BaseSocketT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::Socket = typename BaseSocket::Socket private
Definition at line 43 of file SocketConnectionFactory.h.
SocketAddress
template<typename BaseSocketT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::SocketAddress = typename Socket::SocketAddress
Definition at line 60 of file SocketConnectionFactory.h.
SocketConnection
template<typename BaseSocketT , typename SocketConnectionT > using core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::SocketConnection = SocketConnectionT protected
Definition at line 46 of file SocketConnectionFactory.h.
Constructor & Destructor Documentation
SocketConnectionFactory()
template<typename BaseSocketT , typename SocketConnectionT > core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::SocketConnectionFactory (const std::shared_ptr< core::socket::SocketContextFactory > & socketContextFactory, const std::function< void(SocketConnection *)> & onConnect, const std::function< void(SocketConnection *)> & onConnected, const std::function< void(SocketConnection *)> & onDisconnect) inline
Definition at line 49 of file SocketConnectionFactory.h.
             : socketContextFactory(socketContextFactory)
             , onConnect(onConnect)
             , onConnected(onConnected)
             , onDisconnect(onDisconnect) {
         }
Member Function Documentation
create()
template<typename BaseSocketT , typename SocketConnectionT > void core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::create (Socket & socket, const std::shared_ptr< Config > & config) inline
Definition at line 62 of file SocketConnectionFactory.h.
{
             if (socket.isValid()) {
                 socket.dontClose();
                 SocketAddress localAddress{};
                 SocketAddress remoteAddress{};
                 if (socket.getSockname(localAddress) == 0 && socket.getPeername(remoteAddress) == 0) {
                     onConnected(new SocketConnection(socket.getFd(),
                                                      socketContextFactory,
                                                      SocketAddress(localAddress),
                                                      SocketAddress(remoteAddress),
                                                      onConnect,
                                                      onDisconnect,
                                                      config->getReadTimeout(),
                                                      config->getWriteTimeout(),
                                                      config->getReadBlockSize(),
                                                      config->getWriteBlockSize(),
                                                      config->getTerminateTimeout()));
                 } else {
                     PLOG(ERROR) << "getsockname";
                 }
             }
         }
References core::ERROR, core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::onConnect, core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::onConnected, core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::onDisconnect, core::system::socket(), and core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::socketContextFactory.
Referenced by core::socket::stream::SocketAcceptor< SocketServerT, SocketConnectionT >::acceptEvent(), and core::socket::stream::SocketConnector< SocketClientT, SocketConnectionT >::connectEvent().
Member Data Documentation
onConnect
template<typename BaseSocketT , typename SocketConnectionT > std::function<void(SocketConnection*)> core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::onConnect protected
Definition at line 88 of file SocketConnectionFactory.h.
Referenced by core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::create().
onConnected
template<typename BaseSocketT , typename SocketConnectionT > std::function<void(SocketConnection*)> core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::onConnected protected
Definition at line 89 of file SocketConnectionFactory.h.
Referenced by core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::create().
onDisconnect
template<typename BaseSocketT , typename SocketConnectionT > std::function<void(SocketConnection*)> core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::onDisconnect protected
Definition at line 90 of file SocketConnectionFactory.h.
Referenced by core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::create().
socketContextFactory
template<typename BaseSocketT , typename SocketConnectionT > std::shared_ptr<core::socket::SocketContextFactory> core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::socketContextFactory = nullptr protected
Definition at line 86 of file SocketConnectionFactory.h.
Referenced by core::socket::stream::SocketConnectionFactory< BaseSocketT, SocketConnectionT >::create().
The documentation for this class was generated from the following file:
core/socket/stream/SocketConnectionFactory.h