snode.c: net::socket::ip::tcp::SocketClient< ConcreteSocketClient > Class Template Reference
net::socket::ip::tcp::SocketClient< ConcreteSocketClient > Class Template Reference
#include <SocketClient.h>
Public Types
using SocketAddress = typename ConcreteSocketClient::SocketAddress
Public Member Functions
void connect (const std::string &ipOrHostname, uint16_t port, const std::function< void(int)> &onError)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindIpOrHostname, const std::function< void(int)> &onError)
void connect (const std::string &ipOrHostname, uint16_t port, const std::string &bindIpOrHostname, uint16_t bindPort, const std::function< void(int)> &onError)
Detailed Description
template<typename ConcreteSocketClient>
class net::socket::ip::tcp::SocketClient< ConcreteSocketClient >
Definition at line 33 of file SocketClient.h.
Member Typedef Documentation
SocketAddress
template<typename ConcreteSocketClient > using net::socket::ip::tcp::SocketClient< ConcreteSocketClient >::SocketAddress = typename ConcreteSocketClient::SocketAddress
Definition at line 37 of file SocketClient.h.
Member Function Documentation
connect() [1/3]
template<typename ConcreteSocketClient > void net::socket::ip::tcp::SocketClient< ConcreteSocketClient >::connect (const std::string & ipOrHostname, uint16_t port, const std::function< void(int)> & onError) inline
Definition at line 41 of file SocketClient.h.
{
             connect(SocketAddress(ipOrHostname, port), onError);
         }
Referenced by web::http::client::legacy::Client< Request, Response >::connect(), web::http::client::legacy::Client6< Request, Response >::connect(), web::http::client::tls::Client< Request, Response >::connect(), web::http::client::tls::Client6< Request, Response >::connect(), and net::socket::ip::tcp::SocketClient< ConcreteSocketClient >::connect().
connect() [2/3]
template<typename ConcreteSocketClient > void net::socket::ip::tcp::SocketClient< ConcreteSocketClient >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindIpOrHostname, const std::function< void(int)> & onError) inline
Definition at line 45 of file SocketClient.h.
{
             connect(SocketAddress(ipOrHostname, port), bindIpOrHostname, onError);
         }
References net::socket::ip::tcp::SocketClient< ConcreteSocketClient >::connect().
connect() [3/3]
template<typename ConcreteSocketClient > void net::socket::ip::tcp::SocketClient< ConcreteSocketClient >::connect (const std::string & ipOrHostname, uint16_t port, const std::string & bindIpOrHostname, uint16_t bindPort, const std::function< void(int)> & onError) inline
Definition at line 52 of file SocketClient.h.
{
             connect(SocketAddress(ipOrHostname, port), SocketAddress(bindIpOrHostname, bindPort), onError);
         }
References net::socket::ip::tcp::SocketClient< ConcreteSocketClient >::connect().
The documentation for this class was generated from the following file:
net/socket/ip/tcp/SocketClient.h