snode.c: net::rc::stream::SocketClient< ConfigT > Class Template Reference
net::rc::stream::SocketClient< ConfigT > Class Template Reference
#include <SocketClient.h>
Public Member Functions
void connect (const std::string &address, uint8_t channel, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &localAddress, const std::function< void(const SocketAddress &, int)> &onError)
void connect (const std::string &address, uint8_t channel, const std::string &localAddress, uint8_t bindChannel, const std::function< void(const SocketAddress &, int)> &onError)
Public Member Functions inherited from net::stream::SocketClient< ConfigT, net::rc::stream::ClientSocket >
SocketClient ()=default
SocketClient (const SocketClient &)=default
virtual ~SocketClient ()=default
virtual void connect (const std::function< void(const SocketAddress &, int)> &onError) const=0
void connect (const SocketAddress &remoteAddress, const SocketAddress &localAddress, const std::function< void(const SocketAddress &, int)> &onError) const
void connect (const SocketAddress &remoteAddress, const std::function< void(const SocketAddress &, int)> &onError) const
Public Member Functions inherited from net::SocketConfig< ConfigT >
SocketConfig (const std::string &name)
SocketConfig (const SocketConfig &)=default
const Config & getConfig ()
Protected Member Functions
SocketClient (const std::string &name)
Private Types
using Super = net::stream::SocketClient< ConfigT, net::rc::stream::ClientSocket >
Additional Inherited Members
Public Types inherited from net::stream::SocketClient< ConfigT, net::rc::stream::ClientSocket >
using Config = ConfigT
using Socket = net::rc::stream::ClientSocket
using SocketAddress = typename Socket::SocketAddress
Public Types inherited from net::SocketConfig< ConfigT >
using Config = ConfigT
Protected Types inherited from net::stream::SocketClient< ConfigT, net::rc::stream::ClientSocket >
using Super = net::SocketConfig< ConfigT >
Protected Attributes inherited from net::SocketConfig< ConfigT >
std::shared_ptr< Config > config
Detailed Description
template<typename ConfigT>
class net::rc::stream::SocketClient< ConfigT >
Definition at line 36 of file SocketClient.h.
Member Typedef Documentation
Super
template<typename ConfigT > using net::rc::stream::SocketClient< ConfigT >::Super = net::stream::SocketClient<ConfigT, net::rc::stream::ClientSocket> private
Definition at line 38 of file SocketClient.h.
Constructor & Destructor Documentation
SocketClient()
template<typename Config > net::rc::stream::SocketClient< Config >::SocketClient (const std::string & name) explicit protected
Definition at line 29 of file SocketClient.hpp.
         : Super(name) {
     }
Member Function Documentation
connect() [1/3]
template<typename Config > void net::rc::stream::SocketClient< Config >::connect (const std::string & address, uint8_t channel, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 34 of file SocketClient.hpp.
{
         connect(SocketAddress(address, channel), onError);
     }
References core::system::connect().
connect() [2/3]
template<typename Config > void net::rc::stream::SocketClient< Config >::connect (const std::string & address, uint8_t channel, const std::string & localAddress, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 41 of file SocketClient.hpp.
{
         connect(SocketAddress(address, channel), SocketAddress(localAddress), onError);
     }
References core::system::connect().
connect() [3/3]
template<typename Config > void net::rc::stream::SocketClient< Config >::connect (const std::string & address, uint8_t channel, const std::string & localAddress, uint8_t bindChannel, const std::function< void(const SocketAddress &, int)> & onError)
Definition at line 49 of file SocketClient.hpp.
{
         connect(SocketAddress(address, channel), SocketAddress(localAddress, bindChannel), onError);
     }
References core::system::connect().
The documentation for this class was generated from the following files:
net/rc/stream/SocketClient.h
net/rc/stream/SocketClient.hpp