@startuml inline_umlgraph_1.svg
!include net/socket/stream/pu/SocketAcceptor.pu!0
@enduml
@startuml inline_umlgraph_2.svg
!include net/socket/stream/pu/SocketClient.pu
@enduml
@startuml inline_umlgraph_3.svg
!include web/http/server/pu/response_upgrade.pu
@enduml
