snode.c: core::socket::stream::tls Namespace Reference
core::socket::stream::tls Namespace Reference
Classes
class SocketAcceptor
class SocketClient
class SocketConnection
class SocketConnector
class SocketReader
class SocketServer
class SocketWriter
class TLSHandshake
class TLSShutdown
Functions
static int password_callback (char *buf, int size, int, void *u)
static int verify_callback (int preverify_ok, [[maybe_unused]] X509_STORE_CTX *ctx)
SSL_CTX * ssl_ctx_new (const std::map< std::string, std::any > &options, bool server)
void ssl_ctx_free (SSL_CTX *ctx)
void ssl_set_sni (SSL *ssl, std::map< std::string, std::any > &options)
void ssl_log (const std::string &message, int sslErr)
void ssl_log_error (const std::string &message)
void ssl_log_warning (const std::string &message)
void ssl_log_info (const std::string &message)
Function Documentation
password_callback()
static int core::socket::stream::tls::password_callback (char * buf, int size, int , void * u) static
Definition at line 43 of file ssl_utils.cpp.
{
         strncpy(buf, static_cast<char*>(u), static_cast<std::size_t>(size));
         buf[size - 1] = '\0';
         memset(u, 0, ::strlen(static_cast<char*>(u))); // garble Password
         free(u);
         return static_cast<int>(::strlen(buf));
     }
Referenced by ssl_ctx_new().
ssl_ctx_free()
void core::socket::stream::tls::ssl_ctx_free (SSL_CTX * ctx)
Definition at line 178 of file ssl_utils.cpp.
{
         if (ctx != nullptr) {
             SSL_CTX_free(ctx);
         }
     }
Referenced by core::socket::stream::tls::SocketServer< SocketServerT, SocketContextFactoryT >::freeSniCerts(), core::socket::stream::tls::SocketAcceptor< SocketServerT >::~SocketAcceptor(), and core::socket::stream::tls::SocketConnector< SocketClientT >::~SocketConnector().
ssl_ctx_new()
SSL_CTX * core::socket::stream::tls::ssl_ctx_new (const std::map< std::string, std::any > & options, bool server)
Definition at line 85 of file ssl_utils.cpp.
{
         static int sslSessionCtxId = 1;
         std::string certChain;
         std::string certChainKey;
         std::string password;
         std::string caFile;
         std::string caDir;
         bool useDefaultCaDir = false;
         for (const auto& [name, value] : options) { // cppcheck-suppress unassignedVariable
             if (name == "CertChain") {
                 certChain = std::any_cast<const char*>(value);
             } else if (name == "CertChainKey") {
                 certChainKey = std::any_cast<const char*>(value);
             } else if (name == "Password") {
                 password = std::any_cast<const char*>(value);
             } else if (name == "CaFile") {
                 caFile = std::any_cast<const char*>(value);
             } else if (name == "CaDir") {
                 caDir = std::any_cast<const char*>(value);
             } else if (name == "UseDefaultCaDir") {
                 useDefaultCaDir = std::any_cast<bool>(value);
             }
         }
         SSL_CTX* ctx = SSL_CTX_new(server ? TLS_server_method() : TLS_client_method());
         if (ctx != nullptr) {
 #if OPENSSL_VERSION_NUMBER >= 0x30000000L
             SSL_CTX_set_options(ctx, SSL_OP_IGNORE_UNEXPECTED_EOF);
 #endif
             SSL_CTX_set_read_ahead(ctx, 1);
             SSL_CTX_set_mode(ctx, SSL_MODE_ENABLE_PARTIAL_WRITE);
             SSL_CTX_set_mode(ctx, SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER);
             bool sslErr = false;
             if (server) {
                 SSL_CTX_set_session_id_context(ctx, reinterpret_cast<const unsigned char*>(&sslSessionCtxId), sizeof(sslSessionCtxId));
                 sslSessionCtxId++;
             }
             if (!caFile.empty() || !caDir.empty()) {
                 if (!SSL_CTX_load_verify_locations(
                         ctx, !caFile.empty() ? caFile.c_str() : nullptr, !caDir.empty() ? caDir.c_str() : nullptr)) {
                     ssl_log_error("Can not load CA file or non default CA directory");
                     sslErr = true;
                 }
             }
             if (!sslErr && useDefaultCaDir) {
                 if (!SSL_CTX_set_default_verify_paths(ctx)) {
                     ssl_log_error("Can not load default CA directory");
                     sslErr = true;
                 }
             }
             if (!sslErr) {
                 if (server && (useDefaultCaDir || !caFile.empty() || !caDir.empty())) {
                     SSL_CTX_set_verify_depth(ctx, 5);
                     SSL_CTX_set_verify(ctx, SSL_VERIFY_FLAGS, verify_callback);
                 }
                 if (!certChain.empty()) {
                     if (SSL_CTX_use_certificate_chain_file(ctx, certChain.c_str()) != 1) {
                         ssl_log_error("Can not load certificate chain");
                         sslErr = true;
                     } else if (!certChainKey.empty()) {
                         if (!password.empty()) {
                             SSL_CTX_set_default_passwd_cb(ctx, password_callback);
                             SSL_CTX_set_default_passwd_cb_userdata(ctx, ::strdup(password.c_str()));
                         }
                         if (SSL_CTX_use_PrivateKey_file(ctx, certChainKey.c_str(), SSL_FILETYPE_PEM) != 1) {
                             errno = EINVAL;
                             ssl_log_error("Can not load private key");
                             sslErr = true;
                         } else if (!SSL_CTX_check_private_key(ctx)) {
                             errno = EINVAL;
                             ssl_log_error("Private key not consistent with CA files");
                             sslErr = true;
                         }
                     }
                 }
             }
             if (sslErr) {
                 SSL_CTX_free(ctx);
                 ctx = nullptr;
             }
         } else {
             ssl_log_error("SSL CTX not created");
         }
         return ctx;
     }
References password_callback(), ssl_log_error(), SSL_VERIFY_FLAGS, and verify_callback().
Referenced by core::socket::stream::tls::SocketServer< SocketServerT, SocketContextFactoryT >::addSniCert().
ssl_log()
void core::socket::stream::tls::ssl_log (const std::string & message, int sslErr)
Definition at line 190 of file ssl_utils.cpp.
{
         int errnum = errno;
         switch (sslErr) {
             case SSL_ERROR_NONE:
                 [[fallthrough]];
             case SSL_ERROR_ZERO_RETURN:
                 ssl_log_info(message);
                 break;
             case SSL_ERROR_SYSCALL:
                 if (errno != 0) {
                     ssl_log_error(message);
                 } else {
                     ssl_log_info(message);
                 }
                 break;
             default:
                 ssl_log_warning(message);
                 break;
         }
         errno = errnum;
     }
References ssl_log_error(), ssl_log_info(), and ssl_log_warning().
Referenced by core::socket::stream::tls::SocketConnection< SocketT >::doWriteShutdown(), core::socket::stream::tls::SocketReader< SocketT >::read(), core::socket::stream::tls::SocketAcceptor< SocketServerT >::SocketAcceptor(), core::socket::stream::tls::SocketConnector< SocketClientT >::SocketConnector(), and core::socket::stream::tls::SocketWriter< SocketT >::write().
ssl_log_error()
void core::socket::stream::tls::ssl_log_error (const std::string & message)
Definition at line 212 of file ssl_utils.cpp.
{
         PLOG(ERROR) << message;
         unsigned long errorCode;
         while ((errorCode = ERR_get_error()) != 0) {
             LOG(ERROR) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
         }
     }
References core::ERROR.
Referenced by ssl_ctx_new(), and ssl_log().
ssl_log_info()
void core::socket::stream::tls::ssl_log_info (const std::string & message)
Definition at line 230 of file ssl_utils.cpp.
{
         PLOG(INFO) << message;
         unsigned long errorCode;
         while ((errorCode = ERR_get_error()) != 0) {
             LOG(INFO) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
         }
     }
Referenced by ssl_log().
ssl_log_warning()
void core::socket::stream::tls::ssl_log_warning (const std::string & message)
Definition at line 221 of file ssl_utils.cpp.
{
         LOG(WARNING) << message;
         unsigned long errorCode;
         while ((errorCode = ERR_get_error()) != 0) {
             LOG(WARNING) << "|-- with SSL " << ERR_error_string(errorCode, nullptr);
         }
     }
Referenced by ssl_log().
ssl_set_sni()
void core::socket::stream::tls::ssl_set_sni (SSL * ssl, std::map< std::string, std::any > & options)
Definition at line 184 of file ssl_utils.cpp.
{
         if (options.contains("SNI")) {
             SSL_set_tlsext_host_name(ssl, std::any_cast<const char*>(options["SNI"]));
         }
     }
Referenced by core::socket::stream::tls::SocketConnector< SocketClientT >::SocketConnector().
verify_callback()
static int core::socket::stream::tls::verify_callback (int preverify_ok, [[maybe_unused] ] X509_STORE_CTX * ctx) static
Definition at line 53 of file ssl_utils.cpp.
{
         char buf[256];
         X509* err_cert;
         int err = 0;
         int depth = 0;
         err_cert = X509_STORE_CTX_get_current_cert(ctx);
         err = X509_STORE_CTX_get_error(ctx);
         depth = X509_STORE_CTX_get_error_depth(ctx);
         X509_NAME_oneline(X509_get_subject_name(err_cert), buf, 256);
         if (!preverify_ok) {
             LOG(INFO) << "verify_error:num=" << err << ":" << X509_verify_cert_error_string(err) << ":depth=" << depth << ":" << buf;
         } else {
             LOG(INFO) << "depth=" << depth << ":" << buf;
         }
         /*
          * At this point, err contains the last verification error. We can use
          * it for something special
          */
         /*
                 if (!preverify_ok && (err == X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT)) {
                     X509_NAME_oneline(X509_get_issuer_name(err_cert), buf, 256);
                     printf("issuer= %s\n", buf);
                 }
         */
         return preverify_ok;
     }
Referenced by ssl_ctx_new().