snode.c: core Namespace Reference
core Namespace Reference
Namespaces
epoll
file
pipe
poll
select
socket
ssl
system
timer
Classes
class AcceptEventReceiver
class ConnectEventReceiver
class Descriptor
class DescriptorEventDispatcher
class DynamicLoader
class EventDispatcher
class EventLoop
class Observer
class EventReceiver
class ExceptionalConditionEventReceiver
class ReadEventReceiver
class SNodeC
class TimerEventDispatcher
class TimerEventReceiver
class WriteEventReceiver
Enumerations
enum class TickStatus { SUCCESS , NO_OBSERVER , ERROR }
Functions
enum Descriptor::FLAGS operator| (const enum Descriptor::FLAGS &f1, const enum Descriptor::FLAGS &f2)
enum Descriptor::FLAGS operator& (const enum Descriptor::FLAGS &f1, const enum Descriptor::FLAGS &f2)
int daemonize (std::string name, std::string path="", std::string outfile="", std::string errfile="", std::string infile="")
static std::string getTickCounterAsString (const el::LogMessage *)
Enumeration Type Documentation
TickStatus
enum core::TickStatus strong
Enumerator
SUCCESS
NO_OBSERVER
ERROR
Definition at line 28 of file TickStatus.h.
 { SUCCESS, NO_OBSERVER, ERROR };
Function Documentation
daemonize()
int core::daemonize (std::string name, std::string path = "", std::string outfile = "", std::string errfile = "", std::string infile = "")
Definition at line 58 of file EventLoop.cpp.
{
         if (path.empty()) {
             path = "/";
         }
         if (name.empty()) {
             name = "SNodeC daemon";
         }
         if (infile.empty()) {
             infile = "/dev/null";
         }
         if (outfile.empty()) {
             outfile = "/dev/null";
         }
         if (errfile.empty()) {
             errfile = "/dev/null";
         }
         // printf("%s %s %s %s\n",name,path,outfile,infile);
         pid_t child;
         // fork, detach from process group leader
         if ((child = fork()) < 0) { // failed fork
             VLOG(0) << "error: failed fork";
             exit(EXIT_FAILURE);
         }
         if (child > 0) { // parent
             exit(EXIT_SUCCESS);
         }
         if (setsid() < 0) { // failed to become session leader
             VLOG(0) << "error: failed setsid";
             exit(EXIT_FAILURE);
         }
         // catch/ignore signals
         signal(SIGCHLD, SIG_IGN);
         signal(SIGHUP, SIG_IGN);
         // fork second time
         if ((child = fork()) < 0) { // failed fork
             VLOG(0) << "error: failed fork";
             exit(EXIT_FAILURE);
         }
         if (child > 0) { // parent
             exit(EXIT_SUCCESS);
         }
         // new file permissions
         umask(0);
         // change to path directory
         chdir(path.c_str());
         // Close all open file descriptors
         long fd;
         for (fd = sysconf(_SC_OPEN_MAX); fd >= 0; --fd) {
             close(static_cast<int>(fd));
         }
         // reopen stdin, stdout, stderr
         stdin = fopen(infile.c_str(), "r");    // fd=0
         stdout = fopen(outfile.c_str(), "w+"); // fd=1
         stderr = fopen(errfile.c_str(), "w+"); // fd=2
         return (0);
     }
References core::system::close(), and core::system::signal().
Referenced by core::EventLoop::init().
getTickCounterAsString()
static std::string core::getTickCounterAsString (const el::LogMessage *) static
Definition at line 124 of file EventLoop.cpp.
{
         std::string tick = std::to_string(EventLoop::getTickCounter());
         if (tick.length() < 10) {
             tick.insert(0, 10 - tick.length(), '0');
         }
         return tick;
     }
References core::EventLoop::getTickCounter(), and CLI::detail::to_string().
Referenced by core::EventLoop::init().
operator&()
enum Descriptor::FLAGS core::operator& (const enum Descriptor::FLAGS & f1, const enum Descriptor::FLAGS & f2)
Definition at line 50 of file Descriptor.cpp.
{
         return static_cast<enum Descriptor::FLAGS>(static_cast<unsigned short>(f1) & static_cast<unsigned short>(f2));
     }
operator|()
enum Descriptor::FLAGS core::operator| (const enum Descriptor::FLAGS & f1, const enum Descriptor::FLAGS & f2)
Definition at line 50 of file Descriptor.cpp.
{
         return static_cast<enum Descriptor::FLAGS>(static_cast<unsigned short>(f1) | static_cast<unsigned short>(f2));
     }