snode.c: express::dispatcher Namespace Reference
express::dispatcher Namespace Reference
Classes
class ApplicationDispatcher
class MiddlewareDispatcher
class RouterDispatcher
Functions
const std::string path_concat (const std::vector< std::string > &stringvec)
const std::vector< std::string > explode (const std::string &s, char delim)
const std::regex & pathRegex ()
const std::smatch matchResult (const std::string &cpath)
bool hasResult (const std::string &cpath)
bool matchFunction (const std::string &cpath, const std::string &reqpath)
void setParams (const std::string &cpath, Request &req)
std::string path_concat (const std::string &first, const std::string &second)
bool checkForUrlMatch (const std::string &cpath, const std::string &reqpath)
Function Documentation
checkForUrlMatch()
bool express::dispatcher::checkForUrlMatch (const std::string & cpath, const std::string & reqpath)
Definition at line 148 of file regex_utils.cpp.
{
         bool hasRegex = hasResult(cpath);
         return (!hasRegex && cpath == reqpath) || (hasRegex && matchFunction(cpath, reqpath));
     }
References hasResult(), and matchFunction().
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), and express::dispatcher::MiddlewareDispatcher::dispatch().
explode()
const std::vector< std::string > express::dispatcher::explode (const std::string & s, char delim)
Definition at line 48 of file regex_utils.cpp.
{
         std::vector<std::string> result;
         std::istringstream iss(s);
         for (std::string token; std::getline(iss, token, delim);) {
             result.push_back(std::move(token));
         }
         return result;
     }
Referenced by matchFunction(), and setParams().
hasResult()
bool express::dispatcher::hasResult (const std::string & cpath)
Definition at line 74 of file regex_utils.cpp.
{
         std::smatch smatch;
         return std::regex_search(cpath, smatch, pathRegex());
     }
References pathRegex().
Referenced by checkForUrlMatch(), express::dispatcher::ApplicationDispatcher::dispatch(), and express::dispatcher::MiddlewareDispatcher::dispatch().
matchFunction()
bool express::dispatcher::matchFunction (const std::string & cpath, const std::string & reqpath)
Definition at line 80 of file regex_utils.cpp.
{
         std::vector<std::string> explodedString = explode(cpath, '/');
         for (std::vector<std::string>::size_type i = 0; i < explodedString.size(); i++) {
             if (explodedString[i].front() == ':') {
                 std::smatch smatch = matchResult(explodedString[i]);
                 std::string regex = "(.*)";
                 if (smatch.size() > 1) {
                     if (smatch[1] != "") {
                         regex = smatch[1];
                     }
                 }
                 explodedString[i] = regex;
             }
         }
         std::string regexPath = path_concat(explodedString);
         return std::regex_match(reqpath, std::regex(regexPath));
     }
References explode(), matchResult(), and path_concat().
Referenced by checkForUrlMatch().
matchResult()
const std::smatch express::dispatcher::matchResult (const std::string & cpath)
Definition at line 66 of file regex_utils.cpp.
{
         std::smatch smatch;
         std::regex_search(cpath, smatch, pathRegex());
         return smatch;
     }
References pathRegex().
Referenced by matchFunction(), and setParams().
path_concat() [1/2]
std::string express::dispatcher::path_concat (const std::string & first, const std::string & second)
Definition at line 130 of file regex_utils.cpp.
{
         std::string result;
         if (first.back() == '/' && second.front() == '/') {
             result = first + second.substr(1);
         } else if (first.back() != '/' && second.front() != '/') {
             result = first + '/' + second;
         } else {
             result = first + second;
         }
         if (result.length() > 1 && result.back() == '/') {
             result.pop_back();
         }
         return result;
     }
path_concat() [2/2]
const std::string express::dispatcher::path_concat (const std::vector< std::string > & stringvec)
Definition at line 36 of file regex_utils.cpp.
{
         std::string s;
         for (std::vector<std::string>::size_type i = 0; i < stringvec.size(); i++) {
             if (!stringvec[i].empty() && stringvec[i].front() != ' ') {
                 s += "\\/" + stringvec[i];
             }
         }
         return s;
     }
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), express::dispatcher::MiddlewareDispatcher::dispatch(), express::dispatcher::RouterDispatcher::dispatch(), and matchFunction().
pathRegex()
const std::regex & express::dispatcher::pathRegex ()
Definition at line 60 of file regex_utils.cpp.
{
         static std::regex pathregex(PATH_REGEX);
         return pathregex;
     }
References PATH_REGEX.
Referenced by hasResult(), and matchResult().
setParams()
void express::dispatcher::setParams (const std::string & cpath, Request & req)
Definition at line 103 of file regex_utils.cpp.
{
         std::vector<std::string> explodedString = explode(cpath, '/');
         std::vector<std::string> explodedReqString = explode(req.url, '/');
         for (std::vector<std::string>::size_type i = 0; i < explodedString.size() && i < explodedReqString.size(); i++) {
             if (explodedString[i].front() == ':') {
                 std::smatch smatch = matchResult(explodedString[i]);
                 std::string regex = "(.*)";
                 if (smatch.size() > 1) {
                     if (smatch[1] != "") {
                         regex = smatch[1];
                     }
                 }
                 if (std::regex_match(explodedReqString[i], std::regex(regex))) {
                     std::string attributeName = smatch[0];
                     attributeName.erase(0, 1);
                     attributeName.erase((attributeName.length() - static_cast<std::size_t>(smatch[1].length())),
                                         static_cast<std::size_t>(smatch[1].length()));
                     req.params[attributeName] = explodedReqString[i];
                 }
             }
         }
     }
References explode(), matchResult(), express::Request::params, and web::http::server::Request::url.
Referenced by express::dispatcher::ApplicationDispatcher::dispatch(), and express::dispatcher::MiddlewareDispatcher::dispatch().