snode.c: CLI::FailureMessage Namespace Reference
CLI::FailureMessage Namespace Reference
Functions
std::string simple (const App *app, const Error &e)
Printout a clean, simple message on error (the default in CLI11 1.5+)
std::string help (const App *app, const Error &e)
Printout the full help string on error (if this fn is set, the old default for CLI11)
Function Documentation
help()
std::string CLI::FailureMessage::help (const App * app, const Error & e) inline
Printout the full help string on error (if this fn is set, the old default for CLI11)
Definition at line 8846 of file CLI11.hpp.
{
             std::string header = std::string("ERROR: ") + e.get_name() + ": " + e.what() + "\n";
             header += app->help();
             return header;
         }
References CLI::Error::get_name(), and CLI::App::help().
Referenced by CLI::App::exit(), utils::Timeval::operator+(), and utils::Timeval::operator-().
simple()
std::string CLI::FailureMessage::simple (const App * app, const Error & e) inline
Printout a clean, simple message on error (the default in CLI11 1.5+)
Definition at line 8827 of file CLI11.hpp.
{
             std::string header = std::string(e.what()) + "\n";
             std::vector<std::string> names;
             // Collect names
             if (app->get_help_ptr() != nullptr)
                 names.push_back(app->get_help_ptr()->get_name());
             if (app->get_help_all_ptr() != nullptr)
                 names.push_back(app->get_help_all_ptr()->get_name());
             // If any names found, suggest those
             if (!names.empty())
                 header += "Run with " + detail::join(names, " or ") + " for more information.\n";
             return header;
         }
References CLI::App::get_help_all_ptr(), CLI::App::get_help_ptr(), CLI::Option::get_name(), and CLI::detail::join().