snode.c: core::system Namespace Reference
core::system Namespace Reference
Functions
void * dlopen (const char *filename, int flags)
int dlclose (void *handle)
void * dlsym (void *handle, const char *symbol)
char * dlerror (void)
int epoll_create1 (int flags)
int epoll_wait (int epfd, epoll_event *events, int maxevents, int timeout)
int epoll_ctl (int epfd, int op, int fd, epoll_event *event)
int getaddrinfo (const char *node, const char *service, const struct addrinfo *hints, struct addrinfo **res)
void freeaddrinfo (struct addrinfo *res)
int getnameinfo (const struct sockaddr *addr, socklen_t addrlen, char *host, socklen_t hostlen, char *serv, socklen_t servlen, int flags)
int poll (pollfd *fds, nfds_t nfds, int timeout)
int select (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout)
sighandler_t signal (int signum, sighandler_t handler)
int socket (int domain, int type, int protocol)
int bind (int sockfd, const struct sockaddr *addr, socklen_t addrlen)
int listen (int sockfd, int backlog)
int accept4 (int sockfd, struct sockaddr *addr, socklen_t *addrlen, int flags)
int connect (int sockfd, const struct sockaddr *addr, socklen_t addrlen)
int getsockname (int sockfd, struct sockaddr *addr, socklen_t *addrlen)
int getpeername (int sockfd, struct sockaddr *addr, socklen_t *addrlen)
ssize_t recv (int sockfd, void *buf, std::size_t len, int flags)
ssize_t send (int sockfd, const void *buf, std::size_t len, int flags)
int getsockopt (int sockfd, int level, int optname, void *optval, socklen_t *optlen)
int setsockopt (int sockfd, int level, int optname, const void *optval, socklen_t optlen)
int shutdown (int sockfd, int how)
time_t time (time_t *tloc)
int gettimeofday (struct timeval *tv, struct timezone *tz)
struct tm * gmtime (const time_t *timep)
time_t mktime (struct tm *tm)
int open (const char *pathname, int flags)
ssize_t read (int fd, void *buf, std::size_t count)
ssize_t write (int fd, const void *buf, std::size_t count)
int close (int fd)
int pipe2 (int pipefd[2], int flags)
Function Documentation
accept4()
int core::system::accept4 (int sockfd, struct sockaddr * addr, socklen_t * addrlen, int flags)
Definition at line 44 of file socket.cpp.
{
         errno = 0;
         return ::accept4(sockfd, addr, addrlen, flags);
     }
Referenced by core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::acceptEvent().
bind()
int core::system::bind (int sockfd, const struct sockaddr * addr, socklen_t addrlen)
Definition at line 34 of file socket.cpp.
{
         errno = 0;
         return ::bind(sockfd, addr, addrlen);
     }
Referenced by core::socket::Socket< SocketAddressT >::bind().
close()
int core::system::close (int fd)
Definition at line 44 of file unistd.cpp.
                       {
         errno = 0;
         return ::close(fd);
     }
Referenced by core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::acceptEvent(), core::Descriptor::close(), utils::Daemon::daemonize(), and utils::Daemon::kill().
connect()
int core::system::connect (int sockfd, const struct sockaddr * addr, socklen_t addrlen)
Definition at line 48 of file socket.cpp.
{
         errno = 0;
         return ::connect(sockfd, addr, addrlen);
     }
Referenced by core::socket::stream::tls::SocketConnector< ClientConfigT, SocketT >::connect(), and core::file::FileReader::FileReader().
dlclose()
int core::system::dlclose (void * handle)
Definition at line 31 of file dlfcn.cpp.
{
         return ::dlclose(handle);
     }
Referenced by core::DynamicLoader::execDlClose().
dlerror()
char * core::system::dlerror (void)
Definition at line 39 of file dlfcn.cpp.
{
         return ::dlerror();
     }
Referenced by core::DynamicLoader::dlError().
dlopen()
void * core::system::dlopen (const char * filename, int flags)
Definition at line 27 of file dlfcn.cpp.
{
         return ::dlopen(filename, flags);
     }
Referenced by core::DynamicLoader::dlOpen().
dlsym()
void * core::system::dlsym (void * handle, const char * symbol)
Definition at line 35 of file dlfcn.cpp.
{
         return ::dlsym(handle, symbol);
     }
Referenced by core::DynamicLoader::dlSym().
epoll_create1()
int core::system::epoll_create1 (int flags)
Definition at line 29 of file epoll.cpp.
{
         errno = 0;
         return ::epoll_create1(flags);
     }
Referenced by core::epoll::DescriptorEventDispatcher::EPollEvents::EPollEvents(), and core::epoll::EventDispatcher::EventDispatcher().
epoll_ctl()
int core::system::epoll_ctl (int epfd, int op, int fd, epoll_event * event)
Definition at line 41 of file epoll.cpp.
{
         errno = 0;
         return ::epoll_ctl(epfd, op, fd, event);
     }
Referenced by core::epoll::EventDispatcher::EventDispatcher(), core::epoll::DescriptorEventDispatcher::EPollEvents::mod(), core::epoll::DescriptorEventDispatcher::EPollEvents::modAdd(), and core::epoll::DescriptorEventDispatcher::EPollEvents::modDel().
epoll_wait()
int core::system::epoll_wait (int epfd, epoll_event * events, int maxevents, int timeout)
Definition at line 35 of file epoll.cpp.
{
         errno = 0;
         return ::epoll_wait(epfd, events, maxevents, timeout);
     }
Referenced by core::epoll::DescriptorEventDispatcher::dispatchActiveEvents(), and core::epoll::EventDispatcher::multiplex().
freeaddrinfo()
void core::system::freeaddrinfo (struct addrinfo * res)
Definition at line 34 of file netdb.cpp.
{
         errno = 0;
         return ::freeaddrinfo(res);
     }
Referenced by net::in::SocketAddress::SocketAddress(), and net::in6::SocketAddress::SocketAddress().
getaddrinfo()
int core::system::getaddrinfo (const char * node, const char * service, const struct addrinfo * hints, struct addrinfo ** res)
Definition at line 29 of file netdb.cpp.
{
         errno = 0;
         return ::getaddrinfo(node, service, hints, res);
     }
Referenced by net::in::SocketAddress::SocketAddress(), and net::in6::SocketAddress::SocketAddress().
getnameinfo()
int core::system::getnameinfo (const struct sockaddr * addr, socklen_t addrlen, char * host, socklen_t hostlen, char * serv, socklen_t servlen, int flags)
Definition at line 40 of file netdb.cpp.
{
         errno = 0;
         return ::getnameinfo(addr, addrlen, host, hostlen, serv, servlen, flags);
     }
Referenced by net::in::SocketAddress::address(), net::in6::SocketAddress::address(), net::in::SocketAddress::host(), net::in6::SocketAddress::host(), net::in::SocketAddress::serv(), and net::in6::SocketAddress::serv().
getpeername()
int core::system::getpeername (int sockfd, struct sockaddr * addr, socklen_t * addrlen)
Definition at line 58 of file socket.cpp.
{
         errno = 0;
         return ::getpeername(sockfd, addr, addrlen);
     }
Referenced by core::socket::stream::SocketConnector< ClientConfigT, SocketConnectionT >::connectEvent().
getsockname()
int core::system::getsockname (int sockfd, struct sockaddr * addr, socklen_t * addrlen)
Definition at line 53 of file socket.cpp.
{
         errno = 0;
         return ::getsockname(sockfd, addr, addrlen);
     }
Referenced by core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::acceptEvent(), and core::socket::stream::SocketConnector< ClientConfigT, SocketConnectionT >::connectEvent().
getsockopt()
int core::system::getsockopt (int sockfd, int level, int optname, void * optval, socklen_t * optlen)
Definition at line 73 of file socket.cpp.
{
         errno = 0;
         return ::getsockopt(sockfd, level, optname, optval, optlen);
     }
Referenced by core::socket::stream::SocketConnector< ClientConfigT, SocketConnectionT >::connectEvent().
gettimeofday()
int core::system::gettimeofday (struct timeval * tv, struct timezone * tz)
Definition at line 34 of file time.cpp.
{
         errno = 0;
         return ::gettimeofday(tv, tz);
     }
Referenced by utils::Timeval::currentTime().
gmtime()
struct tm * core::system::gmtime (const time_t * timep)
Definition at line 39 of file time.cpp.
{
         errno = 0;
         return ::gmtime(timep);
     }
Referenced by web::http::server::Response::clearCookie(), httputils::file_mod_http_date(), and httputils::from_http_date().
listen()
int core::system::listen (int sockfd, int backlog)
Definition at line 39 of file socket.cpp.
{
         errno = 0;
         return ::listen(sockfd, backlog);
     }
Referenced by web::http::server::Server< SocketServerT, RequestT, ResponseT >::listen(), and core::socket::stream::tls::SocketAcceptor< ServerConfigT, SocketT >::listen().
mktime()
time_t core::system::mktime (struct tm * tm)
Definition at line 44 of file time.cpp.
{
         errno = 0;
         return ::mktime(tm);
     }
Referenced by httputils::from_http_date().
open()
int core::system::open (const char * pathname, int flags)
Definition at line 29 of file unistd.cpp.
{
         errno = 0;
         return ::open(pathname, flags);
     }
Referenced by core::file::FileReader::connect().
pipe2()
int core::system::pipe2 (int pipefd[2], int flags)
Definition at line 49 of file unistd.cpp.
{
         errno = 0;
         return ::pipe2(pipefd, flags);
     }
Referenced by core::pipe::Pipe::Pipe().
poll()
int core::system::poll (pollfd * fds, nfds_t nfds, int timeout)
Definition at line 29 of file poll.cpp.
{
         errno = 0;
         return ::poll(fds, nfds, timeout);
     }
Referenced by utils::Daemon::kill(), and core::poll::EventDispatcher::multiplex().
read()
ssize_t core::system::read (int fd, void * buf, std::size_t count)
Definition at line 34 of file unistd.cpp.
{
         errno = 0;
         return ::read(fd, buf, count);
     }
Referenced by core::file::FileReader::readEvent(), and core::pipe::PipeSink::readEvent().
recv()
ssize_t core::system::recv (int sockfd, void * buf, std::size_t len, int flags)
Definition at line 63 of file socket.cpp.
{
         errno = 0;
         return ::recv(sockfd, buf, len, flags);
     }
Referenced by core::socket::stream::legacy::SocketReader< SocketT >::read().
select()
int core::system::select (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout)
Definition at line 29 of file select.cpp.
{
         errno = 0;
         return ::select(nfds, readfds, writefds, exceptfds, timeout);
     }
Referenced by core::select::EventDispatcher::multiplex().
send()
ssize_t core::system::send (int sockfd, const void * buf, std::size_t len, int flags)
Definition at line 68 of file socket.cpp.
{
         errno = 0;
         return ::send(sockfd, buf, len, flags);
     }
Referenced by core::socket::stream::legacy::SocketWriter< SocketT >::write().
setsockopt()
int core::system::setsockopt (int sockfd, int level, int optname, const void * optval, socklen_t optlen)
Definition at line 78 of file socket.cpp.
{
         errno = 0;
         return ::setsockopt(sockfd, level, optname, optval, optlen);
     }
Referenced by core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::reuseAddress().
shutdown()
int core::system::shutdown (int sockfd, int how)
Definition at line 83 of file socket.cpp.
{
         errno = 0;
         return ::shutdown(sockfd, how);
     }
Referenced by core::socket::stream::SocketAcceptor< ServerConfigT, SocketConnectionT >::acceptEvent(), and core::socket::Socket< SocketAddressT >::shutdown().
signal()
sighandler_t core::system::signal (int signum, sighandler_t handler)
Definition at line 29 of file signal.cpp.
{
         errno = 0;
         return ::signal(signum, handler);
     }
Referenced by utils::Daemon::daemonize(), core::EventLoop::start(), and core::EventLoop::tick().
socket()
int core::system::socket (int domain, int type, int protocol)
Definition at line 29 of file socket.cpp.
{
         errno = 0;
         return ::socket(domain, type, protocol);
     }
Referenced by net::in::stream::Socket::create(), net::in6::stream::Socket::create(), net::rf::stream::Socket::create(), net::un::stream::Socket::create(), and net::l2::stream::Socket::create().
time()
time_t core::system::time (time_t * tloc)
Definition at line 29 of file time.cpp.
{
         errno = 0;
         return ::time(tloc);
     }
Referenced by web::http::server::Response::clearCookie(), httputils::from_http_date(), and utils::Timeval::Timeval().
write()
ssize_t core::system::write (int fd, const void * buf, std::size_t count)
Definition at line 39 of file unistd.cpp.
{
         errno = 0;
         return ::write(fd, buf, count);
     }
Referenced by core::pipe::PipeSource::writeEvent().