snode.c: CLI Namespace Reference
CLI Namespace Reference
Namespaces
detail
enums
FailureMessage
Classes
class Error
All errors derive from this one.
class ConstructionError
Construction errors (not in parsing)
class IncorrectConstruction
Thrown when an option is set to conflicting values (non-vector and multi args, for example)
class BadNameString
Thrown on construction of a bad name.
class OptionAlreadyAdded
Thrown when an option already exists.
class ParseError
Anything that can error in Parse.
class Success
This is a successful completion on parsing, supposed to exit.
class CallForHelp
-h or –help on command line
class CallForAllHelp
Usually something like –help-all on command line.
class CallForVersion
-v or –version on command line
class RuntimeError
Does not output a diagnostic in CLI11_PARSE, but allows main() to return with a specific error code.
class FileError
Thrown when parsing an INI file and it is missing.
class ConversionError
Thrown when conversion call back fails, such as when an int fails to coerce to a string.
class ValidationError
Thrown when validation of results fails.
class RequiredError
Thrown when a required option is missing.
class ArgumentMismatch
Thrown when the wrong number of arguments has been received.
class RequiresError
Thrown when a requires option is missing.
class ExcludesError
Thrown when an excludes option is present.
class ExtrasError
Thrown when too many positionals or options are found.
class ConfigError
Thrown when extra values are found in an INI file.
class InvalidError
Thrown when validation fails before parsing.
class HorribleError
class OptionNotFound
Thrown when counting a non-existent option.
struct make_void
A copy of std::void_t from C++17 (helper for C++11 and C++14)
struct is_bool
Check to see if something is bool (fail check by default)
struct is_bool< bool >
Check to see if something is bool (true if actually a bool)
struct is_shared_ptr
Check to see if something is a shared pointer.
struct is_shared_ptr< std::shared_ptr< T > >
Check to see if something is a shared pointer (True if really a shared pointer)
struct is_shared_ptr< const std::shared_ptr< T > >
Check to see if something is a shared pointer (True if really a shared pointer)
struct is_copyable_ptr
Check to see if something is copyable pointer.
struct IsMemberType
This can be specialized to override the type deduction for IsMember.
struct IsMemberType< const char * >
The main custom type needed here is const char * should be a string.
struct ConfigItem
Holds values to load into Options.
class Config
This class provides a converter for configuration files.
class ConfigBase
This converter works with INI/TOML files; to write INI files use ConfigINI.
class ConfigINI
ConfigINI generates a "standard" INI compliant output.
class Validator
Some validators that are provided.
class CustomValidator
Class wrapping some of the accessors of Validator.
class TypeValidator
Validate the input as a particular type.
class FileOnDefaultPath
class Range
Produce a range (factory). Min and max are inclusive.
class Bound
Produce a bounded range (factory). Min and max are inclusive.
class IsMember
Verify items are in a set.
class Transformer
Translate named items to other or a value set.
class CheckedTransformer
translate named items to other or a value set
class AsNumberWithUnit
class AsSizeValue
class FormatterBase
class FormatterLambda
This is a specialty override for lambda functions.
class Formatter
class OptionBase
class OptionDefaults
class Option
class App
Creates a command line program, with very few defaults.
class Option_group
Extension of App to better manage groups of options.
Typedefs
template<bool B, class T = void>
using enable_if_t = typename std::enable_if< B, T >::type
template<typename... Ts>
using void_t = typename make_void< Ts... >::type
A copy of std::void_t from C++17 - same reasoning as enable_if_t, it does not hurt to redefine.
template<bool B, class T , class F >
using conditional_t = typename std::conditional< B, T, F >::type
A copy of std::conditional_t from C++14 - same reasoning as enable_if_t, it does not hurt to redefine.
using ConfigTOML = ConfigBase
the default Config is the TOML file format
using results_t = std::vector< std::string >
using callback_t = std::function< bool(const results_t &)>
callback function definition
using Option_p = std::unique_ptr< Option >
using App_p = std::shared_ptr< App >
Enumerations
enum class ExitCodes {
Success = 0 , IncorrectConstruction = 100 , BadNameString , OptionAlreadyAdded ,
FileError , ConversionError , ValidationError , RequiredError ,
RequiresError , ExcludesError , ExtrasError , ConfigError ,
InvalidError , HorribleError , OptionNotFound , ArgumentMismatch ,
BaseClass = 127
}
enum class AppFormatMode { Normal , All , Sub }
enum class MultiOptionPolicy : char {
Throw , TakeLast , TakeFirst , Join ,
TakeAll , Sum
}
Enumeration of the multiOption Policy selection.
enum class config_extras_mode : char { error = 0 , ignore , ignore_all , capture }
enumeration of modes of how to deal with extras in config files
Functions
void TriggerOn (App *trigger_app, App *app_to_enable)
Helper function to enable one option group/subcommand when another is used.
void TriggerOn (App *trigger_app, std::vector< App * > apps_to_enable)
Helper function to enable one option group/subcommand when another is used.
void TriggerOff (App *trigger_app, App *app_to_enable)
Helper function to disable one option group/subcommand when another is used.
void TriggerOff (App *trigger_app, std::vector< App * > apps_to_enable)
Helper function to disable one option group/subcommand when another is used.
void deprecate_option (Option *opt, const std::string &replacement="")
Helper function to mark an option as deprecated.
void deprecate_option (App *app, const std::string &option_name, const std::string &replacement="")
Helper function to mark an option as deprecated.
void deprecate_option (App &app, const std::string &option_name, const std::string &replacement="")
Helper function to mark an option as deprecated.
void retire_option (App *app, Option *opt)
Helper function to mark an option as retired.
void retire_option (App &app, Option *opt)
Helper function to mark an option as retired.
void retire_option (App *app, const std::string &option_name)
Helper function to mark an option as retired.
void retire_option (App &app, const std::string &option_name)
Helper function to mark an option as retired.
template<typename T >
using TransformPairs = std::vector< std::pair< std::string, T > >
definition of the default transformation object
const detail::ExistingFileValidator ExistingFile
Check for existing file (returns error message if check fails)
const detail::ExistingDirectoryValidator ExistingDirectory
Check for an existing directory (returns error message if check fails)
const detail::ExistingPathValidator ExistingPath
Check for an existing path.
const detail::NonexistentPathValidator NonexistentPath
Check for an non-existing path.
const detail::IPV4Validator ValidIPV4
Check for an IP4 address.
const TypeValidator< double > Number ("NUMBER")
Check for a number.
const Range NonNegativeNumber ((std::numeric_limits< double >::max)(), "NONNEGATIVE")
Check for a non negative number.
const Range PositiveNumber ((std::numeric_limits< double >::min)(),(std::numeric_limits< double >::max)(), "POSITIVE")
Check for a positive valued number (val>0.0), min() her is the smallest positive number.
std::string ignore_case (std::string item)
Helper function to allow ignore_case to be passed to IsMember or Transform.
std::string ignore_underscore (std::string item)
Helper function to allow ignore_underscore to be passed to IsMember or Transform.
std::string ignore_space (std::string item)
Helper function to allow checks to ignore spaces to be passed to IsMember or Transform.
Typedef Documentation
App_p
using CLI::App_p = typedef std::shared_ptr<App>
Definition at line 5598 of file CLI11.hpp.
callback_t
using CLI::callback_t = typedef std::function<bool(const results_t&)>
callback function definition
Definition at line 4146 of file CLI11.hpp.
conditional_t
template<bool B, class T , class F > using CLI::conditional_t = typedef typename std::conditional<B, T, F>::type
A copy of std::conditional_t from C++14 - same reasoning as enable_if_t, it does not hurt to redefine.
Definition at line 973 of file CLI11.hpp.
ConfigTOML
using CLI::ConfigTOML = typedef ConfigBase
the default Config is the TOML file format
Definition at line 2781 of file CLI11.hpp.
enable_if_t
template<bool B, class T = void> using CLI::enable_if_t = typedef typename std::enable_if<B, T>::type
A copy of enable_if_t from C++14, compatible with C++11.
We could check to see if C++14 is being used, but it does not hurt to redefine this (even Google does this: https://github.com/google/skia/blob/main/include/private/SkTLogic.h) It is not in the std namespace anyway, so no harm done.
Definition at line 959 of file CLI11.hpp.
Option_p
using CLI::Option_p = typedef std::unique_ptr<Option>
Definition at line 4151 of file CLI11.hpp.
results_t
using CLI::results_t = typedef std::vector<std::string>
Definition at line 4144 of file CLI11.hpp.
TransformPairs
template<typename T > using CLI::TransformPairs = typedef std::vector<std::pair<std::string, T> >
definition of the default transformation object
Definition at line 3553 of file CLI11.hpp.
void_t
template<typename... Ts> using CLI::void_t = typedef typename make_void<Ts...>::type
A copy of std::void_t from C++17 - same reasoning as enable_if_t, it does not hurt to redefine.
Definition at line 969 of file CLI11.hpp.
Enumeration Type Documentation
AppFormatMode
enum CLI::AppFormatMode strong
This enum signifies the type of help requested
This is passed in by App; all user classes must accept this as the second argument.
Enumerator
Normal
The normal, detailed help.
All
A fully expanded help.
Sub
Used when printed as part of expanded subcommand.
Definition at line 3981 of file CLI11.hpp.
{
         Normal,
         All,
         Sub,
     };
config_extras_mode
enum CLI::config_extras_mode : char strong
enumeration of modes of how to deal with extras in config files
Enumerator
error
ignore
ignore_all
capture
Definition at line 5594 of file CLI11.hpp.
 : char { error = 0, ignore, ignore_all, capture };
ExitCodes
enum CLI::ExitCodes strong
These codes are part of every error in CLI. They can be obtained from e using e.exit_code or as a quick shortcut, int values from e.get_error_code().
Enumerator
Success
IncorrectConstruction
BadNameString
OptionAlreadyAdded
FileError
ConversionError
ValidationError
RequiredError
RequiresError
ExcludesError
ExtrasError
ConfigError
InvalidError
HorribleError
OptionNotFound
ArgumentMismatch
BaseClass
Definition at line 598 of file CLI11.hpp.
{
         Success = 0,
         IncorrectConstruction = 100,
         BadNameString,
         OptionAlreadyAdded,
         FileError,
         ConversionError,
         ValidationError,
         RequiredError,
         RequiresError,
         ExcludesError,
         ExtrasError,
         ConfigError,
         InvalidError,
         HorribleError,
         OptionNotFound,
         ArgumentMismatch,
         BaseClass = 127
     };
MultiOptionPolicy
enum CLI::MultiOptionPolicy : char strong
Enumeration of the multiOption Policy selection.
Enumerator
Throw
Throw an error if any extra arguments were given.
TakeLast
take only the last Expected number of arguments
TakeFirst
take only the first Expected number of arguments
Join
merge all the arguments together into a single string via the delimiter character default('
')
TakeAll
just get all the passed argument regardless
Sum
sum all the arguments together if numerical or concatenate directly without delimiter
Definition at line 4153 of file CLI11.hpp.
                                  : char {
         Throw,
         TakeLast,
         TakeFirst,
         Join,
         TakeAll,
         Sum
     };
Function Documentation
deprecate_option() [1/3]
void CLI::deprecate_option (App & app, const std::string & option_name, const std::string & replacement = "") inline
Helper function to mark an option as deprecated.
Definition at line 8764 of file CLI11.hpp.
{
         auto opt = app.get_option(option_name);
         deprecate_option(opt, replacement);
     }
References deprecate_option(), and CLI::App::get_option().
deprecate_option() [2/3]
void CLI::deprecate_option (App * app, const std::string & option_name, const std::string & replacement = "") inline
Helper function to mark an option as deprecated.
Definition at line 8758 of file CLI11.hpp.
{
         auto opt = app->get_option(option_name);
         deprecate_option(opt, replacement);
     }
References deprecate_option(), and CLI::App::get_option().
deprecate_option() [3/3]
void CLI::deprecate_option (Option * opt, const std::string & replacement = "") inline
Helper function to mark an option as deprecated.
Definition at line 8744 of file CLI11.hpp.
{
         Validator deprecate_warning{[opt, replacement](std::string&) {
                                         std::cout << opt->get_name() << " is deprecated please use '" << replacement << "' instead\n";
                                         return std::string();
                                     },
                                     "DEPRECATED"};
         deprecate_warning.application_index(0);
         opt->check(deprecate_warning);
         if (!replacement.empty()) {
             opt->description(opt->get_description() + " DEPRECATED: please use '" + replacement + "' instead");
         }
     }
References CLI::Option::check(), CLI::Option::description(), CLI::Option::get_description(), and CLI::Option::get_name().
Referenced by deprecate_option().
ignore_case()
std::string CLI::ignore_case (std::string item) inline
Helper function to allow ignore_case to be passed to IsMember or Transform.
Definition at line 3706 of file CLI11.hpp.
{
         return detail::to_lower(item);
     }
References CLI::detail::to_lower().
Referenced by CLI::detail::find_member().
ignore_space()
std::string CLI::ignore_space (std::string item) inline
Helper function to allow checks to ignore spaces to be passed to IsMember or Transform.
Definition at line 3716 of file CLI11.hpp.
{
         item.erase(std::remove(std::begin(item), std::end(item), ' '), std::end(item));
         item.erase(std::remove(std::begin(item), std::end(item), '\t'), std::end(item));
         return item;
     }
ignore_underscore()
std::string CLI::ignore_underscore (std::string item) inline
Helper function to allow ignore_underscore to be passed to IsMember or Transform.
Definition at line 3711 of file CLI11.hpp.
{
         return detail::remove_underscore(item);
     }
References CLI::detail::remove_underscore().
Referenced by CLI::detail::find_member().
retire_option() [1/4]
void CLI::retire_option (App & app, const std::string & option_name) inline
Helper function to mark an option as retired.
Definition at line 8820 of file CLI11.hpp.
{
         retire_option(&app, option_name);
     }
References retire_option().
retire_option() [2/4]
void CLI::retire_option (App & app, Option * opt) inline
Helper function to mark an option as retired.
Definition at line 8795 of file CLI11.hpp.
{
         retire_option(&app, opt);
     }
References retire_option().
retire_option() [3/4]
void CLI::retire_option (App * app, const std::string & option_name) inline
Helper function to mark an option as retired.
Definition at line 8800 of file CLI11.hpp.
{
         auto opt = app->get_option_no_throw(option_name);
         if (opt != nullptr) {
             retire_option(app, opt);
             return;
         }
         auto opt2 = app->add_option(option_name, "option has been retired and has no effect")
                         ->type_name("RETIRED")
                         ->expected(0, 1)
                         ->default_str("RETIRED");
         Validator retired_warning{[opt2](std::string&) {
                                       std::cout << "WARNING " << opt2->get_name() << " is retired and has no effect\n";
                                       return std::string();
                                   },
                                   ""};
         retired_warning.application_index(0);
         opt2->check(retired_warning);
     }
References CLI::App::add_option(), CLI::Option::default_str(), CLI::Option::expected(), CLI::Validator::get_name(), CLI::App::get_option_no_throw(), retire_option(), and CLI::Option::type_name().
retire_option() [4/4]
void CLI::retire_option (App * app, Option * opt) inline
Helper function to mark an option as retired.
Definition at line 8770 of file CLI11.hpp.
{
         App temp;
         auto option_copy = temp.add_option(opt->get_name(false, true))
                                ->type_size(opt->get_type_size_min(), opt->get_type_size_max())
                                ->expected(opt->get_expected_min(), opt->get_expected_max())
                                ->allow_extra_args(opt->get_allow_extra_args());
         app->remove_option(opt);
         auto opt2 = app->add_option(option_copy->get_name(false, true), "option has been retired and has no effect")
                         ->type_name("RETIRED")
                         ->default_str("RETIRED")
                         ->type_size(option_copy->get_type_size_min(), option_copy->get_type_size_max())
                         ->expected(option_copy->get_expected_min(), option_copy->get_expected_max())
                         ->allow_extra_args(option_copy->get_allow_extra_args());
         Validator retired_warning{[opt2](std::string&) {
                                       std::cout << "WARNING " << opt2->get_name() << " is retired and has no effect\n";
                                       return std::string();
                                   },
                                   ""};
         retired_warning.application_index(0);
         opt2->check(retired_warning);
     }
References CLI::App::add_option(), CLI::Option::allow_extra_args(), CLI::Option::default_str(), CLI::Option::expected(), CLI::Option::get_allow_extra_args(), CLI::Option::get_expected_max(), CLI::Option::get_expected_min(), CLI::Validator::get_name(), CLI::Option::get_name(), CLI::Option::get_type_size_max(), CLI::Option::get_type_size_min(), CLI::App::remove_option(), CLI::Option::type_name(), and CLI::Option::type_size().
Referenced by retire_option().
TriggerOff() [1/2]
void CLI::TriggerOff (App * trigger_app, App * app_to_enable) inline
Helper function to disable one option group/subcommand when another is used.
Definition at line 8721 of file CLI11.hpp.
{
         app_to_enable->disabled_by_default(false);
         app_to_enable->enabled_by_default();
         trigger_app->preparse_callback([app_to_enable](std::size_t) {
             app_to_enable->disabled();
         });
     }
References CLI::App::disabled(), CLI::App::disabled_by_default(), CLI::App::enabled_by_default(), and CLI::App::preparse_callback().
TriggerOff() [2/2]
void CLI::TriggerOff (App * trigger_app, std::vector< App * > apps_to_enable) inline
Helper function to disable one option group/subcommand when another is used.
Definition at line 8730 of file CLI11.hpp.
{
         for (auto& app : apps_to_enable) {
             app->disabled_by_default(false);
             app->enabled_by_default();
         }
         trigger_app->preparse_callback([apps_to_enable](std::size_t) {
             for (auto& app : apps_to_enable) {
                 app->disabled();
             }
         });
     }
References CLI::App::preparse_callback().
TriggerOn() [1/2]
void CLI::TriggerOn (App * trigger_app, App * app_to_enable) inline
Helper function to enable one option group/subcommand when another is used.
Definition at line 8698 of file CLI11.hpp.
{
         app_to_enable->enabled_by_default(false);
         app_to_enable->disabled_by_default();
         trigger_app->preparse_callback([app_to_enable](std::size_t) {
             app_to_enable->disabled(false);
         });
     }
References CLI::App::disabled(), CLI::App::disabled_by_default(), CLI::App::enabled_by_default(), and CLI::App::preparse_callback().
TriggerOn() [2/2]
void CLI::TriggerOn (App * trigger_app, std::vector< App * > apps_to_enable) inline
Helper function to enable one option group/subcommand when another is used.
Definition at line 8707 of file CLI11.hpp.
{
         for (auto& app : apps_to_enable) {
             app->enabled_by_default(false);
             app->disabled_by_default();
         }
         trigger_app->preparse_callback([apps_to_enable](std::size_t) {
             for (auto& app : apps_to_enable) {
                 app->disabled(false);
             }
         });
     }
References CLI::App::preparse_callback().
Variable Documentation
ExistingDirectory
const detail::ExistingDirectoryValidator CLI::ExistingDirectory
Check for an existing directory (returns error message if check fails)
Definition at line 3191 of file CLI11.hpp.
ExistingFile
const detail::ExistingFileValidator CLI::ExistingFile
Check for existing file (returns error message if check fails)
Definition at line 3188 of file CLI11.hpp.
ExistingPath
const detail::ExistingPathValidator CLI::ExistingPath
Check for an existing path.
Definition at line 3194 of file CLI11.hpp.
NonexistentPath
const detail::NonexistentPathValidator CLI::NonexistentPath
Check for an non-existing path.
Definition at line 3197 of file CLI11.hpp.
NonNegativeNumber
const Range CLI::NonNegativeNumber((std::numeric_limits< double >::max)(), "NONNEGATIVE") ((std::numeric_limits< double >::max)() , "NONNEGATIVE")
Check for a non negative number.
Number
const TypeValidator<double> CLI::Number("NUMBER") ("NUMBER")
Check for a number.
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit().
PositiveNumber
const Range CLI::PositiveNumber((std::numeric_limits< double >::min)(),(std::numeric_limits< double >::max)(), "POSITIVE") ((std::numeric_limits< double >::min)() , (std::numeric_limits< double >::max)() , "POSITIVE")
Check for a positive valued number (val>0.0), min() her is the smallest positive number.
ValidIPV4
const detail::IPV4Validator CLI::ValidIPV4
Check for an IP4 address.
Definition at line 3200 of file CLI11.hpp.