snode.c: CLI::detail Namespace Reference
CLI::detail Namespace Reference
Classes
struct element_type
not a pointer
struct element_type< T, typename std::enable_if< is_copyable_ptr< T >::value >::type >
struct element_value_type
struct pair_adaptor
Adaptor for set-like structure: This just wraps a normal container in a few utilities that do almost nothing.
struct pair_adaptor< T, conditional_t< false, void_t< typename T::value_type::first_type, typename T::value_type::second_type >, void > >
class is_direct_constructible
class is_ostreamable
class is_istreamable
Check for input streamability.
class is_complex
Check for complex.
struct is_mutable_container
struct is_mutable_container< T, conditional_t< false, void_t< typename T::value_type, decltype(std::declval< T >().end()), decltype(std::declval< T >().clear()), decltype(std::declval< T >().insert(std::declval< decltype(std::declval< T >().end())>(), std::declval< const typename T::value_type & >()))>, void > >
struct is_readable_container
struct is_readable_container< T, conditional_t< false, void_t< decltype(std::declval< T >().end()), decltype(std::declval< T >().begin())>, void > >
struct is_wrapper
struct is_wrapper< T, conditional_t< false, void_t< typename T::value_type >, void > >
class is_tuple_like
struct wrapped_type
template to get the underlying value type if it exists or use a default
struct wrapped_type< T, def, typename std::enable_if< is_wrapper< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct type_count_base
This will only trigger for actual void type.
struct type_count_base< T, typename std::enable_if<!is_tuple_like< T >::value &&!is_mutable_container< T >::value &&!std::is_void< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct type_count_base< T, typename std::enable_if< is_tuple_like< T >::value &&!is_mutable_container< T >::value >::type >
the base tuple size
struct type_count_base< T, typename std::enable_if< is_mutable_container< T >::value >::type >
Type count base for containers is the type_count_base of the individual element.
struct subtype_count
Set of overloads to get the type size of an object.
struct subtype_count_min
forward declare the subtype_count_min structure
struct type_count
This will only trigger for actual void type.
struct type_count< T, typename std::enable_if<!is_wrapper< T >::value &&!is_tuple_like< T >::value &&!is_complex< T >::value &&!std::is_void< T >::value >::type >
Type size for regular object types that do not look like a tuple.
struct type_count< T, typename std::enable_if< is_complex< T >::value >::type >
Type size for complex since it sometimes looks like a wrapper.
struct type_count< T, typename std::enable_if< is_mutable_container< T >::value >::type >
Type size of types that are wrappers,except complex and tuples(which can also be wrappers sometimes)
struct type_count< T, typename std::enable_if< is_wrapper< T >::value &&!is_complex< T >::value &&!is_tuple_like< T >::value &&!is_mutable_container< T >::value >::type >
Type size of types that are wrappers,except containers complex and tuples(which can also be wrappers sometimes)
class ExistingFileValidator
Check for an existing file (returns error message if check fails)
class ExistingDirectoryValidator
Check for an existing directory (returns error message if check fails)
class ExistingPathValidator
Check for an existing path.
class NonexistentPathValidator
Check for an non-existing path.
class IPV4Validator
Validate the given string is a legal ipv4 address.
struct has_find
struct AppFriend
This class is simply to allow tests access to App's protected functions.
Enumerations
enum class enabler
Simple empty scoped class.
enum class path_type { nonexistent , file , directory }
CLI enumeration of different file types.
enum class Classifier {
NONE , POSITIONAL_MARK , SHORT , LONG ,
WINDOWS_STYLE , SUBCOMMAND , SUBCOMMAND_TERMINATOR
}
Functions
std::vector< std::string > split (const std::string &s, char delim)
Split a string by a delim.
template<typename T >
std::string join (const T &v, std::string delim=",")
Simple function to join a string.
template<typename T , typename Callable , typename = typename std::enable_if<!std::is_constructible<std::string, Callable>::value>::type>
std::string join (const T &v, Callable func, std::string delim=",")
Simple function to join a string from processed elements.
template<typename T >
std::string rjoin (const T &v, std::string delim=",")
Join a string in reverse order.
std::string & ltrim (std::string &str)
Trim whitespace from left of string.
std::string & ltrim (std::string &str, const std::string &filter)
Trim anything from left of string.
std::string & rtrim (std::string &str)
Trim whitespace from right of string.
std::string & rtrim (std::string &str, const std::string &filter)
Trim anything from right of string.
std::string & trim (std::string &str)
Trim whitespace from string.
std::string & trim (std::string &str, const std::string filter)
Trim anything from string.
std::string trim_copy (const std::string &str)
Make a copy of the string and then trim it.
std::string & remove_quotes (std::string &str)
remove quotes at the front and back of a string either '"' or '\''
std::string fix_newlines (const std::string &leader, std::string input)
std::string trim_copy (const std::string &str, const std::string &filter)
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
std::ostream & format_help (std::ostream &out, std::string name, const std::string &description, std::size_t wid)
Print a two part "help" string.
std::ostream & format_aliases (std::ostream &out, const std::vector< std::string > &aliases, std::size_t wid)
Print subcommand aliases.
template<typename T >
bool valid_first_char (T c)
template<typename T >
bool valid_later_char (T c)
Verify following characters of an option.
bool valid_name_string (const std::string &str)
Verify an option/subcommand name.
bool valid_alias_name_string (const std::string &str)
Verify an app name.
bool is_separator (const std::string &str)
check if a string is a container segment separator (empty or "%%")
bool isalpha (const std::string &str)
Verify that str consists of letters only.
std::string to_lower (std::string str)
Return a lower case version of a string.
std::string remove_underscore (std::string str)
remove underscores from a string
std::string find_and_replace (std::string str, std::string from, std::string to)
Find and replace a substring with another substring.
bool has_default_flag_values (const std::string &flags)
check if the flag definitions has possible false flags
void remove_default_flag_values (std::string &flags)
std::ptrdiff_t find_member (std::string name, const std::vector< std::string > names, bool ignore_case=false, bool ignore_underscore=false)
Check if a string is a member of a list of strings and optionally ignore case or ignore underscores.
template<typename Callable >
std::string find_and_modify (std::string str, std::string trigger, Callable modify)
std::vector< std::string > split_up (std::string str, char delimiter='\0')
std::size_t escape_detect (std::string &str, std::size_t offset)
std::string & add_quotes_if_needed (std::string &str)
Add quotes if the string contains spaces.
template<typename T , enable_if_t< is_istreamable< T >::value, detail::enabler > = detail::dummy>
bool from_stream (const std::string &istring, T &obj)
Templated operation to get a value from a stream.
template<typename T , enable_if_t< std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy>
auto to_string (T &&value) -> decltype(std::forward< T >(value))
Convert an object to a string (directly forward if this can become a string)
template<typename T , enable_if_t< std::is_constructible< std::string, T >::value &&!std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy>
std::string to_string (const T &value)
Construct a string from the object.
template<typename T , enable_if_t<!std::is_convertible< std::string, T >::value &&!std::is_constructible< std::string, T >::value &&is_ostreamable< T >::value, detail::enabler > = detail::dummy>
std::string to_string (T &&value)
Convert an object to a string (streaming must be supported for that type)
template<typename T1 , typename T2 , typename T , enable_if_t< std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy>
auto checked_to_string (T &&value) -> decltype(to_string(std::forward< T >(value)))
special template overload
template<typename T1 , typename T2 , typename T , enable_if_t<!std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy>
std::string checked_to_string (T &&)
special template overload
template<typename T , enable_if_t< std::is_arithmetic< T >::value, detail::enabler > = detail::dummy>
std::string value_string (const T &value)
get a string as a convertible value for arithmetic types
template<typename T , enable_if_t<!std::is_enum< T >::value &&!std::is_arithmetic< T >::value, detail::enabler > = detail::dummy>
auto value_string (const T &value) -> decltype(to_string(value))
for other types just use the regular to_string function
template<typename T , std::size_t I>
constexpr std::enable_if< I==type_count_base< T >::value, int >::type tuple_type_size ()
0 if the index > tuple size
template<typename T , std::size_t I>
constexpr std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size() { return subtype_count< typename std::tuple_element< I, T >::type >::value+tuple_type_size< T, I+1 >);} template< typename T > struct type_count< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size< T, 0 >)};};template< typename T > struct subtype_count { static constexpr int value{is_mutable_container< T >::value ? expected_max_vector_size :type_count< T >::value};};template< typename T, typename Enable=void > struct type_count_min { static const int value{0};};template< typename T > struct type_count_min< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_tuple_like< T >::value &&!is_wrapper< T >::value &&!is_complex< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{type_count< T >::value};};template< typename T > struct type_count_min< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr int value{1};};template< typename T > struct type_count_min< T, typename std::enable_if< is_wrapper< T >::value &&!is_complex< T >::value &&!is_tuple_like< T >::value >::type > { static constexpr int value{subtype_count_min< typename T::value_type >::value};};template< typename T, std::size_t I > constexpr typename std::enable_if< I==type_count_base< T >::value, int >::type tuple_type_size_min() { return 0;} template< typename T, std::size_t I > constexpr typename std::enable_if< I< type_count_base< T >::value, int >::type tuple_type_size_min() { return subtype_count_min< typename std::tuple_element< I, T >::type >::value+tuple_type_size_min< T, I+1 >);} template< typename T > struct type_count_min< T, typename std::enable_if< is_tuple_like< T >::value >::type > { static constexpr int value{tuple_type_size_min< T, 0 >)};};template< typename T > struct subtype_count_min { static constexpr int value{is_mutable_container< T >::value ?((type_count< T >::value< expected_max_vector_size) ? type_count< T >::value :0) :type_count_min< T >::value};};template< typename T, typename Enable=void > struct expected_count { static const int value{0};};template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&!is_wrapper< T >::value &&!std::is_void< T >::value >::type > { static constexpr int value{1};};template< typename T > struct expected_count< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr int value{expected_max_vector_size};};template< typename T > struct expected_count< T, typename std::enable_if<!is_mutable_container< T >::value &&is_wrapper< T >::value >::type > { static constexpr int value{expected_count< typename T::value_type >::value};};enum class object_category :int { char_value=1, integral_value=2, unsigned_integral=4, enumeration=6, boolean_value=8, floating_point=10, number_constructible=12, double_constructible=14, integer_constructible=16, string_assignable=23, string_constructible=24, other=45, wrapper_value=50, complex_number=60, tuple_value=70, container_value=80, };template< typename T, typename Enable=void > struct classify_object { static constexpr object_category value{object_category::other};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&!std::is_same< T, char >::value &&std::is_signed< T >::value &&!is_bool< T >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::integral_value};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_integral< T >::value &&std::is_unsigned< T >::value &&!std::is_same< T, char >::value &&!is_bool< T >::value >::type > { static constexpr object_category value{object_category::unsigned_integral};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_same< T, char >::value &&!std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::char_value};};template< typename T > struct classify_object< T, typename std::enable_if< is_bool< T >::value >::type > { static constexpr object_category value{object_category::boolean_value};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_floating_point< T >::value >::type > { static constexpr object_category value{object_category::floating_point};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&std::is_assignable< T &, std::string >::value >::type > { static constexpr object_category value{object_category::string_assignable};};template< typename T > struct classify_object< T, typename std::enable_if<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&(type_count< T >::value==1) &&std::is_constructible< T, std::string >::value >::type > { static constexpr object_category value{object_category::string_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< std::is_enum< T >::value >::type > { static constexpr object_category value{object_category::enumeration};};template< typename T > struct classify_object< T, typename std::enable_if< is_complex< T >::value >::type > { static constexpr object_category value{object_category::complex_number};};template< typename T > struct uncommon_type { using type=typename std::conditional<!std::is_floating_point< T >::value &&!std::is_integral< T >::value &&!std::is_assignable< T &, std::string >::value &&!std::is_constructible< T, std::string >::value &&!is_complex< T >::value &&!is_mutable_container< T >::value &&!std::is_enum< T >::value, std::true_type, std::false_type >::type;static constexpr bool value=type::value;};template< typename T > struct classify_object< T, typename std::enable_if<(!is_mutable_container< T >::value &&is_wrapper< T >::value &&!is_tuple_like< T >::value &&uncommon_type< T >::value)>::type > { static constexpr object_category value{object_category::wrapper_value};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::number_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&!is_direct_constructible< T, double >::value &&is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::integer_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< uncommon_type< T >::value &&type_count< T >::value==1 &&!is_wrapper< T >::value &&is_direct_constructible< T, double >::value &&!is_direct_constructible< T, int >::value >::type > { static constexpr object_category value{object_category::double_constructible};};template< typename T > struct classify_object< T, typename std::enable_if< is_tuple_like< T >::value &&((type_count< T >::value >=2 &&!is_wrapper< T >::value)||(uncommon_type< T >::value &&!is_direct_constructible< T, double >::value &&!is_direct_constructible< T, int >::value))>::type > { static constexpr object_category value{object_category::tuple_value};};template< typename T > struct classify_object< T, typename std::enable_if< is_mutable_container< T >::value >::type > { static constexpr object_category value{object_category::container_value};};template< typename T, enable_if_t< classify_object< T >::value==object_category::char_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "CHAR";} template< typename T, enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::integer_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "INT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::unsigned_integral, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "UINT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::floating_point||classify_object< T >::value==object_category::number_constructible||classify_object< T >::value==object_category::double_constructible, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "FLOAT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::enumeration, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "ENUM";} template< typename T, enable_if_t< classify_object< T >::value==object_category::boolean_value, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "BOOLEAN";} template< typename T, enable_if_t< classify_object< T >::value==object_category::complex_number, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "COMPLEX";} template< typename T, enable_if_t< classify_object< T >::value >=object_category::string_assignable &&classify_object< T >::value<=object_category::other, detail::enabler >=detail::dummy > constexpr const char *type_name() { return "TEXT";} template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler >=detail::dummy > std::string type_name();template< typename T, enable_if_t< classify_object< T >::value==object_category::container_value||classify_object< T >::value==object_category::wrapper_value, detail::enabler >=detail::dummy > std::string type_name();template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value==1, detail::enabler >=detail::dummy > inline std::string type_name() { return type_name< typename std::decay< typename std::tuple_element< 0, T >::type >::type >);} template< typename T, std::size_t I > inline typename std::enable_if< I==type_count_base< T >::value, std::string >::type tuple_name() { return std::string{};} template< typename T, std::size_t I > inline typename std::enable_if<(I< type_count_base< T >::value), std::string >::type tuple_name() { std::string str=std::string(type_name< typename std::decay< typename std::tuple_element< I, T >::type >::type >))+','+tuple_name< T, I+1 >);if(str.back()==',') str.pop_back();return str;} template< typename T, enable_if_t< classify_object< T >::value==object_category::tuple_value &&type_count_base< T >::value >=2, detail::enabler > > std::string type_name ()
Recursively generate the tuple type name.
template<typename T , enable_if_t< classify_object< T >::value==object_category::container_value||classify_object< T >::value==object_category::wrapper_value, detail::enabler > >
std::string type_name ()
get the type name for a type that has a value_type member
template<typename T , enable_if_t< std::is_unsigned< T >::value, detail::enabler > = detail::dummy>
bool integral_conversion (const std::string &input, T &output) noexcept
Convert to an unsigned integral.
std::int64_t to_flag_value (std::string val)
Convert a flag into an integer value typically binary flags.
template<typename T , enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::unsigned_integral, detail::enabler > = detail::dummy>
bool lexical_cast (const std::string &input, T &output)
Integer conversion.
template<typename AssignTo , typename ConvertTo , enable_if_t< std::is_same< AssignTo, ConvertTo >::value &&(classify_object< AssignTo >::value==object_category::string_assignable||classify_object< AssignTo >::value==object_category::string_constructible), detail::enabler > = detail::dummy>
bool lexical_assign (const std::string &input, AssignTo &output)
Assign a value through lexical cast operations.
bool split_short (const std::string &current, std::string &name, std::string &rest)
bool split_long (const std::string &current, std::string &name, std::string &value)
bool split_windows_style (const std::string &current, std::string &name, std::string &value)
std::vector< std::string > split_names (std::string current)
std::vector< std::pair< std::string, std::string > > get_default_flag_values (const std::string &str)
extract default flag values either {def} or starting with a !
std::tuple< std::vector< std::string >, std::vector< std::string >, std::string > get_names (const std::vector< std::string > &input)
Get a vector of short names, one of long names, and a single name.
path_type check_path (const char *file) noexcept
get the type of the path from a file name
template<typename T , enable_if_t< is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy>
auto smart_deref (T value) -> decltype(*value)
template<typename T , enable_if_t<!is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy>
std::remove_reference< T >::type & smart_deref (T &value)
template<typename T >
std::string generate_set (const T &set)
Generate a string representation of a set.
template<typename T >
std::string generate_map (const T &map, bool key_only=false)
Generate a string representation of a map.
template<typename T , typename V , enable_if_t<!has_find< T, V >::value, detail::enabler > = detail::dummy>
auto search (const T &set, const V &val) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function.
template<typename T , typename V >
auto search (const T &set, const V &val, const std::function< V(V)> &filter_function) -> std::pair< bool, decltype(std::begin(detail::smart_deref(set)))>
A search function with a filter function.
template<typename T >
std::enable_if< std::is_signed< T >::value, T >::type overflowCheck (const T &a, const T &b)
Do a check for overflow on signed numbers.
template<typename T >
std::enable_if<!std::is_signed< T >::value, T >::type overflowCheck (const T &a, const T &b)
Do a check for overflow on unsigned numbers.
template<typename T >
std::enable_if< std::is_integral< T >::value, bool >::type checked_multiply (T &a, T b)
Performs a *= b; if it doesn't cause integer overflow. Returns false otherwise.
template<typename T >
std::enable_if< std::is_floating_point< T >::value, bool >::type checked_multiply (T &a, T b)
Performs a *= b; if it doesn't equal infinity. Returns false otherwise.
std::pair< std::string, std::string > split_program_name (std::string commandline)
template<typename T , enable_if_t<!std::is_integral< T >::value||(sizeof(T)<=1U), detail::enabler > = detail::dummy>
Option * default_flag_modifiers (Option *opt)
helper functions for adding in appropriate flag modifiers for add_flag
std::string convert_arg_for_ini (const std::string &arg, char stringQuote='"', char characterQuote = '\'')
std::string ini_join (const std::vector< std::string > &args, char sepChar=',', char arrayStart='[', char arrayEnd=']', char stringQuote='"', char characterQuote = '\'')
Comma separated join, adds quotes if needed.
std::vector< std::string > generate_parents (const std::string &section, std::string &name, char parentSeparator)
void checkParentSegments (std::vector< ConfigItem > &output, const std::string &currentSection, char parentSeparator)
assuming non default segments do a check on the close and open of the segments in a configItem structure
Variables
constexpr int expected_max_vector_size {1 << 29}
constexpr enabler dummy = {}
An instance to use in EnableIf.
Enumeration Type Documentation
Classifier
enum CLI::detail::Classifier strong
Enumerator
NONE
POSITIONAL_MARK
SHORT
LONG
WINDOWS_STYLE
SUBCOMMAND
SUBCOMMAND_TERMINATOR
Definition at line 5583 of file CLI11.hpp.
 { NONE, POSITIONAL_MARK, SHORT, LONG, WINDOWS_STYLE, SUBCOMMAND, SUBCOMMAND_TERMINATOR };
enabler
enum CLI::detail::enabler strong
Simple empty scoped class.
Definition at line 947 of file CLI11.hpp.
 {};
path_type
enum CLI::detail::path_type strong
CLI enumeration of different file types.
Enumerator
nonexistent
file
directory
Definition at line 3048 of file CLI11.hpp.
 { nonexistent, file, directory };
Function Documentation
add_quotes_if_needed()
std::string& CLI::detail::add_quotes_if_needed (std::string & str) inline
Add quotes if the string contains spaces.
Definition at line 558 of file CLI11.hpp.
{
             if ((str.front() != '"' && str.front() != '\'') || str.front() != str.back()) {
                 char quote = str.find('"') < str.find('\'') ? '\'' : '"';
                 if (str.find(' ') != std::string::npos) {
                     str.insert(0, 1, quote);
                     str.append(1, quote);
                 }
             }
             return str;
         }
check_path()
path_type CLI::detail::check_path (const char * file) inline noexcept
get the type of the path from a file name
Definition at line 3077 of file CLI11.hpp.
{
 #if defined(_MSC_VER)
             struct __stat64 buffer;
             if (_stat64(file, &buffer) == 0) {
                 return ((buffer.st_mode & S_IFDIR) != 0) ? path_type::directory : path_type::file;
             }
 #else
             struct stat buffer;
             if (stat(file, &buffer) == 0) {
                 return ((buffer.st_mode & S_IFDIR) != 0) ? path_type::directory : path_type::file;
             }
 #endif
             return path_type::nonexistent;
         }
References file.
Referenced by CLI::App::_process_config_file(), CLI::detail::ExistingDirectoryValidator::ExistingDirectoryValidator(), CLI::detail::ExistingFileValidator::ExistingFileValidator(), CLI::detail::ExistingPathValidator::ExistingPathValidator(), CLI::FileOnDefaultPath::FileOnDefaultPath(), CLI::detail::NonexistentPathValidator::NonexistentPathValidator(), and split_program_name().
checked_multiply() [1/2]
template<typename T > std::enable_if<std::is_integral<T>::value, bool>::type CLI::detail::checked_multiply (T & a, T b)
Performs a *= b; if it doesn't cause integer overflow. Returns false otherwise.
Definition at line 3449 of file CLI11.hpp.
{
             if (a == 0 || b == 0 || a == 1 || b == 1) {
                 a *= b;
                 return true;
             }
             if (a == (std::numeric_limits<T>::min)() || b == (std::numeric_limits<T>::min)()) {
                 return false;
             }
             if (overflowCheck(a, b)) {
                 return false;
             }
             a *= b;
             return true;
         }
References overflowCheck().
Referenced by CLI::App::_parse_arg(), CLI::AsNumberWithUnit::AsNumberWithUnit(), and CLI::Option::get_items_expected_max().
checked_multiply() [2/2]
template<typename T > std::enable_if<std::is_floating_point<T>::value, bool>::type CLI::detail::checked_multiply (T & a, T b)
Performs a *= b; if it doesn't equal infinity. Returns false otherwise.
Definition at line 3466 of file CLI11.hpp.
{
             T c = a * b;
             if (std::isinf(c) && !std::isinf(a) && !std::isinf(b)) {
                 return false;
             }
             a = c;
             return true;
         }
checked_to_string() [1/2]
template<typename T1 , typename T2 , typename T , enable_if_t<!std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy> std::string CLI::detail::checked_to_string (T &&)
special template overload
Definition at line 1285 of file CLI11.hpp.
{
             return std::string{};
         }
checked_to_string() [2/2]
template<typename T1 , typename T2 , typename T , enable_if_t< std::is_same< T1, T2 >::value, detail::enabler > = detail::dummy> auto CLI::detail::checked_to_string (T && value) -> decltype(to_string(std::forward<T>(value)))
special template overload
Definition at line 1279 of file CLI11.hpp.
{
             return to_string(std::forward<T>(value));
         }
References to_string().
checkParentSegments()
void CLI::detail::checkParentSegments (std::vector< ConfigItem > & output, const std::string & currentSection, char parentSeparator) inline
assuming non default segments do a check on the close and open of the segments in a configItem structure
Definition at line 8993 of file CLI11.hpp.
{
             std::string estring;
             auto parents = detail::generate_parents(currentSection, estring, parentSeparator);
             if (!output.empty() && output.back().name == "--") {
                 std::size_t msize = (parents.size() > 1U) ? parents.size() : 2;
                 while (output.back().parents.size() >= msize) {
                     output.push_back(output.back());
                     output.back().parents.pop_back();
                 }
                 if (parents.size() > 1) {
                     std::size_t common = 0;
                     std::size_t mpair = (std::min)(output.back().parents.size(), parents.size() - 1);
                     for (std::size_t ii = 0; ii < mpair; ++ii) {
                         if (output.back().parents[ii] != parents[ii]) {
                             break;
                         }
                         ++common;
                     }
                     if (common == mpair) {
                         output.pop_back();
                     } else {
                         while (output.back().parents.size() > common + 1) {
                             output.push_back(output.back());
                             output.back().parents.pop_back();
                         }
                     }
                     for (std::size_t ii = common; ii < parents.size() - 1; ++ii) {
                         output.emplace_back();
                         output.back().parents.assign(parents.begin(), parents.begin() + static_cast<std::ptrdiff_t>(ii) + 1);
                         output.back().name = "++";
                     }
                 }
             } else if (parents.size() > 1) {
                 for (std::size_t ii = 0; ii < parents.size() - 1; ++ii) {
                     output.emplace_back();
                     output.back().parents.assign(parents.begin(), parents.begin() + static_cast<std::ptrdiff_t>(ii) + 1);
                     output.back().name = "++";
                 }
             }
             // insert a section end which is just an empty items_buffer
             output.emplace_back();
             output.back().parents = std::move(parents);
             output.back().name = "++";
         }
References generate_parents().
Referenced by CLI::ConfigBase::from_config().
convert_arg_for_ini()
std::string CLI::detail::convert_arg_for_ini (const std::string & arg, char stringQuote = '"', char characterQuote = '\'') inline
Definition at line 8893 of file CLI11.hpp.
{
             if (arg.empty()) {
                 return std::string(2, stringQuote);
             }
             // some specifically supported strings
             if (arg == "true" || arg == "false" || arg == "nan" || arg == "inf") {
                 return arg;
             }
             // floating point conversion can convert some hex codes, but don't try that here
             if (arg.compare(0, 2, "0x") != 0 && arg.compare(0, 2, "0X") != 0) {
                 double val;
                 if (detail::lexical_cast(arg, val)) {
                     return arg;
                 }
             }
             // just quote a single non numeric character
             if (arg.size() == 1) {
                 return std::string(1, characterQuote) + arg + characterQuote;
             }
             // handle hex, binary or octal arguments
             if (arg.front() == '0') {
                 if (arg[1] == 'x') {
                     if (std::all_of(arg.begin() + 2, arg.end(), [](char x) {
                             return (x >= '0' && x <= '9') || (x >= 'A' && x <= 'F') || (x >= 'a' && x <= 'f');
                         })) {
                         return arg;
                     }
                 } else if (arg[1] == 'o') {
                     if (std::all_of(arg.begin() + 2, arg.end(), [](char x) {
                             return (x >= '0' && x <= '7');
                         })) {
                         return arg;
                     }
                 } else if (arg[1] == 'b') {
                     if (std::all_of(arg.begin() + 2, arg.end(), [](char x) {
                             return (x == '0' || x == '1');
                         })) {
                         return arg;
                     }
                 }
             }
             if (arg.find_first_of(stringQuote) == std::string::npos) {
                 return std::string(1, stringQuote) + arg + stringQuote;
             } else {
                 return characterQuote + arg + characterQuote;
             }
         }
References lexical_cast().
Referenced by ini_join(), and CLI::ConfigBase::to_config().
default_flag_modifiers()
template<typename T , enable_if_t<!std::is_integral< T >::value||(sizeof(T)<=1U), detail::enabler > = detail::dummy> Option * CLI::detail::default_flag_modifiers (Option * opt)
helper functions for adding in appropriate flag modifiers for add_flag
summing modifiers
Definition at line 5604 of file CLI11.hpp.
{
             return opt->always_capture_default();
         }
References CLI::OptionBase< CRTP >::always_capture_default().
escape_detect()
std::size_t CLI::detail::escape_detect (std::string & str, std::size_t offset) inline
This function detects an equal or colon followed by an escaped quote after an argument then modifies the string to replace the equality with a space. This is needed to allow the split up function to work properly and is intended to be used with the find_and_modify function the return value is the offset+1 which is required by the find_and_modify function.
Definition at line 545 of file CLI11.hpp.
{
             auto next = str[offset + 1];
             if ((next == '\"') || (next == '\'') || (next == '`')) {
                 auto astart = str.find_last_of("-/ \"\'`", offset - 1);
                 if (astart != std::string::npos) {
                     if (str[astart] == ((str[offset] == '=') ? '-' : '/'))
                         str[offset] = ' '; // interpret this as a space so the split_up works properly
                 }
             }
             return offset + 1;
         }
Referenced by CLI::App::parse().
find_and_modify()
template<typename Callable > std::string CLI::detail::find_and_modify (std::string str, std::string trigger, Callable modify) inline
Find a trigger string and call a modify callable function that takes the current string and starting position of the trigger and returns the position in the string to search for the next trigger string
Definition at line 480 of file CLI11.hpp.
{
             std::size_t start_pos = 0;
             while ((start_pos = str.find(trigger, start_pos)) != std::string::npos) {
                 start_pos = modify(str, start_pos);
             }
             return str;
         }
Referenced by CLI::App::parse().
find_and_replace()
std::string CLI::detail::find_and_replace (std::string str, std::string from, std::string to) inline
Find and replace a substring with another substring.
Definition at line 420 of file CLI11.hpp.
{
             std::size_t start_pos = 0;
             while ((start_pos = str.find(from, start_pos)) != std::string::npos) {
                 str.replace(start_pos, from.length(), to);
                 start_pos += to.length();
             }
             return str;
         }
Referenced by CLI::Formatter::make_expanded(), split_program_name(), and split_up().
find_member()
std::ptrdiff_t CLI::detail::find_member (std::string name, const std::vector< std::string > names, bool ignore_case = false, bool ignore_underscore = false) inline
Check if a string is a member of a list of strings and optionally ignore case or ignore underscores.
Definition at line 450 of file CLI11.hpp.
{
             auto it = std::end(names);
             if (ignore_case) {
                 if (ignore_underscore) {
                     name = detail::to_lower(detail::remove_underscore(name));
                     it = std::find_if(std::begin(names), std::end(names), [&name](std::string local_name) {
                         return detail::to_lower(detail::remove_underscore(local_name)) == name;
                     });
                 } else {
                     name = detail::to_lower(name);
                     it = std::find_if(std::begin(names), std::end(names), [&name](std::string local_name) {
                         return detail::to_lower(local_name) == name;
                     });
                 }
             } else if (ignore_underscore) {
                 name = detail::remove_underscore(name);
                 it = std::find_if(std::begin(names), std::end(names), [&name](std::string local_name) {
                     return detail::remove_underscore(local_name) == name;
                 });
             } else {
                 it = std::find(std::begin(names), std::end(names), name);
             }
             return (it != std::end(names)) ? (it - std::begin(names)) : (-1);
         }
References CLI::ignore_case(), CLI::ignore_underscore(), remove_underscore(), and to_lower().
Referenced by CLI::Option::check_fname(), CLI::Option::check_lname(), CLI::Option::check_sname(), and CLI::Option::get_flag_value().
fix_newlines()
std::string CLI::detail::fix_newlines (const std::string & leader, std::string input) inline
Add a leader to the beginning of all new lines (nothing is added at the start of the first line). "; " would be for ini files
Can't use Regex, or this would be a subs.
Definition at line 305 of file CLI11.hpp.
{
             std::string::size_type n = 0;
             while (n != std::string::npos && n < input.size()) {
                 n = input.find('\n', n);
                 if (n != std::string::npos) {
                     input = input.substr(0, n + 1) + leader + input.substr(n + 1);
                     n += leader.size();
                 }
             }
             return input;
         }
Referenced by format_aliases(), and CLI::ConfigBase::to_config().
format_aliases()
std::ostream& CLI::detail::format_aliases (std::ostream & out, const std::vector< std::string > & aliases, std::size_t wid) inline
Print subcommand aliases.
Definition at line 341 of file CLI11.hpp.
{
             if (!aliases.empty()) {
                 out << std::setw(static_cast<int>(wid)) << "     aliases: ";
                 bool front = true;
                 for (const auto& alias : aliases) {
                     if (!front) {
                         out << ", ";
                     } else {
                         front = false;
                     }
                     out << detail::fix_newlines("              ", alias);
                 }
                 out << "\n";
             }
             return out;
         }
References fix_newlines().
Referenced by CLI::Formatter::make_expanded().
format_help()
std::ostream& CLI::detail::format_help (std::ostream & out, std::string name, const std::string & description, std::size_t wid) inline
Print a two part "help" string.
Definition at line 323 of file CLI11.hpp.
{
             name = "  " + name;
             out << std::setw(static_cast<int>(wid)) << std::left << name;
             if (!description.empty()) {
                 if (name.length() >= wid)
                     out << "\n" << std::setw(static_cast<int>(wid)) << "";
                 for (const char c : description) {
                     out.put(c);
                     if (c == '\n') {
                         out << std::setw(static_cast<int>(wid)) << "";
                     }
                 }
             }
             out << "\n";
             return out;
         }
Referenced by CLI::Formatter::make_option(), and CLI::Formatter::make_subcommand().
from_stream()
template<typename T , enable_if_t< is_istreamable< T >::value, detail::enabler > = detail::dummy> bool CLI::detail::from_stream (const std::string & istring, T & obj)
Templated operation to get a value from a stream.
Definition at line 1160 of file CLI11.hpp.
{
             std::istringstream is;
             is.str(istring);
             is >> obj;
             return !is.fail() && !is.rdbuf()->in_avail();
         }
generate_map()
template<typename T > std::string CLI::detail::generate_map (const T & map, bool key_only = false)
Generate a string representation of a map.
Definition at line 3359 of file CLI11.hpp.
{
             using element_t = typename detail::element_type<T>::type;
             using iteration_type_t = typename detail::pair_adaptor<element_t>::value_type; // the type of the object pair
             std::string out(1, '{');
             out.append(detail::join(
                 detail::smart_deref(map),
                 [key_only](const iteration_type_t& v) {
                     std::string res{detail::to_string(detail::pair_adaptor<element_t>::first(v))};
                     if (!key_only) {
                         res.append("->");
                         res += detail::to_string(detail::pair_adaptor<element_t>::second(v));
                     }
                     return res;
                 },
                 ","));
             out.push_back('}');
             return out;
         }
References join(), smart_deref(), and to_string().
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit(), CLI::CheckedTransformer::CheckedTransformer(), and CLI::Transformer::Transformer().
generate_parents()
std::vector<std::string> CLI::detail::generate_parents (const std::string & section, std::string & name, char parentSeparator) inline
Definition at line 8968 of file CLI11.hpp.
{
             std::vector<std::string> parents;
             if (detail::to_lower(section) != "default") {
                 if (section.find(parentSeparator) != std::string::npos) {
                     parents = detail::split(section, parentSeparator);
                 } else {
                     parents = {section};
                 }
             }
             if (name.find(parentSeparator) != std::string::npos) {
                 std::vector<std::string> plist = detail::split(name, parentSeparator);
                 name = plist.back();
                 detail::remove_quotes(name);
                 plist.pop_back();
                 parents.insert(parents.end(), plist.begin(), plist.end());
             }
             // clean up quotes on the parents
             for (auto& parent : parents) {
                 detail::remove_quotes(parent);
             }
             return parents;
         }
References remove_quotes(), split(), and to_lower().
Referenced by checkParentSegments(), and CLI::ConfigBase::from_config().
generate_set()
template<typename T > std::string CLI::detail::generate_set (const T & set)
Generate a string representation of a set.
Definition at line 3343 of file CLI11.hpp.
{
             using element_t = typename detail::element_type<T>::type;
             using iteration_type_t = typename detail::pair_adaptor<element_t>::value_type; // the type of the object pair
             std::string out(1, '{');
             out.append(detail::join(
                 detail::smart_deref(set),
                 [](const iteration_type_t& v) {
                     return detail::pair_adaptor<element_t>::first(v);
                 },
                 ","));
             out.push_back('}');
             return out;
         }
References CLI::detail::pair_adaptor< T, _ >::first(), join(), and smart_deref().
Referenced by CLI::IsMember::IsMember().
get_default_flag_values()
std::vector<std::pair<std::string, std::string> > CLI::detail::get_default_flag_values (const std::string & str) inline
extract default flag values either {def} or starting with a !
Definition at line 2565 of file CLI11.hpp.
{
             std::vector<std::string> flags = split_names(str);
             flags.erase(std::remove_if(
                             flags.begin(),
                             flags.end(),
                             [](const std::string& name) {
                                 return ((name.empty()) ||
                                         (!(((name.find_first_of('{') != std::string::npos) && (name.back() == '}')) || (name[0] == '!'))));
                             }),
                         flags.end());
             std::vector<std::pair<std::string, std::string>> output;
             output.reserve(flags.size());
             for (auto& flag : flags) {
                 auto def_start = flag.find_first_of('{');
                 std::string defval = "false";
                 if ((def_start != std::string::npos) && (flag.back() == '}')) {
                     defval = flag.substr(def_start + 1);
                     defval.pop_back();
                     flag.erase(def_start, std::string::npos);
                 }
                 flag.erase(0, flag.find_first_not_of("-!"));
                 output.emplace_back(flag, defval);
             }
             return output;
         }
References split_names().
Referenced by CLI::App::_add_flag_internal().
get_names()
std::tuple<std::vector<std::string>, std::vector<std::string>, std::string> CLI::detail::get_names (const std::vector< std::string > & input) inline
Get a vector of short names, one of long names, and a single name.
Definition at line 2593 of file CLI11.hpp.
{
             std::vector<std::string> short_names;
             std::vector<std::string> long_names;
             std::string pos_name;
             for (std::string name : input) {
                 if (name.length() == 0) {
                     continue;
                 }
                 if (name.length() > 1 && name[0] == '-' && name[1] != '-') {
                     if (name.length() == 2 && valid_first_char(name[1]))
                         short_names.emplace_back(1, name[1]);
                     else
                         throw BadNameString::OneCharName(name);
                 } else if (name.length() > 2 && name.substr(0, 2) == "--") {
                     name = name.substr(2);
                     if (valid_name_string(name))
                         long_names.push_back(name);
                     else
                         throw BadNameString::BadLongName(name);
                 } else if (name == "-" || name == "--") {
                     throw BadNameString::DashesOnly(name);
                 } else {
                     if (pos_name.length() > 0)
                         throw BadNameString::MultiPositionalNames(name);
                     pos_name = name;
                 }
             }
             return std::tuple<std::vector<std::string>, std::vector<std::string>, std::string>(short_names, long_names, pos_name);
         }
References CLI::BadNameString::BadLongName(), CLI::BadNameString::DashesOnly(), CLI::BadNameString::MultiPositionalNames(), CLI::BadNameString::OneCharName(), valid_first_char(), and valid_name_string().
Referenced by CLI::Option::Option().
has_default_flag_values()
bool CLI::detail::has_default_flag_values (const std::string & flags) inline
check if the flag definitions has possible false flags
Definition at line 432 of file CLI11.hpp.
{
             return (flags.find_first_of("{!") != std::string::npos);
         }
Referenced by CLI::App::_add_flag_internal().
ini_join()
std::string CLI::detail::ini_join (const std::vector< std::string > & args, char sepChar = ',', char arrayStart = '[', char arrayEnd = ']', char stringQuote = '"', char characterQuote = '\'') inline
Comma separated join, adds quotes if needed.
Definition at line 8942 of file CLI11.hpp.
{
             std::string joined;
             if (args.size() > 1 && arrayStart != '\0') {
                 joined.push_back(arrayStart);
             }
             std::size_t start = 0;
             for (const auto& arg : args) {
                 if (start++ > 0) {
                     joined.push_back(sepChar);
                     if (isspace(sepChar) == 0) {
                         joined.push_back(' ');
                     }
                 }
                 joined.append(convert_arg_for_ini(arg, stringQuote, characterQuote));
             }
             if (args.size() > 1 && arrayEnd != '\0') {
                 joined.push_back(arrayEnd);
             }
             return joined;
         }
References convert_arg_for_ini().
Referenced by CLI::ConfigBase::to_config().
integral_conversion()
template<typename T , enable_if_t< std::is_unsigned< T >::value, detail::enabler > = detail::dummy> bool CLI::detail::integral_conversion (const std::string & input, T & output) noexcept
Convert to an unsigned integral.
Convert to a signed integral.
Definition at line 1767 of file CLI11.hpp.
{
             if (input.empty()) {
                 return false;
             }
             char* val = nullptr;
             std::uint64_t output_ll = std::strtoull(input.c_str(), &val, 0);
             output = static_cast<T>(output_ll);
             if (val == (input.c_str() + input.size()) && static_cast<std::uint64_t>(output) == output_ll) {
                 return true;
             }
             val = nullptr;
             std::int64_t output_sll = std::strtoll(input.c_str(), &val, 0);
             if (val == (input.c_str() + input.size())) {
                 output = (output_sll < 0) ? static_cast<T>(0) : static_cast<T>(output_sll);
                 return (static_cast<std::int64_t>(output) == output_sll);
             }
             return false;
         }
Referenced by lexical_cast().
is_separator()
bool CLI::detail::is_separator (const std::string & str) inline
check if a string is a container segment separator (empty or "%%")
Definition at line 393 of file CLI11.hpp.
{
             static const std::string sep("%%");
             return (str.empty() || str == sep);
         }
Referenced by CLI::Option::_validate_results().
isalpha()
bool CLI::detail::isalpha (const std::string & str) inline
Verify that str consists of letters only.
Definition at line 399 of file CLI11.hpp.
{
             return std::all_of(str.begin(), str.end(), [](char c) {
                 return std::isalpha(c, std::locale());
             });
         }
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit(), and CLI::AsNumberWithUnit::validate_mapping().
join() [1/2]
template<typename T , typename Callable , typename = typename std::enable_if<!std::is_constructible<std::string, Callable>::value>::type> std::string CLI::detail::join (const T & v, Callable func, std::string delim = ",")
Simple function to join a string from processed elements.
Definition at line 208 of file CLI11.hpp.
{
             std::ostringstream s;
             auto beg = std::begin(v);
             auto end = std::end(v);
             auto loc = s.tellp();
             while (beg != end) {
                 auto nloc = s.tellp();
                 if (nloc > loc) {
                     s << delim;
                     loc = nloc;
                 }
                 s << func(*beg++);
             }
             return s.str();
         }
join() [2/2]
template<typename T > std::string CLI::detail::join (const T & v, std::string delim = ",")
Simple function to join a string.
Definition at line 192 of file CLI11.hpp.
{
             std::ostringstream s;
             auto beg = std::begin(v);
             auto end = std::end(v);
             if (beg != end)
                 s << *beg++;
             while (beg != end) {
                 s << delim << *beg++;
             }
             return s.str();
         }
Referenced by CLI::App::_process_requirements(), CLI::Option::_reduce_results(), CLI::CheckedTransformer::CheckedTransformer(), CLI::ConfigItem::fullname(), generate_map(), generate_set(), CLI::Option::get_name(), CLI::Formatter::make_usage(), and CLI::FailureMessage::simple().
lexical_assign()
template<typename AssignTo , typename ConvertTo , enable_if_t< std::is_same< AssignTo, ConvertTo >::value &&(classify_object< AssignTo >::value==object_category::string_assignable||classify_object< AssignTo >::value==object_category::string_constructible), detail::enabler > = detail::dummy> bool CLI::detail::lexical_assign (const std::string & input, AssignTo & output)
Assign a value through lexical cast operations.
Assign a value from a lexical cast through constructing a value and move assigning it.
Assign a value converted from a string in lexical cast to the output value directly.
Assign a value through lexical cast operations Strings can be empty so we need to do a little different
Assign a value through lexical cast operations for int compatible values mainly for atomic operations on some compilers
Definition at line 2068 of file CLI11.hpp.
{
             return lexical_cast(input, output);
         }
References lexical_cast().
lexical_cast()
template<typename T , enable_if_t< classify_object< T >::value==object_category::integral_value||classify_object< T >::value==object_category::unsigned_integral, detail::enabler > = detail::dummy> bool CLI::detail::lexical_cast (const std::string & input, T & output)
Integer conversion.
Non-string parsable by a stream.
Non-string convertible from an int.
Assignable from double.
Assignable from int.
Assignable from double or int.
wrapper types
Enumerations.
String and similar constructible and copy assignment.
String and similar direct assignment.
complex
Floats.
Boolean values.
char values
Definition at line 1854 of file CLI11.hpp.
{
             return integral_conversion(input, output);
         }
References integral_conversion().
Referenced by CLI::App::add_flag(), CLI::App::add_flag_callback(), CLI::App::add_flag_function(), CLI::AsNumberWithUnit::AsNumberWithUnit(), CLI::Bound::Bound(), CLI::CheckedTransformer::CheckedTransformer(), convert_arg_for_ini(), CLI::detail::IPV4Validator::IPV4Validator(), CLI::IsMember::IsMember(), lexical_assign(), CLI::Transformer::Transformer(), and CLI::TypeValidator< DesiredType >::TypeValidator().
ltrim() [1/2]
std::string& CLI::detail::ltrim (std::string & str) inline
Trim whitespace from left of string.
Definition at line 239 of file CLI11.hpp.
{
             auto it = std::find_if(str.begin(), str.end(), [](char ch) {
                 return !std::isspace<char>(ch, std::locale());
             });
             str.erase(str.begin(), it);
             return str;
         }
Referenced by trim().
ltrim() [2/2]
std::string& CLI::detail::ltrim (std::string & str, const std::string & filter) inline
Trim anything from left of string.
Definition at line 248 of file CLI11.hpp.
{
             auto it = std::find_if(str.begin(), str.end(), [&filter](char ch) {
                 return filter.find(ch) == std::string::npos;
             });
             str.erase(str.begin(), it);
             return str;
         }
Referenced by split_program_name().
overflowCheck() [1/2]
template<typename T > std::enable_if<std::is_signed<T>::value, T>::type CLI::detail::overflowCheck (const T & a, const T & b) inline
Do a check for overflow on signed numbers.
Definition at line 3434 of file CLI11.hpp.
{
             if ((a > 0) == (b > 0)) {
                 return ((std::numeric_limits<T>::max)() / (std::abs)(a) < (std::abs)(b));
             } else {
                 return ((std::numeric_limits<T>::min)() / (std::abs)(a) > -(std::abs)(b));
             }
         }
overflowCheck() [2/2]
template<typename T > std::enable_if<!std::is_signed<T>::value, T>::type CLI::detail::overflowCheck (const T & a, const T & b) inline
Do a check for overflow on unsigned numbers.
Definition at line 3443 of file CLI11.hpp.
{
             return ((std::numeric_limits<T>::max)() / a < b);
         }
Referenced by checked_multiply().
remove_default_flag_values()
void CLI::detail::remove_default_flag_values (std::string & flags) inline
Definition at line 436 of file CLI11.hpp.
{
             auto loc = flags.find_first_of('{', 2);
             while (loc != std::string::npos) {
                 auto finish = flags.find_first_of("},", loc + 1);
                 if ((finish != std::string::npos) && (flags[finish] == '}')) {
                     flags.erase(flags.begin() + static_cast<std::ptrdiff_t>(loc), flags.begin() + static_cast<std::ptrdiff_t>(finish) + 1);
                 }
                 loc = flags.find_first_of('{', loc + 1);
             }
             flags.erase(std::remove(flags.begin(), flags.end(), '!'), flags.end());
         }
Referenced by CLI::App::_add_flag_internal().
remove_quotes()
std::string& CLI::detail::remove_quotes (std::string & str) inline
remove quotes at the front and back of a string either '"' or '\''
Definition at line 291 of file CLI11.hpp.
{
             if (str.length() > 1 && (str.front() == '"' || str.front() == '\'')) {
                 if (str.front() == str.back()) {
                     str.pop_back();
                     str.erase(str.begin(), str.begin() + 1);
                 }
             }
             return str;
         }
Referenced by CLI::ConfigBase::from_config(), and generate_parents().
remove_underscore()
std::string CLI::detail::remove_underscore (std::string str) inline
remove underscores from a string
Definition at line 414 of file CLI11.hpp.
{
             str.erase(std::remove(std::begin(str), std::end(str), '_'), std::end(str));
             return str;
         }
Referenced by CLI::Option::check_name(), CLI::App::check_name(), find_member(), and CLI::ignore_underscore().
rjoin()
template<typename T > std::string CLI::detail::rjoin (const T & v, std::string delim = ",")
Join a string in reverse order.
Definition at line 226 of file CLI11.hpp.
{
             std::ostringstream s;
             for (std::size_t start = 0; start < v.size(); start++) {
                 if (start > 0)
                     s << delim;
                 s << v[v.size() - start - 1];
             }
             return s.str();
         }
rtrim() [1/2]
std::string& CLI::detail::rtrim (std::string & str) inline
Trim whitespace from right of string.
Definition at line 257 of file CLI11.hpp.
{
             auto it = std::find_if(str.rbegin(), str.rend(), [](char ch) {
                 return !std::isspace<char>(ch, std::locale());
             });
             str.erase(it.base(), str.end());
             return str;
         }
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit(), and trim().
rtrim() [2/2]
std::string& CLI::detail::rtrim (std::string & str, const std::string & filter) inline
Trim anything from right of string.
Definition at line 266 of file CLI11.hpp.
{
             auto it = std::find_if(str.rbegin(), str.rend(), [&filter](char ch) {
                 return filter.find(ch) == std::string::npos;
             });
             str.erase(it.base(), str.end());
             return str;
         }
Referenced by split_program_name().
search() [1/2]
template<typename T , typename V , enable_if_t<!has_find< T, V >::value, detail::enabler > = detail::dummy> auto CLI::detail::search (const T & set, const V & val) -> std::pair<bool, decltype(std::begin(detail::smart_deref(set)))>
A search function.
A search function that uses the built in find function.
Definition at line 3392 of file CLI11.hpp.
{
             using element_t = typename detail::element_type<T>::type;
             auto& setref = detail::smart_deref(set);
             auto it = std::find_if(std::begin(setref), std::end(setref), [&val](decltype(*std::begin(setref)) v) {
                 return (detail::pair_adaptor<element_t>::first(v) == val);
             });
             return {(it != std::end(setref)), it};
         }
References smart_deref().
Referenced by CLI::CheckedTransformer::CheckedTransformer(), httputils::ci_contains(), CLI::IsMember::IsMember(), and CLI::Transformer::Transformer().
search() [2/2]
template<typename T , typename V > auto CLI::detail::search (const T & set, const V & val, const std::function< V(V)> & filter_function) -> std::pair<bool, decltype(std::begin(detail::smart_deref(set)))>
A search function with a filter function.
Definition at line 3411 of file CLI11.hpp.
{
             using element_t = typename detail::element_type<T>::type;
             // do the potentially faster first search
             auto res = search(set, val);
             if ((res.first) || (!(filter_function))) {
                 return res;
             }
             // if we haven't found it do the longer linear search with all the element translations
             auto& setref = detail::smart_deref(set);
             auto it = std::find_if(std::begin(setref), std::end(setref), [&](decltype(*std::begin(setref)) v) {
                 V a{detail::pair_adaptor<element_t>::first(v)};
                 a = filter_function(a);
                 return (a == val);
             });
             return {(it != std::end(setref)), it};
         }
References CLI::detail::pair_adaptor< T, _ >::first(), and smart_deref().
smart_deref() [1/2]
template<typename T , enable_if_t<!is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy> std::remove_reference<T>::type& CLI::detail::smart_deref (T & value)
Definition at line 3338 of file CLI11.hpp.
{
             return value;
         }
smart_deref() [2/2]
template<typename T , enable_if_t< is_copyable_ptr< typename std::remove_reference< T >::type >::value, detail::enabler > = detail::dummy> auto CLI::detail::smart_deref (T value) -> decltype(*value)
Definition at line 3332 of file CLI11.hpp.
{
             return *value;
         }
Referenced by CLI::CheckedTransformer::CheckedTransformer(), generate_map(), generate_set(), CLI::IsMember::IsMember(), search(), and CLI::Transformer::Transformer().
split()
std::vector<std::string> CLI::detail::split (const std::string & s, char delim) inline
Split a string by a delim.
Definition at line 174 of file CLI11.hpp.
{
             std::vector<std::string> elems;
             // Check to see if empty string, give consistent result
             if (s.empty()) {
                 elems.emplace_back();
             } else {
                 std::stringstream ss;
                 ss.str(s);
                 std::string item;
                 while (std::getline(ss, item, delim)) {
                     elems.push_back(item);
                 }
             }
             return elems;
         }
Referenced by CLI::Option::_add_result(), generate_parents(), CLI::detail::IPV4Validator::IPV4Validator(), httputils::str_split(), and httputils::str_split_last().
split_long()
bool CLI::detail::split_long (const std::string & current, std::string & name, std::string & value) inline
Definition at line 2521 of file CLI11.hpp.
{
             if (current.size() > 2 && current.substr(0, 2) == "--" && valid_first_char(current[2])) {
                 auto loc = current.find_first_of('=');
                 if (loc != std::string::npos) {
                     name = current.substr(2, loc - 2);
                     value = current.substr(loc + 1);
                 } else {
                     name = current.substr(2);
                     value = "";
                 }
                 return true;
             }
             return false;
         }
References valid_first_char().
Referenced by CLI::App::_parse_arg(), and CLI::App::_recognize().
split_names()
std::vector<std::string> CLI::detail::split_names (std::string current) inline
Definition at line 2553 of file CLI11.hpp.
{
             std::vector<std::string> output;
             std::size_t val;
             while ((val = current.find(",")) != std::string::npos) {
                 output.push_back(trim_copy(current.substr(0, val)));
                 current = current.substr(val + 1);
             }
             output.push_back(trim_copy(current));
             return output;
         }
References trim_copy().
Referenced by get_default_flag_values(), and CLI::Option::Option().
split_program_name()
std::pair<std::string, std::string> CLI::detail::split_program_name (std::string commandline) inline
Split a string into a program name and command line arguments the string is assumed to contain a file name followed by other arguments the return value contains is a pair with the first argument containing the program name and the second everything else.
Definition at line 3925 of file CLI11.hpp.
{
             // try to determine the programName
             std::pair<std::string, std::string> vals;
             trim(commandline);
             auto esp = commandline.find_first_of(' ', 1);
             while (detail::check_path(commandline.substr(0, esp).c_str()) != path_type::file) {
                 esp = commandline.find_first_of(' ', esp + 1);
                 if (esp == std::string::npos) {
                     // if we have reached the end and haven't found a valid file just assume the first argument is the
                     // program name
                     if (commandline[0] == '"' || commandline[0] == '\'' || commandline[0] == '`') {
                         bool embeddedQuote = false;
                         auto keyChar = commandline[0];
                         auto end = commandline.find_first_of(keyChar, 1);
                         while ((end != std::string::npos) && (commandline[end - 1] == '\\')) { // deal with escaped quotes
                             end = commandline.find_first_of(keyChar, end + 1);
                             embeddedQuote = true;
                         }
                         if (end != std::string::npos) {
                             vals.first = commandline.substr(1, end - 1);
                             esp = end + 1;
                             if (embeddedQuote) {
                                 vals.first = find_and_replace(vals.first, std::string("\\") + keyChar, std::string(1, keyChar));
                             }
                         } else {
                             esp = commandline.find_first_of(' ', 1);
                         }
                     } else {
                         esp = commandline.find_first_of(' ', 1);
                     }
                     break;
                 }
             }
             if (vals.first.empty()) {
                 vals.first = commandline.substr(0, esp);
                 rtrim(vals.first);
             }
             // strip the program name
             vals.second = (esp != std::string::npos) ? commandline.substr(esp + 1) : std::string{};
             ltrim(vals.second);
             return vals;
         }
References check_path(), find_and_replace(), ltrim(), rtrim(), and trim().
Referenced by CLI::App::parse().
split_short()
bool CLI::detail::split_short (const std::string & current, std::string & name, std::string & rest) inline
Definition at line 2511 of file CLI11.hpp.
{
             if (current.size() > 1 && current[0] == '-' && valid_first_char(current[1])) {
                 name = current.substr(1, 1);
                 rest = current.substr(2);
                 return true;
             }
             return false;
         }
References valid_first_char().
Referenced by CLI::App::_parse_arg(), and CLI::App::_recognize().
split_up()
std::vector<std::string> CLI::detail::split_up (std::string str, char delimiter = '\0') inline
Split a string '"one two" "three"' into 'one two', 'three' Quote characters can be ‘ ’ or "
Definition at line 490 of file CLI11.hpp.
{
             const std::string delims("\'\"`");
             auto find_ws = [delimiter](char ch) {
                 return (delimiter == '\0') ? (std::isspace<char>(ch, std::locale()) != 0) : (ch == delimiter);
             };
             trim(str);
             std::vector<std::string> output;
             bool embeddedQuote = false;
             char keyChar = ' ';
             while (!str.empty()) {
                 if (delims.find_first_of(str[0]) != std::string::npos) {
                     keyChar = str[0];
                     auto end = str.find_first_of(keyChar, 1);
                     while ((end != std::string::npos) && (str[end - 1] == '\\')) { // deal with escaped quotes
                         end = str.find_first_of(keyChar, end + 1);
                         embeddedQuote = true;
                     }
                     if (end != std::string::npos) {
                         output.push_back(str.substr(1, end - 1));
                         if (end + 2 < str.size()) {
                             str = str.substr(end + 2);
                         } else {
                             str.clear();
                         }
                     } else {
                         output.push_back(str.substr(1));
                         str = "";
                     }
                 } else {
                     auto it = std::find_if(std::begin(str), std::end(str), find_ws);
                     if (it != std::end(str)) {
                         std::string value = std::string(str.begin(), it);
                         output.push_back(value);
                         str = std::string(it + 1, str.end());
                     } else {
                         output.push_back(str);
                         str = "";
                     }
                 }
                 // transform any embedded quotes into the regular character
                 if (embeddedQuote) {
                     output.back() = find_and_replace(output.back(), std::string("\\") + keyChar, std::string(1, keyChar));
                     embeddedQuote = false;
                 }
                 trim(str);
             }
             return output;
         }
References find_and_replace(), and trim().
Referenced by CLI::ConfigBase::from_config(), and CLI::App::parse().
split_windows_style()
bool CLI::detail::split_windows_style (const std::string & current, std::string & name, std::string & value) inline
Definition at line 2537 of file CLI11.hpp.
{
             if (current.size() > 1 && current[0] == '/' && valid_first_char(current[1])) {
                 auto loc = current.find_first_of(':');
                 if (loc != std::string::npos) {
                     name = current.substr(1, loc - 1);
                     value = current.substr(loc + 1);
                 } else {
                     name = current.substr(1);
                     value = "";
                 }
                 return true;
             }
             return false;
         }
References valid_first_char().
Referenced by CLI::App::_parse_arg(), and CLI::App::_recognize().
to_flag_value()
std::int64_t CLI::detail::to_flag_value (std::string val) inline
Convert a flag into an integer value typically binary flags.
Definition at line 1807 of file CLI11.hpp.
{
             static const std::string trueString("true");
             static const std::string falseString("false");
             if (val == trueString) {
                 return 1;
             }
             if (val == falseString) {
                 return -1;
             }
             val = detail::to_lower(val);
             std::int64_t ret;
             if (val.size() == 1) {
                 if (val[0] >= '1' && val[0] <= '9') {
                     return (static_cast<std::int64_t>(val[0]) - '0');
                 }
                 switch (val[0]) {
                     case '0':
                     case 'f':
                     case 'n':
                     case '-':
                         ret = -1;
                         break;
                     case 't':
                     case 'y':
                     case '+':
                         ret = 1;
                         break;
                     default:
                         throw std::invalid_argument("unrecognized character");
                 }
                 return ret;
             }
             if (val == trueString || val == "on" || val == "yes" || val == "enable") {
                 ret = 1;
             } else if (val == falseString || val == "off" || val == "no" || val == "disable") {
                 ret = -1;
             } else {
                 ret = std::stoll(val);
             }
             return ret;
         }
References to_lower().
Referenced by CLI::Option::get_flag_value().
to_lower()
std::string CLI::detail::to_lower (std::string str) inline
Return a lower case version of a string.
Definition at line 406 of file CLI11.hpp.
{
             std::transform(std::begin(str), std::end(str), std::begin(str), [](const std::string::value_type& x) {
                 return std::tolower(x, std::locale());
             });
             return str;
         }
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit(), CLI::Option::check_name(), CLI::App::check_name(), find_member(), CLI::ConfigBase::from_config(), generate_parents(), CLI::ignore_case(), CLI::Formatter::make_subcommands(), to_flag_value(), and CLI::AsNumberWithUnit::validate_mapping().
to_string() [1/3]
template<typename T , enable_if_t< std::is_constructible< std::string, T >::value &&!std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy> std::string CLI::detail::to_string (const T & value)
Construct a string from the object.
Definition at line 1235 of file CLI11.hpp.
{
             return std::string(value);
         }
to_string() [2/3]
template<typename T , enable_if_t<!std::is_convertible< std::string, T >::value &&!std::is_constructible< std::string, T >::value &&is_ostreamable< T >::value, detail::enabler > = detail::dummy> std::string CLI::detail::to_string (T && value)
Convert an object to a string (streaming must be supported for that type)
convert a readable container to a string
If conversion is not supported, return an empty string (streaming is not supported for that type)
Definition at line 1244 of file CLI11.hpp.
{
             std::stringstream stream;
             stream << value;
             return stream.str();
         }
Referenced by CLI::ArgumentMismatch::AtLeast(), CLI::ArgumentMismatch::AtMost(), checked_to_string(), CLI::Option::get_flag_value(), CLI::App::get_subcommand(), CLI::App::get_subcommand_ptr(), CLI::Formatter::make_description(), CLI::RequiredError::Option(), CLI::ArgumentMismatch::PartialType(), CLI::RequiredError::Subcommand(), CLI::ArgumentMismatch::TypedAtLeast(), and value_string().
to_string() [3/3]
template<typename T , enable_if_t< std::is_convertible< T, std::string >::value, detail::enabler > = detail::dummy> auto CLI::detail::to_string (T && value) -> decltype(std::forward<T>(value))
Convert an object to a string (directly forward if this can become a string)
Definition at line 1227 of file CLI11.hpp.
{
             return std::forward<T>(value);
         }
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit(), CLI::Bound::Bound(), CLI::CheckedTransformer::CheckedTransformer(), database::mariadb::commands::async::MariaDBAutoCommitCommand::commandInfo(), database::mariadb::commands::async::MariaDBConnectCommand::commandInfo(), net::un::config::ConfigAddress< ConfigAddressTypeT >::ConfigAddress(), net::config::ConfigCluster::ConfigCluster(), CLI::Option::default_val(), generate_map(), core::getTickCounterAsString(), web::http::client::Request::send(), web::http::server::Response::send(), web::http::server::Response::sendFile(), web::http::client::Request::sendHeader(), web::http::server::Response::sendHeader(), net::in::SocketAddress::toString(), net::in6::SocketAddress::toString(), net::l2::SocketAddress::toString(), and net::rc::SocketAddress::toString().
trim() [1/2]
std::string& CLI::detail::trim (std::string & str) inline
Trim whitespace from string.
Definition at line 275 of file CLI11.hpp.
{
             return ltrim(rtrim(str));
         }
References ltrim(), and rtrim().
Referenced by CLI::AsNumberWithUnit::AsNumberWithUnit(), CLI::ConfigBase::from_config(), CLI::App::parse(), split_up(), and trim_copy().
trim() [2/2]
std::string& CLI::detail::trim (std::string & str, const std::string filter) inline
Trim anything from string.
Definition at line 280 of file CLI11.hpp.
{
             return ltrim(rtrim(str, filter), filter);
         }
References ltrim(), and rtrim().
Referenced by split_program_name().
trim_copy() [1/2]
std::string CLI::detail::trim_copy (const std::string & str) inline
Make a copy of the string and then trim it.
Definition at line 285 of file CLI11.hpp.
{
             std::string s = str;
             return trim(s);
         }
References trim().
Referenced by CLI::ConfigBase::from_config().
trim_copy() [2/2]
std::string CLI::detail::trim_copy (const std::string & str, const std::string & filter) inline
Make a copy of the string and then trim it, any filter string can be used (any char in string is filtered)
Definition at line 318 of file CLI11.hpp.
{
             std::string s = str;
             return trim(s, filter);
         }
References trim().
Referenced by split_names().
tuple_type_size()
template<typename T , std::size_t I> constexpr std::enable_if<I == type_count_base<T>::value, int>::type CLI::detail::tuple_type_size () constexpr
0 if the index > tuple size
Definition at line 1388 of file CLI11.hpp.
{
             return 0;
         }
type_name() [1/2]
template<typename T , std::size_t I> constexpr std::enable_if< I<type_count_base<T>::value, int>::type tuple_type_size() { return subtype_count<typename std::tuple_element<I, T>::type>::value + tuple_type_size<T, I + 1>); } template <typename T> struct type_count<T, typename std::enable_if<is_tuple_like<T>::value>::type> { static constexpr int value{tuple_type_size<T, 0>)}; }; template <typename T> struct subtype_count { static constexpr int value{is_mutable_container<T>::value ? expected_max_vector_size : type_count<T>::value}; }; template <typename T, typename Enable = void> struct type_count_min { static const int value{0}; }; template <typename T> struct type_count_min<T, typename std::enable_if<!is_mutable_container<T>::value && !is_tuple_like<T>::value && !is_wrapper<T>::value && !is_complex<T>::value && !std::is_void<T>::value>::type> { static constexpr int value{type_count<T>::value}; }; template <typename T> struct type_count_min<T, typename std::enable_if<is_complex<T>::value>::type> { static constexpr int value{1}; }; template <typename T> struct type_count_min<T, typename std::enable_if<is_wrapper<T>::value && !is_complex<T>::value && !is_tuple_like<T>::value>::type> { static constexpr int value{subtype_count_min<typename T::value_type>::value}; }; template <typename T, std::size_t I> constexpr typename std::enable_if<I == type_count_base<T>::value, int>::type tuple_type_size_min() { return 0; } template <typename T, std::size_t I> constexpr typename std::enable_if < I<type_count_base<T>::value, int>::type tuple_type_size_min() { return subtype_count_min<typename std::tuple_element<I, T>::type>::value + tuple_type_size_min<T, I + 1>); } template <typename T> struct type_count_min<T, typename std::enable_if<is_tuple_like<T>::value>::type> { static constexpr int value{tuple_type_size_min<T, 0>)}; }; template <typename T> struct subtype_count_min { static constexpr int value{is_mutable_container<T>::value ? ((type_count<T>::value < expected_max_vector_size) ? type_count<T>::value : 0) : type_count_min<T>::value}; }; template <typename T, typename Enable = void> struct expected_count { static const int value{0}; }; template <typename T> struct expected_count< T, typename std::enable_if<!is_mutable_container<T>::value && !is_wrapper<T>::value && !std::is_void<T>::value>::type> { static constexpr int value{1}; }; template <typename T> struct expected_count<T, typename std::enable_if<is_mutable_container<T>::value>::type> { static constexpr int value{expected_max_vector_size}; }; template <typename T> struct expected_count<T, typename std::enable_if<!is_mutable_container<T>::value && is_wrapper<T>::value>::type> { static constexpr int value{expected_count<typename T::value_type>::value}; }; enum class object_category : int { char_value = 1, integral_value = 2, unsigned_integral = 4, enumeration = 6, boolean_value = 8, floating_point = 10, number_constructible = 12, double_constructible = 14, integer_constructible = 16, string_assignable = 23, string_constructible = 24, other = 45, wrapper_value = 50, complex_number = 60, tuple_value = 70, container_value = 80, }; template <typename T, typename Enable = void> struct classify_object { static constexpr object_category value{object_category::other}; }; template <typename T> struct classify_object<T, typename std::enable_if<std::is_integral<T>::value && !std::is_same<T, char>::value && std::is_signed<T>::value && !is_bool<T>::value && !std::is_enum<T>::value>::type> { static constexpr object_category value{object_category::integral_value}; }; template <typename T> struct classify_object<T, typename std::enable_if<std::is_integral<T>::value && std::is_unsigned<T>::value && !std::is_same<T, char>::value && !is_bool<T>::value>::type> { static constexpr object_category value{object_category::unsigned_integral}; }; template <typename T> struct classify_object<T, typename std::enable_if<std::is_same<T, char>::value && !std::is_enum<T>::value>::type> { static constexpr object_category value{object_category::char_value}; }; template <typename T> struct classify_object<T, typename std::enable_if<is_bool<T>::value>::type> { static constexpr object_category value{object_category::boolean_value}; }; template <typename T> struct classify_object<T, typename std::enable_if<std::is_floating_point<T>::value>::type> { static constexpr object_category value{object_category::floating_point}; }; template <typename T> struct classify_object<T, typename std::enable_if<!std::is_floating_point<T>::value && !std::is_integral<T>::value && std::is_assignable<T&, std::string>::value>::type> { static constexpr object_category value{object_category::string_assignable}; }; template <typename T> struct classify_object<T, typename std::enable_if<!std::is_floating_point<T>::value && !std::is_integral<T>::value && !std::is_assignable<T&, std::string>::value && (type_count<T>::value == 1) && std::is_constructible<T, std::string>::value>::type> { static constexpr object_category value{object_category::string_constructible}; }; template <typename T> struct classify_object<T, typename std::enable_if<std::is_enum<T>::value>::type> { static constexpr object_category value{object_category::enumeration}; }; template <typename T> struct classify_object<T, typename std::enable_if<is_complex<T>::value>::type> { static constexpr object_category value{object_category::complex_number}; }; template <typename T> struct uncommon_type { using type = typename std::conditional<!std::is_floating_point<T>::value && !std::is_integral<T>::value && !std::is_assignable<T&, std::string>::value && !std::is_constructible<T, std::string>::value && !is_complex<T>::value && !is_mutable_container<T>::value && !std::is_enum<T>::value, std::true_type, std::false_type>::type; static constexpr bool value = type::value; }; template <typename T> struct classify_object<T, typename std::enable_if<(!is_mutable_container<T>::value && is_wrapper<T>::value && !is_tuple_like<T>::value && uncommon_type<T>::value)>::type> { static constexpr object_category value{object_category::wrapper_value}; }; template <typename T> struct classify_object< T, typename std::enable_if<uncommon_type<T>::value && type_count<T>::value == 1 && !is_wrapper<T>::value && is_direct_constructible<T, double>::value && is_direct_constructible<T, int>::value>::type> { static constexpr object_category value{object_category::number_constructible}; }; template <typename T> struct classify_object< T, typename std::enable_if<uncommon_type<T>::value && type_count<T>::value == 1 && !is_wrapper<T>::value && !is_direct_constructible<T, double>::value && is_direct_constructible<T, int>::value>::type> { static constexpr object_category value{object_category::integer_constructible}; }; template <typename T> struct classify_object< T, typename std::enable_if<uncommon_type<T>::value && type_count<T>::value == 1 && !is_wrapper<T>::value && is_direct_constructible<T, double>::value && !is_direct_constructible<T, int>::value>::type> { static constexpr object_category value{object_category::double_constructible}; }; template <typename T> struct classify_object< T, typename std::enable_if<is_tuple_like<T>::value && ((type_count<T>::value >= 2 && !is_wrapper<T>::value) || (uncommon_type<T>::value && !is_direct_constructible<T, double>::value && !is_direct_constructible<T, int>::value))>::type> { static constexpr object_category value{object_category::tuple_value}; }; template <typename T> struct classify_object<T, typename std::enable_if<is_mutable_container<T>::value>::type> { static constexpr object_category value{object_category::container_value}; }; template <typename T, enable_if_t<classify_object<T>::value == object_category::char_value, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "CHAR"; } template <typename T, enable_if_t<classify_object<T>::value == object_category::integral_value || classify_object<T>::value == object_category::integer_constructible, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "INT"; } template <typename T, enable_if_t<classify_object<T>::value == object_category::unsigned_integral, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "UINT"; } template <typename T, enable_if_t<classify_object<T>::value == object_category::floating_point || classify_object<T>::value == object_category::number_constructible || classify_object<T>::value == object_category::double_constructible, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "FLOAT"; } template <typename T, enable_if_t<classify_object<T>::value == object_category::enumeration, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "ENUM"; } template <typename T, enable_if_t<classify_object<T>::value == object_category::boolean_value, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "BOOLEAN"; } template <typename T, enable_if_t<classify_object<T>::value == object_category::complex_number, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "COMPLEX"; } template <typename T, enable_if_t<classify_object<T>::value >= object_category::string_assignable && classify_object<T>::value <= object_category::other, detail::enabler> = detail::dummy> constexpr const char* type_name() { return "TEXT"; } template <typename T, enable_if_t<classify_object<T>::value == object_category::tuple_value && type_count_base<T>::value >= 2, detail::enabler> = detail::dummy> std::string type_name(); template <typename T, enable_if_t<classify_object<T>::value == object_category::container_value || classify_object<T>::value == object_category::wrapper_value, detail::enabler> = detail::dummy> std::string type_name(); template <typename T, enable_if_t<classify_object<T>::value == object_category::tuple_value && type_count_base<T>::value == 1, detail::enabler> = detail::dummy> inline std::string type_name() { return type_name<typename std::decay<typename std::tuple_element<0, T>::type>::type>); } template <typename T, std::size_t I> inline typename std::enable_if<I == type_count_base<T>::value, std::string>::type tuple_name() { return std::string{}; } template <typename T, std::size_t I> inline typename std::enable_if<(I < type_count_base<T>::value), std::string>::type tuple_name() { std::string str = std::string(type_name<typename std::decay<typename std::tuple_element<I, T>::type>::type>)) + ',' + tuple_name<T, I + 1>); if (str.back() == ',') str.pop_back(); return str; } template <typename T, enable_if_t<classify_object<T>::value == object_category::tuple_value && type_count_base<T>::value >= 2, detail::enabler> > std::string CLI::detail::type_name () inline constexpr
Recursively generate the tuple type name.
Definition at line 1748 of file CLI11.hpp.
{
             auto tname = std::string(1, '[') + tuple_name<T, 0>();
             tname.push_back(']');
             return tname;
         }
type_name() [2/2]
template<typename T , enable_if_t< classify_object< T >::value==object_category::container_value||classify_object< T >::value==object_category::wrapper_value, detail::enabler > > std::string CLI::detail::type_name () inline
get the type name for a type that has a value_type member
Definition at line 1759 of file CLI11.hpp.
{
             return type_name<typename T::value_type>();
         }
valid_alias_name_string()
bool CLI::detail::valid_alias_name_string (const std::string & str) inline
Verify an app name.
Definition at line 387 of file CLI11.hpp.
{
             static const std::string badChars(std::string("\n") + '\0');
             return (str.find_first_of(badChars) == std::string::npos);
         }
Referenced by CLI::App::add_option_group(), CLI::App::alias(), and CLI::OptionBase< CRTP >::group().
valid_first_char()
template<typename T > bool CLI::detail::valid_first_char (T c)
Verify the first character of an option
is a trigger character, ! has special meaning and new lines would just be annoying to deal with
Definition at line 361 of file CLI11.hpp.
{
             return ((c != '-') && (c != '!') && (c != ' ') && c != '\n');
         }
Referenced by CLI::App::add_subcommand(), get_names(), split_long(), split_short(), split_windows_style(), and valid_name_string().
valid_later_char()
template<typename T > bool CLI::detail::valid_later_char (T c)
Verify following characters of an option.
Definition at line 367 of file CLI11.hpp.
{
             // = and : are value separators, { has special meaning for option defaults,
             // and \n would just be annoying to deal with in many places allowing space here has too much potential for
             // inadvertent entry errors and bugs
             return ((c != '=') && (c != ':') && (c != '{') && (c != ' ') && c != '\n');
         }
Referenced by CLI::App::add_subcommand(), and valid_name_string().
valid_name_string()
bool CLI::detail::valid_name_string (const std::string & str) inline
Verify an option/subcommand name.
Definition at line 375 of file CLI11.hpp.
{
             if (str.empty() || !valid_first_char(str[0])) {
                 return false;
             }
             auto e = str.end();
             for (auto c = str.begin() + 1; c != e; ++c)
                 if (!valid_later_char(*c))
                     return false;
             return true;
         }
References valid_first_char(), and valid_later_char().
Referenced by CLI::App::add_subcommand(), and get_names().
value_string() [1/2]
template<typename T , enable_if_t< std::is_arithmetic< T >::value, detail::enabler > = detail::dummy> std::string CLI::detail::value_string (const T & value)
get a string as a convertible value for arithmetic types
get a string as a convertible value for enumerations
Definition at line 1290 of file CLI11.hpp.
{
             return std::to_string(value);
         }
References to_string().
Referenced by CLI::CheckedTransformer::CheckedTransformer(), CLI::IsMember::IsMember(), and CLI::Transformer::Transformer().
value_string() [2/2]
template<typename T , enable_if_t<!std::is_enum< T >::value &&!std::is_arithmetic< T >::value, detail::enabler > = detail::dummy> auto CLI::detail::value_string (const T & value) -> decltype(to_string(value))
for other types just use the regular to_string function
Definition at line 1300 of file CLI11.hpp.
{
             return to_string(value);
         }
References to_string().
Variable Documentation
dummy
constexpr enabler CLI::detail::dummy = {} constexpr
An instance to use in EnableIf.
Definition at line 950 of file CLI11.hpp.
expected_max_vector_size
constexpr int CLI::detail::expected_max_vector_size {1 << 29} constexpr
a constant defining an expected max vector size defined to be a big number that could be multiplied by 4 and not produce overflow for some expected uses
Definition at line 171 of file CLI11.hpp.
Referenced by CLI::App::_parse_arg(), CLI::App::_validate(), CLI::Option::expected(), CLI::Option::get_items_expected_max(), CLI::Formatter::make_option_opts(), CLI::Formatter::make_option_usage(), CLI::Option::multi_option_policy(), and CLI::Option::type_size().