snode.c: CLI::detail::AppFriend Struct Reference
CLI::detail::AppFriend Struct Reference
This class is simply to allow tests access to App's protected functions.
#include <CLI11.hpp>
Static Public Member Functions
template<typename... Args>
static auto parse_arg (App *app, Args &&... args) -> typename std::result_of< decltype(&App::_parse_arg)(App, Args...)>::type
Wrap _parse_short, perfectly forward arguments and return.
template<typename... Args>
static auto parse_subcommand (App *app, Args &&... args) -> typename std::result_of< decltype(&App::_parse_subcommand)(App, Args...)>::type
Wrap _parse_subcommand, perfectly forward arguments and return.
static App * get_fallthrough_parent (App *app)
Wrap the fallthrough parent function to make sure that is working correctly.
Detailed Description
This class is simply to allow tests access to App's protected functions.
Definition at line 8856 of file CLI11.hpp.
Member Function Documentation
get_fallthrough_parent()
static App* CLI::detail::AppFriend::get_fallthrough_parent (App * app) inline static
Wrap the fallthrough parent function to make sure that is working correctly.
Definition at line 8885 of file CLI11.hpp.
{
                 return app->_get_fallthrough_parent();
             }
References CLI::App::_get_fallthrough_parent().
parse_arg()
template<typename... Args> static auto CLI::detail::AppFriend::parse_arg (App * app, Args &&... args) -> typename std::result_of<decltype (&App::_parse_arg)(App, Args...)>::type inline static
Wrap _parse_short, perfectly forward arguments and return.
Definition at line 8873 of file CLI11.hpp.
{
                 return app->_parse_arg(std::forward<Args>(args)...);
             }
References CLI::App::_parse_arg().
parse_subcommand()
template<typename... Args> static auto CLI::detail::AppFriend::parse_subcommand (App * app, Args &&... args) -> typename std::result_of<decltype (&App::_parse_subcommand)(App, Args...)>::type inline static
Wrap _parse_subcommand, perfectly forward arguments and return.
Definition at line 8879 of file CLI11.hpp.
{
                 return app->_parse_subcommand(std::forward<Args>(args)...);
             }
References CLI::App::_parse_subcommand().
The documentation for this struct was generated from the following file:
utils/CLI11.hpp