snode.c: CLI::ConfigItem Struct Reference
CLI::ConfigItem Struct Reference
Holds values to load into Options.
#include <CLI11.hpp>
Public Member Functions
std::string fullname () const
The list of parents and name joined by ".".
Public Attributes
std::vector< std::string > parents {}
This is the list of parents.
std::string name {}
This is the name.
std::vector< std::string > inputs {}
Listing of inputs.
Detailed Description
Holds values to load into Options.
Definition at line 2630 of file CLI11.hpp.
Member Function Documentation
fullname()
std::string CLI::ConfigItem::fullname () const inline
The list of parents and name joined by ".".
Definition at line 2641 of file CLI11.hpp.
{
             std::vector<std::string> tmp = parents;
             tmp.emplace_back(name);
             return detail::join(tmp, ".");
         }
References CLI::detail::join().
Referenced by CLI::App::_parse_single_config(), and CLI::Config::to_flag().
Member Data Documentation
inputs
std::vector<std::string> CLI::ConfigItem::inputs {}
Listing of inputs.
Definition at line 2638 of file CLI11.hpp.
Referenced by CLI::App::_parse_single_config(), and CLI::Config::to_flag().
name
std::string CLI::ConfigItem::name {}
This is the name.
Definition at line 2635 of file CLI11.hpp.
Referenced by CLI::App::_parse_single_config().
parents
std::vector<std::string> CLI::ConfigItem::parents {}
This is the list of parents.
Definition at line 2632 of file CLI11.hpp.
Referenced by CLI::App::_parse_single_config().
The documentation for this struct was generated from the following file:
utils/CLI11.hpp